// apps/mobile/.backup_vue3_converted/pages/videos/creator/revenue/index.vue
<template>
  <view class="min-h-screen bg-background pb-20">
    <!-- 顶部导航 -->
    <view class="sticky top-0 z-10 bg-background border-b border-border">
      <view class="flex items-center justify-between px-4 h-14">
        <view class="flex items-center gap-2">
          <view @click="goBack" class="p-1">
            <text class="text-xl text-foreground">←</text>
          </view>
          <text class="text-lg font-semibold text-foreground">创作者收益</text>
        </view>
        <view @click="goTo('/pages/wallet/withdraw/index')" class="flex items-center gap-1 text-xs text-primary">
          <text></text>
          <text>提现</text>
        </view>
      </view>
    </view>

    <!-- 加载骨架 -->
    <view v-if="loading" class="p-4 space-y-4">
      <view class="h-40 bg-secondary rounded-xl animate-pulse" />
      <view class="h-48 bg-secondary rounded-xl animate-pulse" />
      <view class="h-32 bg-secondary rounded-xl animate-pulse" />
    </view>

    <!-- 错误 -->
    <view v-else-if="error" class="p-4">
      <view class="flex flex-col items-center justify-center py-16">
        <text class="text-4xl mb-3">😞</text>
        <text class="text-sm text-muted-foreground mb-4">{{ error }}</text>
        <view @click="fetchData" class="px-4 py-2 bg-primary text-white rounded-full text-xs">重试</view>
      </view>
    </view>

    <!-- 空状态 -->
    <view v-else-if="!data" class="p-4">
      <view class="flex flex-col items-center justify-center py-16">
        <text class="text-4xl mb-3">📊</text>
        <text class="text-sm text-muted-foreground">暂无收益数据</text>
      </view>
    </view>

    <view v-else class="p-4 space-y-4">
      <!-- 收益总览卡片 -->
      <view class="p-5 rounded-xl bg-gradient-to-br from-primary/10 to-primary/5 border border-primary/20">
        <view class="text-center mb-4">
          <text class="text-sm text-muted-foreground block mb-1">累计收益（元）</text>
          <text class="text-3xl font-bold text-primary">{{ data.overview.totalRevenue.toFixed(2) }}</text>
        </view>

        <view class="grid grid-cols-3 gap-4 pt-4 border-t border-primary/10">
          <view class="text-center">
            <text class="text-xs text-muted-foreground block mb-1">本月收益</text>
            <text class="font-semibold text-foreground">{{ data.overview.monthRevenue.toLocaleString() }}</text>
            <view :class="['flex items-center justify-center text-xs mt-1', data.overview.monthGrowthRate >= 0 ? 'text-green-600' : 'text-red-600']">
              <text>{{ data.overview.monthGrowthRate >= 0 ? '📈' : '📉' }}</text>
              <text>{{ Math.abs(data.overview.monthGrowthRate) }}%</text>
            </view>
          </view>
          <view class="text-center">
            <text class="text-xs text-muted-foreground block mb-1">可提现</text>
            <text class="font-semibold text-primary">{{ data.overview.withdrawable.toLocaleString() }}</text>
          </view>
          <view class="text-center">
            <text class="text-xs text-muted-foreground block mb-1">待结算</text>
            <text class="font-semibold text-amber-600">{{ data.overview.pending.toLocaleString() }}</text>
          </view>
        </view>
      </view>

      <!-- 收益趋势 -->
      <view class="bg-white rounded-xl border border-border p-4">
        <view class="flex items-center justify-between mb-2">
          <text class="font-medium text-foreground">收益趋势</text>
          <text class="text-xs text-muted-foreground">近30天</text>
        </view>
        <view class="relative h-32 mt-4">
          <svg class="w-full h-full" viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <linearGradient id="trendGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" stop-color="#C41E3A" stop-opacity="0.3" />
                <stop offset="100%" stop-color="#C41E3A" stop-opacity="0" />
              </linearGradient>
            </defs>
            <path :d="trendAreaPath" fill="url(#trendGradient)" />
            <path :d="trendLinePath" fill="none" stroke="#C41E3A" stroke-width="2" />
          </svg>
          <view class="flex justify-between mt-2 text-xs text-muted-foreground">
            <text>{{ data.trend[0]?.date.slice(5) }}</text>
            <text>{{ data.trend[Math.floor(data.trend.length / 2)]?.date.slice(5) }}</text>
            <text>{{ data.trend[data.trend.length - 1]?.date.slice(5) }}</text>
          </view>
        </view>
      </view>

      <!-- 收益来源构成 -->
      <view class="bg-white rounded-xl border border-border p-4">
        <view class="flex items-center justify-between mb-4">
          <text class="font-medium text-foreground">收益来源</text>
          <view class="flex items-center gap-0.5 text-xs text-muted-foreground">
            <text>查看详情</text>
            <text>›</text>
          </view>
        </view>

        <view class="space-y-3">
          <view
            v-for="source in data.sources" :key="source.type"
            @click="selectedType = source.type"
            class="flex items-center -mx-2 px-2 py-1 rounded-lg"
          >
            <view :class="['w-8 h-8 rounded-lg flex items-center justify-center text-white mr-3', sourceColors[source.type]]">
              <text>{{ sourceIcons[source.type] }}</text>
            </view>
            <view class="flex-1 min-w-0">
              <view class="flex items-center justify-between mb-1">
                <text class="text-sm text-foreground">{{ sourceNames[source.type] }}</text>
                <text class="font-medium text-foreground">{{ source.amount.toLocaleString() }}</text>
              </view>
              <view class="flex items-center">
                <view class="flex-1 h-1.5 bg-secondary rounded-full overflow-hidden mr-2">
                  <view :class="['h-full rounded-full', sourceColors[source.type]]" :style="{ width: source.percentage + '%' }" />
                </view>
                <text class="text-xs text-muted-foreground w-10">{{ source.percentage }}%</text>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 收益明细 -->
      <view class="bg-white rounded-xl border border-border p-4">
        <text class="font-medium text-foreground block mb-4">收益明细</text>

        <!-- 类型筛选 -->
        <view class="flex flex-wrap gap-1 mb-4">
          <view
            @click="selectedType = 'all'"
            :class="['px-3 py-1.5 rounded-full text-xs font-medium', selectedType === 'all' ? 'bg-primary text-white' : 'bg-secondary text-foreground']"
          >
            全部
          </view>
          <view
            v-for="(name, type) in sourceNames" :key="type"
            @click="selectedType = type"
            :class="['px-3 py-1.5 rounded-full text-xs font-medium', selectedType === type ? 'bg-primary text-white' : 'bg-secondary text-foreground']"
          >
            {{ name }}
          </view>
        </view>

        <!-- 明细列表 -->
        <view v-if="detailsLoading" class="space-y-3">
          <view v-for="i in 3" :key="i" class="flex items-center gap-3">
            <view class="w-10 h-10 rounded-lg bg-secondary animate-pulse" />
            <view class="flex-1 space-y-2">
              <view class="h-4 bg-secondary rounded animate-pulse w-3/4" />
              <view class="h-3 bg-secondary rounded animate-pulse w-1/2" />
            </view>
          </view>
        </view>

        <view v-else-if="details.length === 0" class="py-8 text-center">
          <text class="text-sm text-muted-foreground">暂无收益记录</text>
        </view>

        <view v-else class="space-y-3">
          <view v-for="item in details" :key="item.id" class="flex items-start p-3 bg-secondary/30 rounded-xl">
            <view :class="['w-10 h-10 rounded-lg flex items-center justify-center text-white mr-3 flex-shrink-0', sourceColors[item.type]]">
              <text>{{ sourceIcons[item.type] }}</text>
            </view>
            <view class="flex-1 min-w-0">
              <view class="flex items-start justify-between mb-1">
                <text class="text-sm font-medium text-foreground truncate pr-2">{{ item.title }}</text>
                <text class="text-primary font-semibold whitespace-nowrap">+{{ item.amount }}</text>
              </view>
              <view class="flex items-center justify-between">
                <view class="flex items-center text-xs text-muted-foreground">
                  <view v-if="item.buyer" class="flex items-center mr-2">
                    <view class="w-4 h-4 rounded-full bg-[#E8E0D5] flex items-center justify-center mr-1">
                      <text class="text-[8px]">{{ item.buyer.nickname[0] }}</text>
                    </view>
                    <text>{{ item.buyer.nickname }}</text>
                  </view>
                  <text>{{ item.createdAt }}</text>
                </view>
                <view :class="['text-xs px-1.5 rounded', statusBadgeClass(item.status)]">
                  <text>{{ statusLabel(item.status) }}</text>
                </view>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

const loading = ref(true)
const error = ref<string | null>(null)
const detailsLoading = ref(false)
const selectedType = ref<string>('all')

const sourceIcons: Record<string, string> = {
  course: '', question: '❓', reward: '🎁', tip: '', article: '', live: '📡',
}
const sourceColors: Record<string, string> = {
  course: 'bg-blue-500', question: 'bg-green-500', reward: 'bg-orange-500', tip: 'bg-pink-500', article: 'bg-purple-500', live: 'bg-red-500',
}
const sourceNames: Record<string, string> = {
  course: '课程', question: '问答', reward: '打赏', tip: '赞赏', article: '文章', live: '直播',
}

interface Overview {
  totalRevenue: number
  monthRevenue: number
  monthGrowthRate: number
  withdrawable: number
  pending: number
}

interface TrendPoint { date: string; amount: number }
interface SourceItem { type: string; amount: number; percentage: number }
interface DetailItem { id: string; type: string; title: string; amount: number; buyer?: { nickname: string }; createdAt: string; status: string }

interface RevenueData {
  overview: Overview
  trend: TrendPoint[]
  sources: SourceItem[]
}

const data = ref<RevenueData | null>(null)
const details = ref<DetailItem[]>([])

const trendAreaPath = computed(() => {
  if (!data.value?.trend.length) return ''
  const t = data.value.trend
  const max = Math.max(...t.map(p => p.amount))
  const min = Math.min(...t.map(p => p.amount))
  const range = max - min || 1
  let d = `M0,${100 - ((t[0].amount - min) / range) * 80}`
  t.forEach((p, i) => {
    const x = (i / (t.length - 1)) * 300
    const y = 100 - ((p.amount - min) / range) * 80
    d += ` L${x},${y}`
  })
  d += ' L300,100 L0,100 Z'
  return d
})

const trendLinePath = computed(() => {
  if (!data.value?.trend.length) return ''
  const t = data.value.trend
  const max = Math.max(...t.map(p => p.amount))
  const min = Math.min(...t.map(p => p.amount))
  const range = max - min || 1
  let d = `M0,${100 - ((t[0].amount - min) / range) * 80}`
  t.forEach((p, i) => {
    const x = (i / (t.length - 1)) * 300
    const y = 100 - ((p.amount - min) / range) * 80
    d += ` L${x},${y}`
  })
  return d
})

function statusLabel(s: string) {
  const map: Record<string, string> = { settled: '已结算', pending: '待结算', frozen: '冻结中' }
  return map[s] || s
}

function statusBadgeClass(s: string) {
  const map: Record<string, string> = {
    settled: 'text-green-600 bg-green-50 border border-green-200',
    pending: 'text-orange-600 bg-orange-50 border border-orange-200',
    frozen: 'text-blue-600 bg-blue-50 border border-blue-200',
  }
  return map[s] || ''
}

async function fetchData() {
  loading.value = true
  error.value = null
  // 模拟数据
  await new Promise(r => setTimeout(r, 600))
  data.value = {
    overview: { totalRevenue: 186520.00, monthRevenue: 28450, monthGrowthRate: 12.5, withdrawable: 18650.00, pending: 3200.00 },
    trend: [
      { date: '2024-06-01', amount: 800 }, { date: '2024-06-05', amount: 1200 }, { date: '2024-06-10', amount: 950 },
      { date: '2024-06-15', amount: 1500 }, { date: '2024-06-20', amount: 1800 }, { date: '2024-06-25', amount: 1350 },
      { date: '2024-06-30', amount: 2100 },
    ],
    sources: [
      { type: 'course', amount: 85000, percentage: 46 },
      { type: 'question', amount: 42000, percentage: 23 },
      { type: 'live', amount: 28000, percentage: 15 },
      { type: 'reward', amount: 15000, percentage: 8 },
      { type: 'article', amount: 10000, percentage: 5 },
      { type: 'tip', amount: 6520, percentage: 3 },
    ],
  }
  loading.value = false
}

async function fetchDetails() {
  detailsLoading.value = true
  await new Promise(r => setTimeout(r, 400))
  const all: DetailItem[] = [
    { id: '1', type: 'course', title: '八字命理精讲课程', amount: 1280, buyer: { nickname: '山河客' }, createdAt: '2024-06-28', status: 'settled' },
    { id: '2', type: 'live', title: '直播间打赏', amount: 520, buyer: { nickname: '星空旅人' }, createdAt: '2024-06-28', status: 'settled' },
    { id: '3', type: 'question', title: '紫微斗数排盘咨询', amount: 88, buyer: { nickname: '云上墨' }, createdAt: '2024-06-27', status: 'pending' },
    { id: '4', type: 'reward', title: '收到打赏', amount: 200, buyer: { nickname: '问道者' }, createdAt: '2024-06-27', status: 'settled' },
    { id: '5', type: 'article', title: '奇门遁甲入门文章', amount: 360, createdAt: '2024-06-26', status: 'frozen' },
    { id: '6', type: 'tip', title: '用户赞赏', amount: 66, createdAt: '2024-06-25', status: 'settled' },
  ]
  details.value = selectedType.value === 'all' ? all : all.filter(d => d.type === selectedType.value)
  detailsLoading.value = false
}

onMounted(() => {
  fetchData()
  fetchDetails()
})

function goBack() { uni.navigateBack() }
function goTo(url: string) { uni.navigateTo({ url }) }
</script>

// proto-ref-app/creator/revenue/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ChevronLeft, TrendingUp, TrendingDown, Wallet, ChevronRight, BookOpen, HelpCircle, Gift, Heart, FileText, Radio } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { DataState } from '@/components/data-state'
import { getCreatorRevenueData, getRevenueDetails } from '@/lib/api/creator-revenue'
import { REVENUE_SOURCE_NAMES } from '@/lib/types/creator-revenue'
import type { CreatorRevenueData, RevenueDetailItem, RevenueSourceType } from '@/lib/types/creator-revenue'

// 收益来源图标映射
const SOURCE_ICONS: Record<RevenueSourceType, React.ReactNode> = {
  course: <BookOpen className="w-4 h-4" />,
  question: <HelpCircle className="w-4 h-4" />,
  reward: <Gift className="w-4 h-4" />,
  tip: <Heart className="w-4 h-4" />,
  article: <FileText className="w-4 h-4" />,
  live: <Radio className="w-4 h-4" />,
}

// 收益来源颜色映射
const SOURCE_COLORS: Record<RevenueSourceType, string> = {
  course: 'bg-blue-500',
  question: 'bg-green-500',
  reward: 'bg-orange-500',
  tip: 'bg-pink-500',
  article: 'bg-purple-500',
  live: 'bg-red-500',
}

export default function CreatorRevenuePage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [data, setData] = useState<CreatorRevenueData | null>(null)
  const [details, setDetails] = useState<RevenueDetailItem[]>([])
  const [detailsLoading, setDetailsLoading] = useState(false)
  const [selectedType, setSelectedType] = useState<RevenueSourceType | 'all'>('all')

  // 加载收益数据
  useEffect(() => {
    async function fetchData() {
      setLoading(true)
      try {
        const res = await getCreatorRevenueData()
        if (res.code === 200) {
          setData(res.data)
        } else {
          setError(res.message)
        }
      } catch {
        setError('加载失败，请重试')
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  // 加载收益明细
  useEffect(() => {
    async function fetchDetails() {
      setDetailsLoading(true)
      try {
        const res = await getRevenueDetails(1, 20, selectedType === 'all' ? undefined : selectedType)
        if (res.code === 200) {
          setDetails(res.data.list)
        }
      } catch {
        // ignore
      } finally {
        setDetailsLoading(false)
      }
    }
    fetchDetails()
  }, [selectedType])

  // 计算趋势图数据
  const renderTrendChart = () => {
    if (!data?.trend.length) return null
    const maxAmount = Math.max(...data.trend.map(p => p.amount))
    const minAmount = Math.min(...data.trend.map(p => p.amount))
    const range = maxAmount - minAmount || 1

    return (
      <div className="relative h-32 mt-4">
        <svg className="w-full h-full" viewBox="0 0 300 100" preserveAspectRatio="none">
          <defs>
            <linearGradient id="trendGradient" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor="#C41E3A" stopOpacity="0.3" />
              <stop offset="100%" stopColor="#C41E3A" stopOpacity="0" />
            </linearGradient>
          </defs>
          {/* 填充区域 */}
          <path
            d={`M0,${100 - ((data.trend[0].amount - minAmount) / range) * 80} ${data.trend.map((p, i) => {
              const x = (i / (data.trend.length - 1)) * 300
              const y = 100 - ((p.amount - minAmount) / range) * 80
              return `L${x},${y}`
            }).join(' ')} L300,100 L0,100 Z`}
            fill="url(#trendGradient)"
          />
          {/* 线条 */}
          <path
            d={`M0,${100 - ((data.trend[0].amount - minAmount) / range) * 80} ${data.trend.map((p, i) => {
              const x = (i / (data.trend.length - 1)) * 300
              const y = 100 - ((p.amount - minAmount) / range) * 80
              return `L${x},${y}`
            }).join(' ')}`}
            fill="none"
            stroke="#C41E3A"
            strokeWidth="2"
          />
        </svg>
        {/* X轴标签 */}
        <div className="flex justify-between mt-2 text-xs text-muted-foreground">
          <span>{data.trend[0]?.date.slice(5)}</span>
          <span>{data.trend[Math.floor(data.trend.length / 2)]?.date.slice(5)}</span>
          <span>{data.trend[data.trend.length - 1]?.date.slice(5)}</span>
        </div>
      </div>
    )
  }

  // 状态标签样式
  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'settled':
        return <Badge variant="outline" className="text-green-600 border-green-200 bg-green-50">已结算</Badge>
      case 'pending':
        return <Badge variant="outline" className="text-orange-600 border-orange-200 bg-orange-50">待结算</Badge>
      case 'frozen':
        return <Badge variant="outline" className="text-blue-600 border-blue-200 bg-blue-50">冻结中</Badge>
      default:
        return null
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between px-4 h-14">
          <Button variant="ghost" size="icon" onClick={() => router.back()}>
            <ChevronLeft className="w-5 h-5" />
          </Button>
          <h1 className="text-lg font-semibold">创作者收益</h1>
          <Button 
            variant="ghost" 
            size="sm"
            className="text-primary"
            onClick={() => router.push('/wallet/withdraw')}
          >
            <Wallet className="w-4 h-4 mr-1" />
            提现
          </Button>
        </div>
      </header>

      <DataState
        loading={loading}
        error={error}
        empty={!data}
        emptyMessage="暂无收益数据"
        onRetry={() => window.location.reload()}
        skeleton={
          <div className="p-4 space-y-4">
            <div className="h-40 bg-muted rounded-xl animate-pulse" />
            <div className="h-48 bg-muted rounded-xl animate-pulse" />
            <div className="h-32 bg-muted rounded-xl animate-pulse" />
          </div>
        }
      >
        <div className="p-4 space-y-4 pb-20">
          {/* 收益总览卡片 */}
          <Card className="p-5 bg-gradient-to-br from-primary/10 to-primary/5 border-primary/20">
            <div className="text-center mb-4">
              <p className="text-sm text-muted-foreground mb-1">累计收益（元）</p>
              <p className="text-3xl font-bold text-primary">
                {data?.overview.totalRevenue.toLocaleString('zh-CN', { minimumFractionDigits: 2 })}
              </p>
            </div>
            
            <div className="grid grid-cols-3 gap-4 pt-4 border-t border-primary/10">
              <div className="text-center">
                <p className="text-xs text-muted-foreground mb-1">本月收益</p>
                <p className="font-semibold">{data?.overview.monthRevenue.toLocaleString()}</p>
                <div className={`flex items-center justify-center text-xs mt-1 ${(data?.overview.monthGrowthRate ?? 0) >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                  {(data?.overview.monthGrowthRate ?? 0) >= 0 ? (
                    <TrendingUp className="w-3 h-3 mr-0.5" />
                  ) : (
                    <TrendingDown className="w-3 h-3 mr-0.5" />
                  )}
                  {Math.abs(data?.overview.monthGrowthRate ?? 0)}%
                </div>
              </div>
              <div className="text-center">
                <p className="text-xs text-muted-foreground mb-1">可提现</p>
                <p className="font-semibold text-primary">{data?.overview.withdrawable.toLocaleString()}</p>
              </div>
              <div className="text-center">
                <p className="text-xs text-muted-foreground mb-1">待结算</p>
                <p className="font-semibold text-orange-600">{data?.overview.pending.toLocaleString()}</p>
              </div>
            </div>
          </Card>

          {/* 收益趋势 */}
          <Card className="p-4">
            <div className="flex items-center justify-between mb-2">
              <h3 className="font-medium">收益趋势</h3>
              <span className="text-xs text-muted-foreground">近30天</span>
            </div>
            {renderTrendChart()}
          </Card>

          {/* 收益来源构成 */}
          <Card className="p-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-medium">收益来源</h3>
              <Button 
                variant="ghost" 
                size="sm" 
                className="text-xs text-muted-foreground"
                onClick={() => router.push('/creator/revenue/sources')}
              >
                查看详情
                <ChevronRight className="w-4 h-4 ml-0.5" />
              </Button>
            </div>
            
            <div className="space-y-3">
              {data?.sources.map((source) => (
                <div 
                  key={source.type}
                  className="flex items-center cursor-pointer hover:bg-muted/50 -mx-2 px-2 py-1 rounded-lg transition-colors"
                  onClick={() => setSelectedType(source.type)}
                >
                  <div className={`w-8 h-8 rounded-lg ${SOURCE_COLORS[source.type]} flex items-center justify-center text-white mr-3`}>
                    {SOURCE_ICONS[source.type]}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm">{REVENUE_SOURCE_NAMES[source.type]}</span>
                      <span className="font-medium">{source.amount.toLocaleString()}</span>
                    </div>
                    <div className="flex items-center">
                      <div className="flex-1 h-1.5 bg-muted rounded-full overflow-hidden mr-2">
                        <div 
                          className={`h-full ${SOURCE_COLORS[source.type]} rounded-full`}
                          style={{ width: `${source.percentage}%` }}
                        />
                      </div>
                      <span className="text-xs text-muted-foreground w-10">{source.percentage}%</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* 收益明细 */}
          <Card className="p-4">
            <h3 className="font-medium mb-4">收益明细</h3>
            
            {/* 类型筛选 */}
            <Tabs value={selectedType} onValueChange={(v) => setSelectedType(v as RevenueSourceType | 'all')} className="mb-4">
              <TabsList className="w-full h-auto flex-wrap gap-1 bg-transparent p-0">
                <TabsTrigger 
                  value="all" 
                  className="text-xs data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                >
                  全部
                </TabsTrigger>
                {Object.entries(REVENUE_SOURCE_NAMES).map(([type, name]) => (
                  <TabsTrigger 
                    key={type}
                    value={type}
                    className="text-xs data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                  >
                    {name}
                  </TabsTrigger>
                ))}
              </TabsList>
            </Tabs>

            {/* 明细列表 */}
            {detailsLoading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="flex items-center space-x-3">
                    <div className="w-10 h-10 rounded-lg bg-muted animate-pulse" />
                    <div className="flex-1 space-y-2">
                      <div className="h-4 bg-muted rounded animate-pulse w-3/4" />
                      <div className="h-3 bg-muted rounded animate-pulse w-1/2" />
                    </div>
                  </div>
                ))}
              </div>
            ) : details.length === 0 ? (
              <div className="py-8 text-center text-muted-foreground">
                暂无收益记录
              </div>
            ) : (
              <div className="space-y-3">
                {details.map((item) => (
                  <div 
                    key={item.id}
                    className="flex items-start p-3 bg-muted/30 rounded-xl"
                  >
                    <div className={`w-10 h-10 rounded-lg ${SOURCE_COLORS[item.type]} flex items-center justify-center text-white mr-3 flex-shrink-0`}>
                      {SOURCE_ICONS[item.type]}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between mb-1">
                        <p className="text-sm font-medium truncate pr-2">{item.title}</p>
                        <span className="text-primary font-semibold whitespace-nowrap">+{item.amount}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center text-xs text-muted-foreground">
                          {item.buyer && (
                            <>
                              <Avatar className="w-4 h-4 mr-1">
                                <AvatarImage src={item.buyer.avatar} />
                                <AvatarFallback>{item.buyer.nickname[0]}</AvatarFallback>
                              </Avatar>
                              <span className="mr-2">{item.buyer.nickname}</span>
                            </>
                          )}
                          <span>{item.createdAt}</span>
                        </div>
                        {getStatusBadge(item.status)}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Card>
        </div>
      </DataState>
    </div>
  )
}
