// apps/mobile/src/pkg-course/purchase-confirm/index.vue
<script setup lang="ts">
/** 课程购买确认页 - 从原型 app/courses/purchase-confirm/page.tsx 迁移 */
import { ref, computed, onMounted } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { goBack } from '@/utils/router'
import AppIcon from '@/components/common/app-icon.vue'
import { courseApi } from '@/lib/course-data'

const loading = ref(true)
const error = ref('')
const courseId = ref('')

const course = ref<any>(null)
const coupons = ref<any[]>([])

const selectedCoupon = ref<string | null>(null)
const payMethod = ref('wechat')
const agreed = ref(false)
const showCouponList = ref(false)

const payMethods = [
  { id: 'wechat', name: '微信支付', icon: 'smartphone', color: '#22c55e' },
  { id: 'alipay', name: '支付宝', icon: 'credit-card', color: '#3b82f6' },
  { id: 'unionpay', name: '云闪付', icon: 'landmark', color: '#ef4444' },
  { id: 'huifu', name: '汇付天下', icon: 'building-2', color: '#f97316' },
]

const availableCoupons = computed(() => coupons.value.filter((c) => c.isAvailable && c.minAmount <= (course.value?.price ?? 0)))
const selectedCouponData = computed(() => (selectedCoupon.value ? coupons.value.find((c) => c.id === selectedCoupon.value) : null))
const discount = computed(() => {
  const c = selectedCouponData.value
  if (!c) return 0
  if (c.type === 'amount') return c.value
  return Math.min((course.value?.price ?? 0) * (c.value / 100), c.maxDiscount || Infinity)
})
const finalPrice = computed(() => (course.value?.price ?? 0) - discount.value)

function selectCoupon(id: string | null) {
  selectedCoupon.value = id
  showCouponList.value = false
}
function isCouponAvailable(c: any) {
  return c.isAvailable && c.minAmount <= (course.value?.price ?? 0)
}

async function loadData() {
  loading.value = true
  error.value = ''
  try {
    const [purchaseCourse, purchaseCoupons] = await Promise.all([
      courseApi.getPurchaseCourse(courseId.value),
      courseApi.getPurchaseCoupons(),
    ])
    course.value = purchaseCourse
    coupons.value = purchaseCoupons
  } catch (e: any) {
    error.value = e?.message || '加载失败'
  } finally {
    loading.value = false
  }
}

onLoad((options: any) => {
  courseId.value = options?.id || '1'
})

onMounted(() => {
  loadData()
})
</script>

<template>
  <!-- Loading -->
  <view v-if="loading" class="loading-wrap">
    <text class="loading-text">加载中...</text>
  </view>
  <!-- Error -->
  <view v-else-if="error" class="error-wrap">
    <text class="error-text">{{ error }}</text>
    <view class="retry-btn" @tap="loadData"><text class="retry-text">重试</text></view>
  </view>
  <!-- Content -->
  <view v-else class="page">
    <!-- 顶部导航 -->
    <view class="nav">
      <view class="nav-back" @tap="goBack"><app-icon name="arrow-left" :size="40" color="#2C2C2C" /></view>
      <text class="nav-title">确认订单</text>
      <view class="nav-right" />
    </view>

    <view class="body">
      <!-- 课程信息 -->
      <view class="card course-card">
        <image lazy-load class="course-cover" :src="course.cover" mode="aspectFill" />
        <view class="course-info">
          <text class="course-title">{{ course.title }}</text>
          <text class="course-meta">{{ course.instructorName }} | {{ course.chapters }}课时</text>
          <view class="course-price">
            <text class="price-now">¥{{ course.price }}</text>
            <text class="price-old">¥{{ course.originalPrice }}</text>
          </view>
        </view>
      </view>

      <!-- 优惠券 -->
      <view class="card">
        <view class="coupon-head" @tap="showCouponList = !showCouponList">
          <view class="coupon-head-left">
            <app-icon name="tag" :size="40" color="#C41E3A" />
            <text class="coupon-label">优惠券</text>
            <text v-if="availableCoupons.length > 0" class="coupon-badge">{{ availableCoupons.length }}张可用</text>
          </view>
          <view class="coupon-head-right">
            <text v-if="selectedCouponData" class="coupon-discount">-¥{{ discount }}</text>
            <text v-else-if="availableCoupons.length > 0" class="coupon-hint">选择优惠券</text>
            <text v-else class="coupon-hint">暂无可用</text>
            <app-icon name="chevron-right" :size="32" color="#999999" :class="{ rotated: showCouponList }" />
          </view>
        </view>

        <view v-if="showCouponList" class="coupon-list">
          <view class="coupon-item simple" :class="{ active: !selectedCoupon }" @tap="selectCoupon(null)">
            <text class="coupon-none-txt">不使用优惠券</text>
            <app-icon v-if="!selectedCoupon" name="check" :size="40" color="#C41E3A" />
          </view>
          <view
            v-for="c in coupons" :key="c.id"
            class="coupon-item" :class="{ active: selectedCoupon === c.id, disabled: !isCouponAvailable(c) }"
            @tap="isCouponAvailable(c) && selectCoupon(c.id)"
          >
            <view class="coupon-item-left">
              <view class="coupon-val">
                <template v-if="c.type === 'percent'">
                  <text class="coupon-val-num">{{ c.value }}%</text>
                  <text class="coupon-val-unit">折扣</text>
                </template>
                <template v-else>
                  <text class="coupon-val-yen">¥</text>
                  <text class="coupon-val-num2">{{ c.value }}</text>
                </template>
              </view>
              <view class="coupon-detail">
                <text class="coupon-name">{{ c.name }}</text>
                <text class="coupon-min">满{{ c.minAmount }}可用</text>
                <view class="coupon-expire">
                  <app-icon name="clock" :size="24" color="#999999" />
                  <text class="coupon-expire-txt">{{ c.expireAt }}到期</text>
                </view>
              </view>
            </view>
            <app-icon v-if="selectedCoupon === c.id" name="check" :size="40" color="#C41E3A" />
          </view>
        </view>
      </view>

      <!-- 支付方式 -->
      <view class="card">
        <text class="section-title">支付方式</text>
        <view class="pay-list">
          <view
            v-for="m in payMethods" :key="m.id"
            class="pay-item" :class="{ active: payMethod === m.id }"
            @tap="payMethod = m.id"
          >
            <view class="pay-item-left">
              <app-icon :name="m.icon" :size="48" :color="m.color" />
              <text class="pay-name">{{ m.name }}</text>
            </view>
            <app-icon v-if="payMethod === m.id" name="check" :size="40" color="#C41E3A" />
          </view>
        </view>
      </view>

      <!-- 价格明细 -->
      <view class="card">
        <text class="section-title">价格明细</text>
        <view class="price-rows">
          <view class="price-row">
            <text class="price-row-label">课程原价</text>
            <text class="price-row-val">¥{{ course.price }}</text>
          </view>
          <view v-if="discount" class="price-row discount">
            <text class="price-row-label red">优惠券抵扣</text>
            <text class="price-row-val red">-¥{{ discount }}</text>
          </view>
          <view class="price-row total">
            <text class="price-row-label">实付金额</text>
            <text class="price-total">¥{{ finalPrice }}</text>
          </view>
        </view>
      </view>

      <!-- 用户协议 -->
      <view class="agree">
        <view class="agree-box" :class="{ checked: agreed }" @tap="agreed = !agreed">
          <app-icon v-if="agreed" name="check" :size="24" color="#ffffff" />
        </view>
        <text class="agree-txt">我已阅读并同意<text class="agree-link">《用户协议》</text>和<text class="agree-link">《隐私政策》</text>，购买后不支持退款</text>
      </view>
    </view>

    <!-- 底部支付栏 -->
    <view class="footer">
      <view class="footer-price">
        <view class="footer-price-row">
          <text class="footer-pay-label">实付</text>
          <text class="footer-yen">¥</text>
          <text class="footer-amount">{{ finalPrice }}</text>
        </view>
        <text v-if="discount" class="footer-saved">已优惠 ¥{{ discount }}</text>
      </view>
      <view class="footer-btn" :class="{ disabled: !agreed }">
        <app-icon name="shield-check" :size="40" color="#ffffff" />
        <text class="footer-btn-txt">确认支付</text>
      </view>
    </view>
  </view>
</template>

<style scoped>
.page { min-height: 100vh; background: #FAF8F5; padding-bottom: 160rpx; }

.nav { position: sticky; top: 0; z-index: 50; background: #fff; border-bottom: 1rpx solid #E8E3DB; display: flex; align-items: center; height: 96rpx; padding: 0 32rpx; }
.nav-back { margin-left: -8rpx; padding: 8rpx; }
.nav-title { flex: 1; text-align: center; font-size: 32rpx; font-weight: 500; color: #2C2C2C; }
.nav-right { width: 48rpx; }

.body { padding: 32rpx; display: flex; flex-direction: column; gap: 24rpx; }
.card { background: #fff; border-radius: 24rpx; padding: 32rpx; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }

.course-card { display: flex; gap: 24rpx; }
.course-cover { width: 192rpx; height: 144rpx; border-radius: 16rpx; flex-shrink: 0; background: #F2EFEA; }
.course-info { flex: 1; min-width: 0; }
.course-title { display: block; font-size: 28rpx; font-weight: 500; color: #2C2C2C; margin-bottom: 8rpx; line-height: 1.4; }
.course-meta { display: block; font-size: 24rpx; color: #999; margin-bottom: 16rpx; }
.course-price { display: flex; align-items: baseline; gap: 16rpx; }
.price-now { font-size: 36rpx; font-weight: 700; color: var(--brand); }
.price-old { font-size: 24rpx; color: #999; text-decoration: line-through; }

.coupon-head { display: flex; align-items: center; justify-content: space-between; }
.coupon-head-left { display: flex; align-items: center; gap: 16rpx; }
.coupon-label { font-size: 28rpx; font-weight: 500; color: #2C2C2C; }
.coupon-badge { font-size: 20rpx; color: var(--brand); background: rgba(196,30,58,0.1); padding: 4rpx 12rpx; border-radius: 8rpx; }
.coupon-head-right { display: flex; align-items: center; gap: 8rpx; }
.coupon-discount { font-size: 28rpx; color: var(--brand); }
.coupon-hint { font-size: 28rpx; color: #999; }
.rotated { transform: rotate(90deg); }

.coupon-list { border-top: 1rpx solid #F2EFEA; margin-top: 32rpx; padding-top: 32rpx; display: flex; flex-direction: column; gap: 16rpx; }
.coupon-item { border: 4rpx solid #E8E3DB; border-radius: 16rpx; padding: 24rpx; display: flex; align-items: center; justify-content: space-between; }
.coupon-item.simple { justify-content: space-between; }
.coupon-item.active { border-color: var(--brand); background: rgba(196,30,58,0.05); }
.coupon-item.disabled { opacity: 0.5; }
.coupon-none-txt { font-size: 28rpx; color: #666; }
.coupon-item-left { display: flex; align-items: center; gap: 24rpx; }
.coupon-val { width: 112rpx; height: 112rpx; border-radius: 16rpx; background: linear-gradient(135deg, var(--brand), #8B0000); display: flex; flex-direction: column; align-items: center; justify-content: center; color: #fff; }
.coupon-val-num { font-size: 32rpx; font-weight: 700; color: #fff; }
.coupon-val-unit { font-size: 20rpx; color: #fff; }
.coupon-val-yen { font-size: 20rpx; color: #fff; }
.coupon-val-num2 { font-size: 36rpx; font-weight: 700; color: #fff; line-height: 1; }
.coupon-detail { text-align: left; }
.coupon-name { display: block; font-size: 28rpx; font-weight: 500; color: #2C2C2C; }
.coupon-min { display: block; font-size: 24rpx; color: #999; }
.coupon-expire { display: flex; align-items: center; gap: 4rpx; margin-top: 4rpx; }
.coupon-expire-txt { font-size: 20rpx; color: #999; }

.section-title { display: block; font-size: 28rpx; font-weight: 500; color: #2C2C2C; margin-bottom: 24rpx; }
.pay-list { display: flex; flex-direction: column; gap: 16rpx; }
.pay-item { border: 4rpx solid #E8E3DB; border-radius: 16rpx; padding: 24rpx; display: flex; align-items: center; justify-content: space-between; }
.pay-item.active { border-color: var(--brand); background: rgba(196,30,58,0.05); }
.pay-item-left { display: flex; align-items: center; gap: 24rpx; }
.pay-name { font-size: 28rpx; color: #2C2C2C; }

.price-rows { display: flex; flex-direction: column; gap: 16rpx; }
.price-row { display: flex; align-items: center; justify-content: space-between; }
.price-row-label { font-size: 28rpx; color: #666; }
.price-row-val { font-size: 28rpx; color: #2C2C2C; }
.price-row-label.red, .price-row-val.red { color: var(--brand); }
.price-row.total { padding-top: 16rpx; border-top: 1rpx solid #F2EFEA; align-items: baseline; }
.price-total { font-size: 48rpx; font-weight: 700; color: var(--brand); }

.agree { display: flex; align-items: flex-start; gap: 16rpx; padding: 0 8rpx; }
.agree-box { width: 40rpx; height: 40rpx; border-radius: 8rpx; border: 4rpx solid #CCC; flex-shrink: 0; margin-top: 4rpx; display: flex; align-items: center; justify-content: center; }
.agree-box.checked { background: var(--brand); border-color: var(--brand); }
.agree-txt { font-size: 24rpx; color: #999; line-height: 1.6; }
.agree-link { color: var(--brand); }

.footer { position: fixed; bottom: 0; left: 0; right: 0; background: #fff; border-top: 1rpx solid #E8E3DB; padding: 24rpx 32rpx; padding-bottom: calc(24rpx + env(safe-area-inset-bottom)); display: flex; align-items: center; gap: 32rpx; }
.footer-price { flex: 1; }
.footer-price-row { display: flex; align-items: baseline; gap: 4rpx; }
.footer-pay-label { font-size: 24rpx; color: #666; }
.footer-yen { font-size: 20rpx; color: var(--brand); }
.footer-amount { font-size: 48rpx; font-weight: 700; color: var(--brand); }
.footer-saved { font-size: 22rpx; color: #999; }
.footer-btn { display: flex; align-items: center; gap: 12rpx; padding: 24rpx 64rpx; border-radius: 999rpx; background: linear-gradient(to right, var(--brand), #E74C3C); box-shadow: 0 8rpx 24rpx rgba(196,30,58,0.3); }
.footer-btn.disabled { background: #CCC; box-shadow: none; }
.footer-btn-txt { font-size: 32rpx; font-weight: 700; color: #fff; }

/* 加载 / 错误 */
.loading-wrap, .error-wrap { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; gap: 24rpx; }
.loading-text, .error-text { font-size: 28rpx; color: var(--text-soft); }
.retry-btn { padding: 16rpx 48rpx; background: var(--brand); border-radius: 999rpx; }
.retry-text { font-size: 28rpx; color: #fff; }
</style>

// proto-ref-app/courses/purchase-confirm/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import Link from "next/link"
import { ArrowLeft, Check, Tag, CreditCard, Smartphone, ChevronRight, ShieldCheck, Clock, Landmark, Building2 } from "lucide-react"
import { cn } from "@/lib/utils"
import { courseApi, shopApi, pricingApi, type Course, type Coupon, type PriceCalcResult } from "@/lib/api"
import { usePaymentBindings, type PaymentChannel } from "@/hooks/use-payment-bindings"
import { BindPaymentDialog } from "@/components/wallet/bind-payment-dialog"

// Mock data
const mockCourse: Course = {
  id: "1",
  title: "八字命理入门到精通",
  cover: "https://picsum.photos/seed/course1/400/300",
  instructor: { id: "1", name: "张老师", avatar: "https://i.pravatar.cc/100?img=1", title: "资深命理师" },
  price: 299,
  originalPrice: 599,
  students: 2860,
  rating: 4.9,
  chapters: 32,
  category: "命理",
  isFree: false,
}

const mockCoupons: Coupon[] = [
  { id: "1", name: "新人专享券", type: "amount", value: 50, minAmount: 100, expireAt: "2024-12-31", scope: ["course"], isAvailable: true },
  { id: "2", name: "课程9折券", type: "percent", value: 10, minAmount: 200, maxDiscount: 100, expireAt: "2024-06-30", scope: ["course"], isAvailable: true },
  { id: "3", name: "满300减30", type: "amount", value: 30, minAmount: 300, expireAt: "2024-07-15", scope: ["course"], isAvailable: false },
]

const payMethods = [
  { id: "wechat", name: "微信支付", icon: Smartphone, color: "text-green-500" },
  { id: "alipay", name: "支付宝", icon: CreditCard, color: "text-blue-500" },
  { id: "unionpay", name: "云闪付", icon: Landmark, color: "text-red-500" },
  { id: "huifu", name: "汇付天下", icon: Building2, color: "text-orange-500" },
]

// 骨架屏
function PurchaseSkeleton() {
  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      <div className="h-12 bg-white" />
      <div className="p-4 space-y-4">
        <div className="bg-white rounded-xl p-4 animate-pulse">
          <div className="flex gap-3">
            <div className="w-24 h-18 bg-[#F2EFEA] rounded-lg" />
            <div className="flex-1 space-y-2">
              <div className="h-5 bg-[#F2EFEA] rounded w-3/4" />
              <div className="h-4 bg-[#F2EFEA] rounded w-1/2" />
              <div className="h-6 bg-[#F2EFEA] rounded w-1/3" />
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl p-4 animate-pulse space-y-3">
          <div className="h-5 bg-[#F2EFEA] rounded w-1/4" />
          <div className="h-16 bg-[#F2EFEA] rounded" />
          <div className="h-16 bg-[#F2EFEA] rounded" />
        </div>
      </div>
    </div>
  )
}

function PurchaseConfirmContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const courseId = searchParams.get("id") || "1"
  
  const [course, setCourse] = useState<Course | null>(null)
  const [coupons, setCoupons] = useState<Coupon[]>([])
  const [selectedCoupon, setSelectedCoupon] = useState<string | null>(null)
  const [payMethod, setPayMethod] = useState("wechat")
  const [priceResult, setPriceResult] = useState<PriceCalcResult | null>(null)
  const [agreed, setAgreed] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [showCouponList, setShowCouponList] = useState(false)
  const { isBound } = usePaymentBindings()
  const [showBindDialog, setShowBindDialog] = useState(false)

  useEffect(() => {
    const loadData = async () => {
      setIsLoading(true)
      try {
        // 实际项目中从API获取
        // const [courseData, couponsData] = await Promise.all([
        //   courseApi.detail(courseId),
        //   shopApi.myCoupons({ available: true })
        // ])
        setCourse(mockCourse)
        setCoupons(mockCoupons)
        setPriceResult({
          originalPrice: mockCourse.price,
          discountAmount: 0,
          finalPrice: mockCourse.price,
        })
      } catch (error) {
        console.error("Failed to load data:", error)
      } finally {
        setIsLoading(false)
      }
    }
    loadData()
  }, [courseId])

  // 选择优惠券后计算价格
  const handleSelectCoupon = async (couponId: string | null) => {
    setSelectedCoupon(couponId)
    setShowCouponList(false)
    
    if (!course) return
    
    if (couponId) {
      const coupon = coupons.find(c => c.id === couponId)
      if (coupon) {
        let discount = 0
        if (coupon.type === "amount") {
          discount = coupon.value
        } else if (coupon.type === "percent") {
          discount = Math.min(course.price * (coupon.value / 100), coupon.maxDiscount || Infinity)
        }
        setPriceResult({
          originalPrice: course.price,
          discountAmount: discount,
          finalPrice: course.price - discount,
          couponUsed: { id: coupon.id, name: coupon.name, discount },
        })
      }
    } else {
      setPriceResult({
        originalPrice: course.price,
        discountAmount: 0,
        finalPrice: course.price,
      })
    }
  }

  // 提交订单
  const handleSubmit = async () => {
    if (!agreed || !course || isSubmitting) return

    // 所选第三方支付渠道未绑定时，引导用户先绑定
    if (!isBound(payMethod as PaymentChannel)) {
      setShowBindDialog(true)
      return
    }

    setIsSubmitting(true)
    try {
      // const result = await pricingApi.createOrder({
      //   productId: course.id,
      //   productType: "course",
      //   couponId: selectedCoupon || undefined,
      //   payMethod,
      // })
      // 模拟跳转支付
      await new Promise(resolve => setTimeout(resolve, 1000))
      router.push(`/payment/result?status=success&orderId=mock123`)
    } catch (error) {
      console.error("Failed to create order:", error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (isLoading) return <PurchaseSkeleton />
  if (!course) return null

  const selectedCouponData = selectedCoupon ? coupons.find(c => c.id === selectedCoupon) : null
  const availableCoupons = coupons.filter(c => c.isAvailable && c.minAmount <= course.price)

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-32">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-50 bg-white border-b border-[#E8E3DB]">
        <div className="flex items-center h-12 px-4">
          <button onClick={() => router.back()} className="p-1 -ml-1">
            <ArrowLeft className="w-5 h-5 text-[#2C2C2C]" />
          </button>
          <h1 className="flex-1 text-center text-[16px] font-medium text-[#2C2C2C]">确认订单</h1>
          <div className="w-6" />
        </div>
      </div>

      <div className="p-4 space-y-3">
        {/* 课程信息 */}
        <div className="bg-white rounded-xl p-4 shadow-sm">
          <div className="flex gap-3">
            <img
              src={course.cover}
              alt={course.title}
              className="w-24 h-[72px] rounded-lg object-cover flex-shrink-0"
            />
            <div className="flex-1 min-w-0">
              <h3 className="text-[14px] font-medium text-[#2C2C2C] line-clamp-2 mb-1">{course.title}</h3>
              <p className="text-[12px] text-[#999999] mb-2">{course.instructor.name} | {course.chapters}课时</p>
              <div className="flex items-baseline gap-2">
                <span className="text-[18px] font-bold text-[#C41E3A]">¥{course.price}</span>
                <span className="text-[12px] text-[#999999] line-through">¥{course.originalPrice}</span>
              </div>
            </div>
          </div>
        </div>

        {/* 优惠券选择 */}
        <div className="bg-white rounded-xl shadow-sm">
          <button 
            onClick={() => setShowCouponList(!showCouponList)}
            className="w-full p-4 flex items-center justify-between"
          >
            <div className="flex items-center gap-2">
              <Tag className="w-5 h-5 text-[#C41E3A]" />
              <span className="text-[14px] font-medium text-[#2C2C2C]">优惠券</span>
              {availableCoupons.length > 0 && (
                <span className="text-[10px] text-[#C41E3A] bg-[#C41E3A]/10 px-1.5 py-0.5 rounded">
                  {availableCoupons.length}张可用
                </span>
              )}
            </div>
            <div className="flex items-center gap-1">
              {selectedCouponData ? (
                <span className="text-[14px] text-[#C41E3A]">-¥{priceResult?.couponUsed?.discount || 0}</span>
              ) : availableCoupons.length > 0 ? (
                <span className="text-[14px] text-[#999999]">选择优惠券</span>
              ) : (
                <span className="text-[14px] text-[#999999]">暂无可用</span>
              )}
              <ChevronRight className={cn("w-4 h-4 text-[#999999] transition-transform", showCouponList && "rotate-90")} />
            </div>
          </button>

          {/* 优惠券列表 */}
          {showCouponList && (
            <div className="border-t border-[#F2EFEA] p-4 space-y-2">
              {/* 不使用优惠券 */}
              <button
                onClick={() => handleSelectCoupon(null)}
                className={cn(
                  "w-full p-3 rounded-lg border-2 transition-all flex items-center justify-between",
                  !selectedCoupon ? "border-[#C41E3A] bg-[#C41E3A]/5" : "border-[#E8E3DB]"
                )}
              >
                <span className="text-[14px] text-[#666666]">不使用优惠券</span>
                {!selectedCoupon && <Check className="w-5 h-5 text-[#C41E3A]" />}
              </button>

              {coupons.map((coupon) => {
                const isAvailable = coupon.isAvailable && coupon.minAmount <= course.price
                return (
                  <button
                    key={coupon.id}
                    onClick={() => isAvailable && handleSelectCoupon(coupon.id)}
                    disabled={!isAvailable}
                    className={cn(
                      "w-full p-3 rounded-lg border-2 transition-all",
                      selectedCoupon === coupon.id ? "border-[#C41E3A] bg-[#C41E3A]/5" : "border-[#E8E3DB]",
                      !isAvailable && "opacity-50 cursor-not-allowed"
                    )}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-14 h-14 bg-gradient-to-br from-[#C41E3A] to-[#8B0000] rounded-lg flex flex-col items-center justify-center text-white">
                          {coupon.type === "percent" ? (
                            <>
                              <span className="text-[16px] font-bold">{coupon.value}%</span>
                              <span className="text-[10px]">折扣</span>
                            </>
                          ) : (
                            <>
                              <span className="text-[10px]">¥</span>
                              <span className="text-[18px] font-bold leading-none">{coupon.value}</span>
                            </>
                          )}
                        </div>
                        <div className="text-left">
                          <p className="text-[14px] font-medium text-[#2C2C2C]">{coupon.name}</p>
                          <p className="text-[12px] text-[#999999]">满{coupon.minAmount}可用</p>
                          <div className="flex items-center gap-1 mt-0.5">
                            <Clock className="w-3 h-3 text-[#999999]" />
                            <span className="text-[10px] text-[#999999]">{coupon.expireAt}到期</span>
                          </div>
                        </div>
                      </div>
                      {selectedCoupon === coupon.id && <Check className="w-5 h-5 text-[#C41E3A]" />}
                    </div>
                  </button>
                )
              })}
            </div>
          )}
        </div>

        {/* 支付方式 */}
        <div className="bg-white rounded-xl p-4 shadow-sm">
          <h3 className="text-[14px] font-medium text-[#2C2C2C] mb-3">支付方式</h3>
          <div className="space-y-2">
            {payMethods.map((method) => (
              <button
                key={method.id}
                onClick={() => setPayMethod(method.id)}
                className={cn(
                  "w-full p-3 rounded-lg border-2 transition-all flex items-center justify-between",
                  payMethod === method.id ? "border-[#C41E3A] bg-[#C41E3A]/5" : "border-[#E8E3DB]"
                )}
              >
                <div className="flex items-center gap-3">
                  <method.icon className={cn("w-6 h-6", method.color)} />
                  <span className="text-[14px] text-[#2C2C2C]">{method.name}</span>
                </div>
                {payMethod === method.id && <Check className="w-5 h-5 text-[#C41E3A]" />}
              </button>
            ))}
          </div>
        </div>

        {/* 价格明细 */}
        <div className="bg-white rounded-xl p-4 shadow-sm">
          <h3 className="text-[14px] font-medium text-[#2C2C2C] mb-3">价格明细</h3>
          <div className="space-y-2 text-[14px]">
            <div className="flex justify-between">
              <span className="text-[#666666]">课程原价</span>
              <span className="text-[#2C2C2C]">¥{priceResult?.originalPrice || course.price}</span>
            </div>
            {priceResult?.discountAmount ? (
              <div className="flex justify-between text-[#C41E3A]">
                <span>优惠券抵扣</span>
                <span>-¥{priceResult.discountAmount}</span>
              </div>
            ) : null}
            <div className="pt-2 border-t border-[#F2EFEA] flex justify-between items-baseline">
              <span className="text-[#666666]">实付金额</span>
              <span className="text-[24px] font-bold text-[#C41E3A]">¥{priceResult?.finalPrice || course.price}</span>
            </div>
          </div>
        </div>

        {/* 用户协议 */}
        <div className="flex items-start gap-2 px-1">
          <button
            onClick={() => setAgreed(!agreed)}
            className={cn(
              "w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 mt-0.5 transition-colors",
              agreed ? "bg-[#C41E3A] border-[#C41E3A]" : "border-[#CCCCCC]"
            )}
          >
            {agreed && <Check className="w-3 h-3 text-white" />}
          </button>
          <p className="text-[12px] text-[#999999] leading-relaxed">
            我已阅读并同意
            <Link href="/policy/user" className="text-[#C41E3A]">《用户协议》</Link>
            和
            <Link href="/policy/privacy" className="text-[#C41E3A]">《隐私政策》</Link>
            ，购买后不支持退款
          </p>
        </div>
      </div>

      {/* 底部支付栏 */}
      <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-[#E8E3DB] p-4 safe-area-pb">
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="flex items-baseline gap-1">
              <span className="text-[12px] text-[#666666]">实付</span>
              <span className="text-[10px] text-[#C41E3A]">¥</span>
              <span className="text-[24px] font-bold text-[#C41E3A]">{priceResult?.finalPrice || course.price}</span>
            </div>
            {priceResult?.discountAmount ? (
              <p className="text-[11px] text-[#999999]">已优惠 ¥{priceResult.discountAmount}</p>
            ) : null}
          </div>
          <button
            onClick={handleSubmit}
            disabled={!agreed || isSubmitting}
            className={cn(
              "px-8 py-3 rounded-full text-[16px] font-bold transition-all flex items-center gap-2",
              agreed && !isSubmitting
                ? "bg-gradient-to-r from-[#C41E3A] to-[#E74C3C] text-white shadow-lg"
                : "bg-[#CCCCCC] text-white cursor-not-allowed"
            )}
          >
            {isSubmitting ? (
              <>
                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                处理中...
              </>
            ) : (
              <>
                <ShieldCheck className="w-5 h-5" />
                确认支付
              </>
            )}
          </button>
        </div>
      </div>

      <BindPaymentDialog
        open={showBindDialog}
        onClose={() => setShowBindDialog(false)}
        channel={payMethod as PaymentChannel}
      />
    </div>
  )
}

export default function PurchaseConfirmPage() {
  return (
    <Suspense fallback={<PurchaseSkeleton />}>
      <PurchaseConfirmContent />
    </Suspense>
  )
}
