// apps/mobile/src/pkg-merchant/inquiries/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="nav" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="nav-bar">
        <view class="nav-back" @tap="onNavBack">
          <app-icon name="arrow-left" :size="22" color="#1a1a1a" />
        </view>
        <text class="nav-title">{{ selected ? '咨询详情' : '咨询管理' }}</text>
        <view class="nav-placeholder" />
      </view>
    </view>

    <scroll-view scroll-y class="scroll" :style="{ paddingTop: navHeight + 'px' }">
      <!-- 详情视图 -->
      <template v-if="selected">
        <view class="prod-box">
          <text class="prod-label">商品</text>
          <text class="prod-name">{{ selected.productName }}</text>
        </view>

        <view class="customer-box">
          <view class="customer-avatar">
            <app-icon name="user" :size="24" color="#c41e3a" />
          </view>
          <view class="customer-info">
            <text class="customer-name">{{ selected.customer }}</text>
            <view class="customer-time">
              <app-icon name="clock" :size="12" color="#9ca3af" />
              <text class="customer-time-text">{{ selected.time }}</text>
            </view>
          </view>
          <text class="status-badge" :class="selected.status === 'answered' ? 'badge-green' : 'badge-orange'">
            {{ selected.status === 'answered' ? '已回答' : '待回答' }}
          </text>
        </view>

        <view class="section">
          <text class="section-title">客户问题</text>
          <view class="card"><text class="question-text">{{ selected.question }}</text></view>
        </view>

        <view v-if="selected.answer" class="section">
          <text class="section-title">您的回复</text>
          <view class="card answer-card">
            <view class="answer-head">
              <app-icon name="check-circle" :size="20" color="#16a34a" />
              <text class="answer-tag">已回复</text>
            </view>
            <text class="answer-text">{{ selected.answer }}</text>
          </view>
        </view>

        <view v-if="selected.status === 'unanswered'" class="section">
          <text class="section-title">写回复</text>
          <textarea v-model="replyText" class="reply-textarea" placeholder="请输入您的回复内容..." />
          <view class="reply-btn" :class="{ disabled: !replyText.trim() || isReplying }" @tap="handleReply">
            <text class="reply-btn-text">{{ isReplying ? '提交中...' : '提交回复' }}</text>
          </view>
        </view>
      </template>

      <!-- 列表视图 -->
      <template v-else>
        <view class="stat-grid">
          <view class="stat-card">
            <text class="stat-num">{{ inquiries.length }}</text>
            <text class="stat-label">总咨询</text>
          </view>
          <view class="stat-card stat-orange">
            <text class="stat-num stat-num-orange">{{ unansweredCount }}</text>
            <text class="stat-label stat-label-orange">待回答</text>
          </view>
          <view class="stat-card stat-green">
            <text class="stat-num stat-num-green">{{ answeredCount }}</text>
            <text class="stat-label stat-label-green">已回答</text>
          </view>
        </view>

        <view class="filter-bar">
          <view
            v-for="f in filters"
            :key="f.key"
            class="filter"
            :class="{ 'filter-active': filter === f.key }"
            @tap="filter = f.key"
          >
            <text class="filter-text" :class="{ 'filter-text-active': filter === f.key }">{{ f.label }}</text>
          </view>
        </view>

        <view class="list">
          <view
            v-for="inquiry in filteredInquiries"
            :key="inquiry.id"
            class="inq-card"
            @tap="selected = inquiry"
          >
            <view class="inq-head">
              <view class="inq-head-body">
                <text class="inq-product">{{ inquiry.productName }}</text>
                <view class="inq-meta">
                  <view class="inq-meta-item"><app-icon name="user" :size="12" color="#9ca3af" /><text class="inq-meta-text">{{ inquiry.customer }}</text></view>
                  <view class="inq-meta-item"><app-icon name="clock" :size="12" color="#9ca3af" /><text class="inq-meta-text">{{ inquiry.time }}</text></view>
                </view>
              </view>
              <text class="status-badge" :class="inquiry.status === 'answered' ? 'badge-green' : 'badge-orange'">
                {{ inquiry.status === 'answered' ? '已回答' : '待回答' }}
              </text>
            </view>
            <text class="inq-question">{{ inquiry.question }}</text>
            <view v-if="inquiry.status === 'unanswered'" class="inq-tip">
              <app-icon name="alert-circle" :size="12" color="#ea580c" />
              <text class="inq-tip-text">待您回复</text>
            </view>
          </view>

          <view v-if="filteredInquiries.length === 0" class="empty">
            <app-icon name="message-square" :size="24" color="#9ca3af" />
            <text class="empty-text">暂无咨询</text>
          </view>
        </view>
      </template>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'
import { merchantInquiries } from '@/lib/merchant-data'

type Inquiry = { id: string; productName: string; customer: string; status: 'answered' | 'unanswered'; question: string; answer: string; time: string; replies: number }

const statusBarHeight = ref(0)
const navHeight = ref(44)

const sys = uni.getSystemInfoSync()
statusBarHeight.value = sys.statusBarHeight || 0
navHeight.value = (sys.statusBarHeight || 0) + 44

const inquiries = ref<Inquiry[]>(merchantInquiries.map((i) => ({ ...i })))
const filter = ref<'all' | 'unanswered' | 'answered'>('all')
const selected = ref<Inquiry | null>(null)
const replyText = ref('')
const isReplying = ref(false)

const filters = [
  { key: 'all' as const, label: '全部' },
  { key: 'unanswered' as const, label: '待回答' },
  { key: 'answered' as const, label: '已回答' },
]

const unansweredCount = computed(() => inquiries.value.filter((i) => i.status === 'unanswered').length)
const answeredCount = computed(() => inquiries.value.filter((i) => i.status === 'answered').length)
const filteredInquiries = computed(() =>
  inquiries.value.filter((i) => (filter.value === 'all' ? true : i.status === filter.value)),
)

function handleReply() {
  if (!replyText.value.trim() || !selected.value || isReplying.value) return
  isReplying.value = true
  setTimeout(() => {
    const target = inquiries.value.find((i) => i.id === selected.value!.id)
    if (target) {
      target.status = 'answered'
      target.answer = replyText.value
      target.replies += 1
    }
    selected.value = null
    replyText.value = ''
    isReplying.value = false
    uni.showToast({ title: '回复成功', icon: 'success' })
  }, 1000)
}
function onNavBack() {
  if (selected.value) {
    selected.value = null
    replyText.value = ''
  } else {
    goBack()
  }
}
</script>

<style scoped>
.page { min-height: 100vh; background: #ffffff; }
.nav { position: fixed; top: 0; left: 0; right: 0; z-index: 50; background: #ffffff; border-bottom: 1px solid #ededed; }
.nav-bar { display: flex; align-items: center; height: 44px; padding: 0 16px; }
.nav-back { width: 32px; height: 32px; display: flex; align-items: center; }
.nav-title { flex: 1; text-align: center; font-size: 17px; font-weight: 600; color: #1a1a1a; }
.nav-placeholder { width: 32px; }
.scroll { height: 100vh; box-sizing: border-box; padding-bottom: 40px; }

.stat-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; padding: 16px 16px 0; }
.stat-card { padding: 12px; border-radius: 12px; border: 1px solid #ededed; display: flex; flex-direction: column; align-items: center; }
.stat-orange { background: #fff7ed; border-color: #fed7aa; }
.stat-green { background: #f0fdf4; border-color: #bbf7d0; }
.stat-num { font-size: 24px; font-weight: 700; color: #1a1a1a; }
.stat-num-orange { color: #ea580c; }
.stat-num-green { color: #16a34a; }
.stat-label { font-size: 12px; color: #9ca3af; margin-top: 4px; }
.stat-label-orange { color: #c2620e; }
.stat-label-green { color: #15803d; }

.filter-bar { display: flex; gap: 8px; padding: 16px 16px 0; }
.filter { padding: 6px 14px; border-radius: 999px; background: #f3f4f6; }
.filter-active { background: #c41e3a; }
.filter-text { font-size: 14px; color: #4b5563; }
.filter-text-active { color: #ffffff; }

.list { padding: 16px; display: flex; flex-direction: column; gap: 8px; }
.inq-card { padding: 16px; border-radius: 12px; border: 1px solid #ededed; }
.inq-head { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 8px; }
.inq-head-body { flex: 1; min-width: 0; }
.inq-product { display: block; font-size: 15px; font-weight: 600; color: #1a1a1a; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.inq-meta { display: flex; align-items: center; gap: 12px; margin-top: 4px; }
.inq-meta-item { display: flex; align-items: center; gap: 4px; }
.inq-meta-text { font-size: 12px; color: #9ca3af; }
.inq-question { display: block; font-size: 14px; color: rgba(26, 26, 26, 0.7); line-height: 1.5; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; }
.inq-tip { display: flex; align-items: center; gap: 4px; margin-top: 8px; }
.inq-tip-text { font-size: 12px; color: #ea580c; }
.status-badge { font-size: 12px; padding: 2px 10px; border-radius: 999px; flex-shrink: 0; }
.badge-green { color: #166534; background: #dcfce7; }
.badge-orange { color: #9a3412; background: #ffedd5; }

.empty { padding: 48px 0; display: flex; flex-direction: column; align-items: center; gap: 8px; }
.empty-text { font-size: 14px; color: #9ca3af; }

.prod-box { margin: 16px 16px 0; padding: 16px; background: #f9fafb; border-radius: 12px; }
.prod-label { display: block; font-size: 14px; color: #9ca3af; margin-bottom: 4px; }
.prod-name { font-size: 15px; font-weight: 600; color: #1a1a1a; }
.customer-box { margin: 12px 16px 0; padding: 16px; background: #ffffff; border: 1px solid #ededed; border-radius: 12px; display: flex; align-items: center; gap: 12px; }
.customer-avatar { width: 48px; height: 48px; border-radius: 50%; background: rgba(196, 30, 58, 0.1); display: flex; align-items: center; justify-content: center; }
.customer-info { flex: 1; }
.customer-name { display: block; font-size: 15px; font-weight: 600; color: #1a1a1a; }
.customer-time { display: flex; align-items: center; gap: 4px; margin-top: 4px; }
.customer-time-text { font-size: 12px; color: #9ca3af; }

.section { padding: 16px 16px 0; }
.section-title { display: block; font-size: 14px; font-weight: 600; color: #1a1a1a; margin-bottom: 12px; }
.card { background: #ffffff; border: 1px solid #ededed; border-radius: 12px; padding: 16px; }
.question-text { font-size: 15px; color: #1a1a1a; line-height: 1.6; }
.answer-card { background: rgba(196, 30, 58, 0.05); border-color: rgba(196, 30, 58, 0.2); }
.answer-head { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
.answer-tag { font-size: 12px; color: #16a34a; font-weight: 500; }
.answer-text { font-size: 15px; color: #1a1a1a; line-height: 1.6; }
.reply-textarea { width: 100%; box-sizing: border-box; height: 100px; padding: 12px; border: 1px solid #e5e7eb; border-radius: 8px; font-size: 14px; }
.reply-btn { margin-top: 12px; height: 46px; border-radius: 10px; background: #c41e3a; display: flex; align-items: center; justify-content: center; }
.reply-btn.disabled { opacity: 0.5; }
.reply-btn-text { font-size: 15px; font-weight: 500; color: #ffffff; }
</style>

// app/merchant/inquiries/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, MessageSquare, User, Clock, CheckCircle, AlertCircle } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'

// Mock data - 咨询列表
const mockInquiries = [
  {
    id: '1',
    productName: '《渊海子平》古籍影印本',
    customer: '张女士',
    status: 'unanswered',
    question: '请问这本书有电子版吗？能否快递到偏远地区？',
    time: '2024-01-20 14:30',
    replies: 0,
  },
  {
    id: '2',
    productName: '紫砂茶具套装',
    customer: '李先生',
    status: 'answered',
    question: '这套茶具是纯手工制作吗？有发票吗？',
    answer: '是的，全部由我们的手工艺人制作，购买时可提供发票。',
    time: '2024-01-20 10:15',
    replies: 1,
  },
  {
    id: '3',
    productName: '八字算命初学者套装',
    customer: '王女士',
    status: 'unanswered',
    question: '是否有退货政策？如果不满意可以退吗？',
    time: '2024-01-19 16:45',
    replies: 0,
  },
  {
    id: '4',
    productName: '国学经典诵读课程',
    customer: '陈先生',
    status: 'answered',
    question: '课程有效期是多久？可以重复学习吗？',
    answer: '课程一次购买终身有效，您可以随时重复学习。',
    time: '2024-01-19 09:20',
    replies: 2,
  },
  {
    id: '5',
    productName: '香道入门套装',
    customer: '赵女士',
    status: 'answered',
    question: '香道入门需要什么基础吗？',
    answer: '无需任何基础，我们的课程从零开始教学，包含详细的视频讲解。',
    time: '2024-01-18 14:10',
    replies: 1,
  },
]

const getStatusBadge = (status: string) => {
  if (status === 'answered') {
    return <Badge className="bg-green-100 text-green-800">已回答</Badge>
  }
  return <Badge className="bg-orange-100 text-orange-800">待回答</Badge>
}

export default function InquiriesPage() {
  const router = useRouter()
  const [inquiries, setInquiries] = useState(mockInquiries)
  const [filter, setFilter] = useState<'all' | 'unanswered' | 'answered'>('all')
  const [selectedInquiry, setSelectedInquiry] = useState<typeof mockInquiries[0] | null>(null)
  const [replyText, setReplyText] = useState('')
  const [isReplying, setIsReplying] = useState(false)

  const filteredInquiries = inquiries.filter(inquiry =>
    filter === 'all' ? true : inquiry.status === filter
  )

  const unansweredCount = inquiries.filter(i => i.status === 'unanswered').length

  const handleReply = async () => {
    if (!replyText.trim() || !selectedInquiry) return
    
    setIsReplying(true)
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    setInquiries(inquiries.map(i =>
      i.id === selectedInquiry.id
        ? { ...i, status: 'answered' as const, answer: replyText, replies: i.replies + 1 }
        : i
    ))
    
    setSelectedInquiry(null)
    setReplyText('')
    setIsReplying(false)
  }

  if (selectedInquiry) {
    return (
      <div className="min-h-screen bg-background">
        {/* 顶部导航 */}
        <div className="sticky top-0 z-10 bg-background border-b border-border">
          <div className="flex items-center justify-between px-4 py-3">
            <button onClick={() => setSelectedInquiry(null)} className="p-1">
              <ArrowLeft className="w-6 h-6 text-foreground" />
            </button>
            <h1 className="text-lg font-semibold text-foreground">咨询详情</h1>
            <div className="w-8" />
          </div>
        </div>

        <div className="pb-24">
          {/* 商品信息 */}
          <div className="mx-4 mt-4 p-4 bg-muted/50 rounded-xl">
            <div className="text-sm text-muted-foreground mb-1">商品</div>
            <div className="font-semibold text-foreground">{selectedInquiry.productName}</div>
          </div>

          {/* 客户信息 */}
          <div className="mx-4 mt-3 p-4 bg-card rounded-xl border border-border flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
              <User className="w-6 h-6 text-primary" />
            </div>
            <div className="flex-1">
              <div className="font-semibold text-foreground">{selectedInquiry.customer}</div>
              <div className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                <Clock className="w-3 h-3" /> {selectedInquiry.time}
              </div>
            </div>
            {getStatusBadge(selectedInquiry.status)}
          </div>

          {/* 问题 */}
          <div className="mx-4 mt-4">
            <h3 className="text-sm font-semibold text-foreground mb-3">客户问题</h3>
            <Card className="p-4">
              <p className="text-foreground leading-relaxed">{selectedInquiry.question}</p>
            </Card>
          </div>

          {/* 回复 */}
          {selectedInquiry.answer && (
            <div className="mx-4 mt-4">
              <h3 className="text-sm font-semibold text-foreground mb-3">您的回复</h3>
              <Card className="p-4 bg-primary/5 border border-primary/20">
                <div className="flex items-start gap-2 mb-2">
                  <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-xs text-green-600 font-medium">已回复</span>
                </div>
                <p className="text-foreground leading-relaxed">{selectedInquiry.answer}</p>
              </Card>
            </div>
          )}

          {/* 回复表单 */}
          {selectedInquiry.status === 'unanswered' && (
            <div className="mx-4 mt-6">
              <h3 className="text-sm font-semibold text-foreground mb-3">写回复</h3>
              <div className="space-y-3">
                <textarea
                  value={replyText}
                  onChange={(e) => setReplyText(e.target.value)}
                  placeholder="请输入您的回复内容..."
                  rows={4}
                  className="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-primary"
                />
                <Button
                  onClick={handleReply}
                  disabled={!replyText.trim() || isReplying}
                  className="w-full bg-primary hover:bg-primary/90"
                >
                  {isReplying ? '提交中...' : '提交回复'}
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <button onClick={() => router.back()} className="p-1">
            <ArrowLeft className="w-6 h-6 text-foreground" />
          </button>
          <h1 className="text-lg font-semibold text-foreground">咨询管理</h1>
          <div className="w-8" />
        </div>
      </div>

      <div className="pb-20">
        {/* 统计 */}
        <div className="mx-4 mt-4 grid grid-cols-3 gap-3">
          <Card className="p-3 text-center">
            <div className="text-2xl font-bold text-foreground">{inquiries.length}</div>
            <div className="text-xs text-muted-foreground mt-1">总咨询</div>
          </Card>
          <Card className="p-3 text-center border border-orange-200 bg-orange-50">
            <div className="text-2xl font-bold text-orange-600">{unansweredCount}</div>
            <div className="text-xs text-orange-700 mt-1">待回答</div>
          </Card>
          <Card className="p-3 text-center border border-green-200 bg-green-50">
            <div className="text-2xl font-bold text-green-600">
              {inquiries.filter(i => i.status === 'answered').length}
            </div>
            <div className="text-xs text-green-700 mt-1">已回答</div>
          </Card>
        </div>

        {/* 筛选 */}
        <div className="mx-4 mt-4 flex gap-2">
          {(['all', 'unanswered', 'answered'] as const).map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                filter === f
                  ? 'bg-primary text-white'
                  : 'bg-muted text-foreground hover:bg-muted/80'
              }`}
            >
              {f === 'all' ? '全部' : f === 'unanswered' ? '待回答' : '已回答'}
            </button>
          ))}
        </div>

        {/* 咨询列表 */}
        <div className="mx-4 mt-4">
          {filteredInquiries.length > 0 ? (
            <div className="space-y-2">
              {filteredInquiries.map(inquiry => (
                <button
                  key={inquiry.id}
                  onClick={() => setSelectedInquiry(inquiry)}
                  className="w-full p-4 rounded-xl border border-border hover:border-primary/30 bg-card transition-all text-left"
                >
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex-1">
                      <h3 className="font-semibold text-foreground line-clamp-1">
                        {inquiry.productName}
                      </h3>
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-xs text-muted-foreground flex items-center gap-1">
                          <User className="w-3 h-3" /> {inquiry.customer}
                        </span>
                        <span className="text-xs text-muted-foreground flex items-center gap-1">
                          <Clock className="w-3 h-3" /> {inquiry.time}
                        </span>
                      </div>
                    </div>
                    {getStatusBadge(inquiry.status)}
                  </div>
                  <p className="text-sm text-foreground/70 line-clamp-2">
                    {inquiry.question}
                  </p>
                  {inquiry.status === 'unanswered' && (
                    <div className="mt-2 flex items-center gap-1 text-xs text-orange-600">
                      <AlertCircle className="w-3 h-3" /> 待您回复
                    </div>
                  )}
                </button>
              ))}
            </div>
          ) : (
            <Card className="p-8 text-center">
              <div className="flex items-center justify-center gap-2 mb-2">
                <MessageSquare className="w-6 h-6 text-muted-foreground" />
              </div>
              <div className="text-muted-foreground">暂无咨询</div>
            </Card>
          )}
        </div>
      </div>
    </div>
  )
}
