// apps/mobile/src/pages_backup_20260609/courses/id-detail/learn/index.vue
<template>
  <view class="page">
    <view class="nav-header"><view class="nav-left" @click="goBack"><text>←</text><text class="nav-title">{{course.title}}</text></view><view style="width:48rpx"/></view>

    <view class="info-bar">
      <view class="progress-ring"><text class="pr-pct">{{progress.progressPercent}}%</text></view>
      <view class="ib-info"><text class="ib-title">{{course.title}}</text><view class="ib-instructor"><text class="ib-avatar">{{course.instructor.name[0]}}</text><text>{{course.instructor.name}}</text></view><text class="ib-meta">已学{{progress.completedLessons.length}}/{{progress.totalLessons}}节·🕐{{Math.floor(progress.studyTime/60)}}时{{progress.studyTime%60}}分</text></view>
    </view>

    <view class="tab-bar"><view v-for="t in tabs" :key="t.id" class="tab" :class="{act:activeTab===t.id}" @click="activeTab=t.id"><text>{{t.icon}} {{t.label}} {{t.count}}</text></view></view>

    <scroll-view v-if="!isLoading" scroll-y class="content" :style="{height:'calc(100vh - 56px - 56px - 56px - 140rpx)'}">
      <!-- 目录 -->
      <view v-if="activeTab==='catalog'" class="panel">
        <view v-for="c in chapters" :key="c.id" class="ch-card">
          <view class="ch-head" @click="toggleCh(c.id)"><text class="ch-check">{{isChDone(c)?'✓':completedIn(c)+'/'+c.lessons.length}}</text><view class="ch-info"><text class="ch-title">{{c.title}}</text><text class="ch-dur">{{c.lessons.length}}节·{{c.duration}}分钟</text></view><text class="ch-arrow" :class="{exp:expanded.has(c.id)}">▼</text></view>
          <view v-if="expanded.has(c.id)" class="ch-body">
            <view v-for="(l,i) in c.lessons" :key="l.id" class="l-item" @click="goPlayer(l.id)">
              <text class="l-icon">{{l.isCompleted?'✓':!c.isFree&&!l.isFree?'🔒':'▶'}}</text><view class="l-info"><text class="l-title" :class="{done:l.isCompleted}">{{i+1}}. {{l.title}}</text></view><text v-if="l.isFree" class="l-free">试看</text><text class="l-dur">{{l.duration}}分钟</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 笔记 -->
      <view v-if="activeTab==='notes'" class="panel">
        <view v-for="n in notes" :key="n.id" class="note-card"><text class="nc-chapter">{{n.chapterTitle}}</text><text class="nc-lesson">{{n.lessonTitle}}</text><text class="nc-content">{{n.content}}</text><text class="nc-date">{{n.createdAt}}</text></view>
        <view v-if="notes.length===0" class="empty">📄 暂无笔记</view>
      </view>

      <!-- 问答 -->
      <view v-if="activeTab==='questions'" class="panel">
        <view class="ask-btn" @click="showAsk=true">💬 我要提问</view>
        <view v-for="q in questions" :key="q.id" class="q-card"><view class="qc-head"><text class="qc-avatar">{{q.author.name[0]}}</text><view><text class="qc-name">{{q.author.name}}</text><text class="qc-time">{{q.createdAt}}</text></view></view><text class="qc-content">{{q.content}}</text><view class="qc-foot"><text>{{q.chapterTitle}}</text><text class="qc-answers">{{q.answers}}条回答</text><text v-if="q.isAnswered" class="qc-answered">已解答</text></view></view>
      </view>
      <view style="height:48rpx"/>
    </scroll-view>

    <view class="bottom-bar"><view class="bb-btn" @click="goPlayer(progress.lastLesson.id)">▶ 继续学习·{{progress.lastLesson.title}}</view></view>

    <view v-if="showAsk" class="modal-mask" @click="showAsk=false"/>
    <view v-if="showAsk" class="ask-modal"><view class="am-head"><text>我要提问</text><text class="am-close" @click="showAsk=false">✕</text></view><textarea v-model="askContent" class="am-textarea" placeholder="请输入问题..." :rows="5"/><view class="am-btn" :class="{dis:!askContent.trim()}" @click="submitAsk">提交问题</view></view>
  </view>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { onPullDownRefresh } from '@dcloudio/uni-app'
const isLoading=ref(true),activeTab=ref<'catalog'|'notes'|'questions'>('catalog'),expanded=ref(new Set(['c1','c2'])),showAsk=ref(false),askContent=ref('')

const course={title:'八字命理入门到精通',instructor:{name:'李明远'}}
const progress={courseId:'1',completedLessons:['l1','l2','l3','l4','l5'],totalLessons:32,progressPercent:15,lastLesson:{id:'l6',title:'天干地支的阴阳属性'},studyTime:180}
const tabs=[{id:'catalog' as const,label:'目录',icon:'📚',count:3},{id:'notes' as const,label:'笔记',icon:'📄',count:3},{id:'questions' as const,label:'问答',icon:'💬',count:3}]

const chapters=ref([{id:'c1',title:'第一章 八字基础概念',duration:180,isFree:true,lessons:[{id:'l1',title:'什么是八字命理',duration:15,isFree:true,isCompleted:true},{id:'l2',title:'八字的起源与发展',duration:18,isFree:true,isCompleted:true},{id:'l3',title:'四柱八字的构成',duration:20,isFree:true,isCompleted:true}]},{id:'c2',title:'第二章 天干地支详解',duration:240,isFree:false,lessons:[{id:'l4',title:'十天干基础',duration:25,isFree:false,isCompleted:true},{id:'l5',title:'十二地支基础',duration:25,isFree:false,isCompleted:true},{id:'l6',title:'天干地支的阴阳属性',duration:22,isFree:false,isCompleted:false},{id:'l7',title:'干支的五行属性',duration:28,isFree:false,isCompleted:false}]},{id:'c3',title:'第三章 排盘方法',duration:300,isFree:false,lessons:[{id:'l8',title:'年柱的推算',duration:30,isFree:false,isCompleted:false},{id:'l9',title:'月柱的推算',duration:32,isFree:false,isCompleted:false},{id:'l10',title:'日柱的推算',duration:28,isFree:false,isCompleted:false}]}])
const notes=[{id:'n1',content:'八字由年、月、日、时四柱组成',chapterTitle:'第一章 八字基础概念',lessonTitle:'四柱八字的构成',createdAt:'2024-01-15'},{id:'n2',content:'十天干：甲乙丙丁戊己庚辛壬癸',chapterTitle:'第二章 天干地支详解',lessonTitle:'十天干基础',createdAt:'2024-01-16'},{id:'n3',content:'十二地支：子丑寅卯辰巳午未申酉戌亥',chapterTitle:'第二章 天干地支详解',lessonTitle:'十二地支基础',createdAt:'2024-01-16'}]
const questions=[{id:'q1',content:'请问老师，为什么说八字中日柱最重要？',author:{name:'学习者小王'},chapterTitle:'第一章',createdAt:'2024-01-18',answers:3,isAnswered:true},{id:'q2',content:'天干地支的阴阳划分有什么实际应用意义？',author:{name:'命理新手'},chapterTitle:'第二章',createdAt:'2024-01-17',answers:5,isAnswered:true},{id:'q3',content:'如何判断一个八字的五行是否平衡？',author:{name:'易学爱好者'},chapterTitle:'第三章',createdAt:'2024-01-16',answers:0,isAnswered:false}]

function completedIn(c:any){return c.lessons.filter((l:any)=>l.isCompleted).length}
function isChDone(c:any){return completedIn(c)===c.lessons.length}
function toggleCh(id:string){const s=new Set(expanded.value);s.has(id)?s.delete(id):s.add(id);expanded.value=s}
function goPlayer(id:string){uni.navigateTo({url:'/pages/courses/id-detail/player/index'})}
function submitAsk(){showAsk.value=false;askContent.value=''}

function goBack(){uni.navigateBack()}
onMounted(async()=>{await new Promise(r=>setTimeout(r,600));isLoading.value=false})
onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))
</script>
<style scoped>
.page{background:#FAF8F5;min-height:100vh}
.nav-header{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5;position:sticky;top:0;z-index:40}
.nav-left{display:flex;align-items:center;gap:12rpx;font-size:36rpx;color:#2C2C2C}.nav-title{font-size:26rpx;font-weight:500;max-width:440rpx;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.info-bar{display:flex;align-items:center;gap:20rpx;padding:24rpx;background:#fff;border-bottom:1px solid #E8E0D5}
.progress-ring{width:100rpx;height:100rpx;border-radius:50%;border:6rpx solid #E8E0D5;display:flex;align-items:center;justify-content:center;flex-shrink:0}.pr-pct{font-size:28rpx;font-weight:700;color:#C41E3A}
.ib-title{font-size:28rpx;font-weight:600;color:#2C2C2C;display:block}.ib-instructor{display:flex;align-items:center;gap:8rpx;margin-top:4rpx;font-size:22rpx;color:#999}.ib-avatar{width:36rpx;height:36rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:18rpx;color:#999}.ib-meta{font-size:20rpx;color:#999;margin-top:4rpx;display:block}
.tab-bar{display:flex;background:#fff;border-bottom:1px solid #E8E0D5;position:sticky;top:0;z-index:30}.tab{flex:1;text-align:center;padding:20rpx;font-size:24rpx;color:#999;border-bottom:2rpx solid transparent}.tab.act{color:#C41E3A;border-bottom-color:#C41E3A}
.content{padding:24rpx}
.panel{}.ch-card{background:#fff;border-radius:20rpx;overflow:hidden;margin-bottom:16rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.ch-head{display:flex;align-items:center;gap:16rpx;padding:20rpx 24rpx}.ch-check{width:48rpx;height:48rpx;border-radius:50%;background:rgba(196,30,58,.1);color:#C41E3A;display:flex;align-items:center;justify-content:center;font-size:22rpx;font-weight:600;flex-shrink:0}.ch-arrow{font-size:22rpx;color:#999;transition:transform .2s}.ch-arrow.exp{transform:rotate(180deg)}
.ch-info{flex:1}.ch-title{font-size:26rpx;font-weight:500;color:#2C2C2C;display:block}.ch-dur{font-size:20rpx;color:#999}
.ch-body{background:#FAF8F5;padding:0 24rpx 16rpx}.l-item{display:flex;align-items:center;gap:12rpx;padding:16rpx 0;border-bottom:1px solid #E8E0D5}.l-item:last-child{border-bottom:none}.l-icon{font-size:24rpx;width:36rpx;text-align:center}.l-info{flex:1}.l-title{font-size:24rpx;color:#2C2C2C}.l-title.done{color:#999}.l-free{font-size:18rpx;padding:2rpx 8rpx;background:rgba(34,197,94,.1);color:#22c55e;border-radius:6rpx}.l-dur{font-size:20rpx;color:#999}
.note-card{background:#fff;border-radius:16rpx;padding:20rpx;margin-bottom:12rpx;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.nc-chapter{font-size:20rpx;color:#C41E3A;display:block}.nc-lesson{font-size:20rpx;color:#999;margin-top:2rpx}.nc-content{font-size:26rpx;color:#2C2C2C;margin-top:8rpx;line-height:1.5}.nc-date{font-size:20rpx;color:#999;margin-top:8rpx;display:block}
.empty{text-align:center;padding:80rpx 0;font-size:26rpx;color:#999}
.ask-btn{width:100%;padding:24rpx;text-align:center;background:#fff;border:2rpx dashed #C41E3A;border-radius:20rpx;font-size:26rpx;color:#C41E3A;margin-bottom:16rpx}
.q-card{background:#fff;border-radius:16rpx;padding:20rpx;margin-bottom:12rpx;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.qc-head{display:flex;align-items:center;gap:12rpx;margin-bottom:12rpx}.qc-avatar{width:48rpx;height:48rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:20rpx;color:#999}.qc-name{font-size:24rpx;font-weight:500;color:#2C2C2C;display:block}.qc-time{font-size:20rpx;color:#999}.qc-content{font-size:26rpx;color:#2C2C2C;margin-bottom:12rpx}.qc-foot{display:flex;gap:16rpx;font-size:20rpx;color:#999}.qc-answers{color:#C41E3A}.qc-answered{background:rgba(34,197,94,.1);color:#22c55e;padding:2rpx 10rpx;border-radius:6rpx;font-size:18rpx}
.bottom-bar{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:1px solid #E8E0D5;padding:20rpx 24rpx;z-index:50}.bb-btn{padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:40rpx;font-size:28rpx;font-weight:600}
.modal-mask{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:100}.ask-modal{position:fixed;bottom:0;left:0;right:0;background:#fff;border-radius:32rpx 32rpx 0 0;padding:24rpx;z-index:101}.am-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20rpx;font-size:32rpx;font-weight:600;color:#2C2C2C}.am-close{font-size:28rpx;color:#999;padding:8rpx}.am-textarea{width:100%;padding:20rpx;background:#F5F1EB;border-radius:16rpx;font-size:24rpx;box-sizing:border-box;resize:none;margin-bottom:20rpx}.am-btn{padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:24rpx;font-size:28rpx;font-weight:600}.am-btn.dis{background:#D9D9D9;color:#999}
</style>

// v0-reference/app/courses/[id]/learn/page.tsx
"use client"

import { useState, useEffect } from "react"
import { useParams, useRouter } from "next/navigation"
import Link from "next/link"
import { ArrowLeft, Play, CheckCircle, Lock, BookOpen, MessageCircle, FileText, Clock, ChevronDown, ChevronUp, Send, X } from "lucide-react"
import { Card } from "@/components/ui/card"
import { cn } from "@/lib/utils"

// Mock data
const mockCourse = {
  id: "1",
  title: "八字命理入门到精通",
  cover: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
  instructor: { id: "1", name: "李明远", avatar: "https://i.pravatar.cc/100?img=11", title: "资深命理师" },
  totalLessons: 32,
  totalDuration: 1920,
}

const mockProgress = {
  courseId: "1",
  completedLessons: ["l1", "l2", "l3", "l4", "l5"],
  totalLessons: 32,
  progressPercent: 15,
  lastLesson: { id: "l6", chapterId: "c2", title: "天干地支的阴阳属性" },
  studyTime: 180,
}

const mockChapters = [
  {
    id: "c1",
    title: "第一章 八字基础概念",
    duration: 180,
    isFree: true,
    lessons: [
      { id: "l1", title: "什么是八字命理", duration: 15, isFree: true, isCompleted: true },
      { id: "l2", title: "八字的起源与发展", duration: 18, isFree: true, isCompleted: true },
      { id: "l3", title: "四柱八字的构成", duration: 20, isFree: true, isCompleted: true },
    ],
  },
  {
    id: "c2",
    title: "第二章 天干地支详解",
    duration: 240,
    isFree: false,
    lessons: [
      { id: "l4", title: "十天干基础", duration: 25, isFree: false, isCompleted: true },
      { id: "l5", title: "十二地支基础", duration: 25, isFree: false, isCompleted: true },
      { id: "l6", title: "天干地支的阴阳属性", duration: 22, isFree: false, isCompleted: false },
      { id: "l7", title: "干支的五行属性", duration: 28, isFree: false, isCompleted: false },
    ],
  },
  {
    id: "c3",
    title: "第三章 排盘方法",
    duration: 300,
    isFree: false,
    lessons: [
      { id: "l8", title: "年柱的推算", duration: 30, isFree: false, isCompleted: false },
      { id: "l9", title: "月柱的推算", duration: 32, isFree: false, isCompleted: false },
      { id: "l10", title: "日柱的推算", duration: 28, isFree: false, isCompleted: false },
    ],
  },
]

const mockNotes = [
  { id: "n1", content: "八字由年、月、日、时四柱组成，每柱包含天干地支，共八个字。", chapterId: "c1", chapterTitle: "第一章 八字基础概念", lessonTitle: "四柱八字的构成", createdAt: "2024-01-15" },
  { id: "n2", content: "十天干：甲乙丙丁戊己庚辛壬癸。其中甲丙戊庚壬为阳干，乙丁己辛癸为阴干。", chapterId: "c2", chapterTitle: "第二章 天干地支详解", lessonTitle: "十天干基础", timestamp: 320, createdAt: "2024-01-16" },
  { id: "n3", content: "十二地支：子丑寅卯辰巳午未申酉戌亥。对应十二生肖。", chapterId: "c2", chapterTitle: "第二章 天干地支详解", lessonTitle: "十二地支基础", timestamp: 180, createdAt: "2024-01-16" },
]

const mockQuestions = [
  { id: "q1", content: "请问老师，为什么说八字中日柱最重要？", author: { id: "u1", name: "学习者小王", avatar: "https://i.pravatar.cc/100?img=33" }, chapterTitle: "第一章", createdAt: "2024-01-18", answers: 3, isAnswered: true },
  { id: "q2", content: "天干地支的阴阳划分有什么实际应用意义？", author: { id: "u2", name: "命理新手", avatar: "https://i.pravatar.cc/100?img=44" }, chapterTitle: "第二章", createdAt: "2024-01-17", answers: 5, isAnswered: true },
  { id: "q3", content: "如何判断一个八字的五行是否平衡？", author: { id: "u3", name: "易学爱好者", avatar: "https://i.pravatar.cc/100?img=55" }, chapterTitle: "第三章", createdAt: "2024-01-16", answers: 0, isAnswered: false },
]

// 进度环组件
function ProgressRing({ percent, size = 80, strokeWidth = 6 }: { percent: number; size?: number; strokeWidth?: number }) {
  const radius = (size - strokeWidth) / 2
  const circumference = radius * 2 * Math.PI
  const strokeDashoffset = circumference - (percent / 100) * circumference

  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg className="transform -rotate-90" width={size} height={size}>
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="#E8E3DB"
          strokeWidth={strokeWidth}
        />
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="#C41E3A"
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={strokeDashoffset}
          strokeLinecap="round"
          className="transition-all duration-500"
        />
      </svg>
      <div className="absolute inset-0 flex items-center justify-center">
        <span className="text-[16px] font-bold text-[#C41E3A]">{percent}%</span>
      </div>
    </div>
  )
}

// 章节列表项
function ChapterItem({ 
  chapter, 
  isExpanded, 
  onToggle, 
  onLessonClick 
}: { 
  chapter: typeof mockChapters[0]
  isExpanded: boolean
  onToggle: () => void
  onLessonClick: (lessonId: string) => void
}) {
  const completedCount = chapter.lessons?.filter(l => l.isCompleted).length || 0
  const totalCount = chapter.lessons?.length || 0
  const isCompleted = completedCount === totalCount && totalCount > 0

  return (
    <div className="border-b border-[#E8E3DB] last:border-b-0">
      <button
        onClick={onToggle}
        className="w-full px-4 py-3 flex items-center justify-between active:bg-[#F5F0E8] transition-colors"
      >
        <div className="flex items-center gap-3">
          {isCompleted ? (
            <div className="w-6 h-6 rounded-full bg-[#C41E3A]/10 flex items-center justify-center">
              <CheckCircle className="w-4 h-4 text-[#C41E3A]" />
            </div>
          ) : (
            <div className="w-6 h-6 rounded-full bg-[#E8E3DB] flex items-center justify-center">
              <span className="text-[10px] font-bold text-[#666]">{completedCount}/{totalCount}</span>
            </div>
          )}
          <div className="text-left">
            <h3 className="text-[14px] font-medium text-[#2C2C2C]">{chapter.title}</h3>
            <p className="text-[12px] text-[#999]">{totalCount}节 · {chapter.duration}分钟</p>
          </div>
        </div>
        {isExpanded ? (
          <ChevronUp className="w-5 h-5 text-[#999]" />
        ) : (
          <ChevronDown className="w-5 h-5 text-[#999]" />
        )}
      </button>

      {isExpanded && chapter.lessons && (
        <div className="bg-[#FAFAFA] px-4 pb-2">
          {chapter.lessons.map((lesson, idx) => (
            <button
              key={lesson.id}
              onClick={() => onLessonClick(lesson.id)}
              className="w-full py-2.5 flex items-center gap-3 border-b border-[#E8E3DB]/50 last:border-b-0 active:bg-[#F0EBE3] transition-colors"
            >
              <div className="w-6 h-6 flex items-center justify-center">
                {lesson.isCompleted ? (
                  <CheckCircle className="w-4 h-4 text-[#C41E3A]" />
                ) : !chapter.isFree && !lesson.isFree ? (
                  <Lock className="w-4 h-4 text-[#999]" />
                ) : (
                  <Play className="w-4 h-4 text-[#666]" />
                )}
              </div>
              <div className="flex-1 text-left">
                <p className={cn(
                  "text-[13px]",
                  lesson.isCompleted ? "text-[#999]" : "text-[#2C2C2C]"
                )}>
                  {idx + 1}. {lesson.title}
                </p>
              </div>
              <div className="flex items-center gap-2">
                {lesson.isFree && (
                  <span className="text-[10px] text-[#52c41a] bg-[#52c41a]/10 px-1.5 py-0.5 rounded">试看</span>
                )}
                <span className="text-[11px] text-[#999]">{lesson.duration}分钟</span>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

// 笔记项
function NoteItem({ note }: { note: typeof mockNotes[0] }) {
  return (
    <Card className="p-3 border-0 shadow-sm bg-white rounded-lg">
      <div className="flex items-start gap-2 mb-2">
        <FileText className="w-4 h-4 text-[#C9A96E] mt-0.5 flex-shrink-0" />
        <div className="flex-1">
          <p className="text-[12px] text-[#C41E3A]">{note.chapterTitle}</p>
          <p className="text-[11px] text-[#999]">{note.lessonTitle} {note.timestamp && `· ${Math.floor(note.timestamp / 60)}:${(note.timestamp % 60).toString().padStart(2, '0')}`}</p>
        </div>
      </div>
      <p className="text-[13px] text-[#2C2C2C] leading-relaxed pl-6">{note.content}</p>
      <p className="text-[11px] text-[#999] mt-2 pl-6">{note.createdAt}</p>
    </Card>
  )
}

// 问答项
function QuestionItem({ question }: { question: typeof mockQuestions[0] }) {
  return (
    <Card className="p-3 border-0 shadow-sm bg-white rounded-lg">
      <div className="flex items-start gap-2.5">
        <img src={question.author.avatar} alt="" className="w-8 h-8 rounded-full object-cover" />
        <div className="flex-1">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[12px] font-medium text-[#2C2C2C]">{question.author.name}</span>
            <span className="text-[11px] text-[#999]">{question.createdAt}</span>
          </div>
          <p className="text-[13px] text-[#2C2C2C] leading-relaxed mb-2">{question.content}</p>
          <div className="flex items-center gap-3">
            <span className="text-[11px] text-[#999]">{question.chapterTitle}</span>
            <span className="text-[11px] text-[#C41E3A]">{question.answers}条回答</span>
            {question.isAnswered && (
              <span className="text-[10px] text-white bg-[#52c41a] px-1.5 py-0.5 rounded">已解答</span>
            )}
          </div>
        </div>
      </div>
    </Card>
  )
}

// 提问弹窗
function AskQuestionModal({ isOpen, onClose, onSubmit }: { isOpen: boolean; onClose: () => void; onSubmit: (content: string) => void }) {
  const [content, setContent] = useState("")

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-end">
      <div className="w-full bg-white rounded-t-2xl p-4 pb-8 animate-in slide-in-from-bottom">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-[16px] font-bold text-[#2C2C2C]">我要提问</h3>
          <button onClick={onClose} className="p-1">
            <X className="w-5 h-5 text-[#999]" />
          </button>
        </div>
        <textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          placeholder="请输入您的问题..."
          className="w-full h-32 p-3 bg-[#F5F0E8] rounded-lg text-[14px] text-[#2C2C2C] placeholder:text-[#999] resize-none focus:outline-none focus:ring-2 focus:ring-[#C41E3A]/30"
        />
        <button
          onClick={() => {
            if (content.trim()) {
              onSubmit(content)
              setContent("")
              onClose()
            }
          }}
          disabled={!content.trim()}
          className={cn(
            "w-full mt-4 py-3 rounded-full text-[14px] font-bold flex items-center justify-center gap-2 transition-all",
            content.trim()
              ? "bg-[#C41E3A] text-white active:bg-[#A01830]"
              : "bg-[#E8E3DB] text-[#999]"
          )}
        >
          <Send className="w-4 h-4" />
          提交问题
        </button>
      </div>
    </div>
  )
}

// 骨架屏
function LearnSkeleton() {
  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      <div className="bg-white p-4 animate-pulse">
        <div className="flex items-center gap-4">
          <div className="w-20 h-20 rounded-full bg-[#E8E3DB]" />
          <div className="flex-1 space-y-2">
            <div className="h-5 bg-[#E8E3DB] rounded w-3/4" />
            <div className="h-4 bg-[#E8E3DB] rounded w-1/2" />
          </div>
        </div>
      </div>
      <div className="p-4 space-y-3">
        {[1, 2, 3, 4].map(i => (
          <div key={i} className="h-20 bg-white rounded-lg animate-pulse" />
        ))}
      </div>
    </div>
  )
}

export default function CourseLearnPage() {
  const params = useParams()
  const router = useRouter()
  const [isLoading, setIsLoading] = useState(true)
  const [activeTab, setActiveTab] = useState<"catalog" | "notes" | "questions">("catalog")
  const [expandedChapters, setExpandedChapters] = useState<Set<string>>(new Set(["c1", "c2"]))
  const [showAskModal, setShowAskModal] = useState(false)

  useEffect(() => {
    // Simulate API loading
    const timer = setTimeout(() => setIsLoading(false), 800)
    return () => clearTimeout(timer)
  }, [])

  const toggleChapter = (chapterId: string) => {
    setExpandedChapters(prev => {
      const next = new Set(prev)
      next.has(chapterId) ? next.delete(chapterId) : next.add(chapterId)
      return next
    })
  }

  const handleLessonClick = (lessonId: string) => {
    router.push(`/courses/${params.id}/player?lesson=${lessonId}`)
  }

  const handleAskQuestion = (content: string) => {
    // TODO: Call courseApi.askQuestion
    console.log("Ask question:", content)
  }

  if (isLoading) return <LearnSkeleton />

  const tabs = [
    { id: "catalog", label: "目录", icon: BookOpen, count: mockChapters.length },
    { id: "notes", label: "笔记", icon: FileText, count: mockNotes.length },
    { id: "questions", label: "问答", icon: MessageCircle, count: mockQuestions.length },
  ]

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-24">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-40 bg-white border-b border-[#E8E3DB]">
        <div className="flex items-center px-4 h-11">
          <button onClick={() => router.back()} className="p-1 -ml-1">
            <ArrowLeft className="w-5 h-5 text-[#2C2C2C]" />
          </button>
          <h1 className="flex-1 text-center text-[16px] font-medium text-[#2C2C2C] truncate px-4">
            {mockCourse.title}
          </h1>
          <div className="w-6" />
        </div>
      </div>

      {/* 课程信息 + 进度 */}
      <div className="bg-white p-4 border-b border-[#E8E3DB]">
        <div className="flex items-center gap-4">
          <ProgressRing percent={mockProgress.progressPercent} />
          <div className="flex-1">
            <h2 className="text-[15px] font-bold text-[#2C2C2C] mb-1">{mockCourse.title}</h2>
            <div className="flex items-center gap-2 mb-2">
              <img src={mockCourse.instructor.avatar} alt="" className="w-5 h-5 rounded-full" />
              <span className="text-[12px] text-[#666]">{mockCourse.instructor.name}</span>
            </div>
            <div className="flex items-center gap-3 text-[11px] text-[#999]">
              <span>已学 {mockProgress.completedLessons.length}/{mockProgress.totalLessons} 节</span>
              <span>·</span>
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                {Math.floor(mockProgress.studyTime / 60)}小时{mockProgress.studyTime % 60}分钟
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Tab 切换 */}
      <div className="bg-white border-b border-[#E8E3DB] sticky top-11 z-30">
        <div className="flex">
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as typeof activeTab)}
              className={cn(
                "flex-1 py-3 flex items-center justify-center gap-1.5 border-b-2 transition-colors",
                activeTab === tab.id
                  ? "border-[#C41E3A] text-[#C41E3A]"
                  : "border-transparent text-[#666]"
              )}
            >
              <tab.icon className="w-4 h-4" />
              <span className="text-[13px] font-medium">{tab.label}</span>
              <span className={cn(
                "text-[11px] px-1.5 py-0.5 rounded-full",
                activeTab === tab.id ? "bg-[#C41E3A]/10" : "bg-[#F5F0E8]"
              )}>
                {tab.count}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Tab 内容 */}
      <div className="p-4">
        {/* 目录 Tab */}
        {activeTab === "catalog" && (
          <Card className="overflow-hidden border-0 shadow-sm bg-white rounded-xl">
            {mockChapters.map(chapter => (
              <ChapterItem
                key={chapter.id}
                chapter={chapter}
                isExpanded={expandedChapters.has(chapter.id)}
                onToggle={() => toggleChapter(chapter.id)}
                onLessonClick={handleLessonClick}
              />
            ))}
          </Card>
        )}

        {/* 笔记 Tab */}
        {activeTab === "notes" && (
          <div className="space-y-3">
            {mockNotes.length > 0 ? (
              mockNotes.map(note => <NoteItem key={note.id} note={note} />)
            ) : (
              <div className="text-center py-12">
                <FileText className="w-12 h-12 text-[#E8E3DB] mx-auto mb-3" />
                <p className="text-[14px] text-[#999]">暂无笔记</p>
                <p className="text-[12px] text-[#BBB] mt-1">学习时可以随时记录笔记</p>
              </div>
            )}
          </div>
        )}

        {/* 问答 Tab */}
        {activeTab === "questions" && (
          <div className="space-y-3">
            <button
              onClick={() => setShowAskModal(true)}
              className="w-full py-3 bg-white rounded-xl border border-dashed border-[#C41E3A] text-[#C41E3A] text-[13px] font-medium flex items-center justify-center gap-2 active:bg-[#C41E3A]/5"
            >
              <MessageCircle className="w-4 h-4" />
              我要提问
            </button>
            {mockQuestions.map(question => (
              <QuestionItem key={question.id} question={question} />
            ))}
          </div>
        )}
      </div>

      {/* 底部继续学习按钮 */}
      <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-[#E8E3DB] p-4 pb-8">
        <button
          onClick={() => handleLessonClick(mockProgress.lastLesson?.id || "l1")}
          className="w-full py-3 bg-gradient-to-r from-[#C41E3A] to-[#E74C3C] text-white text-[15px] font-bold rounded-full flex items-center justify-center gap-2 shadow-lg shadow-[#C41E3A]/30 active:scale-[0.98] transition-all"
        >
          <Play className="w-5 h-5" fill="white" />
          继续学习 · {mockProgress.lastLesson?.title}
        </button>
      </div>

      {/* 提问弹窗 */}
      <AskQuestionModal
        isOpen={showAskModal}
        onClose={() => setShowAskModal(false)}
        onSubmit={handleAskQuestion}
      />
    </div>
  )
}
