// app/merchant/circle-bindding/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Check, ChevronRight, Search, Users } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

// Mock data - 可用圈子列表
const mockCircles = [
  { id: '1', name: '八字算命爱好者', category: '算命', members: 1250, bound: false },
  { id: '2', name: '紫微斗数研究', category: '占卜', members: 980, bound: true },
  { id: '3', name: '道教文化传承', category: '道教', members: 650, bound: false },
  { id: '4', name: '中医养生圈', category: '健康', members: 2100, bound: false },
  { id: '5', name: '古籍收藏交流', category: '文化', members: 380, bound: false },
  { id: '6', name: '国学经典讨论', category: '国学', members: 1520, bound: false },
]

export default function CircleBindingPage() {
  const router = useRouter()
  const [circles, setCircles] = useState(mockCircles)
  const [searchText, setSearchText] = useState('')
  const [selectedCircles, setSelectedCircles] = useState<string[]>(
    mockCircles.filter(c => c.bound).map(c => c.id)
  )
  const [isSubmitting, setIsSubmitting] = useState(false)

  const filteredCircles = circles.filter(circle =>
    circle.name.toLowerCase().includes(searchText.toLowerCase()) ||
    circle.category.toLowerCase().includes(searchText.toLowerCase())
  )

  const handleToggleCircle = (id: string) => {
    setSelectedCircles(prev =>
      prev.includes(id) ? prev.filter(cId => cId !== id) : [...prev, id]
    )
  }

  const handleSubmit = async () => {
    setIsSubmitting(true)
    // Mock submission
    await new Promise(resolve => setTimeout(resolve, 1500))
    setIsSubmitting(false)
    // Show success toast
    router.push('/merchant/dashboard')
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <button onClick={() => router.back()} className="p-1">
            <ArrowLeft className="w-6 h-6 text-foreground" />
          </button>
          <h1 className="text-lg font-semibold text-foreground">绑定圈子</h1>
          <div className="w-8" />
        </div>
      </div>

      <div className="pb-24">
        {/* 说明 */}
        <div className="mx-4 mt-4 p-4 bg-primary/10 border border-primary/20 rounded-xl">
          <h3 className="font-semibold text-foreground mb-1">圈子绑定说明</h3>
          <p className="text-sm text-muted-foreground">
            绑定圈子后，您可以在该圈子中发布内容、与圈主进行合作。请选择您希望合作的圈子。
          </p>
        </div>

        {/* 搜索 */}
        <div className="mx-4 mt-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="搜索圈子名称或分类"
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              className="pl-10"
            />
          </div>
        </div>

        {/* 圈子列表 */}
        <div className="mx-4 mt-4">
          <h2 className="text-sm font-semibold text-foreground mb-3">
            可绑定圈子 ({filteredCircles.length})
          </h2>
          <div className="space-y-2">
            {filteredCircles.map(circle => (
              <button
                key={circle.id}
                onClick={() => handleToggleCircle(circle.id)}
                className={`w-full p-4 rounded-xl border transition-all flex items-center justify-between ${
                  selectedCircles.includes(circle.id)
                    ? 'border-primary bg-primary/5'
                    : 'border-border hover:border-primary/30'
                }`}
              >
                <div className="flex items-center gap-3 flex-1 text-left">
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                    selectedCircles.includes(circle.id)
                      ? 'bg-primary text-white'
                      : 'bg-muted'
                  }`}>
                    {selectedCircles.includes(circle.id) ? (
                      <Check className="w-6 h-6" />
                    ) : (
                      <Users className="w-6 h-6 text-foreground/60" />
                    )}
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground">{circle.name}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-xs px-2 py-0.5 bg-muted text-muted-foreground rounded-full">
                        {circle.category}
                      </span>
                      <span className="text-xs text-muted-foreground flex items-center gap-1">
                        <Users className="w-3 h-3" /> {circle.members} 人
                      </span>
                    </div>
                  </div>
                </div>
                <ChevronRight className={`w-5 h-5 text-foreground/40 transition-transform ${
                  selectedCircles.includes(circle.id) ? 'text-primary' : ''
                }`} />
              </button>
            ))}
          </div>

          {filteredCircles.length === 0 && (
            <Card className="p-8 text-center">
              <div className="text-muted-foreground">未找到匹配的圈子</div>
            </Card>
          )}
        </div>

        {/* 统计 */}
        {selectedCircles.length > 0 && (
          <div className="mx-4 mt-6 p-4 bg-muted/50 rounded-xl">
            <div className="text-sm text-muted-foreground mb-2">
              已选择 {selectedCircles.length} 个圈子
            </div>
            <div className="space-y-1">
              {circles
                .filter(c => selectedCircles.includes(c.id))
                .map(c => (
                  <div key={c.id} className="text-sm text-foreground">
                    • {c.name}
                  </div>
                ))}
            </div>
          </div>
        )}
      </div>

      {/* 底部操作按钮 */}
      <div className="fixed bottom-0 left-0 right-0 bg-background border-t border-border p-4">
        <div className="flex gap-3">
          <Button
            variant="outline"
            onClick={() => router.back()}
            className="flex-1"
          >
            返回
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={isSubmitting || selectedCircles.length === 0}
            className="flex-1 bg-primary hover:bg-primary/90"
          >
            {isSubmitting ? '提交中...' : '确认绑定'}
          </Button>
        </div>
      </div>
    </div>
  )
}

// apps/mobile/src/pkg-merchant/circle-bindding/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="navbar" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="navbar-inner">
        <view class="nav-back" @tap="goBack">
          <AppIcon name="arrow-left" :size="24" color="#1f1f1f" />
        </view>
        <text class="nav-title">绑定圈子</text>
        <view class="nav-placeholder" />
      </view>
    </view>

    <scroll-view scroll-y class="scroll" :style="{ top: navH + 'px' }">
      <!-- 说明 -->
      <view class="intro">
        <text class="intro-title">圈子绑定说明</text>
        <text class="intro-text">绑定圈子后，您可以在该圈子中发布内容、与圈主进行合作。请选择您希望合作的圈子。</text>
      </view>

      <!-- 搜索 -->
      <view class="search-wrap">
        <view class="search-box">
          <AppIcon name="search" :size="16" color="#9ca3af" />
          <input
            v-model="searchText"
            class="search-input"
            placeholder="搜索圈子名称或分类"
            placeholder-class="search-ph"
          />
        </view>
      </view>

      <!-- 圈子列表 -->
      <view class="list-wrap">
        <text class="section-title">可绑定圈子 ({{ filteredCircles.length }})</text>
        <view class="circle-list">
          <view
            v-for="circle in filteredCircles"
            :key="circle.id"
            class="circle-item"
            :class="{ 'circle-item-active': selected.includes(circle.id) }"
            @tap="toggle(circle.id)"
          >
            <view class="circle-left">
              <view class="circle-avatar" :class="{ 'circle-avatar-active': selected.includes(circle.id) }">
                <AppIcon v-if="selected.includes(circle.id)" name="check" :size="24" color="#fff" />
                <AppIcon v-else name="users" :size="24" color="#9ca3af" />
              </view>
              <view class="circle-info">
                <text class="circle-name">{{ circle.name }}</text>
                <view class="circle-meta">
                  <view class="circle-cat">
                    <text class="circle-cat-text">{{ circle.category }}</text>
                  </view>
                  <view class="circle-members">
                    <AppIcon name="users" :size="12" color="#9ca3af" />
                    <text class="circle-members-text">{{ circle.members }} 人</text>
                  </view>
                </view>
              </view>
            </view>
            <AppIcon name="chevron-right" :size="20" :color="selected.includes(circle.id) ? '#c41e3a' : '#d1d5db'" />
          </view>
        </view>

        <view v-if="filteredCircles.length === 0" class="empty">
          <text class="empty-text">未找到匹配的圈子</text>
        </view>
      </view>

      <!-- 已选统计 -->
      <view v-if="selected.length > 0" class="summary">
        <text class="summary-title">已选择 {{ selected.length }} 个圈子</text>
        <view class="summary-list">
          <text v-for="c in selectedCircles" :key="c.id" class="summary-item">• {{ c.name }}</text>
        </view>
      </view>
      <view style="height: 100px" />
    </scroll-view>

    <!-- 底部操作按钮 -->
    <view class="footer">
      <view class="btn btn-outline" @tap="goBack">
        <text class="btn-outline-text">返回</text>
      </view>
      <view
        class="btn btn-primary"
        :class="{ 'btn-disabled': submitting || selected.length === 0 }"
        @tap="submit"
      >
        <text class="btn-primary-text">{{ submitting ? '提交中...' : '确认绑定' }}</text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack, go } from '@/utils/router'
import { merchantCircles } from '@/lib/merchant-data'

const statusBarHeight = ref(20)
const navH = ref(64)
uni.getSystemInfo({
  success: (r) => {
    statusBarHeight.value = r.statusBarHeight || 20
    navH.value = (r.statusBarHeight || 20) + 44
  },
})

const searchText = ref('')
const selected = ref<string[]>(merchantCircles.filter((c) => c.bound).map((c) => c.id))
const submitting = ref(false)

const filteredCircles = computed(() =>
  merchantCircles.filter(
    (c) =>
      c.name.toLowerCase().includes(searchText.value.toLowerCase()) ||
      c.category.toLowerCase().includes(searchText.value.toLowerCase()),
  ),
)

const selectedCircles = computed(() => merchantCircles.filter((c) => selected.value.includes(c.id)))

function toggle(id: string) {
  if (selected.value.includes(id)) {
    selected.value = selected.value.filter((x) => x !== id)
  } else {
    selected.value = [...selected.value, id]
  }
}

function submit() {
  if (submitting.value || selected.value.length === 0) return
  submitting.value = true
  setTimeout(() => {
    submitting.value = false
    uni.showToast({ title: '绑定成功', icon: 'success' })
    setTimeout(() => go('/merchant/dashboard'), 800)
  }, 1500)
}
</script>

<style scoped>
.page { min-height: 100vh; background: #fff; }
.navbar { position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: #fff; border-bottom: 1px solid #ededed; }
.navbar-inner { height: 44px; display: flex; align-items: center; justify-content: space-between; padding: 0 12px; }
.nav-back { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; }
.nav-title { font-size: 17px; font-weight: 600; color: #1f1f1f; }
.nav-placeholder { width: 32px; }
.scroll { position: fixed; left: 0; right: 0; bottom: 0; }

.intro { margin: 16px; padding: 16px; background: rgba(196, 30, 58, 0.08); border: 1px solid rgba(196, 30, 58, 0.2); border-radius: 12px; }
.intro-title { font-size: 15px; font-weight: 600; color: #1f1f1f; display: block; margin-bottom: 4px; }
.intro-text { font-size: 13px; color: #6b7280; line-height: 1.5; }

.search-wrap { padding: 0 16px; margin-top: 4px; }
.search-box { display: flex; align-items: center; gap: 8px; height: 40px; padding: 0 12px; background: #f5f5f5; border-radius: 8px; }
.search-input { flex: 1; font-size: 14px; color: #1f1f1f; }
.search-ph { color: #9ca3af; }

.list-wrap { padding: 16px; }
.section-title { font-size: 14px; font-weight: 600; color: #1f1f1f; display: block; margin-bottom: 12px; }
.circle-list { display: flex; flex-direction: column; gap: 8px; }
.circle-item { display: flex; align-items: center; justify-content: space-between; padding: 16px; border: 1px solid #ededed; border-radius: 12px; }
.circle-item-active { border-color: #c41e3a; background: rgba(196, 30, 58, 0.05); }
.circle-left { display: flex; align-items: center; gap: 12px; flex: 1; }
.circle-avatar { width: 40px; height: 40px; border-radius: 8px; background: #f3f4f6; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.circle-avatar-active { background: #c41e3a; }
.circle-info { flex: 1; }
.circle-name { font-size: 15px; font-weight: 600; color: #1f1f1f; display: block; }
.circle-meta { display: flex; align-items: center; gap: 8px; margin-top: 4px; }
.circle-cat { padding: 1px 8px; background: #f3f4f6; border-radius: 999px; }
.circle-cat-text { font-size: 11px; color: #6b7280; }
.circle-members { display: flex; align-items: center; gap: 4px; }
.circle-members-text { font-size: 11px; color: #9ca3af; }

.empty { padding: 32px; display: flex; justify-content: center; }
.empty-text { font-size: 14px; color: #9ca3af; }

.summary { margin: 24px 16px 0; padding: 16px; background: #f9fafb; border-radius: 12px; }
.summary-title { font-size: 13px; color: #6b7280; display: block; margin-bottom: 8px; }
.summary-list { display: flex; flex-direction: column; gap: 4px; }
.summary-item { font-size: 13px; color: #1f1f1f; }

.footer { position: fixed; bottom: 0; left: 0; right: 0; display: flex; gap: 12px; padding: 12px 16px; padding-bottom: calc(12px + env(safe-area-inset-bottom)); background: #fff; border-top: 1px solid #ededed; }
.btn { flex: 1; height: 44px; border-radius: 8px; display: flex; align-items: center; justify-content: center; }
.btn-outline { border: 1px solid #d1d5db; }
.btn-outline-text { font-size: 15px; color: #4b5563; }
.btn-primary { background: #c41e3a; }
.btn-primary-text { font-size: 15px; color: #fff; }
.btn-disabled { opacity: 0.5; }
</style>
