// v0-reference/app/institute/members/page.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { 
  ArrowLeft, Search, Crown, Award, Users, Star, 
  MessageCircle, BookOpen, Video, MapPin, Filter,
  ChevronRight, BadgeCheck
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"
import { cn } from "@/lib/utils"

// 成员职位类型
type MemberRole = "dean" | "vice_dean" | "secretary" | "member"

// 成员数据
interface InstituteMember {
  id: number
  name: string
  avatar: string
  role: MemberRole
  title: string // 擅长领域
  circleName: string
  circleMembers: number
  joinDate: string
  contributions: number // 分享次数
  isOnlineTeacher: boolean // 是否入选人才库
  location?: string
}

// 职位配置（院长金色 / 副院长银色 / 秘书长蓝色）
const roleConfig: Record<MemberRole, { label: string; color: string; bgColor: string; order: number }> = {
  dean: { label: "院长", color: "text-amber-600", bgColor: "bg-amber-100", order: 1 },
  vice_dean: { label: "副院长", color: "text-slate-500", bgColor: "bg-slate-100", order: 2 },
  secretary: { label: "秘书长", color: "text-blue-600", bgColor: "bg-blue-100", order: 3 },
  member: { label: "成员", color: "text-muted-foreground", bgColor: "bg-muted", order: 4 },
}

// 模拟数据
const mockMembers: InstituteMember[] = [
  { 
    id: 1, name: "张道玄", avatar: "", role: "dean", title: "八字命理", 
    circleName: "玄学命理研习社", circleMembers: 3280, joinDate: "2022-01-01",
    contributions: 48, isOnlineTeacher: true, location: "北京"
  },
  { 
    id: 2, name: "李易安", avatar: "", role: "secretary", title: "紫微斗数", 
    circleName: "紫微斗数研究会", circleMembers: 2150, joinDate: "2022-03-15",
    contributions: 36, isOnlineTeacher: true, location: "上海"
  },
  { 
    id: 3, name: "王明德", avatar: "", role: "secretary", title: "风水堪舆", 
    circleName: "风水地理学社", circleMembers: 1860, joinDate: "2022-02-20",
    contributions: 32, isOnlineTeacher: true, location: "广州"
  },
  { 
    id: 4, name: "陈太极", avatar: "", role: "vice_dean", title: "易经占卜", 
    circleName: "周易研习圈", circleMembers: 1520, joinDate: "2022-06-10",
    contributions: 28, isOnlineTeacher: true, location: "成都"
  },
  { 
    id: 5, name: "刘玄机", avatar: "", role: "vice_dean", title: "六爻预测", 
    circleName: "六爻占卦研究会", circleMembers: 1380, joinDate: "2022-08-05",
    contributions: 24, isOnlineTeacher: false, location: "杭州"
  },
  { 
    id: 6, name: "赵无极", avatar: "", role: "vice_dean", title: "奇门遁甲", 
    circleName: "奇门遁甲学社", circleMembers: 1260, joinDate: "2022-09-12",
    contributions: 22, isOnlineTeacher: true, location: "南京"
  },
  { 
    id: 7, name: "孙易理", avatar: "", role: "member", title: "梅花易数", 
    circleName: "梅花易数研习社", circleMembers: 980, joinDate: "2023-01-20",
    contributions: 18, isOnlineTeacher: false, location: "武汉"
  },
  { 
    id: 8, name: "周天师", avatar: "", role: "member", title: "面相手相", 
    circleName: "相学研究会", circleMembers: 1120, joinDate: "2023-03-08",
    contributions: 16, isOnlineTeacher: true, location: "西安"
  },
  { 
    id: 9, name: "吴玄真", avatar: "", role: "member", title: "起名择日", 
    circleName: "姓名学研习社", circleMembers: 860, joinDate: "2023-05-15",
    contributions: 14, isOnlineTeacher: false, location: "重庆"
  },
  { 
    id: 10, name: "郑易心", avatar: "", role: "member", title: "八字命理", 
    circleName: "命理实战研究会", circleMembers: 720, joinDate: "2023-07-22",
    contributions: 12, isOnlineTeacher: false, location: "天津"
  },
]

// 筛选选项
const filterOptions = [
  { id: "all", label: "全部" },
  { id: "leadership", label: "管理层" },
  { id: "teacher", label: "人才库" },
]

export default function InstituteMembersPage() {
  const [searchKeyword, setSearchKeyword] = useState("")
  const [activeFilter, setActiveFilter] = useState("all")
  
  // 筛选和排序成员
  const filteredMembers = mockMembers
    .filter(m => {
      if (activeFilter === "leadership") {
        return m.role === "dean" || m.role === "vice_dean" || m.role === "secretary"
      }
      if (activeFilter === "teacher") {
        return m.isOnlineTeacher
      }
      return true
    })
    .filter(m => {
      if (!searchKeyword) return true
      return m.name.includes(searchKeyword) || m.title.includes(searchKeyword)
    })
    .sort((a, b) => roleConfig[a.role].order - roleConfig[b.role].order)

  // 统计数据
  const stats = {
    total: mockMembers.length,
    leadership: mockMembers.filter(m => m.role !== "member").length,
    teachers: mockMembers.filter(m => m.isOnlineTeacher).length,
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-10 bg-background/95 backdrop-blur border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <Link href="/institute" className="p-1">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <h1 className="text-lg font-semibold">研究院成员</h1>
          </div>
          <Badge variant="secondary" className="text-xs">
            {stats.total}人
          </Badge>
        </div>
      </header>

      {/* 搜索栏 */}
      <div className="px-4 py-3 border-b border-border">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="搜索成员姓名或擅长领域"
            value={searchKeyword}
            onChange={(e) => setSearchKeyword(e.target.value)}
            className="pl-9 bg-secondary/30 border-0"
          />
        </div>
      </div>

      {/* 统计卡片 */}
      <div className="px-4 py-3">
        <div className="grid grid-cols-3 gap-2">
          <div className="text-center p-3 rounded-xl bg-gold/10">
            <p className="text-lg font-bold text-gold">{stats.total}</p>
            <p className="text-[10px] text-muted-foreground">总成员</p>
          </div>
          <div className="text-center p-3 rounded-xl bg-operator/10">
            <p className="text-lg font-bold text-operator">{stats.leadership}</p>
            <p className="text-[10px] text-muted-foreground">管理层</p>
          </div>
          <div className="text-center p-3 rounded-xl bg-success/10">
            <p className="text-lg font-bold text-success">{stats.teachers}</p>
            <p className="text-[10px] text-muted-foreground">入选人才库</p>
          </div>
        </div>
      </div>

      {/* 筛选Tab */}
      <div className="px-4 py-2 flex gap-2">
        {filterOptions.map(opt => (
          <Button
            key={opt.id}
            variant={activeFilter === opt.id ? "default" : "outline"}
            size="sm"
            onClick={() => setActiveFilter(opt.id)}
            className={cn(
              "rounded-full text-xs",
              activeFilter === opt.id && "bg-primary text-primary-foreground"
            )}
          >
            {opt.label}
          </Button>
        ))}
      </div>

      {/* 成员列表 */}
      <div className="px-4 py-3 space-y-3">
        {filteredMembers.map(member => {
          const config = roleConfig[member.role]
          return (
            <Link href={`/institute/members/${member.id}`} key={member.id}>
              <Card className="p-3 hover:bg-secondary/30 transition-colors">
                <div className="flex gap-3">
                  {/* 头像 */}
                  <div className="relative flex-shrink-0">
                    <div className="w-14 h-14 rounded-full bg-gradient-to-br from-gold/20 to-gold/20 flex items-center justify-center text-lg font-bold text-gold">
                      {member.name.slice(0, 1)}
                    </div>
                    {member.role !== "member" && (
                      <div className={cn(
                        "absolute -bottom-1 -right-1 w-5 h-5 rounded-full flex items-center justify-center",
                        config.bgColor
                      )}>
                        {member.role === "dean" ? (
                          <Crown className={cn("w-3 h-3", config.color)} />
                        ) : member.role === "vice_dean" ? (
                          <Award className={cn("w-3 h-3", config.color)} />
                        ) : (
                          <Star className={cn("w-3 h-3", config.color)} />
                        )}
                      </div>
                    )}
                  </div>
                  
                  {/* 信息 */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-foreground">{member.name}</span>
                      <Badge className={cn("text-[10px] px-1.5 py-0", config.bgColor, config.color)}>
                        {config.label}
                      </Badge>
                      {member.isOnlineTeacher && (
                        <Badge className="text-[10px] px-1.5 py-0 bg-success/10 text-success">
                          人才库
                        </Badge>
                      )}
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      擅长：{member.title}
                    </p>
                    <div className="flex items-center gap-3 mt-1.5 text-[10px] text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <Users className="w-3 h-3" />
                        {member.circleName}
                      </span>
                      <span className="flex items-center gap-1">
                        <Video className="w-3 h-3" />
                        分享{member.contributions}次
                      </span>
                      {member.location && (
                        <span className="flex items-center gap-1">
                          <MapPin className="w-3 h-3" />
                          {member.location}
                        </span>
                      )}
                    </div>
                  </div>
                  
                  <ChevronRight className="w-4 h-4 text-muted-foreground self-center flex-shrink-0" />
                </div>
              </Card>
            </Link>
          )
        })}
      </div>

      {/* 申请入口 */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t border-border">
        <Link href="/institute/member-apply">
          <Button className="w-full bg-gradient-to-r from-gold to-gold hover:from-gold hover:to-[#7A6548]">
            申请加入研究院
          </Button>
        </Link>
      </div>

      {/* 底部占位 */}
      <div className="h-20" />
    </div>
  )
}

// apps/mobile/src/pkg-institute/members/index.vue
<template>
  <view class="page">
    <view class="nav" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="nav-bar">
        <view class="nav-left">
          <view class="nav-back" @tap="goBack">
            <app-icon name="arrow-left" :size="20" color="#1a1a1a" />
          </view>
          <text class="nav-title">研究院成员</text>
        </view>
        <view class="nav-count"><text class="nav-count-text">{{ stats.total }}人</text></view>
      </view>
      <view class="search-wrap">
        <view class="search-box">
          <app-icon name="search" :size="16" color="#9ca3af" />
          <input class="search-input" v-model="keyword" placeholder="搜索成员姓名或擅长领域" placeholder-class="search-ph" />
        </view>
      </view>
    </view>

    <scroll-view scroll-y class="scroll" :style="{ height: scrollHeight + 'px' }">
      <!-- 统计 -->
      <view class="stats">
        <view class="stat-card" style="background:rgba(212,160,23,0.1)">
          <text class="stat-num" style="color:#d4a017">{{ stats.total }}</text>
          <text class="stat-label">总成员</text>
        </view>
        <view class="stat-card" style="background:rgba(196,30,58,0.1)">
          <text class="stat-num" style="color:#c41e3a">{{ stats.leadership }}</text>
          <text class="stat-label">管理层</text>
        </view>
        <view class="stat-card" style="background:rgba(22,163,74,0.1)">
          <text class="stat-num" style="color:#16a34a">{{ stats.teachers }}</text>
          <text class="stat-label">入选人才库</text>
        </view>
      </view>

      <!-- 筛选 -->
      <view class="filter-row">
        <view
          v-for="opt in filterOptions"
          :key="opt.id"
          class="filter-chip"
          :class="{ 'filter-chip-active': activeFilter === opt.id }"
          @tap="activeFilter = opt.id"
        >
          <text class="filter-text" :class="{ 'filter-text-active': activeFilter === opt.id }">{{ opt.label }}</text>
        </view>
      </view>

      <!-- 成员列表 -->
      <view class="list">
        <view v-if="loading" class="empty-state">
          <text class="empty-state-text">加载中...</text>
        </view>
        <view v-else-if="error" class="empty-state">
          <text class="empty-state-text">加载失败</text>
          <view class="retry-btn" @tap="fetchMembers"><text class="retry-btn-text">重试</text></view>
        </view>
        <view v-else-if="filteredMembers.length === 0" class="empty-state">
          <text class="empty-state-text">暂无成员</text>
        </view>
        <view
          v-for="m in filteredMembers"
          :key="m.id"
          class="member-card"
          @tap="goDetail(m.id)"
        >
          <view class="avatar-wrap">
            <view class="avatar">
              <text class="avatar-text">{{ m.name.slice(0, 1) }}</text>
            </view>
            <view v-if="m.role !== 'member'" class="role-badge" :style="{ background: roleConfig[m.role].bg }">
              <app-icon :name="roleIcon(m.role)" :size="12" :color="roleConfig[m.role].color" />
            </view>
          </view>

          <view class="member-info">
            <view class="name-row">
              <text class="m-name">{{ m.name }}</text>
              <view class="role-tag" :style="{ background: roleConfig[m.role].bg }">
                <text class="role-tag-text" :style="{ color: roleConfig[m.role].color }">{{ roleConfig[m.role].label }}</text>
              </view>
              <view v-if="m.isOnlineTeacher" class="teacher-tag">
                <text class="teacher-tag-text">人才库</text>
              </view>
            </view>
            <text class="m-title">擅长：{{ m.title }}</text>
            <view class="meta-row">
              <view class="meta-item">
                <app-icon name="users" :size="11" color="#9ca3af" />
                <text class="meta-text">{{ m.circleName }}</text>
              </view>
              <view class="meta-item">
                <app-icon name="video" :size="11" color="#9ca3af" />
                <text class="meta-text">分享{{ m.contributions }}次</text>
              </view>
            </view>
          </view>

          <app-icon name="chevron-right" :size="16" color="#9ca3af" />
        </view>
      </view>
      <view class="bottom-pad" />
    </scroll-view>

    <!-- 申请入口 -->
    <view class="footer">
      <view class="footer-btn" @tap="goApply">
        <text class="footer-btn-text">申请加入研究院</text>
      </view>
    </view>
  </view>

  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { onMounted } from '@dcloudio/uni-app'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack, navigateTo } from '@/utils/router'
import {
  instituteApi,
  memberRoleConfig as roleConfig,
  memberFilterOptions as filterOptions,
  type InstituteMember,
  type MemberRole,
} from '@/lib/institute-data'

const statusBarHeight = ref(0)
const scrollHeight = ref(600)
try {
  const info = uni.getSystemInfoSync()
  statusBarHeight.value = info.statusBarHeight || 0
  scrollHeight.value = (info.windowHeight || 700) - statusBarHeight.value - 44 - 52 - 64
} catch (e) {}

const keyword = ref('')
const activeFilter = ref('all')
const members = ref<InstituteMember[]>([])
const loading = ref(true)
const error = ref(false)

async function fetchMembers() {
  loading.value = true
  error.value = false
  try {
    members.value = await instituteApi.getMembers()
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchMembers()
})

const stats = computed(() => ({
  total: members.value.length,
  leadership: members.value.filter(m => m.role !== 'member').length,
  teachers: members.value.filter(m => m.isOnlineTeacher).length,
}))

const filteredMembers = computed(() => members.value
  .filter(m => {
    if (activeFilter.value === 'leadership') return m.role === 'dean' || m.role === 'vice_dean' || m.role === 'secretary'
    if (activeFilter.value === 'teacher') return m.isOnlineTeacher
    return true
  })
  .filter(m => !keyword.value || m.name.includes(keyword.value) || m.title.includes(keyword.value))
  .sort((a, b) => roleConfig[a.role].order - roleConfig[b.role].order)
)

function roleIcon(role: MemberRole) {
  if (role === 'dean') return 'crown'
  if (role === 'vice_dean') return 'award'
  return 'star'
}
function goDetail(id: number) {
  navigateTo(`/institute/members/${id}`)
}
function goApply() {
  navigateTo('/institute/member-apply')
}
</script>

<style scoped>
.page { min-height: 100vh; background: #f5f5f5; }
.nav { position: sticky; top: 0; z-index: 20; background: rgba(255,255,255,0.95); border-bottom: 1px solid #ededed; }
.nav-bar { display: flex; align-items: center; justify-content: space-between; height: 44px; padding: 0 12px; }
.nav-left { display: flex; align-items: center; gap: 8px; }
.nav-back { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; }
.nav-title { font-size: 17px; font-weight: 600; color: #1a1a1a; }
.nav-count { padding: 2px 10px; background: #f3f4f6; border-radius: 999px; }
.nav-count-text { font-size: 12px; color: #4b5563; }
.search-wrap { padding: 0 16px 10px; }
.search-box { display: flex; align-items: center; gap: 8px; height: 36px; padding: 0 12px; background: #f3f4f6; border-radius: 8px; }
.search-input { flex: 1; font-size: 13px; color: #1a1a1a; }
.search-ph { color: #9ca3af; }

.scroll { width: 100%; }
.stats { display: flex; gap: 8px; padding: 12px 16px; }
.stat-card { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 4px; padding: 12px 0; border-radius: 12px; }
.stat-num { font-size: 18px; font-weight: 700; }
.stat-label { font-size: 10px; color: #9ca3af; }

.filter-row { display: flex; gap: 8px; padding: 0 16px 8px; }
.filter-chip { padding: 5px 16px; border-radius: 999px; border: 1px solid #d1d5db; background: #fff; }
.filter-chip-active { background: #c41e3a; border-color: #c41e3a; }
.filter-text { font-size: 12px; color: #4b5563; }
.filter-text-active { color: #fff; }

.list { padding: 4px 16px 12px; display: flex; flex-direction: column; gap: 12px; }
.member-card { display: flex; align-items: center; gap: 12px; background: #fff; border-radius: 12px; border: 1px solid #ededed; padding: 12px; }
.avatar-wrap { position: relative; flex-shrink: 0; }
.avatar { width: 56px; height: 56px; border-radius: 50%; background: rgba(212,160,23,0.15); display: flex; align-items: center; justify-content: center; }
.avatar-text { font-size: 20px; font-weight: 700; color: #d4a017; }
.role-badge { position: absolute; bottom: -2px; right: -2px; width: 20px; height: 20px; border-radius: 50%; display: flex; align-items: center; justify-content: center; border: 2px solid #fff; }
.member-info { flex: 1; min-width: 0; }
.name-row { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
.m-name { font-size: 15px; font-weight: 500; color: #1a1a1a; }
.role-tag { padding: 1px 7px; border-radius: 4px; }
.role-tag-text { font-size: 10px; }
.teacher-tag { padding: 1px 7px; border-radius: 4px; background: rgba(22,163,74,0.1); }
.teacher-tag-text { font-size: 10px; color: #16a34a; }
.m-title { display: block; font-size: 12px; color: #6b7280; margin-top: 3px; }
.meta-row { display: flex; align-items: center; gap: 12px; margin-top: 6px; }
.meta-item { display: flex; align-items: center; gap: 4px; }
.meta-text { font-size: 10px; color: #9ca3af; }

.bottom-pad { height: 16px; }

.empty-state { padding: 40px 0; display: flex; flex-direction: column; align-items: center; gap: 12px; }
.empty-state-text { font-size: 14px; color: #9ca3af; }
.retry-btn { padding: 6px 16px; background: #c41e3a; border-radius: 8px; }
.retry-btn-text { font-size: 13px; color: #fff; }
.footer { position: fixed; bottom: 0; left: 0; right: 0; padding: 12px 16px; padding-bottom: calc(12px + env(safe-area-inset-bottom)); background: #fff; border-top: 1px solid #ededed; }
.footer-btn { display: flex; align-items: center; justify-content: center; height: 44px; background: linear-gradient(90deg, #d4a017, #b8860b); border-radius: 8px; }
.footer-btn-text { font-size: 14px; color: #fff; font-weight: 500; }
</style>
