// apps/mobile/src/pkg-im/im/friend-requests/index.vue
<template>
  <view v-if="error" class="load-state">
    <text class="load-state-text">{{ error }}</text>
    <view class="retry-btn" @tap="loadData"><text class="retry-text">重试</text></view>
  </view>
  <view v-else class="page">
    <!-- 导航栏 -->
    <view class="nav">
      <view class="nav-btn" @tap="goBack">
        <app-icon name="arrow-left" :size="40" color="#1f2937" />
      </view>
      <text class="nav-title">好友请求</text>
      <view class="nav-placeholder" />
    </view>

    <!-- 骨架屏 -->
    <view v-if="loading" class="skeleton">
      <view class="sk-section-head"><view class="sk-line sk-w20" /></view>
      <view v-for="i in 3" :key="i" class="sk-item">
        <view class="sk-avatar" />
        <view class="sk-info">
          <view class="sk-line sk-w24" />
          <view class="sk-line sk-w32" />
          <view class="sk-line sk-w48" />
        </view>
        <view class="sk-actions">
          <view class="sk-btn" />
          <view class="sk-btn" />
        </view>
      </view>
    </view>

    <!-- 内容 -->
    <view v-else-if="hasAny" class="content">
      <!-- 待处理 -->
      <view v-if="pending.length > 0" class="section">
        <view class="section-head">
          <text class="section-title">待处理 ({{ pending.length }})</text>
          <view class="approve-all" @tap="handleApproveAll">
            <text class="approve-all-text">{{ approveAllLoading ? '处理中...' : '全部同意' }}</text>
          </view>
        </view>
        <view class="req-list">
          <view v-for="req in pending" :key="req.id" class="req-item">
            <image lazy-load class="avatar" :src="req.fromUser.avatar" mode="aspectFill" @tap="goUser(req.fromUser.id)" />
            <view class="req-info">
              <view class="req-name-row">
                <text class="req-name">{{ req.fromUser.nickname }}</text>
              </view>
              <text v-if="req.fromUser.signature" class="req-signature">{{ req.fromUser.signature }}</text>
              <text v-if="req.message" class="req-message">{{ req.message }}</text>
              <text class="req-time">{{ req.createdAt }}</text>
            </view>
            <view class="req-actions">
              <view class="btn btn-reject" @tap="openRejectDialog(req)">
                <app-icon name="x" :size="32" color="#1f2937" />
              </view>
              <view class="btn btn-approve" @tap="handleApprove(req)">
                <text v-if="processingIds.includes(req.id)" class="dots">...</text>
                <app-icon v-else name="check" :size="32" color="#ffffff" />
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 已处理 -->
      <view v-if="processed.length > 0" class="section">
        <view class="section-head clickable" @tap="showProcessed = !showProcessed">
          <text class="section-title">已处理 ({{ processed.length }})</text>
          <app-icon :name="showProcessed ? 'chevron-up' : 'chevron-down'" :size="32" color="#9ca3af" />
        </view>
        <view v-if="showProcessed" class="req-list">
          <view v-for="req in processed" :key="req.id" class="req-item processed">
            <image lazy-load class="avatar avatar-sm" :src="req.fromUser.avatar" mode="aspectFill" />
            <view class="req-info">
              <view class="req-name-row">
                <text class="req-name-sm">{{ req.fromUser.nickname }}</text>
                <view class="status-tag">
                  <app-icon
                    :name="req.status === 'approved' ? 'check-circle' : req.status === 'rejected' ? 'x-circle' : 'clock'"
                    :size="28"
                    :color="req.status === 'approved' ? '#22c55e' : req.status === 'rejected' ? '#ef4444' : '#9ca3af'"
                  />
                  <text class="status-text">{{ statusText(req.status) }}</text>
                </view>
              </view>
              <text v-if="req.message" class="req-message-sm">{{ req.message }}</text>
              <text class="req-time">{{ req.processedAt || req.createdAt }}</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 仅待处理为空 -->
      <view v-if="pending.length === 0 && processed.length > 0" class="empty-inline">
        <app-icon name="users" :size="96" color="#9ca3af" />
        <text class="empty-text">暂无待处理的好友请求</text>
      </view>
    </view>

    <!-- 全空态 -->
    <view v-else class="empty">
      <app-icon name="user-plus" :size="96" color="#9ca3af" />
      <text class="empty-text">暂无好友请求</text>
    </view>

    <!-- 拒绝确认弹窗 -->
    <view v-if="rejectDialog.open" class="mask center" @tap="closeReject">
      <view class="dialog" @tap.stop>
        <text class="dialog-title">拒绝好友请求</text>
        <text class="dialog-desc">确定要拒绝 {{ rejectDialog.userName }} 的好友请求吗？</text>
        <textarea
          class="dialog-textarea"
          v-model="rejectReason"
          placeholder="可选：填写拒绝理由"
          placeholder-class="dialog-ph"
          :maxlength="-1"
          auto-height
        />
        <view class="dialog-actions">
          <view class="dialog-btn cancel" @tap="closeReject">取消</view>
          <view class="dialog-btn confirm" @tap="handleReject">拒绝</view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { navigateTo, goBack as routerBack } from '@/utils/router'
import {
  imApi,
  getRequestStatusText,
  type FriendRequestItem,
  type FriendRequestStatus,
} from '@/lib/im-data'

const loading = ref(true)
const error = ref('')
const pending = ref<FriendRequestItem[]>([])
const processed = ref<FriendRequestItem[]>([])

async function loadData() {
  loading.value = true
  error.value = ''
  try {
    const res = await imApi.getFriendRequests()
    pending.value = res.pending
    processed.value = res.processed
  } catch (e) {
    error.value = (e as Error)?.message || '加载好友请求失败，请重试'
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})

const showProcessed = ref(false)
const processingIds = ref<string[]>([])
const approveAllLoading = ref(false)

const rejectDialog = ref<{ open: boolean; requestId: string | null; userName: string }>({
  open: false,
  requestId: null,
  userName: '',
})
const rejectReason = ref('')

const hasAny = computed(() => pending.value.length > 0 || processed.value.length > 0)

function statusText(status: FriendRequestStatus) {
  return getRequestStatusText(status)
}

function goBack() {
  routerBack()
}
function goUser(id: string) {
  navigateTo(`/user/${id}`)
}

function nowStr() {
  const d = new Date()
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`
}

// 同意请求
async function handleApprove(req: FriendRequestItem) {
  if (processingIds.value.includes(req.id)) return
  processingIds.value.push(req.id)
  try {
    await imApi.handleFriendRequest(req.id, 'approve')
    pending.value = pending.value.filter((r) => r.id !== req.id)
    processed.value = [{ ...req, status: 'approved', processedAt: nowStr() }, ...processed.value]
    uni.showToast({ title: `已添加 ${req.fromUser.nickname} 为好友`, icon: 'none' })
  } catch (e) {
    uni.showToast({ title: (e as Error)?.message || '操作失败，请重试', icon: 'none' })
  } finally {
    processingIds.value = processingIds.value.filter((id) => id !== req.id)
  }
}

// 打开拒绝弹窗
function openRejectDialog(req: FriendRequestItem) {
  rejectDialog.value = { open: true, requestId: req.id, userName: req.fromUser.nickname }
  rejectReason.value = ''
}
function closeReject() {
  rejectDialog.value = { ...rejectDialog.value, open: false }
}

// 确认拒绝
async function handleReject() {
  const id = rejectDialog.value.requestId
  if (id == null) return
  const req = pending.value.find((r) => r.id === id)
  rejectDialog.value = { ...rejectDialog.value, open: false }
  if (!req) return
  try {
    await imApi.handleFriendRequest(id, 'reject')
    const reason = rejectReason.value || undefined
    pending.value = pending.value.filter((r) => r.id !== id)
    processed.value = [{ ...req, status: 'rejected', processedAt: nowStr(), rejectReason: reason }, ...processed.value]
    uni.showToast({ title: '已拒绝请求', icon: 'none' })
  } catch (e) {
    uni.showToast({ title: (e as Error)?.message || '操作失败，请重试', icon: 'none' })
  }
}

// 全部同意
async function handleApproveAll() {
  if (pending.value.length === 0 || approveAllLoading.value) return
  approveAllLoading.value = true
  const now = nowStr()
  const succeeded: FriendRequestItem[] = []
  let failed = 0
  try {
    for (const req of [...pending.value]) {
      try {
        await imApi.handleFriendRequest(req.id, 'approve')
        succeeded.push({ ...req, status: 'approved', processedAt: now })
      } catch {
        failed++
      }
    }
    const okIds = new Set(succeeded.map((r) => r.id))
    processed.value = [...succeeded, ...processed.value]
    pending.value = pending.value.filter((r) => !okIds.has(r.id))
    uni.showToast({
      title: failed > 0 ? `已添加${succeeded.length}位，${failed}位失败` : `已添加${succeeded.length}位好友`,
      icon: 'none',
    })
  } finally {
    approveAllLoading.value = false
  }
}
</script>

<style scoped>
.page { min-height: 100vh; background: #ffffff; }

/* 导航栏 */
.nav { position: sticky; top: 0; z-index: 50; display: flex; align-items: center; justify-content: space-between; height: 112rpx; padding: 0 32rpx; background: #ffffff; border-bottom: 2rpx solid #e5e7eb; }
.nav-btn { padding: 16rpx; margin-left: -16rpx; display: flex; align-items: center; justify-content: center; }
.nav-title { font-size: 32rpx; font-weight: 500; color: #111827; }
.nav-placeholder { width: 72rpx; }

/* 内容 */
.content { padding-bottom: 48rpx; }
.section { margin-bottom: 32rpx; }
.section-head { display: flex; align-items: center; justify-content: space-between; padding: 24rpx 32rpx; background: rgba(243,244,246,0.5); }
.section-head.clickable:active { background: rgba(243,244,246,0.8); }
.section-title { font-size: 28rpx; color: #6b7280; }
.approve-all { padding: 8rpx 16rpx; }
.approve-all-text { font-size: 28rpx; color: var(--brand); }

/* 请求项 */
.req-list { background: #ffffff; }
.req-item { display: flex; align-items: flex-start; gap: 24rpx; padding: 32rpx; border-bottom: 2rpx solid #f3f4f6; background: #ffffff; }
.req-item.processed { opacity: 0.7; }
.avatar { width: 96rpx; height: 96rpx; border-radius: 999rpx; background: #f3f4f6; flex-shrink: 0; }
.avatar-sm { width: 80rpx; height: 80rpx; }

.req-info { flex: 1; min-width: 0; }
.req-name-row { display: flex; align-items: center; gap: 16rpx; margin-bottom: 8rpx; }
.req-name { font-weight: 500; color: #111827; font-size: 30rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.req-name-sm { font-size: 28rpx; color: #111827; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.req-signature { display: block; font-size: 22rpx; color: #9ca3af; margin-bottom: 8rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.req-message { display: block; font-size: 28rpx; color: rgba(31,41,55,0.8); margin-bottom: 16rpx; line-height: 1.5; }
.req-message-sm { display: block; font-size: 22rpx; color: #9ca3af; margin-top: 8rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.req-time { display: block; font-size: 22rpx; color: #9ca3af; }

.status-tag { display: flex; align-items: center; gap: 6rpx; }
.status-text { font-size: 22rpx; color: #9ca3af; }

/* 操作按钮 */
.req-actions { display: flex; align-items: center; gap: 16rpx; flex-shrink: 0; }
.btn { height: 64rpx; min-width: 64rpx; padding: 0 24rpx; border-radius: 12rpx; display: flex; align-items: center; justify-content: center; }
.btn-reject { background: #ffffff; border: 2rpx solid #e5e7eb; }
.btn-approve { background: var(--brand); }
.dots { color: #ffffff; font-size: 32rpx; }

/* 空态 */
.empty, .empty-inline { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 96rpx 32rpx; gap: 24rpx; }
.empty-text { font-size: 28rpx; color: #6b7280; text-align: center; }

/* 骨架 */
.skeleton { }
.sk-section-head { padding: 24rpx 32rpx; background: rgba(243,244,246,0.5); }
.sk-item { display: flex; align-items: flex-start; gap: 24rpx; padding: 32rpx; border-bottom: 2rpx solid #f3f4f6; }
.sk-avatar { width: 96rpx; height: 96rpx; border-radius: 999rpx; background: #f0ebe5; flex-shrink: 0; }
.sk-info { flex: 1; }
.sk-line { height: 28rpx; background: #f0ebe5; border-radius: 8rpx; margin-bottom: 16rpx; }
.sk-w20 { width: 20%; }
.sk-w24 { width: 24%; }
.sk-w32 { width: 32%; }
.sk-w48 { width: 48%; }
.sk-actions { display: flex; gap: 16rpx; }
.sk-btn { width: 64rpx; height: 64rpx; border-radius: 12rpx; background: #f0ebe5; }

/* 遮罩与弹窗 */
.mask { position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 100; display: flex; }
.mask.center { align-items: center; justify-content: center; }
.dialog { width: 90%; max-width: 640rpx; background: #ffffff; border-radius: 24rpx; padding: 48rpx; }
.dialog-title { display: block; font-size: 34rpx; font-weight: 600; color: #111827; margin-bottom: 16rpx; }
.dialog-desc { display: block; font-size: 28rpx; color: #6b7280; line-height: 1.6; margin-bottom: 24rpx; }
.dialog-textarea { width: 100%; min-height: 96rpx; box-sizing: border-box; padding: 20rpx; border: 2rpx solid #e5e7eb; border-radius: 12rpx; font-size: 28rpx; color: #111827; margin-bottom: 32rpx; }
.dialog-ph { color: #9ca3af; }
.dialog-actions { display: flex; gap: 24rpx; }
.dialog-btn { flex: 1; height: 80rpx; border-radius: 12rpx; display: flex; align-items: center; justify-content: center; font-size: 30rpx; }
.dialog-btn.cancel { background: #f3f4f6; color: #374151; }
.dialog-btn.confirm { background: #dc2626; color: #ffffff; }

/* 加载/错误状态 */
.load-state { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; gap: 24rpx; }
.load-state-text { font-size: 28rpx; color: #8a8178; }
.retry-btn { padding: 16rpx 48rpx; background: var(--brand); border-radius: 999rpx; }
.retry-text { font-size: 28rpx; color: #fff; }
</style>

// v0-reference/app/im/friend-requests/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { 
  ArrowLeft, 
  Check, 
  X, 
  ChevronDown, 
  ChevronUp, 
  UserPlus, 
  Clock,
  CheckCircle,
  XCircle,
  Users
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Textarea } from '@/components/ui/textarea'
import { toast } from 'sonner'
import { DataState } from '@/components/data-state'
import { 
  getFriendRequests, 
  approveFriendRequest, 
  rejectFriendRequest,
  approveAllFriendRequests
} from '@/lib/api/im'
import type { FriendRequestItem, FriendRequestsResponse } from '@/lib/types/im'

export default function FriendRequestsPage() {
  const router = useRouter()
  
  // 数据状态
  const [data, setData] = useState<FriendRequestsResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  // UI 状态
  const [showProcessed, setShowProcessed] = useState(false)
  const [processingIds, setProcessingIds] = useState<Set<number>>(new Set())
  const [approveAllLoading, setApproveAllLoading] = useState(false)
  
  // 拒绝弹窗
  const [rejectDialog, setRejectDialog] = useState<{
    open: boolean
    requestId: number | null
    userName: string
  }>({ open: false, requestId: null, userName: '' })
  const [rejectReason, setRejectReason] = useState('')
  
  // 加载数据
  useEffect(() => {
    loadData()
  }, [])
  
  async function loadData() {
    setLoading(true)
    setError(null)
    try {
      const res = await getFriendRequests()
      if (res.code === 200) {
        setData(res.data)
      } else {
        setError(res.message || '加载失败')
      }
    } catch {
      setError('网络错误，请重试')
    } finally {
      setLoading(false)
    }
  }
  
  // 同意请求
  async function handleApprove(request: FriendRequestItem) {
    setProcessingIds(prev => new Set(prev).add(request.id))
    try {
      const res = await approveFriendRequest(request.id)
      if (res.code === 200) {
        toast.success(`已添加 ${request.fromUser.nickname} 为好友`)
        // 更新本地状态
        setData(prev => {
          if (!prev) return prev
          return {
            ...prev,
            pending: prev.pending.filter(r => r.id !== request.id),
            processed: [{ ...request, status: 'approved', processedAt: new Date().toISOString() } as FriendRequestItem, ...prev.processed],
            totalPending: prev.totalPending - 1,
          }
        })
      } else {
        toast.error(res.message || '操作失败')
      }
    } catch {
      toast.error('网络错误')
    } finally {
      setProcessingIds(prev => {
        const next = new Set(prev)
        next.delete(request.id)
        return next
      })
    }
  }
  
  // 打开拒绝弹窗
  function openRejectDialog(request: FriendRequestItem) {
    setRejectDialog({
      open: true,
      requestId: request.id,
      userName: request.fromUser.nickname,
    })
    setRejectReason('')
  }
  
  // 确认拒绝
  async function handleReject() {
    if (!rejectDialog.requestId) return
    
    setProcessingIds(prev => new Set(prev).add(rejectDialog.requestId!))
    setRejectDialog(prev => ({ ...prev, open: false }))
    
    try {
      const res = await rejectFriendRequest(rejectDialog.requestId, rejectReason || undefined)
      if (res.code === 200) {
        toast.success('已拒绝请求')
        // 更新本地状态
        setData(prev => {
          if (!prev) return prev
          const request = prev.pending.find(r => r.id === rejectDialog.requestId)
          if (!request) return prev
          return {
            ...prev,
            pending: prev.pending.filter(r => r.id !== rejectDialog.requestId),
            processed: [{ 
              ...request, 
              status: 'rejected', 
              processedAt: new Date().toISOString(),
              rejectReason: rejectReason || undefined 
            } as FriendRequestItem, ...prev.processed],
            totalPending: prev.totalPending - 1,
          }
        })
      } else {
        toast.error(res.message || '操作失败')
      }
    } catch {
      toast.error('网络错误')
    } finally {
      setProcessingIds(prev => {
        const next = new Set(prev)
        next.delete(rejectDialog.requestId!)
        return next
      })
    }
  }
  
  // 全部同意
  async function handleApproveAll() {
    if (!data || data.pending.length === 0) return
    
    setApproveAllLoading(true)
    try {
      const requestIds = data.pending.map(r => r.id)
      const res = await approveAllFriendRequests(requestIds)
      if (res.code === 200) {
        toast.success(res.message || `已添加${res.data.successCount}位好友`)
        // 更新本地状态
        setData(prev => {
          if (!prev) return prev
          const now = new Date().toISOString()
          return {
            ...prev,
            pending: [],
            processed: [
              ...prev.pending.map(r => ({ ...r, status: 'approved' as const, processedAt: now })),
              ...prev.processed,
            ],
            totalPending: 0,
          }
        })
      } else {
        toast.error(res.message || '操作失败')
      }
    } catch {
      toast.error('网络错误')
    } finally {
      setApproveAllLoading(false)
    }
  }
  
  // 获取状态图标
  function getStatusIcon(status: string) {
    switch (status) {
      case 'approved':
        return <CheckCircle className="w-4 h-4 text-green-500" />
      case 'rejected':
        return <XCircle className="w-4 h-4 text-red-500" />
      default:
        return <Clock className="w-4 h-4 text-muted-foreground" />
    }
  }
  
  // 获取状态文本
  function getStatusText(status: string) {
    switch (status) {
      case 'approved':
        return '已同意'
      case 'rejected':
        return '已拒绝'
      case 'expired':
        return '已过期'
      default:
        return '待处理'
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 导航栏 */}
      <header className="sticky top-0 z-50 bg-background border-b">
        <div className="flex items-center justify-between h-14 px-4">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <h1 className="text-base font-medium">好友请求</h1>
          <div className="w-9" />
        </div>
      </header>

      <DataState
        loading={loading}
        error={error}
        empty={!data || (data.pending.length === 0 && data.processed.length === 0)}
        emptyMessage="暂无好友请求"
        emptyIcon={<UserPlus className="w-12 h-12 text-muted-foreground" />}
        onRetry={loadData}
      >
        <div className="pb-6">
          {/* 待处理请求 */}
          {data && data.pending.length > 0 && (
            <div className="mb-4">
              <div className="flex items-center justify-between px-4 py-3 bg-muted/30">
                <span className="text-sm text-muted-foreground">
                  待处理 ({data.pending.length})
                </span>
                <Button 
                  variant="ghost" 
                  size="sm"
                  onClick={handleApproveAll}
                  disabled={approveAllLoading}
                  className="text-primary"
                >
                  {approveAllLoading ? '处理中...' : '全部同意'}
                </Button>
              </div>
              
              <div className="divide-y">
                {data.pending.map(request => (
                  <div 
                    key={request.id}
                    className="flex items-start gap-3 p-4 bg-background"
                  >
                    {/* 头像 */}
                    <Link href={`/user/${request.fromUser.id}`}>
                      <div className="w-12 h-12 rounded-full bg-muted overflow-hidden shrink-0">
                        <img 
                          src={request.fromUser.avatar} 
                          alt="" 
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </Link>
                    
                    {/* 信息 */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-medium truncate">
                          {request.fromUser.nickname}
                        </span>
                      </div>
                      
                      {request.fromUser.signature && (
                        <p className="text-xs text-muted-foreground truncate mb-1">
                          {request.fromUser.signature}
                        </p>
                      )}
                      
                      {request.message && (
                        <p className="text-sm text-foreground/80 mb-2">
                          {request.message}
                        </p>
                      )}
                      
                      <p className="text-xs text-muted-foreground">
                        {request.createdAt}
                      </p>
                    </div>
                    
                    {/* 操作按钮 */}
                    <div className="flex items-center gap-2 shrink-0">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => openRejectDialog(request)}
                        disabled={processingIds.has(request.id)}
                        className="h-8 px-3"
                      >
                        <X className="w-4 h-4" />
                      </Button>
                      <Button
                        size="sm"
                        onClick={() => handleApprove(request)}
                        disabled={processingIds.has(request.id)}
                        className="h-8 px-3 bg-primary"
                      >
                        {processingIds.has(request.id) ? (
                          <span className="animate-pulse">...</span>
                        ) : (
                          <Check className="w-4 h-4" />
                        )}
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 已处理请求 */}
          {data && data.processed.length > 0 && (
            <div>
              <button
                onClick={() => setShowProcessed(!showProcessed)}
                className="flex items-center justify-between w-full px-4 py-3 bg-muted/30"
              >
                <span className="text-sm text-muted-foreground">
                  已处理 ({data.processed.length})
                </span>
                {showProcessed ? (
                  <ChevronUp className="w-4 h-4 text-muted-foreground" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-muted-foreground" />
                )}
              </button>
              
              {showProcessed && (
                <div className="divide-y">
                  {data.processed.map(request => (
                    <div 
                      key={request.id}
                      className="flex items-start gap-3 p-4 bg-background opacity-70"
                    >
                      {/* 头像 */}
                      <div className="w-10 h-10 rounded-full bg-muted overflow-hidden shrink-0">
                        <img 
                          src={request.fromUser.avatar} 
                          alt="" 
                          className="w-full h-full object-cover"
                        />
                      </div>
                      
                      {/* 信息 */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-sm truncate">
                            {request.fromUser.nickname}
                          </span>
                          <div className="flex items-center gap-1">
                            {getStatusIcon(request.status)}
                            <span className="text-xs text-muted-foreground">
                              {getStatusText(request.status)}
                            </span>
                          </div>
                        </div>
                        
                        {request.message && (
                          <p className="text-xs text-muted-foreground truncate mt-1">
                            {request.message}
                          </p>
                        )}
                        
                        <p className="text-xs text-muted-foreground mt-1">
                          {request.processedAt || request.createdAt}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
          
          {/* 空态 - 仅待处理为空 */}
          {data && data.pending.length === 0 && data.processed.length > 0 && (
            <div className="flex flex-col items-center justify-center py-12 px-4">
              <Users className="w-12 h-12 text-muted-foreground mb-4" />
              <p className="text-muted-foreground text-center">
                暂无待处理的好友请求
              </p>
            </div>
          )}
        </div>
      </DataState>
      
      {/* 拒绝确认弹窗 */}
      <AlertDialog 
        open={rejectDialog.open} 
        onOpenChange={(open) => setRejectDialog(prev => ({ ...prev, open }))}
      >
        <AlertDialogContent className="max-w-[90%] rounded-xl">
          <AlertDialogHeader>
            <AlertDialogTitle>拒绝好友请求</AlertDialogTitle>
            <AlertDialogDescription>
              确定要拒绝 {rejectDialog.userName} 的好友请求吗？
            </AlertDialogDescription>
          </AlertDialogHeader>
          
          <div className="py-2">
            <Textarea
              placeholder="可选：填写拒绝理由"
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              className="resize-none"
              rows={2}
            />
          </div>
          
          <AlertDialogFooter>
            <AlertDialogCancel>取消</AlertDialogCancel>
            <AlertDialogAction onClick={handleReject} className="bg-destructive hover:bg-destructive/90">
              拒绝
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
      
      {/* 骨架屏 */}
      {loading && (
        <div className="absolute inset-0 top-14 bg-background">
          <div className="px-4 py-3 bg-muted/30">
            <Skeleton className="h-4 w-20" />
          </div>
          {[1, 2, 3].map(i => (
            <div key={i} className="flex items-start gap-3 p-4 border-b">
              <Skeleton className="w-12 h-12 rounded-full shrink-0" />
              <div className="flex-1 space-y-2">
                <Skeleton className="h-4 w-24" />
                <Skeleton className="h-3 w-32" />
                <Skeleton className="h-3 w-48" />
              </div>
              <div className="flex gap-2">
                <Skeleton className="w-8 h-8 rounded" />
                <Skeleton className="w-8 h-8 rounded" />
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
