// v0-reference/app/circles/[id]/guests/page.tsx
"use client"

import { useState } from "react"
import { useParams, useRouter } from "next/navigation"
import Link from "next/link"
import { 
  ChevronLeft, Plus, Search, MoreVertical, UserPlus, Crown, 
  Shield, Trash2, Edit, TrendingUp, FileText, BookOpen, Radio,
  Check, X, Clock, ChevronRight, Copy, QrCode
} from "lucide-react"

// Mock: 圈子嘉宾/老师列表
const mockGuests = [
  {
    id: "1",
    name: "张玄风",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zhang",
    title: "资深命理师",
    role: "guest" as const, // guest: 嘉宾, teacher: 老师
    joinedAt: "2024-01-10",
    status: "active" as const,
    stats: {
      articles: 28,
      courses: 3,
      lives: 12,
      totalRevenue: 12680.50,
      thisMonthRevenue: 2350.00,
    },
    revenueShare: 70, // 分成比例 70%
    permissions: ["article", "course", "live", "qa"],
  },
  {
    id: "2",
    name: "李易安",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=li",
    title: "紫微斗数讲师",
    role: "teacher" as const,
    joinedAt: "2024-02-15",
    status: "active" as const,
    stats: {
      articles: 15,
      courses: 5,
      lives: 8,
      totalRevenue: 8920.00,
      thisMonthRevenue: 1680.00,
    },
    revenueShare: 60,
    permissions: ["article", "course"],
  },
  {
    id: "3",
    name: "王命理",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=wang",
    title: "八字研究者",
    role: "guest" as const,
    joinedAt: "2024-03-01",
    status: "pending" as const, // 待审核
    stats: {
      articles: 0,
      courses: 0,
      lives: 0,
      totalRevenue: 0,
      thisMonthRevenue: 0,
    },
    revenueShare: 50,
    permissions: ["article"],
  },
]

// Mock: 待处理的邀请
const mockPendingInvites = [
  { id: "inv1", name: "陈风水", invitedAt: "2024-03-10", status: "pending" },
  { id: "inv2", name: "周易学", invitedAt: "2024-03-08", status: "expired" },
]

const permissionLabels: Record<string, string> = {
  article: "文章",
  course: "课程",
  live: "直播",
  qa: "问答",
  post: "帖子",
}

export default function GuestsManagePage() {
  const params = useParams()
  const router = useRouter()
  const circleId = params.id as string

  const [searchQuery, setSearchQuery] = useState("")
  const [activeTab, setActiveTab] = useState<"all" | "guest" | "teacher" | "pending">("all")
  const [showInviteModal, setShowInviteModal] = useState(false)
  const [showActionMenu, setShowActionMenu] = useState<string | null>(null)
  const [showEditModal, setShowEditModal] = useState<string | null>(null)

  // 筛选嘉宾
  const filteredGuests = mockGuests.filter(guest => {
    if (activeTab === "pending") return guest.status === "pending"
    if (activeTab === "guest") return guest.role === "guest" && guest.status === "active"
    if (activeTab === "teacher") return guest.role === "teacher" && guest.status === "active"
    return guest.status === "active"
  }).filter(guest => 
    guest.name.includes(searchQuery) || guest.title.includes(searchQuery)
  )

  const pendingCount = mockGuests.filter(g => g.status === "pending").length

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-white border-b border-muted">
        <div className="flex items-center justify-between px-4 h-14">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ChevronLeft className="w-5 h-5 text-foreground" />
          </button>
          <h1 className="font-semibold text-foreground">嘉宾/老师管理</h1>
          <button 
            onClick={() => setShowInviteModal(true)}
            className="p-2 -mr-2 text-primary"
          >
            <UserPlus className="w-5 h-5" />
          </button>
        </div>

        {/* 搜索 */}
        <div className="px-4 pb-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="搜索嘉宾/老师"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2.5 bg-background rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
            />
          </div>
        </div>

        {/* Tabs */}
        <div className="flex px-4 gap-2 pb-3">
          {[
            { key: "all", label: "全部" },
            { key: "guest", label: "嘉宾" },
            { key: "teacher", label: "老师" },
            { key: "pending", label: "待审核", count: pendingCount },
          ].map(tab => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key as typeof activeTab)}
              className={`px-4 py-1.5 rounded-full text-sm transition-all ${
                activeTab === tab.key
                  ? "bg-primary text-white"
                  : "bg-background text-muted-foreground"
              }`}
            >
              {tab.label}
              {tab.count ? <span className="ml-1 text-xs">({tab.count})</span> : null}
            </button>
          ))}
        </div>
      </div>

      {/* 嘉宾列表 */}
      <div className="p-4 space-y-3">
        {filteredGuests.length === 0 ? (
          <div className="text-center py-12">
            <UserPlus className="w-12 h-12 text-muted mx-auto mb-3" />
            <p className="text-muted-foreground text-sm">暂无嘉宾/老师</p>
            <button 
              onClick={() => setShowInviteModal(true)}
              className="mt-4 px-6 py-2 bg-primary text-white text-sm rounded-xl"
            >
              邀请嘉宾
            </button>
          </div>
        ) : (
          filteredGuests.map(guest => (
            <div 
              key={guest.id}
              className="bg-white rounded-2xl p-4 shadow-[0_2px_12px_rgba(0,0,0,0.04)]"
            >
              {/* 头部信息 */}
              <div className="flex items-start gap-3">
                <img alt="图片" 
                  src={guest.avatar} 
                  alt={guest.name}
                  className="w-12 h-12 rounded-xl"
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-medium text-foreground">{guest.name}</span>
                    <span className={`text-[10px] px-1.5 py-0.5 rounded ${
                      guest.role === "teacher" 
                        ? "bg-info/10 text-info" 
                        : "bg-gold/10 text-gold"
                    }`}>
                      {guest.role === "teacher" ? "老师" : "嘉宾"}
                    </span>
                    {guest.status === "pending" && (
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-orange-100 text-orange-600">
                        待审核
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5">{guest.title}</p>
                  <p className="text-[10px] text-muted-foreground mt-1">加入于 {guest.joinedAt}</p>
                </div>
                <button 
                  onClick={() => setShowActionMenu(showActionMenu === guest.id ? null : guest.id)}
                  className="p-2 -mr-2 text-muted-foreground"
                >
                  <MoreVertical className="w-5 h-5" />
                </button>
              </div>

              {/* 操作菜单 */}
              {showActionMenu === guest.id && (
                <div className="mt-3 pt-3 border-t border-muted flex gap-2">
                  <button 
                    onClick={() => { setShowEditModal(guest.id); setShowActionMenu(null) }}
                    className="flex-1 flex items-center justify-center gap-1 py-2 text-sm text-muted-foreground bg-background rounded-lg"
                  >
                    <Edit className="w-4 h-4" />
                    编辑
                  </button>
                  <Link 
                    href={`/circles/${circleId}/guests/${guest.id}/revenue`}
                    className="flex-1 flex items-center justify-center gap-1 py-2 text-sm text-muted-foreground bg-background rounded-lg"
                  >
                    <TrendingUp className="w-4 h-4" />
                    收益
                  </Link>
                  <button className="flex-1 flex items-center justify-center gap-1 py-2 text-sm text-red-500 bg-red-50 rounded-lg">
                    <Trash2 className="w-4 h-4" />
                    移除
                  </button>
                </div>
              )}

              {/* 权限标签 */}
              <div className="mt-3 flex flex-wrap gap-1.5">
                <span className="text-[10px] text-muted-foreground">可发布：</span>
                {guest.permissions.map(perm => (
                  <span key={perm} className="text-[10px] px-1.5 py-0.5 rounded bg-background text-muted-foreground">
                    {permissionLabels[perm]}
                  </span>
                ))}
              </div>

              {/* 数据统计 */}
              {guest.status === "active" && (
                <div className="mt-3 pt-3 border-t border-muted">
                  <div className="grid grid-cols-4 gap-2 text-center">
                    <div>
                      <div className="flex items-center justify-center gap-1 text-muted-foreground">
                        <FileText className="w-3 h-3" />
                        <span className="text-sm font-medium">{guest.stats.articles}</span>
                      </div>
                      <p className="text-[10px] text-muted-foreground">文章</p>
                    </div>
                    <div>
                      <div className="flex items-center justify-center gap-1 text-muted-foreground">
                        <BookOpen className="w-3 h-3" />
                        <span className="text-sm font-medium">{guest.stats.courses}</span>
                      </div>
                      <p className="text-[10px] text-muted-foreground">课程</p>
                    </div>
                    <div>
                      <div className="flex items-center justify-center gap-1 text-muted-foreground">
                        <Radio className="w-3 h-3" />
                        <span className="text-sm font-medium">{guest.stats.lives}</span>
                      </div>
                      <p className="text-[10px] text-muted-foreground">直播</p>
                    </div>
                    <div>
                      <div className="text-sm font-medium text-gold">
                        ¥{guest.stats.thisMonthRevenue.toFixed(0)}
                      </div>
                      <p className="text-[10px] text-muted-foreground">本月收益</p>
                    </div>
                  </div>
                  <div className="mt-2 flex items-center justify-between text-xs">
                    <span className="text-muted-foreground">分成比例：{guest.revenueShare}%</span>
                    <span className="text-muted-foreground">累计收益：¥{guest.stats.totalRevenue.toFixed(2)}</span>
                  </div>
                </div>
              )}

              {/* 待审核操作 */}
              {guest.status === "pending" && (
                <div className="mt-3 pt-3 border-t border-muted flex gap-2">
                  <button className="flex-1 flex items-center justify-center gap-1 py-2.5 text-sm text-white bg-primary rounded-xl">
                    <Check className="w-4 h-4" />
                    通过
                  </button>
                  <button className="flex-1 flex items-center justify-center gap-1 py-2.5 text-sm text-muted-foreground bg-background rounded-xl">
                    <X className="w-4 h-4" />
                    拒绝
                  </button>
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {/* 邀请嘉宾弹窗 */}
      {showInviteModal && (
        <InviteGuestModal 
          circleId={circleId}
          onClose={() => setShowInviteModal(false)} 
        />
      )}

      {/* 编辑嘉宾弹窗 */}
      {showEditModal && (
        <EditGuestModal
          guest={mockGuests.find(g => g.id === showEditModal)!}
          onClose={() => setShowEditModal(null)}
        />
      )}
    </div>
  )
}

// 邀请嘉宾弹窗
function InviteGuestModal({ circleId, onClose }: { circleId: string; onClose: () => void }) {
  const [inviteType, setInviteType] = useState<"link" | "search">("link")
  const [role, setRole] = useState<"guest" | "teacher">("guest")
  const [revenueShare, setRevenueShare] = useState(50)
  const [selectedPermissions, setSelectedPermissions] = useState<string[]>(["article"])
  
  const inviteLink = `https://rebugx.com/invite/${circleId}?role=${role}`

  const togglePermission = (perm: string) => {
    setSelectedPermissions(prev => 
      prev.includes(perm) ? prev.filter(p => p !== perm) : [...prev, perm]
    )
  }

  return (
    <div className="fixed inset-0 z-50 flex items-end">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative w-full bg-white rounded-t-3xl max-h-[85vh] overflow-hidden animate-in slide-in-from-bottom">
        <div className="flex items-center justify-between p-4 border-b border-muted">
          <button onClick={onClose} className="text-muted-foreground">取消</button>
          <span className="font-medium text-foreground">邀请嘉宾/老师</span>
          <button className="text-primary font-medium">确定</button>
        </div>

        <div className="p-4 space-y-4 overflow-y-auto max-h-[70vh]">
          {/* 邀请方式 */}
          <div className="flex gap-2">
            <button
              onClick={() => setInviteType("link")}
              className={`flex-1 py-2.5 rounded-xl text-sm ${
                inviteType === "link" ? "bg-primary text-white" : "bg-background text-muted-foreground"
              }`}
            >
              链接邀请
            </button>
            <button
              onClick={() => setInviteType("search")}
              className={`flex-1 py-2.5 rounded-xl text-sm ${
                inviteType === "search" ? "bg-primary text-white" : "bg-background text-muted-foreground"
              }`}
            >
              搜索用户
            </button>
          </div>

          {/* 角色选择 */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">角色类型</label>
            <div className="flex gap-2">
              <button
                onClick={() => setRole("guest")}
                className={`flex-1 p-3 rounded-xl border-2 text-left ${
                  role === "guest" ? "border-primary bg-primary/5" : "border-muted"
                }`}
              >
                <div className="flex items-center gap-2">
                  <Crown className={`w-5 h-5 ${role === "guest" ? "text-gold" : "text-muted-foreground"}`} />
                  <span className={`font-medium ${role === "guest" ? "text-foreground" : "text-muted-foreground"}`}>嘉宾</span>
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">受邀创作者，可发布内容</p>
              </button>
              <button
                onClick={() => setRole("teacher")}
                className={`flex-1 p-3 rounded-xl border-2 text-left ${
                  role === "teacher" ? "border-primary bg-primary/5" : "border-muted"
                }`}
              >
                <div className="flex items-center gap-2">
                  <Shield className={`w-5 h-5 ${role === "teacher" ? "text-info" : "text-muted-foreground"}`} />
                  <span className={`font-medium ${role === "teacher" ? "text-foreground" : "text-muted-foreground"}`}>老师</span>
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">签约讲师，可开设课程</p>
              </button>
            </div>
          </div>

          {/* 权限设置 */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">发布权限</label>
            <div className="flex flex-wrap gap-2">
              {Object.entries(permissionLabels).map(([key, label]) => (
                <button
                  key={key}
                  onClick={() => togglePermission(key)}
                  className={`px-4 py-2 rounded-xl text-sm ${
                    selectedPermissions.includes(key)
                      ? "bg-primary text-white"
                      : "bg-background text-muted-foreground"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          {/* 分成比例 */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">
              收益分成比例（嘉宾/老师）
            </label>
            <div className="flex items-center gap-4">
              <input
                type="range"
                min="10"
                max="90"
                step="5"
                value={revenueShare}
                onChange={(e) => setRevenueShare(parseInt(e.target.value))}
                className="flex-1 accent-primary"
              />
              <span className="text-lg font-bold text-primary w-16 text-right">{revenueShare}%</span>
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              嘉宾/老师获得 {revenueShare}%，圈子获得 {100 - revenueShare}%
            </p>
          </div>

          {/* 邀请链接 */}
          {inviteType === "link" && (
            <div>
              <label className="block text-sm font-medium text-foreground mb-2">邀请链接</label>
              <div className="flex gap-2">
                <div className="flex-1 px-3 py-2.5 bg-background rounded-xl text-sm text-muted-foreground truncate">
                  {inviteLink}
                </div>
                <button className="px-4 py-2.5 bg-primary text-white rounded-xl">
                  <Copy className="w-4 h-4" />
                </button>
                <button className="px-4 py-2.5 bg-background text-muted-foreground rounded-xl">
                  <QrCode className="w-4 h-4" />
                </button>
              </div>
              <p className="text-xs text-muted-foreground mt-2">链接7天内有效，对方接受邀请后自动成为嘉宾/老师</p>
            </div>
          )}

          {/* 搜索用户 */}
          {inviteType === "search" && (
            <div>
              <label className="block text-sm font-medium text-foreground mb-2">搜索用户</label>
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="输入用户名或ID搜索"
                  className="w-full pl-9 pr-4 py-2.5 bg-background rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// 编辑嘉宾弹窗
function EditGuestModal({ guest, onClose }: { guest: typeof mockGuests[0]; onClose: () => void }) {
  const [role, setRole] = useState(guest.role)
  const [revenueShare, setRevenueShare] = useState(guest.revenueShare)
  const [selectedPermissions, setSelectedPermissions] = useState(guest.permissions)

  const togglePermission = (perm: string) => {
    setSelectedPermissions(prev => 
      prev.includes(perm) ? prev.filter(p => p !== perm) : [...prev, perm]
    )
  }

  return (
    <div className="fixed inset-0 z-50 flex items-end">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative w-full bg-white rounded-t-3xl max-h-[80vh] overflow-hidden animate-in slide-in-from-bottom">
        <div className="flex items-center justify-between p-4 border-b border-muted">
          <button onClick={onClose} className="text-muted-foreground">取消</button>
          <span className="font-medium text-foreground">编辑 {guest.name}</span>
          <button className="text-primary font-medium">保存</button>
        </div>

        <div className="p-4 space-y-4 overflow-y-auto">
          {/* 角色选择 */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">角色类型</label>
            <div className="flex gap-2">
              <button
                onClick={() => setRole("guest")}
                className={`flex-1 py-2.5 rounded-xl text-sm ${
                  role === "guest" ? "bg-gold text-white" : "bg-background text-muted-foreground"
                }`}
              >
                嘉宾
              </button>
              <button
                onClick={() => setRole("teacher")}
                className={`flex-1 py-2.5 rounded-xl text-sm ${
                  role === "teacher" ? "bg-info text-white" : "bg-background text-muted-foreground"
                }`}
              >
                老师
              </button>
            </div>
          </div>

          {/* 权限设置 */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">发布权限</label>
            <div className="flex flex-wrap gap-2">
              {Object.entries(permissionLabels).map(([key, label]) => (
                <button
                  key={key}
                  onClick={() => togglePermission(key)}
                  className={`px-4 py-2 rounded-xl text-sm ${
                    selectedPermissions.includes(key)
                      ? "bg-primary text-white"
                      : "bg-background text-muted-foreground"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          {/* 分成比例 */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">收益分成比例</label>
            <div className="flex items-center gap-4">
              <input
                type="range"
                min="10"
                max="90"
                step="5"
                value={revenueShare}
                onChange={(e) => setRevenueShare(parseInt(e.target.value))}
                className="flex-1 accent-primary"
              />
              <span className="text-lg font-bold text-primary w-16 text-right">{revenueShare}%</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// apps/mobile-backup-20260621_1544/src/pkg-circle/circles/guests.vue
<script setup lang="ts">
/**
 * 嘉宾/老师管理页（从原型 app/circles/[id]/guests/page.tsx 570行高保真迁移）
 * 搜索 + 四Tab(全部/嘉宾/老师/待审核) + 嘉宾卡片(角色徽章/操作菜单编辑·收益·移除/权限标签/4数据统计/待审核通过拒绝)
 * + 邀请嘉宾底部弹窗(链接/搜索·角色·权限·分成滑块·邀请链接复制) + 编辑嘉宾底部弹窗
 */
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack, navigateTo, toastComingSoon } from '@/utils/router'

interface GuestStats { articles: number; courses: number; lives: number; totalRevenue: number; thisMonthRevenue: number }
interface Guest {
  id: string; name: string; avatar: string; title: string
  role: 'guest' | 'teacher'; joinedAt: string; status: 'active' | 'pending'
  stats: GuestStats; revenueShare: number; permissions: string[]
}

const circleId = '1'

const mockGuests: Guest[] = [
  { id: '1', name: '张玄风', avatar: '/static/avatars/u1.png', title: '资深命理师', role: 'guest', joinedAt: '2024-01-10', status: 'active', stats: { articles: 28, courses: 3, lives: 12, totalRevenue: 12680.5, thisMonthRevenue: 2350 }, revenueShare: 70, permissions: ['article', 'course', 'live', 'qa'] },
  { id: '2', name: '李易安', avatar: '/static/avatars/u2.png', title: '紫微斗数讲师', role: 'teacher', joinedAt: '2024-02-15', status: 'active', stats: { articles: 15, courses: 5, lives: 8, totalRevenue: 8920, thisMonthRevenue: 1680 }, revenueShare: 60, permissions: ['article', 'course'] },
  { id: '3', name: '王命理', avatar: '/static/avatars/u3.png', title: '八字研究者', role: 'guest', joinedAt: '2024-03-01', status: 'pending', stats: { articles: 0, courses: 0, lives: 0, totalRevenue: 0, thisMonthRevenue: 0 }, revenueShare: 50, permissions: ['article'] },
]

const permissionLabels: Record<string, string> = { article: '文章', course: '课程', live: '直播', qa: '问答', post: '帖子' }
const permEntries = Object.entries(permissionLabels)

const searchQuery = ref('')
const activeTab = ref<'all' | 'guest' | 'teacher' | 'pending'>('all')
const showInviteModal = ref(false)
const showActionMenu = ref<string | null>(null)
const showEditModal = ref<string | null>(null)

const pendingCount = computed(() => mockGuests.filter((g) => g.status === 'pending').length)
const filteredGuests = computed(() =>
  mockGuests
    .filter((g) => {
      if (activeTab.value === 'pending') return g.status === 'pending'
      if (activeTab.value === 'guest') return g.role === 'guest' && g.status === 'active'
      if (activeTab.value === 'teacher') return g.role === 'teacher' && g.status === 'active'
      return g.status === 'active'
    })
    .filter((g) => g.name.includes(searchQuery.value) || g.title.includes(searchQuery.value)),
)
const editingGuest = computed(() => mockGuests.find((g) => g.id === showEditModal.value) || null)
const tabs = [
  { key: 'all', label: '全部' },
  { key: 'guest', label: '嘉宾' },
  { key: 'teacher', label: '老师' },
  { key: 'pending', label: '待审核' },
] as const

// 邀请弹窗状态
const inviteType = ref<'link' | 'search'>('link')
const inviteRole = ref<'guest' | 'teacher'>('guest')
const inviteShare = ref(50)
const invitePerms = ref<string[]>(['article'])
const inviteLink = computed(() => `https://rebugx.com/invite/${circleId}?role=${inviteRole.value}`)
function toggleInvitePerm(p: string) { invitePerms.value = invitePerms.value.includes(p) ? invitePerms.value.filter((x) => x !== p) : [...invitePerms.value, p] }
function copyInviteLink() { uni.setClipboardData({ data: inviteLink.value, success: () => uni.showToast({ title: '链接已复制', icon: 'none' }) }) }

// 编辑弹窗状态
const editRole = ref<'guest' | 'teacher'>('guest')
const editShare = ref(50)
const editPerms = ref<string[]>([])
function openEdit(g: Guest) {
  showEditModal.value = g.id; showActionMenu.value = null
  editRole.value = g.role; editShare.value = g.revenueShare; editPerms.value = [...g.permissions]
}
function toggleEditPerm(p: string) { editPerms.value = editPerms.value.includes(p) ? editPerms.value.filter((x) => x !== p) : [...editPerms.value, p] }
</script>

<template>
  <view class="gt">
    <!-- Header -->
    <view class="gt-nav">
      <view class="gt-nav-bar">
        <view
          class="gt-back"
          @tap="goBack"
        >
          <app-icon
            name="chevron-left"
            :size="40"
            color="#2C2C2C"
          />
        </view>
        <text class="gt-title">
          嘉宾/老师管理
        </text>
        <view
          class="gt-invite-btn"
          @tap="showInviteModal = true"
        >
          <app-icon
            name="user-plus"
            :size="40"
            color="#C41E3A"
          />
        </view>
      </view>
      <!-- 搜索 -->
      <view class="gt-search-wrap">
        <view class="gt-search">
          <app-icon
            name="search"
            :size="28"
            color="#999999"
          />
          <input
            v-model="searchQuery"
            class="gt-search-input"
            placeholder="搜索嘉宾/老师"
            placeholder-class="gt-ph"
          >
        </view>
      </view>
      <!-- Tabs -->
      <view class="gt-tabs">
        <view
          v-for="t in tabs"
          :key="t.key"
          class="gt-tab"
          :class="{ 'gt-tab-on': activeTab === t.key }"
          @tap="activeTab = t.key"
        >
          {{ t.label }}<text
            v-if="t.key === 'pending' && pendingCount"
            class="gt-tab-count"
          >
            ({{ pendingCount }})
          </text>
        </view>
      </view>
    </view>

    <!-- 列表 -->
    <view class="gt-list">
      <view
        v-if="filteredGuests.length === 0"
        class="gt-empty"
      >
        <app-icon
          name="user-plus"
          :size="56"
          color="#D9D9D9"
        />
        <text class="gt-empty-text">
          暂无嘉宾/老师
        </text>
        <view
          class="gt-empty-btn"
          @tap="showInviteModal = true"
        >
          邀请嘉宾
        </view>
      </view>

      <view
        v-for="g in filteredGuests"
        :key="g.id"
        class="gt-card"
      >
        <view class="gt-card-head">
          <image
            class="gt-avatar"
            :src="g.avatar"
            mode="aspectFill"
          />
          <view class="gt-info">
            <view class="gt-name-row">
              <text class="gt-name">
                {{ g.name }}
              </text>
              <text
                class="gt-role"
                :class="g.role === 'teacher' ? 'gt-role-teacher' : 'gt-role-guest'"
              >
                {{ g.role === 'teacher' ? '老师' : '嘉宾' }}
              </text>
              <text
                v-if="g.status === 'pending'"
                class="gt-role gt-role-pending"
              >
                待审核
              </text>
            </view>
            <text class="gt-titletxt">
              {{ g.title }}
            </text>
            <text class="gt-joined">
              加入于 {{ g.joinedAt }}
            </text>
          </view>
          <view
            class="gt-more"
            @tap="showActionMenu = showActionMenu === g.id ? null : g.id"
          >
            <app-icon
              name="more-vertical"
              :size="36"
              color="#999999"
            />
          </view>
        </view>

        <!-- 操作菜单 -->
        <view
          v-if="showActionMenu === g.id"
          class="gt-menu"
        >
          <view
            class="gt-menu-item"
            @tap="openEdit(g)"
          >
            <app-icon
              name="edit"
              :size="26"
              color="#666666"
            /><text>编辑</text>
          </view>
          <view
            class="gt-menu-item"
            @tap="navigateTo(`/pkg-circle/circles/earnings?id=${circleId}&guest=${g.id}`)"
          >
            <app-icon
              name="trending-up"
              :size="26"
              color="#666666"
            /><text>收益</text>
          </view>
          <view
            class="gt-menu-item gt-menu-del"
            @tap="toastComingSoon()"
          >
            <app-icon
              name="trash-2"
              :size="26"
              color="#EF4444"
            /><text>移除</text>
          </view>
        </view>

        <!-- 权限标签 -->
        <view class="gt-perms">
          <text class="gt-perms-label">
            可发布：
          </text>
          <text
            v-for="p in g.permissions"
            :key="p"
            class="gt-perm"
          >
            {{ permissionLabels[p] }}
          </text>
        </view>

        <!-- 数据统计 -->
        <view
          v-if="g.status === 'active'"
          class="gt-stats"
        >
          <view class="gt-stat-grid">
            <view class="gt-stat">
              <view class="gt-stat-top">
                <app-icon
                  name="file-text"
                  :size="22"
                  color="#999999"
                /><text class="gt-stat-num">
                  {{ g.stats.articles }}
                </text>
              </view>
              <text class="gt-stat-label">
                文章
              </text>
            </view>
            <view class="gt-stat">
              <view class="gt-stat-top">
                <app-icon
                  name="book-open"
                  :size="22"
                  color="#999999"
                /><text class="gt-stat-num">
                  {{ g.stats.courses }}
                </text>
              </view>
              <text class="gt-stat-label">
                课程
              </text>
            </view>
            <view class="gt-stat">
              <view class="gt-stat-top">
                <app-icon
                  name="radio"
                  :size="22"
                  color="#999999"
                /><text class="gt-stat-num">
                  {{ g.stats.lives }}
                </text>
              </view>
              <text class="gt-stat-label">
                直播
              </text>
            </view>
            <view class="gt-stat">
              <text class="gt-stat-num gt-gold">
                ¥{{ g.stats.thisMonthRevenue.toFixed(0) }}
              </text>
              <text class="gt-stat-label">
                本月收益
              </text>
            </view>
          </view>
          <view class="gt-share-row">
            <text class="gt-share-txt">
              分成比例：{{ g.revenueShare }}%
            </text>
            <text class="gt-share-txt">
              累计收益：¥{{ g.stats.totalRevenue.toFixed(2) }}
            </text>
          </view>
        </view>

        <!-- 待审核操作 -->
        <view
          v-if="g.status === 'pending'"
          class="gt-pending-actions"
        >
          <view
            class="gt-pa gt-pa-ok"
            @tap="toastComingSoon()"
          >
            <app-icon
              name="check"
              :size="28"
              color="#ffffff"
            /><text>通过</text>
          </view>
          <view
            class="gt-pa gt-pa-no"
            @tap="toastComingSoon()"
          >
            <app-icon
              name="x"
              :size="28"
              color="#666666"
            /><text>拒绝</text>
          </view>
        </view>
      </view>
    </view>

    <!-- 邀请嘉宾底部弹窗 -->
    <view
      v-if="showInviteModal"
      class="gt-modal-mask"
      @tap="showInviteModal = false"
    >
      <view
        class="gt-sheet"
        @tap.stop
      >
        <view class="gt-sheet-head">
          <text
            class="gt-sheet-cancel"
            @tap="showInviteModal = false"
          >
            取消
          </text>
          <text class="gt-sheet-title">
            邀请嘉宾/老师
          </text>
          <text
            class="gt-sheet-ok"
            @tap="showInviteModal = false"
          >
            确定
          </text>
        </view>
        <scroll-view
          scroll-y
          class="gt-sheet-body"
        >
          <!-- 邀请方式 -->
          <view class="gt-seg">
            <view
              class="gt-seg-btn"
              :class="{ 'gt-seg-on': inviteType === 'link' }"
              @tap="inviteType = 'link'"
            >
              链接邀请
            </view>
            <view
              class="gt-seg-btn"
              :class="{ 'gt-seg-on': inviteType === 'search' }"
              @tap="inviteType = 'search'"
            >
              搜索用户
            </view>
          </view>
          <!-- 角色选择 -->
          <text class="gt-field-label">
            角色类型
          </text>
          <view class="gt-roles">
            <view
              class="gt-role-card"
              :class="{ 'gt-role-card-on': inviteRole === 'guest' }"
              @tap="inviteRole = 'guest'"
            >
              <view class="gt-role-card-head">
                <app-icon
                  name="crown"
                  :size="32"
                  :color="inviteRole === 'guest' ? '#C9A96E' : '#999999'"
                /><text class="gt-role-card-name">
                  嘉宾
                </text>
              </view>
              <text class="gt-role-card-desc">
                受邀创作者，可发布内容
              </text>
            </view>
            <view
              class="gt-role-card"
              :class="{ 'gt-role-card-on': inviteRole === 'teacher' }"
              @tap="inviteRole = 'teacher'"
            >
              <view class="gt-role-card-head">
                <app-icon
                  name="shield"
                  :size="32"
                  :color="inviteRole === 'teacher' ? '#2563EB' : '#999999'"
                /><text class="gt-role-card-name">
                  老师
                </text>
              </view>
              <text class="gt-role-card-desc">
                签约讲师，可开设课程
              </text>
            </view>
          </view>
          <!-- 发布权限 -->
          <text class="gt-field-label">
            发布权限
          </text>
          <view class="gt-perm-pills">
            <view
              v-for="[key, label] in permEntries"
              :key="key"
              class="gt-perm-pill"
              :class="{ 'gt-perm-pill-on': invitePerms.includes(key) }"
              @tap="toggleInvitePerm(key)"
            >
              {{ label }}
            </view>
          </view>
          <!-- 分成比例 -->
          <text class="gt-field-label">
            收益分成比例（嘉宾/老师）
          </text>
          <view class="gt-slider-row">
            <slider
              class="gt-slider"
              :value="inviteShare"
              :min="10"
              :max="90"
              :step="5"
              active-color="#C41E3A"
              block-size="20"
              @changing="inviteShare = $event.detail.value"
              @change="inviteShare = $event.detail.value"
            />
            <text class="gt-slider-val">
              {{ inviteShare }}%
            </text>
          </view>
          <text class="gt-slider-hint">
            嘉宾/老师获得 {{ inviteShare }}%，圈子获得 {{ 100 - inviteShare }}%
          </text>
          <!-- 邀请链接 -->
          <view v-if="inviteType === 'link'">
            <text class="gt-field-label">
              邀请链接
            </text>
            <view class="gt-link-row">
              <view class="gt-link">
                {{ inviteLink }}
              </view>
              <view
                class="gt-link-btn"
                @tap="copyInviteLink"
              >
                <app-icon
                  name="copy"
                  :size="28"
                  color="#ffffff"
                />
              </view>
              <view
                class="gt-link-btn gt-link-btn-ghost"
                @tap="toastComingSoon()"
              >
                <app-icon
                  name="qr-code"
                  :size="28"
                  color="#666666"
                />
              </view>
            </view>
            <text class="gt-slider-hint">
              链接7天内有效，对方接受邀请后自动成为嘉宾/老师
            </text>
          </view>
          <!-- 搜索用户 -->
          <view v-else>
            <text class="gt-field-label">
              搜索用户
            </text>
            <view class="gt-search gt-search-modal">
              <app-icon
                name="search"
                :size="28"
                color="#999999"
              />
              <input
                class="gt-search-input"
                placeholder="输入用户名或ID搜索"
                placeholder-class="gt-ph"
              >
            </view>
          </view>
        </scroll-view>
      </view>
    </view>

    <!-- 编辑嘉宾底部弹窗 -->
    <view
      v-if="showEditModal && editingGuest"
      class="gt-modal-mask"
      @tap="showEditModal = null"
    >
      <view
        class="gt-sheet"
        @tap.stop
      >
        <view class="gt-sheet-head">
          <text
            class="gt-sheet-cancel"
            @tap="showEditModal = null"
          >
            取消
          </text>
          <text class="gt-sheet-title">
            编辑 {{ editingGuest.name }}
          </text>
          <text
            class="gt-sheet-ok"
            @tap="showEditModal = null"
          >
            保存
          </text>
        </view>
        <scroll-view
          scroll-y
          class="gt-sheet-body"
        >
          <text class="gt-field-label">
            角色类型
          </text>
          <view class="gt-seg">
            <view
              class="gt-seg-btn"
              :class="{ 'gt-seg-on-gold': editRole === 'guest' }"
              @tap="editRole = 'guest'"
            >
              嘉宾
            </view>
            <view
              class="gt-seg-btn"
              :class="{ 'gt-seg-on-info': editRole === 'teacher' }"
              @tap="editRole = 'teacher'"
            >
              老师
            </view>
          </view>
          <text class="gt-field-label">
            发布权限
          </text>
          <view class="gt-perm-pills">
            <view
              v-for="[key, label] in permEntries"
              :key="key"
              class="gt-perm-pill"
              :class="{ 'gt-perm-pill-on': editPerms.includes(key) }"
              @tap="toggleEditPerm(key)"
            >
              {{ label }}
            </view>
          </view>
          <text class="gt-field-label">
            收益分成比例
          </text>
          <view class="gt-slider-row">
            <slider
              class="gt-slider"
              :value="editShare"
              :min="10"
              :max="90"
              :step="5"
              active-color="#C41E3A"
              block-size="20"
              @changing="editShare = $event.detail.value"
              @change="editShare = $event.detail.value"
            />
            <text class="gt-slider-val">
              {{ editShare }}%
            </text>
          </view>
        </scroll-view>
      </view>
    </view>
  </view>
</template>

<style lang="scss" scoped>
.gt { min-height: 100vh; background: #FAF8F5; }
.gt-nav { position: sticky; top: 0; z-index: 10; background: #fff; border-bottom: 1rpx solid #F2EFEA; }
.gt-nav-bar { display: flex; align-items: center; justify-content: space-between; padding: 0 24rpx; height: 96rpx; }
.gt-back, .gt-invite-btn { padding: 8rpx; }
.gt-title { font-size: 32rpx; font-weight: 600; color: #2C2C2C; }
.gt-search-wrap { padding: 0 24rpx 18rpx; }
.gt-search { display: flex; align-items: center; gap: 10rpx; background: #FAF8F5; border-radius: 16rpx; padding: 16rpx 20rpx; }
.gt-search-input { flex: 1; font-size: 28rpx; color: #2C2C2C; }
.gt-ph { color: #999999; }
.gt-tabs { display: flex; gap: 14rpx; padding: 0 24rpx 18rpx; }
.gt-tab { padding: 10rpx 28rpx; border-radius: 999rpx; font-size: 28rpx; background: #FAF8F5; color: #999999; }
.gt-tab-on { background: #C41E3A; color: #fff; }
.gt-tab-count { font-size: 22rpx; }
.gt-list { padding: 24rpx; display: flex; flex-direction: column; gap: 18rpx; }
.gt-empty { display: flex; flex-direction: column; align-items: center; padding: 80rpx 0; gap: 18rpx; }
.gt-empty-text { font-size: 26rpx; color: #999999; }
.gt-empty-btn { margin-top: 8rpx; padding: 14rpx 48rpx; background: #C41E3A; color: #fff; border-radius: 16rpx; font-size: 26rpx; }
.gt-card { background: #fff; border-radius: 28rpx; padding: 24rpx; box-shadow: 0 2rpx 12rpx rgba(0,0,0,0.04); }
.gt-card-head { display: flex; align-items: flex-start; gap: 18rpx; }
.gt-avatar { width: 88rpx; height: 88rpx; border-radius: 16rpx; background: #F2EFEA; flex-shrink: 0; }
.gt-info { flex: 1; min-width: 0; }
.gt-name-row { display: flex; align-items: center; gap: 10rpx; flex-wrap: wrap; }
.gt-name { font-size: 30rpx; font-weight: 500; color: #2C2C2C; }
.gt-role { font-size: 20rpx; padding: 2rpx 10rpx; border-radius: 6rpx; }
.gt-role-teacher { background: rgba(37,99,235,0.1); color: #2563EB; }
.gt-role-guest { background: rgba(201,169,110,0.1); color: #C9A96E; }
.gt-role-pending { background: #FFEDD5; color: #EA580C; }
.gt-titletxt { display: block; font-size: 24rpx; color: #999999; margin-top: 4rpx; }
.gt-joined { display: block; font-size: 20rpx; color: #999999; margin-top: 6rpx; }
.gt-more { padding: 8rpx; margin-right: -8rpx; }
.gt-menu { margin-top: 18rpx; padding-top: 18rpx; border-top: 1rpx solid #F2EFEA; display: flex; gap: 14rpx; }
.gt-menu-item { flex: 1; display: flex; align-items: center; justify-content: center; gap: 8rpx; padding: 16rpx 0; font-size: 26rpx; color: #666666; background: #FAF8F5; border-radius: 12rpx; }
.gt-menu-del { color: #EF4444; background: #FEF2F2; }
.gt-perms { margin-top: 18rpx; display: flex; flex-wrap: wrap; align-items: center; gap: 10rpx; }
.gt-perms-label { font-size: 20rpx; color: #999999; }
.gt-perm { font-size: 20rpx; padding: 2rpx 10rpx; border-radius: 6rpx; background: #FAF8F5; color: #999999; }
.gt-stats { margin-top: 18rpx; padding-top: 18rpx; border-top: 1rpx solid #F2EFEA; }
.gt-stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12rpx; }
.gt-stat { text-align: center; }
.gt-stat-top { display: flex; align-items: center; justify-content: center; gap: 6rpx; }
.gt-stat-num { font-size: 28rpx; font-weight: 500; color: #666666; }
.gt-gold { color: #C9A96E; }
.gt-stat-label { display: block; font-size: 20rpx; color: #999999; margin-top: 4rpx; }
.gt-share-row { display: flex; align-items: center; justify-content: space-between; margin-top: 14rpx; }
.gt-share-txt { font-size: 24rpx; color: #999999; }
.gt-pending-actions { margin-top: 18rpx; padding-top: 18rpx; border-top: 1rpx solid #F2EFEA; display: flex; gap: 14rpx; }
.gt-pa { flex: 1; display: flex; align-items: center; justify-content: center; gap: 8rpx; padding: 18rpx 0; border-radius: 16rpx; font-size: 28rpx; }
.gt-pa-ok { background: #C41E3A; color: #fff; }
.gt-pa-no { background: #FAF8F5; color: #666666; }
/* 弹窗 */
.gt-modal-mask { position: fixed; inset: 0; z-index: 50; background: rgba(0,0,0,0.4); display: flex; align-items: flex-end; }
.gt-sheet { width: 100%; background: #fff; border-radius: 36rpx 36rpx 0 0; max-height: 85vh; overflow: hidden; }
.gt-sheet-head { display: flex; align-items: center; justify-content: space-between; padding: 28rpx 24rpx; border-bottom: 1rpx solid #F2EFEA; }
.gt-sheet-cancel { font-size: 28rpx; color: #999999; }
.gt-sheet-title { font-size: 30rpx; font-weight: 500; color: #2C2C2C; }
.gt-sheet-ok { font-size: 28rpx; color: #C41E3A; font-weight: 500; }
.gt-sheet-body { padding: 28rpx 24rpx; max-height: 70vh; }
.gt-seg { display: flex; gap: 14rpx; margin-bottom: 24rpx; }
.gt-seg-btn { flex: 1; padding: 18rpx 0; text-align: center; border-radius: 16rpx; font-size: 28rpx; background: #FAF8F5; color: #999999; }
.gt-seg-on { background: #C41E3A; color: #fff; }
.gt-seg-on-gold { background: #C9A96E; color: #fff; }
.gt-seg-on-info { background: #2563EB; color: #fff; }
.gt-field-label { display: block; font-size: 28rpx; font-weight: 500; color: #2C2C2C; margin: 12rpx 0 16rpx; }
.gt-roles { display: flex; gap: 14rpx; }
.gt-role-card { flex: 1; padding: 22rpx; border-radius: 16rpx; border: 3rpx solid #F2EFEA; }
.gt-role-card-on { border-color: #C41E3A; background: rgba(196,30,58,0.05); }
.gt-role-card-head { display: flex; align-items: center; gap: 10rpx; }
.gt-role-card-name { font-size: 28rpx; font-weight: 500; color: #2C2C2C; }
.gt-role-card-desc { display: block; font-size: 20rpx; color: #999999; margin-top: 6rpx; }
.gt-perm-pills { display: flex; flex-wrap: wrap; gap: 14rpx; }
.gt-perm-pill { padding: 14rpx 32rpx; border-radius: 16rpx; font-size: 28rpx; background: #FAF8F5; color: #999999; }
.gt-perm-pill-on { background: #C41E3A; color: #fff; }
.gt-slider-row { display: flex; align-items: center; gap: 24rpx; }
.gt-slider { flex: 1; }
.gt-slider-val { font-size: 34rpx; font-weight: 700; color: #C41E3A; width: 100rpx; text-align: right; }
.gt-slider-hint { display: block; font-size: 24rpx; color: #999999; margin-top: 10rpx; }
.gt-link-row { display: flex; gap: 14rpx; }
.gt-link { flex: 1; padding: 18rpx 20rpx; background: #FAF8F5; border-radius: 16rpx; font-size: 26rpx; color: #999999; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gt-link-btn { padding: 0 28rpx; display: flex; align-items: center; justify-content: center; background: #C41E3A; border-radius: 16rpx; }
.gt-link-btn-ghost { background: #FAF8F5; }
.gt-search-modal { margin-top: 4rpx; }
</style>
