// apps/mobile/src/pkg-ebook/checkout/success.vue
<template>
  <view class="page">
    <!-- 成功 Hero -->
    <view class="hero">
      <view class="check-circle">
        <AppIcon name="check-circle" :size="80" :color="C.primary" />
      </view>
      <text class="hero-title">支付成功！</text>
      <text class="hero-sub">《{{ order.successBookTitle }}》已添加到你的书架</text>
      <view class="hero-actions">
        <view class="btn-primary" @tap="goReader">
          <AppIcon name="book-open" :size="32" color="#ffffff" />
          <text class="btn-primary-tx">立即阅读</text>
        </view>
        <view class="btn-outline" @tap="goShelf">
          <text class="btn-outline-tx">去书架</text>
        </view>
      </view>
    </view>

    <!-- 订单详情 -->
    <view class="section">
      <view class="order-card">
        <view class="order-row">
          <text class="order-label">订单号</text>
          <text class="order-val mono">{{ order.orderNo }}</text>
        </view>
        <view class="order-row">
          <text class="order-label">支付方式</text>
          <text class="order-val">{{ order.payLabel }}</text>
        </view>
        <view class="order-row">
          <text class="order-label">实付金额</text>
          <text class="order-val price">¥{{ order.amount }}</text>
        </view>
        <view class="order-row">
          <text class="order-label">购买时间</text>
          <text class="order-val">{{ order.payTime }}</text>
        </view>
      </view>
    </view>

    <!-- 相关推荐 -->
    <view class="section">
      <view class="rec-hd">
        <text class="rec-title">买了此书的人还买了</text>
        <view class="rec-more" @tap="goStore">
          <text class="rec-more-tx">更多</text>
          <AppIcon name="chevron-right" :size="32" :color="C.primary" />
        </view>
      </view>
      <scroll-view scroll-x class="rec-scroll">
        <view class="rec-list">
          <view v-for="rb in related" :key="rb.id" class="rec-item" @tap="goDetail(rb.id)">
            <view class="rec-cover" :style="{ background: rb.coverColor }">
              <view class="cover-spine" />
              <view class="cover-text-wrap"><text class="cover-text">{{ rb.title }}</text></view>
            </view>
            <text class="rec-name">{{ rb.title }}</text>
            <text class="rec-price">¥{{ rb.price }}</text>
          </view>
        </view>
      </scroll-view>
    </view>
  </view>
</template>

<script setup lang="ts">
import AppIcon from '@/components/common/app-icon.vue'
import { ebookOrderInfo, ebookRelatedBuy } from '@/lib/ebook-data'

const C = { primary: '#2563eb' }
const order = ebookOrderInfo
const related = ebookRelatedBuy

function goReader() {
  uni.redirectTo({ url: '/pkg-ebook/reader/index?id=1' })
}
function goShelf() {
  uni.redirectTo({ url: '/pkg-ebook/bookshelf/index' })
}
function goStore() {
  uni.navigateTo({ url: '/pkg-ebook/store/index' })
}
function goDetail(id: string) {
  uni.redirectTo({ url: `/pkg-ebook/detail/index?id=${id}` })
}
</script>

<style scoped lang="scss">
.page {
  display: flex;
  flex-direction: column;
  align-items: center;
  min-height: 100vh;
  background: var(--ebook-bg);
}
.hero {
  width: 100%;
  background: #fff;
  padding: 128rpx 64rpx 80rpx;
  text-align: center;
  border-bottom: 2rpx solid var(--ebook-border);
  display: flex;
  flex-direction: column;
  align-items: center;
  box-sizing: border-box;
}
.check-circle {
  width: 160rpx;
  height: 160rpx;
  border-radius: 50%;
  background: rgba(37, 99, 235, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 32rpx;
}
.hero-title {
  font-size: 40rpx;
  font-weight: 700;
  color: var(--ebook-text);
}
.hero-sub {
  font-size: 28rpx;
  color: var(--ebook-text-soft);
  margin-top: 16rpx;
}
.hero-actions {
  display: flex;
  gap: 24rpx;
  margin-top: 48rpx;
}
.btn-primary {
  display: flex;
  align-items: center;
  gap: 16rpx;
  padding: 20rpx 48rpx;
  background: var(--ebook-primary);
  border-radius: 16rpx;
}
.btn-primary-tx {
  font-size: 28rpx;
  font-weight: 500;
  color: #fff;
}
.btn-outline {
  padding: 20rpx 48rpx;
  border: 2rpx solid var(--ebook-border);
  border-radius: 16rpx;
}
.btn-outline-tx {
  font-size: 28rpx;
  color: var(--ebook-text-soft);
}
.section {
  width: 100%;
  padding: 40rpx 32rpx 0;
  box-sizing: border-box;
}
.order-card {
  background: #fff;
  border-radius: 24rpx;
  border: 2rpx solid var(--ebook-border);
  overflow: hidden;
}
.order-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24rpx 32rpx;
  border-top: 2rpx solid var(--ebook-border);
}
.order-row:first-child {
  border-top: none;
}
.order-label {
  font-size: 28rpx;
  color: var(--ebook-text-soft);
}
.order-val {
  font-size: 28rpx;
  color: var(--ebook-text);
}
.order-val.mono {
  font-size: 24rpx;
  font-family: monospace;
}
.order-val.price {
  font-weight: 700;
  color: var(--ebook-price);
}
.rec-hd {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24rpx;
}
.rec-title {
  font-size: 32rpx;
  font-weight: 600;
  color: var(--ebook-text);
}
.rec-more {
  display: flex;
  align-items: center;
  gap: 2rpx;
}
.rec-more-tx {
  font-size: 28rpx;
  color: var(--ebook-primary);
}
.rec-scroll {
  width: 100%;
  white-space: nowrap;
}
.rec-list {
  display: flex;
  gap: 24rpx;
  padding-bottom: 64rpx;
}
.rec-item {
  width: 192rpx;
  flex-shrink: 0;
}
.rec-cover {
  width: 100%;
  height: 288rpx;
  border-radius: 16rpx;
  box-shadow: 0 4rpx 12rpx rgba(0, 0, 0, 0.15);
  margin-bottom: 16rpx;
  position: relative;
  overflow: hidden;
}
.cover-spine {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 8rpx;
  background: rgba(255, 255, 255, 0.1);
}
.cover-text-wrap {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16rpx;
}
.cover-text {
  color: rgba(255, 255, 255, 0.8);
  font-size: 20rpx;
  font-weight: 500;
  text-align: center;
  line-height: 1.4;
  white-space: normal;
}
.rec-name {
  display: block;
  font-size: 24rpx;
  font-weight: 500;
  color: var(--ebook-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.rec-price {
  display: block;
  font-size: 24rpx;
  font-weight: 700;
  color: var(--ebook-price);
}
</style>

// app/ebook/checkout/success/page.tsx
"use client"

import { Button } from "@/components/ui/button"
import { CheckCircle, BookOpen, ChevronRight } from "lucide-react"
import Link from "next/link"

const relatedBooks = [
  { id: "2", title: "紫微斗数入门", author: "紫微居士", price: 58, coverColor: "#1a4731" },
  { id: "3", title: "六爻预测实战", author: "陈易卦", price: 68, coverColor: "#4a1942" },
  { id: "4", title: "风水学基础", author: "张天师", price: 88, coverColor: "#3d1f00" },
]

export default function EbookCheckoutSuccessPage() {
  return (
    <div className="min-h-screen bg-[var(--ebook-bg)] flex flex-col items-center">
      {/* Success hero */}
      <div className="w-full bg-white pt-16 pb-10 px-8 text-center border-b border-[var(--ebook-border)]">
        <div className="w-20 h-20 rounded-full bg-[var(--ebook-primary)]/10 flex items-center justify-center mx-auto mb-4">
          <CheckCircle className="w-10 h-10 text-[var(--ebook-primary)]" />
        </div>
        <h1 className="text-xl font-bold text-[var(--ebook-text)]">支付成功！</h1>
        <p className="text-sm text-[var(--ebook-text-soft)] mt-2">《八字命理精解》已添加到你的书架</p>

        {/* Quick actions */}
        <div className="flex gap-3 mt-6 justify-center">
          <Button className="bg-[var(--ebook-primary)] hover:bg-[var(--ebook-primary)]/90 px-6 gap-2" asChild>
            <Link href="/ebook/reader/1">
              <BookOpen className="w-4 h-4" />
              立即阅读
            </Link>
          </Button>
          <Button variant="outline" className="border-[var(--ebook-border)] text-[var(--ebook-text-soft)] px-6 gap-2" asChild>
            <Link href="/ebook/bookshelf">
              去书架
            </Link>
          </Button>
        </div>
      </div>

      {/* Order details */}
      <div className="w-full max-w-lg px-4 py-5">
        <div className="bg-white rounded-xl border border-[var(--ebook-border)] divide-y divide-[var(--ebook-border)]">
          <div className="px-4 py-3 flex justify-between text-sm">
            <span className="text-[var(--ebook-text-soft)]">订单号</span>
            <span className="text-[var(--ebook-text)] font-mono text-xs">#EB2024031501</span>
          </div>
          <div className="px-4 py-3 flex justify-between text-sm">
            <span className="text-[var(--ebook-text-soft)]">支付方式</span>
            <span className="text-[var(--ebook-text)]">微信支付</span>
          </div>
          <div className="px-4 py-3 flex justify-between text-sm">
            <span className="text-[var(--ebook-text-soft)]">实付金额</span>
            <span className="text-[var(--ebook-price)] font-bold">¥68</span>
          </div>
          <div className="px-4 py-3 flex justify-between text-sm">
            <span className="text-[var(--ebook-text-soft)]">购买时间</span>
            <span className="text-[var(--ebook-text)]">2024-03-15 14:32</span>
          </div>
        </div>
      </div>

      {/* Related recommendation */}
      <div className="w-full px-4 pb-8">
        <div className="flex items-center justify-between mb-3">
          <h2 className="font-semibold text-[var(--ebook-text)]">买了此书的人还买了</h2>
          <Link href="/ebook" className="text-sm text-[var(--ebook-primary)] flex items-center gap-0.5">
            更多<ChevronRight className="w-4 h-4" />
          </Link>
        </div>
        <div className="flex gap-3 overflow-x-auto scrollbar-hide pb-1 -mx-4 px-4">
          {relatedBooks.map((rb) => (
            <Link key={rb.id} href={`/ebook/${rb.id}`} className="flex-shrink-0 w-24">
              <div
                className="w-full aspect-[2/3] rounded-xl shadow-md mb-2 relative overflow-hidden"
                style={{ background: rb.coverColor }}
              >
                <div className="absolute left-0 top-0 bottom-0 w-1 bg-white/10" />
                <div className="absolute inset-0 flex items-center justify-center p-2">
                  <p className="text-white/80 text-[10px] text-center font-medium leading-snug line-clamp-4">{rb.title}</p>
                </div>
              </div>
              <p className="text-xs font-medium text-[var(--ebook-text)] line-clamp-1">{rb.title}</p>
              <p className="text-[var(--ebook-price)] text-xs font-bold">¥{rb.price}</p>
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}
