// apps/mobile/.backup_vue3_converted/pages/offline/settlements/index.vue
<template>
  <view class="min-h-screen bg-background pb-4">
    <!-- 头部 -->
    <view class="sticky top-0 z-10 bg-white border-b border-border">
      <view class="flex items-center justify-between px-4 py-3">
        <view class="flex items-center gap-3">
          <view class="p-1" @click="goBack">
            <text class="text-foreground text-lg">←</text>
          </view>
          <text class="text-lg font-semibold text-foreground">收入结算</text>
        </view>
        <view class="p-1" @click="showFilter = true">
          <text class="text-muted-foreground">📊</text>
        </view>
      </view>
    </view>

    <!-- 统计卡片 -->
    <view class="p-4">
      <view class="rounded-xl p-4 text-white" style="background:linear-gradient(to right,#C41E3A,#C41E3A);">
        <text class="text-sm opacity-90 block mb-1">累计收入</text>
        <text class="text-3xl font-bold block mb-4">¥{{ stats.totalNetAmount.toLocaleString() }}</text>
        <view class="grid grid-cols-3 gap-4 text-sm">
          <view>
            <text class="opacity-75 block">总收入</text>
            <text class="font-medium block">¥{{ stats.totalIncome.toLocaleString() }}</text>
          </view>
          <view>
            <text class="opacity-75 block">扣除</text>
            <text class="font-medium block">¥{{ stats.totalDeduction.toLocaleString() }}</text>
          </view>
          <view>
            <text class="opacity-75 block">待结算</text>
            <text class="font-medium block">¥{{ stats.pendingAmount.toLocaleString() }}</text>
          </view>
        </view>
      </view>
    </view>

    <!-- 状态筛选 -->
    <view class="px-4 mb-4">
      <view class="flex gap-2 overflow-x-auto pb-2">
        <view
          v-for="opt in statusOptions"
          :key="opt.value"
          class="px-3 py-1.5 rounded-full text-sm whitespace-nowrap flex-shrink-0"
          :style="{ backgroundColor: selectedStatus === opt.value ? '#C41E3A' : '#F1EDE8', color: selectedStatus === opt.value ? '#fff' : '#2C2C2C' }"
          @click="selectedStatus = opt.value"
        >
          <text>{{ opt.label }}</text>
        </view>
      </view>
    </view>

    <!-- 结算列表 -->
    <view class="px-4 space-y-3">
      <!-- 加载骨架 -->
      <template v-if="loading">
        <view v-for="i in 3" :key="i" class="bg-white rounded-xl border border-border p-4">
          <view class="flex items-center justify-between mb-3">
            <view>
              <view class="h-4 w-40 rounded mb-2" style="background:#F0EBE5" />
              <view class="h-3 w-32 rounded" style="background:#F0EBE5" />
            </view>
            <view class="h-5 w-14 rounded-full" style="background:#F0EBE5" />
          </view>
          <view class="grid grid-cols-3 gap-4">
            <view v-for="j in 3" :key="j">
              <view class="h-3 w-10 rounded mb-1" style="background:#F0EBE5" />
              <view class="h-5 w-16 rounded" style="background:#F0EBE5" />
            </view>
          </view>
        </view>
      </template>

      <template v-if="!loading">
      <view v-for="settlement in settlements" :key="settlement.id" class="bg-white rounded-xl border border-border p-4" @click="openDetail(settlement)">
        <view class="flex items-start justify-between mb-3">
          <view>
            <view class="flex items-center gap-2 mb-1">
              <text class="text-muted-foreground"></text>
              <text class="text-sm text-foreground">{{ settlement.periodStart }} ~ {{ settlement.periodEnd }}</text>
            </view>
            <text class="text-xs text-muted-foreground block">结算单号：{{ settlement.settlementNo }}</text>
          </view>
          <view
            class="text-xs px-2 py-0.5 rounded-full"
            :style="{ backgroundColor: getStatusStyle(settlement.status).bg, color: getStatusStyle(settlement.status).color }"
          >
            <text>{{ getStatusLabel(settlement.status) }}</text>
          </view>
        </view>

        <view class="flex items-end justify-between">
          <view class="flex flex-1 gap-4 text-sm">
            <view>
              <text class="text-xs text-muted-foreground block">收入</text>
              <text class="font-medium text-foreground block">¥{{ settlement.totalIncome.toLocaleString() }}</text>
            </view>
            <view>
              <text class="text-xs text-muted-foreground block">扣除</text>
              <text class="font-medium block" style="color:#EF4444">-¥{{ settlement.totalDeduction.toLocaleString() }}</text>
            </view>
            <view>
              <text class="text-xs text-muted-foreground block">实收</text>
              <text class="font-medium block" style="color:#22C55E">¥{{ settlement.netAmount.toLocaleString() }}</text>
            </view>
          </view>
          <text class="text-muted-foreground">›</text>
        </view>
      </view>

      <view v-if="!loading && settlements.length === 0" class="text-center py-12">
        <text class="text-4xl text-muted-foreground/30 block mb-3"></text>
        <text class="text-sm text-muted-foreground block">暂无结算记录</text>
      </view>
      </template>
    </view>

    <!-- 筛选弹窗 -->
    <view v-if="showFilter" class="fixed inset-0 z-50" style="background-color:rgba(0,0,0,0.5)" @click="showFilter = false">
      <view class="absolute bottom-0 left-0 right-0 bg-white rounded-t-2xl p-4" @click.stop>
        <view class="flex items-center justify-between mb-4">
          <text class="font-semibold text-foreground">筛选</text>
          <view class="p-1" @click="showFilter = false">
            <text class="text-muted-foreground">✕</text>
          </view>
        </view>
        <view class="mb-4">
          <text class="text-sm text-muted-foreground block mb-2">选择年份</text>
          <view class="flex flex-wrap gap-2">
            <view
              v-for="year in years"
              :key="year"
              class="px-3 py-1.5 rounded-full text-sm"
              :style="{ backgroundColor: selectedYear === year ? '#C41E3A' : '#F1EDE8', color: selectedYear === year ? '#fff' : '#2C2C2C' }"
              @click="selectedYear = year"
            >
              <text>{{ year }}年</text>
            </view>
          </view>
        </view>
        <view class="w-full py-3 rounded-xl text-sm text-center text-white" style="background-color:#C41E3A" @click="showFilter = false">
          <text>确定</text>
        </view>
      </view>
    </view>

    <!-- 详情弹窗 -->
    <view v-if="showDetail && detailData" class="fixed inset-0 z-50" style="background-color:rgba(0,0,0,0.5)" @click="showDetail = false">
      <view class="absolute bottom-0 left-0 right-0 bg-white rounded-t-2xl" style="max-height:85vh;overflow-y:auto" @click.stop>
        <view class="sticky top-0 bg-white border-b border-border p-4 flex items-center justify-between">
          <text class="font-semibold text-foreground">结算详情</text>
          <view class="p-1" @click="showDetail = false">
            <text class="text-muted-foreground">✕</text>
          </view>
        </view>
        <view class="p-4 space-y-4">
          <!-- 结算概览 -->
          <view class="rounded-lg p-4" style="background-color:rgba(241,237,232,0.5)">
            <view class="flex items-center gap-2 mb-3">
              <text class="text-muted-foreground"></text>
              <text class="text-sm text-foreground">{{ detailData.periodStart }} ~ {{ detailData.periodEnd }}</text>
              <view class="ml-auto text-xs px-2 py-0.5 rounded-full" :style="{ backgroundColor: getStatusStyle(detailData.status).bg, color: getStatusStyle(detailData.status).color }">
                <text>{{ getStatusLabel(detailData.status) }}</text>
              </view>
            </view>
            <view class="grid grid-cols-3 gap-4 text-center">
              <view>
                <text class="text-xs text-muted-foreground block">总收入</text>
                <text class="font-semibold text-foreground block">¥{{ detailData.totalIncome.toLocaleString() }}</text>
              </view>
              <view>
                <text class="text-xs text-muted-foreground block">扣除</text>
                <text class="font-semibold block" style="color:#EF4444">-¥{{ detailData.totalDeduction.toLocaleString() }}</text>
              </view>
              <view>
                <text class="text-xs text-muted-foreground block">实收</text>
                <text class="font-semibold block" style="color:#22C55E">¥{{ detailData.netAmount.toLocaleString() }}</text>
              </view>
            </view>
          </view>

          <!-- 收入构成 -->
          <view>
            <text class="font-medium text-foreground block mb-3">收入构成</text>
            <view class="grid grid-cols-2 gap-3">
              <view v-for="item in detailData.incomeByType" :key="item.type" class="bg-white rounded-xl border border-border p-3">
                <view class="flex items-center gap-2 mb-2">
                  <view class="p-1.5 rounded" :style="{ backgroundColor: getIncomeTypeColor(item.type).bg }">
                    <text>{{ getIncomeTypeIcon(item.type) }}</text>
                  </view>
                  <text class="text-sm text-foreground">{{ getIncomeTypeLabel(item.type) }}</text>
                </view>
                <text class="font-semibold text-foreground block">¥{{ item.amount.toLocaleString() }}</text>
                <text class="text-xs text-muted-foreground block">{{ item.count }}笔</text>
              </view>
            </view>
          </view>

          <!-- 收入明细 -->
          <view>
            <text class="font-medium text-foreground block mb-3">收入明细</text>
            <view class="space-y-2">
              <view v-for="item in detailData.incomeItems" :key="item.id" class="flex items-center gap-3 py-2 border-b border-border last:border-0">
                <view class="p-1.5 rounded" :style="{ backgroundColor: getIncomeTypeColor(item.type).bg }">
                  <text>{{ getIncomeTypeIcon(item.type) }}</text>
                </view>
                <view class="flex-1 min-w-0">
                  <text class="text-sm text-foreground truncate block">{{ item.title }}</text>
                  <text class="text-xs text-muted-foreground block">{{ item.time }}</text>
                </view>
                <text class="font-medium" style="color:#22C55E">+¥{{ item.amount }}</text>
              </view>
            </view>
          </view>

          <!-- 扣除明细 -->
          <view>
            <text class="font-medium text-foreground block mb-3">扣除明细</text>
            <view class="space-y-2">
              <view v-for="item in detailData.deductionItems" :key="item.id" class="flex items-center justify-between py-2 border-b border-border last:border-0">
                <view>
                  <text class="text-sm text-foreground block">{{ item.title }}</text>
                  <text v-if="item.remark" class="text-xs text-muted-foreground block">{{ item.remark }}</text>
                </view>
                <text class="font-medium" style="color:#EF4444">-¥{{ item.amount.toLocaleString() }}</text>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const selectedStatus = ref('all')
const selectedYear = ref(2026)
const showFilter = ref(false)
const showDetail = ref(false)
const detailData = ref<any>(null)
const loading = ref(false)

const statusOptions = [
  { value: 'all', label: '全部' },
  { value: 'pending', label: '待结算' },
  { value: 'processing', label: '结算中' },
  { value: 'completed', label: '已结算' },
]

const years = [2026, 2025, 2024]

const stats = {
  totalNetAmount: 128600,
  totalIncome: 158000,
  totalDeduction: 29400,
  pendingAmount: 35800,
}

const settlements = [
  { id: 1, periodStart: '2026-05-01', periodEnd: '2026-05-15', settlementNo: 'SET20260515001', status: 'completed', totalIncome: 28600, totalDeduction: 4300, netAmount: 24300 },
  { id: 2, periodStart: '2026-04-16', periodEnd: '2026-04-30', settlementNo: 'SET20260430002', status: 'completed', totalIncome: 35200, totalDeduction: 5300, netAmount: 29900 },
  { id: 3, periodStart: '2026-04-01', periodEnd: '2026-04-15', settlementNo: 'SET20260415003', status: 'pending', totalIncome: 18800, totalDeduction: 2800, netAmount: 16000 },
  { id: 4, periodStart: '2026-03-16', periodEnd: '2026-03-31', settlementNo: 'SET20260331004', status: 'processing', totalIncome: 42000, totalDeduction: 6300, netAmount: 35700 },
]

const mockDetailData = {
  id: 1, periodStart: '2026-05-01', periodEnd: '2026-05-15', status: 'completed',
  totalIncome: 28600, totalDeduction: 4300, netAmount: 24300,
  incomeByType: [
    { type: 'course', amount: 15800, count: 28 },
    { type: 'product', amount: 8600, count: 45 },
    { type: 'booking', amount: 3200, count: 12 },
    { type: 'commission', amount: 1000, count: 5 },
  ],
  incomeItems: [
    { id: 1, type: 'course', title: '八字命理入门实战班', amount: 299, time: '2026-05-15' },
    { id: 2, type: 'product', title: '滴天髓精解', amount: 136, time: '2026-05-14' },
    { id: 3, type: 'booking', title: '一对一命理咨询', amount: 500, time: '2026-05-13' },
  ],
  deductionItems: [
    { id: 1, title: '平台服务费', amount: 2860, remark: '按总收入10%收取' },
    { id: 2, title: '手续费', amount: 1440, remark: '支付通道手续费' },
  ],
}

function getStatusLabel(status: string): string {
  const map: Record<string, string> = { pending: '待结算', processing: '结算中', completed: '已结算' }
  return map[status] || status
}

function getStatusStyle(status: string): { bg: string; color: string } {
  const map: Record<string, { bg: string; color: string }> = {
    pending: { bg: 'rgba(245,158,11,0.1)', color: '#F59E0B' },
    processing: { bg: 'rgba(59,130,246,0.1)', color: '#3B82F6' },
    completed: { bg: 'rgba(34,197,94,0.1)', color: '#22C55E' },
  }
  return map[status] || { bg: '#F1EDE8', color: '#999' }
}

function getIncomeTypeLabel(type: string): string {
  const map: Record<string, string> = { course: '课程收入', product: '商品收入', booking: '预约收入', commission: '佣金收入' }
  return map[type] || type
}

function getIncomeTypeIcon(type: string): string {
  const map: Record<string, string> = { course: '', product: '️', booking: '', commission: '🎁' }
  return map[type] || ''
}

function getIncomeTypeColor(type: string): { bg: string } {
  const map: Record<string, { bg: string }> = {
    course: { bg: 'rgba(59,130,246,0.1)' },
    product: { bg: 'rgba(34,197,94,0.1)' },
    booking: { bg: 'rgba(168,85,247,0.1)' },
    commission: { bg: 'rgba(245,158,11,0.1)' },
  }
  return map[type] || { bg: '#F1EDE8' }
}

function openDetail(settlement: any) {
  detailData.value = { ...mockDetailData, ...settlement }
  showDetail.value = true
}

function goBack() { uni.navigateBack() }
</script>

<style scoped>
/* 样式由 Tailwind 处理 */
</style>

// v0-reference/proto-ref-app/offline/settlements/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import { 
  ChevronLeft, 
  Calendar,
  TrendingUp,
  Wallet,
  Clock,
  CheckCircle,
  ChevronRight,
  Filter,
  X,
  BookOpen,
  ShoppingBag,
  Users,
  Gift
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { 
  getSettlements,
  getSettlementDetail,
  getSettlementStatusLabel,
  getSettlementStatusColor,
  getIncomeTypeLabel,
  getIncomeTypeColor,
} from "@/lib/api/offline"
import type { Settlement, SettlementDetail, SettlementStats, SettlementStatus, IncomeType } from "@/lib/types/offline"

function Skeleton({ className }: { className?: string }) {
  return <div className={cn("animate-pulse bg-muted rounded", className)} />
}

function LoadingSkeleton() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 bg-background border-b border-border px-4 py-3">
        <div className="flex items-center gap-3">
          <Skeleton className="w-8 h-8 rounded-full" />
          <Skeleton className="h-5 w-24" />
        </div>
      </header>
      <div className="p-4 space-y-4">
        <Skeleton className="h-32 rounded-lg" />
        <Skeleton className="h-24 rounded-lg" />
        <Skeleton className="h-24 rounded-lg" />
      </div>
    </div>
  )
}

function SettlementsContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const stationId = Number(searchParams.get('stationId')) || 1

  const [settlements, setSettlements] = useState<Settlement[]>([])
  const [stats, setStats] = useState<SettlementStats | null>(null)
  const [loading, setLoading] = useState(true)
  const [selectedStatus, setSelectedStatus] = useState<SettlementStatus | 'all'>('all')
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [showDetail, setShowDetail] = useState(false)
  const [detailData, setDetailData] = useState<SettlementDetail | null>(null)
  const [detailLoading, setDetailLoading] = useState(false)
  const [showFilter, setShowFilter] = useState(false)

  const statusOptions: { value: SettlementStatus | 'all'; label: string }[] = [
    { value: 'all', label: '全部' },
    { value: 'pending', label: '待结算' },
    { value: 'processing', label: '结算中' },
    { value: 'completed', label: '已结算' },
  ]

  const years = [2026, 2025, 2024]

  useEffect(() => {
    loadSettlements()
  }, [stationId, selectedStatus, selectedYear])

  async function loadSettlements() {
    setLoading(true)
    try {
      const res = await getSettlements({
        stationId,
        status: selectedStatus === 'all' ? undefined : selectedStatus,
        year: selectedYear,
      })
      if (res.code === 200 && res.data) {
        setSettlements(res.data.list)
        setStats(res.data.stats)
      }
    } finally {
      setLoading(false)
    }
  }

  async function openDetail(settlement: Settlement) {
    setShowDetail(true)
    setDetailLoading(true)
    try {
      const res = await getSettlementDetail(settlement.id)
      if (res.code === 200 && res.data) {
        setDetailData(res.data)
      }
    } finally {
      setDetailLoading(false)
    }
  }

  function getIncomeIcon(type: IncomeType) {
    const icons = {
      course: BookOpen,
      product: ShoppingBag,
      booking: Users,
      commission: Gift,
    }
    return icons[type]
  }

  return (
    <div className="min-h-screen bg-background pb-4">
      {/* 头部 */}
      <header className="sticky top-0 z-10 bg-background border-b border-border px-4 py-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button 
              variant="ghost" 
              size="icon" 
              className="h-8 w-8"
              onClick={() => router.back()}
            >
              <ChevronLeft className="h-5 w-5" />
            </Button>
            <h1 className="text-lg font-semibold">收入结算</h1>
          </div>
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => setShowFilter(true)}
          >
            <Filter className="h-5 w-5" />
          </Button>
        </div>
      </header>

      {/* 统计卡片 */}
      {stats && (
        <div className="p-4">
          <div className="bg-gradient-to-r from-primary to-primary/80 rounded-xl p-4 text-primary-foreground">
            <div className="text-sm opacity-90 mb-1">累计收入</div>
            <div className="text-3xl font-bold mb-4">
              ¥{stats.totalNetAmount.toLocaleString()}
            </div>
            <div className="grid grid-cols-3 gap-4 text-sm">
              <div>
                <div className="opacity-75">总收入</div>
                <div className="font-medium">¥{stats.totalIncome.toLocaleString()}</div>
              </div>
              <div>
                <div className="opacity-75">扣除</div>
                <div className="font-medium">¥{stats.totalDeduction.toLocaleString()}</div>
              </div>
              <div>
                <div className="opacity-75">待结算</div>
                <div className="font-medium">¥{stats.pendingAmount.toLocaleString()}</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 状态筛选 */}
      <div className="px-4 mb-4">
        <div className="flex gap-2 overflow-x-auto pb-2">
          {statusOptions.map(option => (
            <Button
              key={option.value}
              variant={selectedStatus === option.value ? "default" : "outline"}
              size="sm"
              className="flex-shrink-0"
              onClick={() => setSelectedStatus(option.value)}
            >
              {option.label}
            </Button>
          ))}
        </div>
      </div>

      {/* 结算列表 */}
      <div className="px-4 space-y-3">
        {loading ? (
          Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-28 rounded-lg" />
          ))
        ) : settlements.length === 0 ? (
          <div className="text-center py-12">
            <Wallet className="h-12 w-12 mx-auto text-muted-foreground/50 mb-3" />
            <p className="text-muted-foreground">暂无结算记录</p>
          </div>
        ) : (
          settlements.map(settlement => (
            <div
              key={settlement.id}
              className="bg-card rounded-lg border border-border p-4 cursor-pointer active:bg-muted/50"
              onClick={() => openDetail(settlement)}
            >
              <div className="flex items-start justify-between mb-3">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm">
                      {settlement.periodStart} ~ {settlement.periodEnd}
                    </span>
                  </div>
                  <div className="text-xs text-muted-foreground">
                    结算单号：{settlement.settlementNo}
                  </div>
                </div>
                <span className={cn(
                  "text-xs px-2 py-0.5 rounded-full",
                  getSettlementStatusColor(settlement.status)
                )}>
                  {getSettlementStatusLabel(settlement.status)}
                </span>
              </div>

              <div className="flex items-end justify-between">
                <div className="grid grid-cols-3 gap-4 text-sm flex-1">
                  <div>
                    <div className="text-muted-foreground text-xs">收入</div>
                    <div className="font-medium">¥{settlement.totalIncome.toLocaleString()}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground text-xs">扣除</div>
                    <div className="font-medium text-red-500">-¥{settlement.totalDeduction.toLocaleString()}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground text-xs">实收</div>
                    <div className="font-medium text-green-600">¥{settlement.netAmount.toLocaleString()}</div>
                  </div>
                </div>
                <ChevronRight className="h-5 w-5 text-muted-foreground" />
              </div>
            </div>
          ))
        )}
      </div>

      {/* 筛选弹窗 */}
      {showFilter && (
        <div className="fixed inset-0 z-50 bg-black/50" onClick={() => setShowFilter(false)}>
          <div 
            className="absolute bottom-0 left-0 right-0 bg-background rounded-t-2xl p-4"
            onClick={e => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold">筛选</h3>
              <Button variant="ghost" size="icon" onClick={() => setShowFilter(false)}>
                <X className="h-5 w-5" />
              </Button>
            </div>

            <div className="mb-4">
              <div className="text-sm text-muted-foreground mb-2">选择年份</div>
              <div className="flex flex-wrap gap-2">
                {years.map(year => (
                  <Button
                    key={year}
                    variant={selectedYear === year ? "default" : "outline"}
                    size="sm"
                    onClick={() => setSelectedYear(year)}
                  >
                    {year}年
                  </Button>
                ))}
              </div>
            </div>

            <Button 
              className="w-full" 
              onClick={() => setShowFilter(false)}
            >
              确定
            </Button>
          </div>
        </div>
      )}

      {/* 详情弹窗 */}
      {showDetail && (
        <div className="fixed inset-0 z-50 bg-black/50" onClick={() => setShowDetail(false)}>
          <div 
            className="absolute bottom-0 left-0 right-0 bg-background rounded-t-2xl max-h-[85vh] overflow-y-auto"
            onClick={e => e.stopPropagation()}
          >
            <div className="sticky top-0 bg-background border-b border-border p-4 flex items-center justify-between">
              <h3 className="font-semibold">结算详情</h3>
              <Button variant="ghost" size="icon" onClick={() => setShowDetail(false)}>
                <X className="h-5 w-5" />
              </Button>
            </div>

            {detailLoading ? (
              <div className="p-4 space-y-4">
                <Skeleton className="h-20 rounded-lg" />
                <Skeleton className="h-40 rounded-lg" />
              </div>
            ) : detailData && (
              <div className="p-4 space-y-4">
                {/* 结算概览 */}
                <div className="bg-muted/50 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm">
                      {detailData.periodStart} ~ {detailData.periodEnd}
                    </span>
                    <span className={cn(
                      "text-xs px-2 py-0.5 rounded-full ml-auto",
                      getSettlementStatusColor(detailData.status)
                    )}>
                      {getSettlementStatusLabel(detailData.status)}
                    </span>
                  </div>
                  <div className="grid grid-cols-3 gap-4 text-center">
                    <div>
                      <div className="text-xs text-muted-foreground">总收入</div>
                      <div className="font-semibold">¥{detailData.totalIncome.toLocaleString()}</div>
                    </div>
                    <div>
                      <div className="text-xs text-muted-foreground">扣除</div>
                      <div className="font-semibold text-red-500">-¥{detailData.totalDeduction.toLocaleString()}</div>
                    </div>
                    <div>
                      <div className="text-xs text-muted-foreground">实收</div>
                      <div className="font-semibold text-green-600">¥{detailData.netAmount.toLocaleString()}</div>
                    </div>
                  </div>
                </div>

                {/* 收入构成 */}
                <div>
                  <h4 className="font-medium mb-3">收入构成</h4>
                  <div className="grid grid-cols-2 gap-3">
                    {detailData.incomeByType.map(item => {
                      const Icon = getIncomeIcon(item.type)
                      return (
                        <div key={item.type} className="bg-card rounded-lg border border-border p-3">
                          <div className="flex items-center gap-2 mb-2">
                            <div className={cn("p-1.5 rounded", getIncomeTypeColor(item.type))}>
                              <Icon className="h-4 w-4" />
                            </div>
                            <span className="text-sm">{getIncomeTypeLabel(item.type)}</span>
                          </div>
                          <div className="font-semibold">¥{item.amount.toLocaleString()}</div>
                          <div className="text-xs text-muted-foreground">{item.count}笔</div>
                        </div>
                      )
                    })}
                  </div>
                </div>

                {/* 收入明细 */}
                <div>
                  <h4 className="font-medium mb-3">收入明细</h4>
                  <div className="space-y-2">
                    {detailData.incomeItems.map(item => {
                      const Icon = getIncomeIcon(item.type)
                      return (
                        <div key={item.id} className="flex items-center gap-3 py-2 border-b border-border last:border-0">
                          <div className={cn("p-1.5 rounded", getIncomeTypeColor(item.type))}>
                            <Icon className="h-4 w-4" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="text-sm truncate">{item.title}</div>
                            <div className="text-xs text-muted-foreground">{item.time}</div>
                          </div>
                          <div className="font-medium text-green-600">+¥{item.amount}</div>
                        </div>
                      )
                    })}
                  </div>
                </div>

                {/* 扣除明细 */}
                <div>
                  <h4 className="font-medium mb-3">扣除明细</h4>
                  <div className="space-y-2">
                    {detailData.deductionItems.map(item => (
                      <div key={item.id} className="flex items-center justify-between py-2 border-b border-border last:border-0">
                        <div>
                          <div className="text-sm">{item.title}</div>
                          {item.remark && (
                            <div className="text-xs text-muted-foreground">{item.remark}</div>
                          )}
                        </div>
                        <div className="font-medium text-red-500">-¥{item.amount.toLocaleString()}</div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

export default function SettlementsPage() {
  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <SettlementsContent />
    </Suspense>
  )
}
