// proto-ref-app/courses/study-plan/page.tsx
"use client"

import { useState, useEffect, useCallback } from "react"
import { useRouter } from "next/navigation"
import {
  ChevronLeft, Target, Flame, CheckCircle2, Circle, Clock,
  Plus, Pencil, Trash2, GripVertical, Check, X, BookOpen,
  TrendingUp, Calendar, Award
} from "lucide-react"
import { cn } from "@/lib/utils"

// ─── 类型定义 ─────────────────────────────────
interface StudyGoal {
  daysPerWeek: number   // 每周学习天数 1-7
  minutesPerDay: number // 每日目标时长（分钟）
}

interface PlannedCourse {
  id: string
  courseId: string
  title: string
  cover: string
  totalLessons: number
  completedLessons: number
  scheduledDays: number[] // 0=周日 1=周一 ... 6=周六
  order: number
}

interface DailyTask {
  id: string
  courseId: string
  title: string
  lessonTitle: string
  duration: number // 分钟
  isDone: boolean
  date: string // YYYY-MM-DD
}

// ─── Mock 数据（等待后端API） ──────────────────
const MOCK_GOAL: StudyGoal = { daysPerWeek: 5, minutesPerDay: 30 }

const MOCK_COURSES: PlannedCourse[] = [
  {
    id: "pc1", courseId: "c1",
    title: "八字命理入门精讲",
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=120&h=80&fit=crop",
    totalLessons: 32, completedLessons: 12,
    scheduledDays: [1, 3, 5], order: 0,
  },
  {
    id: "pc2", courseId: "c2",
    title: "紫微斗数基础课",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=120&h=80&fit=crop",
    totalLessons: 24, completedLessons: 6,
    scheduledDays: [2, 4], order: 1,
  },
  {
    id: "pc3", courseId: "c3",
    title: "周易易经入门",
    cover: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=120&h=80&fit=crop",
    totalLessons: 18, completedLessons: 0,
    scheduledDays: [6], order: 2,
  },
]

const WEEK_LABELS = ["日", "一", "二", "三", "四", "五", "六"]
const TODAY = new Date()
const todayStr = TODAY.toISOString().slice(0, 10)
const todayDay = TODAY.getDay()

// 打卡记录数据（过去30天）
const generateCheckInData = () => {
  const data: { [key: string]: number } = {}
  for (let i = 0; i < 30; i++) {
    const date = new Date(TODAY)
    date.setDate(date.getDate() - i)
    const dateStr = date.toISOString().slice(0, 10)
    // 模拟打卡数据：0=未打卡, 1=少量, 2=中等, 3=大量
    const rand = Math.random()
    if (rand > 0.3) {
      data[dateStr] = rand > 0.8 ? 3 : rand > 0.6 ? 2 : 1
    }
  }
  return data
}

const MOCK_CHECKIN_DATA = generateCheckInData()

// ─── 生成今日任务 ──────────────────────────────
function generateTodayTasks(courses: PlannedCourse[]): DailyTask[] {
  return courses
    .filter(c => c.scheduledDays.includes(todayDay))
    .map(c => ({
      id: `task-${c.courseId}`,
      courseId: c.courseId,
      title: c.title,
      lessonTitle: `第 ${c.completedLessons + 1} 课`,
      duration: 30,
      isDone: false,
      date: todayStr,
    }))
}

// ─── 组件：打卡日历热力图 ────────────────────────
function CheckInCalendar({ data }: { data: { [key: string]: number } }) {
  // 生成过去4周的日期
  const weeks: Date[][] = []
  const startDate = new Date(TODAY)
  startDate.setDate(startDate.getDate() - 27) // 从28天前开始
  // 对齐到周日
  startDate.setDate(startDate.getDate() - startDate.getDay())
  
  for (let w = 0; w < 4; w++) {
    const week: Date[] = []
    for (let d = 0; d < 7; d++) {
      const date = new Date(startDate)
      date.setDate(date.getDate() + w * 7 + d)
      week.push(date)
    }
    weeks.push(week)
  }
  
  const getIntensityColor = (level: number) => {
    switch (level) {
      case 0: return "bg-[#F2EFEA]"
      case 1: return "bg-[#FFE5E5]"
      case 2: return "bg-[#FF9999]"
      case 3: return "bg-[#C41E3A]"
      default: return "bg-[#F2EFEA]"
    }
  }
  
  const totalDays = Object.values(data).filter(v => v > 0).length
  
  return (
    <div className="bg-white rounded-2xl p-4 shadow-[0_2px_12px_rgba(0,0,0,0.06)] mb-4">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-[#C41E3A]/10 rounded-lg flex items-center justify-center">
            <Calendar className="w-4 h-4 text-[#C41E3A]" />
          </div>
          <span className="text-[15px] font-semibold text-[#2C2C2C]">打卡日历</span>
        </div>
        <span className="text-[12px] text-[#999999]">近30天打卡 <span className="text-[#C41E3A] font-medium">{totalDays}</span> 天</span>
      </div>
      
      {/* 星期标签 */}
      <div className="flex mb-2">
        <div className="w-6" />
        {WEEK_LABELS.map((label, i) => (
          <div key={i} className="flex-1 text-center text-[10px] text-[#999999]">{label}</div>
        ))}
      </div>
      
      {/* 热力图网格 */}
      <div className="space-y-1">
        {weeks.map((week, wi) => (
          <div key={wi} className="flex items-center">
            <div className="w-6 text-[10px] text-[#999999]">
              {week[0].getMonth() + 1}月
            </div>
            {week.map((date, di) => {
              const dateStr = date.toISOString().slice(0, 10)
              const level = data[dateStr] || 0
              const isToday = dateStr === todayStr
              const isFuture = date > TODAY
              
              return (
                <div key={di} className="flex-1 flex justify-center">
                  <div 
                    className={cn(
                      "w-6 h-6 rounded-md transition-colors",
                      isFuture ? "bg-transparent" : getIntensityColor(level),
                      isToday && "ring-2 ring-[#C41E3A] ring-offset-1"
                    )}
                    title={`${dateStr}: ${level > 0 ? "已打卡" : "未打卡"}`}
                  />
                </div>
              )
            })}
          </div>
        ))}
      </div>
      
      {/* 图例 */}
      <div className="flex items-center justify-end gap-1 mt-3 text-[10px] text-[#999999]">
        <span>少</span>
        <div className="w-3 h-3 rounded bg-[#F2EFEA]" />
        <div className="w-3 h-3 rounded bg-[#FFE5E5]" />
        <div className="w-3 h-3 rounded bg-[#FF9999]" />
        <div className="w-3 h-3 rounded bg-[#C41E3A]" />
        <span>多</span>
      </div>
    </div>
  )
}

// ─── 组件：目标设置卡片 ────────────────────────
function GoalCard({
  goal, onEdit,
}: { goal: StudyGoal; onEdit: () => void }) {
  const pct = Math.min(100, Math.round((goal.daysPerWeek / 7) * 100))
  return (
    <div className="bg-white rounded-2xl p-4 shadow-[0_2px_12px_rgba(0,0,0,0.06)] mb-4">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-[#C41E3A]/10 rounded-lg flex items-center justify-center">
            <Target className="w-4 h-4 text-[#C41E3A]" />
          </div>
          <span className="text-[15px] font-semibold text-[#2C2C2C]">学习目标</span>
        </div>
        <button
          onClick={onEdit}
          className="flex items-center gap-1 text-[12px] text-[#C41E3A] font-medium"
        >
          <Pencil className="w-3.5 h-3.5" /> 编辑
        </button>
      </div>

      <div className="flex items-center gap-4 mb-3">
        <div className="flex-1 text-center bg-[#FAF8F5] rounded-xl py-3">
          <div className="text-[28px] font-black text-[#C41E3A] leading-none">{goal.daysPerWeek}</div>
          <div className="text-[11px] text-[#999] mt-1">天 / 周</div>
        </div>
        <div className="flex-1 text-center bg-[#FAF8F5] rounded-xl py-3">
          <div className="text-[28px] font-black text-[#C9A96E] leading-none">{goal.minutesPerDay}</div>
          <div className="text-[11px] text-[#999] mt-1">分钟 / 天</div>
        </div>
        <div className="flex-1 text-center bg-[#FAF8F5] rounded-xl py-3">
          <div className="text-[28px] font-black text-[#4A90D9] leading-none">
            {goal.daysPerWeek * goal.minutesPerDay}
          </div>
          <div className="text-[11px] text-[#999] mt-1">分钟 / 周</div>
        </div>
      </div>

      {/* 周计划指示格 */}
      <div className="flex gap-1.5">
        {WEEK_LABELS.map((label, i) => {
          const isToday = i === todayDay
          const planned = i !== 0 && i <= goal.daysPerWeek
          return (
            <div
              key={i}
              className={cn(
                "flex-1 h-8 rounded-md flex flex-col items-center justify-center gap-0.5 transition-all",
                isToday
                  ? "bg-[#C41E3A] text-white"
                  : planned
                    ? "bg-[#C41E3A]/10 text-[#C41E3A]"
                    : "bg-[#F2EFEA] text-[#BBBBBB]"
              )}
            >
              <span className="text-[9px] font-medium">{label}</span>
              {planned && !isToday && <div className="w-1 h-1 rounded-full bg-[#C41E3A]/50" />}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ─── 组件：今日任务卡片 ────────────────────────
function TodayTaskCard({
  tasks, onToggle,
}: { tasks: DailyTask[]; onToggle: (id: string) => void }) {
  const doneCount = tasks.filter(t => t.isDone).length
  const totalMin = tasks.reduce((s, t) => s + t.duration, 0)
  const doneMin = tasks.filter(t => t.isDone).reduce((s, t) => s + t.duration, 0)

  return (
    <div className="bg-white rounded-2xl shadow-[0_2px_12px_rgba(0,0,0,0.06)] mb-4 overflow-hidden">
      {/* 标题行 */}
      <div className="px-4 pt-4 pb-3 border-b border-[#F2EFEA]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-orange-50 rounded-lg flex items-center justify-center">
              <Flame className="w-4 h-4 text-orange-500" />
            </div>
            <div>
              <span className="text-[15px] font-semibold text-[#2C2C2C]">今日任务</span>
              <span className="text-[12px] text-[#999] ml-2">
                {new Date().toLocaleDateString("zh-CN", { month: "long", day: "numeric", weekday: "long" })}
              </span>
            </div>
          </div>
          <div className="text-[13px] font-bold text-[#C41E3A]">
            {doneCount}/{tasks.length}
          </div>
        </div>
        {/* 进度条 */}
        <div className="mt-2.5 h-1.5 bg-[#F2EFEA] rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-[#C41E3A] to-[#E74C3C] rounded-full transition-all duration-500"
            style={{ width: tasks.length ? `${(doneCount / tasks.length) * 100}%` : "0%" }}
          />
        </div>
        <div className="flex justify-between mt-1">
          <span className="text-[10px] text-[#999]">计划 {totalMin} 分钟</span>
          <span className="text-[10px] text-[#C41E3A]">已完成 {doneMin} 分钟</span>
        </div>
      </div>

      {/* 任务列表 */}
      {tasks.length === 0 ? (
        <div className="py-8 text-center text-[13px] text-[#BBBBBB]">
          今日没有安排学习任务
        </div>
      ) : (
        <div className="divide-y divide-[#F5F0E8]">
          {tasks.map(task => (
            <button
              key={task.id}
              onClick={() => onToggle(task.id)}
              className="w-full flex items-center gap-3 px-4 py-3 active:bg-[#FAF8F5] transition-colors text-left"
            >
              {task.isDone
                ? <CheckCircle2 className="w-5 h-5 text-[#52C41A] flex-shrink-0" />
                : <Circle className="w-5 h-5 text-[#DDDDDD] flex-shrink-0" />}
              <div className="flex-1 min-w-0">
                <div className={cn("text-[13px] font-medium truncate", task.isDone && "line-through text-[#BBBBBB]")}>
                  {task.title}
                </div>
                <div className="text-[11px] text-[#999] mt-0.5">{task.lessonTitle}</div>
              </div>
              <div className="flex items-center gap-1 text-[11px] text-[#BBBBBB] flex-shrink-0">
                <Clock className="w-3 h-3" />
                {task.duration}分钟
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

// ─── 组件：课程时间线卡片 ──────────────────────
function CourseTimeline({
  courses,
  draggingId,
  onDragStart,
  onDragOver,
  onDrop,
  onRemove,
  onAdd,
}: {
  courses: PlannedCourse[]
  draggingId: string | null
  onDragStart: (id: string) => void
  onDragOver: (id: string) => void
  onDrop: () => void
  onRemove: (id: string) => void
  onAdd: () => void
}) {
  return (
    <div className="bg-white rounded-2xl shadow-[0_2px_12px_rgba(0,0,0,0.06)] mb-4 overflow-hidden">
      <div className="flex items-center justify-between px-4 pt-4 pb-3 border-b border-[#F2EFEA]">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-[#4A90D9]/10 rounded-lg flex items-center justify-center">
            <Calendar className="w-4 h-4 text-[#4A90D9]" />
          </div>
          <span className="text-[15px] font-semibold text-[#2C2C2C]">课程安排</span>
        </div>
        <button
          onClick={onAdd}
          className="w-7 h-7 bg-[#C41E3A]/10 rounded-full flex items-center justify-center"
        >
          <Plus className="w-4 h-4 text-[#C41E3A]" />
        </button>
      </div>

      {courses.length === 0 ? (
        <button
          onClick={onAdd}
          className="w-full py-10 flex flex-col items-center gap-2 text-[#BBBBBB]"
        >
          <BookOpen className="w-8 h-8" />
          <span className="text-[13px]">还没有安排课程，点击添加</span>
        </button>
      ) : (
        <div className="divide-y divide-[#F5F0E8]">
          {courses.map((course, idx) => {
            const pct = Math.round((course.completedLessons / course.totalLessons) * 100)
            const isDragging = draggingId === course.id
            return (
              <div
                key={course.id}
                draggable
                onDragStart={() => onDragStart(course.id)}
                onDragOver={e => { e.preventDefault(); onDragOver(course.id) }}
                onDrop={onDrop}
                className={cn(
                  "flex items-center gap-3 px-4 py-3 transition-all",
                  isDragging && "opacity-40 bg-[#FAF8F5]"
                )}
              >
                {/* 拖拽把手 */}
                <GripVertical className="w-4 h-4 text-[#DDDDDD] flex-shrink-0 cursor-grab active:cursor-grabbing" />

                {/* 封面 */}
                <div className="w-12 h-12 rounded-lg overflow-hidden flex-shrink-0 bg-[#F2EFEA]">
                  <img src={course.cover} alt={course.title} className="w-full h-full object-cover" />
                </div>

                {/* 信息 */}
                <div className="flex-1 min-w-0">
                  <div className="text-[13px] font-medium text-[#2C2C2C] truncate">{course.title}</div>
                  <div className="flex items-center gap-2 mt-1">
                    {/* 进度 */}
                    <div className="flex-1 h-1.5 bg-[#F2EFEA] rounded-full overflow-hidden">
                      <div
                        className="h-full bg-gradient-to-r from-[#C41E3A] to-[#E74C3C] rounded-full"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                    <span className="text-[10px] text-[#BBBBBB] flex-shrink-0">{pct}%</span>
                  </div>
                  {/* 计划日 */}
                  <div className="flex gap-1 mt-1.5">
                    {WEEK_LABELS.map((l, i) => (
                      <span
                        key={i}
                        className={cn(
                          "text-[9px] w-4 h-4 rounded flex items-center justify-center font-medium",
                          course.scheduledDays.includes(i)
                            ? "bg-[#C41E3A] text-white"
                            : "bg-[#F2EFEA] text-[#CCCCCC]"
                        )}
                      >{l}</span>
                    ))}
                  </div>
                </div>

                {/* 删除 */}
                <button
                  onClick={() => onRemove(course.id)}
                  className="w-7 h-7 rounded-full flex items-center justify-center text-[#DDDDDD] active:text-red-400 flex-shrink-0"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

// ─── 组件：目标编辑弹窗 ────────────────────────
function GoalEditor({
  goal, onSave, onClose,
}: { goal: StudyGoal; onSave: (g: StudyGoal) => void; onClose: () => void }) {
  const [days, setDays] = useState(goal.daysPerWeek)
  const [minutes, setMinutes] = useState(goal.minutesPerDay)
  const minuteOptions = [15, 20, 30, 45, 60, 90, 120]

  return (
    <div className="fixed inset-0 z-50 flex items-end">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative w-full bg-white rounded-t-2xl px-4 pt-4 pb-8 safe-area-bottom">
        <div className="flex items-center justify-between mb-4">
          <span className="text-[16px] font-bold text-[#2C2C2C]">设置学习目标</span>
          <button onClick={onClose}><X className="w-5 h-5 text-[#999]" /></button>
        </div>

        {/* 每周天数 */}
        <div className="mb-4">
          <div className="text-[13px] text-[#666] mb-2">每周学习天数</div>
          <div className="flex gap-2">
            {[1, 2, 3, 4, 5, 6, 7].map(d => (
              <button
                key={d}
                onClick={() => setDays(d)}
                className={cn(
                  "flex-1 py-2.5 rounded-xl text-[13px] font-bold transition-all",
                  days === d
                    ? "bg-[#C41E3A] text-white shadow-[0_4px_12px_rgba(196,30,58,0.3)]"
                    : "bg-[#F2EFEA] text-[#666]"
                )}
              >{d}</button>
            ))}
          </div>
        </div>

        {/* 每日时长 */}
        <div className="mb-6">
          <div className="text-[13px] text-[#666] mb-2">每日学习时长</div>
          <div className="flex flex-wrap gap-2">
            {minuteOptions.map(m => (
              <button
                key={m}
                onClick={() => setMinutes(m)}
                className={cn(
                  "px-4 py-2 rounded-xl text-[13px] font-bold transition-all",
                  minutes === m
                    ? "bg-[#C41E3A] text-white shadow-[0_4px_12px_rgba(196,30,58,0.3)]"
                    : "bg-[#F2EFEA] text-[#666]"
                )}
              >{m >= 60 ? `${m / 60}小时` : `${m}分钟`}</button>
            ))}
          </div>
        </div>

        <button
          onClick={() => { onSave({ daysPerWeek: days, minutesPerDay: minutes }); onClose() }}
          className="w-full py-3.5 bg-gradient-to-r from-[#C41E3A] to-[#E74C3C] text-white font-bold rounded-xl text-[15px] shadow-[0_4px_16px_rgba(196,30,58,0.35)]"
        >
          保存目标
        </button>
      </div>
    </div>
  )
}

// ─── 主页面 ───────────────────────────────────
export default function StudyPlanPage() {
  const router = useRouter()

  // 从 localStorage 读取或使用 mock 数据
  const [goal, setGoal] = useState<StudyGoal>(MOCK_GOAL)
  const [courses, setCourses] = useState<PlannedCourse[]>(MOCK_COURSES)
  const [tasks, setTasks] = useState<DailyTask[]>([])
  const [showGoalEditor, setShowGoalEditor] = useState(false)
  const [draggingId, setDraggingId] = useState<string | null>(null)
  const [dragOverId, setDragOverId] = useState<string | null>(null)

  // 初始化：从 localStorage 读取
  useEffect(() => {
    try {
      const savedGoal = localStorage.getItem("study_goal")
      const savedCourses = localStorage.getItem("study_courses")
      const savedTasks = localStorage.getItem(`study_tasks_${todayStr}`)
      if (savedGoal) setGoal(JSON.parse(savedGoal))
      if (savedCourses) setCourses(JSON.parse(savedCourses))
      if (savedTasks) setTasks(JSON.parse(savedTasks))
      else setTasks(generateTodayTasks(savedCourses ? JSON.parse(savedCourses) : MOCK_COURSES))
    } catch {
      setTasks(generateTodayTasks(MOCK_COURSES))
    }
  }, [])

  const saveGoal = (g: StudyGoal) => {
    setGoal(g)
    localStorage.setItem("study_goal", JSON.stringify(g))
  }

  const toggleTask = (id: string) => {
    setTasks(prev => {
      const next = prev.map(t => t.id === id ? { ...t, isDone: !t.isDone } : t)
      localStorage.setItem(`study_tasks_${todayStr}`, JSON.stringify(next))
      return next
    })
  }

  const removeCourse = (id: string) => {
    setCourses(prev => {
      const next = prev.filter(c => c.id !== id)
      localStorage.setItem("study_courses", JSON.stringify(next))
      return next
    })
  }

  // 拖拽排序
  const handleDrop = () => {
    if (!draggingId || !dragOverId || draggingId === dragOverId) {
      setDraggingId(null); setDragOverId(null); return
    }
    setCourses(prev => {
      const arr = [...prev]
      const fromIdx = arr.findIndex(c => c.id === draggingId)
      const toIdx = arr.findIndex(c => c.id === dragOverId)
      const [item] = arr.splice(fromIdx, 1)
      arr.splice(toIdx, 0, item)
      const reordered = arr.map((c, i) => ({ ...c, order: i }))
      localStorage.setItem("study_courses", JSON.stringify(reordered))
      return reordered
    })
    setDraggingId(null); setDragOverId(null)
  }

  // 完成度统计
  const doneCount = tasks.filter(t => t.isDone).length
  const streak = 7 // TODO: 从后端获取

  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      {/* 导航栏 */}
      <div className="sticky top-0 z-10 bg-[#C41E3A] text-white">
        <div className="flex items-center h-14 px-4 gap-3">
          <button onClick={() => router.back()} className="w-8 h-8 flex items-center justify-center">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <span className="flex-1 text-[17px] font-bold">学习计划</span>
          <div className="flex items-center gap-1 bg-white/20 px-2.5 py-1 rounded-full">
            <Flame className="w-3.5 h-3.5 text-orange-300" />
            <span className="text-[12px] font-bold">{streak}天连续</span>
          </div>
        </div>
      </div>

      {/* 完成度统计条 */}
      <div className="bg-gradient-to-r from-[#C41E3A] to-[#9B0B28] px-4 pb-5 pt-1">
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[12px] text-white/80">今日完成</span>
              <span className="text-[12px] text-white font-bold">{doneCount}/{tasks.length} 项</span>
            </div>
            <div className="h-2 bg-white/20 rounded-full overflow-hidden">
              <div
                className="h-full bg-[#C9A96E] rounded-full transition-all duration-500"
                style={{ width: tasks.length ? `${(doneCount / tasks.length) * 100}%` : "0%" }}
              />
            </div>
          </div>
          <div className="text-center">
            <div className="text-[24px] font-black text-[#C9A96E] leading-none">
              {tasks.length ? Math.round((doneCount / tasks.length) * 100) : 0}%
            </div>
            <div className="text-[10px] text-white/60 mt-0.5">完成率</div>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4">
        {/* 打卡日历热力图 */}
        <CheckInCalendar data={MOCK_CHECKIN_DATA} />
        
        {/* 目标卡片 */}
        <GoalCard goal={goal} onEdit={() => setShowGoalEditor(true)} />

        {/* 今日任务 */}
        <TodayTaskCard tasks={tasks} onToggle={toggleTask} />

        {/* 课程时间线 */}
        <CourseTimeline
          courses={courses}
          draggingId={draggingId}
          onDragStart={setDraggingId}
          onDragOver={setDragOverId}
          onDrop={handleDrop}
          onRemove={removeCourse}
          onAdd={() => router.push("/courses-list")}
        />

        {/* 底部去选课提示 */}
        <div className="mt-2 mb-8 text-center">
          <span className="text-[12px] text-[#BBBBBB]">从</span>
          <button
            onClick={() => router.push("/courses-list")}
            className="text-[12px] text-[#C41E3A] font-medium mx-1"
          >课程广场</button>
          <span className="text-[12px] text-[#BBBBBB]">添加更多课程到学习计划</span>
        </div>
      </div>

      {/* 目标编辑弹窗 */}
      {showGoalEditor && (
        <GoalEditor
          goal={goal}
          onSave={saveGoal}
          onClose={() => setShowGoalEditor(false)}
        />
      )}
    </div>
  )
}

// apps/mobile/src/pages/courses/study-plan.vue
<template>
  <view class="page">
    <!-- 导航栏 -->
    <view class="nav-bar">
      <view class="nav-content">
        <text
          class="back-btn"
          @click="uni.navigateBack"
        >
          ‹
        </text>
        <text class="nav-title">
          学习计划
        </text>
        <view class="nav-streak">
          <text class="streak-icon">
            🔥
          </text>
          <text class="streak-val">
            {{ streak }}天连续
          </text>
        </view>
      </view>
    </view>

    <!-- 完成度统计 -->
    <view class="progress-bar">
      <view class="progress-left">
        <view class="progress-header">
          <text class="progress-label">
            今日完成
          </text>
          <text class="progress-fraction">
            {{ doneCount }}/{{ tasks.length }} 项
          </text>
        </view>
        <view class="progress-track">
          <view
            class="progress-fill"
            :style="{ width: progressPct + '%' }"
          />
        </view>
      </view>
      <view class="progress-right">
        <text class="progress-pct">
          {{ progressPct }}%
        </text>
        <text class="progress-pct-label">
          完成率
        </text>
      </view>
    </view>

    <scroll-view
      scroll-y
      class="scroll-area"
    >
      <!-- 学习目标卡片 -->
      <view class="goal-card">
        <view class="goal-header">
          <view class="goal-title-row">
            <text class="goal-icon">
              🎯
            </text>
            <text class="goal-title">
              学习目标
            </text>
          </view>
          <text
            class="goal-edit"
            @click="showGoalEditor = true"
          >
            ✏️ 编辑
          </text>
        </view>
        <view class="goal-stats">
          <view class="goal-stat">
            <text
              class="goal-val"
              style="color:#C41E3A"
            >
              {{ goal.daysPerWeek }}
            </text>
            <text class="goal-label">
              天 / 周
            </text>
          </view>
          <view class="goal-stat">
            <text
              class="goal-val"
              style="color:#C9A96E"
            >
              {{ goal.minutesPerDay }}
            </text>
            <text class="goal-label">
              分钟 / 天
            </text>
          </view>
          <view class="goal-stat">
            <text
              class="goal-val"
              style="color:#4A90D9"
            >
              {{ goal.daysPerWeek * goal.minutesPerDay }}
            </text>
            <text class="goal-label">
              分钟 / 周
            </text>
          </view>
        </view>
        <!-- 周计划指示格 -->
        <view class="week-grid">
          <view
            v-for="(label, i) in weekLabels"
            :key="i"
            class="week-cell"
            :class="{ 'week-today': i === todayDay, 'week-planned': i > 0 && i <= goal.daysPerWeek }"
          >
            <text class="week-label">
              {{ label }}
            </text>
          </view>
        </view>
      </view>

      <!-- 今日任务 -->
      <view class="task-card">
        <view class="task-header">
          <view class="task-title-row">
            <text class="task-icon">
              🔥
            </text>
            <view class="task-title-group">
              <text class="task-card-title">
                今日任务
              </text>
              <text class="task-date">
                {{ todayDateStr }}
              </text>
            </view>
          </view>
          <text class="task-count">
            {{ doneCount }}/{{ tasks.length }}
          </text>
        </view>
        <view class="task-progress">
          <view class="task-progress-track">
            <view
              class="task-progress-fill"
              :style="{ width: progressPct + '%' }"
            />
          </view>
          <view class="task-progress-info">
            <text class="task-plan-time">
              计划 {{ totalMinutes }} 分钟
            </text>
            <text class="task-done-time">
              已完成 {{ doneMinutes }} 分钟
            </text>
          </view>
        </view>
        <view
          v-if="tasks.length === 0"
          class="task-empty"
        >
          <text>今日没有安排学习任务</text>
        </view>
        <view
          v-else
          class="task-list"
        >
          <view
            v-for="t in tasks"
            :key="t.id"
            class="task-item"
            @click="toggleTask(t.id)"
          >
            <view
              class="task-check"
              :class="{ 'task-checked': t.isDone }"
            >
              <text v-if="t.isDone">
                ✓
              </text>
            </view>
            <view class="task-info">
              <text
                class="task-name"
                :class="{ 'task-name-done': t.isDone }"
              >
                {{ t.title }}
              </text>
              <text class="task-lesson">
                {{ t.lessonTitle }}
              </text>
            </view>
            <text class="task-duration">
              🕐 {{ t.duration }}分钟
            </text>
          </view>
        </view>
      </view>

      <!-- 课程安排 -->
      <view class="course-card">
        <view class="course-card-header">
          <view class="course-card-title-row">
            <text class="course-card-icon">
              📅
            </text>
            <text class="course-card-title">
              课程安排
            </text>
          </view>
          <text
            class="course-add"
            @click="goAddCourse"
          >
            ＋
          </text>
        </view>
        <view
          v-if="courses.length === 0"
          class="course-empty"
          @click="goAddCourse"
        >
          <text class="course-empty-icon">
            📚
          </text>
          <text class="course-empty-text">
            还没有安排课程，点击添加
          </text>
        </view>
        <view
          v-else
          class="course-list"
        >
          <view
            v-for="(c, idx) in courses"
            :key="c.id"
            class="course-item"
            :class="{ 'course-dragging': draggingId === c.id }"
          >
            <text class="course-drag">
              ⠿
            </text>
            <image
              :src="c.cover"
              class="course-cover"
              mode="aspectFill"
            />
            <view class="course-info">
              <text class="course-name">
                {{ c.title }}
              </text>
              <view class="course-progress">
                <view class="course-progress-track">
                  <view
                    class="course-progress-fill"
                    :style="{ width: (c.completedLessons / c.totalLessons * 100) + '%' }"
                  />
                </view>
                <text class="course-progress-pct">
                  {{ Math.round(c.completedLessons / c.totalLessons * 100) }}%
                </text>
              </view>
              <view class="course-days">
                <text
                  v-for="(l, i) in weekLabels"
                  :key="i"
                  class="course-day"
                  :class="{ 'course-day-active': c.scheduledDays?.includes(i) }"
                >
                  {{ l }}
                </text>
              </view>
            </view>
            <text
              class="course-remove"
              @click="removeCourse(c.id)"
            >
              🗑️
            </text>
          </view>
        </view>
      </view>

      <!-- 底部提示 -->
      <view class="bottom-tip">
        <text class="tip-text">
          从
        </text>
        <text
          class="tip-link"
          @click="goAddCourse"
        >
          课程广场
        </text>
        <text class="tip-text">
          添加更多课程到学习计划
        </text>
      </view>

      <view class="bottom-spacer" />
    </scroll-view>

    <!-- 目标编辑弹窗 -->
    <view
      v-if="showGoalEditor"
      class="dialog-overlay"
      @click="showGoalEditor = false"
    >
      <view
        class="dialog-content"
        @click.stop
      >
        <view class="dialog-header">
          <text class="dialog-title">
            设置学习目标
          </text>
          <text
            class="dialog-close"
            @click="showGoalEditor = false"
          >
            ✕
          </text>
        </view>
        <view class="editor-section">
          <text class="editor-label">
            每周学习天数
          </text>
          <view class="days-selector">
            <text
              v-for="d in 7"
              :key="d"
              class="day-btn"
              :class="{ 'day-active': editDays === d }"
              @click="editDays = d"
            >
              {{ d }}
            </text>
          </view>
        </view>
        <view class="editor-section">
          <text class="editor-label">
            每日学习时长
          </text>
          <view class="minutes-selector">
            <text
              v-for="m in minuteOptions"
              :key="m"
              class="minute-btn"
              :class="{ 'minute-active': editMinutes === m }"
              @click="editMinutes = m"
            >
              {{ m >= 60 ? (m / 60) + '小时' : m + '分钟' }}
            </text>
          </view>
        </view>
        <text
          class="save-goal-btn"
          @click="saveGoal"
        >
          保存目标
        </text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

const showGoalEditor = ref(false)
const editDays = ref(5)
const editMinutes = ref(30)
const draggingId = ref<string | null>(null)
const streak = ref(7)

const weekLabels = ['日', '一', '二', '三', '四', '五', '六']
const today = new Date()
const todayDay = today.getDay()
const todayDateStr = today.toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' })
const minuteOptions = [15, 20, 30, 45, 60, 90, 120]

const goal = ref({ daysPerWeek: 5, minutesPerDay: 30 })
const courses = ref<any[]>([
  { id: 'pc1', courseId: 'c1', title: '八字命理入门精讲', cover: '', totalLessons: 32, completedLessons: 12, scheduledDays: [1, 3, 5], order: 0 },
  { id: 'pc2', courseId: 'c2', title: '紫微斗数基础课', cover: '', totalLessons: 24, completedLessons: 6, scheduledDays: [2, 4], order: 1 },
  { id: 'pc3', courseId: 'c3', title: '周易易经入门', cover: '', totalLessons: 18, completedLessons: 0, scheduledDays: [6], order: 2 },
])

const tasks = ref<any[]>([])
const loading = ref(false)

const doneCount = computed(() => tasks.value.filter((t: any) => t.isDone).length)
const totalMinutes = computed(() => tasks.value.reduce((s: number, t: any) => s + (t.duration || 0), 0))
const doneMinutes = computed(() => tasks.value.filter((t: any) => t.isDone).reduce((s: number, t: any) => s + (t.duration || 0), 0))
const progressPct = computed(() => tasks.value.length ? Math.round((doneCount.value / tasks.value.length) * 100) : 0)

onMounted(() => {
  loadFromStorage()
  initTasks()
})

function loadFromStorage() {
  try {
    const savedGoal = uni.getStorageSync('study_goal')
    const savedCourses = uni.getStorageSync('study_courses')
    if (savedGoal) goal.value = JSON.parse(savedGoal)
    if (savedCourses) courses.value = JSON.parse(savedCourses)
  } catch {}
}

function initTasks() {
  const todayStr = today.toISOString().slice(0, 10)
  try {
    const saved = uni.getStorageSync(`study_tasks_${todayStr}`)
    if (saved) {
      tasks.value = JSON.parse(saved)
      return
    }
  } catch {}
  // Generate from courses
  tasks.value = courses.value
    .filter((c: any) => c.scheduledDays?.includes(todayDay))
    .map((c: any) => ({
      id: `task-${c.courseId}`,
      courseId: c.courseId,
      title: c.title,
      lessonTitle: `第 ${c.completedLessons + 1} 课`,
      duration: goal.value.minutesPerDay,
      isDone: false,
      date: today.toISOString().slice(0, 10),
    }))
  saveTasks()
}

function saveTasks() {
  const todayStr = today.toISOString().slice(0, 10)
  uni.setStorageSync(`study_tasks_${todayStr}`, JSON.stringify(tasks.value))
}

function toggleTask(id: string) {
  const t = tasks.value.find((t: any) => t.id === id)
  if (t) {
    t.isDone = !t.isDone
    saveTasks()
  }
}

function removeCourse(id: string) {
  courses.value = courses.value.filter((c: any) => c.id !== id)
  uni.setStorageSync('study_courses', JSON.stringify(courses.value))
  initTasks()
}

function saveGoal() {
  goal.value = { daysPerWeek: editDays.value, minutesPerDay: editMinutes.value }
  uni.setStorageSync('study_goal', JSON.stringify(goal.value))
  showGoalEditor.value = false
  initTasks()
  uni.showToast({ title: '目标已保存' })
}

function goAddCourse() {
  uni.showToast({ title: '课程广场功能开发中', icon: 'none' })
}
</script>

<style scoped>
.page { background: #F5F0E8; min-height: 100vh; }

.nav-bar { background: #C41E3A; padding: 60rpx 24rpx 20rpx; }
.nav-content { display: flex; align-items: center; gap: 16rpx; }
.back-btn { font-size: 44rpx; color: #fff; line-height: 1; }
.nav-title { flex: 1; font-size: 32rpx; font-weight: 600; color: #fff; }
.nav-streak { display: flex; align-items: center; gap: 4rpx; background: rgba(255,255,255,0.2); padding: 6rpx 16rpx; border-radius: 20rpx; }
.streak-icon { font-size: 24rpx; }
.streak-val { font-size: 22rpx; color: #fff; font-weight: 500; }

.progress-bar { background: linear-gradient(135deg, #C41E3A, #9B0B28); padding: 8rpx 24rpx 24rpx; display: flex; gap: 24rpx; align-items: center; }
.progress-left { flex: 1; }
.progress-header { display: flex; justify-content: space-between; margin-bottom: 8rpx; }
.progress-label { font-size: 22rpx; color: rgba(255,255,255,0.8); }
.progress-fraction { font-size: 22rpx; color: #fff; font-weight: 600; }
.progress-track { height: 12rpx; background: rgba(255,255,255,0.2); border-radius: 6rpx; overflow: hidden; }
.progress-fill { height: 100%; background: #C9A96E; border-radius: 6rpx; transition: width 0.5s; }
.progress-right { text-align: center; }
.progress-pct { font-size: 40rpx; font-weight: bold; color: #C9A96E; display: block; line-height: 1; }
.progress-pct-label { font-size: 18rpx; color: rgba(255,255,255,0.6); margin-top: 4rpx; display: block; }

.scroll-area { padding: 24rpx; }

.goal-card { background: #fff; border-radius: 24rpx; padding: 24rpx; margin-bottom: 20rpx; box-shadow: 0 4rpx 16rpx rgba(0,0,0,0.06); }
.goal-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20rpx; }
.goal-title-row { display: flex; align-items: center; gap: 12rpx; }
.goal-icon { font-size: 32rpx; }
.goal-title { font-size: 28rpx; font-weight: 600; color: #2C2C2C; }
.goal-edit { font-size: 22rpx; color: #C41E3A; }
.goal-stats { display: flex; gap: 16rpx; margin-bottom: 20rpx; }
.goal-stat { flex: 1; text-align: center; background: #FAF8F5; border-radius: 16rpx; padding: 20rpx; }
.goal-val { font-size: 44rpx; font-weight: bold; display: block; line-height: 1; }
.goal-label { font-size: 20rpx; color: #999; margin-top: 8rpx; display: block; }
.week-grid { display: flex; gap: 8rpx; }
.week-cell { flex: 1; height: 56rpx; border-radius: 12rpx; display: flex; align-items: center; justify-content: center; background: #F2EFEA; }
.week-label { font-size: 22rpx; color: #bbb; }
.week-today { background: #C41E3A; }
.week-today .week-label { color: #fff; font-weight: 500; }
.week-planned { background: rgba(196,30,58,0.08); }
.week-planned .week-label { color: #C41E3A; }

.task-card { background: #fff; border-radius: 24rpx; margin-bottom: 20rpx; overflow: hidden; box-shadow: 0 4rpx 16rpx rgba(0,0,0,0.06); }
.task-header { padding: 24rpx 24rpx 0; display: flex; justify-content: space-between; align-items: flex-start; }
.task-title-row { display: flex; gap: 12rpx; }
.task-icon { font-size: 32rpx; }
.task-title-group { }
.task-card-title { font-size: 28rpx; font-weight: 600; color: #2C2C2C; display: block; }
.task-date { font-size: 22rpx; color: #999; margin-top: 4rpx; display: block; }
.task-count { font-size: 26rpx; font-weight: bold; color: #C41E3A; }
.task-progress { padding: 16rpx 24rpx 0; }
.task-progress-track { height: 12rpx; background: #F2EFEA; border-radius: 6rpx; overflow: hidden; }
.task-progress-fill { height: 100%; background: linear-gradient(90deg, #C41E3A, #E74C3C); border-radius: 6rpx; transition: width 0.5s; }
.task-progress-info { display: flex; justify-content: space-between; margin-top: 4rpx; font-size: 18rpx; color: #999; }
.task-done-time { color: #C41E3A; }
.task-empty { text-align: center; padding: 48rpx 0; font-size: 24rpx; color: #bbb; }
.task-list { }
.task-item { display: flex; align-items: center; gap: 16rpx; padding: 24rpx; border-top: 1rpx solid #F5F0E8; }
.task-check { width: 40rpx; height: 40rpx; border-radius: 50%; border: 2rpx solid #ddd; display: flex; align-items: center; justify-content: center; font-size: 24rpx; color: #fff; flex-shrink: 0; }
.task-checked { background: #52C41A; border-color: #52C41A; }
.task-info { flex: 1; }
.task-name { font-size: 24rpx; font-weight: 500; color: #2C2C2C; display: block; }
.task-name-done { text-decoration: line-through; color: #bbb; }
.task-lesson { font-size: 20rpx; color: #999; margin-top: 4rpx; display: block; }
.task-duration { font-size: 20rpx; color: #bbb; }

.course-card { background: #fff; border-radius: 24rpx; margin-bottom: 20rpx; overflow: hidden; box-shadow: 0 4rpx 16rpx rgba(0,0,0,0.06); }
.course-card-header { padding: 24rpx; display: flex; justify-content: space-between; align-items: center; border-bottom: 1rpx solid #F2EFEA; }
.course-card-title-row { display: flex; align-items: center; gap: 12rpx; }
.course-card-icon { font-size: 32rpx; }
.course-card-title { font-size: 28rpx; font-weight: 600; color: #2C2C2C; }
.course-add { width: 48rpx; height: 48rpx; border-radius: 50%; background: rgba(196,30,58,0.08); display: flex; align-items: center; justify-content: center; font-size: 32rpx; color: #C41E3A; }
.course-empty { padding: 64rpx 0; text-align: center; }
.course-empty-icon { font-size: 64rpx; display: block; margin-bottom: 16rpx; }
.course-empty-text { font-size: 24rpx; color: #bbb; }
.course-list { }
.course-item { display: flex; align-items: center; gap: 16rpx; padding: 24rpx; border-bottom: 1rpx solid #F5F0E8; }
.course-dragging { opacity: 0.4; background: #FAF8F5; }
.course-drag { font-size: 28rpx; color: #ddd; cursor: grab; flex-shrink: 0; }
.course-cover { width: 72rpx; height: 72rpx; border-radius: 12rpx; background: #F2EFEA; flex-shrink: 0; }
.course-info { flex: 1; }
.course-name { font-size: 24rpx; font-weight: 500; color: #2C2C2C; display: block; margin-bottom: 8rpx; }
.course-progress { display: flex; align-items: center; gap: 8rpx; margin-bottom: 8rpx; }
.course-progress-track { flex: 1; height: 10rpx; background: #F2EFEA; border-radius: 5rpx; overflow: hidden; }
.course-progress-fill { height: 100%; background: linear-gradient(90deg, #C41E3A, #E74C3C); border-radius: 5rpx; }
.course-progress-pct { font-size: 18rpx; color: #bbb; }
.course-days { display: flex; gap: 4rpx; }
.course-day { width: 28rpx; height: 28rpx; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 16rpx; font-weight: 500; background: #F2EFEA; color: #ccc; }
.course-day-active { background: #C41E3A; color: #fff; }
.course-remove { font-size: 28rpx; flex-shrink: 0; }

.bottom-tip { text-align: center; padding: 16rpx 0 40rpx; font-size: 22rpx; color: #bbb; }
.tip-link { color: #C41E3A; font-weight: 500; }

.bottom-spacer { height: 40rpx; }

.dialog-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 100; display: flex; align-items: flex-end; }
.dialog-content { background: #fff; border-radius: 32rpx 32rpx 0 0; padding: 32rpx; width: 100%; }
.dialog-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32rpx; }
.dialog-title { font-size: 32rpx; font-weight: bold; color: #2C2C2C; }
.dialog-close { font-size: 36rpx; color: #999; padding: 8rpx; }
.editor-section { margin-bottom: 28rpx; }
.editor-label { font-size: 24rpx; color: #666; display: block; margin-bottom: 16rpx; }
.days-selector { display: flex; gap: 16rpx; }
.day-btn { flex: 1; height: 72rpx; border-radius: 16rpx; display: flex; align-items: center; justify-content: center; font-size: 26rpx; font-weight: bold; background: #F2EFEA; color: #666; }
.day-active { background: #C41E3A; color: #fff; box-shadow: 0 8rpx 24rpx rgba(196,30,58,0.3); }
.minutes-selector { display: flex; flex-wrap: wrap; gap: 16rpx; }
.minute-btn { padding: 16rpx 32rpx; border-radius: 16rpx; font-size: 24rpx; font-weight: bold; background: #F2EFEA; color: #666; }
.minute-active { background: #C41E3A; color: #fff; box-shadow: 0 8rpx 24rpx rgba(196,30,58,0.3); }
.save-goal-btn { width: 100%; height: 88rpx; background: linear-gradient(135deg, #C41E3A, #E74C3C); color: #fff; border-radius: 20rpx; font-size: 28rpx; font-weight: bold; display: flex; align-items: center; justify-content: center; box-shadow: 0 8rpx 32rpx rgba(196,30,58,0.35); }
</style>
