// apps/mobile/.backup_vue3_converted/pages/earnings/records/index.vue
<template>
  <view class="min-h-screen bg-background">
    <!-- 顶部导航 -->
    <view class="sticky top-0 z-10 bg-background border-b border-border">
      <view class="flex items-center justify-between px-4 py-3">
        <view @click="goBack" class="p-1">
          <text class="text-foreground text-xl">←</text>
        </view>
        <text class="text-lg font-semibold text-foreground">收益记录</text>
        <view class="w-8" />
      </view>
    </view>

    <!-- 加载骨架屏 -->
    <view v-if="loading" class="px-4 pt-4 space-y-4">
      <view class="grid grid-cols-2 gap-3">
        <view v-for="i in 4" :key="i" class="p-4 rounded-xl bg-muted animate-pulse" />
      </view>
      <view class="flex gap-3">
        <view class="flex-1 h-10 rounded-xl bg-muted animate-pulse" />
        <view class="flex-1 h-10 rounded-xl bg-muted animate-pulse" />
      </view>
      <view class="flex gap-2">
        <view v-for="i in 4" :key="i" class="h-7 w-16 rounded-full bg-muted animate-pulse" />
      </view>
      <view v-for="i in 3" :key="i" class="p-4 rounded-xl bg-muted animate-pulse" />
    </view>

    <view v-else class="pb-24">
      <!-- 统计卡片 -->
      <view class="mx-4 mt-4 grid grid-cols-2 gap-3">
        <view class="p-4 text-center rounded-xl border col-span-2" style="background:rgba(196,30,58,0.05);border-color:rgba(196,30,58,0.2)">
          <text class="text-xs text-muted-foreground block mb-1">累计总收益</text>
          <text class="text-3xl font-bold text-primary block">¥{{ (totalEarnings).toFixed(2) }}</text>
        </view>
        <view class="p-4 text-center rounded-xl border border-border bg-white">
          <text class="text-xs text-muted-foreground block mb-1">本月收益</text>
          <text class="text-xl font-bold text-foreground block">¥{{ (monthEarnings).toFixed(2) }}</text>
          <text class="text-[10px] text-green-500 mt-0.5 block">↑ 较上月增长{{ ((monthEarnings - lastMonthEarnings) / lastMonthEarnings * 100).toFixed(1) }}%</text>
        </view>
        <view class="p-4 text-center rounded-xl border border-border bg-white">
          <text class="text-xs text-muted-foreground block mb-1">上月收益</text>
          <text class="text-xl font-bold text-foreground block">¥{{ (lastMonthEarnings).toFixed(2) }}</text>
        </view>
        <view class="p-4 text-center rounded-xl border border-border bg-white">
          <text class="text-xs text-muted-foreground block mb-1">可提现</text>
          <text class="text-xl font-bold block" style="color: #16A34A">¥{{ (availableBalance).toFixed(2) }}</text>
        </view>
        <view class="p-4 text-center rounded-xl border border-border bg-white">
          <text class="text-xs text-muted-foreground block mb-1">冻结中</text>
          <text class="text-xl font-bold text-muted-foreground block">¥{{ (frozenBalance).toFixed(2) }}</text>
        </view>
      </view>

      <!-- 快捷操作 -->
      <view class="mx-4 mt-4 flex gap-3">
        <view @click="goWithdraw" class="flex-1 py-2.5 rounded-xl bg-primary text-white text-sm font-medium text-center">
          申请提现
        </view>
        <view @click="goBreakdown" class="flex-1 py-2.5 rounded-xl border border-border text-foreground text-sm font-medium text-center">
          收益明细
        </view>
      </view>

      <!-- 月度趋势简图 -->
      <view class="mx-4 mt-4 bg-white rounded-xl p-4 border border-border">
        <view class="flex items-center justify-between mb-3">
          <text class="text-xs font-semibold text-foreground">📊 月度趋势</text>
          <text class="text-[10px] text-muted-foreground">近6个月</text>
        </view>
        <view class="flex items-end justify-between h-20 gap-1">
          <view v-for="(item, idx) in monthlyTrend" :key="idx" class="flex flex-col items-center flex-1">
            <view
              class="w-full rounded-t"
              :style="{ height: (item.amount / maxTrend * 100) + '%' }"
              :class="idx === monthlyTrend.length - 1 ? 'bg-primary' : 'bg-primary/30'"
            />
            <text class="text-[8px] text-muted-foreground mt-1">{{ item.month }}</text>
          </view>
        </view>
      </view>

      <!-- 分类筛选 -->
      <view class="mx-4 mt-4">
        <view class="flex gap-2 overflow-x-auto whitespace-nowrap scrollbar-hide">
          <view
            v-for="s in statusFilters"
            :key="s.value"
            @click="activeStatus = s.value"
            class="px-3 py-1.5 rounded-full text-xs font-medium transition-colors"
            :class="activeStatus === s.value ? 'bg-primary text-white' : 'bg-muted text-foreground'"
          >
            <text>{{ s.label }}</text>
            <text v-if="s.count !== undefined" class="ml-1 opacity-70">({{ s.count }})</text>
          </view>
        </view>
      </view>

      <!-- 收益记录列表 -->
      <view class="mx-4 mt-4">
        <view v-if="filteredItems.length > 0" class="space-y-2">
          <view v-for="item in filteredItems" :key="item.id" class="p-4 rounded-xl border border-border bg-white">
            <view class="flex items-start justify-between gap-3">
              <view class="flex items-start gap-3 flex-1 min-w-0">
                <view class="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0"
                  :class="getTypeColor(item.type)">
                  <text>{{ getTypeIcon(item.type) }}</text>
                </view>
                <view class="flex-1 min-w-0">
                  <text class="text-sm font-medium text-foreground line-clamp-1 block">{{ item.title }}</text>
                  <text class="text-xs text-muted-foreground mt-0.5 line-clamp-1 block">{{ item.description }}</text>
                  <view class="flex items-center gap-2 mt-2">
                    <text class="px-1.5 py-0.5 rounded text-[10px] bg-secondary text-foreground">{{ getEarningsTypeName(item.type) }}</text>
                    <text class="px-1.5 py-0.5 rounded text-[10px]" :class="statusColors[item.status]">{{ getEarningsStatusName(item.status) }}</text>
                  </view>
                  <text class="text-xs text-muted-foreground mt-1 block">{{ item.createdAt }}</text>
                </view>
              </view>
              <text class="text-sm font-bold flex-shrink-0" style="color: #16A34A">+¥{{ (item.amount).toFixed(2) }}</text>
            </view>
          </view>
        </view>

        <!-- 空状态 -->
        <view v-else class="p-10 rounded-xl border border-border bg-white text-center">
          <text class="text-4xl block mb-3"></text>
          <text class="text-muted-foreground text-sm block">暂无收益记录</text>
          <text class="text-xs text-muted-foreground mt-1 block">发布内容或推荐好友可获得收益</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

interface EarningsItem {
  id: string
  title: string
  description: string
  type: 'course_commission' | 'product_commission' | 'member_commission' | 'invite_reward' | 'platform_reward'
  status: 'settled' | 'pending' | 'frozen'
  amount: number
  createdAt: string
}

interface FilterOption {
  label: string
  value: string
  count?: number
}

interface TrendItem {
  month: string
  amount: number
}

// 加载状态
const loading = ref(true)
setTimeout(() => { loading.value = false }, 600)

// 汇总数据
const totalEarnings = ref(18450.50)
const monthEarnings = ref(5840)
const lastMonthEarnings = ref(4200)
const availableBalance = ref(12580.30)
const frozenBalance = ref(2500)

// 月度趋势
const monthlyTrend: TrendItem[] = [
  { month: '1月', amount: 3200 },
  { month: '2月', amount: 2800 },
  { month: '3月', amount: 4100 },
  { month: '4月', amount: 3800 },
  { month: '5月', amount: 5200 },
  { month: '6月', amount: 5840 },
]
const maxTrend = computed(() => Math.max(...monthlyTrend.map(t => t.amount)) * 1.2)

// 收益数据
const items = ref<EarningsItem[]>([
  { id: '1', title: '八字入门课分成', description: '来自学员张三的课程购买', type: 'course_commission', status: 'settled', amount: 5000, createdAt: '2024-01-15' },
  { id: '2', title: '1月会员费', description: '3位新会员入圈', type: 'member_commission', status: 'pending', amount: 3800, createdAt: '2024-01-10' },
  { id: '3', title: '邀请奖励', description: '推荐李四注册', type: 'invite_reward', status: 'settled', amount: 200, createdAt: '2024-01-08' },
  { id: '4', title: '课程销售分成', description: '紫微斗数课程销售佣金', type: 'course_commission', status: 'settled', amount: 2800, createdAt: '2024-01-05' },
  { id: '5', title: '商品佣金', description: '风水罗盘销售分成', type: 'product_commission', status: 'frozen', amount: 680, createdAt: '2024-01-03' },
  { id: '6', title: '平台奖励', description: '1月优质内容激励', type: 'platform_reward', status: 'settled', amount: 500, createdAt: '2024-01-01' },
])

// 状态筛选
const statusFilters: FilterOption[] = [
  { label: '全部', value: 'all', count: items.value.length },
  { label: '已结算', value: 'settled', count: items.value.filter(i => i.status === 'settled').length },
  { label: '待结算', value: 'pending', count: items.value.filter(i => i.status === 'pending').length },
  { label: '冻结中', value: 'frozen', count: items.value.filter(i => i.status === 'frozen').length },
]

const statusColors: Record<string, string> = {
  settled: 'bg-green-100 text-green-800',
  pending: 'bg-yellow-100 text-yellow-800',
  frozen: 'bg-gray-100 text-gray-800',
}

const activeStatus = ref('all')

const filteredItems = computed(() => {
  if (activeStatus.value === 'all') return items.value
  return items.value.filter(i => i.status === activeStatus.value)
})

function getTypeColor(type: string): string {
  const colors: Record<string, string> = {
    course_commission: 'bg-blue-50',
    product_commission: 'bg-purple-50',
    member_commission: 'bg-amber-50',
    invite_reward: 'bg-green-50',
    platform_reward: 'bg-rose-50',
  }
  return colors[type] || 'bg-primary/10'
}

function getTypeIcon(type: string): string {
  const icons: Record<string, string> = {
    course_commission: '',
    product_commission: '',
    member_commission: '',
    invite_reward: '🎁',
    platform_reward: '',
  }
  return icons[type] || ''
}

function getEarningsTypeName(type: string): string {
  const names: Record<string, string> = {
    course_commission: '课程佣金',
    product_commission: '商品佣金',
    member_commission: '会员佣金',
    invite_reward: '邀请奖励',
    platform_reward: '平台奖励',
  }
  return names[type] || type
}

function getEarningsStatusName(status: string): string {
  const names: Record<string, string> = {
    settled: '已结算',
    pending: '待结算',
    frozen: '冻结中',
  }
  return names[status] || status
}

function goBack() { uni.navigateBack() }
function goWithdraw() { uni.navigateTo({ url: '/pages/earnings/withdraw/index' }) }
function goBreakdown() { uni.navigateTo({ url: '/pages/earnings/breakdown/index' }) }
</script>

<style scoped>
/* 样式由 Tailwind 处理 */
.scrollbar-hide::-webkit-scrollbar { display: none; }
</style>

// proto-ref-app/earnings/records/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, TrendingUp } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { DataState } from '@/components/data-state'
import { getEarningsOverview, getEarningsList, getEarningsTypeName, getEarningsStatusName } from '@/lib/api/earnings'
import type { EarningsOverview, EarningsItem } from '@/lib/types/earnings'

const STATUS_COLORS = {
  settled: 'bg-green-100 text-green-800',
  pending: 'bg-yellow-100 text-yellow-800',
  frozen: 'bg-gray-100 text-gray-800',
}

export default function EarningsRecordsPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [overview, setOverview] = useState<EarningsOverview | null>(null)
  const [items, setItems] = useState<EarningsItem[]>([])
  const [activeStatus, setActiveStatus] = useState<'all' | 'settled' | 'pending' | 'frozen'>('all')

  useEffect(() => {
    loadData()
  }, [activeStatus])

  const loadData = async () => {
    setLoading(true)
    setError(null)
    try {
      const [overviewRes, listRes] = await Promise.all([
        getEarningsOverview(),
        getEarningsList(1, 20, {
          status: activeStatus === 'all' ? undefined : activeStatus,
        }),
      ])
      if (overviewRes.code === 200) setOverview(overviewRes.data)
      else setError('加载数据失败')
      if (listRes.code === 200) setItems(listRes.data.list)
    } catch {
      setError('加载失败，请重试')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <button onClick={() => router.back()} className="p-1">
            <ArrowLeft className="w-6 h-6 text-foreground" />
          </button>
          <h1 className="text-lg font-semibold text-foreground">收益记录</h1>
          <div className="w-8" />
        </div>
      </div>

      <DataState
        loading={loading}
        error={error}
        empty={!overview}
        onRetry={loadData}
        skeleton={
          <div className="p-4 space-y-4">
            <div className="grid grid-cols-2 gap-3">
              {[1, 2, 3, 4].map(i => (
                <div key={i} className="h-24 bg-gray-200 rounded-xl animate-pulse" />
              ))}
            </div>
            <div className="space-y-3">
              {[1, 2, 3].map(i => (
                <div key={i} className="h-20 bg-gray-200 rounded-xl animate-pulse" />
              ))}
            </div>
          </div>
        }
      >
        {overview && (
          <div className="pb-20">
            {/* 统计卡片 */}
            <div className="mx-4 mt-4 grid grid-cols-2 gap-3">
              <Card className="p-4 text-center col-span-2 bg-primary/5 border border-primary/20">
                <div className="text-xs text-muted-foreground mb-1">累计总收益</div>
                <div className="text-3xl font-bold text-primary">
                  ¥{overview.totalEarnings.toLocaleString('zh-CN', { minimumFractionDigits: 2 })}
                </div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">本月收益</div>
                <div className="text-xl font-bold text-foreground">
                  ¥{overview.monthEarnings.toFixed(2)}
                </div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">上月收益</div>
                <div className="text-xl font-bold text-foreground">
                  ¥{overview.lastMonthEarnings.toFixed(2)}
                </div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">可提现</div>
                <div className="text-xl font-bold text-green-600">
                  ¥{overview.availableBalance.toFixed(2)}
                </div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">冻结中</div>
                <div className="text-xl font-bold text-muted-foreground">
                  ¥{overview.frozenBalance.toFixed(2)}
                </div>
              </Card>
            </div>

            {/* 快捷操作 */}
            <div className="mx-4 mt-4 flex gap-3">
              <button
                onClick={() => router.push('/earnings/withdraw')}
                className="flex-1 py-2.5 rounded-xl bg-primary text-white text-sm font-medium"
              >
                申请提现
              </button>
              <button
                onClick={() => router.push('/earnings/breakdown')}
                className="flex-1 py-2.5 rounded-xl border border-border text-foreground text-sm font-medium"
              >
                收益明细
              </button>
            </div>

            {/* 状态筛选 */}
            <div className="mx-4 mt-5">
              <div className="flex gap-2">
                {(['all', 'settled', 'pending', 'frozen'] as const).map(s => (
                  <button
                    key={s}
                    onClick={() => setActiveStatus(s)}
                    className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                      activeStatus === s
                        ? 'bg-primary text-white'
                        : 'bg-muted text-foreground hover:bg-muted/80'
                    }`}
                  >
                    {s === 'all' ? '全部' : s === 'settled' ? '已结算' : s === 'pending' ? '待结算' : '冻结中'}
                  </button>
                ))}
              </div>
            </div>

            {/* 收益记录列表 */}
            <div className="mx-4 mt-4">
              {items.length > 0 ? (
                <div className="space-y-2">
                  {items.map(item => (
                    <Card key={item.id} className="p-4">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex items-start gap-3 flex-1 min-w-0">
                          <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
                            <TrendingUp className="w-5 h-5 text-primary" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="text-sm font-medium text-foreground line-clamp-1">
                              {item.title}
                            </div>
                            <div className="text-xs text-muted-foreground mt-0.5 line-clamp-1">
                              {item.description}
                            </div>
                            <div className="flex items-center gap-2 mt-2">
                              <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                                {getEarningsTypeName(item.type)}
                              </Badge>
                              <Badge
                                variant="secondary"
                                className={`text-[10px] px-1.5 py-0 ${STATUS_COLORS[item.status]}`}
                              >
                                {getEarningsStatusName(item.status)}
                              </Badge>
                            </div>
                            <div className="text-xs text-muted-foreground mt-1">
                              {item.createdAt}
                            </div>
                          </div>
                        </div>
                        <div className="text-sm font-bold text-green-600 flex-shrink-0">
                          +¥{item.amount.toFixed(2)}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              ) : (
                <Card className="p-10 text-center">
                  <div className="text-muted-foreground text-sm">暂无收益记录</div>
                </Card>
              )}
            </div>
          </div>
        )}
      </DataState>
    </div>
  )
}
