// apps/mobile/src/pkg-live/schedule/index.vue
<template>
  <view class="schedule-page">
    <!-- 顶部导航 -->
    <view class="nav-bar">
      <view class="nav-left">
        <view
          class="nav-back"
          @tap="goBack"
        >
          <app-icon
            name="chevron-left"
            :size="48"
            color="#1a1a1a"
          />
        </view>
        <text class="nav-title">
          直播排期管理
        </text>
      </view>
      <view class="nav-right">
        <view
          class="nav-btn nav-btn-outline"
          @tap="showImportDialog = true"
        >
          <app-icon
            name="upload"
            :size="32"
            color="#1a1a1a"
          />
          <text class="nav-btn-text">
            导入
          </text>
        </view>
        <view
          class="nav-btn nav-btn-primary"
          @tap="goCreate()"
        >
          <app-icon
            name="plus"
            :size="32"
            color="#fff"
          />
          <text class="nav-btn-text nav-btn-text-light">
            新建场次
          </text>
        </view>
      </view>
    </view>

    <!-- 视图切换 & 搜索 -->
    <view class="toolbar">
      <view class="toolbar-row">
        <view class="view-switch">
          <view
            class="view-tab"
            :class="{ 'view-tab-active': viewMode === 'calendar' }"
            @tap="viewMode = 'calendar'"
          >
            <app-icon
              name="calendar-days"
              :size="32"
              :color="viewMode === 'calendar' ? '#1a1a1a' : '#999'"
            />
            <text
              class="view-tab-text"
              :class="{ 'view-tab-text-active': viewMode === 'calendar' }"
            >
              日历
            </text>
          </view>
          <view
            class="view-tab"
            :class="{ 'view-tab-active': viewMode === 'list' }"
            @tap="viewMode = 'list'"
          >
            <app-icon
              name="list"
              :size="32"
              :color="viewMode === 'list' ? '#1a1a1a' : '#999'"
            />
            <text
              class="view-tab-text"
              :class="{ 'view-tab-text-active': viewMode === 'list' }"
            >
              列表
            </text>
          </view>
        </view>
        <view class="search-box">
          <app-icon
            name="search"
            :size="32"
            color="#999"
            class="search-icon"
          />
          <input
            v-model="searchQuery"
            class="search-input"
            placeholder="搜索直播..."
            placeholder-class="search-ph"
          >
        </view>
      </view>
      <!-- 状态筛选 -->
      <scroll-view
        scroll-x
        class="filter-scroll"
        :show-scrollbar="false"
      >
        <view class="filter-row">
          <view
            v-for="item in statusFilters"
            :key="item.key"
            class="filter-chip"
            :class="{ 'filter-chip-active': filterStatus === item.key }"
            @tap="filterStatus = item.key"
          >
            {{ item.label }}
          </view>
        </view>
      </scroll-view>
    </view>

    <!-- 日历视图 -->
    <view
      v-if="viewMode === 'calendar'"
      class="calendar-view"
    >
      <view class="month-switch">
        <view
          class="month-arrow"
          @tap="changeMonth(-1)"
        >
          <app-icon
            name="chevron-left"
            :size="40"
            color="#1a1a1a"
          />
        </view>
        <text class="month-title">
          {{ year }}年{{ monthNames[month] }}
        </text>
        <view
          class="month-arrow"
          @tap="changeMonth(1)"
        >
          <app-icon
            name="chevron-right"
            :size="40"
            color="#1a1a1a"
          />
        </view>
      </view>

      <view class="week-head">
        <view
          v-for="d in weekDays"
          :key="d"
          class="week-cell"
        >
          {{ d }}
        </view>
      </view>

      <view class="cal-grid">
        <view
          v-for="(day, index) in calendarDays"
          :key="index"
          class="cal-cell"
          :class="{
            'cal-cell-selected': day && dateStrOf(day) === selectedDate,
            'cal-cell-today': day && dateStrOf(day) === todayStr && dateStrOf(day) !== selectedDate,
          }"
          @tap="day && toggleDate(day)"
        >
          <template v-if="day">
            <text
              class="cal-day"
              :class="{ 'cal-day-today': dateStrOf(day) === todayStr }"
            >
              {{ day }}
            </text>
            <view
              v-if="getSchedulesForDate(day).length"
              class="cal-dots"
            >
              <view
                v-for="(s, i) in getSchedulesForDate(day).slice(0, 3)"
                :key="i"
                class="cal-dot"
                :style="{ background: statusConfig[s.status].dot }"
              />
              <text
                v-if="getSchedulesForDate(day).length > 3"
                class="cal-dot-more"
              >
                +{{ getSchedulesForDate(day).length - 3 }}
              </text>
            </view>
          </template>
        </view>
      </view>

      <!-- 选中日期场次 -->
      <view
        v-if="selectedDate"
        class="selected-section"
      >
        <text class="selected-title">
          {{ formatDate(selectedDate) }} 的直播 ({{ filteredSchedules.length }}场)
        </text>
        <view
          v-if="filteredSchedules.length === 0"
          class="empty-day"
        >
          <app-icon
            name="calendar"
            :size="64"
            color="#ccc"
          />
          <text class="empty-day-text">
            当日暂无直播排期
          </text>
          <view
            class="empty-btn"
            @tap="goCreate()"
          >
            <app-icon
              name="plus"
              :size="32"
              color="#1a1a1a"
            />
            <text class="empty-btn-text">
              新建场次
            </text>
          </view>
        </view>
        <view
          v-else
          class="card-list"
        >
          <schedule-card
            v-for="s in filteredSchedules"
            :key="s.id"
            :schedule="s"
            @edit="goCreate(s.id)"
            @copy="onCopy(s)"
            @del="onDelete(s)"
          />
        </view>
      </view>
    </view>

    <!-- 列表视图 -->
    <view
      v-if="viewMode === 'list'"
      class="list-view"
    >
      <view class="stat-grid">
        <view class="stat-card">
          <text class="stat-num stat-num-blue">
            {{ countByStatus('scheduled') }}
          </text>
          <text class="stat-label">
            待开播
          </text>
        </view>
        <view class="stat-card">
          <text class="stat-num stat-num-red">
            {{ countByStatus('live') }}
          </text>
          <text class="stat-label">
            直播中
          </text>
        </view>
        <view class="stat-card">
          <text class="stat-num stat-num-gray">
            {{ countByStatus('completed') }}
          </text>
          <text class="stat-label">
            已结束
          </text>
        </view>
      </view>

      <view
        v-if="filteredSchedules.length === 0"
        class="empty-list"
      >
        <app-icon
          name="calendar-days"
          :size="96"
          color="#e0e0e0"
        />
        <text class="empty-list-text">
          暂无直播排期
        </text>
        <view
          class="empty-list-btn"
          @tap="goCreate()"
        >
          <app-icon
            name="plus"
            :size="32"
            color="#fff"
          />
          <text class="empty-list-btn-text">
            创建第一场直播
          </text>
        </view>
      </view>
      <view
        v-else
        class="card-list"
      >
        <schedule-card
          v-for="s in filteredSchedules"
          :key="s.id"
          :schedule="s"
          show-date
          @edit="goCreate(s.id)"
          @copy="onCopy(s)"
          @del="onDelete(s)"
        />
      </view>
    </view>

    <!-- 导入对话框 -->
    <view
      v-if="showImportDialog"
      class="dialog-mask"
      @tap="showImportDialog = false"
    >
      <view
        class="dialog"
        @tap.stop
      >
        <text class="dialog-title">
          批量导入场次
        </text>
        <text class="dialog-desc">
          通过Excel文件批量导入直播排期
        </text>
        <view class="tpl-row">
          <view class="tpl-left">
            <app-icon
              name="file-spreadsheet"
              :size="40"
              color="#16a34a"
            />
            <text class="tpl-name">
              排期导入模板.xlsx
            </text>
          </view>
          <view class="tpl-dl">
            <app-icon
              name="download"
              :size="32"
              color="#1a1a1a"
            />
            <text class="tpl-dl-text">
              下载模板
            </text>
          </view>
        </view>
        <view class="upload-zone">
          <app-icon
            name="upload"
            :size="80"
            color="#999"
          />
          <text class="upload-main">
            点击或拖拽文件到此处
          </text>
          <text class="upload-sub">
            支持 .xlsx, .xls 格式，单次最多100条
          </text>
        </view>
        <view class="dialog-footer">
          <view
            class="dlg-btn dlg-btn-outline"
            @tap="showImportDialog = false"
          >
            取消
          </view>
          <view class="dlg-btn dlg-btn-primary">
            开始导入
          </view>
        </view>
      </view>
    </view>

    <!-- 删除确认对话框 -->
    <view
      v-if="showDeleteDialog"
      class="dialog-mask"
      @tap="showDeleteDialog = false"
    >
      <view
        class="dialog"
        @tap.stop
      >
        <text class="dialog-title">
          确认删除
        </text>
        <text class="dialog-desc">
          确定要删除直播「{{ selectedSchedule?.title }}」吗？此操作不可恢复。
        </text>
        <view class="dialog-footer">
          <view
            class="dlg-btn dlg-btn-outline"
            @tap="showDeleteDialog = false"
          >
            取消
          </view>
          <view
            class="dlg-btn dlg-btn-danger"
            @tap="confirmDelete"
          >
            确认删除
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { scheduleList, scheduleStatusConfig, type ScheduleItem } from '@/lib/live-data'
import ScheduleCard from './schedule-card.vue'

const viewMode = ref<'calendar' | 'list'>('calendar')
const currentYear = ref(2026)
const currentMonth = ref(4) // 0-based，2026年5月
const selectedDate = ref<string | null>(null)
const showImportDialog = ref(false)
const showDeleteDialog = ref(false)
const selectedSchedule = ref<ScheduleItem | null>(null)
const filterStatus = ref('all')
const searchQuery = ref('')

const todayStr = '2026-05-10'
const statusConfig = scheduleStatusConfig
const monthNames = ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
const weekDays = ['日', '一', '二', '三', '四', '五', '六']
const statusFilters = [
  { key: 'all', label: '全部' },
  { key: 'scheduled', label: '待开播' },
  { key: 'live', label: '直播中' },
  { key: 'completed', label: '已结束' },
]

const year = computed(() => currentYear.value)
const month = computed(() => currentMonth.value)

const calendarDays = computed(() => {
  const firstDay = new Date(year.value, month.value, 1)
  const lastDay = new Date(year.value, month.value + 1, 0)
  const startDay = firstDay.getDay()
  const totalDays = lastDay.getDate()
  const days: (number | null)[] = []
  for (let i = 0; i < startDay; i++) days.push(null)
  for (let i = 1; i <= totalDays; i++) days.push(i)
  return days
})

function dateStrOf(day: number) {
  return `${year.value}-${String(month.value + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
}
function getSchedulesForDate(day: number) {
  const ds = dateStrOf(day)
  return scheduleList.filter((s) => s.date === ds)
}
function toggleDate(day: number) {
  const ds = dateStrOf(day)
  selectedDate.value = selectedDate.value === ds ? null : ds
}
function changeMonth(delta: number) {
  const d = new Date(year.value, month.value + delta, 1)
  currentYear.value = d.getFullYear()
  currentMonth.value = d.getMonth()
  selectedDate.value = null
}
function formatDate(dateStr: string) {
  const d = new Date(dateStr)
  return `${d.getMonth() + 1}月${d.getDate()}日`
}
function countByStatus(status: string) {
  return scheduleList.filter((s) => s.status === status).length
}

const filteredSchedules = computed(() => {
  return scheduleList
    .filter((s) => {
      if (filterStatus.value !== 'all' && s.status !== filterStatus.value) return false
      if (searchQuery.value && !s.title.toLowerCase().includes(searchQuery.value.toLowerCase())) return false
      if (selectedDate.value && s.date !== selectedDate.value) return false
      return true
    })
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
})

function goBack() {
  uni.navigateBack()
}
function goCreate(id?: number) {
  const url = id ? `/pkg-live/create/index?id=${id}` : '/pkg-live/create/index'
  uni.navigateTo({ url })
}
function onCopy(s: ScheduleItem) {
  console.log('[v0] 复制场次', s.id)
}
function onDelete(s: ScheduleItem) {
  selectedSchedule.value = s
  showDeleteDialog.value = true
}
function confirmDelete() {
  console.log('[v0] 删除场次', selectedSchedule.value?.id)
  showDeleteDialog.value = false
}
</script>

<style scoped>
.schedule-page {
  min-height: 100vh;
  background: #faf8f5;
  padding-bottom: 80rpx;
}

/* 顶部导航 */
.nav-bar {
  position: sticky;
  top: 0;
  z-index: 40;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 88rpx;
  padding: 0 24rpx;
  background: rgba(250, 248, 245, 0.95);
  border-bottom: 1px solid #ece8e1;
}
.nav-left {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.nav-back {
  display: flex;
  align-items: center;
}
.nav-title {
  font-size: 34rpx;
  font-weight: 600;
  color: #1a1a1a;
}
.nav-right {
  display: flex;
  align-items: center;
  gap: 12rpx;
}
.nav-btn {
  display: flex;
  align-items: center;
  gap: 8rpx;
  height: 56rpx;
  padding: 0 20rpx;
  border-radius: 12rpx;
}
.nav-btn-outline {
  border: 1px solid #d8d2c8;
  background: transparent;
}
.nav-btn-primary {
  background: #C41E3A;
}
.nav-btn-text {
  font-size: 26rpx;
  color: #1a1a1a;
}
.nav-btn-text-light {
  color: #fff;
}

/* 工具栏 */
.toolbar {
  padding: 24rpx;
  border-bottom: 1px solid #ece8e1;
}
.toolbar-row {
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.view-switch {
  display: flex;
  align-items: center;
  gap: 8rpx;
  padding: 8rpx;
  background: #f0ece5;
  border-radius: 16rpx;
}
.view-tab {
  display: flex;
  align-items: center;
  gap: 12rpx;
  padding: 12rpx 24rpx;
  border-radius: 12rpx;
}
.view-tab-active {
  background: #fff;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
}
.view-tab-text {
  font-size: 26rpx;
  color: #999;
}
.view-tab-text-active {
  color: #1a1a1a;
}
.search-box {
  flex: 1;
  position: relative;
  display: flex;
  align-items: center;
}
.search-icon {
  position: absolute;
  left: 20rpx;
  z-index: 1;
}
.search-input {
  flex: 1;
  height: 72rpx;
  padding: 0 20rpx 0 64rpx;
  background: #fff;
  border: 1px solid #e5e0d8;
  border-radius: 12rpx;
  font-size: 26rpx;
  color: #1a1a1a;
}
.search-ph {
  color: #b3b3b3;
}
.filter-scroll {
  margin-top: 24rpx;
  white-space: nowrap;
  width: 100%;
}
.filter-row {
  display: inline-flex;
  align-items: center;
  gap: 16rpx;
}
.filter-chip {
  flex-shrink: 0;
  padding: 12rpx 24rpx;
  border-radius: 999rpx;
  font-size: 26rpx;
  color: #999;
  background: #f0ece5;
}
.filter-chip-active {
  background: #C41E3A;
  color: #fff;
}

/* 日历视图 */
.calendar-view {
  padding: 32rpx 24rpx;
}
.month-switch {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 32rpx;
}
.month-arrow {
  width: 64rpx;
  height: 64rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.month-title {
  font-size: 34rpx;
  font-weight: 600;
  color: #1a1a1a;
}
.week-head {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 8rpx;
  margin-bottom: 16rpx;
}
.week-cell {
  text-align: center;
  font-size: 22rpx;
  color: #999;
  padding: 16rpx 0;
}
.cal-grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 8rpx;
}
.cal-cell {
  aspect-ratio: 1;
  border-radius: 16rpx;
  padding: 8rpx;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: flex-start;
  position: relative;
}
.cal-cell-selected {
  background: rgba(196, 30, 58, 0.1);
  border: 2px solid #C41E3A;
}
.cal-cell-today {
  background: #f0ece5;
}
.cal-day {
  font-size: 26rpx;
  font-weight: 500;
  color: #1a1a1a;
}
.cal-day-today {
  color: #C41E3A;
}
.cal-dots {
  display: flex;
  align-items: center;
  gap: 4rpx;
  margin-top: 4rpx;
}
.cal-dot {
  width: 12rpx;
  height: 12rpx;
  border-radius: 50%;
}
.cal-dot-more {
  font-size: 16rpx;
  color: #999;
}

/* 选中日期场次 */
.selected-section {
  margin-top: 32rpx;
  padding-top: 32rpx;
  border-top: 1px solid #ece8e1;
}
.selected-title {
  font-size: 26rpx;
  font-weight: 500;
  color: #1a1a1a;
  margin-bottom: 24rpx;
  display: block;
}
.empty-day {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 64rpx 0;
}
.empty-day-text {
  font-size: 26rpx;
  color: #999;
  margin-top: 16rpx;
}
.empty-btn {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-top: 24rpx;
  padding: 12rpx 28rpx;
  border: 1px solid #d8d2c8;
  border-radius: 12rpx;
}
.empty-btn-text {
  font-size: 26rpx;
  color: #1a1a1a;
}
.card-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}

/* 列表视图 */
.list-view {
  padding: 32rpx 24rpx;
}
.stat-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24rpx;
  margin-bottom: 32rpx;
}
.stat-card {
  background: #fff;
  border: 1px solid #ece8e1;
  border-radius: 16rpx;
  padding: 24rpx;
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
}
.stat-num {
  font-size: 48rpx;
  font-weight: 700;
  line-height: 1.2;
}
.stat-num-blue {
  color: #2563eb;
}
.stat-num-red {
  color: #dc2626;
}
.stat-num-gray {
  color: #4b5563;
}
.stat-label {
  font-size: 22rpx;
  color: #999;
  margin-top: 8rpx;
}
.empty-list {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 96rpx 0;
}
.empty-list-text {
  font-size: 26rpx;
  color: #999;
  margin-top: 24rpx;
}
.empty-list-btn {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-top: 32rpx;
  padding: 16rpx 32rpx;
  background: #C41E3A;
  border-radius: 12rpx;
}
.empty-list-btn-text {
  font-size: 26rpx;
  color: #fff;
}

/* 对话框 */
.dialog-mask {
  position: fixed;
  inset: 0;
  z-index: 100;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48rpx;
}
.dialog {
  width: 100%;
  max-width: 640rpx;
  background: #fff;
  border-radius: 24rpx;
  padding: 40rpx;
}
.dialog-title {
  font-size: 32rpx;
  font-weight: 600;
  color: #1a1a1a;
  display: block;
}
.dialog-desc {
  font-size: 26rpx;
  color: #999;
  margin-top: 12rpx;
  display: block;
  line-height: 1.5;
}
.tpl-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 24rpx;
  background: #f0ece5;
  border-radius: 16rpx;
  margin-top: 32rpx;
}
.tpl-left {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.tpl-name {
  font-size: 26rpx;
  color: #1a1a1a;
}
.tpl-dl {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.tpl-dl-text {
  font-size: 26rpx;
  color: #1a1a1a;
}
.upload-zone {
  border: 2px dashed #d8d2c8;
  border-radius: 16rpx;
  padding: 64rpx 32rpx;
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 32rpx;
}
.upload-main {
  font-size: 26rpx;
  font-weight: 500;
  color: #1a1a1a;
  margin-top: 24rpx;
}
.upload-sub {
  font-size: 22rpx;
  color: #999;
  margin-top: 8rpx;
}
.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 16rpx;
  margin-top: 40rpx;
}
.dlg-btn {
  padding: 16rpx 32rpx;
  border-radius: 12rpx;
  font-size: 26rpx;
}
.dlg-btn-outline {
  border: 1px solid #d8d2c8;
  color: #1a1a1a;
}
.dlg-btn-primary {
  background: #C41E3A;
  color: #fff;
}
.dlg-btn-danger {
  background: #dc2626;
  color: #fff;
}
</style>

// v0-reference/app/creator/live/schedule/page.tsx
"use client"

import { useState, useMemo } from "react"
import { useRouter } from "next/navigation"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"
import { 
  ChevronLeft, ChevronRight, Plus, Calendar, Clock, Eye, 
  MoreHorizontal, Copy, Trash2, Edit3, Upload, Download,
  Radio, BookOpen, ShoppingBag, Users, FileSpreadsheet,
  CalendarDays, List, Filter, Search
} from "lucide-react"

// 模拟场次数据
const mockSchedules = [
  {
    id: 1,
    title: "八字命理入门第一课：天干地支基础",
    date: "2026-05-12",
    time: "20:00",
    duration: 90,
    type: "knowledge",
    status: "scheduled",
    seriesName: "八字命理入门系列",
    seriesIndex: 1,
    seriesTotal: 8,
    viewerEstimate: 500,
  },
  {
    id: 2,
    title: "八字命理入门第二课：五行生克制化",
    date: "2026-05-14",
    time: "20:00",
    duration: 90,
    type: "knowledge",
    status: "scheduled",
    seriesName: "八字命理入门系列",
    seriesIndex: 2,
    seriesTotal: 8,
    viewerEstimate: 500,
  },
  {
    id: 3,
    title: "开光吉祥物专场直播",
    date: "2026-05-15",
    time: "19:30",
    duration: 120,
    type: "commerce",
    status: "scheduled",
    seriesName: null,
    seriesIndex: null,
    seriesTotal: null,
    viewerEstimate: 800,
  },
  {
    id: 4,
    title: "八字命理入门第三课：十神详解",
    date: "2026-05-19",
    time: "20:00",
    duration: 90,
    type: "knowledge",
    status: "scheduled",
    seriesName: "八字命理入门系列",
    seriesIndex: 3,
    seriesTotal: 8,
    viewerEstimate: 500,
  },
  {
    id: 5,
    title: "风水布局答疑专场",
    date: "2026-05-10",
    time: "20:00",
    duration: 60,
    type: "knowledge",
    status: "completed",
    seriesName: null,
    seriesIndex: null,
    seriesTotal: null,
    viewerEstimate: 300,
    actualViewers: 428,
  },
  {
    id: 6,
    title: "紫微斗数基础课",
    date: "2026-05-08",
    time: "19:00",
    duration: 90,
    type: "knowledge",
    status: "completed",
    seriesName: "紫微斗数入门系列",
    seriesIndex: 1,
    seriesTotal: 6,
    viewerEstimate: 400,
    actualViewers: 512,
  },
]

// 获取当月日历数据
function getCalendarDays(year: number, month: number) {
  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  const startDay = firstDay.getDay()
  const totalDays = lastDay.getDate()
  
  const days: (number | null)[] = []
  
  // 填充月初空白
  for (let i = 0; i < startDay; i++) {
    days.push(null)
  }
  
  // 填充日期
  for (let i = 1; i <= totalDays; i++) {
    days.push(i)
  }
  
  return days
}

// 格式化日期
function formatDate(dateStr: string) {
  const date = new Date(dateStr)
  return `${date.getMonth() + 1}月${date.getDate()}日`
}

// 状态配置
const statusConfig = {
  scheduled: { label: "待开播", color: "bg-blue-500/10 text-blue-600 border-blue-500/20" },
  live: { label: "直播中", color: "bg-red-500/10 text-red-600 border-red-500/20" },
  completed: { label: "已结束", color: "bg-gray-500/10 text-gray-600 border-gray-500/20" },
  cancelled: { label: "已取消", color: "bg-orange-500/10 text-orange-600 border-orange-500/20" },
}

export default function LiveSchedulePage() {
  const router = useRouter()
  const [viewMode, setViewMode] = useState<"calendar" | "list">("calendar")
  const [currentDate, setCurrentDate] = useState(new Date(2026, 4, 1)) // 2026年5月
  const [selectedDate, setSelectedDate] = useState<string | null>(null)
  const [showNewDialog, setShowNewDialog] = useState(false)
  const [showImportDialog, setShowImportDialog] = useState(false)
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [selectedSchedule, setSelectedSchedule] = useState<typeof mockSchedules[0] | null>(null)
  const [filterStatus, setFilterStatus] = useState<string>("all")
  const [searchQuery, setSearchQuery] = useState("")
  
  const year = currentDate.getFullYear()
  const month = currentDate.getMonth()
  const calendarDays = useMemo(() => getCalendarDays(year, month), [year, month])
  
  const monthNames = ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"]
  const weekDays = ["日", "一", "二", "三", "四", "五", "六"]
  
  // 获取某日期的场次
  const getSchedulesForDate = (day: number) => {
    const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`
    return mockSchedules.filter(s => s.date === dateStr)
  }
  
  // 过滤场次列表
  const filteredSchedules = useMemo(() => {
    return mockSchedules.filter(s => {
      if (filterStatus !== "all" && s.status !== filterStatus) return false
      if (searchQuery && !s.title.toLowerCase().includes(searchQuery.toLowerCase())) return false
      if (selectedDate && s.date !== selectedDate) return false
      return true
    }).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
  }, [filterStatus, searchQuery, selectedDate])
  
  // 切换月份
  const changeMonth = (delta: number) => {
    setCurrentDate(new Date(year, month + delta, 1))
    setSelectedDate(null)
  }
  
  // 复制场次
  const handleCopy = (schedule: typeof mockSchedules[0]) => {
    // 实际应用中会调用API复制场次
    console.log("复制场次:", schedule.id)
  }
  
  // 删除场次
  const handleDelete = (schedule: typeof mockSchedules[0]) => {
    setSelectedSchedule(schedule)
    setShowDeleteDialog(true)
  }
  
  return (
    <div className="min-h-screen bg-background pb-20">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-40 bg-background/95 backdrop-blur-md border-b border-border">
        <div className="flex items-center justify-between px-4 h-14">
          <div className="flex items-center gap-3">
            <button onClick={() => router.back()}>
              <ChevronLeft className="w-6 h-6" />
            </button>
            <h1 className="text-lg font-semibold">直播排期管理</h1>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => setShowImportDialog(true)}>
              <Upload className="w-4 h-4 mr-1.5" />
              导入
            </Button>
            <Button size="sm" onClick={() => router.push("/creator/live/create")}>
              <Plus className="w-4 h-4 mr-1.5" />
              新建场次
            </Button>
          </div>
        </div>
      </div>
      
      {/* 视图切换 & 筛选 */}
      <div className="px-4 py-3 border-b border-border">
        <div className="flex items-center justify-between gap-3">
          {/* 视图切换 */}
          <div className="flex items-center gap-1 p-1 bg-secondary rounded-lg">
            <button
              onClick={() => setViewMode("calendar")}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm transition-colors",
                viewMode === "calendar" ? "bg-background shadow-sm" : "text-muted-foreground"
              )}
            >
              <CalendarDays className="w-4 h-4" />
              日历
            </button>
            <button
              onClick={() => setViewMode("list")}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm transition-colors",
                viewMode === "list" ? "bg-background shadow-sm" : "text-muted-foreground"
              )}
            >
              <List className="w-4 h-4" />
              列表
            </button>
          </div>
          
          {/* 搜索 */}
          <div className="flex-1 max-w-xs relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="搜索直播..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 h-9"
            />
          </div>
        </div>
        
        {/* 状态筛选 */}
        <div className="flex items-center gap-2 mt-3 overflow-x-auto scrollbar-hide">
          {[
            { key: "all", label: "全部" },
            { key: "scheduled", label: "待开播" },
            { key: "live", label: "直播中" },
            { key: "completed", label: "已结束" },
          ].map(item => (
            <button
              key={item.key}
              onClick={() => setFilterStatus(item.key)}
              className={cn(
                "flex-shrink-0 px-3 py-1.5 rounded-full text-sm transition-colors",
                filterStatus === item.key 
                  ? "bg-primary text-primary-foreground" 
                  : "bg-secondary text-muted-foreground hover:text-foreground"
              )}
            >
              {item.label}
            </button>
          ))}
        </div>
      </div>
      
      {/* 日历视图 */}
      {viewMode === "calendar" && (
        <div className="px-4 py-4">
          {/* 月份切换 */}
          <div className="flex items-center justify-between mb-4">
            <button onClick={() => changeMonth(-1)} className="w-8 h-8 rounded-full hover:bg-secondary flex items-center justify-center">
              <ChevronLeft className="w-5 h-5" />
            </button>
            <h2 className="text-lg font-semibold">{year}年{monthNames[month]}</h2>
            <button onClick={() => changeMonth(1)} className="w-8 h-8 rounded-full hover:bg-secondary flex items-center justify-center">
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>
          
          {/* 星期头部 */}
          <div className="grid grid-cols-7 gap-1 mb-2">
            {weekDays.map(day => (
              <div key={day} className="text-center text-xs text-muted-foreground py-2">
                {day}
              </div>
            ))}
          </div>
          
          {/* 日历格子 */}
          <div className="grid grid-cols-7 gap-1">
            {calendarDays.map((day, index) => {
              if (day === null) {
                return <div key={`empty-${index}`} className="aspect-square" />
              }
              
              const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`
              const schedules = getSchedulesForDate(day)
              const isSelected = selectedDate === dateStr
              const isToday = dateStr === "2026-05-10" // 模拟今天
              
              return (
                <button
                  key={day}
                  onClick={() => setSelectedDate(isSelected ? null : dateStr)}
                  className={cn(
                    "aspect-square rounded-lg p-1 flex flex-col items-center justify-start transition-colors relative",
                    isSelected ? "bg-primary/10 ring-2 ring-primary" : "hover:bg-secondary",
                    isToday && !isSelected && "bg-accent"
                  )}
                >
                  <span className={cn(
                    "text-sm font-medium",
                    isToday && "text-primary"
                  )}>
                    {day}
                  </span>
                  
                  {/* 场次指示点 */}
                  {schedules.length > 0 && (
                    <div className="flex items-center gap-0.5 mt-0.5">
                      {schedules.slice(0, 3).map((s, i) => (
                        <div
                          key={i}
                          className={cn(
                            "w-1.5 h-1.5 rounded-full",
                            s.status === "scheduled" ? "bg-blue-500" :
                            s.status === "live" ? "bg-red-500" :
                            "bg-gray-400"
                          )}
                        />
                      ))}
                      {schedules.length > 3 && (
                        <span className="text-[8px] text-muted-foreground">+{schedules.length - 3}</span>
                      )}
                    </div>
                  )}
                </button>
              )
            })}
          </div>
          
          {/* 选中日期的场次列表 */}
          {selectedDate && (
            <div className="mt-4 pt-4 border-t border-border">
              <h3 className="text-sm font-medium mb-3">
                {formatDate(selectedDate)} 的直播 ({filteredSchedules.length}场)
              </h3>
              {filteredSchedules.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">
                  <Calendar className="w-8 h-8 mx-auto mb-2 opacity-50" />
                  <p className="text-sm">当日暂无直播排期</p>
                  <Button variant="outline" size="sm" className="mt-3" onClick={() => router.push("/creator/live/create")}>
                    <Plus className="w-4 h-4 mr-1.5" />
                    新建场次
                  </Button>
                </div>
              ) : (
                <div className="space-y-3">
                  {filteredSchedules.map(schedule => (
                    <ScheduleCard 
                      key={schedule.id} 
                      schedule={schedule} 
                      onEdit={() => router.push(`/creator/live/create?id=${schedule.id}`)}
                      onCopy={() => handleCopy(schedule)}
                      onDelete={() => handleDelete(schedule)}
                    />
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}
      
      {/* 列表视图 */}
      {viewMode === "list" && (
        <div className="px-4 py-4">
          {/* 统计概览 */}
          <div className="grid grid-cols-3 gap-3 mb-4">
            <Card className="p-3 text-center">
              <p className="text-2xl font-bold text-blue-600">
                {mockSchedules.filter(s => s.status === "scheduled").length}
              </p>
              <p className="text-xs text-muted-foreground mt-1">待开播</p>
            </Card>
            <Card className="p-3 text-center">
              <p className="text-2xl font-bold text-red-600">
                {mockSchedules.filter(s => s.status === "live").length}
              </p>
              <p className="text-xs text-muted-foreground mt-1">直播中</p>
            </Card>
            <Card className="p-3 text-center">
              <p className="text-2xl font-bold text-gray-600">
                {mockSchedules.filter(s => s.status === "completed").length}
              </p>
              <p className="text-xs text-muted-foreground mt-1">已结束</p>
            </Card>
          </div>
          
          {/* 场次列表 */}
          {filteredSchedules.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <CalendarDays className="w-12 h-12 mx-auto mb-3 opacity-30" />
              <p className="text-sm">暂无直播排期</p>
              <Button className="mt-4" onClick={() => router.push("/creator/live/create")}>
                <Plus className="w-4 h-4 mr-1.5" />
                创建第一场直播
              </Button>
            </div>
          ) : (
            <div className="space-y-3">
              {filteredSchedules.map(schedule => (
                <ScheduleCard 
                  key={schedule.id} 
                  schedule={schedule} 
                  showDate
                  onEdit={() => router.push(`/creator/live/create?id=${schedule.id}`)}
                  onCopy={() => handleCopy(schedule)}
                  onDelete={() => handleDelete(schedule)}
                />
              ))}
            </div>
          )}
        </div>
      )}
      
      {/* 新建场次对话框 */}
      <Dialog open={showNewDialog} onOpenChange={setShowNewDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>新建直播场次</DialogTitle>
            <DialogDescription>选择创建方式</DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-3 py-4">
            <button
              onClick={() => {
                setShowNewDialog(false)
                router.push("/creator/live/create")
              }}
              className="p-4 rounded-xl border border-border hover:border-primary hover:bg-primary/5 transition-colors text-center"
            >
              <Plus className="w-8 h-8 mx-auto mb-2 text-primary" />
              <p className="font-medium">单场直播</p>
              <p className="text-xs text-muted-foreground mt-1">创建独立直播场次</p>
            </button>
            <button
              onClick={() => {
                setShowNewDialog(false)
                router.push("/creator/live/create?series=true")
              }}
              className="p-4 rounded-xl border border-border hover:border-primary hover:bg-primary/5 transition-colors text-center"
            >
              <CalendarDays className="w-8 h-8 mx-auto mb-2 text-primary" />
              <p className="font-medium">系列直播</p>
              <p className="text-xs text-muted-foreground mt-1">批量创建多场直播</p>
            </button>
          </div>
        </DialogContent>
      </Dialog>
      
      {/* 导入对话框 */}
      <Dialog open={showImportDialog} onOpenChange={setShowImportDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>批量导入场次</DialogTitle>
            <DialogDescription>通过Excel文件批量导入直播排期</DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {/* 下载模板 */}
            <div className="flex items-center justify-between p-3 bg-secondary rounded-lg mb-4">
              <div className="flex items-center gap-2">
                <FileSpreadsheet className="w-5 h-5 text-green-600" />
                <span className="text-sm">排期导入模板.xlsx</span>
              </div>
              <Button variant="ghost" size="sm">
                <Download className="w-4 h-4 mr-1.5" />
                下载模板
              </Button>
            </div>
            
            {/* 上传区域 */}
            <div className="border-2 border-dashed border-border rounded-xl p-8 text-center hover:border-primary/50 transition-colors cursor-pointer">
              <Upload className="w-10 h-10 mx-auto mb-3 text-muted-foreground" />
              <p className="text-sm font-medium mb-1">点击或拖拽文件到此处</p>
              <p className="text-xs text-muted-foreground">支持 .xlsx, .xls 格式，单次最多100条</p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowImportDialog(false)}>取消</Button>
            <Button>开始导入</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      
      {/* 删除确认对话框 */}
      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>确认删除</DialogTitle>
            <DialogDescription>
              确定要删除直播「{selectedSchedule?.title}」吗？此操作不可恢复。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDeleteDialog(false)}>取消</Button>
            <Button variant="destructive" onClick={() => {
              console.log("删除场次:", selectedSchedule?.id)
              setShowDeleteDialog(false)
            }}>
              确认删除
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// 场次卡片组件
function ScheduleCard({ 
  schedule, 
  showDate = false,
  onEdit,
  onCopy,
  onDelete,
}: { 
  schedule: typeof mockSchedules[0]
  showDate?: boolean
  onEdit: () => void
  onCopy: () => void
  onDelete: () => void
}) {
  const [showMenu, setShowMenu] = useState(false)
  const status = statusConfig[schedule.status as keyof typeof statusConfig]
  
  return (
    <Card className="overflow-hidden">
      <div className="flex gap-3 p-3">
        {/* 封面占位 */}
        <div className="w-24 h-16 rounded-lg bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center flex-shrink-0 relative">
          {schedule.type === "knowledge" ? (
            <BookOpen className="w-6 h-6 text-primary/50" />
          ) : (
            <ShoppingBag className="w-6 h-6 text-primary/50" />
          )}
          {/* 系列标签 */}
          {schedule.seriesName && (
            <span className="absolute bottom-1 left-1 px-1 py-0.5 rounded bg-black/60 text-white text-[8px]">
              {schedule.seriesIndex}/{schedule.seriesTotal}
            </span>
          )}
        </div>
        
        {/* 内容 */}
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-2">
            <div className="min-w-0">
              <h3 className="text-sm font-medium line-clamp-1">{schedule.title}</h3>
              {schedule.seriesName && (
                <p className="text-[10px] text-muted-foreground truncate">{schedule.seriesName}</p>
              )}
            </div>
            <Badge variant="outline" className={cn("flex-shrink-0 text-[10px]", status.color)}>
              {status.label}
            </Badge>
          </div>
          
          <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
            {showDate && (
              <span className="flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {formatDate(schedule.date)}
              </span>
            )}
            <span className="flex items-center gap-1">
              <Clock className="w-3 h-3" />
              {schedule.time}
            </span>
            <span>{schedule.duration}分钟</span>
            <span className="flex items-center gap-1">
              <Eye className="w-3 h-3" />
              {schedule.status === "completed" ? schedule.actualViewers : `预计${schedule.viewerEstimate}`}
            </span>
          </div>
        </div>
        
        {/* 操作菜单 */}
        <div className="relative">
          <button 
            onClick={() => setShowMenu(!showMenu)}
            className="w-8 h-8 rounded-full hover:bg-secondary flex items-center justify-center"
          >
            <MoreHorizontal className="w-4 h-4" />
          </button>
          
          {showMenu && (
            <>
              <div className="fixed inset-0 z-40" onClick={() => setShowMenu(false)} />
              <div className="absolute right-0 top-full mt-1 z-50 w-32 bg-popover border border-border rounded-lg shadow-lg py-1">
                <button
                  onClick={() => { onEdit(); setShowMenu(false); }}
                  className="w-full flex items-center gap-2 px-3 py-2 text-sm hover:bg-secondary transition-colors"
                >
                  <Edit3 className="w-4 h-4" />
                  编辑
                </button>
                <button
                  onClick={() => { onCopy(); setShowMenu(false); }}
                  className="w-full flex items-center gap-2 px-3 py-2 text-sm hover:bg-secondary transition-colors"
                >
                  <Copy className="w-4 h-4" />
                  复制
                </button>
                <button
                  onClick={() => { onDelete(); setShowMenu(false); }}
                  className="w-full flex items-center gap-2 px-3 py-2 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-950/20 transition-colors"
                >
                  <Trash2 className="w-4 h-4" />
                  删除
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </Card>
  )
}
