// vue3/src/pkg-mine/change-phone/index.vue
<script setup lang="ts">
import { ref, onUnmounted } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'
import { mineProfile } from '@/lib/mine-data'

const step = ref(1)
const currentPhone = mineProfile.phone
const verifyCode = ref('')
const newPhone = ref('')
const newCode = ref('')
const countdown = ref(0)
const newCountdown = ref(0)
const loading = ref(false)
const error = ref('')

const steps = [
  { num: 1, label: '验证身份' },
  { num: 2, label: '绑定新号' },
  { num: 3, label: '完成' },
]

let timer1: ReturnType<typeof setInterval> | null = null
let timer2: ReturnType<typeof setInterval> | null = null

function sendVerifyCode() {
  if (countdown.value > 0) return
  countdown.value = 60
  timer1 = setInterval(() => {
    countdown.value--
    if (countdown.value <= 0 && timer1) clearInterval(timer1)
  }, 1000)
}
function sendNewCode() {
  if (newCountdown.value > 0 || newPhone.value.length !== 11) return
  newCountdown.value = 60
  timer2 = setInterval(() => {
    newCountdown.value--
    if (newCountdown.value <= 0 && timer2) clearInterval(timer2)
  }, 1000)
}
function onVerifyInput(e: any) {
  verifyCode.value = e.detail.value.replace(/\D/g, '')
  error.value = ''
}
function onNewPhoneInput(e: any) {
  newPhone.value = e.detail.value.replace(/\D/g, '')
  error.value = ''
}
function onNewCodeInput(e: any) {
  newCode.value = e.detail.value.replace(/\D/g, '')
  error.value = ''
}

async function verifyCurrentPhone() {
  if (verifyCode.value.length !== 6) {
    error.value = '请输入6位验证码'
    return
  }
  loading.value = true
  error.value = ''
  await new Promise((r) => setTimeout(r, 1000))
  loading.value = false
  step.value = 2
}
async function submitNewPhone() {
  if (newPhone.value.length !== 11) {
    error.value = '请输入正确的手机号'
    return
  }
  if (newCode.value.length !== 6) {
    error.value = '请输入6位验证码'
    return
  }
  loading.value = true
  error.value = ''
  await new Promise((r) => setTimeout(r, 1500))
  loading.value = false
  step.value = 3
  setTimeout(() => goBack(), 2000)
}
function maskedNewPhone() {
  return newPhone.value.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2')
}

onUnmounted(() => {
  if (timer1) clearInterval(timer1)
  if (timer2) clearInterval(timer2)
})
</script>

<template>
  <view class="page">
    <!-- 导航 -->
    <app-nav-bar title="修改手机号" :title-size="36" />

    <!-- 步骤指示器 -->
    <view class="steps">
      <view v-for="(item, idx) in steps" :key="item.num" class="step-cell">
        <view class="step-col">
          <view class="step-dot" :class="{ active: step >= item.num }">
            <AppIcon v-if="step > item.num" name="check-circle" :size="20" color="#fff" />
            <text v-else class="step-num" :class="{ active: step >= item.num }">{{ item.num }}</text>
          </view>
          <text class="step-label" :class="{ active: step >= item.num }">{{ item.label }}</text>
        </view>
        <view v-if="idx < 2" class="step-line" :class="{ active: step > item.num }" />
      </view>
    </view>

    <!-- 步骤1 -->
    <view v-if="step === 1" class="body">
      <view class="card">
        <view class="card-head">
          <view class="head-icon red"><AppIcon name="shield" :size="24" color="#C41E3A" /></view>
          <view>
            <text class="head-title">验证当前手机号</text>
            <text class="head-sub">为保障账号安全，请先验证身份</text>
          </view>
        </view>
        <view class="phone-box">
          <AppIcon name="phone" :size="20" color="#666" />
          <text class="phone-text">{{ currentPhone }}</text>
          <text class="phone-tag">当前绑定</text>
        </view>
        <view class="form">
          <text class="form-label">短信验证码</text>
          <view class="code-row">
            <input class="code-input" type="number" :maxlength="6" :value="verifyCode" @input="onVerifyInput" placeholder="请输入验证码" placeholder-class="ph" />
            <view class="code-btn" :class="{ disabled: countdown > 0 }" @tap="sendVerifyCode">
              <text class="code-btn-text" :class="{ disabled: countdown > 0 }">{{ countdown > 0 ? `${countdown}s` : '获取验证码' }}</text>
            </view>
          </view>
          <text v-if="error" class="err">{{ error }}</text>
          <view class="primary-btn" :class="{ disabled: loading || verifyCode.length !== 6 }" @tap="verifyCurrentPhone">
            <text class="primary-btn-text">{{ loading ? '验证中...' : '下一步' }}</text>
            <AppIcon v-if="!loading" name="arrow-right" :size="16" color="#fff" />
          </view>
        </view>
      </view>
    </view>

    <!-- 步骤2 -->
    <view v-if="step === 2" class="body">
      <view class="card">
        <view class="card-head">
          <view class="head-icon green"><AppIcon name="phone" :size="24" color="#16a34a" /></view>
          <view>
            <text class="head-title">绑定新手机号</text>
            <text class="head-sub">请输入新的手机号并验证</text>
          </view>
        </view>
        <view class="form">
          <text class="form-label">新手机号</text>
          <input class="full-input" type="number" :maxlength="11" :value="newPhone" @input="onNewPhoneInput" placeholder="请输入新手机号" placeholder-class="ph" />
          <text class="form-label">短信验证码</text>
          <view class="code-row">
            <input class="code-input" type="number" :maxlength="6" :value="newCode" @input="onNewCodeInput" placeholder="请输入验证码" placeholder-class="ph" />
            <view class="code-btn" :class="{ disabled: newCountdown > 0 || newPhone.length !== 11 }" @tap="sendNewCode">
              <text class="code-btn-text" :class="{ disabled: newCountdown > 0 || newPhone.length !== 11 }">{{ newCountdown > 0 ? `${newCountdown}s` : '获取验证码' }}</text>
            </view>
          </view>
          <text v-if="error" class="err">{{ error }}</text>
          <view class="primary-btn" :class="{ disabled: loading || newPhone.length !== 11 || newCode.length !== 6 }" @tap="submitNewPhone">
            <text class="primary-btn-text">{{ loading ? '提交中...' : '确认绑定' }}</text>
          </view>
          <view class="back-btn" @tap="step = 1"><text class="back-btn-text">返回上一步</text></view>
        </view>
      </view>
      <text class="foot-tip">温馨提示：更换手机号后，原手机号将无法用于登录和找回密码</text>
    </view>

    <!-- 步骤3 -->
    <view v-if="step === 3" class="body">
      <view class="card done-card">
        <view class="done-icon"><AppIcon name="check-circle" :size="40" color="#16a34a" /></view>
        <text class="done-title">绑定成功</text>
        <text class="done-sub">新手机号已绑定</text>
        <text class="done-phone">{{ maskedNewPhone() }}</text>
        <text class="done-tip">页面即将自动返回...</text>
      </view>
    </view>
  </view>
</template>

<style scoped>
.page {
  min-height: 100vh;
  background: #faf8f5;
}
.steps {
  display: flex;
  align-items: flex-start;
  padding: 48rpx;
}
.step-cell {
  display: flex;
  align-items: center;
  flex: 1;
}
.step-cell:last-child {
  flex: none;
}
.step-col {
  display: flex;
  flex-direction: column;
  align-items: center;
}
.step-dot {
  width: 64rpx;
  height: 64rpx;
  border-radius: 50%;
  background: #e8e3db;
  display: flex;
  align-items: center;
  justify-content: center;
}
.step-dot.active {
  background: #c41e3a;
}
.step-num {
  font-size: 28rpx;
  font-weight: 500;
  color: #999;
}
.step-num.active {
  color: #fff;
}
.step-label {
  font-size: 22rpx;
  color: #999;
  margin-top: 12rpx;
}
.step-label.active {
  color: #c41e3a;
}
.step-line {
  flex: 1;
  height: 2rpx;
  background: #e8e3db;
  margin: 32rpx 16rpx 0;
}
.step-line.active {
  background: #c41e3a;
}
.body {
  padding: 0 32rpx;
}
.card {
  background: #fff;
  border-radius: 28rpx;
  padding: 48rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
}
.card-head {
  display: flex;
  align-items: center;
  gap: 24rpx;
  margin-bottom: 48rpx;
}
.head-icon {
  width: 96rpx;
  height: 96rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.head-icon.red {
  background: rgba(196, 30, 58, 0.1);
}
.head-icon.green {
  background: #dcfce7;
}
.head-title {
  display: block;
  font-size: 30rpx;
  font-weight: 500;
  color: #2c2c2c;
}
.head-sub {
  display: block;
  font-size: 26rpx;
  color: #999;
  margin-top: 4rpx;
}
.phone-box {
  display: flex;
  align-items: center;
  gap: 24rpx;
  background: #faf8f5;
  border-radius: 20rpx;
  padding: 28rpx;
  margin-bottom: 48rpx;
}
.phone-text {
  font-size: 28rpx;
  font-weight: 500;
  color: #2c2c2c;
}
.phone-tag {
  margin-left: auto;
  font-size: 22rpx;
  color: #999;
}
.form {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.form-label {
  font-size: 26rpx;
  color: #666;
}
.full-input {
  height: 88rpx;
  padding: 0 28rpx;
  background: #faf8f5;
  border-radius: 20rpx;
  font-size: 28rpx;
  color: #2c2c2c;
}
.code-row {
  display: flex;
  gap: 24rpx;
}
.code-input {
  flex: 1;
  height: 88rpx;
  padding: 0 28rpx;
  background: #faf8f5;
  border-radius: 20rpx;
  font-size: 28rpx;
  color: #2c2c2c;
}
.ph {
  color: #ccc;
}
.code-btn {
  padding: 0 28rpx;
  height: 88rpx;
  border-radius: 20rpx;
  background: #c41e3a;
  display: flex;
  align-items: center;
  justify-content: center;
}
.code-btn.disabled {
  background: #e8e3db;
}
.code-btn-text {
  font-size: 26rpx;
  font-weight: 500;
  color: #fff;
}
.code-btn-text.disabled {
  color: #999;
}
.err {
  font-size: 24rpx;
  color: #ef4444;
}
.primary-btn {
  height: 88rpx;
  border-radius: 20rpx;
  background: #c41e3a;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12rpx;
}
.primary-btn.disabled {
  opacity: 0.5;
}
.primary-btn-text {
  font-size: 28rpx;
  font-weight: 500;
  color: #fff;
}
.back-btn {
  height: 88rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}
.back-btn-text {
  font-size: 26rpx;
  color: #666;
}
.foot-tip {
  display: block;
  font-size: 22rpx;
  color: #999;
  margin-top: 24rpx;
  padding: 0 8rpx;
}
.done-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 64rpx 48rpx;
}
.done-icon {
  width: 160rpx;
  height: 160rpx;
  border-radius: 50%;
  background: #dcfce7;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 48rpx;
}
.done-title {
  font-size: 40rpx;
  font-weight: 600;
  color: #2c2c2c;
  margin-bottom: 16rpx;
}
.done-sub {
  font-size: 28rpx;
  color: #666;
  margin-bottom: 16rpx;
}
.done-phone {
  font-size: 32rpx;
  font-weight: 500;
  color: #c41e3a;
}
.done-tip {
  font-size: 24rpx;
  color: #999;
  margin-top: 48rpx;
}
</style>

// v0-reference/proto-ref-app/mine/change-phone/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ChevronLeft, Phone, Shield, CheckCircle, ArrowRight } from 'lucide-react'

export default function ChangePhonePage() {
  const router = useRouter()
  const [step, setStep] = useState(1)
  const [currentPhone] = useState('138****8888')
  const [verifyCode, setVerifyCode] = useState('')
  const [newPhone, setNewPhone] = useState('')
  const [newCode, setNewCode] = useState('')
  const [countdown, setCountdown] = useState(0)
  const [newCountdown, setNewCountdown] = useState(0)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    if (countdown > 0) {
      const timer = setTimeout(() => setCountdown(countdown - 1), 1000)
      return () => clearTimeout(timer)
    }
  }, [countdown])

  useEffect(() => {
    if (newCountdown > 0) {
      const timer = setTimeout(() => setNewCountdown(newCountdown - 1), 1000)
      return () => clearTimeout(timer)
    }
  }, [newCountdown])

  const sendVerifyCode = () => {
    if (countdown > 0) return
    setCountdown(60)
  }

  const sendNewCode = () => {
    if (newCountdown > 0 || !newPhone || newPhone.length !== 11) return
    setNewCountdown(60)
  }

  const verifyCurrentPhone = async () => {
    if (verifyCode.length !== 6) {
      setError('请输入6位验证码')
      return
    }
    setLoading(true)
    setError('')
    await new Promise(resolve => setTimeout(resolve, 1000))
    setLoading(false)
    setStep(2)
  }

  const submitNewPhone = async () => {
    if (!newPhone || newPhone.length !== 11) {
      setError('请输入正确的手机号')
      return
    }
    if (newCode.length !== 6) {
      setError('请输入6位验证码')
      return
    }
    setLoading(true)
    setError('')
    await new Promise(resolve => setTimeout(resolve, 1500))
    setLoading(false)
    setStep(3)
    setTimeout(() => router.back(), 2000)
  }

  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      {/* 导航栏 */}
      <div className="sticky top-0 z-10 bg-white border-b border-[#E8E3DB]">
        <div className="flex items-center justify-between px-4 h-14">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ChevronLeft className="w-5 h-5 text-[#2C2C2C]" />
          </button>
          <h1 className="text-lg font-semibold text-[#2C2C2C]">修改手机号</h1>
          <div className="w-9" />
        </div>
      </div>

      {/* 步骤指示器 */}
      <div className="px-6 py-6">
        <div className="flex items-center justify-between">
          {[
            { num: 1, label: '验证身份' },
            { num: 2, label: '绑定新号' },
            { num: 3, label: '完成' }
          ].map((item, index) => (
            <div key={item.num} className="flex items-center flex-1">
              <div className="flex flex-col items-center">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors ${
                  step >= item.num 
                    ? 'bg-[#C41E3A] text-white' 
                    : 'bg-[#E8E3DB] text-[#999999]'
                }`}>
                  {step > item.num ? <CheckCircle className="w-5 h-5" /> : item.num}
                </div>
                <span className={`text-xs mt-2 ${
                  step >= item.num ? 'text-[#C41E3A]' : 'text-[#999999]'
                }`}>{item.label}</span>
              </div>
              {index < 2 && (
                <div className={`flex-1 h-0.5 mx-2 mt-[-20px] ${
                  step > item.num ? 'bg-[#C41E3A]' : 'bg-[#E8E3DB]'
                }`} />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* 步骤1：验证当前手机号 */}
      {step === 1 && (
        <div className="px-4">
          <div className="bg-white rounded-2xl p-6 shadow-sm">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-12 h-12 rounded-full bg-[#C41E3A]/10 flex items-center justify-center">
                <Shield className="w-6 h-6 text-[#C41E3A]" />
              </div>
              <div>
                <h3 className="font-medium text-[#2C2C2C]">验证当前手机号</h3>
                <p className="text-sm text-[#999999]">为保障账号安全，请先验证身份</p>
              </div>
            </div>

            <div className="bg-[#FAF8F5] rounded-xl p-4 mb-6">
              <div className="flex items-center gap-3">
                <Phone className="w-5 h-5 text-[#666666]" />
                <span className="text-[#2C2C2C] font-medium">{currentPhone}</span>
                <span className="text-xs text-[#999999] ml-auto">当前绑定</span>
              </div>
            </div>

            <div className="space-y-4">
              <div>
                <label className="text-sm text-[#666666] mb-2 block">短信验证码</label>
                <div className="flex gap-3">
                  <input
                    type="text"
                    maxLength={6}
                    value={verifyCode}
                    onChange={(e) => {
                      setVerifyCode(e.target.value.replace(/\D/g, ''))
                      setError('')
                    }}
                    placeholder="请输入验证码"
                    className="flex-1 h-12 px-4 bg-[#FAF8F5] rounded-xl border-0 text-[#2C2C2C] placeholder:text-[#CCCCCC] focus:ring-2 focus:ring-[#C41E3A]/20"
                  />
                  <button
                    onClick={sendVerifyCode}
                    disabled={countdown > 0}
                    className={`px-4 h-12 rounded-xl text-sm font-medium whitespace-nowrap ${
                      countdown > 0
                        ? 'bg-[#E8E3DB] text-[#999999]'
                        : 'bg-[#C41E3A] text-white'
                    }`}
                  >
                    {countdown > 0 ? `${countdown}s` : '获取验证码'}
                  </button>
                </div>
              </div>

              {error && (
                <p className="text-sm text-red-500">{error}</p>
              )}

              <button
                onClick={verifyCurrentPhone}
                disabled={loading || verifyCode.length !== 6}
                className="w-full h-12 bg-[#C41E3A] text-white rounded-xl font-medium disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {loading ? (
                  <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    下一步
                    <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 步骤2：输入新手机号 */}
      {step === 2 && (
        <div className="px-4">
          <div className="bg-white rounded-2xl p-6 shadow-sm">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center">
                <Phone className="w-6 h-6 text-green-600" />
              </div>
              <div>
                <h3 className="font-medium text-[#2C2C2C]">绑定新手机号</h3>
                <p className="text-sm text-[#999999]">请输入新的手机号并验证</p>
              </div>
            </div>

            <div className="space-y-4">
              <div>
                <label className="text-sm text-[#666666] mb-2 block">新手机号</label>
                <input
                  type="tel"
                  maxLength={11}
                  value={newPhone}
                  onChange={(e) => {
                    setNewPhone(e.target.value.replace(/\D/g, ''))
                    setError('')
                  }}
                  placeholder="请输入新手机号"
                  className="w-full h-12 px-4 bg-[#FAF8F5] rounded-xl border-0 text-[#2C2C2C] placeholder:text-[#CCCCCC] focus:ring-2 focus:ring-[#C41E3A]/20"
                />
              </div>

              <div>
                <label className="text-sm text-[#666666] mb-2 block">短信验证码</label>
                <div className="flex gap-3">
                  <input
                    type="text"
                    maxLength={6}
                    value={newCode}
                    onChange={(e) => {
                      setNewCode(e.target.value.replace(/\D/g, ''))
                      setError('')
                    }}
                    placeholder="请输入验证码"
                    className="flex-1 h-12 px-4 bg-[#FAF8F5] rounded-xl border-0 text-[#2C2C2C] placeholder:text-[#CCCCCC] focus:ring-2 focus:ring-[#C41E3A]/20"
                  />
                  <button
                    onClick={sendNewCode}
                    disabled={newCountdown > 0 || newPhone.length !== 11}
                    className={`px-4 h-12 rounded-xl text-sm font-medium whitespace-nowrap ${
                      newCountdown > 0 || newPhone.length !== 11
                        ? 'bg-[#E8E3DB] text-[#999999]'
                        : 'bg-[#C41E3A] text-white'
                    }`}
                  >
                    {newCountdown > 0 ? `${newCountdown}s` : '获取验证码'}
                  </button>
                </div>
              </div>

              {error && (
                <p className="text-sm text-red-500">{error}</p>
              )}

              <button
                onClick={submitNewPhone}
                disabled={loading || newPhone.length !== 11 || newCode.length !== 6}
                className="w-full h-12 bg-[#C41E3A] text-white rounded-xl font-medium disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {loading ? (
                  <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  '确认绑定'
                )}
              </button>

              <button
                onClick={() => setStep(1)}
                className="w-full h-12 text-[#666666] text-sm"
              >
                返回上一步
              </button>
            </div>
          </div>

          <div className="mt-4 px-2">
            <p className="text-xs text-[#999999]">
              温馨提示：更换手机号后，原手机号将无法用于登录和找回密码
            </p>
          </div>
        </div>
      )}

      {/* 步骤3：完成 */}
      {step === 3 && (
        <div className="px-4">
          <div className="bg-white rounded-2xl p-8 shadow-sm text-center">
            <div className="w-20 h-20 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-6">
              <CheckCircle className="w-10 h-10 text-green-600" />
            </div>
            <h3 className="text-xl font-semibold text-[#2C2C2C] mb-2">绑定成功</h3>
            <p className="text-[#666666] mb-2">新手机号已绑定</p>
            <p className="text-lg font-medium text-[#C41E3A]">
              {newPhone.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2')}
            </p>
            <p className="text-sm text-[#999999] mt-6">页面即将自动返回...</p>
          </div>
        </div>
      )}
    </div>
  )
}
