// app/classics/collections/page.tsx
"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Search, Trash2, Heart, BookOpen, Headphones, Video, GraduationCap, ChevronRight } from "lucide-react"
import { cn } from "@/lib/utils"
import { ClassicsHeader, FlatCover, coverColorForBook, type CoverColor } from "@/components/classics"

type MediaType = "audiobook" | "article" | "video" | "course"

interface CollectionItem {
  id: string
  title: string
  type: MediaType
  author: string
  addedDate: string
  plays: number
  color: CoverColor
}

const mockCollections: CollectionItem[] = [
  { id: "1", title: "《道德经》完整版朗读", type: "audiobook", author: "王教授", addedDate: "2024-01-18", plays: 45, color: "brown" },
  { id: "2", title: "易经入门必读", type: "article", author: "易学研究院", addedDate: "2024-01-17", plays: 0, color: "cream" },
  { id: "3", title: "四书五经核心讲座", type: "video", author: "孔子学堂", addedDate: "2024-01-16", plays: 28, color: "red" },
  { id: "4", title: "黄帝内经养生秘诀", type: "article", author: "中医学院", addedDate: "2024-01-15", plays: 12, color: "green" },
  { id: "5", title: "奇门遁甲应用指南", type: "course", author: "命理大师", addedDate: "2024-01-14", plays: 0, color: "blue" },
]

const TYPE_META: Record<MediaType, { label: string; icon: typeof BookOpen }> = {
  audiobook: { label: "有声书", icon: Headphones },
  article: { label: "文章", icon: BookOpen },
  video: { label: "视频", icon: Video },
  course: { label: "课程", icon: GraduationCap },
}

const FILTERS = [
  { id: "all", label: "全部" },
  { id: "article", label: "文章" },
  { id: "audiobook", label: "有声书" },
  { id: "video", label: "视频" },
  { id: "course", label: "课程" },
] as const

export default function ClassicsCollectionsPage() {
  const router = useRouter()
  const [searchText, setSearchText] = useState("")
  const [filter, setFilter] = useState<string>("all")
  const [collections, setCollections] = useState(mockCollections)

  const filtered = collections.filter(
    (item) =>
      (filter === "all" || item.type === filter) &&
      (item.title.includes(searchText) || item.author.includes(searchText)),
  )

  const removeCollection = (id: string) => setCollections((prev) => prev.filter((item) => item.id !== id))

  const openCollection = (item: CollectionItem) => {
    switch (item.type) {
      case "audiobook":
        router.push(`/classics/audiobooks/${item.id}`)
        break
      case "video":
        router.push(`/video/${item.id}`)
        break
      case "course":
        router.push(`/courses/${item.id}`)
        break
      default:
        router.push(`/classics/${item.id}`)
    }
  }

  return (
    <div className="min-h-screen bg-[#f4f2ee] dark:bg-background pb-20 sm:pb-10">
      <ClassicsHeader title="我的收藏" showSearch={false} />

      <main className="max-w-screen-xl mx-auto">
        {/* Hero */}
        <section className="px-5 sm:px-6 pt-2 pb-4">
          <p className="text-[13px] font-semibold tracking-wide text-[#c41e3a] dark:text-amber-400 mb-1.5">珍藏一处</p>
          <h2 className="text-[34px] leading-[1.1] font-bold tracking-tight text-foreground">我的收藏</h2>
        </section>

        {/* 搜索 */}
        <section className="px-5 sm:px-6 pb-3">
          <div className="flex items-center gap-2.5 w-full h-11 px-4 rounded-2xl bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5">
            <Search className="w-[18px] h-[18px] text-muted-foreground flex-shrink-0" />
            <input
              placeholder="搜索收藏的内容"
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              className="flex-1 bg-transparent text-[15px] text-foreground placeholder:text-muted-foreground outline-none"
            />
          </div>
        </section>

        {/* 类型筛选 */}
        <section className="pb-4">
          <div className="flex gap-2 overflow-x-auto scrollbar-hide px-5 sm:px-6">
            {FILTERS.map((f) => (
              <button
                key={f.id}
                onClick={() => setFilter(f.id)}
                className={cn(
                  "flex-shrink-0 h-8 px-3.5 rounded-full text-[13px] font-medium transition-colors",
                  filter === f.id
                    ? "bg-foreground text-background"
                    : "bg-card text-muted-foreground ring-1 ring-black/[0.04] dark:ring-white/5",
                )}
              >
                {f.label}
              </button>
            ))}
          </div>
        </section>

        {/* 收藏列表 */}
        <section className="px-5 sm:px-6">
          {filtered.length > 0 ? (
            <div className="space-y-3">
              {filtered.map((item) => {
                const meta = TYPE_META[item.type]
                const Icon = meta.icon
                return (
                  <div
                    key={item.id}
                    className="flex items-center gap-4 p-4 bg-card rounded-2xl shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5"
                  >
                    <button onClick={() => openCollection(item)} className="flex items-center gap-4 flex-1 min-w-0 text-left active:scale-[0.99] transition-transform">
                      <FlatCover title={item.title.replace(/[《》]/g, "").slice(0, 4)} coverColor={coverColorForBook(item.title)} className="w-14 flex-shrink-0" titleClassName="text-xs" />
                      <div className="flex-1 min-w-0">
                        <h3 className="font-semibold text-[15px] text-foreground line-clamp-1">{item.title}</h3>
                        <p className="text-[12px] text-muted-foreground mt-1 flex items-center gap-1.5">
                          <Icon className="w-3.5 h-3.5" />
                          <span className="px-1.5 py-0.5 rounded-md bg-muted text-[11px]">{meta.label}</span>
                          <span>{item.author}</span>
                        </p>
                        {item.plays > 0 && (
                          <p className="text-[11px] text-muted-foreground/70 mt-1">已播放 {item.plays} 次</p>
                        )}
                      </div>
                    </button>
                    <button
                      onClick={() => removeCollection(item.id)}
                      className="p-2 text-muted-foreground/60 active:text-[#c41e3a] transition-colors flex-shrink-0"
                      aria-label="移除收藏"
                    >
                      <Trash2 className="w-[18px] h-[18px]" />
                    </button>
                  </div>
                )
              })}
            </div>
          ) : (
            <div className="rounded-3xl bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 p-10 text-center">
              <span className="w-14 h-14 rounded-full bg-muted flex items-center justify-center mx-auto mb-3">
                <Heart className="w-6 h-6 text-muted-foreground" />
              </span>
              <p className="text-[15px] text-foreground font-medium">还没有收藏任何内容</p>
              <p className="text-[13px] text-muted-foreground mt-1">浏览古籍，把喜欢的收进来</p>
              <button
                onClick={() => router.push("/classics/home")}
                className="mt-5 inline-flex items-center gap-1.5 h-10 px-5 rounded-full bg-[#c41e3a] dark:bg-amber-500 text-white text-[14px] font-semibold active:scale-[0.98] transition-transform"
              >
                <BookOpen className="w-4 h-4" />去逛古籍馆
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          )}
        </section>
      </main>
    </div>
  )
}

// apps/mobile/src/pkg-classics/collections/index.vue
<template>
  <view class="cl-page">
    <classics-header
      title="我的收藏"
      :show-search="false"
    />

    <view class="cl-main">
      <!-- Hero -->
      <view class="cl-hero">
        <text class="cl-kicker">
          珍藏一处
        </text>
        <text class="cl-title">
          我的收藏
        </text>
      </view>

      <!-- 搜索 -->
      <view class="cl-search-wrap">
        <view class="cl-search">
          <app-icon
            name="search"
            :size="36"
            color="#999999"
          />
          <input
            v-model="searchText"
            class="cl-search-input"
            placeholder="搜索收藏的内容"
            placeholder-class="cl-ph"
          >
        </view>
      </view>

      <!-- 类型筛选 -->
      <scroll-view
        scroll-x
        class="cl-filters"
        :show-scrollbar="false"
      >
        <view class="cl-filters-row">
          <view
            v-for="f in filters"
            :key="f.id"
            class="cl-chip"
            :class="{ 'cl-chip--active': filter === f.id }"
            @tap="filter = f.id"
          >
            <text
              class="cl-chip-text"
              :class="{ 'cl-chip-text--active': filter === f.id }"
            >
              {{ f.label }}
            </text>
          </view>
        </view>
      </scroll-view>

      <!-- 收藏列表 -->
      <view class="cl-list-wrap">
        <view
          v-if="filtered.length > 0"
          class="cl-list"
        >
          <view
            v-for="item in filtered"
            :key="item.id"
            class="cl-card"
          >
            <view
              class="cl-card-main"
              @tap="openItem(item)"
            >
              <view class="cl-cover">
                <flat-cover
                  :title="shortTitle(item.title)"
                  :cover-color="coverColorForBook(item.title)"
                  :title-size="22"
                />
              </view>
              <view class="cl-info">
                <text class="cl-name">
                  {{ item.title }}
                </text>
                <view class="cl-meta">
                  <app-icon
                    :name="typeMeta[item.type].icon"
                    :size="28"
                    color="#999999"
                  />
                  <text class="cl-type-tag">
                    {{ typeMeta[item.type].label }}
                  </text>
                  <text class="cl-author">
                    {{ item.author }}
                  </text>
                </view>
                <text
                  v-if="item.plays > 0"
                  class="cl-plays"
                >
                  已播放 {{ item.plays }} 次
                </text>
              </view>
            </view>
            <view
              class="cl-del"
              @tap="removeItem(item.id)"
            >
              <app-icon
                name="trash-2"
                :size="36"
                color="#bbbbbb"
              />
            </view>
          </view>
        </view>

        <!-- 空状态 -->
        <view
          v-else
          class="cl-empty"
        >
          <view class="cl-empty-icon">
            <app-icon
              name="heart"
              :size="48"
              color="#999999"
            />
          </view>
          <text class="cl-empty-title">
            还没有收藏任何内容
          </text>
          <text class="cl-empty-sub">
            浏览古籍，把喜欢的收进来
          </text>
          <view
            class="cl-empty-btn"
            @tap="goHome"
          >
            <app-icon
              name="book-open"
              :size="32"
              color="#ffffff"
            />
            <text class="cl-empty-btn-text">
              去逛古籍馆
            </text>
            <app-icon
              name="chevron-right"
              :size="32"
              color="#ffffff"
            />
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import ClassicsHeader from '@/components/classics/classics-header.vue'
import FlatCover from '@/components/classics/flat-cover.vue'
import AppIcon from '@/components/common/app-icon.vue'
import { coverColorForBook } from '@/lib/classics-cover'
import { mockCollections, collectionTypeMeta, collectionFilters, type CollectionItem } from '@/lib/classics-data'

const searchText = ref('')
const filter = ref<string>('all')
const collections = ref<CollectionItem[]>([...mockCollections])
const typeMeta = collectionTypeMeta
const filters = collectionFilters

const filtered = computed(() =>
  collections.value.filter(
    (item) =>
      (filter.value === 'all' || item.type === filter.value) &&
      (item.title.includes(searchText.value) || item.author.includes(searchText.value)),
  ),
)

function shortTitle(t: string): string {
  return t.replace(/[《》]/g, '').slice(0, 4)
}
function removeItem(id: string) {
  collections.value = collections.value.filter((i) => i.id !== id)
}
function openItem(item: CollectionItem) {
  switch (item.type) {
    case 'audiobook':
      uni.navigateTo({ url: `/pkg-classics/audiobooks/player?id=${item.id}` })
      break
    default:
      uni.navigateTo({ url: `/pkg-classics/detail/index?id=${item.id}` })
  }
}
function goHome() {
  uni.navigateTo({ url: '/pkg-classics/home/index' })
}
</script>

<style scoped lang="scss">
.cl-page {
  min-height: 100vh;
  background: #f4f2ee;
  padding-bottom: 160rpx;
}
.cl-main {
  width: 100%;
}
.cl-hero {
  display: flex;
  flex-direction: column;
  padding: 16rpx 40rpx 32rpx;
}
.cl-kicker {
  font-size: 26rpx;
  font-weight: 600;
  letter-spacing: 1rpx;
  color: #c41e3a;
  margin-bottom: 12rpx;
}
.cl-title {
  font-size: 68rpx;
  line-height: 1.1;
  font-weight: 700;
  letter-spacing: -1rpx;
  color: var(--foreground);
}
.cl-search-wrap {
  padding: 0 40rpx 24rpx;
}
.cl-search {
  display: flex;
  align-items: center;
  gap: 20rpx;
  width: 100%;
  height: 88rpx;
  padding: 0 32rpx;
  border-radius: 32rpx;
  background: var(--card);
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
}
.cl-search-input {
  flex: 1;
  font-size: 30rpx;
  color: var(--foreground);
}
.cl-ph {
  color: #999999;
}
.cl-filters {
  width: 100%;
  white-space: nowrap;
  padding-bottom: 32rpx;
}
.cl-filters-row {
  display: inline-flex;
  align-items: center;
  gap: 16rpx;
  padding: 0 40rpx;
}
.cl-chip {
  flex-shrink: 0;
  height: 64rpx;
  padding: 0 28rpx;
  border-radius: 999rpx;
  display: flex;
  align-items: center;
  background: var(--card);
  border: 1rpx solid rgba(0, 0, 0, 0.04);
}
.cl-chip--active {
  background: var(--foreground);
  border-color: var(--foreground);
}
.cl-chip-text {
  font-size: 26rpx;
  font-weight: 500;
  color: #999999;
}
.cl-chip-text--active {
  color: var(--background);
}
.cl-list-wrap {
  padding: 0 40rpx;
}
.cl-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.cl-card {
  display: flex;
  align-items: center;
  gap: 32rpx;
  padding: 32rpx;
  background: var(--card);
  border-radius: 32rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
}
.cl-card-main {
  display: flex;
  align-items: center;
  gap: 32rpx;
  flex: 1;
  min-width: 0;
}
.cl-cover {
  width: 112rpx;
  flex-shrink: 0;
}
.cl-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
}
.cl-name {
  font-size: 30rpx;
  font-weight: 600;
  color: var(--foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.cl-meta {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-top: 8rpx;
}
.cl-type-tag {
  flex-shrink: 0;
  padding: 2rpx 12rpx;
  border-radius: 8rpx;
  background: var(--muted);
  font-size: 22rpx;
  color: #999999;
}
.cl-author {
  font-size: 24rpx;
  color: #999999;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.cl-plays {
  font-size: 22rpx;
  color: rgba(153, 153, 153, 0.7);
  margin-top: 8rpx;
}
.cl-del {
  flex-shrink: 0;
  padding: 16rpx;
}
.cl-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 80rpx 40rpx;
  background: var(--card);
  border-radius: 48rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
}
.cl-empty-icon {
  width: 112rpx;
  height: 112rpx;
  border-radius: 999rpx;
  background: var(--muted);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 24rpx;
}
.cl-empty-title {
  font-size: 30rpx;
  font-weight: 500;
  color: var(--foreground);
}
.cl-empty-sub {
  font-size: 26rpx;
  color: #999999;
  margin-top: 8rpx;
}
.cl-empty-btn {
  display: flex;
  align-items: center;
  gap: 12rpx;
  height: 80rpx;
  padding: 0 40rpx;
  border-radius: 999rpx;
  background: #c41e3a;
  margin-top: 40rpx;
}
.cl-empty-btn-text {
  font-size: 28rpx;
  font-weight: 600;
  color: #ffffff;
}
</style>
