// proto-ref-app/same-city/nearby-users/page.tsx
"use client"

import { useState, useEffect, useCallback } from "react"
import { useRouter } from "next/navigation"
import { 
  ChevronLeft, 
  MapPin, 
  Settings,
  Search,
  UserCheck,
  UserPlus,
  MessageCircle,
  BadgeCheck,
  RefreshCw,
  Users,
  GraduationCap,
  Award,
  Eye,
  EyeOff,
  ChevronRight
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { cn } from "@/lib/utils"
import { 
  getNearbyUsers,
  followUser,
  unfollowUser,
  getLocationPrivacySetting,
  updateLocationPrivacySetting,
  getUserTypeLabel,
  getUserTypeColor,
  formatUserDistance
} from "@/lib/api/same-city"
import type { NearbyUser, NearbyUserType, LocationPrivacySetting } from "@/lib/types/same-city"

// 骨架屏
function Skeleton({ className }: { className?: string }) {
  return <div className={cn("animate-pulse bg-muted rounded", className)} />
}

// 用户类型选项
const userTypes: { value: NearbyUserType | 'all'; label: string; icon: React.ReactNode }[] = [
  { value: 'all', label: '全部', icon: <Users className="w-4 h-4" /> },
  { value: 'enthusiast', label: '爱好者', icon: <Users className="w-4 h-4" /> },
  { value: 'teacher', label: '老师', icon: <GraduationCap className="w-4 h-4" /> },
  { value: 'inheritor', label: '传承人', icon: <Award className="w-4 h-4" /> },
]

export default function NearbyUsersPage() {
  const router = useRouter()
  
  // 状态
  const [users, setUsers] = useState<NearbyUser[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [selectedType, setSelectedType] = useState<NearbyUserType | 'all'>('all')
  const [searchKeyword, setSearchKeyword] = useState('')
  const [showSettings, setShowSettings] = useState(false)
  const [privacySetting, setPrivacySetting] = useState<LocationPrivacySetting | null>(null)
  const [followingIds, setFollowingIds] = useState<Set<number>>(new Set())
  
  // 当前位置（模拟）
  const [location] = useState({ latitude: 39.9087, longitude: 116.4716 })

  // 加载附近用户
  const loadUsers = useCallback(async (showRefresh = false) => {
    if (showRefresh) setRefreshing(true)
    else setLoading(true)
    
    try {
      const res = await getNearbyUsers({
        latitude: location.latitude,
        longitude: location.longitude,
        type: selectedType,
        radius: 5000,
      })
      if (res.code === 200 && res.data) {
        setUsers(res.data.list)
        // 初始化关注状态
        const following = new Set(res.data.list.filter(u => u.isFollowing).map(u => u.id))
        setFollowingIds(following)
      }
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }, [location, selectedType])

  // 加载隐私设置
  const loadPrivacySetting = useCallback(async () => {
    const res = await getLocationPrivacySetting()
    if (res.code === 200 && res.data) {
      setPrivacySetting(res.data)
    }
  }, [])

  useEffect(() => {
    loadUsers()
    loadPrivacySetting()
  }, [loadUsers, loadPrivacySetting])

  // 处理关注/取关
  const handleToggleFollow = async (userId: number) => {
    const isFollowing = followingIds.has(userId)
    
    if (isFollowing) {
      const res = await unfollowUser(userId)
      if (res.code === 200) {
        setFollowingIds(prev => {
          const next = new Set(prev)
          next.delete(userId)
          return next
        })
      }
    } else {
      const res = await followUser(userId)
      if (res.code === 200) {
        setFollowingIds(prev => new Set(prev).add(userId))
      }
    }
  }

  // 处理隐私设置更新
  const handlePrivacyChange = async (key: keyof LocationPrivacySetting, value: boolean | string | number) => {
    if (!privacySetting) return
    
    const newSetting = { ...privacySetting, [key]: value }
    setPrivacySetting(newSetting)
    await updateLocationPrivacySetting({ [key]: value })
  }

  // 过滤用户（搜索）
  const filteredUsers = users.filter(user => {
    if (!searchKeyword) return true
    const kw = searchKeyword.toLowerCase()
    return (
      user.name.toLowerCase().includes(kw) ||
      user.bio?.toLowerCase().includes(kw) ||
      user.interests.some(i => i.toLowerCase().includes(kw))
    )
  })

  // 类型图标
  const getUserTypeIcon = (type: NearbyUserType) => {
    switch (type) {
      case 'teacher':
        return <GraduationCap className="w-3 h-3" />
      case 'inheritor':
        return <Award className="w-3 h-3" />
      default:
        return <Users className="w-3 h-3" />
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="px-4 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <button onClick={() => router.back()} className="p-1 -ml-1">
                <ChevronLeft className="w-6 h-6" />
              </button>
              <h1 className="text-lg font-semibold">附近的人</h1>
            </div>
            <div className="flex items-center gap-2">
              <button 
                onClick={() => loadUsers(true)}
                className={cn("p-2", refreshing && "animate-spin")}
                disabled={refreshing}
              >
                <RefreshCw className="w-5 h-5 text-muted-foreground" />
              </button>
              <button onClick={() => setShowSettings(true)} className="p-2">
                <Settings className="w-5 h-5 text-muted-foreground" />
              </button>
            </div>
          </div>
        </div>

        {/* 搜索框 */}
        <div className="px-4 pb-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="搜索用户名、兴趣..."
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
              className="pl-9 bg-muted/50 border-0"
            />
          </div>
        </div>

        {/* 类型筛选 */}
        <div className="px-4 pb-3">
          <div className="flex gap-2 overflow-x-auto scrollbar-hide">
            {userTypes.map(type => (
              <button
                key={type.value}
                onClick={() => setSelectedType(type.value)}
                className={cn(
                  "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors",
                  selectedType === type.value
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground"
                )}
              >
                {type.icon}
                {type.label}
              </button>
            ))}
          </div>
        </div>
      </header>

      {/* 用户列表 */}
      <div className="p-4">
        {loading ? (
          <div className="space-y-3">
            {[1, 2, 3, 4].map(i => (
              <div key={i} className="bg-card rounded-xl p-4 border border-border">
                <div className="flex gap-3">
                  <Skeleton className="w-14 h-14 rounded-full flex-shrink-0" />
                  <div className="flex-1 space-y-2">
                    <Skeleton className="h-5 w-24" />
                    <Skeleton className="h-4 w-full" />
                    <div className="flex gap-2">
                      <Skeleton className="h-5 w-12 rounded-full" />
                      <Skeleton className="h-5 w-16 rounded-full" />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : filteredUsers.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
            <MapPin className="w-12 h-12 mb-4 opacity-50" />
            <p className="text-center">
              {searchKeyword ? '没有找到匹配的用户' : '附近暂无用户'}
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {filteredUsers.map(user => {
              const isFollowing = followingIds.has(user.id)
              
              return (
                <div
                  key={user.id}
                  className="bg-card rounded-xl p-4 border border-border"
                >
                  <div className="flex gap-3">
                    {/* 头像 */}
                    <button
                      onClick={() => router.push(`/user/${user.id}`)}
                      className="relative flex-shrink-0"
                    >
                      <img
                        src={user.avatar}
                        alt={user.name}
                        className="w-14 h-14 rounded-full object-cover"
                      />
                      {user.isOnline && (
                        <span className="absolute bottom-0 right-0 w-3.5 h-3.5 bg-green-500 border-2 border-card rounded-full" />
                      )}
                    </button>

                    {/* 信息 */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <button
                          onClick={() => router.push(`/user/${user.id}`)}
                          className="font-medium truncate hover:text-primary"
                        >
                          {user.name}
                        </button>
                        {user.verified && (
                          <BadgeCheck className="w-4 h-4 text-primary flex-shrink-0" />
                        )}
                        <span className={cn(
                          "flex items-center gap-0.5 px-1.5 py-0.5 rounded text-xs",
                          getUserTypeColor(user.type)
                        )}>
                          {getUserTypeIcon(user.type)}
                          {getUserTypeLabel(user.type)}
                        </span>
                      </div>

                      {/* 认证标题 */}
                      {user.verifiedTitle && (
                        <p className="text-xs text-primary mb-1">{user.verifiedTitle}</p>
                      )}

                      {/* 简介 */}
                      {user.bio && (
                        <p className="text-sm text-muted-foreground line-clamp-2 mb-2">
                          {user.bio}
                        </p>
                      )}

                      {/* 兴趣标签 */}
                      <div className="flex flex-wrap gap-1.5 mb-2">
                        {user.commonInterests?.map(interest => (
                          <span
                            key={interest}
                            className="px-2 py-0.5 bg-primary/10 text-primary text-xs rounded-full"
                          >
                            {interest}
                          </span>
                        ))}
                        {user.interests.filter(i => !user.commonInterests?.includes(i)).slice(0, 2).map(interest => (
                          <span
                            key={interest}
                            className="px-2 py-0.5 bg-muted text-muted-foreground text-xs rounded-full"
                          >
                            {interest}
                          </span>
                        ))}
                      </div>

                      {/* 底部信息 */}
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3 text-xs text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <MapPin className="w-3 h-3" />
                            {formatUserDistance(user.distance, user.showExactDistance)}
                          </span>
                          <span>{user.followerCount} 粉丝</span>
                          {user.lastActiveAt && (
                            <span>{user.lastActiveAt}</span>
                          )}
                        </div>

                        {/* 操作按钮 */}
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 w-8 p-0"
                            onClick={() => router.push(`/im/chat/${user.id}`)}
                          >
                            <MessageCircle className="w-4 h-4" />
                          </Button>
                          <Button
                            variant={isFollowing ? "outline" : "default"}
                            size="sm"
                            className="h-8"
                            onClick={() => handleToggleFollow(user.id)}
                          >
                            {isFollowing ? (
                              <>
                                <UserCheck className="w-4 h-4 mr-1" />
                                {user.isMutual ? '互关' : '已关注'}
                              </>
                            ) : (
                              <>
                                <UserPlus className="w-4 h-4 mr-1" />
                                关注
                              </>
                            )}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* 隐私设置弹窗 */}
      {showSettings && privacySetting && (
        <div className="fixed inset-0 z-50 bg-black/50" onClick={() => setShowSettings(false)}>
          <div 
            className="absolute bottom-0 left-0 right-0 bg-background rounded-t-2xl max-h-[70vh] overflow-y-auto"
            onClick={e => e.stopPropagation()}
          >
            <div className="sticky top-0 bg-background border-b border-border px-4 py-3">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold">位置隐私设置</h3>
                <button onClick={() => setShowSettings(false)} className="text-muted-foreground">
                  关闭
                </button>
              </div>
            </div>

            <div className="p-4 space-y-4">
              {/* 附近可见开关 */}
              <div className="flex items-center justify-between py-3 border-b border-border">
                <div className="flex items-center gap-3">
                  {privacySetting.visibleToNearby ? (
                    <Eye className="w-5 h-5 text-primary" />
                  ) : (
                    <EyeOff className="w-5 h-5 text-muted-foreground" />
                  )}
                  <div>
                    <p className="font-medium">对附近的人可见</p>
                    <p className="text-sm text-muted-foreground">
                      开启后，附近的人可以发现你
                    </p>
                  </div>
                </div>
                <Switch
                  checked={privacySetting.visibleToNearby}
                  onCheckedChange={(checked) => handlePrivacyChange('visibleToNearby', checked)}
                />
              </div>

              {/* 距离精度 */}
              <div className="py-3 border-b border-border">
                <p className="font-medium mb-2">距离显示精度</p>
                <div className="flex gap-2">
                  <button
                    onClick={() => handlePrivacyChange('distancePrecision', 'fuzzy')}
                    className={cn(
                      "flex-1 py-2 px-3 rounded-lg text-sm transition-colors",
                      privacySetting.distancePrecision === 'fuzzy'
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted text-muted-foreground"
                    )}
                  >
                    模糊（推荐）
                  </button>
                  <button
                    onClick={() => handlePrivacyChange('distancePrecision', 'exact')}
                    className={cn(
                      "flex-1 py-2 px-3 rounded-lg text-sm transition-colors",
                      privacySetting.distancePrecision === 'exact'
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted text-muted-foreground"
                    )}
                  >
                    精确
                  </button>
                </div>
                <p className="text-xs text-muted-foreground mt-2">
                  模糊模式下，1km内统一显示"附近"
                </p>
              </div>

              {/* 可见范围 */}
              <div className="py-3">
                <p className="font-medium mb-2">可见范围</p>
                <div className="flex gap-2 flex-wrap">
                  {[1, 3, 5, 10, 20].map(range => (
                    <button
                      key={range}
                      onClick={() => handlePrivacyChange('visibleRange', range)}
                      className={cn(
                        "py-2 px-4 rounded-lg text-sm transition-colors",
                        privacySetting.visibleRange === range
                          ? "bg-primary text-primary-foreground"
                          : "bg-muted text-muted-foreground"
                      )}
                    >
                      {range}km
                    </button>
                  ))}
                </div>
                <p className="text-xs text-muted-foreground mt-2">
                  只有在此范围内的用户才能看到你
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// apps/mobile/.backup_vue3_converted/pages/same-city/nearby-users/index.vue
<template>
  <view class="min-h-screen bg-background">
    <!-- 顶部导航 -->
    <header class="sticky top-0 z-10 bg-white border-b border-border">
      <view class="px-4 py-3">
        <view class="flex items-center justify-between">
          <view class="flex items-center gap-3">
            <view @click="goBack" class="p-1 -ml-1">
              <text class="text-xl text-foreground">←</text>
            </view>
            <text class="text-lg font-semibold text-foreground">附近的人</text>
          </view>
          <view class="flex items-center gap-2">
            <view @click="loadUsers(true)" :class="'p-2 ' + (refreshing ? 'animate-spin' : '')">
              <text class="text-lg"></text>
            </view>
            <view @click="showSettings=true" class="p-2">
              <text class="text-lg">⚙️</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 搜索框 -->
      <view class="px-4 pb-3">
        <view class="relative">
          <text class="absolute left-3 top-1/2" style="transform:translateY(-50%)"></text>
          <input
            placeholder="搜索用户名、兴趣..."
            :value="searchKeyword"
            @input="e => searchKeyword=e.detail.value"
            class="w-full h-10 pl-9 pr-3 rounded-lg text-sm bg-background/50 text-foreground"
            style="outline:none;border:none"
          />
        </view>
      </view>

      <!-- 类型筛选 -->
      <view class="px-4 pb-3">
        <view class="flex gap-2" style="overflow-x:auto;white-space:nowrap">
          <view v-for="ut in userTypes" :key="ut.value" @click="selectedType=ut.value" :class="'flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm ' + (selectedType===ut.value ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground')">
            <text class="text-xs">{{ut.icon}}</text>
            <text>{{ut.label}}</text>
          </view>
        </view>
      </view>
    </header>

    <!-- 用户列表 -->
    <view class="p-4">
      <!-- Loading skeleton -->
      <view v-if="loading" class="space-y-3">
        <view v-for="i in 4" :key="i" class="bg-white rounded-xl p-4 border border-border">
          <view class="flex gap-3">
            <view class="w-14 h-14 rounded-full bg-[#E8E0D5] animate-pulse" style="flex-shrink:0" />
            <view class="flex-1 space-y-2">
              <view class="h-5 bg-[#E8E0D5] rounded animate-pulse" style="width:96rpx" />
              <view class="h-4 bg-[#E8E0D5] rounded animate-pulse" style="width:100%" />
              <view class="flex gap-2">
                <view class="h-5 bg-[#E8E0D5] rounded-full animate-pulse" style="width:96rpx" />
                <view class="h-5 bg-[#E8E0D5] rounded-full animate-pulse" style="width:128rpx" />
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- Empty state -->
      <view v-else-if="filteredUsers.length===0" class="flex flex-col items-center justify-center py-20">
        <text class="text-3xl text-muted-foreground mb-4">📍</text>
        <text class="text-sm text-muted-foreground text-center">{{searchKeyword ? '没有找到匹配的用户' : '附近暂无用户'}}</text>
      </view>

      <!-- User list -->
      <view v-else class="space-y-3">
        <view v-for="user in filteredUsers" :key="user.id" class="bg-white rounded-xl p-4 border border-border">
          <view class="flex gap-3">
            <!-- 头像 -->
            <view @click="navigateToUser(user.id)" class="relative" style="flex-shrink:0">
              <image :src="user.avatar" class="w-14 h-14 rounded-full" mode="aspectFill" />
              <view v-if="user.isOnline" class="absolute bottom-0 right-0 w-3.5 h-3.5 rounded-full border-2 border-white" style="background-color:#22c55e" />
            </view>

            <!-- 信息 -->
            <view class="flex-1" style="min-width:0">
              <view class="flex items-center gap-2 mb-1">
                <view @click="navigateToUser(user.id)" class="font-medium text-foreground">
                  <text>{{user.name}}</text>
                </view>
                <text v-if="user.verified" class="text-primary text-sm">✓</text>
                <text :class="'flex items-center gap-0.5 px-1.5 py-0.5 rounded text-xs ' + getUserTypeColor(user.type)">
                  {{getUserTypeIcon(user.type)}} {{getUserTypeLabel(user.type)}}
                </text>
              </view>

              <!-- 认证标题 -->
              <text v-if="user.verifiedTitle" class="text-xs text-primary mb-1" style="display:block">{{user.verifiedTitle}}</text>

              <!-- 简介 -->
              <text v-if="user.bio" class="text-sm text-muted-foreground mb-2" style="display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;display:block">{{user.bio}}</text>

              <!-- 兴趣标签 -->
              <view class="flex flex-wrap gap-1.5 mb-2">
                <text v-for="interest in user.commonInterests" :key="interest" class="px-2 py-0.5 text-xs rounded-full" style="background-color:#C41E3A/10;color:#C41E3A">{{interest}}</text>
                <text v-for="interest in user.interests.filter((i:string)=>!user.commonInterests?.includes(i)).slice(0,2)" :key="interest" class="px-2 py-0.5 text-xs rounded-full bg-secondary text-muted-foreground">{{interest}}</text>
              </view>

              <!-- 底部信息 -->
              <view class="flex items-center justify-between">
                <view class="flex items-center gap-3 text-xs text-muted-foreground">
                  <text class="flex items-center gap-1">📍 {{formatUserDistance(user.distance, user.showExactDistance)}}</text>
                  <text>{{user.followerCount}} 粉丝</text>
                  <text v-if="user.lastActiveAt">{{user.lastActiveAt}}</text>
                </view>

                <!-- 操作按钮 -->
                <view class="flex items-center gap-2">
                  <view @click="navigateToChat(user.id)" class="w-8 h-8 rounded-full flex items-center justify-center">
                    <text class="text-sm"></text>
                  </view>
                  <view @click="handleToggleFollow(user.id)" :class="'h-8 px-3 rounded-full text-xs font-medium flex items-center gap-1 ' + (followingIds.includes(user.id) ? 'border border-border text-foreground' : 'bg-primary text-white')">
                    <text>{{followingIds.includes(user.id) ? '✓ 已关注' : '+ 关注'}}</text>
                  </view>
                </view>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 隐私设置弹窗 -->
    <view v-if="showSettings" class="fixed inset-0 z-50 bg-black/50" @click="showSettings=false">
      <view class="absolute bottom-0 left-0 right-0 bg-white rounded-t-2xl" style="max-height:70vh;overflow-y:auto" @click.stop>
        <view class="sticky top-0 bg-white border-b border-border px-4 py-3">
          <view class="flex items-center justify-between">
            <text class="font-semibold text-foreground">位置隐私设置</text>
            <view @click="showSettings=false" class="text-muted-foreground">
              <text>关闭</text>
            </view>
          </view>
        </view>

        <view class="p-4 space-y-4">
          <!-- 附近可见开关 -->
          <view class="flex items-center justify-between py-3 border-b border-border">
            <view class="flex items-center gap-3">
              <text class="text-lg">{{privacySetting.visibleToNearby ? '' : '‍🗨'}}</text>
              <view>
                <text class="font-medium text-foreground" style="display:block">对附近的人可见</text>
                <text class="text-sm text-muted-foreground" style="display:block">开启后，附近的人可以发现你</text>
              </view>
            </view>
            <switch :checked="privacySetting.visibleToNearby" @change="e => handlePrivacyChange('visibleToNearby', e.detail.value)" />
          </view>

          <!-- 距离精度 -->
          <view class="py-3 border-b border-border">
            <text class="font-medium text-foreground mb-2" style="display:block">距离显示精度</text>
            <view class="flex gap-2">
              <view @click="handlePrivacyChange('distancePrecision','fuzzy')" :class="'flex-1 py-2 px-3 rounded-lg text-sm text-center ' + (privacySetting.distancePrecision==='fuzzy' ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground')">
                <text>模糊（推荐）</text>
              </view>
              <view @click="handlePrivacyChange('distancePrecision','exact')" :class="'flex-1 py-2 px-3 rounded-lg text-sm text-center ' + (privacySetting.distancePrecision==='exact' ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground')">
                <text>精确</text>
              </view>
            </view>
            <text class="text-xs text-muted-foreground mt-2" style="display:block">模糊模式下，1km内统一显示"附近"</text>
          </view>

          <!-- 可见范围 -->
          <view class="py-3">
            <text class="font-medium text-foreground mb-2" style="display:block">可见范围</text>
            <view class="flex gap-2 flex-wrap">
              <view v-for="range in [1,3,5,10,20]" :key="range" @click="handlePrivacyChange('visibleRange',range)" :class="'py-2 px-4 rounded-lg text-sm ' + (privacySetting.visibleRange===range ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground')">
                <text>{{range}}km</text>
              </view>
            </view>
            <text class="text-xs text-muted-foreground mt-2" style="display:block">只有在此范围内的用户才能看到你</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

const userTypes = [
  { value: 'all', label: '全部', icon: '' },
  { value: 'enthusiast', label: '爱好者', icon: '' },
  { value: 'teacher', label: '老师', icon: '🎓' },
  { value: 'inheritor', label: '传承人', icon: '' },
]

const users = ref<any[]>([])
const loading = ref(true)
const refreshing = ref(false)
const selectedType = ref<string>('all')
const searchKeyword = ref('')
const showSettings = ref(false)
const privacySetting = ref<any>({
  visibleToNearby: true,
  distancePrecision: 'fuzzy',
  visibleRange: 5
})
const followingIds = ref<number[]>([])
const location = ref({ latitude: 39.9087, longitude: 116.4716 })

onMounted(() => {
  loadUsers()
})

function loadUsers(showRefresh = false) {
  if (showRefresh) refreshing.value = true
  else loading.value = true

  setTimeout(() => {
    // Mock data
    users.value = [
      { id: 1, name: '易学大师', avatar: '', isOnline: true, verified: true, verifiedTitle: '认证命理师', type: 'teacher', bio: '专注八字命理研究20年', interests: ['八字命理', '紫微斗数'], commonInterests: ['八字命理'], distance: 500, showExactDistance: false, followerCount: 1280, lastActiveAt: '最近在线' },
      { id: 2, name: '风水实践派', avatar: '', isOnline: true, verified: true, type: 'inheritor', bio: '杨公风水第38代传人', interests: ['风水堪舆', '阳宅布局'], commonInterests: [], distance: 1200, showExactDistance: false, followerCount: 856, lastActiveAt: '1小时前' },
      { id: 3, name: '国学爱好者小王', avatar: '', isOnline: false, verified: false, type: 'enthusiast', bio: '刚入门，请多关照', interests: ['八字命理', '梅花易数', '国学经典'], commonInterests: ['八字命理'], distance: 2500, showExactDistance: false, followerCount: 56, lastActiveAt: '昨天' },
      { id: 4, name: '玄学研究员', avatar: '', isOnline: true, verified: false, type: 'enthusiast', bio: '万物皆数，探索宇宙奥秘', interests: ['奇门遁甲', '六爻占卜'], commonInterests: [], distance: 800, showExactDistance: false, followerCount: 234, lastActiveAt: '10分钟前' },
    ]
    loading.value = false
    refreshing.value = false
  }, 500)
}

const filteredUsers = computed(() => {
  let list = users.value
  if (selectedType.value !== 'all') {
    list = list.filter(u => u.type === selectedType.value)
  }
  if (searchKeyword.value) {
    const kw = searchKeyword.value.toLowerCase()
    list = list.filter(u =>
      u.name.toLowerCase().includes(kw) ||
      (u.bio && u.bio.toLowerCase().includes(kw)) ||
      u.interests.some((i: string) => i.toLowerCase().includes(kw))
    )
  }
  return list
})

function getUserTypeColor(type: string) {
  switch (type) {
    case 'teacher': return 'bg-blue-100 text-blue-800'
    case 'inheritor': return 'bg-yellow-100 text-yellow-800'
    default: return 'bg-gray-100 text-gray-800'
  }
}

function getUserTypeLabel(type: string) {
  switch (type) {
    case 'teacher': return '老师'
    case 'inheritor': return '传承人'
    default: return '爱好者'
  }
}

function getUserTypeIcon(type: string) {
  switch (type) {
    case 'teacher': return '🎓'
    case 'inheritor': return ''
    default: return ''
  }
}

function formatUserDistance(distance: number, showExact?: boolean) {
  if (!showExact && distance < 1000) return '附近'
  if (distance < 1000) return `${distance}m`
  return `${(distance / 1000).toFixed(1)}km`
}

function handleToggleFollow(userId: number) {
  const idx = followingIds.value.indexOf(userId)
  if (idx > -1) {
    followingIds.value.splice(idx, 1)
  } else {
    followingIds.value.push(userId)
  }
}

function handlePrivacyChange(key: string, value: any) {
  privacySetting.value[key] = value
}

function navigateToUser(userId: number) {
  uni.navigateTo({ url: `/pages/user/${userId}/index` })
}

function navigateToChat(userId: number) {
  uni.navigateTo({ url: `/pages/message/chat/${userId}/index` })
}

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
/* 样式由 Tailwind 处理 */
</style>
