// apps/mobile/src/pages_backup_20260609/cart/index.vue
<template>
  <view class="cart-page">
    <view class="header-sticky">
      <view class="header-row">
        <text class="header-back" @click="uni.navigateBack()">‹</text>
        <text class="header-title">购物车({{ totalCount }})</text>
        <text class="header-edit" @click="isEditing = !isEditing">{{ isEditing ? '完成' : '编辑' }}</text>
      </view>
    </view>

    <view v-if="loading" class="load-area">
      <LoadingSkeleton v-for="i in 2" :key="i" type="card" />
    </view>

    <view v-else-if="empty" class="empty-wrap">
      <view class="empty-icon">🛒</view>
      <text class="empty-title">购物车是空的</text>
      <text class="empty-desc">快去挑选心仪的商品吧</text>
      <view class="empty-btn" @click="goPage('/pages/discover/index')">去逛逛</view>
      <view class="recommend-section">
        <view class="section-head">
          <text class="section-title">热门推荐</text>
          <text class="section-more" @click="goPage('/pages/mall/index')">更多</text>
        </view>
        <view class="recommend-grid">
          <view v-for="p in recommendProducts" :key="p.id" class="recommend-card">
            <view class="recommend-img">🛍</view>
            <text class="recommend-name">{{ p.name }}</text>
            <text class="recommend-price">¥{{ p.price }}</text>
          </view>
        </view>
      </view>
    </view>

    <view v-else class="cart-body">
      <view v-if="saved > 0 && !isEditing" class="save-tip">
        <text class="save-text">已为您节省 ¥{{ saved }}</text>
        <text class="save-link">领更多优惠券 ›</text>
      </view>

      <view v-for="group in groups" :key="group.id" class="shop-card">
        <view class="shop-header">
          <view class="shop-info">
            <view class="shop-avatar">{{ group.sellerName[0] }}</view>
            <text class="shop-name">{{ group.sellerName }}</text>
            <text class="shop-tag">{{ group.sellerType === 'circle' ? '圈子' : '驿站' }}</text>
          </view>
          <text class="shop-arrow">›</text>
        </view>

        <view v-for="item in group.items" :key="item.id" class="cart-item">
          <view class="item-left">
            <text v-if="isEditing" class="item-del" @click="removeItem(group.id, item.id)">🗑</text>
            <view v-else class="item-check" :class="{ on: sel.has(item.id) }" @click="toggleSel(item.id)">
              <text v-if="sel.has(item.id)" class="check-mark">✓</text>
            </view>
          </view>
          <view class="item-img-wrap">
            <image v-if="item.image" :src="item.image" class="item-img" mode="aspectFill" />
            <text v-else class="item-img-fb">📦</text>
          </view>
          <view class="item-info">
            <text class="item-name">{{ item.name }}</text>
            <text class="item-spec">{{ item.spec }}</text>
            <view class="item-bottom">
              <view class="price-row">
                <text class="price">¥{{ item.price }}</text>
                <text v-if="item.originalPrice > item.price" class="price-old">¥{{ item.originalPrice }}</text>
              </view>
              <view v-if="item.type === 'product'" class="qty-ctrl">
                <text class="qty-btn" @click="changeQty(group.id, item.id, -1)">−</text>
                <text class="qty-num">{{ item.quantity }}</text>
                <text class="qty-btn" @click="changeQty(group.id, item.id, 1)">+</text>
              </view>
            </view>
          </view>
        </view>

        <view v-if="groupFreeDiff(group) > 0 && groupSelTotal(group) > 0" class="free-ship-hint">
          <text class="hint-text">再买 ¥{{ groupFreeDiff(group) }} 即可享受包邮</text>
          <text class="hint-link" @click="goPage('/pages/mall/index')">去凑单 ›</text>
        </view>

        <view class="shop-sub">
          <text class="sub-label">小计：</text>
          <text class="sub-val">¥{{ groupSelTotal(group) }}</text>
        </view>
      </view>

      <view v-if="invalidItems.length" class="invalid-card">
        <view class="invalid-head">
          <text class="invalid-title">失效商品({{ invalidItems.length }})</text>
          <text class="invalid-clear" @click="invalidItems = []">清空</text>
        </view>
        <view v-for="it in invalidItems" :key="it.id" class="invalid-item">
          <view class="invalid-img-wrap">
            <image v-if="it.image" :src="it.image" class="invalid-img" mode="aspectFill" />
            <view class="invalid-overlay"><text class="invalid-tag">失效</text></view>
          </view>
          <view class="invalid-info">
            <text class="invalid-name">{{ it.name }}</text>
            <text class="invalid-reason">{{ it.reason }}</text>
            <text class="invalid-price">¥{{ it.price }}</text>
          </view>
        </view>
      </view>

      <view class="recommend-row">
        <text class="section-title">为你推荐</text>
        <scroll-view scroll-x class="rec-scroll" :show-scrollbar="false">
          <view v-for="p in recommendProducts" :key="p.id" class="rec-chip">
            <view class="rec-img">🛍</view>
            <text class="rec-name">{{ p.name }}</text>
            <text class="rec-price">¥{{ p.price }}</text>
          </view>
        </scroll-view>
      </view>
    </view>

    <view v-if="!loading && !empty" class="bottom-bar">
      <view class="bottom-left" @click="toggleAll">
        <view class="dot" :class="{ on: allSelected }">
          <text v-if="allSelected" class="check-mark">✓</text>
        </view>
        <text class="all-text">全选</text>
      </view>
      <view class="bottom-right">
        <template v-if="isEditing">
          <view class="action-btn" :class="{ off: sel.size === 0 }" @click="batchRemove">
            <text>删除({{ sel.size }})</text>
          </view>
        </template>
        <template v-else>
          <view class="total-block">
            <view class="total-line">
              <text class="total-label">合计:</text>
              <text class="total-num">¥{{ totalPrice }}</text>
            </view>
            <text v-if="saved > 0" class="total-old">¥{{ originalPrice }}</text>
          </view>
          <view class="action-btn" :class="{ off: sel.size === 0 }" @click="goCheckout">
            <text>结算({{ totalCount }})</text>
          </view>
        </template>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import LoadingSkeleton from '../../components/LoadingSkeleton.vue'

interface CartItem {
  id: number; name: string; spec: string; price: number
  originalPrice: number; quantity: number; image: string; type: string
}

const loading = ref(true)
const empty = ref(false)
const isEditing = ref(false)

const groups = reactive([
  {
    id: 1, sellerName: '易道书院', sellerType: 'circle', freeShippingThreshold: 199,
    items: [
      { id: 1, name: '《渊海子平》精装典藏版', spec: '精装版 / 全三册', price: 168, originalPrice: 298, quantity: 1, image: '', type: 'product' },
      { id: 2, name: '八字命理入门到精通', spec: '视频课程 / 共36节', price: 299, originalPrice: 599, quantity: 1, image: '', type: 'course' },
    ],
  },
  {
    id: 2, sellerName: '玄学文创旗舰店', sellerType: 'store', freeShippingThreshold: 99,
    items: [
      { id: 3, name: '天然黑曜石貔貅手链', spec: '14mm / 男款', price: 128, originalPrice: 199, quantity: 2, image: '', type: 'product' },
    ],
  },
])

const invalidItems = ref([
  { id: 101, name: '限量版紫水晶摆件', spec: '已下架', price: 388, image: '', reason: '商品已下架' },
])

const recommendProducts = [
  { id: 1, name: '紫微斗数全书', price: 88 },
  { id: 2, name: '开光铜钱挂件', price: 68 },
  { id: 3, name: '风水罗盘专业版', price: 268 },
  { id: 4, name: '命理学基础课', price: 199 },
]

const sel = ref(new Set<number>())

const totalPrice = computed(() => {
  let s = 0
  groups.forEach(g => g.items.forEach(i => { if (sel.value.has(i.id)) s += i.price * i.quantity }))
  return s.toFixed(2)
})
const originalPrice = computed(() => {
  let s = 0
  groups.forEach(g => g.items.forEach(i => { if (sel.value.has(i.id)) s += i.originalPrice * i.quantity }))
  return s.toFixed(2)
})
const saved = computed(() => (Number(originalPrice.value) - Number(totalPrice.value)).toFixed(2))
const totalCount = computed(() => {
  let c = 0
  groups.forEach(g => g.items.forEach(i => { if (sel.value.has(i.id)) c += i.quantity }))
  return c
})
const allSelected = computed(() => {
  let n = 0; groups.forEach(g => n += g.items.length)
  return sel.value.size === n && n > 0
})

function groupSelTotal(g: typeof groups[0]) {
  return g.items.reduce((s, i) => sel.value.has(i.id) ? s + i.price * i.quantity : s, 0).toFixed(2)
}
function groupFreeDiff(g: typeof groups[0]) {
  return Math.max(0, (g.freeShippingThreshold || 0) - Number(groupSelTotal(g)))
}

function toggleAll() {
  if (allSelected.value) { sel.value = new Set(); return }
  const ids = new Set<number>(); groups.forEach(g => g.items.forEach(i => ids.add(i.id)))
  sel.value = ids
}
function toggleSel(id: number) {
  const n = new Set(sel.value); n.has(id) ? n.delete(id) : n.add(id); sel.value = n
}
function changeQty(gid: number, iid: number, d: number) {
  const g = groups.find(x => x.id === gid)
  const item = g?.items.find(x => x.id === iid)
  if (item) item.quantity = Math.max(1, item.quantity + d)
}
function removeItem(gid: number, iid: number) {
  const gi = groups.findIndex(x => x.id === gid)
  if (gi < 0) return
  groups[gi].items = groups[gi].items.filter(x => x.id !== iid)
  if (groups[gi].items.length === 0) { groups.splice(gi, 1); if (groups.length === 0) empty.value = true }
  const n = new Set(sel.value); n.delete(iid); sel.value = n
}
function batchRemove() {
  if (sel.value.size === 0) return
  for (let i = groups.length - 1; i >= 0; i--) {
    groups[i].items = groups[i].items.filter(x => !sel.value.has(x.id))
    if (groups[i].items.length === 0) groups.splice(i, 1)
  }
  sel.value = new Set(); isEditing.value = false
  if (groups.length === 0) empty.value = true
}
function goCheckout() { if (sel.value.size) uni.navigateTo({ url: '/pages/checkout/index' }) }
function goPage(url: string) { uni.navigateTo({ url }) }

setTimeout(() => {
  const ids = new Set<number>(); groups.forEach(g => g.items.forEach(i => ids.add(i.id)))
  sel.value = ids; loading.value = false
}, 500)
</script>

<style scoped>
.cart-page { min-height: 100vh; background: #FAF8F5; padding-bottom: 120rpx; }
.header-sticky { position: sticky; top: 0; z-index: 30; background: rgba(250,248,245,0.95); backdrop-filter: blur(12rpx); border-bottom: 1px solid #E8E0D5; }
.header-row { display: flex; align-items: center; padding: 0 24rpx; height: 88rpx; }
.header-back { font-size: 48rpx; color: #333; width: 64rpx; }
.header-title { flex: 1; font-size: 34rpx; font-weight: 700; color: #2C2C2C; }
.header-edit { font-size: 26rpx; color: #C41E3A; font-weight: 500; }
.load-area { padding: 24rpx; }

.empty-wrap { display: flex; flex-direction: column; align-items: center; padding: 120rpx 48rpx; }
.empty-icon { font-size: 96rpx; margin-bottom: 24rpx; }
.empty-title { font-size: 32rpx; font-weight: 500; color: #2C2C2C; margin-bottom: 8rpx; }
.empty-desc { font-size: 26rpx; color: #999; margin-bottom: 32rpx; }
.empty-btn { padding: 16rpx 48rpx; border-radius: 40rpx; background: #C41E3A; color: #fff; font-size: 28rpx; font-weight: 500; }

.recommend-section { width: 100%; margin-top: 60rpx; }
.section-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16rpx; }
.section-title { font-size: 28rpx; font-weight: 600; color: #2C2C2C; }
.section-more { font-size: 24rpx; color: #C41E3A; }
.recommend-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12rpx; }
.recommend-card { background: #fff; border-radius: 16rpx; padding: 16rpx; box-shadow: 0 2rpx 12rpx rgba(0,0,0,0.06); }
.recommend-img { width: 100%; aspect-ratio: 1; border-radius: 12rpx; background: #F5F1EB; display: flex; align-items: center; justify-content: center; font-size: 48rpx; }
.recommend-name { font-size: 24rpx; color: #333; margin-top: 8rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.recommend-price { font-size: 24rpx; color: #C41E3A; font-weight: 500; margin-top: 4rpx; }

.cart-body { padding: 16rpx 24rpx; }
.save-tip { margin-bottom: 16rpx; padding: 16rpx 24rpx; border-radius: 16rpx; background: rgba(196,30,58,0.08); display: flex; justify-content: space-between; align-items: center; }
.save-text { font-size: 24rpx; color: #C41E3A; }
.save-link { font-size: 24rpx; color: #C41E3A; }

.shop-card { background: #fff; border-radius: 20rpx; padding: 24rpx; margin-bottom: 16rpx; box-shadow: 0 2rpx 12rpx rgba(0,0,0,0.06); }
.shop-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20rpx; padding-bottom: 16rpx; border-bottom: 1px solid #F0EDE5; }
.shop-info { display: flex; align-items: center; gap: 12rpx; }
.shop-avatar { width: 48rpx; height: 48rpx; border-radius: 50%; background: rgba(196,30,58,0.1); color: #C41E3A; display: flex; align-items: center; justify-content: center; font-size: 22rpx; font-weight: 600; }
.shop-name { font-size: 28rpx; font-weight: 500; color: #2C2C2C; }
.shop-tag { font-size: 20rpx; color: #999; background: #F5F1EB; padding: 2rpx 12rpx; border-radius: 8rpx; }
.shop-arrow { font-size: 36rpx; color: #999; }

.cart-item { display: flex; gap: 16rpx; padding: 16rpx 0; }
.cart-item + .cart-item { border-top: 1px solid #F5F1EB; }
.item-left { display: flex; align-items: center; flex-shrink: 0; }
.item-check { width: 40rpx; height: 40rpx; border-radius: 50%; border: 3rpx solid #CCC; display: flex; align-items: center; justify-content: center; }
.item-check.on { background: #C41E3A; border-color: #C41E3A; }
.check-mark { font-size: 24rpx; color: #fff; font-weight: 700; }
.item-del { font-size: 36rpx; }

.item-img-wrap { width: 160rpx; height: 160rpx; border-radius: 16rpx; overflow: hidden; flex-shrink: 0; background: linear-gradient(135deg, #F5F0E8, #EDE5D5); }
.item-img { width: 100%; height: 100%; }
.item-img-fb { width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; font-size: 48rpx; }
.item-info { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.item-name { font-size: 26rpx; font-weight: 500; color: #333; display: -webkit-box; -webkit-line-clamp: 1; -webkit-box-orient: vertical; overflow: hidden; }
.item-spec { font-size: 22rpx; color: #999; margin-top: 4rpx; }
.item-bottom { display: flex; justify-content: space-between; align-items: center; margin-top: auto; }
.price-row { display: flex; align-items: baseline; gap: 8rpx; }
.price { font-size: 32rpx; font-weight: 700; color: #C41E3A; }
.price-old { font-size: 22rpx; color: #999; text-decoration: line-through; }
.qty-ctrl { display: flex; align-items: center; background: #F5F1EB; border-radius: 32rpx; }
.qty-btn { width: 52rpx; height: 52rpx; display: flex; align-items: center; justify-content: center; font-size: 28rpx; color: #666; }
.qty-num { min-width: 52rpx; text-align: center; font-size: 28rpx; font-weight: 500; color: #333; }

.free-ship-hint { margin-top: 16rpx; padding: 16rpx 20rpx; border-radius: 12rpx; background: rgba(201,169,110,0.1); display: flex; justify-content: space-between; align-items: center; }
.hint-text { font-size: 22rpx; color: #C9A96E; }
.hint-link { font-size: 22rpx; color: #C9A96E; font-weight: 500; }

.shop-sub { display: flex; justify-content: flex-end; margin-top: 16rpx; padding-top: 16rpx; border-top: 1px solid #F0EDE5; }
.sub-label { font-size: 24rpx; color: #999; }
.sub-val { font-size: 28rpx; font-weight: 600; color: #2C2C2C; }

.invalid-card { background: rgba(255,255,255,0.6); border-radius: 20rpx; padding: 24rpx; margin-bottom: 16rpx; border: 2rpx dashed #E8E0D5; }
.invalid-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16rpx; }
.invalid-title { font-size: 26rpx; color: #999; }
.invalid-clear { font-size: 24rpx; color: #C41E3A; }
.invalid-item { display: flex; gap: 16rpx; opacity: 0.6; margin-bottom: 12rpx; }
.invalid-img-wrap { width: 128rpx; height: 128rpx; border-radius: 12rpx; overflow: hidden; flex-shrink: 0; position: relative; background: #F5F1EB; }
.invalid-img { width: 100%; height: 100%; }
.invalid-overlay { position: absolute; inset: 0; background: rgba(0,0,0,0.3); display: flex; align-items: center; justify-content: center; }
.invalid-tag { font-size: 20rpx; color: #fff; background: rgba(0,0,0,0.5); padding: 2rpx 12rpx; border-radius: 6rpx; }
.invalid-info { flex: 1; min-width: 0; }
.invalid-name { font-size: 26rpx; color: #999; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block; }
.invalid-reason { font-size: 22rpx; color: #C41E3A; margin-top: 4rpx; }
.invalid-price { font-size: 22rpx; color: #999; text-decoration: line-through; margin-top: 4rpx; }

.recommend-row { margin-top: 8rpx; }
.rec-scroll { white-space: nowrap; margin-top: 12rpx; }
.rec-chip { display: inline-flex; flex-direction: column; width: 200rpx; background: #fff; border-radius: 16rpx; padding: 12rpx; margin-right: 12rpx; box-shadow: 0 2rpx 12rpx rgba(0,0,0,0.06); }
.rec-img { width: 100%; aspect-ratio: 1; border-radius: 12rpx; background: #F5F1EB; display: flex; align-items: center; justify-content: center; font-size: 40rpx; }
.rec-name { font-size: 22rpx; color: #333; margin-top: 8rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.rec-price { font-size: 22rpx; color: #C41E3A; font-weight: 500; margin-top: 4rpx; }

.bottom-bar { position: fixed; bottom: 0; left: 0; right: 0; z-index: 50; background: rgba(255,255,255,0.95); backdrop-filter: blur(12rpx); border-top: 1px solid #E8E0D5; display: flex; align-items: center; justify-content: space-between; padding: 12rpx 24rpx; padding-bottom: calc(12rpx + env(safe-area-inset-bottom)); }
.bottom-left { display: flex; align-items: center; gap: 12rpx; }
.dot { width: 40rpx; height: 40rpx; border-radius: 50%; border: 3rpx solid #CCC; display: flex; align-items: center; justify-content: center; }
.dot.on { background: #C41E3A; border-color: #C41E3A; }
.all-text { font-size: 26rpx; color: #2C2C2C; }
.bottom-right { display: flex; align-items: center; gap: 24rpx; }
.total-block { text-align: right; }
.total-line { display: flex; align-items: baseline; gap: 4rpx; }
.total-label { font-size: 24rpx; color: #999; }
.total-num { font-size: 36rpx; font-weight: 700; color: #C41E3A; }
.total-old { font-size: 20rpx; color: #999; text-decoration: line-through; display: block; }
.action-btn { padding: 16rpx 40rpx; border-radius: 40rpx; background: #C41E3A; color: #fff; font-size: 28rpx; font-weight: 500; }
.action-btn.off { opacity: 0.5; background: #CCC; }
</style>

// v0-reference/app/cart/page.tsx
"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Minus, Plus, Trash2, ShoppingCart, ChevronRight, Check } from "lucide-react"
import { BackButton } from "@/components/common/back-button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { cn } from "@/lib/utils"

// 模拟购物车数据
const cartGroups = [
  {
    id: 1,
    sellerName: "易道书院",
    sellerAvatar: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=100&q=80",
    sellerType: "circle",
    freeShippingThreshold: 199, // 满199包邮
    items: [
      {
        id: 1,
        name: "《渊海子平》精装典藏版",
        spec: "精装版 / 全三册",
        price: 168,
        originalPrice: 298,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200&q=80",
        type: "product"
      },
      {
        id: 2,
        name: "八字命理入门到精通",
        spec: "视频课程 / 共36节",
        price: 299,
        originalPrice: 599,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=200&q=80",
        type: "course"
      }
    ]
  },
  {
    id: 2,
    sellerName: "玄学文创旗舰店",
    sellerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    sellerType: "store",
    freeShippingThreshold: 99, // 满99包邮
    items: [
      {
        id: 3,
        name: "天然黑曜石貔貅手链",
        spec: "14mm / 男款",
        price: 128,
        originalPrice: 199,
        quantity: 2,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=200&q=80",
        type: "product"
      }
    ]
  }
]

// 失效商品
const invalidItems = [
  {
    id: 101,
    name: "限量版紫水晶摆件",
    spec: "已下架",
    price: 388,
    image: "https://images.unsplash.com/photo-1600721391689-2564bb8055de?w=200&q=80",
    reason: "商品已下架"
  }
]

const recommendProducts = [
  { id: 1, name: "紫微斗数全书", price: 88, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200&q=80" },
  { id: 2, name: "开光铜钱挂件", price: 68, image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=200&q=80" },
  { id: 3, name: "风水罗盘专业版", price: 268, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
  { id: 4, name: "命理学基础课", price: 199, image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=200&q=80" },
]

// 骨架屏组件
function CartSkeleton() {
  return (
    <div className="space-y-4 p-4">
      {[1, 2].map((group) => (
        <Card key={group} className="p-4 bg-card animate-pulse">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-6 h-6 rounded-full bg-secondary" />
            <div className="h-4 w-24 bg-secondary rounded" />
          </div>
          {[1, 2].map((item) => (
            <div key={item} className="flex gap-3 py-3 border-t border-border/50">
              <div className="w-5 h-5 rounded bg-secondary" />
              <div className="w-20 h-20 rounded-lg bg-secondary" />
              <div className="flex-1 space-y-2">
                <div className="h-4 w-3/4 bg-secondary rounded" />
                <div className="h-3 w-1/2 bg-secondary rounded" />
                <div className="h-4 w-16 bg-secondary rounded" />
              </div>
            </div>
          ))}
        </Card>
      ))}
    </div>
  )
}

// 空状态组件
function EmptyCart() {
  return (
    <div className="flex flex-col items-center justify-center py-20 px-4">
      <div className="w-24 h-24 rounded-full bg-secondary/50 flex items-center justify-center mb-4">
        <ShoppingCart className="w-12 h-12 text-muted-foreground/50" />
      </div>
      <h3 className="text-lg font-medium text-foreground mb-1">购物车是空的</h3>
      <p className="text-sm text-muted-foreground mb-6">快去挑选心仪的商品吧</p>
      <Link
        href="/discover"
        className="px-6 py-2.5 bg-primary text-primary-foreground text-sm font-medium rounded-full hover:bg-primary/90 transition-colors"
      >
        去逛逛
      </Link>
      
      {/* 热门推荐 */}
      <div className="w-full mt-10">
        <div className="flex items-center justify-between mb-3">
          <h4 className="text-sm font-medium text-foreground">热门推荐</h4>
          <Link href="/mall" className="text-xs text-primary">更多</Link>
        </div>
        <div className="grid grid-cols-2 gap-3">
          {recommendProducts.slice(0, 4).map((product) => (
            <Link key={product.id} href={`/mall/product/${product.id}`}>
              <Card className="p-3 bg-card hover:bg-secondary/50 transition-colors cursor-pointer">
                <div className="aspect-square rounded-lg bg-secondary mb-2 flex items-center justify-center">
                  <ShoppingCart className="w-8 h-8 text-muted-foreground/30" />
                </div>
                <h5 className="text-sm text-foreground line-clamp-1">{product.name}</h5>
                <p className="text-sm text-primary font-medium mt-1">¥{product.price}</p>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}

export default function CartPage() {
  const router = useRouter()
  const [isLoading, setIsLoading] = useState(true)
  const [isEditing, setIsEditing] = useState(false)
  const [groups, setGroups] = useState(cartGroups)
  const [selectedItems, setSelectedItems] = useState<Set<number>>(new Set())
  const [isEmpty, setIsEmpty] = useState(false)
  
  useEffect(() => {
    // 模拟加载
    const timer = setTimeout(() => {
      setIsLoading(false)
      // 初始全选
      const allIds = new Set<number>()
      groups.forEach(g => g.items.forEach(item => allIds.add(item.id)))
      setSelectedItems(allIds)
    }, 1000)
    return () => clearTimeout(timer)
  }, [])
  
  // 计算总价
  const calculateTotal = () => {
    let total = 0
    let originalTotal = 0
    let count = 0
    groups.forEach(group => {
      group.items.forEach(item => {
        if (selectedItems.has(item.id)) {
          total += item.price * item.quantity
          originalTotal += item.originalPrice * item.quantity
          count += item.quantity
        }
      })
    })
    return { total, originalTotal, count, saved: originalTotal - total }
  }
  
  const { total, originalTotal, count, saved } = calculateTotal()
  
  // 全选/取消全选
  const handleSelectAll = () => {
    if (isAllSelected()) {
      setSelectedItems(new Set())
    } else {
      const allIds = new Set<number>()
      groups.forEach(g => g.items.forEach(item => allIds.add(item.id)))
      setSelectedItems(allIds)
    }
  }
  
  const isAllSelected = () => {
    let totalItems = 0
    groups.forEach(g => totalItems += g.items.length)
    return selectedItems.size === totalItems && totalItems > 0
  }
  
  // 切换选中状态
  const toggleItem = (id: number) => {
    const newSelected = new Set(selectedItems)
    if (newSelected.has(id)) {
      newSelected.delete(id)
    } else {
      newSelected.add(id)
    }
    setSelectedItems(newSelected)
  }
  
  // 修改数量
  const updateQuantity = (groupId: number, itemId: number, delta: number) => {
    setGroups(prev => prev.map(group => {
      if (group.id === groupId) {
        return {
          ...group,
          items: group.items.map(item => {
            if (item.id === itemId) {
              const newQty = Math.max(1, item.quantity + delta)
              return { ...item, quantity: newQty }
            }
            return item
          })
        }
      }
      return group
    }))
  }
  
  // 删除商品
  const removeItem = (groupId: number, itemId: number) => {
    setGroups(prev => {
      const newGroups = prev.map(group => {
        if (group.id === groupId) {
          return {
            ...group,
            items: group.items.filter(item => item.id !== itemId)
          }
        }
        return group
      }).filter(group => group.items.length > 0)
      
      if (newGroups.length === 0) {
        setIsEmpty(true)
      }
      return newGroups
    })
    
    // 从选中列表移除
    const newSelected = new Set(selectedItems)
    newSelected.delete(itemId)
    setSelectedItems(newSelected)
  }
  
  // 批量删除
  const removeSelected = () => {
    setGroups(prev => {
      const newGroups = prev.map(group => ({
        ...group,
        items: group.items.filter(item => !selectedItems.has(item.id))
      })).filter(group => group.items.length > 0)
      
      if (newGroups.length === 0) {
        setIsEmpty(true)
      }
      return newGroups
    })
    setSelectedItems(new Set())
    setIsEditing(false)
  }
  
  if (isLoading) {
    return (
      <div className="min-h-screen bg-background max-w-lg mx-auto">
        <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-lg border-b border-border">
          <div className="flex items-center justify-between h-12 px-4">
            <BackButton />
            <h1 className="font-semibold text-base text-foreground">购物车</h1>
            <div className="w-9" />
          </div>
        </header>
        <CartSkeleton />
      </div>
    )
  }
  
  if (isEmpty || groups.length === 0) {
    return (
      <div className="min-h-screen bg-background max-w-lg mx-auto">
        <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-lg border-b border-border">
          <div className="flex items-center justify-between h-12 px-4">
            <BackButton />
            <h1 className="font-semibold text-base text-foreground">购物车</h1>
            <div className="w-9" />
          </div>
        </header>
        <EmptyCart />
      </div>
    )
  }
  
  return (
    <div className="min-h-screen bg-background max-w-lg mx-auto pb-20">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-lg border-b border-border">
        <div className="flex items-center justify-between h-12 px-4">
          <BackButton />
          <h1 className="font-semibold text-base text-foreground">购物车({count})</h1>
          <button
            onClick={() => setIsEditing(!isEditing)}
            className="text-sm text-primary font-medium"
          >
            {isEditing ? "完成" : "编辑"}
          </button>
        </div>
      </header>
      
      {/* 优惠提示 */}
      {saved > 0 && !isEditing && (
        <div className="mx-4 mt-3 px-3 py-2 bg-primary/10 rounded-lg flex items-center justify-between">
          <span className="text-xs text-primary">已为您节省 ¥{saved.toFixed(2)}</span>
          <Link href="/shop/coupons" className="text-xs text-primary flex items-center">
            领更多优惠券 <ChevronRight className="w-3 h-3" />
          </Link>
        </div>
      )}
      
      {/* 商品列表 */}
      <div className="p-4 space-y-4">
        {groups.map((group) => (
          <Card key={group.id} className="p-4 bg-card">
            {/* 店铺信息 */}
            <div className="flex items-center gap-2 mb-3 pb-3 border-b border-border/50">
              <Avatar className="w-6 h-6">
                <AvatarImage src={group.sellerAvatar} />
                <AvatarFallback className="text-[10px] bg-primary/10 text-primary">
                  {group.sellerName[0]}
                </AvatarFallback>
              </Avatar>
              <span className="text-sm font-medium text-foreground">{group.sellerName}</span>
              <Badge variant="outline" className="text-[10px] px-1.5 py-0 border-border text-muted-foreground">
                {group.sellerType === "circle" ? "圈子" : "驿站"}
              </Badge>
              <ChevronRight className="w-4 h-4 text-muted-foreground ml-auto" />
            </div>
            
            {/* 商品列表 */}
            <div className="space-y-3">
              {group.items.map((item) => (
                <div key={item.id} className="flex gap-3">
                  {/* 选择框/删除按钮 */}
                  {isEditing ? (
                    <button
                      onClick={() => removeItem(group.id, item.id)}
                      className="flex-shrink-0 w-5 h-5 mt-7 text-destructive"
                    >
                      <Trash2 className="w-5 h-5" />
                    </button>
                  ) : (
                    <button
                      onClick={() => toggleItem(item.id)}
                      className={cn(
                        "flex-shrink-0 w-5 h-5 mt-7 rounded-full border-2 flex items-center justify-center transition-colors",
                        selectedItems.has(item.id)
                          ? "bg-primary border-primary"
                          : "border-muted-foreground/30"
                      )}
                    >
                      {selectedItems.has(item.id) && (
                        <Check className="w-3 h-3 text-primary-foreground" />
                      )}
                    </button>
                  )}
                  
                  {/* 商品图片 */}
                  <div className="w-20 h-20 rounded-lg bg-secondary flex-shrink-0 overflow-hidden">
                    <img 
                      src={item.image} 
                      alt={item.name}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  
                  {/* 商品信息 */}
                  <div className="flex-1 min-w-0">
                    <h3 className="text-sm font-medium text-foreground line-clamp-1">{item.name}</h3>
                    <p className="text-xs text-muted-foreground mt-0.5">{item.spec}</p>
                    <div className="flex items-center justify-between mt-2">
                      <div className="flex items-baseline gap-1.5">
                        <span className="text-base font-semibold text-primary">¥{item.price}</span>
                        {item.originalPrice > item.price && (
                          <span className="text-xs text-muted-foreground line-through">¥{item.originalPrice}</span>
                        )}
                      </div>
                      
                      {/* 数量控制 */}
                      {item.type === "product" && (
                        <div className="flex items-center gap-2 bg-secondary rounded-full">
                          <button
                            onClick={() => updateQuantity(group.id, item.id, -1)}
                            className="w-7 h-7 flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors"
                            disabled={item.quantity <= 1}
                          >
                            <Minus className="w-3.5 h-3.5" />
                          </button>
                          <span className="text-sm font-medium text-foreground w-5 text-center">{item.quantity}</span>
                          <button
                            onClick={() => updateQuantity(group.id, item.id, 1)}
                            className="w-7 h-7 flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors"
                          >
                            <Plus className="w-3.5 h-3.5" />
                          </button>
        {/* 失效商品 */}
        {invalidItems.length > 0 && (
          <Card className="p-4 bg-card/60 border-dashed">
            <div className="flex items-center justify-between mb-3">
              <span className="text-sm text-muted-foreground">失效商品({invalidItems.length})</span>
              <button className="text-xs text-destructive">清空</button>
            </div>
            <div className="space-y-3 opacity-60">
              {invalidItems.map((item) => (
                <div key={item.id} className="flex gap-3">
                  <div className="w-16 h-16 rounded-lg bg-secondary flex-shrink-0 overflow-hidden relative">
                    <img src={item.image} alt={item.name} className="w-full h-full object-cover grayscale" />
                    <div className="absolute inset-0 bg-black/30 flex items-center justify-center">
                      <span className="text-[10px] text-white bg-black/50 px-1.5 py-0.5 rounded">失效</span>
                    </div>
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="text-sm text-muted-foreground line-clamp-1">{item.name}</h3>
                    <p className="text-xs text-destructive mt-0.5">{item.reason}</p>
                    <p className="text-xs text-muted-foreground line-through mt-1">¥{item.price}</p>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        )}
      </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
            
            {/* 凑单提示 */}
            {(() => {
              const groupTotal = group.items.reduce((sum, item) => 
                selectedItems.has(item.id) ? sum + item.price * item.quantity : sum, 0
              )
              const threshold = group.freeShippingThreshold || 0
              const diff = threshold - groupTotal
              if (diff > 0 && groupTotal > 0) {
                return (
                  <div className="mt-3 px-3 py-2 bg-accent/10 rounded-lg flex items-center justify-between">
                    <span className="text-xs text-accent">
                      再买 <span className="font-medium">¥{diff.toFixed(0)}</span> 即可享受包邮
                    </span>
                    <Link href="/mall" className="text-xs text-accent font-medium flex items-center">
                      去凑单 <ChevronRight className="w-3 h-3" />
                    </Link>
                  </div>
                )
              }
              return null
            })()}
            
            {/* 店铺小计 */}
            <div className="mt-3 pt-3 border-t border-border/50 flex justify-end">
              <span className="text-xs text-muted-foreground">
                小计：
                <span className="text-sm font-semibold text-foreground ml-1">
                  ¥{group.items.reduce((sum, item) => 
                    selectedItems.has(item.id) ? sum + item.price * item.quantity : sum, 0
                  ).toFixed(2)}
                </span>
              </span>
            </div>
          </Card>
        ))}
      </div>
      
      {/* 猜你喜欢 */}
      <div className="px-4 mt-4">
        <h3 className="text-sm font-medium text-foreground mb-3">为你推荐</h3>
        <div className="flex gap-3 overflow-x-auto pb-4 scrollbar-hide">
          {recommendProducts.map((product) => (
            <Card key={product.id} className="flex-shrink-0 w-28 p-2 bg-card hover:bg-secondary/50 transition-colors cursor-pointer">
              <div className="aspect-square rounded-lg bg-secondary mb-2 overflow-hidden">
                <img src={product.image} alt={product.name} className="w-full h-full object-cover" />
              </div>
              <h5 className="text-xs text-foreground line-clamp-1">{product.name}</h5>
              <p className="text-xs text-primary font-medium mt-0.5">¥{product.price}</p>
            </Card>
          ))}
        </div>
      </div>
      
      {/* 底部结算栏 */}
      <div className="fixed bottom-0 left-0 right-0 bg-card/95 backdrop-blur-lg border-t border-border safe-area-pb">
        <div className="max-w-lg mx-auto flex items-center justify-between h-14 px-4">
          <div className="flex items-center gap-3">
            {/* 全选 */}
            <button
              onClick={handleSelectAll}
              className="flex items-center gap-2"
            >
              <div className={cn(
                "w-5 h-5 rounded-full border-2 flex items-center justify-center transition-colors",
                isAllSelected()
                  ? "bg-primary border-primary"
                  : "border-muted-foreground/30"
              )}>
                {isAllSelected() && <Check className="w-3 h-3 text-primary-foreground" />}
              </div>
              <span className="text-sm text-foreground">全选</span>
            </button>
          </div>
          
          {isEditing ? (
            <button
              onClick={removeSelected}
              disabled={selectedItems.size === 0}
              className={cn(
                "px-6 py-2 rounded-full text-sm font-medium transition-colors",
                selectedItems.size > 0
                  ? "bg-destructive text-destructive-foreground"
                  : "bg-muted text-muted-foreground"
              )}
            >
              删除({selectedItems.size})
            </button>
          ) : (
            <div className="flex items-center gap-4">
              {/* 价格 */}
              <div className="text-right">
                <div className="flex items-baseline gap-1">
                  <span className="text-xs text-muted-foreground">合计:</span>
                  <span className="text-lg font-bold text-primary">¥{total.toFixed(2)}</span>
                </div>
                {saved > 0 && (
                  <span className="text-[10px] text-muted-foreground line-through">¥{originalTotal.toFixed(2)}</span>
                )}
              </div>
              
              {/* 结算按钮 */}
              <button
                disabled={selectedItems.size === 0}
                onClick={() => router.push("/checkout")}
                className={cn(
                  "px-6 py-2 rounded-full text-sm font-medium transition-colors",
                  selectedItems.size > 0
                    ? "bg-primary text-primary-foreground hover:bg-primary/90"
                    : "bg-muted text-muted-foreground"
                )}
              >
                结算({count})
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
