// apps/mobile/src/pkg-mine/memberships/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <app-nav-bar title="我的权益">
      <template #right>
        <view class="nav-bell" @tap="goExpiryNotice">
          <app-icon name="bell" :size="20" color="#1a1a1a" />
          <text v-if="expiringCount > 0" class="bell-badge">{{ expiringCount }}</text>
        </view>
      </template>
    </app-nav-bar>

    <scroll-view scroll-y class="scroll-area">
      <!-- 统计卡片 -->
      <view class="stat-wrap">
        <view class="stat-card">
          <view class="stat-head">
            <text class="stat-title">权益概览</text>
            <view class="stat-link" @tap="goOrders">
              <text class="stat-link-txt">订单记录</text>
              <app-icon name="chevron-right" :size="12" color="#c41e3a" />
            </view>
          </view>
          <view class="stat-grid">
            <view class="stat-item" :class="{ 'stat-item-all': filter === 'all' }" @tap="filter = 'all'">
              <text class="stat-num">{{ stats.total }}</text>
              <text class="stat-label">全部权益</text>
            </view>
            <view class="stat-item" :class="{ 'stat-item-green': filter === 'active' }" @tap="filter = 'active'">
              <text class="stat-num c-green">{{ stats.active }}</text>
              <text class="stat-label">正常</text>
            </view>
            <view class="stat-item" :class="{ 'stat-item-amber': filter === 'expiring' }" @tap="filter = 'expiring'">
              <text class="stat-num c-amber">{{ stats.expiring }}</text>
              <text class="stat-label">即将到期</text>
            </view>
            <view class="stat-item" :class="{ 'stat-item-red': filter === 'expired' }" @tap="filter = 'expired'">
              <text class="stat-num c-red">{{ stats.expired }}</text>
              <text class="stat-label">已过期</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 权益列表 -->
      <view class="list">
        <!-- 空态 -->
        <view v-if="filteredMemberships.length === 0" class="empty">
          <app-icon name="gift" :size="48" color="rgba(0,0,0,0.2)" />
          <text class="empty-txt">暂无权益</text>
          <view class="empty-btn" @tap="goVip">
            <text class="empty-btn-txt">开通会员</text>
          </view>
        </view>

        <!-- 权益卡 -->
        <view
          v-for="m in filteredMemberships"
          :key="m.id"
          class="mcard"
          :class="m.bgClass"
        >
          <!-- 头部 -->
          <view class="mcard-head">
            <view class="mcard-head-left">
              <view class="mcard-icon" :class="m.iconBgClass">
                <app-icon :name="m.icon" :size="16" :color="m.iconColor" />
              </view>
              <view>
                <text class="mcard-name">{{ m.name }}</text>
                <text class="mcard-date">{{ m.startDate }} ~ {{ m.expireDate }}</text>
              </view>
            </view>
            <text class="mcard-status" :class="statusConfig[m.status].cls">{{ statusConfig[m.status].label }}</text>
          </view>

          <!-- 有效期 -->
          <view class="mcard-body">
            <view class="exp-row">
              <view class="exp-left">
                <app-icon name="clock" :size="14" color="rgba(0,0,0,0.4)" />
                <text class="exp-label">剩余有效期</text>
              </view>
              <text class="exp-days" :style="{ color: isExpiring(m) ? '#d97706' : m.iconColor }">
                {{ m.daysLeft > 0 ? m.daysLeft + '天' : '已过期' }}
              </text>
            </view>
            <!-- 进度条 -->
            <view class="bar-track">
              <view
                class="bar-fill"
                :style="{ width: barWidth(m) + '%', background: isExpiring(m) ? '#f59e0b' : m.iconColor }"
              />
            </view>
            <!-- 权益标签 -->
            <view class="benefit-tags">
              <text v-for="(b, i) in m.benefits.slice(0, 4)" :key="i" class="benefit-tag">{{ b }}</text>
            </view>
          </view>

          <!-- 底部操作 -->
          <view class="mcard-foot">
            <view class="renew-switch">
              <switch
                :checked="m.autoRenew"
                color="#c41e3a"
                style="transform: scale(0.7)"
                @change="toggleAutoRenew(m.id)"
              />
              <text class="renew-switch-txt">{{ m.autoRenew ? '自动续费已开启' : '自动续费' }}</text>
            </view>
            <view class="renew-right">
              <view class="renew-price">
                <text class="renew-price-label">续费价格</text>
                <text class="renew-price-num">
                  ¥{{ m.price }}
                  <text v-if="m.originalPrice" class="renew-price-old">¥{{ m.originalPrice }}</text>
                </text>
              </view>
              <view class="renew-btn" :class="{ 'renew-btn-amber': isExpiring(m) }" @tap="goRenew(m)">
                <app-icon name="refresh-cw" :size="14" color="#fff" />
                <text class="renew-btn-txt">{{ isExpiring(m) ? '立即续费' : '续费' }}</text>
              </view>
            </view>
          </view>

          <!-- 即将到期警告 -->
          <view v-if="isExpiring(m)" class="warn">
            <app-icon name="alert-triangle" :size="16" color="#f59e0b" />
            <text class="warn-txt">您的权益将在{{ m.daysLeft }}天后到期，续费可享受连续优惠</text>
          </view>

          <!-- 管理订阅（仅圈子会员，退出入口深藏） -->
          <view v-if="m.type === 'circle'" class="manage">
            <view class="manage-toggle" @tap="toggleManage(m.id)">
              <text class="manage-toggle-txt">管理订阅</text>
              <app-icon
                name="chevron-down"
                :size="12"
                color="rgba(0,0,0,0.4)"
                :style="{ transform: manageOpen === m.id ? 'rotate(180deg)' : 'none' }"
              />
            </view>
            <view v-if="manageOpen === m.id" class="manage-panel">
              <text class="manage-desc">退出后将失去圈内全部权益与内容访问，已用时长按天计费，剩余部分可申请退款。</text>
              <view class="manage-exit" @tap="goExit(m)">
                <app-icon name="log-out" :size="12" color="rgba(0,0,0,0.5)" />
                <text class="manage-exit-txt">申请退出并退款</text>
              </view>
            </view>
          </view>
        </view>
      </view>
    </scroll-view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import AppNavBar from '@/components/common/app-nav-bar.vue'
import AppIcon from '@/components/common/app-icon.vue'
import { navigateTo } from '@/utils/router'

type MembershipType = 'vip' | 'circle' | 'station' | 'institute'
type MembershipStatus = 'active' | 'expiring' | 'expired'

interface Membership {
  id: string
  type: MembershipType
  name: string
  icon: string
  iconColor: string
  iconBgClass: string
  bgClass: string
  status: MembershipStatus
  startDate: string
  expireDate: string
  daysLeft: number
  price: number
  originalPrice?: number
  autoRenew: boolean
  benefits: string[]
}

const memberships = ref<Membership[]>([
  {
    id: 'vip-1', type: 'vip', name: '热卜国学VIP会员', icon: 'crown',
    iconColor: '#c8a96a', iconBgClass: 'ibg-gold', bgClass: 'bg-gold',
    status: 'active', startDate: '2024-01-08', expireDate: '2025-01-08', daysLeft: 186,
    price: 365, originalPrice: 588, autoRenew: true,
    benefits: ['排盘工具无限使用', '课程专属折扣', '专属客服', '去广告'],
  },
  {
    id: 'circle-1', type: 'circle', name: '八字命理研习社', icon: 'users',
    iconColor: '#c41e3a', iconBgClass: 'ibg-primary', bgClass: 'bg-primary',
    status: 'expiring', startDate: '2024-01-14', expireDate: '2025-01-14', daysLeft: 28,
    price: 199, autoRenew: false,
    benefits: ['圈内免费内容', '专属直播', '圈内问答', '交流群'],
  },
  {
    id: 'circle-2', type: 'circle', name: '紫微斗数学习班', icon: 'users',
    iconColor: '#c41e3a', iconBgClass: 'ibg-primary', bgClass: 'bg-primary',
    status: 'active', startDate: '2024-03-01', expireDate: '2025-03-01', daysLeft: 268,
    price: 299, autoRenew: true,
    benefits: ['系统课程', '案例分析', '作业点评', '1v1答疑'],
  },
  {
    id: 'station-1', type: 'station', name: '分站站长资格', icon: 'building-2',
    iconColor: '#2d8a4e', iconBgClass: 'ibg-success', bgClass: 'bg-success',
    status: 'active', startDate: '2023-12-20', expireDate: '2024-12-20', daysLeft: 45,
    price: 999, autoRenew: false,
    benefits: ['专属分站页面', '推广分佣', '自购返佣', '品牌展示'],
  },
  {
    id: 'institute-1', type: 'institute', name: '研究院成员', icon: 'graduation-cap',
    iconColor: '#7c3aed', iconBgClass: 'ibg-operator', bgClass: 'bg-operator',
    status: 'active', startDate: '2023-12-15', expireDate: '2024-12-15', daysLeft: 40,
    price: 10000, autoRenew: false,
    benefits: ['内部交流', '线下活动', '资源对接', '保证金可退'],
  },
])

const statusConfig: Record<MembershipStatus, { label: string; cls: string }> = {
  active: { label: '正常', cls: 'st-active' },
  expiring: { label: '即将到期', cls: 'st-expiring' },
  expired: { label: '已过期', cls: 'st-expired' },
}

const filter = ref<'all' | MembershipStatus>('all')
const manageOpen = ref<string | null>(null)

const stats = computed(() => ({
  total: memberships.value.length,
  active: memberships.value.filter((m) => m.status === 'active').length,
  expiring: memberships.value.filter((m) => m.status === 'expiring').length,
  expired: memberships.value.filter((m) => m.status === 'expired').length,
}))

const filteredMemberships = computed(() =>
  filter.value === 'all' ? memberships.value : memberships.value.filter((m) => m.status === filter.value),
)

const expiringCount = computed(() => memberships.value.filter((m) => m.daysLeft <= 30 && m.daysLeft > 0).length)

function isExpiring(m: Membership) {
  return m.daysLeft <= 30 && m.daysLeft > 0
}
function barWidth(m: Membership) {
  return Math.min(100, Math.max(0, (m.daysLeft / 365) * 100))
}
function toggleAutoRenew(id: string) {
  const m = memberships.value.find((x) => x.id === id)
  if (m) m.autoRenew = !m.autoRenew
}
function toggleManage(id: string) {
  manageOpen.value = manageOpen.value === id ? null : id
}
function goExpiryNotice() {
  navigateTo('/notifications?type=expiry')
}
function goOrders() {
  navigateTo('/orders/center')
}
function goVip() {
  navigateTo('/vip')
}
function goRenew(m: Membership) {
  navigateTo(`/renew?type=${m.type}&id=${m.id}`)
}
function goExit(m: Membership) {
  navigateTo(`/circles/${m.id.replace('circle-', '')}/exit`)
}
</script>

<style scoped lang="scss">
.page {
  min-height: 100vh;
  background: #faf8f5;
}
.nav-bell {
  position: relative;
  padding: 8rpx;
}
.bell-badge {
  position: absolute;
  top: 0;
  right: 0;
  min-width: 28rpx;
  height: 28rpx;
  padding: 0 4rpx;
  border-radius: 14rpx;
  background: #ef4444;
  color: #fff;
  font-size: 18rpx;
  line-height: 28rpx;
  text-align: center;
}
.scroll-area {
  height: calc(100vh - 88rpx);
}

/* 统计卡 */
.stat-wrap {
  padding: 24rpx;
}
.stat-card {
  background: linear-gradient(135deg, rgba(196, 30, 58, 0.1), rgba(196, 30, 58, 0.04));
  border: 1rpx solid rgba(196, 30, 58, 0.2);
  border-radius: 20rpx;
  padding: 24rpx;
}
.stat-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24rpx;
}
.stat-title {
  font-size: 28rpx;
  font-weight: 500;
  color: #1a1a1a;
}
.stat-link {
  display: flex;
  align-items: center;
  gap: 4rpx;
}
.stat-link-txt {
  font-size: 22rpx;
  color: #c41e3a;
}
.stat-grid {
  display: flex;
  gap: 12rpx;
}
.stat-item {
  flex: 1;
  padding: 16rpx 0;
  border-radius: 16rpx;
  background: rgba(255, 255, 255, 0.5);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4rpx;
}
.stat-item-all {
  background: rgba(196, 30, 58, 0.2);
}
.stat-item-green {
  background: #dcfce7;
}
.stat-item-amber {
  background: #fef3c7;
}
.stat-item-red {
  background: #fee2e2;
}
.stat-num {
  font-size: 36rpx;
  font-weight: 700;
  color: #1a1a1a;
}
.stat-num.c-green {
  color: #16a34a;
}
.stat-num.c-amber {
  color: #d97706;
}
.stat-num.c-red {
  color: #dc2626;
}
.stat-label {
  font-size: 20rpx;
  color: rgba(0, 0, 0, 0.45);
}

/* 列表 */
.list {
  padding: 0 24rpx 160rpx;
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}

/* 空态 */
.empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 120rpx 0;
  gap: 12rpx;
}
.empty-txt {
  font-size: 26rpx;
  color: rgba(0, 0, 0, 0.4);
}
.empty-btn {
  margin-top: 16rpx;
  padding: 12rpx 32rpx;
  border: 1rpx solid #c41e3a;
  border-radius: 999rpx;
}
.empty-btn-txt {
  font-size: 24rpx;
  color: #c41e3a;
}

/* 权益卡 */
.mcard {
  border-radius: 20rpx;
  overflow: hidden;
}
.bg-gold {
  background: linear-gradient(90deg, rgba(200, 169, 106, 0.2), rgba(200, 169, 106, 0.05));
}
.bg-primary {
  background: linear-gradient(90deg, rgba(196, 30, 58, 0.2), rgba(196, 30, 58, 0.05));
}
.bg-success {
  background: linear-gradient(90deg, rgba(45, 138, 78, 0.2), rgba(45, 138, 78, 0.05));
}
.bg-operator {
  background: linear-gradient(90deg, rgba(124, 58, 237, 0.2), rgba(124, 58, 237, 0.05));
}
.mcard-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 24rpx;
  border-bottom: 1rpx solid rgba(0, 0, 0, 0.06);
}
.mcard-head-left {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.mcard-icon {
  width: 64rpx;
  height: 64rpx;
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}
.ibg-gold {
  background: rgba(200, 169, 106, 0.2);
}
.ibg-primary {
  background: rgba(196, 30, 58, 0.2);
}
.ibg-success {
  background: rgba(45, 138, 78, 0.2);
}
.ibg-operator {
  background: rgba(124, 58, 237, 0.2);
}
.mcard-name {
  display: block;
  font-size: 26rpx;
  font-weight: 500;
  color: #1a1a1a;
}
.mcard-date {
  display: block;
  font-size: 20rpx;
  color: rgba(0, 0, 0, 0.45);
  margin-top: 4rpx;
}
.mcard-status {
  font-size: 20rpx;
  padding: 4rpx 16rpx;
  border-radius: 999rpx;
}
.st-active {
  background: #dcfce7;
  color: #16a34a;
}
.st-expiring {
  background: #fef3c7;
  color: #d97706;
}
.st-expired {
  background: #fee2e2;
  color: #dc2626;
}
.mcard-body {
  padding: 24rpx;
}
.exp-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16rpx;
}
.exp-left {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.exp-label {
  font-size: 22rpx;
  color: rgba(0, 0, 0, 0.45);
}
.exp-days {
  font-size: 28rpx;
  font-weight: 700;
}
.bar-track {
  height: 12rpx;
  background: #f0ece6;
  border-radius: 999rpx;
  overflow: hidden;
}
.bar-fill {
  height: 100%;
  border-radius: 999rpx;
  transition: width 0.3s;
}
.benefit-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 12rpx;
  margin-top: 24rpx;
}
.benefit-tag {
  padding: 4rpx 16rpx;
  border-radius: 999rpx;
  background: rgba(255, 255, 255, 0.6);
  font-size: 20rpx;
  color: rgba(0, 0, 0, 0.45);
}
.mcard-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 24rpx;
  border-top: 1rpx solid rgba(0, 0, 0, 0.06);
  background: rgba(255, 255, 255, 0.3);
}
.renew-switch {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.renew-switch-txt {
  font-size: 22rpx;
  color: rgba(0, 0, 0, 0.45);
}
.renew-right {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.renew-price {
  text-align: right;
}
.renew-price-label {
  display: block;
  font-size: 20rpx;
  color: rgba(0, 0, 0, 0.45);
}
.renew-price-num {
  font-size: 28rpx;
  font-weight: 700;
  color: #c41e3a;
}
.renew-price-old {
  font-size: 20rpx;
  color: rgba(0, 0, 0, 0.4);
  text-decoration: line-through;
  margin-left: 4rpx;
}
.renew-btn {
  display: flex;
  align-items: center;
  gap: 4rpx;
  height: 56rpx;
  padding: 0 24rpx;
  border-radius: 12rpx;
  background: #c41e3a;
}
.renew-btn-amber {
  background: #f59e0b;
}
.renew-btn-txt {
  font-size: 24rpx;
  color: #fff;
}
.warn {
  display: flex;
  align-items: center;
  gap: 8rpx;
  padding: 16rpx 24rpx;
  background: #fffbeb;
  border-top: 1rpx solid #fef3c7;
}
.warn-txt {
  font-size: 22rpx;
  color: #d97706;
  flex: 1;
}
.manage {
  border-top: 1rpx solid rgba(0, 0, 0, 0.04);
  background: rgba(255, 255, 255, 0.2);
}
.manage-toggle {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 4rpx;
  padding: 16rpx 0;
}
.manage-toggle-txt {
  font-size: 22rpx;
  color: rgba(0, 0, 0, 0.4);
}
.manage-panel {
  padding: 8rpx 24rpx 24rpx;
}
.manage-desc {
  display: block;
  font-size: 22rpx;
  color: rgba(0, 0, 0, 0.45);
  line-height: 1.6;
  margin-bottom: 16rpx;
}
.manage-exit {
  display: inline-flex;
  align-items: center;
  gap: 4rpx;
}
.manage-exit-txt {
  font-size: 22rpx;
  color: rgba(0, 0, 0, 0.5);
  text-decoration: underline;
}
</style>

// proto-ref-app/mine/memberships/page.tsx
"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { 
  ChevronLeft, ChevronRight, Crown, Users, Building2, GraduationCap,
  Clock, AlertTriangle, CheckCircle, Gift, Sparkles, Bell, RefreshCw,
  ChevronDown, LogOut
} from "lucide-react"
import { cn } from "@/lib/utils"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import Link from "next/link"

// ============================================
// 权益类型定义
// ============================================
type MembershipType = "vip" | "circle" | "station" | "institute"
type MembershipStatus = "active" | "expiring" | "expired"

interface Membership {
  id: string
  type: MembershipType
  name: string
  icon: typeof Crown
  color: string
  bgColor: string
  status: MembershipStatus
  startDate: string
  expireDate: string
  daysLeft: number
  price: number // 续费价格
  originalPrice?: number
  autoRenew: boolean
  benefits: string[]
}

// ============================================
// Mock 权益数据
// ============================================
const mockMemberships: Membership[] = [
  {
    id: "vip-1",
    type: "vip",
    name: "热卜国学VIP会员",
    icon: Crown,
    color: "text-gold",
    bgColor: "bg-gradient-to-r from-gold/20 to-gold/5",
    status: "active",
    startDate: "2024-01-08",
    expireDate: "2025-01-08",
    daysLeft: 186,
    price: 365,
    originalPrice: 588,
    autoRenew: true,
    benefits: ["排盘工具无限使用", "课程专属折扣", "专属客服", "去广告"]
  },
  {
    id: "circle-1",
    type: "circle",
    name: "八字命理研习社",
    icon: Users,
    color: "text-primary",
    bgColor: "bg-gradient-to-r from-primary/20 to-primary/5",
    status: "expiring",
    startDate: "2024-01-14",
    expireDate: "2025-01-14",
    daysLeft: 28,
    price: 199,
    autoRenew: false,
    benefits: ["圈内免费内容", "专属直播", "圈内问答", "交流群"]
  },
  {
    id: "circle-2",
    type: "circle",
    name: "紫微斗数学习班",
    icon: Users,
    color: "text-primary",
    bgColor: "bg-gradient-to-r from-primary/20 to-primary/5",
    status: "active",
    startDate: "2024-03-01",
    expireDate: "2025-03-01",
    daysLeft: 268,
    price: 299,
    autoRenew: true,
    benefits: ["系统课程", "案例分析", "作业点评", "1v1答疑"]
  },
  {
    id: "station-1",
    type: "station",
    name: "分站站长资格",
    icon: Building2,
    color: "text-success",
    bgColor: "bg-gradient-to-r from-success/20 to-success/5",
    status: "active",
    startDate: "2023-12-20",
    expireDate: "2024-12-20",
    daysLeft: 45,
    price: 999,
    autoRenew: false,
    benefits: ["专属分站页面", "推广分佣", "自购返佣", "品牌展示"]
  },
  {
    id: "institute-1",
    type: "institute",
    name: "研究院成员",
    icon: GraduationCap,
    color: "text-operator",
    bgColor: "bg-gradient-to-r from-operator/20 to-operator/5",
    status: "active",
    startDate: "2023-12-15",
    expireDate: "2024-12-15",
    daysLeft: 40,
    price: 10000,
    autoRenew: false,
    benefits: ["内部交流", "线下活动", "资源对接", "保证金可退"]
  },
]

// ============================================
// 状态配置
// ============================================
const statusConfig: Record<MembershipStatus, { label: string; color: string; bgColor: string }> = {
  active: { label: "正常", color: "text-green-600", bgColor: "bg-green-50" },
  expiring: { label: "即将到期", color: "text-amber-600", bgColor: "bg-amber-50" },
  expired: { label: "已过期", color: "text-red-600", bgColor: "bg-red-50" },
}

// ============================================
// 主组件
// ============================================
export default function MyMembershipsPage() {
  const router = useRouter()
  const [memberships, setMemberships] = useState(mockMemberships)
  const [filter, setFilter] = useState<"all" | MembershipStatus>("all")
  // 已展开"管理订阅"的会员卡片（退出入口深藏于此，需主动点开）
  const [manageOpen, setManageOpen] = useState<string | null>(null)

  // 统计数据
  const stats = {
    total: memberships.length,
    active: memberships.filter(m => m.status === "active").length,
    expiring: memberships.filter(m => m.status === "expiring").length,
    expired: memberships.filter(m => m.status === "expired").length,
  }

  // 筛选
  const filteredMemberships = filter === "all" 
    ? memberships 
    : memberships.filter(m => m.status === filter)

  // 切换自动续费
  const toggleAutoRenew = (id: string) => {
    setMemberships(prev => prev.map(m => 
      m.id === id ? { ...m, autoRenew: !m.autoRenew } : m
    ))
  }

  // 即将到期提醒（30天内）
  const expiringCount = memberships.filter(m => m.daysLeft <= 30 && m.daysLeft > 0).length

  return (
    <div className="min-h-screen bg-background max-w-lg mx-auto">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-lg border-b border-border">
        <div className="flex items-center justify-between h-12 px-4">
          <button onClick={() => router.back()} className="p-1 -ml-1">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <h1 className="font-semibold text-base">我的权益</h1>
          <Link href="/notifications?type=expiry" className="p-1 relative">
            <Bell className="w-5 h-5" />
            {expiringCount > 0 && (
              <span className="absolute -top-0.5 -right-0.5 w-4 h-4 rounded-full bg-red-500 text-white text-[10px] flex items-center justify-center">
                {expiringCount}
              </span>
            )}
          </Link>
        </div>
      </header>

      {/* 统计卡片 */}
      <div className="p-4">
        <Card className="bg-gradient-to-r from-primary/10 to-primary/5 border-primary/20 p-4">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-medium">权益概��</h2>
            <Link href="/orders/center" className="text-xs text-primary flex items-center gap-1">
              订单记录 <ChevronRight className="w-3 h-3" />
            </Link>
          </div>
          <div className="grid grid-cols-4 gap-2 text-center">
            <button 
              onClick={() => setFilter("all")}
              className={cn(
                "py-2 rounded-lg transition-colors",
                filter === "all" ? "bg-primary/20" : "bg-white/50"
              )}
            >
              <p className="text-lg font-bold text-foreground">{stats.total}</p>
              <p className="text-[10px] text-muted-foreground">全部权益</p>
            </button>
            <button 
              onClick={() => setFilter("active")}
              className={cn(
                "py-2 rounded-lg transition-colors",
                filter === "active" ? "bg-green-100" : "bg-white/50"
              )}
            >
              <p className="text-lg font-bold text-green-600">{stats.active}</p>
              <p className="text-[10px] text-muted-foreground">正常</p>
            </button>
            <button 
              onClick={() => setFilter("expiring")}
              className={cn(
                "py-2 rounded-lg transition-colors",
                filter === "expiring" ? "bg-amber-100" : "bg-white/50"
              )}
            >
              <p className="text-lg font-bold text-amber-600">{stats.expiring}</p>
              <p className="text-[10px] text-muted-foreground">即将到期</p>
            </button>
            <button 
              onClick={() => setFilter("expired")}
              className={cn(
                "py-2 rounded-lg transition-colors",
                filter === "expired" ? "bg-red-100" : "bg-white/50"
              )}
            >
              <p className="text-lg font-bold text-red-600">{stats.expired}</p>
              <p className="text-[10px] text-muted-foreground">已过期</p>
            </button>
          </div>
        </Card>
      </div>

      {/* 权益列表 */}
      <main className="px-4 pb-24 space-y-3">
        {filteredMemberships.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
            <Gift className="w-12 h-12 mb-3 opacity-30" />
            <p className="text-sm">暂无权益</p>
            <Link href="/vip">
              <Button variant="outline" size="sm" className="mt-4">
                开通会员
              </Button>
            </Link>
          </div>
        ) : (
          filteredMemberships.map((membership) => {
            const Icon = membership.icon
            const status = statusConfig[membership.status]
            const isExpiring = membership.daysLeft <= 30 && membership.daysLeft > 0
            
            return (
              <Card key={membership.id} className={cn("overflow-hidden", membership.bgColor)}>
                {/* 头部 */}
                <div className="flex items-center justify-between p-3 border-b border-border/50">
                  <div className="flex items-center gap-2">
                    <div className={cn(
                      "w-8 h-8 rounded-lg flex items-center justify-center",
                      membership.color.replace("text-", "bg-").replace("]", "/20]")
                    )}>
                      <Icon className={cn("w-4 h-4", membership.color)} />
                    </div>
                    <div>
                      <h3 className="font-medium text-sm">{membership.name}</h3>
                      <p className="text-[10px] text-muted-foreground">
                        {membership.startDate} ~ {membership.expireDate}
                      </p>
                    </div>
                  </div>
                  <Badge className={cn("text-[10px]", status.bgColor, status.color)}>
                    {status.label}
                  </Badge>
                </div>

                {/* 有效期 */}
                <div className="p-3">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-muted-foreground" />
                      <span className="text-xs text-muted-foreground">剩余有效期</span>
                    </div>
                    <span className={cn(
                      "text-sm font-bold",
                      isExpiring ? "text-amber-600" : membership.color
                    )}>
                      {membership.daysLeft > 0 ? `${membership.daysLeft}天` : "已过期"}
                    </span>
                  </div>

                  {/* 进度条 */}
                  <div className="h-1.5 bg-secondary rounded-full overflow-hidden">
                    <div 
                      className={cn(
                        "h-full rounded-full transition-all",
                        isExpiring ? "bg-amber-500" : membership.color.replace("text-", "bg-")
                      )}
                      style={{ 
                        width: `${Math.min(100, Math.max(0, (membership.daysLeft / 365) * 100))}%` 
                      }}
                    />
                  </div>

                  {/* 权益说明 */}
                  <div className="flex flex-wrap gap-1.5 mt-3">
                    {membership.benefits.slice(0, 4).map((benefit, i) => (
                      <span 
                        key={i}
                        className="px-2 py-0.5 rounded-full bg-white/60 text-[10px] text-muted-foreground"
                      >
                        {benefit}
                      </span>
                    ))}
                  </div>
                </div>

                {/* 底部操作 */}
                <div className="flex items-center justify-between p-3 border-t border-border/50 bg-white/30">
                  {/* 自动续费开关 */}
                  <div className="flex items-center gap-2">
                    <Switch
                      checked={membership.autoRenew}
                      onCheckedChange={() => toggleAutoRenew(membership.id)}
                      className="scale-75"
                    />
                    <span className="text-xs text-muted-foreground">
                      {membership.autoRenew ? "自动续费已开启" : "自动续费"}
                    </span>
                  </div>

                  {/* 续费按钮 */}
                  <div className="flex items-center gap-2">
                    <div className="text-right mr-2">
                      <p className="text-xs text-muted-foreground">续费价格</p>
                      <p className="font-bold text-primary">
                        ¥{membership.price}
                        {membership.originalPrice && (
                          <span className="text-[10px] text-muted-foreground line-through ml-1">
                            ¥{membership.originalPrice}
                          </span>
                        )}
                      </p>
                    </div>
                    <Link href={`/renew?type=${membership.type}&id=${membership.id}`}>
                      <Button 
                        size="sm" 
                        className={cn(
                          "h-8",
                          isExpiring 
                            ? "bg-amber-500 hover:bg-amber-600" 
                            : "bg-primary hover:bg-primary/90"
                        )}
                      >
                        <RefreshCw className="w-3.5 h-3.5 mr-1" />
                        {isExpiring ? "立即续费" : "续费"}
                      </Button>
                    </Link>
                  </div>
                </div>

                {/* 即将到期警告 */}
                {isExpiring && (
                  <div className="flex items-center gap-2 px-3 py-2 bg-amber-50 border-t border-amber-100">
                    <AlertTriangle className="w-4 h-4 text-amber-500" />
                    <span className="text-xs text-amber-600">
                      您的权益将在{membership.daysLeft}天后到期，续费可享受连续优惠
                    </span>
                  </div>
                )}

                {/* 管理订阅（退出入口深藏于此，弱化处理，仅圈子会员） */}
                {membership.type === "circle" && (
                  <div className="border-t border-border/40 bg-white/20">
                    <button
                      onClick={() => setManageOpen(manageOpen === membership.id ? null : membership.id)}
                      className="w-full flex items-center justify-center gap-1 py-2 text-[11px] text-muted-foreground/60 hover:text-muted-foreground transition-colors"
                    >
                      管理订阅
                      <ChevronDown className={cn("w-3 h-3 transition-transform", manageOpen === membership.id && "rotate-180")} />
                    </button>
                    {manageOpen === membership.id && (
                      <div className="px-3 pb-3 pt-1">
                        <p className="text-[11px] text-muted-foreground/70 leading-relaxed mb-2">
                          退出后将失去圈内全部权益与内容访问，已用时长按天计费，剩余部分可申请退款。
                        </p>
                        <button
                          onClick={() => router.push(`/circles/${membership.id.replace("circle-", "")}/exit`)}
                          className="inline-flex items-center gap-1 text-[11px] text-muted-foreground/70 underline underline-offset-2 hover:text-[#C41E3A]"
                        >
                          <LogOut className="w-3 h-3" />
                          申请退出并退款
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </Card>
            )
          })
        )}
      </main>
    </div>
  )
}
