// components/cards/live-card.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { cn } from "@/lib/utils"
import { Eye, Clock, Bell, Users } from "lucide-react"
import {
  type CardVariant,
  normalizeRatio,
  cardShell,
  formatCount,
  CardCover,
  HotBadge,
  AuthorRow,
} from "./primitives"

export interface LiveCardData {
  id: number | string
  title: string
  cover?: string
  coverRatio?: string
  host?: string
  hostAvatar?: string
  viewers?: number
  reservations?: number
  status?: "live" | "upcoming" | "replay"
  /** 直播类型：knowledge 知识授课 / commerce 电商带货 */
  liveType?: "knowledge" | "commerce"
  scheduledTime?: string
  duration?: string
}

export function LiveCard({
  data,
  variant = "feed",
  className,
}: {
  data: LiveCardData
  variant?: CardVariant
  className?: string
}) {
  const [booked, setBooked] = useState(false)
  const href = `/live/${data.id}`
  const ratio = normalizeRatio(data.coverRatio)
  const status = data.status ?? "live"

  const typeLabel = data.liveType === "commerce" ? "电商带货" : "知识授课"

  const handleBook = (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setBooked((b) => !b)
  }

  // 封面浮层（状态标 + 人数 + 预约按钮）
  const overlay = (
    <>
      <div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent" />
      <span className="absolute top-2 left-2 z-10 text-[10px] px-2 py-0.5 rounded-full text-white/95 font-medium bg-black/35 backdrop-blur-md">
        {typeLabel}
      </span>
      {status === "live" ? (
        <HotBadge kind="live" />
      ) : status === "upcoming" ? (
        <span className="absolute top-2 right-2 z-10 inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-black/35 backdrop-blur-md text-white/95 text-[10px] font-medium">
          <Clock className="w-3 h-3" />
          {data.scheduledTime}
        </span>
      ) : (
        <span className="absolute top-2 right-2 z-10 px-2 py-0.5 rounded-full bg-black/35 backdrop-blur-md text-white/95 text-[10px]">
          {data.duration || "回放"}
        </span>
      )}
      <div className="absolute bottom-2 left-2 z-10 flex items-center gap-1 px-2 py-0.5 rounded-full bg-black/45 backdrop-blur-sm text-white text-[10px]">
        {status === "upcoming" ? (
          <>
            <Users className="w-3 h-3 text-white/80" />
            {formatCount(data.reservations)}预约
          </>
        ) : (
          <>
            <Eye className="w-3 h-3 text-white/80" />
            {formatCount(data.viewers)}
            {status === "replay" ? "次观看" : ""}
          </>
        )}
      </div>
      {status === "upcoming" && (
        <button
          onClick={handleBook}
          className={cn(
            "absolute bottom-2 right-2 z-10 inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-medium transition-all",
            booked ? "bg-white/20 text-white border border-white/30" : "bg-[var(--brand)] text-white",
          )}
        >
          <Bell className="w-3 h-3" />
          {booked ? "已约" : "预约"}
        </button>
      )}
    </>
  )

  // ---------- 横向列表卡 ----------
  if (variant === "list") {
    return (
      <Link href={href} className={cn("block", className)}>
        <article className={cn(cardShell, "flex gap-3 p-2")}>
          <div className="w-[120px] flex-shrink-0">
            <CardCover src={data.cover} alt={data.title} ratio="1:1" className="rounded-xl">
              {overlay}
            </CardCover>
          </div>
          <div className="flex-1 min-w-0 flex flex-col justify-between py-0.5">
            <h3 className="text-[14px] font-medium text-[var(--text-strong)] line-clamp-2 leading-snug">{data.title}</h3>
            <AuthorRow name={data.host} avatar={data.hostAvatar} />
          </div>
        </article>
      </Link>
    )
  }

  // ---------- 横滑小卡 ----------
  if (variant === "rail") {
    return (
      <Link href={href} className={cn("block w-[150px] flex-shrink-0", className)}>
        <article className={cardShell}>
          <CardCover src={data.cover} alt={data.title} ratio="1:1">
            {overlay}
          </CardCover>
          <div className="p-2">
            <h3 className="text-[13px] text-[var(--text-strong)] line-clamp-2 leading-snug mb-1 min-h-[36px]">{data.title}</h3>
            <AuthorRow name={data.host} avatar={data.hostAvatar} />
          </div>
        </article>
      </Link>
    )
  }

  // ---------- 瀑布流/网格竖卡（默认 feed） ----------
  return (
    <Link href={href} className={cn("block break-inside-avoid mb-[6px] sm:mb-2", className)}>
      <article
        className={cn(cardShell, status === "live" && "ring-1 ring-[var(--brand)]/40 live-card-glow")}
      >
        <CardCover src={data.cover} alt={data.title} ratio={ratio}>
          {overlay}
        </CardCover>
        <div className="p-2.5">
          <h3 className="text-[14px] font-medium text-[var(--text-strong)] line-clamp-2 leading-[1.5] mb-2">{data.title}</h3>
          <AuthorRow name={data.host} avatar={data.hostAvatar} />
        </div>
      </article>
    </Link>
  )
}

// apps/mobile/src/components/cards/live-card.vue
<script setup lang="ts">
/** 直播卡(feed)- 从原型 components/cards/live-card.tsx 迁移 */
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { navigateTo } from '@/utils/router'
import { type LiveCardData, normalizeRatio, formatCount } from '@/lib/card-utils'

const props = defineProps<{ data: LiveCardData }>()
const booked = ref(false)
const ratio = computed(() => normalizeRatio(props.data.coverRatio))
const status = computed(() => props.data.status ?? 'live')
const typeLabel = computed(() => (props.data.liveType === 'commerce' ? '电商带货' : '知识授课'))
function open() { navigateTo(`/live/${props.data.id}`) }
function toggleBook() { booked.value = !booked.value }
</script>

<template>
  <view
    class="card"
    :class="status === 'live' && 'card-live'"
    hover-class="card-press"
    @tap="open"
  >
    <view
      class="cover"
      :class="ratio === '1:1' ? 'r-sq' : 'r-34'"
    >
      <image
        v-if="data.cover"
        class="cover-img"
        :src="data.cover"
        mode="aspectFill"
      />
      <view class="grad" />
      <!-- 类型标 -->
      <text class="type-badge">
        {{ typeLabel }}
      </text>
      <!-- 状态标 -->
      <view
        v-if="status === 'live'"
        class="live-badge"
      >
        <view class="live-dot" /><text class="live-txt">
          直播中
        </text>
      </view>
      <view
        v-else-if="status === 'upcoming'"
        class="time-badge"
      >
        <AppIcon
          name="clock"
          :size="20"
          color="#ffffff"
        /><text class="time-txt">
          {{ data.scheduledTime }}
        </text>
      </view>
      <text
        v-else
        class="time-badge time-txt"
      >
        {{ data.duration || '回放' }}
      </text>
      <!-- 人数 -->
      <view class="viewers">
        <AppIcon
          :name="status === 'upcoming' ? 'users' : 'eye'"
          :size="20"
          color="rgba(255,255,255,0.8)"
        />
        <text class="viewers-txt">
          {{ status === 'upcoming' ? formatCount(data.reservations) + '预约' : formatCount(data.viewers) + (status === 'replay' ? '次观看' : '') }}
        </text>
      </view>
      <!-- 预约按钮 -->
      <view
        v-if="status === 'upcoming'"
        class="book-btn"
        :class="booked ? 'book-on' : 'book-off'"
        @tap.stop="toggleBook"
      >
        <AppIcon
          name="bell"
          :size="20"
          :color="booked ? '#ffffff' : '#ffffff'"
        /><text class="book-txt">
          {{ booked ? '已约' : '预约' }}
        </text>
      </view>
    </view>
    <view class="body">
      <text class="title">
        {{ data.title }}
      </text>
      <view
        v-if="data.host"
        class="author"
      >
        <view class="avatar">
          <image
            v-if="data.hostAvatar"
            class="avatar-img"
            :src="data.hostAvatar"
            mode="aspectFill"
          />
          <text
            v-else
            class="avatar-ph"
          >
            {{ data.host.charAt(0) }}
          </text>
        </view>
        <text class="author-name">
          {{ data.host }}
        </text>
      </view>
    </view>
  </view>
</template>

<style scoped lang="scss">
.card { overflow: hidden; background: var(--surface); border-radius: 24rpx; box-shadow: 0 2rpx 16rpx rgba(0,0,0,0.05); margin-bottom: 12rpx; }
.card-live { box-shadow: 0 0 0 2rpx rgba(196,30,58,0.4), 0 2rpx 16rpx rgba(196,30,58,0.15); }
.card-press { transform: scale(0.98); }
.cover { position: relative; width: 100%; background: var(--surface-sunken); overflow: hidden; }
.r-34 { padding-bottom: 133.33%; }
.r-sq { padding-bottom: 100%; }
.cover-img { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }
.grad { position: absolute; inset: 0; background: linear-gradient(to top, rgba(0,0,0,0.55), transparent 60%); }
.type-badge { position: absolute; top: 16rpx; left: 16rpx; z-index: 10; font-size: 20rpx; padding: 2rpx 14rpx; border-radius: 999rpx; color: rgba(255,255,255,0.95); font-weight: 500; background: rgba(0,0,0,0.45); }
.live-badge { position: absolute; top: 16rpx; right: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 4rpx 14rpx; border-radius: 999rpx; background: var(--brand); }
.live-dot { width: 10rpx; height: 10rpx; background: #fff; border-radius: 999rpx; }
.live-txt { font-size: 20rpx; color: #fff; font-weight: 500; }
.time-badge { position: absolute; top: 16rpx; right: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 4rpx 14rpx; border-radius: 999rpx; background: rgba(0,0,0,0.45); }
.time-txt { font-size: 20rpx; color: rgba(255,255,255,0.95); font-weight: 500; }
.viewers { position: absolute; bottom: 16rpx; left: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 4rpx 14rpx; border-radius: 999rpx; background: rgba(0,0,0,0.5); }
.viewers-txt { font-size: 20rpx; color: #fff; }
.book-btn { position: absolute; bottom: 16rpx; right: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 6rpx 18rpx; border-radius: 999rpx; }
.book-off { background: var(--brand); }
.book-on { background: rgba(255,255,255,0.2); border: 2rpx solid rgba(255,255,255,0.3); }
.book-txt { font-size: 20rpx; color: #fff; font-weight: 500; }
.body { padding: 18rpx; }
.title { display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; overflow: hidden; font-size: 28rpx; font-weight: 500; color: var(--text-strong); line-height: 1.5; margin-bottom: 14rpx; }
.author { display: flex; align-items: center; gap: 10rpx; }
.avatar { width: 32rpx; height: 32rpx; border-radius: 999rpx; overflow: hidden; background: rgba(0,0,0,0.08); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.avatar-img { width: 100%; height: 100%; }
.avatar-ph { font-size: 16rpx; color: var(--text); }
.author-name { font-size: 22rpx; color: var(--text); overflow: hidden; white-space: nowrap; text-overflow: ellipsis; }
</style>
