// v0-reference/proto-ref-app/coupons/center/page.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { BackButton } from "@/components/common/back-button"
import { Gift, Crown, Coins, Check, Clock } from "lucide-react"

type CouponType = "满减" | "折扣" | "无门槛"

// 券类型 → 品牌色体系（满减=故宫红 / 折扣=珠宝金 / 无门槛=吉利绿）
const typeStyles: Record<CouponType, { accent: string; text: string; badgeBg: string; badgeText: string }> = {
  满减: { accent: "bg-primary", text: "text-primary", badgeBg: "bg-primary/10", badgeText: "text-primary" },
  折扣: { accent: "bg-gold", text: "text-gold", badgeBg: "bg-gold/15", badgeText: "text-gold" },
  无门槛: { accent: "bg-success", text: "text-success", badgeBg: "bg-success/10", badgeText: "text-success" },
}

const tagStyles: Record<string, string> = {
  热门: "bg-primary text-primary-foreground",
  限时: "bg-gold text-gold-foreground",
  新人: "bg-success text-success-foreground",
}

// 模拟可领取优惠券数据
const availableCoupons = [
  { id: 1, amount: 50, type: "满减" as CouponType, minAmount: 299, scope: "全部课程", startDate: "2026.05.10", endDate: "2026.06.30", tag: "热门" },
  { id: 2, amount: 20, type: "满减" as CouponType, minAmount: 99, scope: "全部商品", startDate: "2026.05.10", endDate: "2026.05.31", tag: "限时" },
  { id: 3, amount: 8, type: "折扣" as CouponType, scope: "指定课程", startDate: "2026.05.10", endDate: "2026.06.15", tag: "" },
  { id: 4, amount: 10, type: "无门槛" as CouponType, scope: "全部商品", startDate: "2026.05.10", endDate: "2026.05.20", tag: "新人" },
  { id: 5, amount: 100, type: "满减" as CouponType, minAmount: 599, scope: "精品课程", startDate: "2026.05.10", endDate: "2026.07.31", tag: "" },
]

// 积分兑换券
const pointsCoupons = [
  { id: 101, amount: 5, type: "无门槛" as CouponType, scope: "全部商品", points: 500 },
  { id: 102, amount: 15, type: "满减" as CouponType, minAmount: 99, scope: "全部商品", points: 1000 },
  { id: 103, amount: 30, type: "满减" as CouponType, minAmount: 199, scope: "全部课程", points: 2000 },
]

// 会员专属券
const vipCoupons = [
  { id: 201, amount: 88, type: "满减" as CouponType, minAmount: 388, scope: "全场通用", vipLevel: 2 },
  { id: 202, amount: 9, type: "折扣" as CouponType, scope: "精品课程", vipLevel: 3 },
]

function CouponValue({ type, amount, size = "md" }: { type: CouponType; amount: number; size?: "md" | "sm" }) {
  const isDiscount = type === "折扣"
  const big = size === "md" ? "text-2xl" : "text-xl"
  return isDiscount ? (
    <div className="flex items-baseline">
      <span className={cn(big, "font-bold")}>{amount}</span>
      <span className="text-sm font-bold">折</span>
    </div>
  ) : (
    <div className="flex items-baseline">
      <span className="text-sm font-bold">¥</span>
      <span className={cn(big, "font-bold")}>{amount}</span>
    </div>
  )
}

export default function CouponCenterPage() {
  const [receivedIds, setReceivedIds] = useState<number[]>([])
  const [activeTab, setActiveTab] = useState<"all" | "course" | "product" | "points">("all")

  const userPoints = 1580
  const userVipLevel = 1

  const handleReceive = (id: number) => {
    if (!receivedIds.includes(id)) setReceivedIds([...receivedIds, id])
  }

  const filteredCoupons = availableCoupons.filter(coupon => {
    if (activeTab === "all") return true
    if (activeTab === "course") return coupon.scope.includes("课程")
    if (activeTab === "product") return coupon.scope.includes("商品")
    return true
  })

  return (
    <div className="min-h-screen bg-background max-w-lg mx-auto">
      {/* 顶部品牌渐变 */}
      <header className="sticky top-0 z-50 bg-gradient-to-br from-[#a01830] via-primary to-primary text-primary-foreground">
        <div className="flex items-center justify-between px-4 h-12">
          <BackButton fallbackPath="/coupons" iconClassName="text-primary-foreground" />
          <h1 className="font-bold flex items-center gap-2">
            <Gift className="w-5 h-5 text-gold" />
            领券中心
          </h1>
          <Link href="/coupons" className="text-xs text-primary-foreground/90">我的券</Link>
        </div>

        {/* 积分入口 */}
        <div className="px-4 pb-4">
          <Card className="bg-primary-foreground/10 border-primary-foreground/20 p-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-gold/20 flex items-center justify-center">
                  <Coins className="w-5 h-5 text-gold" />
                </div>
                <div>
                  <p className="text-primary-foreground/70 text-xs">我的积分</p>
                  <p className="text-xl font-bold text-primary-foreground">{userPoints}</p>
                </div>
              </div>
              <Button size="sm" className="bg-gold text-gold-foreground hover:bg-gold/90 border-0">
                兑换礼品
              </Button>
            </div>
          </Card>
        </div>
      </header>

      {/* Tab切换 */}
      <div className="sticky top-[124px] z-40 bg-background border-b border-border">
        <div className="flex">
          {[
            { key: "all", label: "全部" },
            { key: "course", label: "课程券" },
            { key: "product", label: "商品券" },
            { key: "points", label: "积分兑" },
          ].map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key as typeof activeTab)}
              className={cn(
                "flex-1 py-3 text-sm font-medium relative transition-colors",
                activeTab === tab.key ? "text-primary" : "text-muted-foreground"
              )}
            >
              {tab.label}
              {activeTab === tab.key && (
                <span className="absolute bottom-0 left-1/2 -translate-x-1/2 w-8 h-0.5 bg-primary rounded-full" />
              )}
            </button>
          ))}
        </div>
      </div>

      {/* 内容区 */}
      <main className="p-4 pb-24 space-y-4">
        {activeTab === "points" ? (
          <>
            <div className="text-sm text-muted-foreground mb-2">可用积分：{userPoints}</div>
            <div className="space-y-3">
              {pointsCoupons.map((coupon) => {
                const canExchange = userPoints >= coupon.points
                const isReceived = receivedIds.includes(coupon.id)
                const style = typeStyles[coupon.type]
                return (
                  <Card key={coupon.id} className="p-3 flex items-center gap-3">
                    <div className={cn("w-16 h-16 rounded-lg flex flex-col items-center justify-center text-primary-foreground", style.accent)}>
                      <CouponValue type={coupon.type} amount={coupon.amount} size="sm" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-sm truncate">{coupon.scope}</h4>
                      <p className="text-xs text-muted-foreground">
                        {coupon.minAmount ? `满${coupon.minAmount}可用` : "无门槛"}
                      </p>
                      <p className="text-xs text-gold mt-1 flex items-center gap-1">
                        <Coins className="w-3 h-3" />
                        {coupon.points} 积分
                      </p>
                    </div>
                    <Button
                      size="sm"
                      variant={canExchange && !isReceived ? "default" : "outline"}
                      disabled={!canExchange || isReceived}
                      onClick={() => handleReceive(coupon.id)}
                      className="h-8 px-3 text-xs"
                    >
                      {isReceived ? <><Check className="w-3 h-3 mr-1" />已兑换</> : canExchange ? "兑换" : "积分不足"}
                    </Button>
                  </Card>
                )
              })}
            </div>

            {/* 会员专属券 */}
            <div className="mt-6">
              <div className="flex items-center gap-2 mb-3">
                <Crown className="w-4 h-4 text-gold" />
                <span className="font-bold text-sm">会员专属券</span>
              </div>
              <div className="space-y-3">
                {vipCoupons.map((coupon) => {
                  const canGet = userVipLevel >= coupon.vipLevel
                  const isReceived = receivedIds.includes(coupon.id)
                  return (
                    <Card key={coupon.id} className={cn("p-3 relative overflow-hidden border-gold/40", !canGet && "opacity-60")}>
                      <div className="flex items-center gap-3">
                        <div className="w-16 h-16 rounded-lg bg-gradient-to-br from-gold to-[#b8965a] flex flex-col items-center justify-center text-gold-foreground">
                          <CouponValue type={coupon.type} amount={coupon.amount} size="sm" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <h4 className="font-medium text-sm truncate">{coupon.scope}</h4>
                          <p className="text-xs text-muted-foreground">
                            {coupon.minAmount ? `满${coupon.minAmount}可用` : "无门槛"}
                          </p>
                          <Badge className="mt-1 text-[10px] px-1.5 py-0 bg-gold text-gold-foreground border-0 flex items-center gap-0.5 w-fit">
                            <Crown className="w-2.5 h-2.5" />VIP{coupon.vipLevel}专享
                          </Badge>
                        </div>
                        <Button
                          size="sm"
                          variant={canGet && !isReceived ? "default" : "outline"}
                          disabled={!canGet || isReceived}
                          onClick={() => handleReceive(coupon.id)}
                          className="h-8 px-3 text-xs"
                        >
                          {isReceived ? <><Check className="w-3 h-3 mr-1" />已领取</> : canGet ? "领取" : `需VIP${coupon.vipLevel}`}
                        </Button>
                      </div>
                    </Card>
                  )
                })}
              </div>
            </div>
          </>
        ) : (
          // 普通优惠券列表
          <div className="space-y-3">
            {filteredCoupons.map((coupon) => {
              const isReceived = receivedIds.includes(coupon.id)
              const style = typeStyles[coupon.type]
              return (
                <div key={coupon.id} className="relative overflow-hidden rounded-xl h-24 shadow-sm">
                  {/* 左侧色块背景 */}
                  <div className={cn("absolute inset-y-0 left-0 w-[32%]", style.accent)} />

                  {/* 剪口 */}
                  <div className="absolute left-[32%] top-0 bottom-0 -translate-x-1/2 flex flex-col justify-around py-1 z-10">
                    {[...Array(6)].map((_, i) => (
                      <div key={i} className="w-3 h-3 rounded-full bg-background" />
                    ))}
                  </div>

                  <div className="relative h-full flex">
                    {/* 左侧金额 */}
                    <div className="w-[32%] flex flex-col items-center justify-center text-primary-foreground">
                      <CouponValue type={coupon.type} amount={coupon.amount} />
                      <p className="text-[10px] text-primary-foreground/80 mt-0.5">
                        {coupon.minAmount ? `满${coupon.minAmount}可用` : "无门槛"}
                      </p>
                    </div>

                    {/* 右侧信息 */}
                    <div className="flex-1 flex items-center justify-between pl-6 pr-4 bg-card border border-l-0 border-border rounded-r-xl">
                      <div>
                        <div className="flex items-center gap-1.5 mb-1">
                          <Badge variant="outline" className={cn("text-[10px] px-1.5 py-0 border-0", style.badgeBg, style.badgeText)}>
                            {coupon.type}券
                          </Badge>
                          {coupon.tag && (
                            <Badge className={cn("text-[10px] px-1.5 py-0 border-0", tagStyles[coupon.tag] || "bg-primary text-primary-foreground")}>
                              {coupon.tag}
                            </Badge>
                          )}
                        </div>
                        <h4 className="font-medium text-sm mb-0.5">{coupon.scope}</h4>
                        <p className="text-[10px] text-muted-foreground flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {coupon.startDate} - {coupon.endDate}
                        </p>
                      </div>

                      {isReceived ? (
                        <Button size="sm" variant="outline" className={cn("h-8 px-4 text-xs border-current", style.text)}>
                          去使用
                        </Button>
                      ) : (
                        <Button size="sm" className={cn("h-8 px-4 text-xs text-primary-foreground border-0", style.accent)} onClick={() => handleReceive(coupon.id)}>
                          领取
                        </Button>
                      )}
                    </div>
                  </div>

                  {isReceived && (
                    <div className="absolute top-2 right-2 z-20">
                      <div className="w-6 h-6 rounded-full bg-success flex items-center justify-center">
                        <Check className="w-4 h-4 text-success-foreground" />
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </main>
    </div>
  )
}

// apps/mobile/.backup_vue3_converted/pages/coupons/center/index.vue
<template>
  <view class="min-h-screen bg-background max-w-lg mx-auto">
    <!-- 顶部 -->
    <view class="sticky top-0 z-50 text-white" style="background:linear-gradient(to bottom right,#C41E3A,#C41E3A,#C9A96E)">
      <view class="flex items-center justify-between px-4 h-12">
        <view @click="goBack" class="p-2 -ml-2">
          <text class="text-lg text-white">&#8592;</text>
        </view>
        <text class="font-bold flex items-center gap-1">
          <text>&#127873;</text>
          <text>领券中心</text>
        </text>
        <text @click="goTo('/pages/coupons/index')" class="text-xs text-white/80">我的券</text>
      </view>

      <!-- 积分入口 -->
      <view class="px-4 pb-4">
        <view class="bg-white/10 border border-white/20 rounded-xl p-3">
          <view class="flex items-center justify-between">
            <view class="flex items-center gap-3">
              <view class="w-10 h-10 rounded-full bg-amber-500/20 flex items-center justify-center">
                <text class="text-amber-400 text-lg">&#128176;</text>
              </view>
              <view>
                <text class="text-white/70 text-xs">我的积分</text>
                <text class="text-xl font-bold text-white block">{{ userPoints }}</text>
              </view>
            </view>
            <view class="px-3 py-1.5 bg-white/20 text-white text-xs font-medium rounded-full">
              兑换礼品
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- Tab切换 -->
    <view class="sticky top-[124px] z-40 bg-background border-b border-border">
      <view class="flex">
        <view v-for="tab in tabs" :key="tab.key" @click="activeTab = tab.key" :class="['flex-1 py-3 text-sm font-medium relative text-center transition-colors', activeTab === tab.key ? 'text-primary' : 'text-muted-foreground']">
          {{ tab.label }}
          <view v-if="activeTab === tab.key" class="absolute bottom-0 left-1/2 -translate-x-1/2 w-8 h-0.5 bg-primary rounded-full" />
        </view>
      </view>
    </view>

    <!-- 内容区 -->
    <view class="p-4 pb-32 space-y-4">
      <!-- 积分兑换区 -->
      <template v-if="activeTab === 'points'">
        <text class="text-sm text-muted-foreground mb-2 block">可用积分：{{ userPoints }}</text>
        <view class="space-y-3">
          <view v-for="coupon in pointsCoupons" :key="coupon.id" class="bg-white rounded-xl p-3 flex items-center gap-3">
            <!-- 券面值 -->
            <view class="w-16 h-16 rounded-lg flex flex-col items-center justify-center text-white" style="background:linear-gradient(to bottom right,#f59e0b,#f97316)">
              <template v-if="coupon.type === '折扣'">
                <text class="text-xl font-bold">{{ coupon.amount }}</text>
                <text class="text-[10px]">折</text>
              </template>
              <template v-else>
                <text class="text-[10px]">&#165;</text>
                <text class="text-xl font-bold">{{ coupon.amount }}</text>
              </template>
            </view>

            <!-- 信息 -->
            <view class="flex-1 min-w-0">
              <text class="font-medium text-sm line-clamp-1 block">{{ coupon.scope }}</text>
              <text class="text-xs text-muted-foreground block">{{ coupon.minAmount ? '满' + coupon.minAmount + '可用' : '无门槛' }}</text>
              <text class="text-xs text-amber-600 mt-1 flex items-center gap-1">
                <text>&#128176;</text>
                <text>{{ coupon.points }} 积分</text>
              </text>
            </view>

            <!-- 兑换/已兑换按钮 -->
            <view @click="handleReceive(coupon.id)" :class="['h-8 px-3 text-xs rounded-full flex items-center font-medium', canExchange(coupon) && !isReceived(coupon.id) ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground']">
              <template v-if="isReceived(coupon.id)">
                <text>&#10003;</text>
                <text class="ml-1">已兑换</text>
              </template>
              <template v-else-if="canExchange(coupon)">
                <text>兑换</text>
              </template>
              <template v-else>
                <text>积分不足</text>
              </template>
            </view>
          </view>
        </view>

        <!-- 会员专属券 -->
        <view class="mt-6">
          <view class="flex items-center gap-2 mb-3">
            <text class="text-amber-500 text-lg">&#128081;</text>
            <text class="font-bold text-sm">会员专属券</text>
          </view>
          <view class="space-y-3">
            <view v-for="coupon in vipCoupons" :key="coupon.id" :class="['bg-white rounded-xl p-3 relative overflow-hidden', userVipLevel < coupon.vipLevel ? 'opacity-60' : '']">
              <view class="flex items-center gap-3">
                <view class="w-16 h-16 rounded-lg flex flex-col items-center justify-center text-white" style="background:linear-gradient(to bottom right,#a855f7,#ec4899)">
                  <text class="text-[10px]">&#165;</text>
                  <text class="text-xl font-bold">{{ coupon.amount }}</text>
                </view>
                <view class="flex-1 min-w-0">
                  <text class="font-medium text-sm line-clamp-1 block">{{ coupon.scope }}</text>
                  <text class="text-xs text-muted-foreground block">{{ coupon.minAmount ? '满' + coupon.minAmount + '可用' : '无门槛' }}</text>
                  <text class="text-[10px] px-1.5 py-0.5 rounded mt-1 inline-block text-white" style="background:linear-gradient(to right,#f59e0b,#f97316)">VIP{{ coupon.vipLevel }}专享</text>
                </view>
                <view @click="handleReceive(coupon.id)" :class="['h-8 px-3 text-xs rounded-full flex items-center font-medium', canVipGet(coupon) && !isReceived(coupon.id) ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground']">
                  {{ isReceived(coupon.id) ? '已领取' : canVipGet(coupon) ? '领取' : '需VIP' + coupon.vipLevel }}
                </view>
              </view>
            </view>
          </view>
        </view>
      </template>

      <!-- 普通优惠券列表 -->
      <template v-else>
        <view class="space-y-3">
          <view v-for="coupon in filteredCoupons" :key="coupon.id" class="relative overflow-hidden rounded-xl h-24">
            <!-- 背景渐变 -->
            <view class="absolute inset-0" style="background:linear-gradient(to right,#C41E3A,#C41E3A,#C41E3A/0.9)" />

            <!-- 锯齿装饰 -->
            <view class="absolute right-[30%] top-0 bottom-0 flex flex-col justify-around py-2">
              <view v-for="i in 6" :key="i" class="w-3 h-3 rounded-full bg-background -mr-1.5" />
            </view>

            <view class="relative h-full flex">
              <!-- 左侧金额区 (30%) -->
              <view class="w-[30%] flex flex-col items-center justify-center text-white">
                <template v-if="coupon.type === '折扣'">
                  <view class="text-center">
                    <text class="text-3xl font-bold">{{ coupon.amount }}</text>
                    <text class="text-lg font-bold">折</text>
                  </view>
                </template>
                <template v-else>
                  <view class="text-center">
                    <text class="text-lg">&#165;</text>
                    <text class="text-3xl font-bold">{{ coupon.amount }}</text>
                  </view>
                </template>
                <text class="text-xs text-white/80 mt-0.5">{{ coupon.minAmount ? '满' + coupon.minAmount + '可用' : '无门槛' }}</text>
              </view>

              <!-- 右侧信息区 -->
              <view class="flex-1 flex items-center justify-between px-4 bg-white rounded-r-xl">
                <view>
                  <view class="flex items-center gap-1.5 mb-1">
                    <text class="text-[10px] px-1.5 py-0.5 rounded border text-primary" style="border-color:rgba(196,30,58,0.3)">{{ coupon.type }}券</text>
                    <text v-if="coupon.tag" :class="['text-[10px] px-1.5 py-0.5 rounded text-white', coupon.tag === '热门' ? 'bg-red-500' : coupon.tag === '限时' ? 'bg-orange-500' : coupon.tag === '新人' ? 'bg-green-500' : 'bg-primary']">{{ coupon.tag }}</text>
                  </view>
                  <text class="font-medium text-sm text-foreground block mb-0.5">{{ coupon.scope }}</text>
                  <text class="text-[10px] text-muted-foreground flex items-center gap-1">
                    <text>&#9200;</text>
                    <text>{{ coupon.startDate }} - {{ coupon.endDate }}</text>
                  </text>
                </view>

                <!-- 操作按钮 -->
                <template v-if="isReceived(coupon.id)">
                  <view @click="handleReceive(coupon.id)" class="h-8 px-4 text-xs rounded-full flex items-center font-medium border text-primary" style="border-color:rgba(196,30,58,0.3)">
                    <text>去使用</text>
                  </view>
                </template>
                <template v-else>
                  <view @click="handleReceive(coupon.id)" class="h-8 px-4 text-xs rounded-full flex items-center font-medium bg-primary text-white">
                    <text>领取</text>
                  </view>
                </template>
              </view>
            </view>

            <!-- 已领取绿色勾标记 -->
            <view v-if="isReceived(coupon.id)" class="absolute top-2 right-2">
              <view class="w-6 h-6 rounded-full bg-green-500 flex items-center justify-center">
                <text class="text-white text-sm">&#10003;</text>
              </view>
            </view>
          </view>
        </view>
      </template>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

function goBack() { uni.navigateBack() }
function goTo(url: string) { uni.navigateTo({ url }) }

interface Coupon {
  id: number
  amount: number
  type: string
  minAmount?: number
  scope: string
  startDate?: string
  endDate?: string
  tag?: string
}

interface PointsCoupon {
  id: number
  amount: number
  type: string
  minAmount?: number
  scope: string
  points: number
}

interface VipCoupon {
  id: number
  amount: number
  type: string
  minAmount?: number
  scope: string
  vipLevel: number
}

const availableCoupons: Coupon[] = [
  { id: 1, amount: 50, type: '满减', minAmount: 299, scope: '全部课程', startDate: '2026.05.10', endDate: '2026.06.30', tag: '热门' },
  { id: 2, amount: 20, type: '满减', minAmount: 99, scope: '全部商品', startDate: '2026.05.10', endDate: '2026.05.31', tag: '限时' },
  { id: 3, amount: 8, type: '折扣', scope: '指定课程', startDate: '2026.05.10', endDate: '2026.06.15', tag: '' },
  { id: 4, amount: 10, type: '无门槛', scope: '全部商品', startDate: '2026.05.10', endDate: '2026.05.20', tag: '新人' },
  { id: 5, amount: 100, type: '满减', minAmount: 599, scope: '精品课程', startDate: '2026.05.10', endDate: '2026.07.31', tag: '' },
]

const pointsCoupons: PointsCoupon[] = [
  { id: 101, amount: 5, type: '无门槛', scope: '全部商品', points: 500 },
  { id: 102, amount: 15, type: '满减', minAmount: 99, scope: '全部商品', points: 1000 },
  { id: 103, amount: 30, type: '满减', minAmount: 199, scope: '全部课程', points: 2000 },
]

const vipCoupons: VipCoupon[] = [
  { id: 201, amount: 88, type: '满减', minAmount: 388, scope: '全场通用', vipLevel: 2 },
  { id: 202, amount: 9, type: '折扣', scope: '精品课程', vipLevel: 3 },
]

const tabs = [
  { key: 'all' as const, label: '全部' },
  { key: 'course' as const, label: '课程券' },
  { key: 'product' as const, label: '商品券' },
  { key: 'points' as const, label: '积分兑' },
]

type TabKey = 'all' | 'course' | 'product' | 'points'

const receivedIds = ref<number[]>([])
const activeTab = ref<TabKey>('all')
const userPoints = 1580
const userVipLevel = 1

const handleReceive = (id: number) => {
  if (!receivedIds.value.includes(id)) {
    receivedIds.value.push(id)
  }
}

const isReceived = (id: number) => receivedIds.value.includes(id)
const canExchange = (coupon: PointsCoupon) => userPoints >= coupon.points
const canVipGet = (coupon: VipCoupon) => userVipLevel >= coupon.vipLevel

const filteredCoupons = computed(() => {
  return availableCoupons.filter(coupon => {
    if (activeTab.value === 'all') return true
    if (activeTab.value === 'course') return coupon.scope.includes('课程')
    if (activeTab.value === 'product') return coupon.scope.includes('商品')
    return true
  })
})
</script>

<style scoped>
</style>
