// app/mine/data-export/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { 
  ChevronLeft, 
  Download, 
  FileText, 
  MessageSquare, 
  Bookmark, 
  ShoppingBag, 
  GraduationCap, 
  BookOpen, 
  Users,
  User,
  Check,
  Clock,
  AlertCircle,
  RefreshCw,
  Info
} from 'lucide-react'

interface DataType {
  id: string
  name: string
  description: string
  icon: React.ReactNode
  estimatedSize: string
}

interface ExportRecord {
  id: string
  types: string[]
  status: 'processing' | 'completed' | 'expired' | 'failed'
  createdAt: string
  completedAt?: string
  expireAt?: string
  downloadUrl?: string
  fileSize?: string
}

const dataTypes: DataType[] = [
  { id: 'profile', name: '个人信息', description: '账号资料、头像、昵称、简介等', icon: <User className="w-5 h-5" />, estimatedSize: '< 1MB' },
  { id: 'posts', name: '帖子内容', description: '发布的圈子帖子、评论、回复', icon: <FileText className="w-5 h-5" />, estimatedSize: '约 5MB' },
  { id: 'comments', name: '评论互动', description: '课程评论、视频评论、点赞记录', icon: <MessageSquare className="w-5 h-5" />, estimatedSize: '约 2MB' },
  { id: 'favorites', name: '收藏内容', description: '收藏的课程、帖子、商品等', icon: <Bookmark className="w-5 h-5" />, estimatedSize: '约 1MB' },
  { id: 'orders', name: '订单数据', description: '购买记录、支付信息、发票', icon: <ShoppingBag className="w-5 h-5" />, estimatedSize: '约 3MB' },
  { id: 'learning', name: '学习记录', description: '课程进度、学习时长、测验成绩', icon: <GraduationCap className="w-5 h-5" />, estimatedSize: '约 2MB' },
  { id: 'notes', name: '笔记内容', description: '课程笔记、批注、高亮标记', icon: <BookOpen className="w-5 h-5" />, estimatedSize: '约 4MB' },
  { id: 'follows', name: '关注列表', description: '关注的用户、圈子、讲师', icon: <Users className="w-5 h-5" />, estimatedSize: '< 1MB' },
]

export default function DataExportPage() {
  const router = useRouter()
  const [selectedTypes, setSelectedTypes] = useState<string[]>([])
  const [records, setRecords] = useState<ExportRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [activeTab, setActiveTab] = useState<'create' | 'records'>('create')

  useEffect(() => {
    // 模拟加载导出记录
    setTimeout(() => {
      setRecords([
        {
          id: '1',
          types: ['profile', 'posts', 'comments'],
          status: 'completed',
          createdAt: '2026-06-01T10:30:00',
          completedAt: '2026-06-01T10:35:00',
          expireAt: '2026-06-08T10:35:00',
          downloadUrl: '/api/export/download/1',
          fileSize: '8.2MB'
        },
        {
          id: '2',
          types: ['orders', 'learning'],
          status: 'processing',
          createdAt: '2026-06-03T08:00:00',
        },
        {
          id: '3',
          types: ['profile', 'favorites', 'notes', 'follows'],
          status: 'expired',
          createdAt: '2026-05-20T14:00:00',
          completedAt: '2026-05-20T14:10:00',
          expireAt: '2026-05-27T14:10:00',
        },
      ])
      setLoading(false)
    }, 500)
  }, [])

  const toggleType = (typeId: string) => {
    setSelectedTypes(prev => 
      prev.includes(typeId) 
        ? prev.filter(id => id !== typeId)
        : [...prev, typeId]
    )
  }

  const selectAll = () => {
    if (selectedTypes.length === dataTypes.length) {
      setSelectedTypes([])
    } else {
      setSelectedTypes(dataTypes.map(t => t.id))
    }
  }

  const handleSubmit = async () => {
    if (selectedTypes.length === 0) return
    setSubmitting(true)
    
    // 模拟提交
    setTimeout(() => {
      const newRecord: ExportRecord = {
        id: Date.now().toString(),
        types: selectedTypes,
        status: 'processing',
        createdAt: new Date().toISOString(),
      }
      setRecords(prev => [newRecord, ...prev])
      setSelectedTypes([])
      setSubmitting(false)
      setActiveTab('records')
    }, 1000)
  }

  const getStatusConfig = (status: ExportRecord['status']) => {
    switch (status) {
      case 'processing':
        return { label: '处理中', color: 'text-blue-600 bg-blue-50', icon: <RefreshCw className="w-4 h-4 animate-spin" /> }
      case 'completed':
        return { label: '已完成', color: 'text-green-600 bg-green-50', icon: <Check className="w-4 h-4" /> }
      case 'expired':
        return { label: '已过期', color: 'text-gray-500 bg-gray-100', icon: <Clock className="w-4 h-4" /> }
      case 'failed':
        return { label: '失败', color: 'text-red-600 bg-red-50', icon: <AlertCircle className="w-4 h-4" /> }
    }
  }

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr)
    return `${date.getMonth() + 1}月${date.getDate()}日 ${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`
  }

  const getTypeNames = (typeIds: string[]) => {
    return typeIds.map(id => dataTypes.find(t => t.id === id)?.name || id).join('、')
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 导航栏 */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between h-14 px-4">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <span className="font-medium">数据导出</span>
          <div className="w-9" />
        </div>
      </div>

      {/* Tab 切换 */}
      <div className="flex border-b border-border">
        <button
          onClick={() => setActiveTab('create')}
          className={`flex-1 py-3 text-sm font-medium border-b-2 transition-colors ${
            activeTab === 'create' 
              ? 'text-[#C41E3A] border-[#C41E3A]' 
              : 'text-muted-foreground border-transparent'
          }`}
        >
          申请导出
        </button>
        <button
          onClick={() => setActiveTab('records')}
          className={`flex-1 py-3 text-sm font-medium border-b-2 transition-colors ${
            activeTab === 'records' 
              ? 'text-[#C41E3A] border-[#C41E3A]' 
              : 'text-muted-foreground border-transparent'
          }`}
        >
          导出记录
          {records.filter(r => r.status === 'completed').length > 0 && (
            <span className="ml-1 px-1.5 py-0.5 text-xs bg-[#C41E3A] text-white rounded-full">
              {records.filter(r => r.status === 'completed').length}
            </span>
          )}
        </button>
      </div>

      {activeTab === 'create' ? (
        <div className="p-4 space-y-4">
          {/* 说明卡片 */}
          <div className="flex gap-3 p-4 bg-blue-50 rounded-xl">
            <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-blue-800">
              <p className="font-medium mb-1">数据导出说明</p>
              <ul className="space-y-1 text-blue-700">
                <li>• 导出文件为 ZIP 压缩包格式</li>
                <li>• 处理时间约 5-30 分钟，完成后通知您</li>
                <li>• 文件有效期 7 天，请及时下载</li>
                <li>• 每月最多申请 3 次导出</li>
              </ul>
            </div>
          </div>

          {/* 数据类型选择 */}
          <div className="bg-card rounded-2xl overflow-hidden">
            <div className="flex items-center justify-between p-4 border-b border-border">
              <span className="font-medium">选择导出数据</span>
              <button
                onClick={selectAll}
                className="text-sm text-[#C41E3A]"
              >
                {selectedTypes.length === dataTypes.length ? '取消全选' : '全选'}
              </button>
            </div>
            
            <div className="divide-y divide-border">
              {dataTypes.map(type => (
                <button
                  key={type.id}
                  onClick={() => toggleType(type.id)}
                  className="w-full flex items-center gap-3 p-4 text-left hover:bg-muted/50 transition-colors"
                >
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                    selectedTypes.includes(type.id) ? 'bg-[#C41E3A] text-white' : 'bg-muted text-muted-foreground'
                  }`}>
                    {type.icon}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium">{type.name}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">{type.description}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-muted-foreground">{type.estimatedSize}</span>
                    <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center transition-colors ${
                      selectedTypes.includes(type.id) 
                        ? 'bg-[#C41E3A] border-[#C41E3A]' 
                        : 'border-muted-foreground/30'
                    }`}>
                      {selectedTypes.includes(type.id) && (
                        <Check className="w-3 h-3 text-white" />
                      )}
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* 预估大小 */}
          {selectedTypes.length > 0 && (
            <div className="flex items-center justify-between p-4 bg-muted/50 rounded-xl">
              <span className="text-sm text-muted-foreground">
                已选 {selectedTypes.length} 项数据
              </span>
              <span className="text-sm font-medium">
                预估大小: 约 {selectedTypes.length * 2}MB
              </span>
            </div>
          )}
        </div>
      ) : (
        <div className="p-4">
          {loading ? (
            <div className="space-y-4">
              {[1, 2, 3].map(i => (
                <div key={i} className="bg-card rounded-2xl p-4 animate-pulse">
                  <div className="h-5 w-24 bg-muted rounded mb-3" />
                  <div className="h-4 w-48 bg-muted rounded mb-2" />
                  <div className="h-4 w-32 bg-muted rounded" />
                </div>
              ))}
            </div>
          ) : records.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16">
              <div className="w-20 h-20 rounded-full bg-muted flex items-center justify-center mb-4">
                <Download className="w-8 h-8 text-muted-foreground" />
              </div>
              <p className="text-muted-foreground mb-4">暂无导出记录</p>
              <button
                onClick={() => setActiveTab('create')}
                className="text-[#C41E3A] text-sm"
              >
                去申请导出
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {records.map(record => {
                const statusConfig = getStatusConfig(record.status)
                return (
                  <div key={record.id} className="bg-card rounded-2xl p-4">
                    <div className="flex items-start justify-between mb-3">
                      <div className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${statusConfig.color}`}>
                        {statusConfig.icon}
                        {statusConfig.label}
                      </div>
                      <span className="text-xs text-muted-foreground">
                        {formatDate(record.createdAt)}
                      </span>
                    </div>
                    
                    <p className="text-sm mb-2">
                      {getTypeNames(record.types)}
                    </p>
                    
                    {record.status === 'completed' && record.expireAt && (
                      <p className="text-xs text-muted-foreground mb-3">
                        文件大小: {record.fileSize} · 有效期至 {formatDate(record.expireAt)}
                      </p>
                    )}
                    
                    {record.status === 'processing' && (
                      <div className="flex items-center gap-2 text-xs text-blue-600">
                        <div className="w-full h-1.5 bg-blue-100 rounded-full overflow-hidden">
                          <div className="h-full w-1/3 bg-blue-500 rounded-full animate-pulse" />
                        </div>
                        <span>处理中...</span>
                      </div>
                    )}
                    
                    {record.status === 'completed' && (
                      <button
                        onClick={() => window.open(record.downloadUrl, '_blank')}
                        className="w-full mt-3 py-2.5 bg-[#C41E3A] text-white rounded-xl text-sm font-medium flex items-center justify-center gap-2"
                      >
                        <Download className="w-4 h-4" />
                        下载文件
                      </button>
                    )}
                    
                    {record.status === 'expired' && (
                      <button
                        onClick={() => {
                          setSelectedTypes(record.types)
                          setActiveTab('create')
                        }}
                        className="w-full mt-3 py-2.5 bg-muted text-foreground rounded-xl text-sm font-medium"
                      >
                        重新申请
                      </button>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}

      {/* 底部提交按钮 */}
      {activeTab === 'create' && (
        <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t border-border">
          <button
            onClick={handleSubmit}
            disabled={selectedTypes.length === 0 || submitting}
            className="w-full py-3.5 bg-[#C41E3A] text-white rounded-xl font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {submitting ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                提交中...
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                申请导出 ({selectedTypes.length} 项)
              </>
            )}
          </button>
        </div>
      )}

      {/* 底部占位 */}
      {activeTab === 'create' && <div className="h-24" />}
    </div>
  )
}

// apps/mobile/src/pages/mine/data-export.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="header">
      <view class="header-inner">
        <text
          class="back-btn"
          @click="goBack"
        >
          ←
        </text>
        <text class="header-title">
          数据导出
        </text>
        <view class="header-right" />
      </view>
    </view>

    <!-- Tab 切换 -->
    <view class="tabs">
      <view
        class="tab"
        :class="{ active: activeTab === 'create' }"
        @click="switchTab('create')"
      >
        申请导出
      </view>
      <view
        class="tab"
        :class="{ active: activeTab === 'records' }"
        @click="switchTab('records')"
      >
        导出记录
        <text
          v-if="completedCount > 0"
          class="tab-badge"
        >
          {{ completedCount }}
        </text>
      </view>
    </view>

    <!-- 申请导出 -->
    <view
      v-if="activeTab === 'create'"
      class="create-content"
    >
      <!-- 说明卡片 -->
      <view class="info-card">
        <text class="info-icon">
          ℹ️
        </text>
        <view class="info-body">
          <text class="info-title">
            数据导出说明
          </text>
          <text class="info-item">
            • 导出文件为 ZIP 压缩包格式
          </text>
          <text class="info-item">
            • 处理时间约 5-30 分钟，完成后通知您
          </text>
          <text class="info-item">
            • 文件有效期 7 天，请及时下载
          </text>
          <text class="info-item">
            • 每月最多申请 3 次导出
          </text>
        </view>
      </view>

      <!-- 数据类型选择 -->
      <view class="type-card">
        <view class="type-header">
          <text class="type-title">
            选择导出数据
          </text>
          <text
            class="type-select-all"
            @click="toggleSelectAll"
          >
            {{ selectedTypes.length === dataTypes.length ? '取消全选' : '全选' }}
          </text>
        </view>

        <view class="type-list">
          <view
            v-for="t in dataTypes"
            :key="t.id"
            class="type-item"
            @click="toggleType(t.id)"
          >
            <view
              class="type-icon-wrap"
              :class="{ selected: selectedTypes.includes(t.id) }"
            >
              <text class="type-icon">
                {{ t.icon }}
              </text>
            </view>
            <view class="type-info">
              <text class="type-name">
                {{ t.name }}
              </text>
              <text class="type-desc">
                {{ t.desc }}
              </text>
            </view>
            <view class="type-right">
              <text class="type-size">
                {{ t.size }}
              </text>
              <view
                class="type-check"
                :class="{ checked: selectedTypes.includes(t.id) }"
              >
                <text
                  v-if="selectedTypes.includes(t.id)"
                  class="type-check-mark"
                >
                  ✓
                </text>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 预估大小 -->
      <view
        v-if="selectedTypes.length > 0"
        class="estimate-bar"
      >
        <text class="estimate-text">
          已选 {{ selectedTypes.length }} 项数据
        </text>
        <text class="estimate-size">
          预估大小：约 {{ selectedTypes.length * 2 }}MB
        </text>
      </view>

      <!-- 底部提交 -->
      <view class="bottom-action">
        <view
          class="btn-submit"
          :class="{ disabled: submitting || selectedTypes.length === 0 }"
          @click="handleSubmit"
        >
          {{ submitting ? '提交中...' : '申请导出（' + selectedTypes.length + ' 项）' }}
        </view>
      </view>
      <view class="bottom-spacer" />
    </view>

    <!-- 导出记录 -->
    <view
      v-if="activeTab === 'records'"
      class="records-content"
    >
      <DataState
        :is-loading="loading"
        :error="loadError"
        :is-empty="!loading && records.length === 0"
        empty-icon="📥"
        empty-title="暂无导出记录"
        empty-description="还没有导出记录"
        empty-action-text="去申请导出"
        :empty-show-action="true"
        skeleton-type="card"
        @retry="loadRecords"
        @empty-action="switchTab('create')"
      >
        <view class="records-list">
          <view
            v-for="record in records"
            :key="record.id"
            class="record-card"
          >
            <view class="record-top">
              <view
                class="record-status"
                :class="'rs-' + record.status"
              >
                <text class="record-status-icon">
                  {{ statusIcon(record.status) }}
                </text>
                <text class="record-status-label">
                  {{ statusLabel(record.status) }}
                </text>
              </view>
              <text class="record-date">
                {{ formatDate(record.createdAt) }}
              </text>
            </view>

            <text class="record-types">
              {{ getTypeNames(record.types) }}
            </text>

            <text
              v-if="record.status === 'completed' && record.fileSize"
              class="record-meta"
            >
              文件大小：{{ record.fileSize }} · 有效期至 {{ formatDate(record.expireAt) }}
            </text>

            <!-- 处理中进度条 -->
            <view
              v-if="record.status === 'processing'"
              class="record-progress"
            >
              <view class="progress-track">
                <view class="progress-bar" />
              </view>
              <text class="progress-text">
                处理中...
              </text>
            </view>

            <!-- 已完成 -->
            <view
              v-if="record.status === 'completed'"
              class="record-download"
              @click="handleDownload(record)"
            >
              ⬇ 下载文件
            </view>

            <!-- 已过期 -->
            <view
              v-if="record.status === 'expired'"
              class="record-reapply"
              @click="reapply(record)"
            >
              重新申请
            </view>
          </view>
        </view>
      </DataState>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import DataState from '../../components/DataState.vue'

interface DataType {
  id: string
  name: string
  desc: string
  icon: string
  size: string
}

interface ExportRecord {
  id: string
  types: string[]
  status: 'processing' | 'completed' | 'expired' | 'failed'
  createdAt: string
  completedAt?: string
  expireAt?: string
  downloadUrl?: string
  fileSize?: string
}

const dataTypes: DataType[] = [
  { id: 'profile', name: '个人信息', desc: '账号资料、头像、昵称、简介等', icon: '👤', size: '< 1MB' },
  { id: 'posts', name: '帖子内容', desc: '发布的圈子帖子、评论、回复', icon: '📄', size: '约 5MB' },
  { id: 'comments', name: '评论互动', desc: '课程评论、视频评论、点赞记录', icon: '💬', size: '约 2MB' },
  { id: 'favorites', name: '收藏内容', desc: '收藏的课程、帖子、商品等', icon: '⭐', size: '约 1MB' },
  { id: 'orders', name: '订单数据', desc: '购买记录、支付信息、发票', icon: '🛍', size: '约 3MB' },
  { id: 'learning', name: '学习记录', desc: '课程进度、学习时长、测验成绩', icon: '🎓', size: '约 2MB' },
  { id: 'notes', name: '笔记内容', desc: '课程笔记、批注、高亮标记', icon: '📖', size: '约 4MB' },
  { id: 'follows', name: '关注列表', desc: '关注的用户、圈子、讲师', icon: '👥', size: '< 1MB' },
]

const activeTab = ref<'create' | 'records'>('create')
const selectedTypes = ref<string[]>([])
const records = ref<ExportRecord[]>([])
const loading = ref(true)
const loadError = ref<string | null>(null)
const submitting = ref(false)

const completedCount = ref(0)

function switchTab(tab: 'create' | 'records') {
  activeTab.value = tab
  if (tab === 'records' && records.value.length === 0) {
    loadRecords()
  }
}

function toggleType(id: string) {
  const idx = selectedTypes.value.indexOf(id)
  if (idx >= 0) {
    selectedTypes.value.splice(idx, 1)
  } else {
    selectedTypes.value.push(id)
  }
}

function toggleSelectAll() {
  if (selectedTypes.value.length === dataTypes.length) {
    selectedTypes.value = []
  } else {
    selectedTypes.value = dataTypes.map((t) => t.id)
  }
}

async function loadRecords() {
  loading.value = true
  loadError.value = null
  try {
    await new Promise((r) => setTimeout(r, 500))
    records.value = [
      {
        id: '1', types: ['profile', 'posts', 'comments'], status: 'completed',
        createdAt: '2026-06-01T10:30:00', completedAt: '2026-06-01T10:35:00',
        expireAt: '2026-06-08T10:35:00', downloadUrl: '/api/export/download/1', fileSize: '8.2MB',
      },
      {
        id: '2', types: ['orders', 'learning'], status: 'processing',
        createdAt: '2026-06-03T08:00:00',
      },
      {
        id: '3', types: ['profile', 'favorites', 'notes', 'follows'], status: 'expired',
        createdAt: '2026-05-20T14:00:00', completedAt: '2026-05-20T14:10:00',
        expireAt: '2026-05-27T14:10:00',
      },
    ]
    completedCount.value = records.value.filter((r) => r.status === 'completed').length
  } catch (e: any) {
    loadError.value = e?.errMsg || e?.message || '加载失败'
  } finally {
    loading.value = false
  }
}

async function handleSubmit() {
  if (selectedTypes.value.length === 0) return
  submitting.value = true
  await new Promise((r) => setTimeout(r, 1000))
  const newRecord: ExportRecord = {
    id: Date.now().toString(),
    types: [...selectedTypes.value],
    status: 'processing',
    createdAt: new Date().toISOString(),
  }
  records.value.unshift(newRecord)
  selectedTypes.value = []
  submitting.value = false
  activeTab.value = 'records'
  uni.showToast({ title: '导出申请已提交', icon: 'success' })
}

function statusLabel(status: string) {
  const map: Record<string, string> = { processing: '处理中', completed: '已完成', expired: '已过期', failed: '失败' }
  return map[status] || status
}

function statusIcon(status: string) {
  const map: Record<string, string> = { processing: '⏳', completed: '✅', expired: '🕐', failed: '❌' }
  return map[status] || '❓'
}

function formatDate(dateStr: string) {
  if (!dateStr) return ''
  const d = new Date(dateStr)
  return (d.getMonth() + 1) + '月' + d.getDate() + '日 ' +
    String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0')
}

function getTypeNames(typeIds: string[]) {
  return typeIds.map((id) => dataTypes.find((t) => t.id === id)?.name || id).join('、')
}

function handleDownload(record: ExportRecord) {
  uni.showToast({ title: '开始下载', icon: 'success' })
}

function reapply(record: ExportRecord) {
  selectedTypes.value = [...record.types]
  activeTab.value = 'create'
}

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
.page {
  background: #F5F0E8;
  min-height: 100vh;
}

/* 顶部导航 */
.header {
  background: #fff;
  border-bottom: 1rpx solid #E8E3DB;
}
.header-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 88rpx;
  padding: 0 24rpx;
}
.back-btn { font-size: 36rpx; color: #2C2C2C; padding: 8rpx; }
.header-title { font-size: 34rpx; font-weight: 600; color: #2C2C2C; }
.header-right { width: 80rpx; }

/* Tabs */
.tabs {
  display: flex;
  background: #fff;
  border-bottom: 1rpx solid #E8E3DB;
}
.tab {
  flex: 1;
  height: 88rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 26rpx;
  color: #999;
  border-bottom: 3rpx solid transparent;
  transition: all 0.2s;
}
.tab.active {
  color: #C41E3A;
  border-bottom-color: #C41E3A;
  font-weight: 500;
}
.tab-badge {
  margin-left: 6rpx;
  padding: 2rpx 12rpx;
  font-size: 18rpx;
  color: #fff;
  background: #C41E3A;
  border-radius: 20rpx;
}

/* 申请导出 */
.create-content { padding: 24rpx; }

.info-card {
  display: flex;
  gap: 16rpx;
  background: #E3F2FD;
  border: 1rpx solid #90CAF9;
  border-radius: 20rpx;
  padding: 24rpx;
  margin-bottom: 24rpx;
}
.info-icon { font-size: 32rpx; flex-shrink: 0; margin-top: 2rpx; }
.info-body { flex: 1; }
.info-title { font-size: 26rpx; font-weight: 500; color: #1565C0; display: block; margin-bottom: 8rpx; }
.info-item { font-size: 22rpx; color: #1976D2; display: block; line-height: 1.7; }

.type-card {
  background: #fff;
  border-radius: 24rpx;
  overflow: hidden;
  margin-bottom: 24rpx;
}
.type-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 28rpx 24rpx;
  border-bottom: 1rpx solid #F5F0E8;
}
.type-title { font-size: 26rpx; font-weight: 600; color: #2C2C2C; }
.type-select-all { font-size: 24rpx; color: #C41E3A; }

.type-item {
  display: flex;
  align-items: center;
  gap: 16rpx;
  padding: 24rpx;
  border-bottom: 1rpx solid #F5F0E8;
}
.type-item:last-child { border-bottom: none; }
.type-icon-wrap {
  width: 80rpx;
  height: 80rpx;
  border-radius: 16rpx;
  background: #F5F0E8;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  transition: all 0.2s;
}
.type-icon-wrap.selected {
  background: #C41E3A;
}
.type-icon { font-size: 32rpx; }
.type-info { flex: 1; min-width: 0; }
.type-name { font-size: 26rpx; font-weight: 500; color: #2C2C2C; display: block; }
.type-desc { font-size: 22rpx; color: #999; margin-top: 4rpx; display: block; }
.type-right { display: flex; align-items: center; gap: 12rpx; flex-shrink: 0; }
.type-size { font-size: 20rpx; color: #B8B0A4; }
.type-check {
  width: 40rpx;
  height: 40rpx;
  border-radius: 50%;
  border: 2rpx solid #D0C8B8;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
}
.type-check.checked {
  background: #C41E3A;
  border-color: #C41E3A;
}
.type-check-mark { font-size: 22rpx; color: #fff; font-weight: bold; }

.estimate-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: #FAF8F5;
  border-radius: 16rpx;
  padding: 20rpx 24rpx;
  margin-bottom: 24rpx;
}
.estimate-text { font-size: 24rpx; color: #666; }
.estimate-size { font-size: 24rpx; font-weight: 500; color: #2C2C2C; }

.bottom-action {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 20rpx 24rpx;
  background: #F5F0E8;
  border-top: 1rpx solid #E8E3DB;
}
.btn-submit {
  width: 100%;
  height: 88rpx;
  border-radius: 44rpx;
  background: #C41E3A;
  color: #fff;
  font-size: 28rpx;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
}
.btn-submit.disabled { opacity: 0.5; }
.bottom-spacer { height: 140rpx; }

/* 导出记录 */
.records-content { padding: 24rpx; }
.records-list { display: flex; flex-direction: column; gap: 16rpx; }
.record-card {
  background: #fff;
  border-radius: 20rpx;
  padding: 24rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
}
.record-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12rpx;
}
.record-status {
  display: inline-flex;
  align-items: center;
  gap: 6rpx;
  padding: 4rpx 16rpx;
  border-radius: 20rpx;
  font-size: 20rpx;
  font-weight: 500;
}
.record-status-icon { font-size: 22rpx; }
.record-status-label { font-size: 22rpx; }
.rs-processing { background: #E3F2FD; color: #1976D2; }
.rs-completed { background: #E8F5E9; color: #22C55E; }
.rs-expired { background: #F5F5F5; color: #999; }
.rs-failed { background: #FFEBEE; color: #EF4444; }
.record-date { font-size: 22rpx; color: #B8B0A4; }
.record-types { font-size: 24rpx; color: #2C2C2C; display: block; margin-bottom: 8rpx; }
.record-meta { font-size: 20rpx; color: #B8B0A4; display: block; }

.record-progress {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-top: 12rpx;
}
.progress-track {
  flex: 1;
  height: 12rpx;
  background: #E3F2FD;
  border-radius: 10rpx;
  overflow: hidden;
}
.progress-bar {
  width: 30%;
  height: 100%;
  background: #1976D2;
  border-radius: 10rpx;
  animation: pulse 1.5s ease-in-out infinite;
}
.progress-text { font-size: 20rpx; color: #1976D2; white-space: nowrap; }

.record-download {
  width: 100%;
  height: 72rpx;
  background: #C41E3A;
  color: #fff;
  border-radius: 16rpx;
  font-size: 24rpx;
  font-weight: 500;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 16rpx;
}
.record-reapply {
  width: 100%;
  height: 72rpx;
  background: #F5F0E8;
  color: #666;
  border-radius: 16rpx;
  font-size: 24rpx;
  font-weight: 500;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 16rpx;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}
</style>
