// app/mine/history/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { 
  ChevronLeft, 
  Trash2, 
  BookOpen, 
  Video, 
  Radio, 
  FileText, 
  ShoppingBag,
  Play,
  X,
  Clock,
  Calendar
} from 'lucide-react'

interface HistoryItem {
  id: string
  type: 'course' | 'video' | 'live' | 'article' | 'product' | 'circle'
  title: string
  cover?: string
  progress?: number
  duration?: number
  viewedAt: string
}

interface HistoryGroup {
  date: string
  label: string
  items: HistoryItem[]
}

const typeConfig = {
  course: { icon: BookOpen, label: '课程', color: 'bg-blue-500' },
  video: { icon: Video, label: '视频', color: 'bg-pink-500' },
  live: { icon: Radio, label: '直播', color: 'bg-red-500' },
  article: { icon: FileText, label: '文章', color: 'bg-green-500' },
  product: { icon: ShoppingBag, label: '商品', color: 'bg-orange-500' },
  circle: { icon: BookOpen, label: '圈子', color: 'bg-purple-500' },
}

export default function BrowseHistoryPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [historyGroups, setHistoryGroups] = useState<HistoryGroup[]>([])
  const [showClearConfirm, setShowClearConfirm] = useState(false)
  const [deletingId, setDeletingId] = useState<string | null>(null)

  useEffect(() => {
    setTimeout(() => {
      setHistoryGroups([
        {
          date: '2024-01-15',
          label: '今天',
          items: [
            { id: '1', type: 'course', title: '周易入门：从零开始学习易经', cover: '/api/placeholder/120/80', progress: 45, duration: 3600, viewedAt: '14:30' },
            { id: '2', type: 'video', title: '梅花易数实战案例分析', cover: '/api/placeholder/120/80', progress: 100, duration: 1200, viewedAt: '12:15' },
            { id: '3', type: 'article', title: '八字命理中的十神详解', viewedAt: '10:20' },
          ]
        },
        {
          date: '2024-01-14',
          label: '昨天',
          items: [
            { id: '4', type: 'live', title: '风水布局直播答疑', cover: '/api/placeholder/120/80', viewedAt: '20:00' },
            { id: '5', type: 'product', title: '开光铜葫芦摆件', cover: '/api/placeholder/120/80', viewedAt: '16:45' },
          ]
        },
        {
          date: '2024-01-12',
          label: '1月12日',
          items: [
            { id: '6', type: 'course', title: '六爻预测高级班', cover: '/api/placeholder/120/80', progress: 30, duration: 7200, viewedAt: '19:30' },
            { id: '7', type: 'circle', title: '易学爱好者交流圈', cover: '/api/placeholder/120/80', viewedAt: '15:00' },
            { id: '8', type: 'article', title: '紫微斗数入门指南', viewedAt: '11:20' },
          ]
        },
      ])
      setLoading(false)
    }, 800)
  }, [])

  const handleDelete = (itemId: string) => {
    setHistoryGroups(prev => prev.map(group => ({
      ...group,
      items: group.items.filter(item => item.id !== itemId)
    })).filter(group => group.items.length > 0))
    setDeletingId(null)
  }

  const handleClearAll = () => {
    setHistoryGroups([])
    setShowClearConfirm(false)
  }

  const handleItemClick = (item: HistoryItem) => {
    const routes: Record<string, string> = {
      course: `/courses/${item.id}`,
      video: `/videos/${item.id}`,
      live: `/live/${item.id}`,
      article: `/articles/${item.id}`,
      product: `/shop/product/${item.id}`,
      circle: `/circles/${item.id}`,
    }
    router.push(routes[item.type] || '/')
  }

  const formatProgress = (progress: number, duration: number) => {
    if (progress >= 100) return '已看完'
    const watched = Math.floor((progress / 100) * duration)
    const minutes = Math.floor(watched / 60)
    return `已观看 ${minutes} 分钟`
  }

  const totalCount = historyGroups.reduce((sum, g) => sum + g.items.length, 0)

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between h-14 px-4">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <h1 className="font-semibold">浏览历史</h1>
          {totalCount > 0 ? (
            <button 
              onClick={() => setShowClearConfirm(true)}
              className="text-sm text-red-500"
            >
              清空
            </button>
          ) : (
            <div className="w-10" />
          )}
        </div>
      </div>

      {/* Stats Bar */}
      {totalCount > 0 && (
        <div className="px-4 py-3 bg-muted/50 flex items-center gap-4 text-sm">
          <div className="flex items-center gap-1.5 text-muted-foreground">
            <Clock className="w-4 h-4" />
            <span>共 {totalCount} 条记录</span>
          </div>
          <div className="flex items-center gap-1.5 text-muted-foreground">
            <Calendar className="w-4 h-4" />
            <span>近30天</span>
          </div>
        </div>
      )}

      {/* Content */}
      {loading ? (
        <div className="p-4 space-y-6">
          {[1, 2].map(g => (
            <div key={g} className="space-y-3">
              <div className="h-5 w-16 bg-muted rounded animate-pulse" />
              {[1, 2, 3].map(i => (
                <div key={i} className="flex gap-3 animate-pulse">
                  <div className="w-24 h-16 bg-muted rounded-lg" />
                  <div className="flex-1 space-y-2">
                    <div className="h-4 bg-muted rounded w-3/4" />
                    <div className="h-3 bg-muted rounded w-1/2" />
                  </div>
                </div>
              ))}
            </div>
          ))}
        </div>
      ) : historyGroups.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20">
          <div className="w-20 h-20 bg-muted rounded-full flex items-center justify-center mb-4">
            <Clock className="w-10 h-10 text-muted-foreground" />
          </div>
          <p className="text-muted-foreground mb-2">暂无浏览记录</p>
          <p className="text-sm text-muted-foreground">去发现更多精彩内容吧</p>
          <button 
            onClick={() => router.push('/')}
            className="mt-6 px-6 py-2 bg-primary text-primary-foreground rounded-full text-sm"
          >
            去逛逛
          </button>
        </div>
      ) : (
        <div className="pb-safe">
          {historyGroups.map(group => (
            <div key={group.date} className="mb-6">
              {/* Date Header */}
              <div className="px-4 py-2 sticky top-14 bg-background/95 backdrop-blur-sm z-[5]">
                <span className="text-sm font-medium text-muted-foreground">{group.label}</span>
              </div>

              {/* Items */}
              <div className="px-4 space-y-3">
                {group.items.map(item => {
                  const config = typeConfig[item.type]
                  const Icon = config.icon
                  const isDeleting = deletingId === item.id

                  return (
                    <div 
                      key={item.id}
                      className={`relative overflow-hidden transition-all duration-300 ${
                        isDeleting ? 'translate-x-[-80px]' : ''
                      }`}
                    >
                      <div 
                        className="flex gap-3 bg-card rounded-xl p-3 cursor-pointer active:bg-muted/50 transition-colors"
                        onClick={() => !isDeleting && handleItemClick(item)}
                        onTouchStart={() => setDeletingId(item.id)}
                      >
                        {/* Cover / Icon */}
                        {item.cover ? (
                          <div className="relative w-24 h-16 rounded-lg overflow-hidden bg-muted flex-shrink-0">
                            <img src={item.cover} alt="" className="w-full h-full object-cover" />
                            {item.progress !== undefined && item.progress < 100 && (
                              <div className="absolute bottom-0 left-0 right-0 h-1 bg-black/30">
                                <div 
                                  className="h-full bg-primary"
                                  style={{ width: `${item.progress}%` }}
                                />
                              </div>
                            )}
                            {item.type === 'video' && (
                              <div className="absolute inset-0 flex items-center justify-center">
                                <div className="w-8 h-8 bg-black/50 rounded-full flex items-center justify-center">
                                  <Play className="w-4 h-4 text-white fill-white" />
                                </div>
                              </div>
                            )}
                          </div>
                        ) : (
                          <div className={`w-16 h-16 rounded-lg ${config.color} flex items-center justify-center flex-shrink-0`}>
                            <Icon className="w-6 h-6 text-white" />
                          </div>
                        )}

                        {/* Info */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start gap-2">
                            <span className={`text-xs px-1.5 py-0.5 rounded ${config.color} text-white flex-shrink-0`}>
                              {config.label}
                            </span>
                            <h3 className="text-sm font-medium line-clamp-2 flex-1">{item.title}</h3>
                          </div>
                          <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground">
                            <span>{item.viewedAt}</span>
                            {item.progress !== undefined && item.duration && (
                              <>
                                <span>·</span>
                                <span className={item.progress >= 100 ? 'text-green-500' : ''}>
                                  {formatProgress(item.progress, item.duration)}
                                </span>
                              </>
                            )}
                          </div>
                        </div>

                        {/* Continue Button */}
                        {item.progress !== undefined && item.progress < 100 && (
                          <button 
                            className="self-center px-3 py-1.5 bg-primary/10 text-primary text-xs rounded-full flex-shrink-0"
                            onClick={(e) => {
                              e.stopPropagation()
                              handleItemClick(item)
                            }}
                          >
                            继续
                          </button>
                        )}
                      </div>

                      {/* Delete Button (Swipe) */}
                      <button
                        className="absolute right-0 top-0 bottom-0 w-20 bg-red-500 flex items-center justify-center text-white"
                        style={{ transform: isDeleting ? 'translateX(0)' : 'translateX(100%)' }}
                        onClick={() => handleDelete(item.id)}
                      >
                        <Trash2 className="w-5 h-5" />
                      </button>
                    </div>
                  )
                })}
              </div>
            </div>
          ))}

          {/* Load More Hint */}
          <div className="text-center py-6 text-sm text-muted-foreground">
            仅展示近30天的浏览记录
          </div>
        </div>
      )}

      {/* Clear Confirm Modal */}
      {showClearConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setShowClearConfirm(false)}>
          <div className="bg-card rounded-2xl w-[80%] max-w-sm overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="p-6 text-center">
              <div className="w-14 h-14 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Trash2 className="w-7 h-7 text-red-500" />
              </div>
              <h3 className="font-semibold text-lg mb-2">清空浏览历史</h3>
              <p className="text-sm text-muted-foreground">
                确定要清空所有浏览记录吗？此操作不可恢复
              </p>
            </div>
            <div className="flex border-t border-border">
              <button
                className="flex-1 py-3.5 text-muted-foreground"
                onClick={() => setShowClearConfirm(false)}
              >
                取消
              </button>
              <button
                className="flex-1 py-3.5 text-red-500 font-medium border-l border-border"
                onClick={handleClearAll}
              >
                清空
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Click outside to cancel delete */}
      {deletingId && (
        <div 
          className="fixed inset-0 z-[1]"
          onClick={() => setDeletingId(null)}
        />
      )}
    </div>
  )
}

// apps/mobile/src/pages/mine/history.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="header">
      <view class="header-inner">
        <text
          class="back-btn"
          @click="goBack"
        >
          ←
        </text>
        <text class="header-title">
          浏览历史
        </text>
        <text
          v-if="totalCount > 0"
          class="header-clear"
          @click="showClearDialog = true"
        >
          清空
        </text>
        <view
          v-else
          class="header-right"
        />
      </view>
    </view>

    <!-- 统计 -->
    <view
      v-if="totalCount > 0"
      class="stats-bar"
    >
      <text>📊 共 {{ totalCount }} 条记录 · 近30天</text>
    </view>

    <DataState
      :is-loading="loading"
      :error="loadError"
      :is-empty="!loading && historyGroups.length === 0"
      empty-icon="🕐"
      empty-title="暂无浏览记录"
      empty-description="去发现更多精彩内容吧"
      empty-action-text="去逛逛"
      :empty-show-action="true"
      skeleton-type="card"
      @retry="loadData"
      @empty-action="goHome"
    >
      <view class="history-content">
        <view
          v-for="group in historyGroups"
          :key="group.date"
          class="history-group"
        >
          <view class="date-header">
            {{ group.label }}
          </view>

          <view
            v-for="item in group.items"
            :key="item.id"
            class="history-item"
            :class="{ deleting: deletingId === item.id }"
          >
            <view
              class="history-item-main"
              @click="handleItemClick(item)"
            >
              <view class="history-thumb">
                <image
                  v-if="item.cover"
                  :src="item.cover"
                  class="history-thumb-img"
                  mode="aspectFill"
                />
                <view
                  v-else
                  class="history-thumb-placeholder"
                  :class="'htp-' + item.type"
                >
                  <text class="history-thumb-icon">
                    {{ typeIcon(item.type) }}
                  </text>
                </view>
                <view
                  v-if="item.type === 'video'"
                  class="history-play-overlay"
                >
                  <text class="history-play-icon">
                    ▶
                  </text>
                </view>
              </view>
              <view class="history-info">
                <view class="history-info-top">
                  <text
                    class="history-type-tag"
                    :class="'htt-' + item.type"
                  >
                    {{ typeLabel(item.type) }}
                  </text>
                  <text class="history-title">
                    {{ item.title }}
                  </text>
                </view>
                <view class="history-meta">
                  <text>{{ item.viewedAt }}</text>
                  <text v-if="item.progress !== undefined && item.duration">
                    · <text :class="item.progress >= 100 ? 'done' : ''">
                      {{ formatProgress(item.progress, item.duration) }}
                    </text>
                  </text>
                </view>
              </view>
              <view
                v-if="item.progress !== undefined && item.progress < 100"
                class="history-continue"
                @click.stop="handleItemClick(item)"
              >
                继续
              </view>
            </view>

            <!-- 左滑删除 -->
            <view
              class="history-delete-btn"
              @click="handleDelete(item.id)"
            >
              🗑
            </view>
          </view>
        </view>

        <view class="history-footer">
          仅展示近30天的浏览记录
        </view>
      </view>
    </DataState>

    <!-- 清空确认弹窗 -->
    <view
      v-if="showClearDialog"
      class="dialog-overlay"
      @click="showClearDialog = false"
    >
      <view
        class="dialog-content"
        @click.stop
      >
        <view class="dialog-icon-wrap">
          <text class="dialog-icon">
            🗑
          </text>
        </view>
        <text class="dialog-title">
          清空浏览历史
        </text>
        <text class="dialog-desc">
          确定要清空所有浏览记录吗？此操作不可恢复
        </text>
        <view class="dialog-actions">
          <view
            class="dialog-btn dialog-btn-cancel"
            @click="showClearDialog = false"
          >
            取消
          </view>
          <view
            class="dialog-btn dialog-btn-confirm-danger"
            @click="handleClearAll"
          >
            清空
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import DataState from '../../components/DataState.vue'

interface HistoryItem {
  id: string
  type: string
  title: string
  cover?: string
  progress?: number
  duration?: number
  viewedAt: string
}

interface HistoryGroup {
  date: string
  label: string
  items: HistoryItem[]
}

const loading = ref(true)
const loadError = ref<string | null>(null)
const historyGroups = ref<HistoryGroup[]>([])
const showClearDialog = ref(false)
const deletingId = ref<string | null>(null)

const totalCount = computed(() => historyGroups.value.reduce((sum, g) => sum + g.items.length, 0))

function typeIcon(type: string): string {
  const map: Record<string, string> = { course: '📖', video: '🎬', live: '📡', article: '📄', product: '🛍', circle: '👥' }
  return map[type] || '📁'
}

function typeLabel(type: string): string {
  const map: Record<string, string> = { course: '课程', video: '视频', live: '直播', article: '文章', product: '商品', circle: '圈子' }
  return map[type] || type
}

function formatProgress(progress: number, duration: number): string {
  if (progress >= 100) return '已看完'
  const watched = Math.floor((progress / 100) * duration)
  const minutes = Math.floor(watched / 60)
  return '已观看 ' + minutes + ' 分钟'
}

async function loadData() {
  loading.value = true
  loadError.value = null
  try {
    await new Promise((r) => setTimeout(r, 600))
    historyGroups.value = [
      {
        date: '2026-06-04', label: '今天',
        items: [
          { id: '1', type: 'course', title: '周易入门：从零开始学习易经', cover: '', progress: 45, duration: 3600, viewedAt: '14:30' },
          { id: '2', type: 'video', title: '梅花易数实战案例分析', cover: '', progress: 100, duration: 1200, viewedAt: '12:15' },
          { id: '3', type: 'article', title: '八字命理中的十神详解', viewedAt: '10:20' },
        ],
      },
      {
        date: '2026-06-03', label: '昨天',
        items: [
          { id: '4', type: 'live', title: '风水布局直播答疑', cover: '', viewedAt: '20:00' },
          { id: '5', type: 'product', title: '开光铜葫芦摆件', cover: '', viewedAt: '16:45' },
        ],
      },
      {
        date: '2026-06-01', label: '6月1日',
        items: [
          { id: '6', type: 'course', title: '六爻预测高级班', cover: '', progress: 30, duration: 7200, viewedAt: '19:30' },
        ],
      },
    ]
  } catch (e: any) {
    loadError.value = e?.errMsg || e?.message || '加载失败'
  } finally {
    loading.value = false
  }
}

function handleDelete(itemId: string) {
  historyGroups.value = historyGroups.value
    .map((g) => ({ ...g, items: g.items.filter((i) => i.id !== itemId) }))
    .filter((g) => g.items.length > 0)
  deletingId.value = null
}

function handleClearAll() {
  historyGroups.value = []
  showClearDialog.value = false
  uni.showToast({ title: '已清空', icon: 'success' })
}

function handleItemClick(item: HistoryItem) {
  uni.showToast({ title: '打开：' + item.title, icon: 'none' })
}

function goHome() {
  uni.switchTab({ url: '/pages/index/index' })
}

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
.page { background: #F5F0E8; min-height: 100vh; }
.header { background: #fff; border-bottom: 1rpx solid #E8E3DB; }
.header-inner { display: flex; align-items: center; justify-content: space-between; height: 88rpx; padding: 0 24rpx; }
.back-btn { font-size: 36rpx; color: #2C2C2C; padding: 8rpx; }
.header-title { font-size: 34rpx; font-weight: 600; color: #2C2C2C; }
.header-right { width: 80rpx; }
.header-clear { font-size: 24rpx; color: #EF4444; padding: 8rpx; }

.stats-bar { padding: 16rpx 24rpx; background: #FAF8F5; font-size: 22rpx; color: #999; border-bottom: 1rpx solid #E8E3DB; }

.history-content { padding: 0 0 40rpx; }
.history-group { margin-bottom: 8rpx; }
.date-header { padding: 24rpx 24rpx 16rpx; font-size: 24rpx; font-weight: 500; color: #999; background: #F5F0E8; position: sticky; top: 88rpx; z-index: 5; }

.history-item { display: flex; align-items: stretch; overflow: hidden; transition: all 0.3s; background: #fff; margin: 0 24rpx 2rpx; border-radius: 16rpx; margin-bottom: 8rpx; }
.history-item.deleting { position: relative; }
.history-item-main { flex: 1; display: flex; gap: 16rpx; padding: 20rpx; align-items: center; }
.history-thumb { width: 180rpx; height: 120rpx; border-radius: 12rpx; overflow: hidden; flex-shrink: 0; position: relative; }
.history-thumb-img { width: 100%; height: 100%; }
.history-thumb-placeholder { width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; }
.htp-course { background: #E3F2FD; }
.htp-video { background: #FCE4EC; }
.htp-live { background: #FFEBEE; }
.htp-article { background: #E8F5E9; }
.htp-product { background: #FFF3E0; }
.htp-circle { background: #F3E5F5; }
.history-thumb-icon { font-size: 40rpx; }

.history-play-overlay { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,0.2); }
.history-play-icon { width: 56rpx; height: 56rpx; border-radius: 50%; background: rgba(0,0,0,0.5); color: #fff; font-size: 24rpx; display: flex; align-items: center; justify-content: center; }

.history-info { flex: 1; min-width: 0; }
.history-info-top { display: flex; align-items: flex-start; gap: 8rpx; }
.history-type-tag { font-size: 18rpx; padding: 2rpx 10rpx; border-radius: 6rpx; color: #fff; flex-shrink: 0; margin-top: 2rpx; }
.htt-course { background: #1976D2; }
.htt-video { background: #E91E63; }
.htt-live { background: #EF4444; }
.htt-article { background: #22C55E; }
.htt-product { background: #F59E0B; }
.htt-circle { background: #7B1FA2; }

.history-title { font-size: 26rpx; font-weight: 500; color: #2C2C2C; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; }
.history-meta { font-size: 20rpx; color: #999; margin-top: 8rpx; }
.history-meta .done { color: #22C55E; }

.history-continue { flex-shrink: 0; padding: 8rpx 20rpx; background: #FDE8E8; color: #C41E3A; font-size: 20rpx; border-radius: 20rpx; }
.history-delete-btn { width: 100rpx; background: #EF4444; color: #fff; display: flex; align-items: center; justify-content: center; font-size: 36rpx; flex-shrink: 0; }

.history-footer { text-align: center; padding: 32rpx; font-size: 22rpx; color: #B8B0A4; }

/* 弹窗 */
.dialog-overlay { position: fixed; inset: 0; z-index: 100; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; padding: 48rpx; }
.dialog-content { background: #fff; border-radius: 24rpx; padding: 40rpx 32rpx; width: 100%; max-width: 560rpx; text-align: center; }
.dialog-icon-wrap { margin-bottom: 16rpx; }
.dialog-icon { font-size: 56rpx; }
.dialog-title { font-size: 34rpx; font-weight: 600; color: #2C2C2C; display: block; }
.dialog-desc { font-size: 24rpx; color: #666; margin-top: 12rpx; display: block; line-height: 1.6; }
.dialog-actions { display: flex; gap: 20rpx; margin-top: 28rpx; }
.dialog-btn { flex: 1; height: 80rpx; border-radius: 16rpx; display: flex; align-items: center; justify-content: center; font-size: 26rpx; font-weight: 500; }
.dialog-btn-cancel { background: #F5F0E8; color: #666; }
.dialog-btn-confirm-danger { background: #EF4444; color: #fff; }
</style>
