// apps/mobile/src/pages_backup_20260609/demo/update/index.vue
<template>
  <view class="page" data-v0-route="demo/update">
        <view class="min-h-screen bg-background">
          
          <view class="sticky top-0 z-40 bg-background/95 backdrop-blur border-b border-border">
            <view class="flex items-center gap-3 px-4 h-12">
              
              <text class="font-semibold text-foreground">版本更新弹窗演示</text>
            </view>
          </view>
    
        </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { onPullDownRefresh } from '@dcloudio/uni-app'

const loading = ref(true)
const error = ref<string | null>(null)

onMounted(() => { loading.value = false })
onPullDownRefresh(() => { setTimeout(() => uni.stopPullDownRefresh(), 500) })
</script>

<style scoped>
.page {
  background: #FAF8F5;
  min-height: 100vh;
}

.hr { height: 1px; background: #E8E0D5; margin: 24rpx 0; }
</style>

// proto-ref-app/demo/update/page.tsx
"use client"

import { UpdateModalDemo } from "@/components/update-modal"
import { BackButton } from "@/components/common/back-button"
import { } from "lucide-react"
import Link from "next/link"

export default function UpdateDemoPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-40 bg-background/95 backdrop-blur border-b border-border">
        <div className="flex items-center gap-3 px-4 h-12">
          <BackButton />
          <h1 className="font-semibold text-foreground">版本更新弹窗演示</h1>
        </div>
      </header>

      <UpdateModalDemo />
    </div>
  )
}
