// v0-reference/vue3/src/pkg-institute/teacher-demand/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="nav" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="nav-bar">
        <view class="nav-left">
          <view class="nav-back" @tap="goBack">
            <app-icon name="arrow-left" :size="20" color="#1a1a1a" />
          </view>
          <text class="nav-title">课程需求大厅</text>
        </view>
        <view class="view-switch">
          <view class="switch-btn" :class="{ 'switch-active': viewMode === 'teacher' }" @tap="viewMode = 'teacher'">
            <text class="switch-text" :class="{ 'switch-text-active': viewMode === 'teacher' }">老师视角</text>
          </view>
          <view class="switch-btn" :class="{ 'switch-active': viewMode === 'station' }" @tap="viewMode = 'station'">
            <text class="switch-text" :class="{ 'switch-text-active': viewMode === 'station' }">驿站视角</text>
          </view>
        </view>
      </view>
    </view>

    <!-- Tab切换 -->
    <view class="tab-bar">
      <view
        v-for="tab in tabs"
        :key="tab.id"
        class="tab-chip"
        :class="{ 'tab-chip-active': activeTab === tab.id }"
        @tap="activeTab = tab.id"
      >
        <text class="tab-chip-text" :class="{ 'tab-chip-text-active': activeTab === tab.id }">{{ tab.label }}</text>
      </view>
    </view>

    <scroll-view scroll-y class="scroll" :style="{ height: scrollHeight + 'px' }">
      <view class="list">
        <view
          v-for="demand in filteredDemands"
          :key="demand.id"
          class="demand-card"
          @tap="goDetail(demand.id)"
        >
          <!-- 驿站信息 -->
          <view class="station-row">
            <view class="station-icon">
              <app-icon name="building-2" :size="16" color="#2563eb" />
            </view>
            <view class="station-info">
              <text class="station-name">{{ demand.stationName }}</text>
              <view class="station-loc">
                <app-icon name="map-pin" :size="12" color="#9ca3af" />
                <text class="station-loc-text">{{ demand.stationLocation }}</text>
              </view>
            </view>
            <text class="status-badge" :style="{ color: statusConfig[demand.status].color, background: statusConfig[demand.status].bg }">{{ statusConfig[demand.status].label }}</text>
          </view>

          <!-- 需求内容 -->
          <text class="demand-title">{{ demand.title }}</text>
          <text class="demand-desc">{{ demand.description }}</text>

          <!-- 标签 -->
          <view class="tag-row">
            <text class="tag">{{ demand.specialty }}</text>
            <text class="tag">{{ demand.duration }}</text>
            <text class="tag">{{ demand.studentCount }}人班</text>
          </view>

          <!-- 底部信息 -->
          <view class="bottom-row">
            <view class="bottom-left">
              <view class="bottom-item">
                <app-icon name="calendar" :size="12" color="#9ca3af" />
                <text class="bottom-text">{{ demand.date.split(' ')[0] }}</text>
              </view>
              <view class="bottom-item">
                <app-icon name="users" :size="12" color="#9ca3af" />
                <text class="bottom-text">{{ demand.applicants }}人申请</text>
              </view>
            </view>
            <view class="budget">
              <text class="budget-label">预算 </text>
              <text class="budget-value">¥{{ (demand.budget.min / 1000).toFixed(0) }}k-{{ (demand.budget.max / 1000).toFixed(0) }}k</text>
            </view>
          </view>

          <!-- 老师视角：申请按钮 -->
          <view v-if="viewMode === 'teacher' && demand.status === 'recruiting'" class="apply-btn" @tap.stop="applyDemand">
            <text class="apply-btn-text">申请授课</text>
          </view>
        </view>
      </view>
      <view :style="{ height: viewMode === 'station' ? '88px' : '24px' }" />
    </scroll-view>

    <!-- 驿站视角：发布需求按钮 -->
    <view v-if="viewMode === 'station'" class="footer">
      <view class="footer-btn" @tap="goCreate">
        <app-icon name="plus" :size="16" color="#fff" />
        <text class="footer-btn-text">发布课程需求</text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack, navigateTo } from '@/utils/router'
import { teacherDemands, demandStatusConfig as statusConfig, demandTabs as tabs } from '@/lib/institute-data'

const statusBarHeight = ref(0)
const scrollHeight = ref(600)
try {
  const info = uni.getSystemInfoSync()
  statusBarHeight.value = info.statusBarHeight || 0
  scrollHeight.value = (info.windowHeight || 700) - statusBarHeight.value - 44 - 45
} catch (e) {}

const activeTab = ref('all')
const viewMode = ref<'teacher' | 'station'>('teacher')

const filteredDemands = computed(() => teacherDemands.filter(d => {
  if (activeTab.value === 'all') return true
  return d.status === activeTab.value
}))

function goDetail(id: number) {
  navigateTo(`/institute/demands/${id}`)
}
function goCreate() {
  navigateTo('/institute/demands/create')
}
function applyDemand() {
  uni.showToast({ title: '已提交申请', icon: 'success' })
}
</script>

<style scoped>
.page { min-height: 100vh; background: #f5f5f5; }
.nav { position: sticky; top: 0; z-index: 20; background: rgba(255,255,255,0.95); border-bottom: 1px solid #ededed; }
.nav-bar { display: flex; align-items: center; justify-content: space-between; height: 44px; padding: 0 12px; }
.nav-left { display: flex; align-items: center; gap: 8px; }
.nav-back { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; }
.nav-title { font-size: 17px; font-weight: 600; color: #1a1a1a; }
.view-switch { display: flex; border: 1px solid #d1d5db; border-radius: 8px; overflow: hidden; }
.switch-btn { padding: 4px 10px; height: 28px; display: flex; align-items: center; }
.switch-active { background: #c41e3a; }
.switch-text { font-size: 12px; color: #4b5563; }
.switch-text-active { color: #fff; }

.tab-bar { display: flex; gap: 8px; padding: 8px 16px; overflow-x: auto; border-bottom: 1px solid #ededed; background: #fff; white-space: nowrap; }
.tab-chip { flex-shrink: 0; padding: 4px 14px; border-radius: 999px; border: 1px solid #d1d5db; background: #fff; }
.tab-chip-active { background: #c41e3a; border-color: #c41e3a; }
.tab-chip-text { font-size: 12px; color: #4b5563; }
.tab-chip-text-active { color: #fff; }
.scroll { width: 100%; }

.list { padding: 12px 16px; display: flex; flex-direction: column; gap: 12px; }
.demand-card { background: #fff; border-radius: 12px; border: 1px solid #ededed; padding: 12px; }
.station-row { display: flex; align-items: center; gap: 8px; padding-bottom: 8px; border-bottom: 1px solid #ededed; margin-bottom: 8px; }
.station-icon { width: 32px; height: 32px; border-radius: 8px; background: #eff6ff; display: flex; align-items: center; justify-content: center; }
.station-info { flex: 1; min-width: 0; }
.station-name { font-size: 14px; font-weight: 500; color: #1a1a1a; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.station-loc { display: flex; align-items: center; gap: 4px; margin-top: 2px; }
.station-loc-text { font-size: 10px; color: #9ca3af; }
.status-badge { font-size: 10px; padding: 2px 8px; border-radius: 999px; flex-shrink: 0; }

.demand-title { font-size: 15px; font-weight: 500; color: #1a1a1a; display: block; }
.demand-desc { font-size: 12px; color: #6b7280; margin-top: 4px; line-height: 1.5; display: block; }
.tag-row { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }
.tag { font-size: 10px; padding: 2px 8px; background: #f3f4f6; border-radius: 4px; color: #4b5563; }
.bottom-row { display: flex; align-items: center; justify-content: space-between; margin-top: 12px; padding-top: 8px; border-top: 1px solid #ededed; }
.bottom-left { display: flex; align-items: center; gap: 12px; }
.bottom-item { display: flex; align-items: center; gap: 4px; }
.bottom-text { font-size: 10px; color: #9ca3af; }
.budget-label { font-size: 10px; color: #9ca3af; }
.budget-value { font-size: 14px; font-weight: 500; color: #c41e3a; }

.apply-btn { margin-top: 12px; height: 36px; background: #c41e3a; border-radius: 8px; display: flex; align-items: center; justify-content: center; }
.apply-btn-text { font-size: 12px; color: #fff; font-weight: 500; }

.footer { position: fixed; bottom: 0; left: 0; right: 0; padding: 12px 16px; padding-bottom: calc(12px + env(safe-area-inset-bottom)); background: #fff; border-top: 1px solid #ededed; }
.footer-btn { display: flex; align-items: center; justify-content: center; gap: 8px; height: 44px; background: #c41e3a; border-radius: 8px; }
.footer-btn-text { font-size: 14px; color: #fff; font-weight: 500; }
</style>

// app/institute/teacher-demand/page.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { 
  ArrowLeft, Plus, MapPin, Users, Calendar, Clock,
  ChevronRight, Filter, CheckCircle2, XCircle, MessageCircle,
  Building2, BookOpen, Coins, Eye
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"
import { cn } from "@/lib/utils"

// 需求状态
type DemandStatus = "recruiting" | "matched" | "confirmed" | "completed" | "cancelled"

interface TeacherDemand {
  id: number
  stationName: string
  stationAvatar: string
  stationLocation: string
  title: string
  specialty: string
  date: string
  duration: string
  studentCount: number
  budget: { min: number; max: number }
  status: DemandStatus
  applicants: number
  description: string
  requirements: string[]
  createdAt: string
}

// 状态配置
const statusConfig: Record<DemandStatus, { label: string; color: string; bgColor: string }> = {
  recruiting: { label: "招募中", color: "text-success", bgColor: "bg-success/10" },
  matched: { label: "已匹配", color: "text-info", bgColor: "bg-info/10" },
  confirmed: { label: "已确认", color: "text-operator", bgColor: "bg-operator/10" },
  completed: { label: "已完成", color: "text-muted-foreground", bgColor: "bg-muted" },
  cancelled: { label: "已取消", color: "text-red-500", bgColor: "bg-red-500/10" },
}

// 模拟数据
const mockDemands: TeacherDemand[] = [
  {
    id: 1,
    stationName: "北京国学驿站",
    stationAvatar: "",
    stationLocation: "北京·朝阳区",
    title: "八字命理高级班授课老师",
    specialty: "八字命理",
    date: "2024-04-15 至 2024-04-17",
    duration: "3天/18课时",
    studentCount: 30,
    budget: { min: 15000, max: 25000 },
    status: "recruiting",
    applicants: 5,
    description: "招募资深八字命理老师，为高级班学员授课，要求有丰富的实战经验和教学经验。",
    requirements: ["5年以上授课经验", "研究院成员优先", "可提供往期课程录像"],
    createdAt: "2024-03-18"
  },
  {
    id: 2,
    stationName: "上海易学馆",
    stationAvatar: "",
    stationLocation: "上海·静安区",
    title: "紫微斗数入门班讲师",
    specialty: "紫微斗数",
    date: "2024-04-20 至 2024-04-21",
    duration: "2天/12课时",
    studentCount: 25,
    budget: { min: 8000, max: 12000 },
    status: "recruiting",
    applicants: 3,
    description: "招募紫微斗数讲师，负责入门班教学，需要有系统的教学大纲。",
    requirements: ["3年以上授课经验", "有完整教学体系", "善于与学员互动"],
    createdAt: "2024-03-20"
  },
  {
    id: 3,
    stationName: "广州玄学堂",
    stationAvatar: "",
    stationLocation: "广州·天河区",
    title: "风水堪舆实地教学",
    specialty: "风水堪舆",
    date: "2024-05-01 至 2024-05-03",
    duration: "3天实地考察",
    studentCount: 15,
    budget: { min: 20000, max: 35000 },
    status: "matched",
    applicants: 8,
    description: "组织风水实地考察教学，需要老师带队讲解真实案例。",
    requirements: ["高级讲师", "本地有多个可考察案例", "配合度高"],
    createdAt: "2024-03-15"
  },
  {
    id: 4,
    stationName: "成都周易学社",
    stationAvatar: "",
    stationLocation: "成都·武侯区",
    title: "易经基础班周末课程",
    specialty: "易经占卜",
    date: "2024-04-06、07、13、14",
    duration: "4天/24课时",
    studentCount: 40,
    budget: { min: 12000, max: 18000 },
    status: "confirmed",
    applicants: 6,
    description: "周末易经基础课程，面向零基础学员。",
    requirements: ["教学经验丰富", "课程内容通俗易懂", "周末时间充裕"],
    createdAt: "2024-03-10"
  },
]

// Tab选项
const tabs = [
  { id: "all", label: "全部" },
  { id: "recruiting", label: "招募中" },
  { id: "matched", label: "已匹配" },
  { id: "completed", label: "已完成" },
]

export default function TeacherDemandPage() {
  const [activeTab, setActiveTab] = useState("all")
  const [viewMode, setViewMode] = useState<"station" | "teacher">("teacher") // 视角：驿站/老师

  // 筛选需求
  const filteredDemands = mockDemands.filter(demand => {
    if (activeTab === "all") return true
    return demand.status === activeTab
  })

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-10 bg-background/95 backdrop-blur border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <Link href="/institute/teacher-pool" className="p-1">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <h1 className="text-lg font-semibold">课程需求大厅</h1>
          </div>
          {/* 视角切换 */}
          <div className="flex rounded-lg overflow-hidden border border-border">
            <Button
              variant={viewMode === "teacher" ? "default" : "ghost"}
              size="sm"
              onClick={() => setViewMode("teacher")}
              className="rounded-none text-xs h-7"
            >
              老师视角
            </Button>
            <Button
              variant={viewMode === "station" ? "default" : "ghost"}
              size="sm"
              onClick={() => setViewMode("station")}
              className="rounded-none text-xs h-7"
            >
              驿站视角
            </Button>
          </div>
        </div>
      </header>

      {/* Tab切换 */}
      <div className="px-4 py-2 flex gap-2 overflow-x-auto scrollbar-hide border-b border-border">
        {tabs.map(tab => (
          <Button
            key={tab.id}
            variant={activeTab === tab.id ? "default" : "outline"}
            size="sm"
            onClick={() => setActiveTab(tab.id)}
            className={cn(
              "rounded-full text-xs flex-shrink-0",
              activeTab === tab.id && "bg-primary text-primary-foreground"
            )}
          >
            {tab.label}
          </Button>
        ))}
      </div>

      {/* 需求列表 */}
      <div className="px-4 py-3 space-y-3">
        {filteredDemands.map(demand => {
          const status = statusConfig[demand.status]
          return (
            <Link href={`/institute/demands/${demand.id}`} key={demand.id}>
              <Card className="p-3 hover:bg-secondary/30 transition-colors">
                {/* 驿站信息 */}
                <div className="flex items-center gap-2 pb-2 border-b border-border mb-2">
                  <div className="w-8 h-8 rounded-lg bg-info/10 flex items-center justify-center">
                    <Building2 className="w-4 h-4 text-info" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{demand.stationName}</p>
                    <p className="text-[10px] text-muted-foreground flex items-center gap-1">
                      <MapPin className="w-3 h-3" />
                      {demand.stationLocation}
                    </p>
                  </div>
                  <Badge className={cn("text-[10px]", status.bgColor, status.color)}>
                    {status.label}
                  </Badge>
                </div>

                {/* 需求内容 */}
                <h3 className="font-medium text-foreground">{demand.title}</h3>
                <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{demand.description}</p>

                {/* 标签 */}
                <div className="flex flex-wrap gap-1 mt-2">
                  <Badge variant="secondary" className="text-[10px]">{demand.specialty}</Badge>
                  <Badge variant="secondary" className="text-[10px]">{demand.duration}</Badge>
                  <Badge variant="secondary" className="text-[10px]">{demand.studentCount}人班</Badge>
                </div>

                {/* 底部信息 */}
                <div className="flex items-center justify-between mt-3 pt-2 border-t border-border">
                  <div className="flex items-center gap-3 text-[10px] text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {demand.date.split(" ")[0]}
                    </span>
                    <span className="flex items-center gap-1">
                      <Users className="w-3 h-3" />
                      {demand.applicants}人申请
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] text-muted-foreground">预算 </span>
                    <span className="text-sm font-medium text-primary">
                      ¥{(demand.budget.min / 1000).toFixed(0)}k-{(demand.budget.max / 1000).toFixed(0)}k
                    </span>
                  </div>
                </div>

                {/* 老师视角：申请按钮 */}
                {viewMode === "teacher" && demand.status === "recruiting" && (
                  <Button size="sm" className="w-full mt-3 text-xs">
                    申请授课
                  </Button>
                )}
              </Card>
            </Link>
          )
        })}
      </div>

      {/* 驿站视角：发布需求按钮 */}
      {viewMode === "station" && (
        <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t border-border">
          <Link href="/institute/demands/create">
            <Button className="w-full">
              <Plus className="w-4 h-4 mr-2" />
              发布课程需求
            </Button>
          </Link>
        </div>
      )}

      {viewMode === "station" && <div className="h-20" />}
    </div>
  )
}
