// apps/mobile/.backup_vue3_converted/pages/merchant/product-edit/index.vue
<template>
  <view class="min-h-screen bg-background pb-32">
    <!-- 顶部导航 -->
    <view class="sticky top-0 z-50 bg-white border-b border-border">
      <view class="flex items-center h-14 px-4">
        <view @click="goBack" class="mr-3 p-1">
          <text class="text-xl text-foreground">←</text>
        </view>
        <text class="text-lg font-semibold">{{ isEdit ? '编辑商品' : '发布商品' }}</text>
      </view>
    </view>

    <scroll-view scroll-y class="flex-1 p-4 space-y-4">
      <!-- 商品图片 -->
      <view class="bg-white rounded-2xl p-4">
        <view class="flex items-center justify-between mb-3">
          <text class="font-medium">商品图片</text>
          <text class="text-xs text-muted-foreground">最多9张，首图为封面</text>
        </view>
        <view class="grid grid-cols-3 gap-3">
          <view v-for="(_, index) in formData.images" :key="index" class="aspect-square rounded-xl bg-background relative overflow-hidden border-2 border-dashed border-border">
            <view class="absolute inset-0 flex items-center justify-center">
              <text class="text-3xl"></text>
            </view>
            <view @click="removeImage(index)" class="absolute top-1 right-1 w-6 h-6 rounded-full bg-black/50 flex items-center justify-center">
              <text class="text-xs text-white">✕</text>
            </view>
            <text v-if="index === 0" class="absolute bottom-1 left-1 px-1 py-0.5 rounded text-[10px] bg-primary text-white">封面</text>
          </view>
          <view v-if="formData.images.length < 9" @click="addImage" class="aspect-square rounded-xl border-2 border-dashed border-border flex flex-col items-center justify-center">
            <text class="text-3xl text-muted-foreground">+</text>
            <text class="text-xs text-muted-foreground mt-1">添加图片</text>
          </view>
        </view>
      </view>

      <!-- 基本信息 -->
      <view class="bg-white rounded-2xl p-4 space-y-4">
        <text class="font-medium">基本信息</text>

        <view class="space-y-2">
          <text class="text-sm font-medium">商品名称 <text class="text-primary">*</text></text>
          <input v-model="formData.title" placeholder="请输入商品名称（最多60字）" maxlength="60" class="w-full px-3 py-2.5 bg-background rounded-xl text-sm" />
          <text class="text-xs text-muted-foreground text-right block">{{ formData.title.length }}/60</text>
        </view>

        <view class="space-y-2">
          <text class="text-sm font-medium">商品卖点</text>
          <input v-model="formData.subtitle" placeholder="简要描述商品特点（最多30字）" maxlength="30" class="w-full px-3 py-2.5 bg-background rounded-xl text-sm" />
        </view>

        <view class="space-y-2">
          <text class="text-sm font-medium">商品详情</text>
          <textarea v-model="formData.description" placeholder="详细描述商品信息、规格、使用方法等" rows="5" class="w-full px-3 py-2.5 bg-background rounded-xl text-sm" />
        </view>
      </view>

      <!-- 价格库存 -->
      <view class="bg-white rounded-2xl p-4 space-y-4">
        <text class="font-medium">价格库存</text>

        <view class="grid grid-cols-2 gap-4">
          <view class="space-y-2">
            <text class="text-sm font-medium">售价 <text class="text-primary">*</text></text>
            <view class="relative">
              <text class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">¥</text>
              <input v-model="formData.price" type="digit" placeholder="0.00" class="w-full pl-8 pr-3 py-2.5 bg-background rounded-xl text-sm" />
            </view>
          </view>
          <view class="space-y-2">
            <text class="text-sm font-medium">原价（划线价）</text>
            <view class="relative">
              <text class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">¥</text>
              <input v-model="formData.originalPrice" type="digit" placeholder="0.00" class="w-full pl-8 pr-3 py-2.5 bg-background rounded-xl text-sm" />
            </view>
          </view>
        </view>

        <view class="grid grid-cols-2 gap-4">
          <view class="space-y-2">
            <text class="text-sm font-medium">库存 <text class="text-primary">*</text></text>
            <input v-model="formData.stock" type="number" placeholder="请输入库存数量" class="w-full px-3 py-2.5 bg-background rounded-xl text-sm" />
          </view>
          <view class="space-y-2">
            <text class="text-sm font-medium">限购数量</text>
            <input v-model="formData.limitPerPerson" type="number" placeholder="不限制" class="w-full px-3 py-2.5 bg-background rounded-xl text-sm" />
          </view>
        </view>
      </view>

      <!-- 分类与标签 -->
      <view class="bg-white rounded-2xl p-4 space-y-4">
        <text class="font-medium">分类与标签</text>

        <view class="space-y-2">
          <text class="text-sm font-medium">商品分类 <text class="text-primary">*</text></text>
          <picker :range="categories" range-key="name" @change="onCategoryChange">
            <view :class="['w-full px-3 py-2.5 rounded-xl text-sm border', formData.category ? 'bg-background border-border' : 'bg-background border-border']">
              <text :class="formData.category ? 'text-foreground' : 'text-muted-foreground'">{{ selectedCategoryName || '请选择商品分类' }}</text>
            </view>
          </picker>
          <text v-if="selectedCategory" class="text-xs text-muted-foreground flex items-center gap-1">
            ℹ️ 该分类平台收取 {{ selectedCategory.fee }} 技术服务费
          </text>
        </view>

        <view class="space-y-2">
          <text class="text-sm font-medium">商品标签（最多5个）</text>
          <view class="flex flex-wrap gap-2 mb-2">
            <view v-for="tag in formData.tags" :key="tag" class="px-2 py-1 rounded-lg bg-background text-xs flex items-center gap-1">
              <text>{{ tag }}</text>
              <text @click="removeTag(tag)" class="text-muted-foreground">✕</text>
            </view>
          </view>
          <view class="flex gap-2">
            <input v-model="newTag" placeholder="输入标签后点击添加" maxlength="10" class="flex-1 px-3 py-2 bg-background rounded-xl text-sm" @confirm="addTag" />
            <view @click="addTag" :class="['px-3 py-2 rounded-xl text-sm border border-border', formData.tags.length >= 5 ? 'opacity-50' : '']">
              <text>+</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 其他设置 -->
      <view class="bg-white rounded-2xl p-4 space-y-4">
        <text class="font-medium">其他设置</text>

        <view class="flex items-center justify-between">
          <view>
            <text class="text-sm font-medium block">虚拟商品</text>
            <text class="text-xs text-muted-foreground mt-0.5">虚拟商品无需发货</text>
          </view>
          <switch :checked="formData.isVirtual" @change="formData.isVirtual = !formData.isVirtual" color="#C41E3A" />
        </view>

        <view class="flex items-center justify-between">
          <view>
            <text class="text-sm font-medium block">支持退款</text>
            <text class="text-xs text-muted-foreground mt-0.5">买家可申请退款退货</text>
          </view>
          <switch :checked="formData.allowRefund" @change="formData.allowRefund = !formData.allowRefund" color="#C41E3A" />
        </view>
      </view>
    </scroll-view>

    <!-- 底部操作栏 -->
    <view class="fixed bottom-0 left-0 right-0 p-4 bg-white border-t border-border">
      <view class="flex gap-3">
        <view @click="handleSaveDraft" :class="['flex-1 py-3 rounded-xl text-center text-sm font-medium border border-border', isSaving ? 'opacity-50' : '']">
          <text>{{ isSaving ? ' 保存中...' : '💾 保存草稿' }}</text>
        </view>
        <view @click="handlePublish" :class="['flex-1 py-3 rounded-xl text-center text-sm font-medium', isSubmitting ? 'opacity-50 bg-primary text-white' : 'bg-primary text-white']">
          <text>{{ isSubmitting ? ' 提交中...' : isEdit ? ' 保存修改' : '🚀 立即发布' }}</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

const categories = [
  { id: 'guoxue', name: '国学课程', fee: '5%' },
  { id: 'guji', name: '古籍图书', fee: '3%' },
  { id: 'wenchuang', name: '文创用品', fee: '5%' },
  { id: 'wenfang', name: '文房四宝', fee: '5%' },
  { id: 'chadao', name: '茶道用品', fee: '5%' },
  { id: 'mingli', name: '命理咨询', fee: '10%' },
  { id: 'fengshui', name: '风水服务', fee: '10%' },
  { id: 'shufa', name: '书法字画', fee: '8%' },
]

interface FormData {
  images: string[]
  title: string
  subtitle: string
  description: string
  price: string
  originalPrice: string
  stock: string
  category: string
  tags: string[]
  isVirtual: boolean
  allowRefund: boolean
  limitPerPerson: string
}

const isEdit = ref(false)
const isSubmitting = ref(false)
const isSaving = ref(false)
const newTag = ref('')

const formData = ref<FormData>({
  images: [],
  title: '',
  subtitle: '',
  description: '',
  price: '',
  originalPrice: '',
  stock: '',
  category: '',
  tags: [],
  isVirtual: false,
  allowRefund: true,
  limitPerPerson: '',
})

const selectedCategory = ref<{ id: string; name: string; fee: string } | null>(null)

const selectedCategoryName = ref('')

onMounted(() => {
  const pages = getCurrentPages()
  const currentPage = pages[pages.length - 1] as any
  const productId = currentPage?.options?.id
  if (productId) {
    isEdit.value = true
    formData.value = {
      images: ['1', '2'],
      title: '滴天髓精解',
      subtitle: '命理学经典著作精装版',
      description: '详细描述内容...',
      price: '68',
      originalPrice: '98',
      stock: '156',
      category: 'guji',
      tags: ['命理', '八字', '经典'],
      isVirtual: false,
      allowRefund: true,
      limitPerPerson: '',
    }
    const cat = categories.find(c => c.id === 'guji')
    if (cat) {
      selectedCategory.value = cat
      selectedCategoryName.value = cat.name
    }
  }
})

function onCategoryChange(e: any) {
  const idx = e.detail.value
  const cat = categories[idx]
  if (cat) {
    formData.value.category = cat.id
    selectedCategory.value = cat
    selectedCategoryName.value = cat.name
  }
}

function addImage() {
  formData.value.images.push(String(formData.value.images.length + 1))
}

function removeImage(index: number) {
  formData.value.images = formData.value.images.filter((_, i) => i !== index)
}

function addTag() {
  if (newTag.value && !formData.value.tags.includes(newTag.value) && formData.value.tags.length < 5) {
    formData.value.tags.push(newTag.value)
    newTag.value = ''
  }
}

function removeTag(tag: string) {
  formData.value.tags = formData.value.tags.filter(t => t !== tag)
}

async function handleSaveDraft() {
  isSaving.value = true
  await new Promise(resolve => setTimeout(resolve, 1000))
  isSaving.value = false
  uni.showToast({ title: '草稿已保存', icon: 'success' })
}

async function handlePublish() {
  if (!formData.value.title || !formData.value.price || !formData.value.stock || !formData.value.category) {
    uni.showToast({ title: '请填写必填项', icon: 'none' })
    return
  }
  isSubmitting.value = true
  await new Promise(resolve => setTimeout(resolve, 1500))
  isSubmitting.value = false
  uni.showToast({ title: '发布成功', icon: 'success' })
  setTimeout(() => { uni.navigateBack() }, 800)
}

function goBack() { uni.navigateBack() }
</script>

<style scoped>
/* 样式由 Tailwind 处理 */
</style>

// v0-reference/proto-ref-app/merchant/product-edit/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import Link from "next/link"
import { useRouter, useSearchParams } from "next/navigation"
import { ArrowLeft, Camera, Plus, X, Save, Send, Loader2, Info } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { cn } from "@/lib/utils"

const categories = [
  { id: "guoxue", name: "国学课程", fee: "5%" },
  { id: "guji", name: "古籍图书", fee: "3%" },
  { id: "wenchuang", name: "文创用品", fee: "5%" },
  { id: "wenfang", name: "文房四宝", fee: "5%" },
  { id: "chadao", name: "茶道用品", fee: "5%" },
  { id: "mingli", name: "命理咨询", fee: "10%" },
  { id: "fengshui", name: "风水服务", fee: "10%" },
  { id: "shufa", name: "书法字画", fee: "8%" },
]

function ProductEditContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const productId = searchParams.get("id")
  const isEdit = !!productId
  
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [formData, setFormData] = useState({
    images: [] as string[],
    title: "",
    subtitle: "",
    description: "",
    price: "",
    originalPrice: "",
    stock: "",
    category: "",
    tags: [] as string[],
    isVirtual: false,
    allowRefund: true,
    limitPerPerson: "",
  })
  const [newTag, setNewTag] = useState("")
  
  useEffect(() => {
    if (isEdit) {
      setFormData({
        images: ["1", "2"],
        title: "滴天髓精解",
        subtitle: "命理学经典著作精装版",
        description: "详细描述内容...",
        price: "68",
        originalPrice: "98",
        stock: "156",
        category: "guji",
        tags: ["命理", "八字", "经典"],
        isVirtual: false,
        allowRefund: true,
        limitPerPerson: "",
      })
    }
  }, [isEdit])
  
  const addTag = () => {
    if (newTag && !formData.tags.includes(newTag) && formData.tags.length < 5) {
      setFormData(prev => ({ ...prev, tags: [...prev.tags, newTag] }))
      setNewTag("")
    }
  }
  
  const removeTag = (tag: string) => {
    setFormData(prev => ({ ...prev, tags: prev.tags.filter(t => t !== tag) }))
  }
  
  const handleSaveDraft = async () => {
    setIsSaving(true)
    await new Promise(resolve => setTimeout(resolve, 1000))
    setIsSaving(false)
  }
  
  const handlePublish = async () => {
    if (!formData.title || !formData.price || !formData.stock || !formData.category) {
      alert("请填写必填项")
      return
    }
    setIsSubmitting(true)
    await new Promise(resolve => setTimeout(resolve, 1500))
    setIsSubmitting(false)
    router.push("/merchant/products")
  }

  const selectedCategory = categories.find(c => c.id === formData.category)

  return (
    <div className="min-h-screen bg-background pb-32">
      <header className="sticky top-0 z-50 bg-background border-b border-border">
        <div className="flex items-center h-14 px-4">
          <Link href="/merchant/products" className="mr-3">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-lg font-semibold">{isEdit ? "编辑商品" : "发布商品"}</h1>
        </div>
      </header>
      
      <div className="p-4 space-y-4">
        {/* 商品图片 */}
        <Card className="p-4">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-medium">商品图片</h2>
            <span className="text-xs text-muted-foreground">最多9张，首图为封面</span>
          </div>
          <div className="grid grid-cols-3 gap-3">
            {formData.images.map((_, index) => (
              <div key={index} className="aspect-square rounded-lg bg-muted relative overflow-hidden border-2 border-dashed border-border">
                <div className="absolute inset-0 flex items-center justify-center">
                  <Camera className="w-8 h-8 text-muted-foreground" />
                </div>
                <button 
                  onClick={() => setFormData(prev => ({ ...prev, images: prev.images.filter((_, i) => i !== index) }))} 
                  className="absolute top-1 right-1 w-6 h-6 rounded-full bg-black/50 flex items-center justify-center"
                >
                  <X className="w-4 h-4 text-white" />
                </button>
                {index === 0 && (
                  <Badge className="absolute bottom-1 left-1 text-[10px]">封面</Badge>
                )}
              </div>
            ))}
            {formData.images.length < 9 && (
              <button 
                onClick={() => setFormData(prev => ({ ...prev, images: [...prev.images, String(prev.images.length + 1)] }))}
                className="aspect-square rounded-lg border-2 border-dashed border-border flex flex-col items-center justify-center hover:border-primary hover:bg-primary/5 transition-colors"
              >
                <Plus className="w-8 h-8 text-muted-foreground" />
                <span className="text-xs text-muted-foreground mt-1">添加图片</span>
              </button>
            )}
          </div>
        </Card>
        
        {/* 基本信息 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">基本信息</h2>
          
          <div className="space-y-2">
            <Label>商品名称 <span className="text-destructive">*</span></Label>
            <Input 
              placeholder="请输入商品名称（最多60字）" 
              value={formData.title} 
              onChange={e => setFormData(prev => ({ ...prev, title: e.target.value }))} 
              maxLength={60}
            />
            <p className="text-xs text-muted-foreground text-right">{formData.title.length}/60</p>
          </div>
          
          <div className="space-y-2">
            <Label>商品卖点</Label>
            <Input 
              placeholder="简要描述商品特点（最多30字）" 
              value={formData.subtitle} 
              onChange={e => setFormData(prev => ({ ...prev, subtitle: e.target.value }))} 
              maxLength={30}
            />
          </div>
          
          <div className="space-y-2">
            <Label>商品详情</Label>
            <Textarea 
              placeholder="详细描述商品信息、规格、使用方法等" 
              value={formData.description} 
              onChange={e => setFormData(prev => ({ ...prev, description: e.target.value }))} 
              rows={5}
            />
          </div>
        </Card>
        
        {/* 价格库存 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">价格库存</h2>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>售价 <span className="text-destructive">*</span></Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">¥</span>
                <Input 
                  type="number" 
                  placeholder="0.00" 
                  value={formData.price} 
                  onChange={e => setFormData(prev => ({ ...prev, price: e.target.value }))} 
                  className="pl-8"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label>原价（划线价）</Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">¥</span>
                <Input 
                  type="number" 
                  placeholder="0.00" 
                  value={formData.originalPrice} 
                  onChange={e => setFormData(prev => ({ ...prev, originalPrice: e.target.value }))} 
                  className="pl-8"
                />
              </div>
            </div>
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>库存 <span className="text-destructive">*</span></Label>
              <Input 
                type="number" 
                placeholder="请输入库存数量" 
                value={formData.stock} 
                onChange={e => setFormData(prev => ({ ...prev, stock: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <Label>限购数量</Label>
              <Input 
                type="number" 
                placeholder="不限制" 
                value={formData.limitPerPerson} 
                onChange={e => setFormData(prev => ({ ...prev, limitPerPerson: e.target.value }))}
              />
            </div>
          </div>
        </Card>
        
        {/* 分类与标签 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">分类与标签</h2>
          
          <div className="space-y-2">
            <Label>商品分类 <span className="text-destructive">*</span></Label>
            <Select value={formData.category} onValueChange={value => setFormData(prev => ({ ...prev, category: value }))}>
              <SelectTrigger>
                <SelectValue placeholder="请选择商品分类" />
              </SelectTrigger>
              <SelectContent>
                {categories.map(cat => (
                  <SelectItem key={cat.id} value={cat.id}>
                    <div className="flex items-center justify-between w-full">
                      <span>{cat.name}</span>
                      <span className="text-xs text-muted-foreground ml-2">佣金{cat.fee}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {selectedCategory && (
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <Info className="w-3 h-3" />
                该分类平台收取 {selectedCategory.fee} 技术服务费
              </p>
            )}
          </div>
          
          <div className="space-y-2">
            <Label>商品标签（最多5个）</Label>
            <div className="flex flex-wrap gap-2 mb-2">
              {formData.tags.map(tag => (
                <Badge key={tag} variant="secondary" className="gap-1">
                  {tag}
                  <button onClick={() => removeTag(tag)}>
                    <X className="w-3 h-3" />
                  </button>
                </Badge>
              ))}
            </div>
            <div className="flex gap-2">
              <Input 
                placeholder="输入标签后回车添加" 
                value={newTag} 
                onChange={e => setNewTag(e.target.value)} 
                onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addTag())} 
                className="flex-1"
              />
              <Button variant="outline" onClick={addTag} disabled={formData.tags.length >= 5}>
                <Plus className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </Card>
        
        {/* 其他设置 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">其他设置</h2>
          
          <div className="flex items-center justify-between">
            <div>
              <Label>虚拟商品</Label>
              <p className="text-xs text-muted-foreground mt-0.5">虚拟商品无需发货</p>
            </div>
            <Switch 
              checked={formData.isVirtual}
              onCheckedChange={checked => setFormData(prev => ({ ...prev, isVirtual: checked }))}
            />
          </div>
          
          <div className="flex items-center justify-between">
            <div>
              <Label>支持退款</Label>
              <p className="text-xs text-muted-foreground mt-0.5">买家可申请退款退货</p>
            </div>
            <Switch 
              checked={formData.allowRefund}
              onCheckedChange={checked => setFormData(prev => ({ ...prev, allowRefund: checked }))}
            />
          </div>
        </Card>
      </div>
      
      {/* 底部操作栏 */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t border-border safe-area-bottom">
        <div className="flex gap-3">
          <Button 
            variant="outline" 
            className="flex-1" 
            onClick={handleSaveDraft} 
            disabled={isSaving}
          >
            {isSaving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
            保存草稿
          </Button>
          <Button 
            className="flex-1" 
            onClick={handlePublish} 
            disabled={isSubmitting}
          >
            {isSubmitting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
            {isEdit ? "保存修改" : "立即发布"}
          </Button>
        </div>
      </div>
    </div>
  )
}

export default function ProductEditPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    }>
      <ProductEditContent />
    </Suspense>
  )
}
