// v0-reference/proto-ref-app/flash-sale/page.tsx
"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { Zap, Clock } from "lucide-react"
import { BackButton } from "@/components/common/back-button"
import { ProductCard, type ProductCardData } from "@/components/cards"

// 秒杀场次
const sessions = [
  { id: "s1", time: "10:00", label: "已开抢", status: "active" as const },
  { id: "s2", time: "14:00", label: "即将开始", status: "upcoming" as const },
  { id: "s3", time: "18:00", label: "即将开始", status: "upcoming" as const },
  { id: "s4", time: "20:00", label: "即将开始", status: "upcoming" as const },
]

// 秒杀商品
const flashProducts: (ProductCardData & { stock: number; sold: number })[] = [
  { id: "f1", title: "天然黑曜石貔貅手链 招财转运", cover: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&q=80", coverRatio: "1:1", price: 68, originalPrice: 268, sales: 2600, tag: "秒杀", stock: 100, sold: 78 },
  { id: "f2", title: "专业风水罗盘 纯铜精工", cover: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=400&q=80", coverRatio: "1:1", price: 158, originalPrice: 598, sales: 890, tag: "秒杀", stock: 50, sold: 42 },
  { id: "f3", title: "开光五帝钱挂件 镇宅化煞", cover: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&q=80", coverRatio: "1:1", price: 28, originalPrice: 128, sales: 4500, tag: "秒杀", stock: 200, sold: 156 },
  { id: "f4", title: "天然水晶七星阵摆件", cover: "https://images.unsplash.com/photo-1600721391689-2564bb8055de?w=400&q=80", coverRatio: "1:1", price: 99, originalPrice: 358, sales: 1200, tag: "秒杀", stock: 80, sold: 61 },
]

function useCountdown(targetMinutes: number) {
  const [seconds, setSeconds] = useState(targetMinutes * 60)
  useEffect(() => {
    const timer = setInterval(() => {
      setSeconds((s) => (s > 0 ? s - 1 : 0))
    }, 1000)
    return () => clearInterval(timer)
  }, [])
  const h = String(Math.floor(seconds / 3600)).padStart(2, "0")
  const m = String(Math.floor((seconds % 3600) / 60)).padStart(2, "0")
  const s = String(seconds % 60).padStart(2, "0")
  return { h, m, s }
}

export default function FlashSalePage() {
  const [activeSession, setActiveSession] = useState("s1")
  const { h, m, s } = useCountdown(125)

  return (
    <div className="min-h-screen bg-background pb-8">
      {/* 顶部栏 */}
      <header className="sticky top-0 z-20 bg-primary text-primary-foreground">
        <div className="flex items-center gap-2 px-4 h-14">
          <BackButton fallbackPath="/discover" iconClassName="text-primary-foreground" />
          <h1 className="text-lg font-semibold flex items-center gap-1.5">
            <Zap className="w-5 h-5" />
            限时秒杀
          </h1>
          <div className="ml-auto flex items-center gap-1.5 text-sm">
            <Clock className="w-4 h-4" />
            <span>距本场结束</span>
            <span className="flex items-center gap-0.5 font-mono">
              <span className="bg-foreground/20 rounded px-1 py-0.5 text-xs">{h}</span>
              <span>:</span>
              <span className="bg-foreground/20 rounded px-1 py-0.5 text-xs">{m}</span>
              <span>:</span>
              <span className="bg-foreground/20 rounded px-1 py-0.5 text-xs">{s}</span>
            </span>
          </div>
        </div>

        {/* 场次选择 */}
        <div className="flex gap-2 px-4 pb-3 overflow-x-auto scrollbar-hide">
          {sessions.map((session) => (
            <button
              key={session.id}
              onClick={() => setActiveSession(session.id)}
              className={`shrink-0 flex flex-col items-center px-5 py-1.5 rounded-lg transition-colors ${
                activeSession === session.id
                  ? "bg-primary-foreground text-primary"
                  : "bg-foreground/10 text-primary-foreground"
              }`}
            >
              <span className="text-base font-semibold">{session.time}</span>
              <span className="text-xs opacity-90">{session.label}</span>
            </button>
          ))}
        </div>
      </header>

      {/* 秒杀商品列表 */}
      <div className="px-4 pt-4 space-y-3">
        {flashProducts.map((product) => {
          const percent = Math.round((product.sold / product.stock) * 100)
          return (
            <Link
              key={product.id}
              href={`/product/${product.id}`}
              className="flex gap-3 bg-card rounded-xl p-3 border border-border"
            >
              <div className="relative w-28 h-28 shrink-0 rounded-lg overflow-hidden bg-secondary">
                <img
                  src={product.cover || "/placeholder.svg"}
                  alt={product.title}
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="flex-1 min-w-0 flex flex-col">
                <h3 className="text-sm font-medium text-foreground line-clamp-2 leading-snug">
                  {product.title}
                </h3>
                <div className="mt-auto">
                  {/* 进度条 */}
                  <div className="relative h-4 bg-secondary rounded-full overflow-hidden mb-2">
                    <div
                      className="absolute inset-y-0 left-0 bg-primary/80 rounded-full"
                      style={{ width: `${percent}%` }}
                    />
                    <span className="absolute inset-0 flex items-center justify-center text-[10px] text-foreground font-medium">
                      已抢 {percent}%
                    </span>
                  </div>
                  <div className="flex items-end justify-between">
                    <div className="flex items-baseline gap-1.5">
                      <span className="text-lg font-bold text-primary">¥{product.price}</span>
                      <span className="text-xs text-muted-foreground line-through">
                        ¥{product.originalPrice}
                      </span>
                    </div>
                    <span className="px-4 py-1.5 rounded-full bg-primary text-primary-foreground text-sm font-medium">
                      马上抢
                    </span>
                  </div>
                </div>
              </div>
            </Link>
          )
        })}
      </div>
    </div>
  )
}

// apps/mobile/src/pages_backup_20260609/flash-sale/index.vue
<template>
  <view class="fs-page">
    <view class="fs-header">
      <view class="fsh-row">
        <text class="fsh-back" @click="uni.navigateBack()">‹</text>
        <text class="fsh-title">⚡ 限时秒杀</text>
        <view class="fsh-countdown">
          <text class="fsh-cd-label">距本场结束</text>
          <view class="fsh-cd-nums">
            <text class="cd-num">{{ h }}</text>
            <text>:</text>
            <text class="cd-num">{{ m }}</text>
            <text>:</text>
            <text class="cd-num">{{ s }}</text>
          </view>
        </view>
      </view>
      <view class="fsh-sessions">
        <view v-for="se in sessions" :key="se.id" class="fsh-se" :class="{ active: activeSession === se.id }" @click="activeSession = se.id">
          <text class="fsh-se-time">{{ se.time }}</text>
          <text class="fsh-se-label">{{ se.label }}</text>
        </view>
      </view>
    </view>

    <view class="fs-products">
      <view v-for="p in flashProducts" :key="p.id" class="fs-product" @click="goPage('/pages/product/' + p.id)">
        <view class="fsp-img">
          <text class="fsp-img-icon">📦</text>
        </view>
        <view class="fsp-info">
          <text class="fsp-name">{{ p.title }}</text>
          <view class="fsp-progress">
            <view class="fsp-progress-bar">
              <view class="fsp-progress-fill" :style="{ width: percent(p) + '%' }" />
              <text class="fsp-progress-text">已抢 {{ percent(p) }}%</text>
            </view>
          </view>
          <view class="fsp-bottom">
            <view class="fsp-price-row">
              <text class="fsp-price">¥{{ p.price }}</text>
              <text class="fsp-orig">¥{{ p.originalPrice }}</text>
            </view>
            <view class="fsp-btn">马上抢</view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const activeSession = ref('s1')

const sessions = [
  { id: 's1', time: '10:00', label: '已开抢', status: 'active' },
  { id: 's2', time: '14:00', label: '即将开始', status: 'upcoming' },
  { id: 's3', time: '18:00', label: '即将开始', status: 'upcoming' },
  { id: 's4', time: '20:00', label: '即将开始', status: 'upcoming' },
]

const flashProducts = [
  { id: 'f1', title: '天然黑曜石貔貅手链 招财转运', price: 68, originalPrice: 268, stock: 100, sold: 78 },
  { id: 'f2', title: '专业风水罗盘 纯铜精工', price: 158, originalPrice: 598, stock: 50, sold: 42 },
  { id: 'f3', title: '开光五帝钱挂件 镇宅化煞', price: 28, originalPrice: 128, stock: 200, sold: 156 },
  { id: 'f4', title: '天然水晶七星阵摆件', price: 99, originalPrice: 358, stock: 80, sold: 61 },
]

let timer: any = null
let totalSeconds = 125 * 60

const h = ref('02')
const m = ref('05')
const s = ref('00')

function updateCountdown() {
  if (totalSeconds > 0) totalSeconds--
  h.value = String(Math.floor(totalSeconds / 3600)).padStart(2, '0')
  m.value = String(Math.floor((totalSeconds % 3600) / 60)).padStart(2, '0')
  s.value = String(totalSeconds % 60).padStart(2, '0')
}

onMounted(() => { updateCountdown(); timer = setInterval(updateCountdown, 1000) })
onUnmounted(() => { if (timer) clearInterval(timer) })

function percent(p: typeof flashProducts[0]) { return Math.round((p.sold / p.stock) * 100) }

function goPage(url: string) { uni.navigateTo({ url }) }
</script>

<style scoped>
.fs-page { min-height: 100vh; background: #FAF8F5; padding-bottom: 40rpx; }
.fs-header { background: linear-gradient(135deg, #C41E3A, #C9A96E); }
.fsh-row { display: flex; align-items: center; padding: 0 16rpx; height: 88rpx; }
.fsh-back { font-size: 48rpx; color: #fff; width: 56rpx; }
.fsh-title { font-size: 30rpx; font-weight: 700; color: #fff; margin-right: 16rpx; }
.fsh-countdown { display: flex; align-items: center; gap: 6rpx; margin-left: auto; }
.fsh-cd-label { font-size: 20rpx; color: rgba(255,255,255,0.75); }
.fsh-cd-nums { display: flex; align-items: center; gap: 2rpx; font-size: 20rpx; color: #fff; }
.cd-num { padding: 4rpx 8rpx; background: rgba(255,255,255,0.2); border-radius: 4rpx; font-weight: 600; }

.fsh-sessions { display: flex; gap: 8rpx; padding: 0 24rpx 16rpx; }
.fsh-se { display: flex; flex-direction: column; align-items: center; padding: 8rpx 24rpx; border-radius: 10rpx; background: rgba(255,255,255,0.1); }
.fsh-se.active { background: #fff; }
.fsh-se-time { font-size: 26rpx; font-weight: 600; color: #fff; }
.fsh-se.active .fsh-se-time { color: #C41E3A; }
.fsh-se-label { font-size: 18rpx; color: rgba(255,255,255,0.7); }
.fsh-se.active .fsh-se-label { color: #C9A96E; }

.fs-products { padding: 16rpx 24rpx; }
.fs-product { display: flex; gap: 16rpx; background: #fff; border-radius: 16rpx; padding: 16rpx; margin-bottom: 14rpx; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.fsp-img { width: 180rpx; height: 180rpx; background: #F5F1EB; border-radius: 14rpx; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.fsp-img-icon { font-size: 56rpx; opacity: 0.3; }

.fsp-info { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.fsp-name { font-size: 26rpx; font-weight: 500; color: #333; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; line-height: 1.4; }

.fsp-progress { margin-top: auto; }
.fsp-progress-bar { height: 32rpx; background: #FFF0F0; border-radius: 16rpx; position: relative; overflow: hidden; }
.fsp-progress-fill { height: 100%; background: linear-gradient(90deg, #C41E3A, #C9A96E); border-radius: 16rpx; }
.fsp-progress-text { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; font-size: 18rpx; color: #333; font-weight: 500; }

.fsp-bottom { display: flex; align-items: flex-end; justify-content: space-between; margin-top: 12rpx; }
.fsp-price-row { display: flex; align-items: baseline; gap: 6rpx; }
.fsp-price { font-size: 32rpx; font-weight: 700; color: #C41E3A; }
.fsp-orig { font-size: 20rpx; color: #BBB; text-decoration: line-through; }
.fsp-btn { padding: 8rpx 28rpx; border-radius: 24rpx; background: #C41E3A; color: #fff; font-size: 24rpx; font-weight: 500; }
</style>
