// app/offline/products/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import Image from "next/image"
import { 
  ChevronLeft, 
  Search,
  ShoppingCart,
  Filter,
  ChevronDown,
  BookOpen,
  Compass,
  Coffee,
  Flame,
  Gem,
  Package,
  Check
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import { 
  getStationProducts,
  getStationList,
  getProductCategoryLabel,
  addToCart,
} from "@/lib/api/offline"
import type { StationProduct, StationProductCategory, Station } from "@/lib/types/offline"

// 骨架屏
function Skeleton({ className }: { className?: string }) {
  return <div className={cn("animate-pulse bg-muted rounded", className)} />
}

// 加载骨架屏
function LoadingSkeleton() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 bg-background border-b border-border px-4 py-3">
        <div className="flex items-center gap-3">
          <Skeleton className="w-8 h-8 rounded-full" />
          <Skeleton className="h-5 w-24" />
        </div>
      </header>
      <div className="p-4">
        <Skeleton className="h-10 w-full rounded-lg mb-4" />
        <div className="grid grid-cols-2 gap-3">
          {[1, 2, 3, 4].map(i => (
            <Skeleton key={i} className="aspect-square rounded-lg" />
          ))}
        </div>
      </div>
    </div>
  )
}

// 分类图标
const categoryIcons: Record<StationProductCategory, React.ReactNode> = {
  book: <BookOpen className="w-4 h-4" />,
  tool: <Compass className="w-4 h-4" />,
  tea: <Coffee className="w-4 h-4" />,
  incense: <Flame className="w-4 h-4" />,
  ornament: <Gem className="w-4 h-4" />,
  other: <Package className="w-4 h-4" />,
}

// 分类列表
const categories: { value: StationProductCategory | 'all'; label: string }[] = [
  { value: 'all', label: '全部' },
  { value: 'book', label: '图书' },
  { value: 'tool', label: '工具' },
  { value: 'tea', label: '茶品' },
  { value: 'incense', label: '香品' },
  { value: 'ornament', label: '饰品' },
  { value: 'other', label: '其他' },
]

// 排序选项
const sortOptions = [
  { value: 'default', label: '默认排序' },
  { value: 'sales', label: '销量优先' },
  { value: 'price', label: '价格优先' },
  { value: 'newest', label: '最新上架' },
]

function ProductsContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const stationIdParam = searchParams.get('stationId')
  
  // 状态
  const [products, setProducts] = useState<StationProduct[]>([])
  const [stations, setStations] = useState<Station[]>([])
  const [loading, setLoading] = useState(true)
  const [keyword, setKeyword] = useState("")
  const [selectedStation, setSelectedStation] = useState<number | undefined>(
    stationIdParam ? Number(stationIdParam) : undefined
  )
  const [selectedCategory, setSelectedCategory] = useState<StationProductCategory | 'all'>('all')
  const [sortBy, setSortBy] = useState<'default' | 'sales' | 'price' | 'newest'>('default')
  const [showStationPicker, setShowStationPicker] = useState(false)
  const [showSortPicker, setShowSortPicker] = useState(false)
  const [cartCount, setCartCount] = useState(0)
  const [addingToCart, setAddingToCart] = useState<number | null>(null)

  // 加载驿站列表
  useEffect(() => {
    async function loadStations() {
      const res = await getStationList()
      if (res.code === 200 && res.data) {
        setStations(res.data.list)
      }
    }
    loadStations()
  }, [])

  // 加载商品列表
  useEffect(() => {
    async function loadProducts() {
      setLoading(true)
      const res = await getStationProducts({
        stationId: selectedStation,
        category: selectedCategory === 'all' ? undefined : selectedCategory,
        keyword: keyword || undefined,
        sortBy: sortBy === 'default' ? undefined : sortBy as 'price' | 'sales' | 'newest',
      })
      if (res.code === 200 && res.data) {
        setProducts(res.data.list)
      }
      setLoading(false)
    }
    loadProducts()
  }, [selectedStation, selectedCategory, sortBy, keyword])

  // 添加到购物车
  const handleAddToCart = async (productId: number, e: React.MouseEvent) => {
    e.stopPropagation()
    setAddingToCart(productId)
    const res = await addToCart(productId)
    if (res.code === 200 && res.data) {
      setCartCount(prev => prev + 1)
    }
    setTimeout(() => setAddingToCart(null), 500)
  }

  // 搜索
  const handleSearch = () => {
    // 触发重新加载
  }

  const selectedStationName = selectedStation 
    ? stations.find(s => s.id === selectedStation)?.name || '选择驿站'
    : '全部驿站'

  return (
    <div className="min-h-screen bg-background pb-20">
      {/* 头部 */}
      <header className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="px-4 py-3 flex items-center gap-3">
          <button onClick={() => router.back()} className="p-1">
            <ChevronLeft className="w-6 h-6" />
          </button>
          <h1 className="text-lg font-semibold flex-1">驿站商品</h1>
          <button 
            onClick={() => router.push('/cart')}
            className="relative p-1"
          >
            <ShoppingCart className="w-6 h-6" />
            {cartCount > 0 && (
              <span className="absolute -top-1 -right-1 w-5 h-5 bg-primary text-primary-foreground text-xs rounded-full flex items-center justify-center">
                {cartCount}
              </span>
            )}
          </button>
        </div>
        
        {/* 搜索框 */}
        <div className="px-4 pb-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="搜索商品..."
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
              className="pl-10"
            />
          </div>
        </div>
        
        {/* 筛选栏 */}
        <div className="px-4 pb-3 flex items-center gap-2">
          {/* 驿站筛选 */}
          <button 
            onClick={() => setShowStationPicker(true)}
            className="flex items-center gap-1 px-3 py-1.5 bg-muted rounded-full text-sm"
          >
            <span className="truncate max-w-[100px]">{selectedStationName}</span>
            <ChevronDown className="w-4 h-4 flex-shrink-0" />
          </button>
          
          {/* 排序 */}
          <button 
            onClick={() => setShowSortPicker(true)}
            className="flex items-center gap-1 px-3 py-1.5 bg-muted rounded-full text-sm"
          >
            <Filter className="w-4 h-4" />
            <span>{sortOptions.find(s => s.value === sortBy)?.label}</span>
          </button>
        </div>
        
        {/* 分类Tab */}
        <div className="px-4 pb-3 overflow-x-auto">
          <div className="flex gap-2">
            {categories.map(cat => (
              <button
                key={cat.value}
                onClick={() => setSelectedCategory(cat.value)}
                className={cn(
                  "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors",
                  selectedCategory === cat.value
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground"
                )}
              >
                {cat.value !== 'all' && categoryIcons[cat.value as StationProductCategory]}
                <span>{cat.label}</span>
              </button>
            ))}
          </div>
        </div>
      </header>

      {/* 商品网格 */}
      <div className="p-4">
        {loading ? (
          <div className="grid grid-cols-2 gap-3">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <div key={i} className="bg-card rounded-lg overflow-hidden">
                <Skeleton className="aspect-square" />
                <div className="p-3 space-y-2">
                  <Skeleton className="h-4 w-3/4" />
                  <Skeleton className="h-4 w-1/2" />
                </div>
              </div>
            ))}
          </div>
        ) : products.length === 0 ? (
          <div className="text-center py-20">
            <Package className="w-16 h-16 mx-auto text-muted-foreground/50 mb-4" />
            <p className="text-muted-foreground">暂无商品</p>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-3">
            {products.map(product => (
              <div 
                key={product.id}
                onClick={() => router.push(`/offline/products/${product.id}`)}
                className="bg-card rounded-lg overflow-hidden shadow-sm cursor-pointer active:scale-[0.98] transition-transform"
              >
                {/* 商品图片 */}
                <div className="relative aspect-square bg-muted">
                  <Image
                    src={product.cover}
                    alt={product.name}
                    fill
                    className="object-cover"
                  />
                  {product.originalPrice && product.originalPrice > product.price && (
                    <div className="absolute top-2 left-2 px-2 py-0.5 bg-primary text-primary-foreground text-xs rounded">
                      {Math.round((1 - product.price / product.originalPrice) * 100)}%OFF
                    </div>
                  )}
                </div>
                
                {/* 商品信息 */}
                <div className="p-3">
                  <h3 className="text-sm font-medium line-clamp-2 mb-2">{product.name}</h3>
                  
                  {/* 标签 */}
                  {product.tags && product.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1 mb-2">
                      {product.tags.slice(0, 2).map(tag => (
                        <span 
                          key={tag}
                          className="px-1.5 py-0.5 bg-primary/10 text-primary text-xs rounded"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  )}
                  
                  {/* 价格和购买 */}
                  <div className="flex items-end justify-between">
                    <div>
                      <span className="text-primary font-bold">¥{product.price}</span>
                      {product.originalPrice && product.originalPrice > product.price && (
                        <span className="text-xs text-muted-foreground line-through ml-1">
                          ¥{product.originalPrice}
                        </span>
                      )}
                      <div className="text-xs text-muted-foreground mt-0.5">
                        已售 {product.sales}
                      </div>
                    </div>
                    
                    <button
                      onClick={(e) => handleAddToCart(product.id, e)}
                      disabled={addingToCart === product.id}
                      className={cn(
                        "w-8 h-8 rounded-full flex items-center justify-center transition-colors",
                        addingToCart === product.id
                          ? "bg-green-500 text-white"
                          : "bg-primary text-primary-foreground"
                      )}
                    >
                      {addingToCart === product.id ? (
                        <Check className="w-4 h-4" />
                      ) : (
                        <ShoppingCart className="w-4 h-4" />
                      )}
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* 驿站选择弹窗 */}
      {showStationPicker && (
        <div className="fixed inset-0 z-50 bg-black/50" onClick={() => setShowStationPicker(false)}>
          <div 
            className="absolute bottom-0 left-0 right-0 bg-background rounded-t-2xl max-h-[60vh] overflow-hidden"
            onClick={e => e.stopPropagation()}
          >
            <div className="p-4 border-b border-border flex items-center justify-between">
              <h3 className="font-semibold">选择驿站</h3>
              <button onClick={() => setShowStationPicker(false)}>
                <ChevronDown className="w-5 h-5" />
              </button>
            </div>
            <div className="overflow-y-auto max-h-[50vh]">
              <button
                onClick={() => {
                  setSelectedStation(undefined)
                  setShowStationPicker(false)
                }}
                className={cn(
                  "w-full px-4 py-3 text-left flex items-center justify-between",
                  !selectedStation && "bg-primary/10 text-primary"
                )}
              >
                <span>全部驿站</span>
                {!selectedStation && <Check className="w-5 h-5" />}
              </button>
              {stations.map(station => (
                <button
                  key={station.id}
                  onClick={() => {
                    setSelectedStation(station.id)
                    setShowStationPicker(false)
                  }}
                  className={cn(
                    "w-full px-4 py-3 text-left flex items-center justify-between",
                    selectedStation === station.id && "bg-primary/10 text-primary"
                  )}
                >
                  <div>
                    <div className="font-medium">{station.name}</div>
                    <div className="text-sm text-muted-foreground">{station.city}</div>
                  </div>
                  {selectedStation === station.id && <Check className="w-5 h-5" />}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* 排序选择弹窗 */}
      {showSortPicker && (
        <div className="fixed inset-0 z-50 bg-black/50" onClick={() => setShowSortPicker(false)}>
          <div 
            className="absolute bottom-0 left-0 right-0 bg-background rounded-t-2xl"
            onClick={e => e.stopPropagation()}
          >
            <div className="p-4 border-b border-border flex items-center justify-between">
              <h3 className="font-semibold">排序方��</h3>
              <button onClick={() => setShowSortPicker(false)}>
                <ChevronDown className="w-5 h-5" />
              </button>
            </div>
            <div>
              {sortOptions.map(option => (
                <button
                  key={option.value}
                  onClick={() => {
                    setSortBy(option.value as typeof sortBy)
                    setShowSortPicker(false)
                  }}
                  className={cn(
                    "w-full px-4 py-3 text-left flex items-center justify-between",
                    sortBy === option.value && "bg-primary/10 text-primary"
                  )}
                >
                  <span>{option.label}</span>
                  {sortBy === option.value && <Check className="w-5 h-5" />}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default function ProductsPage() {
  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <ProductsContent />
    </Suspense>
  )
}

// apps/mobile/src/pages/offline/products.vue
<template>
  <view class="page">
    <!-- 头部 -->
    <view class="header">
      <view class="header-row">
        <text
          class="back-btn"
          @click="goBack"
        >
          ←
        </text>
        <text class="header-title">
          驿站商品
        </text>
        <view
          class="cart-btn-wrap"
          @click="goCart"
        >
          <text>🛒</text>
          <text
            v-if="cartCount > 0"
            class="cart-badge"
          >
            {{ cartCount }}
          </text>
        </view>
      </view>
      <!-- 搜索框 -->
      <view class="search-wrap">
        <text class="search-icon">
          🔍
        </text>
        <input
          v-model="keyword"
          class="search-input"
          placeholder="搜索商品..."
          @confirm="handleSearch"
        >
      </view>
      <!-- 筛选栏 -->
      <view class="filter-row">
        <view
          class="filter-btn"
          @click="showStationPicker = true"
        >
          <text class="filter-text">
            {{ selectedStationName }}
          </text>
          <text>▼</text>
        </view>
        <view
          class="filter-btn"
          @click="showSortPicker = true"
        >
          <text>☰</text>
          <text class="filter-text">
            {{ sortLabel }}
          </text>
        </view>
      </view>
      <!-- 分类Tab -->
      <scroll-view
        scroll-x
        class="category-scroll"
        show-scrollbar="false"
      >
        <view class="category-inner">
          <text
            v-for="cat in categories"
            :key="cat.value"
            class="category-tab"
            :class="{ active: selectedCategory === cat.value }"
            @click="selectedCategory = cat.value"
          >
            {{ cat.value !== 'all' ? (categoryIcons[cat.value] || '') : '' }} {{ cat.label }}
          </text>
        </view>
      </scroll-view>
    </view>

    <!-- 商品网格 -->
    <DataState
      :is-loading="loading && products.length === 0"
      :is-empty="!loading && products.length === 0"
      empty-icon="📦"
      empty-title="暂无商品"
      skeleton-type="card"
      @retry="loadProducts"
    >
      <view class="product-grid">
        <view
          v-for="p in products"
          :key="p.id"
          class="product-card"
          @click="goProduct(p)"
        >
          <view class="product-img-wrap">
            <image
              :src="p.cover"
              class="product-img"
              mode="aspectFill"
            />
            <text
              v-if="p.originalPrice && p.originalPrice > p.price"
              class="product-discount"
            >
              {{ Math.round((1 - p.price / p.originalPrice) * 100) }}%OFF
            </text>
          </view>
          <view class="product-body">
            <text class="product-name">
              {{ p.name }}
            </text>
            <view
              v-if="p.tags && p.tags.length"
              class="product-tags"
            >
              <text
                v-for="tag in p.tags.slice(0, 2)"
                :key="tag"
                class="product-tag"
              >
                {{ tag }}
              </text>
            </view>
            <view class="product-bottom">
              <view class="product-price-row">
                <text class="product-price">
                  ¥{{ p.price }}
                </text>
                <text
                  v-if="p.originalPrice && p.originalPrice > p.price"
                  class="product-original-price"
                >
                  ¥{{ p.originalPrice }}
                </text>
              </view>
              <text
                class="product-add-cart"
                :class="{ added: addingToCart === p.id }"
                @click.stop="handleAddToCart(p.id)"
              >
                {{ addingToCart === p.id ? '✓' : '+' }}
              </text>
            </view>
            <text class="product-sales">
              已售 {{ p.sales || 0 }}
            </text>
          </view>
        </view>
      </view>
    </DataState>

    <!-- 驿站选择弹窗 -->
    <view
      v-if="showStationPicker"
      class="mask"
      @click="showStationPicker = false"
    >
      <view
        class="bottom-sheet"
        @click.stop
      >
        <view class="sheet-header">
          <text class="sheet-title">
            选择驿站
          </text>
          <text @click="showStationPicker = false">
            ▼
          </text>
        </view>
        <scroll-view
          scroll-y
          class="sheet-scroll"
        >
          <view
            class="sheet-item"
            :class="{ active: !selectedStation }"
            @click="selectStation(undefined)"
          >
            <text>全部驿站</text>
            <text v-if="!selectedStation">
              ✓
            </text>
          </view>
          <view
            v-for="s in stations"
            :key="s.id"
            class="sheet-item"
            :class="{ active: selectedStation === s.id }"
            @click="selectStation(s.id)"
          >
            <view>
              <text class="sheet-item-name">
                {{ s.name }}
              </text>
              <text class="sheet-item-city">
                {{ s.city }}
              </text>
            </view>
            <text v-if="selectedStation === s.id">
              ✓
            </text>
          </view>
        </scroll-view>
      </view>
    </view>

    <!-- 排序选择弹窗 -->
    <view
      v-if="showSortPicker"
      class="mask"
      @click="showSortPicker = false"
    >
      <view
        class="bottom-sheet"
        @click.stop
      >
        <view class="sheet-header">
          <text class="sheet-title">
            排序方式
          </text>
          <text @click="showSortPicker = false">
            ▼
          </text>
        </view>
        <view>
          <view
            v-for="opt in sortOptions"
            :key="opt.value"
            class="sheet-item"
            :class="{ active: sortBy === opt.value }"
            @click="selectSort(opt.value)"
          >
            <text>{{ opt.label }}</text>
            <text v-if="sortBy === opt.value">
              ✓
            </text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { offlineApi, shopApi } from '../../api'
import DataState from '../../components/DataState.vue'

interface Product {
  id: number
  name: string
  cover: string
  price: number
  originalPrice?: number
  sales?: number
  tags?: string[]
}

interface Station {
  id: number
  name: string
  city?: string
}

const categoryIcons: Record<string, string> = {
  book: '📖',
  tool: '🧭',
  tea: '☕',
  incense: '🔥',
  ornament: '💎',
  other: '📦',
}

const categories = [
  { value: 'all', label: '全部' },
  { value: 'book', label: '图书' },
  { value: 'tool', label: '工具' },
  { value: 'tea', label: '茶品' },
  { value: 'incense', label: '香品' },
  { value: 'ornament', label: '饰品' },
  { value: 'other', label: '其他' },
]

const sortOptions = [
  { value: 'default', label: '默认排序' },
  { value: 'sales', label: '销量优先' },
  { value: 'price', label: '价格优先' },
  { value: 'newest', label: '最新上架' },
]

const products = ref<Product[]>([])
const stations = ref<Station[]>([])
const loading = ref(false)
const keyword = ref('')
const selectedStation = ref<number | undefined>()
const selectedCategory = ref('all')
const sortBy = ref('default')
const showStationPicker = ref(false)
const showSortPicker = ref(false)
const cartCount = ref(0)
const addingToCart = ref<number | null>(null)

const selectedStationName = computed(() =>
  selectedStation.value
    ? stations.value.find(s => s.id === selectedStation.value)?.name || '选择驿站'
    : '全部驿站'
)

const sortLabel = computed(() =>
  sortOptions.find(s => s.value === sortBy.value)?.label || '默认排序'
)

onMounted(() => {
  loadStations()
  loadProducts()
})

watch([selectedStation, selectedCategory, sortBy, keyword], () => { loadProducts() })

async function loadStations() {
  try {
    const res: any = await offlineApi.stations()
    stations.value = Array.isArray(res) ? res : res?.list || res?.data || []
  } catch (e: any) {
    console.error(e)
  }
}

async function loadProducts() {
  loading.value = true
  try {
    const params: any = {}
    if (selectedStation.value) params.stationId = selectedStation.value
    if (selectedCategory.value !== 'all') params.category = selectedCategory.value
    if (keyword.value) params.keyword = keyword.value
    if (sortBy.value !== 'default') params.sortBy = sortBy.value
    const { stationId: sid, ...filters } = params
    const res: any = await offlineApi.getProducts(String(sid || 1), filters)
    const list = Array.isArray(res) ? res : res?.list || res?.data || []
    products.value = list
  } catch (e: any) {
    console.error(e)
  } finally {
    loading.value = false
  }
}

function selectStation(id: number | undefined) {
  selectedStation.value = id
  showStationPicker.value = false
}

function selectSort(val: string) {
  sortBy.value = val
  showSortPicker.value = false
}

async function handleAddToCart(productId: number) {
  addingToCart.value = productId
  try {
    await shopApi.addToCart({ productId: String(productId) })
    cartCount.value += 1
  } catch (e: any) {
    console.error(e)
  }
  setTimeout(() => { addingToCart.value = null }, 500)
}

function handleSearch() {
  // 搜索会自动通过watch触发loadProducts
}

function goProduct(p: Product) {
  uni.navigateTo({ url: `/pages/shop/detail?id=${p.id}` })
}

function goCart() {
  uni.navigateTo({ url: '/pages/shop/cart' })
}

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
.page {
  background: #F5F0E8;
  min-height: 100vh;
  padding-bottom: 40rpx;
}
.header {
  background: #fff;
  position: sticky;
  top: 0;
  z-index: 10;
  border-bottom: 1rpx solid #E5E1DB;
}
.header-row {
  display: flex;
  align-items: center;
  padding: 24rpx;
  gap: 12rpx;
}
.back-btn { font-size: 36rpx; }
.header-title { font-size: 32rpx; font-weight: 600; flex: 1; }
.cart-btn-wrap { position: relative; font-size: 32rpx; padding: 8rpx; }
.cart-badge {
  position: absolute;
  top: -4rpx;
  right: -4rpx;
  width: 32rpx;
  height: 32rpx;
  background: #C41E3A;
  color: #fff;
  font-size: 20rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.search-wrap {
  position: relative;
  margin: 0 24rpx 12rpx;
}
.search-icon {
  position: absolute;
  left: 20rpx;
  top: 50%;
  transform: translateY(-50%);
  font-size: 28rpx;
}
.search-input {
  width: 100%;
  height: 64rpx;
  background: #F5F0E8;
  border-radius: 32rpx;
  padding-left: 60rpx;
  font-size: 26rpx;
  border: none;
  box-sizing: border-box;
}

.filter-row {
  display: flex;
  gap: 12rpx;
  padding: 0 24rpx 12rpx;
}
.filter-btn {
  display: flex;
  align-items: center;
  gap: 6rpx;
  padding: 10rpx 20rpx;
  background: #F5F0E8;
  border-radius: 28rpx;
  font-size: 24rpx;
}
.filter-text { max-width: 140rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.category-scroll {
  white-space: nowrap;
  padding: 0 24rpx 16rpx;
}
.category-inner { display: inline-flex; gap: 12rpx; }
.category-tab {
  display: inline-flex;
  align-items: center;
  gap: 6rpx;
  font-size: 24rpx;
  color: #666;
  padding: 8rpx 22rpx;
  border-radius: 28rpx;
  background: #F5F0E8;
  border: 1rpx solid #E8E0D5;
}
.category-tab.active {
  background: linear-gradient(135deg, #C41E3A, #A01830);
  color: #fff;
  border-color: #C41E3A;
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16rpx;
  padding: 20rpx 24rpx;
}
.product-card {
  background: #fff;
  border-radius: 16rpx;
  overflow: hidden;
  box-shadow: 0 4rpx 12rpx rgba(0,0,0,0.04);
}
.product-img-wrap { position: relative; aspect-ratio: 1; background: #f0ebe3; }
.product-img { width: 100%; height: 100%; }
.product-discount {
  position: absolute;
  top: 12rpx;
  left: 12rpx;
  background: #C41E3A;
  color: #fff;
  font-size: 18rpx;
  padding: 2rpx 10rpx;
  border-radius: 4rpx;
}
.product-body { padding: 16rpx; }
.product-name { font-size: 24rpx; font-weight: 500; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; margin-bottom: 8rpx; }
.product-tags { display: flex; gap: 6rpx; margin-bottom: 8rpx; }
.product-tag { font-size: 18rpx; color: #C41E3A; background: rgba(196,30,58,0.08); padding: 2rpx 8rpx; border-radius: 4rpx; }
.product-bottom { display: flex; justify-content: space-between; align-items: flex-end; }
.product-price-row { display: flex; align-items: baseline; gap: 6rpx; }
.product-price { font-size: 26rpx; color: #C41E3A; font-weight: bold; }
.product-original-price { font-size: 18rpx; color: #999; text-decoration: line-through; }
.product-add-cart {
  width: 44rpx;
  height: 44rpx;
  border-radius: 50%;
  background: linear-gradient(135deg, #C41E3A, #A01830);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28rpx;
  font-weight: bold;
}
.product-add-cart.added { background: #27ae60; }
.product-sales { font-size: 18rpx; color: #999; display: block; margin-top: 4rpx; }

.mask {
  position: fixed;
  inset: 0;
  z-index: 50;
  background: rgba(0,0,0,0.5);
}
.bottom-sheet {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: #fff;
  border-radius: 24rpx 24rpx 0 0;
  max-height: 60vh;
  display: flex;
  flex-direction: column;
}
.sheet-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24rpx 32rpx;
  border-bottom: 1rpx solid #E5E1DB;
  font-size: 28rpx;
}
.sheet-title { font-weight: 600; }
.sheet-scroll { flex: 1; overflow-y: auto; }
.sheet-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20rpx 32rpx;
  border-bottom: 1rpx solid #f5f0e8;
  font-size: 24rpx;
  color: #666;
}
.sheet-item.active { color: #C41E3A; font-weight: 500; background: rgba(196,30,58,0.03); }
.sheet-item-name { display: block; }
.sheet-item-city { font-size: 20rpx; color: #999; display: block; margin-top: 4rpx; }
</style>
