// apps/mobile/src/pages_backup_20260609/downloads/index.vue
<template>
  <view class="dl-page">
    <view class="header-sticky">
      <view class="header-row">
        <text class="header-back" @click="uni.navigateBack()">‹</text>
        <text class="header-title">下载管理</text>
        <text v-if="downloadingTasks.length > 0" class="header-action" @click="toggleAllTasks">
          {{ allPaused ? '全部开始' : '全部暂停' }}
        </text>
        <view v-else class="header-spacer" />
      </view>
    </view>

    <view class="dl-content">
      <!-- 下载中 -->
      <view v-if="downloadingTasks.length > 0" class="section">
        <text class="section-title">🕐 下载中 ({{ downloadingTasks.length }})</text>
        <view class="task-list">
          <view v-for="task in downloadingTasks" :key="task.id" class="task-card">
            <view class="task-main">
              <view class="task-icon" :class="typeIconClass(task.type)">
                <text>{{ typeEmoji(task.type) }}</text>
              </view>
              <view class="task-info">
                <text class="task-name">{{ task.name }}</text>
                <text class="task-source">{{ task.source }}</text>
                <view class="task-progress-wrap">
                  <view class="task-progress-bar">
                    <view
                      class="task-progress-fill"
                      :class="task.status === 'failed' ? 'fill-fail' : task.status === 'paused' ? 'fill-pause' : 'fill-active'"
                      :style="{ width: task.progress + '%' }"
                    />
                  </view>
                  <view class="task-progress-stats">
                    <text class="tps-size">{{ fmtSize(task.downloaded) }} / {{ fmtSize(task.size) }}</text>
                    <view class="tps-right">
                      <text v-if="task.status === 'downloading'" class="tps-speed">{{ fmtSpeed(task.speed) }}</text>
                      <text class="tps-status" :class="statusClass(task.status)">{{ statusLabel(task.status) }}</text>
                    </view>
                  </view>
                </view>
              </view>
              <view class="task-actions">
                <view class="ta-btn" :class="{ pause: task.status === 'downloading' }" @click="toggleTask(task.id)">
                  <text>{{ task.status === 'downloading' ? '⏸' : '▶' }}</text>
                </view>
                <view class="ta-btn del" @click="cancelTask(task.id)">
                  <text>✕</text>
                </view>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 已完成 -->
      <view v-if="completedTasks.length > 0" class="section">
        <view class="section-head" @click="showCompleted = !showCompleted">
          <text class="section-title">✅ 已完成 ({{ completedTasks.length }})</text>
          <text class="section-arrow" :class="{ open: showCompleted }">›</text>
        </view>
        <view v-if="showCompleted" class="task-list">
          <view v-for="task in completedTasks" :key="task.id" class="task-card done">
            <view class="task-icon" :class="typeIconClass(task.type)">
              <text>{{ typeEmoji(task.type) }}</text>
            </view>
            <view class="task-info">
              <text class="task-name">{{ task.name }}</text>
              <text class="task-source">{{ fmtSize(task.size) }} | {{ task.createdAt.split(' ')[0] }}</text>
            </view>
            <view class="done-actions">
              <view class="da-open" @click="goPage(task.type === 'ebook' ? '/pages/reader/index' : '/pages/learn/index')">
                <text>{{ task.type === 'ebook' ? '阅读' : '播放' }}</text>
              </view>
              <view class="da-more" @click="showMenu = showMenu === task.id ? null : task.id">
                <text>⋯</text>
              </view>
              <view v-if="showMenu === task.id" class="menu-popup" @click.stop>
                <text class="menu-item del" @click="deleteCompleted(task.id)">删除文件</text>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 空状态 -->
      <view v-if="tasks.length === 0" class="empty-wrap">
        <text class="empty-icon">📂</text>
        <text class="empty-text">暂无下载任务</text>
        <view class="empty-btn" @click="goPage('/pages/discover/index')">
          <text>去发现内容</text>
        </view>
      </view>
    </view>

    <!-- 底部存储空间 -->
    <view class="storage-bar">
      <view class="storage-info">
        <text class="si-label">💾 存储空间</text>
        <text class="si-val">{{ fmtSize(storageInfo.used) }} / {{ fmtSize(storageInfo.total) }}</text>
      </view>
      <view class="storage-bar-track">
        <view class="sb-seg sb-video" :style="{ width: (storageInfo.videoSize / storageInfo.total * 100) + '%' }" />
        <view class="sb-seg sb-ebook" :style="{ width: (storageInfo.ebookSize / storageInfo.total * 100) + '%' }" />
        <view class="sb-seg sb-audio" :style="{ width: (storageInfo.audioSize / storageInfo.total * 100) + '%' }" />
      </view>
      <view class="storage-legend">
        <text class="sl-item"><view class="sl-dot sl-video" />视频 {{ fmtSize(storageInfo.videoSize) }}</text>
        <text class="sl-item"><view class="sl-dot sl-ebook" />电子书 {{ fmtSize(storageInfo.ebookSize) }}</text>
        <text class="sl-item"><view class="sl-dot sl-audio" />音频 {{ fmtSize(storageInfo.audioSize) }}</text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'

type DownloadStatus = 'downloading' | 'paused' | 'completed' | 'failed' | 'waiting'

interface DownloadTask {
  id: number; name: string; type: string; size: number; downloaded: number
  speed: number; status: DownloadStatus; progress: number; source: string; createdAt: string
}

const tasks = ref<DownloadTask[]>([
  { id: 1, name: '八字命理入门精讲 - 第1章', type: 'video', size: 256, downloaded: 168, speed: 1024, status: 'downloading', progress: 65, source: '八字命理入门', createdAt: '2026-05-10 14:30' },
  { id: 2, name: '渊海子平（完整版）', type: 'ebook', size: 48, downloaded: 24, speed: 0, status: 'paused', progress: 50, source: '古籍书库', createdAt: '2026-05-10 14:25' },
  { id: 3, name: '紫微斗数基础课 - 第3章', type: 'video', size: 180, downloaded: 36, speed: 512, status: 'downloading', progress: 20, source: '紫微斗数基础', createdAt: '2026-05-10 14:20' },
  { id: 4, name: '滴天髓精解', type: 'ebook', size: 32, downloaded: 32, speed: 0, status: 'completed', progress: 100, source: '古籍书库', createdAt: '2026-05-09 10:15' },
  { id: 5, name: '八字命理入门精讲 - 第2章', type: 'video', size: 220, downloaded: 220, speed: 0, status: 'completed', progress: 100, source: '八字命理入门', createdAt: '2026-05-09 09:30' },
  { id: 6, name: '风水堪舆讲座音频', type: 'audio', size: 86, downloaded: 86, speed: 0, status: 'completed', progress: 100, source: '风水研习圈', createdAt: '2026-05-08 16:20' },
  { id: 7, name: '奇门遁甲入门 - 第1章', type: 'video', size: 150, downloaded: 0, speed: 0, status: 'failed', progress: 0, source: '奇门遁甲课程', createdAt: '2026-05-10 14:00' },
])

const showCompleted = ref(true)
const showMenu = ref<number | null>(null)
const allPaused = ref(false)
let timer: any = null

const storageInfo = { used: 846, total: 2048, videoSize: 620, ebookSize: 156, audioSize: 70 }

const downloadingTasks = computed(() => tasks.value.filter(t => t.status !== 'completed'))
const completedTasks = computed(() => tasks.value.filter(t => t.status === 'completed'))

onMounted(() => {
  timer = setInterval(() => {
    tasks.value = tasks.value.map(task => {
      if (task.status === 'downloading' && !allPaused.value) {
        const newDl = Math.min(task.downloaded + (task.speed / 1024) * 0.5, task.size)
        const newProgress = Math.round((newDl / task.size) * 100)
        return { ...task, downloaded: newDl, progress: newProgress, status: newProgress >= 100 ? 'completed' as const : 'downloading', speed: newProgress >= 100 ? 0 : task.speed }
      }
      return task
    })
  }, 500)
})

onUnmounted(() => { if (timer) clearInterval(timer) })

function toggleTask(id: number) {
  tasks.value = tasks.value.map(t => {
    if (t.id !== id) return t
    if (t.status === 'downloading') return { ...t, status: 'paused' as const, speed: 0 }
    if (t.status === 'paused' || t.status === 'failed') return { ...t, status: 'downloading' as const, speed: Math.floor(Math.random() * 1024) + 512 }
    return t
  })
}

function cancelTask(id: number) { tasks.value = tasks.value.filter(t => t.id !== id) }
function deleteCompleted(id: number) { tasks.value = tasks.value.filter(t => t.id !== id); showMenu.value = null }

function toggleAllTasks() {
  allPaused.value = !allPaused.value
  tasks.value = tasks.value.map(t => {
    if (t.status === 'downloading') return { ...t, status: 'paused' as const, speed: 0 }
    if (t.status === 'paused') return { ...t, status: 'downloading' as const, speed: Math.floor(Math.random() * 1024) + 512 }
    return t
  })
}

function typeEmoji(t: string) { return { ebook: '📖', video: '🎬', audio: '🎵', document: '📄' }[t] || '📄' }
function typeIconClass(t: string) { return { video: 'ic-blue', ebook: 'ic-amber', audio: 'ic-purple' }[t] || 'ic-purple' }

function statusLabel(s: string) {
  const m: Record<string, string> = { downloading: '下载中', paused: '已暂停', completed: '已完成', failed: '下载失败', waiting: '等待中' }
  return m[s] || s
}

function statusClass(s: string) {
  const m: Record<string, string> = { downloading: 'st-active', paused: 'st-muted', completed: 'st-green', failed: 'st-red', waiting: 'st-amber' }
  return m[s] || 'st-muted'
}

function fmtSpeed(s: number) { return s >= 1024 ? (s / 1024).toFixed(1) + ' MB/s' : s + ' KB/s' }
function fmtSize(mb: number) { return mb >= 1024 ? (mb / 1024).toFixed(1) + ' GB' : mb + ' MB' }

function goPage(url: string) { uni.navigateTo({ url }) }
</script>

<style scoped>
.dl-page { min-height: 100vh; background: #FAF8F5; padding-bottom: 200rpx; }
.header-sticky { position: sticky; top: 0; z-index: 30; background: rgba(250,248,245,0.95); backdrop-filter: blur(12rpx); border-bottom: 1px solid #E8E0D5; }
.header-row { display: flex; align-items: center; padding: 0 24rpx; height: 88rpx; }
.header-back { font-size: 48rpx; color: #333; width: 64rpx; }
.header-title { font-size: 34rpx; font-weight: 700; color: #2C2C2C; }
.header-action { font-size: 26rpx; color: #C41E3A; font-weight: 500; }
.header-spacer { width: 64rpx; }

.dl-content { padding: 16rpx 24rpx; }
.section { margin-bottom: 28rpx; }
.section-title { font-size: 26rpx; font-weight: 600; color: #2C2C2C; display: block; margin-bottom: 14rpx; }
.section-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14rpx; }
.section-arrow { font-size: 28rpx; color: #BBB; transition: transform 0.2s; display: inline-block; }
.section-arrow.open { transform: rotate(90deg); }

.task-list { }
.task-card { background: #fff; border-radius: 16rpx; padding: 20rpx; margin-bottom: 12rpx; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.task-card.done { display: flex; align-items: center; gap: 14rpx; }

.task-main { display: flex; align-items: flex-start; gap: 14rpx; }
.task-icon { width: 72rpx; height: 72rpx; border-radius: 18rpx; display: flex; align-items: center; justify-content: center; font-size: 32rpx; flex-shrink: 0; }
.ic-blue { background: rgba(22,119,255,0.08); }
.ic-amber { background: rgba(201,169,110,0.1); }
.ic-purple { background: rgba(114,46,209,0.08); }

.task-info { flex: 1; min-width: 0; }
.task-name { font-size: 26rpx; font-weight: 500; color: #333; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.task-source { font-size: 22rpx; color: #999; margin-top: 4rpx; display: block; }

.task-progress-wrap { margin-top: 12rpx; }
.task-progress-bar { height: 6rpx; background: #F0EDE5; border-radius: 3rpx; overflow: hidden; }
.task-progress-fill { height: 100%; border-radius: 3rpx; transition: width 0.3s; }
.fill-active { background: #C41E3A; }
.fill-pause { background: #BBB; }
.fill-fail { background: #FF4D4F; }

.task-progress-stats { display: flex; justify-content: space-between; align-items: center; margin-top: 6rpx; }
.tps-size { font-size: 20rpx; color: #999; }
.tps-right { display: flex; align-items: center; gap: 8rpx; }
.tps-speed { font-size: 20rpx; color: #C41E3A; }
.tps-status { font-size: 18rpx; padding: 2rpx 8rpx; border-radius: 6rpx; }
.st-active { color: #C41E3A; background: rgba(196,30,58,0.06); }
.st-muted { color: #999; background: #F5F1EB; }
.st-green { color: #52C41A; background: rgba(82,196,26,0.06); }
.st-red { color: #FF4D4F; background: rgba(255,77,79,0.06); }
.st-amber { color: #E65100; background: rgba(230,81,0,0.06); }

.task-actions { display: flex; gap: 8rpx; flex-shrink: 0; }
.ta-btn { width: 56rpx; height: 56rpx; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24rpx; background: #F5F1EB; color: #666; }
.ta-btn.pause { background: rgba(196,30,58,0.08); color: #C41E3A; }
.ta-btn.del { color: #999; }

.done-actions { display: flex; align-items: center; gap: 8rpx; flex-shrink: 0; position: relative; }
.da-open { padding: 8rpx 20rpx; border-radius: 24rpx; background: #C41E3A; color: #fff; font-size: 22rpx; }
.da-more { width: 48rpx; height: 48rpx; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 28rpx; color: #999; background: #F5F1EB; }
.menu-popup { position: absolute; right: 0; top: 56rpx; background: #fff; border-radius: 12rpx; padding: 8rpx 16rpx; box-shadow: 0 4rpx 16rpx rgba(0,0,0,0.12); z-index: 10; white-space: nowrap; }
.menu-item { font-size: 24rpx; color: #FF4D4F; }
.menu-item.del { color: #FF4D4F; }

.empty-wrap { display: flex; flex-direction: column; align-items: center; padding: 120rpx 48rpx; }
.empty-icon { font-size: 88rpx; opacity: 0.3; margin-bottom: 20rpx; }
.empty-text { font-size: 28rpx; color: #999; margin-bottom: 24rpx; }
.empty-btn { padding: 14rpx 40rpx; border-radius: 40rpx; background: #C41E3A; color: #fff; font-size: 26rpx; }

.storage-bar { position: fixed; bottom: 0; left: 0; right: 0; padding: 20rpx 24rpx 28rpx; background: rgba(255,255,255,0.95); backdrop-filter: blur(12rpx); border-top: 1px solid #E8E0D5; }
.storage-info { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10rpx; }
.si-label { font-size: 24rpx; color: #333; font-weight: 500; }
.si-val { font-size: 24rpx; color: #999; }
.storage-bar-track { height: 8rpx; background: #F0EDE5; border-radius: 4rpx; overflow: hidden; display: flex; }
.sb-seg { height: 100%; }
.sb-video { background: #1677FF; }
.sb-ebook { background: #C9A96E; }
.sb-audio { background: #722ED1; }
.storage-legend { display: flex; justify-content: center; gap: 24rpx; margin-top: 10rpx; }
.sl-item { font-size: 20rpx; color: #999; display: flex; align-items: center; gap: 6rpx; }
.sl-dot { width: 12rpx; height: 12rpx; border-radius: 50%; }
.sl-video { background: #1677FF; }
.sl-ebook { background: #C9A96E; }
.sl-audio { background: #722ED1; }
</style>

// v0-reference/proto-ref-app/downloads/page.tsx
"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { 
  ArrowLeft, Pause, Play, X, Trash2, BookOpen, Video, FileText,
  MoreHorizontal, FolderOpen, HardDrive, ChevronDown, ChevronUp,
  CheckCircle, AlertCircle, Clock
} from "lucide-react"
import { BackButton } from "@/components/common/back-button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { cn } from "@/lib/utils"

// 下载任务类型
type DownloadStatus = "downloading" | "paused" | "completed" | "failed" | "waiting"

interface DownloadTask {
  id: number
  name: string
  type: "ebook" | "video" | "audio" | "document"
  size: number // MB
  downloaded: number // MB
  speed: number // KB/s
  status: DownloadStatus
  progress: number // 0-100
  source: string // 来源（课程名/圈子名）
  createdAt: string
}

// 模拟下载任务数据
const initialTasks: DownloadTask[] = [
  { id: 1, name: "八字命理入门精讲 - 第1章", type: "video", size: 256, downloaded: 168, speed: 1024, status: "downloading", progress: 65, source: "八字命理入门", createdAt: "2026-05-10 14:30" },
  { id: 2, name: "渊海子平（完整版）", type: "ebook", size: 48, downloaded: 24, speed: 0, status: "paused", progress: 50, source: "古籍书库", createdAt: "2026-05-10 14:25" },
  { id: 3, name: "紫微斗数基础课 - 第3章", type: "video", size: 180, downloaded: 36, speed: 512, status: "downloading", progress: 20, source: "紫微斗数基础", createdAt: "2026-05-10 14:20" },
  { id: 4, name: "滴天髓精解", type: "ebook", size: 32, downloaded: 32, speed: 0, status: "completed", progress: 100, source: "古籍书库", createdAt: "2026-05-09 10:15" },
  { id: 5, name: "八字命理入门精讲 - 第2章", type: "video", size: 220, downloaded: 220, speed: 0, status: "completed", progress: 100, source: "八字命理入门", createdAt: "2026-05-09 09:30" },
  { id: 6, name: "风水堪舆讲座音频", type: "audio", size: 86, downloaded: 86, speed: 0, status: "completed", progress: 100, source: "风水研习圈", createdAt: "2026-05-08 16:20" },
  { id: 7, name: "奇门遁甲入门 - 第1章", type: "video", size: 150, downloaded: 0, speed: 0, status: "failed", progress: 0, source: "奇门遁甲课程", createdAt: "2026-05-10 14:00" },
]

// 存储空间信息
const storageInfo = {
  used: 846, // MB
  total: 2048, // MB
  videoSize: 620,
  ebookSize: 156,
  audioSize: 70,
}

export default function DownloadsPage() {
  const [tasks, setTasks] = useState<DownloadTask[]>(initialTasks)
  const [showCompleted, setShowCompleted] = useState(true)
  const [showMenu, setShowMenu] = useState<number | null>(null)
  const [allPaused, setAllPaused] = useState(false)

  // 模拟下载进度更新
  useEffect(() => {
    const interval = setInterval(() => {
      setTasks(prev => prev.map(task => {
        if (task.status === "downloading" && !allPaused) {
          const newDownloaded = Math.min(task.downloaded + (task.speed / 1024) * 0.5, task.size)
          const newProgress = Math.round((newDownloaded / task.size) * 100)
          return {
            ...task,
            downloaded: newDownloaded,
            progress: newProgress,
            status: newProgress >= 100 ? "completed" : "downloading",
            speed: newProgress >= 100 ? 0 : task.speed
          }
        }
        return task
      }))
    }, 500)
    return () => clearInterval(interval)
  }, [allPaused])

  const downloadingTasks = tasks.filter(t => t.status === "downloading" || t.status === "paused" || t.status === "waiting" || t.status === "failed")
  const completedTasks = tasks.filter(t => t.status === "completed")

  const toggleTask = (id: number) => {
    setTasks(prev => prev.map(task => {
      if (task.id === id) {
        if (task.status === "downloading") {
          return { ...task, status: "paused" as DownloadStatus, speed: 0 }
        } else if (task.status === "paused" || task.status === "failed") {
          return { ...task, status: "downloading" as DownloadStatus, speed: Math.floor(Math.random() * 1024) + 512 }
        }
      }
      return task
    }))
  }

  const cancelTask = (id: number) => {
    setTasks(prev => prev.filter(t => t.id !== id))
    setShowMenu(null)
  }

  const deleteCompleted = (id: number) => {
    setTasks(prev => prev.filter(t => t.id !== id))
    setShowMenu(null)
  }

  const toggleAllTasks = () => {
    setAllPaused(!allPaused)
    setTasks(prev => prev.map(task => {
      if (task.status === "downloading" || task.status === "paused") {
        return { 
          ...task, 
          status: allPaused ? "downloading" : "paused" as DownloadStatus,
          speed: allPaused ? Math.floor(Math.random() * 1024) + 512 : 0
        }
      }
      return task
    }))
  }

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "ebook": return <BookOpen className="w-5 h-5" />
      case "video": return <Video className="w-5 h-5" />
      case "audio": return <FileText className="w-5 h-5" />
      default: return <FileText className="w-5 h-5" />
    }
  }

  const getStatusInfo = (status: DownloadStatus) => {
    switch (status) {
      case "downloading": return { label: "下载中", color: "text-primary", bgColor: "bg-primary/10" }
      case "paused": return { label: "已暂停", color: "text-muted-foreground", bgColor: "bg-secondary" }
      case "completed": return { label: "已完成", color: "text-green-500", bgColor: "bg-green-500/10" }
      case "failed": return { label: "下载失败", color: "text-destructive", bgColor: "bg-destructive/10" }
      case "waiting": return { label: "等待中", color: "text-amber-500", bgColor: "bg-amber-500/10" }
    }
  }

  const formatSpeed = (speed: number) => {
    if (speed >= 1024) return `${(speed / 1024).toFixed(1)} MB/s`
    return `${speed} KB/s`
  }

  const formatSize = (mb: number) => {
    if (mb >= 1024) return `${(mb / 1024).toFixed(1)} GB`
    return `${mb} MB`
  }

  return (
    <div className="min-h-screen bg-background pb-24">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-lg border-b border-border">
        <div className="flex items-center justify-between px-4 h-14">
          <BackButton fallbackPath="/profile" />
          <h1 className="font-semibold text-base text-foreground">下载管理</h1>
          {downloadingTasks.length > 0 && (
            <button
              onClick={toggleAllTasks}
              className="text-sm text-primary font-medium"
            >
              {allPaused ? "全部开始" : "全部暂停"}
            </button>
          )}
          {downloadingTasks.length === 0 && <div className="w-16" />}
        </div>
      </header>

      <div className="p-4 space-y-6">
        {/* 下载中列表 */}
        {downloadingTasks.length > 0 && (
          <div>
            <h2 className="text-sm font-medium text-foreground mb-3 flex items-center gap-2">
              <Clock className="w-4 h-4 text-primary" />
              下载中 ({downloadingTasks.length})
            </h2>
            <div className="space-y-3">
              {downloadingTasks.map(task => {
                const statusInfo = getStatusInfo(task.status)
                return (
                  <Card key={task.id} className="p-3">
                    <div className="flex items-start gap-3">
                      {/* 类型图标 */}
                      <div className={cn(
                        "w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0",
                        task.type === "video" ? "bg-blue-500/10 text-blue-500" :
                        task.type === "ebook" ? "bg-amber-500/10 text-amber-500" :
                        "bg-purple-500/10 text-purple-500"
                      )}>
                        {getTypeIcon(task.type)}
                      </div>

                      {/* 内容 */}
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground line-clamp-1">{task.name}</p>
                        <p className="text-xs text-muted-foreground mt-0.5">{task.source}</p>
                        
                        {/* 进度条 */}
                        <div className="mt-2">
                          <div className="h-1.5 bg-secondary rounded-full overflow-hidden">
                            <div 
                              className={cn(
                                "h-full rounded-full transition-all duration-300",
                                task.status === "failed" ? "bg-destructive" :
                                task.status === "paused" ? "bg-muted-foreground" : "bg-primary"
                              )}
                              style={{ width: `${task.progress}%` }}
                            />
                          </div>
                          <div className="flex items-center justify-between mt-1">
                            <span className="text-xs text-muted-foreground">
                              {formatSize(task.downloaded)} / {formatSize(task.size)}
                            </span>
                            <div className="flex items-center gap-2">
                              {task.status === "downloading" && (
                                <span className="text-xs text-primary">{formatSpeed(task.speed)}</span>
                              )}
                              <Badge variant="secondary" className={cn("text-[10px] px-1.5 py-0", statusInfo.bgColor, statusInfo.color)}>
                                {statusInfo.label}
                              </Badge>
                            </div>
                          </div>
                        </div>
                      </div>

                      {/* 操作按钮 */}
                      <div className="flex items-center gap-1 flex-shrink-0">
                        <button
                          onClick={() => toggleTask(task.id)}
                          className={cn(
                            "p-2 rounded-full transition-colors",
                            task.status === "downloading" 
                              ? "bg-primary/10 text-primary hover:bg-primary/20"
                              : "bg-secondary text-foreground hover:bg-secondary/80"
                          )}
                        >
                          {task.status === "downloading" ? (
                            <Pause className="w-4 h-4" />
                          ) : (
                            <Play className="w-4 h-4" />
                          )}
                        </button>
                        <button
                          onClick={() => cancelTask(task.id)}
                          className="p-2 rounded-full bg-secondary text-muted-foreground hover:bg-destructive/10 hover:text-destructive transition-colors"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </Card>
                )
              })}
            </div>
          </div>
        )}

        {/* 已完成列表 */}
        {completedTasks.length > 0 && (
          <div>
            <button
              onClick={() => setShowCompleted(!showCompleted)}
              className="w-full flex items-center justify-between text-sm font-medium text-foreground mb-3"
            >
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                <span>已完成 ({completedTasks.length})</span>
              </div>
              {showCompleted ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
            </button>
            
            {showCompleted && (
              <div className="space-y-2">
                {completedTasks.map(task => (
                  <Card key={task.id} className="p-3">
                    <div className="flex items-center gap-3">
                      {/* 类型图标 */}
                      <div className={cn(
                        "w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0",
                        task.type === "video" ? "bg-blue-500/10 text-blue-500" :
                        task.type === "ebook" ? "bg-amber-500/10 text-amber-500" :
                        "bg-purple-500/10 text-purple-500"
                      )}>
                        {getTypeIcon(task.type)}
                      </div>

                      {/* 内容 */}
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground line-clamp-1">{task.name}</p>
                        <div className="flex items-center gap-2 mt-0.5">
                          <span className="text-xs text-muted-foreground">{formatSize(task.size)}</span>
                          <span className="text-xs text-muted-foreground">|</span>
                          <span className="text-xs text-muted-foreground">{task.createdAt.split(" ")[0]}</span>
                        </div>
                      </div>

                      {/* 操作 */}
                      <div className="flex items-center gap-1 flex-shrink-0">
                        <Link
                          href={task.type === "ebook" ? `/reader/${task.id}` : `/learn/${task.id}`}
                          className="px-3 py-1.5 bg-primary text-primary-foreground text-xs font-medium rounded-full hover:bg-primary/90 transition-colors"
                        >
                          {task.type === "ebook" ? "阅读" : "播放"}
                        </Link>
                        <div className="relative">
                          <button
                            onClick={() => setShowMenu(showMenu === task.id ? null : task.id)}
                            className="p-2 rounded-full hover:bg-secondary transition-colors"
                          >
                            <MoreHorizontal className="w-4 h-4 text-muted-foreground" />
                          </button>
                          {showMenu === task.id && (
                            <>
                              <div className="fixed inset-0 z-40" onClick={() => setShowMenu(null)} />
                              <div className="absolute right-0 top-full mt-1 w-32 bg-card rounded-lg shadow-lg border border-border z-50 py-1">
                                <button
                                  onClick={() => deleteCompleted(task.id)}
                                  className="flex items-center gap-2 w-full px-3 py-2 text-sm text-destructive hover:bg-secondary transition-colors"
                                >
                                  <Trash2 className="w-4 h-4" />
                                  删除文件
                                </button>
                              </div>
                            </>
                          )}
                        </div>
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
            )}
          </div>
        )}

        {/* 空状态 */}
        {tasks.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="w-20 h-20 rounded-full bg-secondary flex items-center justify-center mb-4">
              <FolderOpen className="w-8 h-8 text-muted-foreground" />
            </div>
            <p className="text-muted-foreground text-sm">暂无下载任务</p>
            <Link
              href="/discover"
              className="mt-4 px-4 py-2 bg-primary text-primary-foreground text-sm font-medium rounded-full"
            >
              去发现内容
            </Link>
          </div>
        )}
      </div>

      {/* 底部存储空间 */}
      <div className="fixed bottom-0 left-0 right-0 bg-card/95 backdrop-blur-lg border-t border-border p-4 safe-area-pb">
        <div className="max-w-lg mx-auto">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <HardDrive className="w-4 h-4 text-muted-foreground" />
              <span className="text-sm text-foreground">存储空间</span>
            </div>
            <span className="text-sm text-muted-foreground">
              {formatSize(storageInfo.used)} / {formatSize(storageInfo.total)}
            </span>
          </div>
          <div className="h-2 bg-secondary rounded-full overflow-hidden flex">
            <div 
              className="h-full bg-blue-500" 
              style={{ width: `${(storageInfo.videoSize / storageInfo.total) * 100}%` }} 
            />
            <div 
              className="h-full bg-amber-500" 
              style={{ width: `${(storageInfo.ebookSize / storageInfo.total) * 100}%` }} 
            />
            <div 
              className="h-full bg-purple-500" 
              style={{ width: `${(storageInfo.audioSize / storageInfo.total) * 100}%` }} 
            />
          </div>
          <div className="flex items-center gap-4 mt-2">
            <div className="flex items-center gap-1.5">
              <div className="w-2 h-2 rounded-full bg-blue-500" />
              <span className="text-xs text-muted-foreground">视频 {formatSize(storageInfo.videoSize)}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-2 h-2 rounded-full bg-amber-500" />
              <span className="text-xs text-muted-foreground">电子书 {formatSize(storageInfo.ebookSize)}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-2 h-2 rounded-full bg-purple-500" />
              <span className="text-xs text-muted-foreground">音频 {formatSize(storageInfo.audioSize)}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
