// proto-ref-app/profile/page.tsx
"use client"

import { useState, useEffect } from "react"
import { 
  Settings, ChevronRight, BookOpen, Users, FileText, 
  Wallet, Ticket, Heart, Download, Clock, 
  HelpCircle, Crown, GraduationCap,
  Star, QrCode, Shield, 
  Award, Package,
  RefreshCw, Truck, Edit3, Coins, Play,
  Bell, CalendarCheck, Compass, Video, Radio, 
  MessageSquare, StickyNote, History, Gift, ClipboardList
} from "lucide-react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { BottomNav } from "@/components/bottom-nav"
import { cn } from "@/lib/utils"
import Link from "next/link"

// 用户角色类型
type UserRole = "user" | "circle_owner" | "teacher" | "station_owner" | "streamer" | "creator"

// 用户数据
const userData = {
  name: "张三丰",
  avatar: "",
  bio: "易学爱好者 | 八字研习中",
  isVip: true,
  vipLevel: "黄金会员",
  vipExpiry: "2025-12-31",
  vipDaysLeft: 234,
  isVerified: true,
  roles: [
    { type: "circle_owner" as UserRole, name: "张氏命理研习社", id: 1 },
    { type: "teacher" as UserRole, name: "八字入门精讲", id: 1 },
    { type: "streamer" as UserRole, name: "直播间", id: 1 },
  ],
  // 消息通知
  messages: {
    system: 2,
    interaction: 5,
    transaction: 1,
  },
  // 签到数据
  checkIn: {
    todayChecked: false,
    continuousDays: 7,
    totalPoints: 350,
  },
  stats: {
    following: 128,
    followers: 1024,
    likes: 3680,
  },
  coins: 520,
  coupons: 3,
  points: 1280,
  orders: {
    pending: 2,
    shipped: 1,
    received: 3,
    refund: 0,
  },
  // 继续学习的课程
  continueLearning: {
    id: 1,
    title: "八字入门实战课",
    progress: 45,
    lastLesson: "第三章：天干地支详解",
  },
}

// 获取问候语
function getGreeting() {
  const hour = new Date().getHours()
  if (hour < 6) return "夜深了"
  if (hour < 12) return "早上好"
  if (hour < 14) return "中午好"
  if (hour < 18) return "下午好"
  return "晚上好"
}

// 角色配置
const roleConfig: Record<UserRole, { label: string; icon: typeof Users; color: string; bgColor: string }> = {
  user: { label: "普通用户", icon: Users, color: "text-muted-foreground", bgColor: "bg-muted/20" },
  circle_owner: { label: "圈主后台", icon: Crown, color: "text-[#C9A96E]", bgColor: "bg-[#C9A96E]/10" },
  teacher: { label: "讲师后台", icon: GraduationCap, color: "text-[#4A90D9]", bgColor: "bg-[#4A90D9]/10" },
  station_owner: { label: "站长后台", icon: Award, color: "text-[#52C41A]", bgColor: "bg-[#52C41A]/10" },
  streamer: { label: "主播中心", icon: Radio, color: "text-[#C41E3A]", bgColor: "bg-[#C41E3A]/10" },
  creator: { label: "创作中心", icon: Video, color: "text-[#722ED1]", bgColor: "bg-[#722ED1]/10" },
}

// 常用功能入口 - 根据业务重新排列
const quickFunctions = [
  { icon: Compass, label: "排盘记录", href: "/paipan", color: "text-[#C41E3A]" },
  { icon: BookOpen, label: "我的课程", href: "/learning", color: "text-[#4A90D9]" },
  { icon: Users, label: "我的圈子", href: "/my-circles", color: "text-[#722ED1]" },
  { icon: StickyNote, label: "我的笔记", href: "/ebook/notes", color: "text-[#C9A96E]" },
  { icon: Heart, label: "我的收藏", href: "/favorites", color: "text-[#C41E3A]" },
  { icon: FileText, label: "我的电子书", href: "/downloads", color: "text-[#52C41A]" },
  { icon: ClipboardList, label: "我的申请", href: "/mine/applications", color: "text-[#FA8C16]" },
  { icon: History, label: "浏览历史", href: "/history", color: "text-[#64748B]" },
  { icon: HelpCircle, label: "帮助中心", href: "/help", color: "text-[#999999]" },
]

// 猜你喜欢推荐
const recommendations = [
  { id: 1, type: "course", title: "紫微斗数入门精讲", price: 199, originalPrice: 399, tag: "热门" },
  { id: 2, type: "product", title: "专业罗盘套装", price: 298, originalPrice: 598, tag: "特惠" },
  { id: 3, type: "course", title: "六爻预测实战班", price: 299, originalPrice: 499, tag: "新课" },
  { id: 4, type: "product", title: "渊海子平精装版", price: 68, originalPrice: 128, tag: "" },
]

// 全部可开通角色（用户未拥有的显示"申请开通"）
const allRoleTypes: { type: UserRole; applyHref: string }[] = [
  { type: "circle_owner", applyHref: "/circles/create" },
  { type: "teacher", applyHref: "/institute/apply" },
  { type: "station_owner", applyHref: "/join/station" },
  { type: "streamer", applyHref: "/creator/live/console" },
]

export default function ProfilePage() {
  const [greeting, setGreeting] = useState("")
  // 身份切换确认弹窗：保存待切换的角色
  const [pendingRole, setPendingRole] = useState<{ type: UserRole; name: string; href: string } | null>(null)

  useEffect(() => {
    setGreeting(getGreeting())
  }, [])

  // 计算用户尚未开通的角色（用于"申请开通"引导）
  const ownedTypes = new Set(userData.roles.map((r) => r.type))
  const availableToApply = allRoleTypes.filter((r) => !ownedTypes.has(r.type))

  // 订单状态配置
  const orderStatus = [
    { key: "pending", label: "待付款", icon: Wallet, count: userData.orders.pending, href: "/orders?status=pending" },
    { key: "shipped", label: "待发货", icon: Package, count: userData.orders.shipped, href: "/orders?status=shipped" },
    { key: "received", label: "待收货", icon: Truck, count: userData.orders.received, href: "/orders?status=received" },
    { key: "refund", label: "售后", icon: RefreshCw, count: userData.orders.refund, href: "/orders?status=refund" },
  ]

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-20">
      {/* ===== 第一层：个人信息区 ===== */}
      <div className="relative">
        {/* 背景渐变 - 宣纸色系 */}
        <div className="absolute inset-0 h-48 bg-gradient-to-b from-[#F5F1EB] via-[#FAF8F5] to-[#FAF8F5]" />
        
        {/* 顶部操作栏 */}
        <div className="relative flex items-center justify-between px-4 pt-12 pb-2">
          <button className="p-2 rounded-full bg-white/60 backdrop-blur-sm">
            <QrCode className="w-5 h-5 text-foreground" />
          </button>
          <div className="flex items-center gap-2">
            {/* 消息通知入口 */}
            <Link href="/im/conversations" className="relative p-2 rounded-full bg-white/60 backdrop-blur-sm">
              <Bell className="w-5 h-5 text-foreground" />
              {(userData.messages.system + userData.messages.interaction + userData.messages.transaction) > 0 && (
                <span className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-[#C41E3A] text-white text-[10px] font-bold rounded-full flex items-center justify-center">
                  {userData.messages.system + userData.messages.interaction + userData.messages.transaction}
                </span>
              )}
            </Link>
            <Link href="/settings" className="p-2 rounded-full bg-white/60 backdrop-blur-sm">
              <Settings className="w-5 h-5 text-foreground" />
            </Link>
          </div>
        </div>

        {/* 用户信息 */}
        <div className="relative px-4 pb-4">
          <div className="flex items-start gap-4">
            {/* 大头像 */}
            <Link href="/profile/edit">
              <Avatar className="w-20 h-20 ring-4 ring-white shadow-lg">
                <AvatarImage src={userData.avatar} alt={userData.name} />
                <AvatarFallback className="bg-[#C41E3A] text-white text-2xl font-serif font-bold">
                  {userData.name[0]}
                </AvatarFallback>
              </Avatar>
            </Link>
            
            <div className="flex-1 pt-1">
              {/* 问候语 */}
              <p className="text-xs text-muted-foreground mb-1">{greeting}，{userData.name}</p>
              
              {/* 昵称 + 认证标识 */}
              <div className="flex items-center gap-2">
                <h1 className="font-serif text-xl font-bold text-foreground">{userData.name}</h1>
                {userData.isVerified && <Shield className="w-4 h-4 text-[#4A90D9]" />}
                {userData.isVip && (
                  <Badge className="bg-gradient-to-r from-[#C9A96E] to-[#D4B87D] text-white border-0 text-[10px] px-1.5">
                    <Crown className="w-3 h-3 mr-0.5" />
                    {userData.vipLevel}
                  </Badge>
                )}
              </div>
              
              {/* 数据行 */}
              <div className="flex items-center gap-4 mt-2">
                <Link href="/follows?tab=following" className="text-center">
                  <span className="text-base font-bold text-foreground">{userData.stats.following}</span>
                  <span className="text-xs text-muted-foreground ml-1">关注</span>
                </Link>
                <div className="w-px h-3 bg-border" />
                <Link href="/follows?tab=followers" className="text-center">
                  <span className="text-base font-bold text-foreground">{userData.stats.followers}</span>
                  <span className="text-xs text-muted-foreground ml-1">粉丝</span>
                </Link>
                <div className="w-px h-3 bg-border" />
                <Link href="/likes" className="text-center">
                  <span className="text-base font-bold text-foreground">{userData.stats.likes}</span>
                  <span className="text-xs text-muted-foreground ml-1">获赞</span>
                </Link>
              </div>
              
              {/* 编辑资料按钮 */}
              <Link href="/profile/edit">
                <Button variant="outline" size="sm" className="mt-3 h-7 text-xs px-3 rounded-full border-border bg-white">
                  <Edit3 className="w-3 h-3 mr-1" />
                  编辑资料
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* ===== 第二层：资产核心区 ===== */}
      <div className="px-4 mt-2">
        <Card className="overflow-hidden bg-gradient-to-r from-[#FAF8F5] to-[#F8F4EC] border border-[#C9A96E]/20 card-shadow">
          <div className="p-4">
            <div className="grid grid-cols-3 divide-x divide-[#C9A96E]/20">
              {/* 国学币 - 核心资产，金色大字突出 */}
              <Link href="/wallet" className="flex flex-col items-center py-1">
                <div className="flex items-center gap-1">
                  <Coins className="w-5 h-5 text-[#C9A96E]" />
                  <span className="text-3xl font-bold text-[#C9A96E] leading-none">{userData.coins}</span>
                </div>
                <span className="text-xs text-[#C9A96E]/90 font-medium mt-1.5">国学币</span>
              </Link>
              
              {/* 优惠券 */}
              <Link href="/coupons" className="flex flex-col items-center py-1">
                <div className="flex items-center gap-1">
                  <Ticket className="w-4 h-4 text-muted-foreground" />
                  <span className="text-xl font-bold text-foreground leading-none">{userData.coupons}</span>
                </div>
                <span className="text-xs text-muted-foreground mt-1.5">优惠券</span>
              </Link>
              
              {/* 积分 */}
              <Link href="/points" className="flex flex-col items-center py-1">
                <div className="flex items-center gap-1">
                  <Star className="w-4 h-4 text-muted-foreground" />
                  <span className="text-xl font-bold text-foreground leading-none">{userData.points}</span>
                </div>
                <span className="text-xs text-muted-foreground mt-1.5">积分</span>
              </Link>
            </div>
          </div>
        </Card>
      </div>

      {/* ===== 第三层：订单与售后区 ===== */}
      <div className="px-4 mt-4">
        <Card className="bg-card border-0 card-shadow overflow-hidden">
          {/* 标题行 */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-border">
            <h3 className="font-medium text-foreground">我的订单</h3>
            <Link href="/orders" className="flex items-center text-xs text-muted-foreground">
              查看全部订单 <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
          
          {/* 订单状态4宫格 */}
          <div className="grid grid-cols-4 py-4">
            {orderStatus.map((item) => (
              <Link key={item.key} href={item.href} className="flex flex-col items-center gap-1.5 relative">
                <div className="w-10 h-10 rounded-full bg-secondary/50 flex items-center justify-center">
                  <item.icon className="w-5 h-5 text-muted-foreground" />
                </div>
                <span className="text-xs text-foreground">{item.label}</span>
                {item.count > 0 && (
                  <span className="absolute top-0 right-1/4 w-4 h-4 bg-[#C41E3A] text-white text-[10px] font-bold rounded-full flex items-center justify-center">
                    {item.count}
                  </span>
                )}
              </Link>
            ))}
          </div>
        </Card>
      </div>

      {/* ===== 第四层：功能入口区 ===== */}
      <div className="px-4 mt-4">
        <Card className="bg-card border-0 card-shadow overflow-hidden">
          <div className="px-4 py-3 border-b border-border">
            <h3 className="font-medium text-foreground">常用功能</h3>
          </div>
          <div className="grid grid-cols-4 gap-y-4 py-4">
            {quickFunctions.map((item) => (
              <Link key={item.label} href={item.href} className="flex flex-col items-center gap-1.5">
                <div className="w-10 h-10 rounded-xl bg-secondary/50 flex items-center justify-center">
                  <item.icon className={cn("w-5 h-5", item.color)} />
                </div>
                <span className="text-xs text-foreground">{item.label}</span>
              </Link>
            ))}
          </div>
        </Card>
      </div>

      {/* ===== 第五层：身份切换区（仅多身份用户展示）===== */}
      {userData.roles.length > 0 && (
        <div className="px-4 mt-4">
          <Card className="bg-card border-0 card-shadow overflow-hidden">
            <div className="px-4 py-3 border-b border-border flex items-center justify-between">
              <h3 className="font-medium text-foreground">身份切换</h3>
              <span className="text-[10px] text-muted-foreground">点击进入对应管理后台</span>
            </div>
            <div className="p-3 grid grid-cols-2 gap-2">
              {/* 已开通身份 - 点击弹确认 */}
              {userData.roles.map((role) => {
                const config = roleConfig[role.type]
                let href = ""
                switch (role.type) {
                  case "circle_owner": href = `/circle/${role.id}/settings`; break
                  case "teacher":      href = `/teacher/dashboard`; break
                  case "streamer":     href = `/creator/live/console`; break
                  case "creator":      href = `/videos/creator`; break
                  case "station_owner":href = `/mine/role-panels/station-master-panel`; break
                  default:             href = "/profile"
                }
                return (
                  <button
                    key={`${role.type}-${role.id}`}
                    onClick={() => setPendingRole({ type: role.type, name: role.name, href })}
                    className="flex items-center gap-3 p-3 rounded-xl border border-border hover:bg-secondary/30 transition-colors text-left"
                  >
                    <div className={cn("w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0", config.bgColor)}>
                      <config.icon className={cn("w-5 h-5", config.color)} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground truncate">{config.label}</p>
                      <p className="text-[10px] text-muted-foreground truncate">{role.name}</p>
                    </div>
                    <ChevronRight className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                  </button>
                )
              })}
            </div>

            {/* 未开通身份 - 申请开通引导 */}
            {availableToApply.length > 0 && (
              <div className="px-3 pb-3">
                <p className="text-[10px] text-muted-foreground mb-2 px-1">开通更多身份</p>
                <div className="flex gap-2 overflow-x-auto scrollbar-hide">
                  {availableToApply.map((r) => {
                    const config = roleConfig[r.type]
                    return (
                      <Link
                        key={r.type}
                        href={r.applyHref}
                        className="flex-shrink-0 flex items-center gap-2 px-3 py-2 rounded-full border border-dashed border-border hover:border-[#C41E3A]/40 hover:bg-[#C41E3A]/5 transition-colors"
                      >
                        <config.icon className={cn("w-4 h-4", config.color)} />
                        <span className="text-xs text-muted-foreground whitespace-nowrap">申请{config.label.replace("后台", "").replace("中心", "")}</span>
                      </Link>
                    )
                  })}
                </div>
              </div>
            )}
          </Card>
        </div>
      )}

      {/* ===== 身份切换确认弹窗 ===== */}
      {pendingRole && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-8"
          onClick={() => setPendingRole(null)}
        >
          <div
            className="w-full max-w-xs bg-card rounded-2xl overflow-hidden card-shadow"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-5 text-center">
              <div className={cn("w-12 h-12 rounded-xl mx-auto flex items-center justify-center mb-3", roleConfig[pendingRole.type].bgColor)}>
                {(() => {
                  const Icon = roleConfig[pendingRole.type].icon
                  return <Icon className={cn("w-6 h-6", roleConfig[pendingRole.type].color)} />
                })()}
              </div>
              <h4 className="font-medium text-foreground">切换到「{roleConfig[pendingRole.type].label}」</h4>
              <p className="text-xs text-muted-foreground mt-1.5">{pendingRole.name}</p>
              <p className="text-[11px] text-muted-foreground mt-2">将进入对应管理后台，确认切换？</p>
            </div>
            <div className="grid grid-cols-2 border-t border-border">
              <button
                onClick={() => setPendingRole(null)}
                className="py-3 text-sm text-muted-foreground hover:bg-secondary/30 transition-colors"
              >
                取消
              </button>
              <Link
                href={pendingRole.href}
                className="py-3 text-sm font-medium text-white bg-[#C41E3A] hover:bg-[#A01829] transition-colors text-center border-l border-border"
              >
                确认切换
              </Link>
            </div>
          </div>
        </div>
      )}

      {/* ===== 签到入口 ===== */}
      <div className="px-4 mt-4">
        <Link href="/check-in">
          <Card className="overflow-hidden bg-gradient-to-r from-[#C41E3A]/5 to-[#C9A96E]/5 border border-[#C41E3A]/20 card-shadow">
            <div className="p-3 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#C41E3A] to-[#C9A96E] flex items-center justify-center">
                  <CalendarCheck className="w-5 h-5 text-white" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-foreground">每日签到</span>
                    {userData.checkIn.todayChecked ? (
                      <Badge className="bg-[#52C41A]/10 text-[#52C41A] border-0 text-[10px] px-1.5">已签到</Badge>
                    ) : (
                      <Badge className="bg-[#C41E3A] text-white border-0 text-[10px] px-1.5 animate-pulse">待签到</Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    已连续签到 <span className="text-[#C41E3A] font-medium">{userData.checkIn.continuousDays}</span> 天，
                    累计 <span className="text-[#C9A96E] font-medium">{userData.checkIn.totalPoints}</span> 积分
                  </p>
                </div>
              </div>
              <ChevronRight className="w-5 h-5 text-muted-foreground" />
            </div>
          </Card>
        </Link>
      </div>

      {/* ===== 继续学习卡片（有未完成课程时显示） ===== */}
      {userData.continueLearning && (
        <div className="px-4 mt-4">
          <Link href={`/learn/${userData.continueLearning.id}`}>
            <Card className="overflow-hidden bg-card border-0 card-shadow card-shadow-hover">
              <div className="p-3 flex items-center gap-3">
                {/* 课程封面 */}
                <div className="w-16 h-12 rounded-lg bg-gradient-to-br from-[#C41E3A]/10 to-[#C9A96E]/10 flex items-center justify-center flex-shrink-0">
                  <Play className="w-6 h-6 text-[#C41E3A]" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-xs text-muted-foreground">继续学习</p>
                  <h4 className="text-sm font-medium text-foreground truncate">{userData.continueLearning.title}</h4>
                  <p className="text-[10px] text-muted-foreground truncate">{userData.continueLearning.lastLesson}</p>
                </div>
                {/* 进度 */}
                <div className="flex flex-col items-end">
                  <span className="text-sm font-bold text-[#C41E3A]">{userData.continueLearning.progress}%</span>
                  <div className="w-12 h-1 bg-secondary rounded-full mt-1 overflow-hidden">
                    <div 
                      className="h-full bg-[#C41E3A] rounded-full"
                      style={{ width: `${userData.continueLearning.progress}%` }}
                    />
                  </div>
                </div>
              </div>
            </Card>
          </Link>
        </div>
      )}

      {/* ===== 猜你喜欢 ===== */}
      <div className="px-4 mt-4 mb-6">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-medium text-foreground">猜��喜欢</h3>
          <Link href="/discover" className="text-xs text-muted-foreground flex items-center">
            更多 <ChevronRight className="w-4 h-4" />
          </Link>
        </div>
        <div className="flex gap-3 overflow-x-auto scrollbar-hide pb-1">
          {recommendations.map((item) => (
            <Link 
              key={item.id} 
              href={item.type === "course" ? `/course/${item.id}` : `/mall/product/${item.id}`}
              className="flex-shrink-0 w-32"
            >
              <div className="aspect-[3/4] rounded-lg bg-gradient-to-br from-[#C41E3A]/5 to-[#C9A96E]/5 relative flex items-center justify-center card-shadow">
                {item.type === "course" ? (
                  <BookOpen className="w-8 h-8 text-[#C41E3A]/30" />
                ) : (
                  <Package className="w-8 h-8 text-[#C9A96E]/30" />
                )}
                {item.tag && (
                  <Badge className="absolute top-1.5 left-1.5 text-[10px] px-1.5 py-0 bg-[#C41E3A] text-white border-0">
                    {item.tag}
                  </Badge>
                )}
              </div>
              <p className="text-xs font-medium mt-2 line-clamp-2 leading-relaxed text-foreground">{item.title}</p>
              <div className="flex items-baseline gap-1 mt-1">
                <span className="text-sm font-bold text-[#C41E3A]">¥{item.price}</span>
                <span className="text-[10px] text-muted-foreground line-through">¥{item.originalPrice}</span>
              </div>
            </Link>
          ))}
        </div>
      </div>

      {/* 会员到期提醒 */}
      {userData.isVip && userData.vipDaysLeft <= 30 && (
        <div className="fixed bottom-20 left-4 right-4 max-w-lg mx-auto">
          <Card className="bg-gradient-to-r from-[#C9A96E] to-[#D4B87D] text-white p-3 flex items-center justify-between card-shadow">
            <div className="flex items-center gap-2">
              <Crown className="w-5 h-5" />
              <span className="text-sm">会员还剩 {userData.vipDaysLeft} 天到期</span>
            </div>
            <Link href="/vip" className="px-3 py-1 bg-white text-[#C9A96E] rounded-full text-xs font-medium">
              立即续费
            </Link>
          </Card>
        </div>
      )}

      <BottomNav />
    </div>
  )
}

// apps/mobile/.backup_vue3_converted/pages/profile/index.vue
<template>
  <view class="min-h-screen bg-background pb-24">
    <!-- ===== 第一层：个人信息区 ===== -->
    <view class="relative">
      <!-- 背景渐变 - 宣纸色系 -->
      <view class="absolute top-0 left-0 right-0 h-48 bg-gradient-to-b from-[#F5F1EB] via-[#FAF8F5] to-[#FAF8F5]" />

      <!-- 顶部操作栏 -->
      <view class="relative flex items-center justify-between px-4 pt-12 pb-2">
        <view class="p-2 rounded-full bg-white/60" style="backdrop-filter: blur(8px);" @click="scanQR">
          <text class="text-foreground text-lg"></text>
        </view>
        <view class="flex items-center gap-2">
          <!-- 消息通知入口 -->
          <view class="relative p-2 rounded-full bg-white/60" style="backdrop-filter: blur(8px);" @click="navigateTo('/pages/messages/index')">
            <text class="text-foreground text-lg"></text>
            <view v-if="totalMessages > 0" class="absolute -top-0.5 -right-0.5 w-4 h-4 bg-primary text-white text-[10px] font-bold rounded-full flex items-center justify-center">
              <text>{{ totalMessages }}</text>
            </view>
          </view>
          <view class="p-2 rounded-full bg-white/60" style="backdrop-filter: blur(8px);" @click="navigateTo('/pages/mine/settings/index')">
            <text class="text-foreground text-lg">⚙</text>
          </view>
        </view>
      </view>

      <!-- 用户信息 -->
      <view class="relative px-4 pb-4">
        <view class="flex items-start gap-4">
          <!-- 大头像 -->
          <view @click="navigateTo('/pages/mine/edit-profile/index')">
            <view class="w-20 h-20 rounded-full ring-4 ring-white shadow-lg bg-primary flex items-center justify-center">
              <text class="text-white text-2xl font-serif font-bold">{{ userData.name[0] }}</text>
            </view>
          </view>

          <view class="flex-1 pt-1">
            <!-- 问候语 -->
            <text class="text-xs text-muted-foreground mb-1 block">{{ greeting }}，{{ userData.name }}</text>

            <!-- 昵称 + 认证标识 -->
            <view class="flex items-center gap-2">
              <text class="font-serif text-xl font-bold text-foreground">{{ userData.name }}</text>
              <text v-if="userData.isVerified" class="text-[#4A90D9] text-base">🛡</text>
              <view v-if="userData.isVip" class="bg-gradient-to-r from-accent to-[#D4B87D] text-white text-[10px] px-1.5 py-0.5 rounded-full flex items-center">
                <text class="text-xs mr-0.5">👑</text>
                <text>{{ userData.vipLevel }}</text>
              </view>
            </view>

            <!-- 数据行 -->
            <view class="flex items-center gap-4 mt-2">
              <view @click="navigateTo('/pages/follows/index?tab=following')" class="text-center">
                <text class="text-base font-bold text-foreground">{{ userData.stats.following }}</text>
                <text class="text-xs text-muted-foreground ml-1">关注</text>
              </view>
              <view class="w-px h-3 bg-[#E8E0D5]" />
              <view @click="navigateTo('/pages/follows/index?tab=followers')" class="text-center">
                <text class="text-base font-bold text-foreground">{{ userData.stats.followers }}</text>
                <text class="text-xs text-muted-foreground ml-1">粉丝</text>
              </view>
              <view class="w-px h-3 bg-[#E8E0D5]" />
              <view @click="navigateTo('/pages/likes/index')" class="text-center">
                <text class="text-base font-bold text-foreground">{{ userData.stats.likes }}</text>
                <text class="text-xs text-muted-foreground ml-1">获赞</text>
              </view>
            </view>

            <!-- 编辑资料按钮 -->
            <view class="mt-3 inline-block" @click="navigateTo('/pages/mine/edit-profile/index')">
              <view class="h-7 text-xs px-3 rounded-full border border-border bg-white flex items-center gap-1">
                <text class="text-xs">✏</text>
                <text class="text-foreground text-xs">编辑资料</text>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- ===== 第二层：资产核心区 ===== -->
    <view class="px-4 mt-2">
      <view class="overflow-hidden bg-gradient-to-r from-[#FAF8F5] to-[#F8F4EC] border border-accent/20 rounded-xl shadow-sm">
        <view class="p-4">
          <view class="grid grid-cols-3" style="display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));">
            <view class="flex flex-col items-center py-1 border-r border-accent/20" @click="navigateTo('/pages/mine/wallet/index')">
              <view class="flex items-center gap-1">
                <text class="text-accent text-lg"></text>
                <text class="text-2xl font-bold text-accent">{{ userData.coins }}</text>
              </view>
              <text class="text-xs text-muted-foreground mt-1">国学币</text>
            </view>
            <view class="flex flex-col items-center py-1 border-r border-accent/20" @click="navigateTo('/pages/coupons/index')">
              <view class="flex items-center gap-1">
                <text class="text-accent text-lg">🎫</text>
                <text class="text-2xl font-bold text-accent">{{ userData.coupons }}</text>
              </view>
              <text class="text-xs text-muted-foreground mt-1">优惠券</text>
            </view>
            <view class="flex flex-col items-center py-1" @click="navigateTo('/pages/mine/points/index')">
              <view class="flex items-center gap-1">
                <text class="text-accent text-lg"></text>
                <text class="text-2xl font-bold text-accent">{{ userData.points }}</text>
              </view>
              <text class="text-xs text-muted-foreground mt-1">积分</text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- ===== 第三层：订单与售后区 ===== -->
    <view class="px-4 mt-4">
      <view class="bg-white rounded-xl shadow-sm overflow-hidden">
        <!-- 标题行 -->
        <view class="flex items-center justify-between px-4 py-3 border-b border-border">
          <text class="font-medium text-foreground">我的订单</text>
          <view class="flex items-center text-xs text-muted-foreground" @click="navigateTo('/pages/orders/index')">
            <text>查看全部订单</text>
            <text class="ml-0.5 text-sm">›</text>
          </view>
        </view>

        <!-- 订单状态4宫格 -->
        <view class="grid grid-cols-4 py-4" style="display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));">
          <view v-for="item in orderStatus" :key="item.key" class="flex flex-col items-center gap-1.5 relative" @click="navigateTo(item.href)">
            <view class="w-10 h-10 rounded-full bg-secondary/50 flex items-center justify-center">
              <text class="text-muted-foreground text-base">{{ item.icon }}</text>
            </view>
            <text class="text-xs text-foreground">{{ item.label }}</text>
            <view v-if="item.count > 0" class="absolute top-0 w-4 h-4 bg-primary text-white text-[10px] font-bold rounded-full flex items-center justify-center" style="right: calc(25% + 8px);">
              <text>{{ item.count }}</text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- ===== 第四层：功能入口区 ===== -->
    <view class="px-4 mt-4">
      <view class="bg-white rounded-xl shadow-sm overflow-hidden">
        <view class="px-4 py-3 border-b border-border">
          <text class="font-medium text-foreground">常用功能</text>
        </view>
        <view class="grid grid-cols-4 gap-y-4 py-4" style="display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));">
          <view v-for="item in quickFunctions" :key="item.label" class="flex flex-col items-center gap-1.5" @click="navigateTo(item.href)">
            <view class="w-10 h-10 rounded-xl bg-secondary/50 flex items-center justify-center">
              <text :class="['text-base', item.color]">{{ item.icon }}</text>
            </view>
            <text class="text-xs text-foreground">{{ item.label }}</text>
          </view>
        </view>
      </view>
    </view>

    <!-- ===== 第五层：身份切换区 ===== -->
    <view v-if="userData.roles.length > 0" class="px-4 mt-4">
      <view class="bg-white rounded-xl shadow-sm overflow-hidden">
        <view class="px-4 py-3 border-b border-border">
          <text class="font-medium text-foreground">身份切换</text>
        </view>
        <view class="p-3 grid grid-cols-2 gap-2" style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));">
          <view v-for="role in userData.roles" :key="role.type + '-' + role.id" class="flex items-center gap-3 p-3 rounded-xl border border-border active:bg-secondary transition-colors" @click="navigateToRole(role)">
            <view :class="['w-10 h-10 rounded-xl flex items-center justify-center', roleConfig[role.type].bgColor]">
              <text :class="['text-base', roleConfig[role.type].color]">{{ roleConfig[role.type].icon }}</text>
            </view>
            <view class="flex-1 min-w-0">
              <text class="text-sm font-medium text-foreground block truncate">{{ roleConfig[role.type].label }}</text>
              <text class="text-[10px] text-muted-foreground block truncate">{{ role.name }}</text>
            </view>
            <text class="text-muted-foreground text-sm flex-shrink-0">›</text>
          </view>
        </view>
      </view>
    </view>

    <!-- ===== 签到入口 ===== -->
    <view class="px-4 mt-4">
      <view class="overflow-hidden bg-gradient-to-r from-primary/5 to-accent/5 border border-primary/20 rounded-xl shadow-sm" @click="navigateTo('/pages/check-in/index')">
        <view class="p-3 flex items-center justify-between">
          <view class="flex items-center gap-3">
            <view class="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center">
              <text class="text-white text-base"></text>
            </view>
            <view>
              <view class="flex items-center gap-2">
                <text class="text-sm font-medium text-foreground">每日签到</text>
                <view v-if="userData.checkIn.todayChecked" class="bg-success/10 text-success text-[10px] px-1.5 py-0.5 rounded-full border-0">
                  <text>已签到</text>
                </view>
                <view v-else class="bg-primary text-white text-[10px] px-1.5 py-0.5 rounded-full border-0 animate-pulse">
                  <text>待签到</text>
                </view>
              </view>
              <text class="text-xs text-muted-foreground block mt-0.5">
                已连续签到 <text class="text-primary font-medium">{{ userData.checkIn.continuousDays }}</text> 天，
                累计 <text class="text-accent font-medium">{{ userData.checkIn.totalPoints }}</text> 积分
              </text>
            </view>
          </view>
          <text class="text-muted-foreground text-lg">›</text>
        </view>
      </view>
    </view>

    <!-- ===== 继续学习卡片（有未完成课程时显示） ===== -->
    <view v-if="userData.continueLearning" class="px-4 mt-4">
      <view class="overflow-hidden bg-white rounded-xl shadow-sm" @click="navigateTo('/pages/learn/' + userData.continueLearning.id + '/index')">
        <view class="p-3 flex items-center gap-3">
          <!-- 课程封面 -->
          <view class="w-16 h-12 rounded-lg bg-gradient-to-br from-primary/10 to-accent/10 flex items-center justify-center flex-shrink-0">
            <text class="text-primary text-xl">▶</text>
          </view>
          <view class="flex-1 min-w-0">
            <text class="text-xs text-muted-foreground block">继续学习</text>
            <text class="text-sm font-medium text-foreground block truncate">{{ userData.continueLearning.title }}</text>
            <text class="text-[10px] text-muted-foreground block truncate">{{ userData.continueLearning.lastLesson }}</text>
          </view>
          <!-- 进度 -->
          <view class="flex flex-col items-end">
            <text class="text-sm font-bold text-primary">{{ userData.continueLearning.progress }}%</text>
            <view class="w-12 h-1 bg-secondary rounded-full mt-1 overflow-hidden">
              <view
                class="h-full bg-primary rounded-full"
                :style="{ width: userData.continueLearning.progress + '%' }"
              />
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- ===== 猜你喜欢 ===== -->
    <view class="px-4 mt-4 mb-6">
      <view class="flex items-center justify-between mb-3">
        <text class="font-medium text-foreground">猜你喜欢</text>
        <view class="text-xs text-muted-foreground flex items-center" @click="navigateTo('/pages/discover/index')">
          <text>更多</text>
          <text class="ml-0.5 text-sm">›</text>
        </view>
      </view>
      <scroll-view scroll-x class="flex gap-3 overflow-x-auto pb-1" style="white-space: nowrap;">
        <view v-for="item in recommendations" :key="item.id" class="inline-flex flex-col flex-shrink-0 w-32 mr-3" @click="navigateTo(item.type === 'course' ? '/pages/course/' + item.id + '/index' : '/pages/mall/product/' + item.id + '/index')">
          <view class="aspect-[3/4] rounded-lg bg-gradient-to-br from-primary/5 to-accent/5 relative flex items-center justify-center shadow-sm" style="aspect-ratio: 3/4;">
            <text v-if="item.type === 'course'" class="text-2xl text-primary/30"></text>
            <text v-else class="text-2xl text-accent/30">📦</text>
            <view v-if="item.tag" class="absolute top-1.5 left-1.5 bg-primary text-white text-[10px] px-1.5 py-0.5 rounded">
              <text>{{ item.tag }}</text>
            </view>
          </view>
          <text class="text-xs font-medium mt-2 leading-relaxed text-foreground line-clamp-2" style="display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;">{{ item.title }}</text>
          <view class="flex items-baseline gap-1 mt-1">
            <text class="text-sm font-bold text-primary">¥{{ item.price }}</text>
            <text class="text-[10px] text-muted-foreground line-through">¥{{ item.originalPrice }}</text>
          </view>
        </view>
      </scroll-view>
    </view>

    <!-- 会员到期提醒 -->
    <view v-if="userData.isVip && userData.vipDaysLeft <= 30" class="fixed bottom-24 left-4 right-4">
      <view class="bg-gradient-to-r from-accent to-[#D4B87D] text-white p-3 rounded-xl shadow-sm flex items-center justify-between">
        <view class="flex items-center gap-2">
          <text class="text-lg">👑</text>
          <text class="text-sm">会员还剩 {{ userData.vipDaysLeft }} 天到期</text>
        </view>
        <view class="px-3 py-1 bg-white text-accent rounded-full text-xs font-medium" @click="navigateTo('/pages/vip/index')">
          <text>立即续费</text>
        </view>
      </view>
    </view>

    <!-- ===== 底部导航栏 ===== -->
    <view class="fixed bottom-0 left-0 right-0 bg-white border-t border-border safe-area-bottom">
      <view class="flex items-center justify-around py-2 px-2">
        <view v-for="tab in bottomNavItems" :key="tab.key" class="flex flex-col items-center gap-0.5" @click="navigateTo(tab.href)">
          <text :class="tab.key === 'profile' ? 'text-primary text-lg' : 'text-muted-foreground text-lg'">{{ tab.icon }}</text>
          <text :class="tab.key === 'profile' ? 'text-primary text-[10px]' : 'text-muted-foreground text-[10px]'">{{ tab.label }}</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

// ===== 类型定义 =====
type UserRole = 'user' | 'circle_owner' | 'teacher' | 'station_owner' | 'streamer' | 'creator'

// ===== 用户数据 =====
const userData = ref({
  name: '张三丰',
  avatar: '',
  bio: '易学爱好者 | 八字研习中',
  isVip: true,
  vipLevel: '黄金会员',
  vipExpiry: '2025-12-31',
  vipDaysLeft: 234,
  isVerified: true,
  roles: [
    { type: 'circle_owner' as UserRole, name: '张氏命理研习社', id: 1 },
    { type: 'teacher' as UserRole, name: '八字入门精讲', id: 1 },
    { type: 'streamer' as UserRole, name: '直播间', id: 1 },
  ],
  messages: {
    system: 2,
    interaction: 5,
    transaction: 1,
  },
  checkIn: {
    todayChecked: false,
    continuousDays: 7,
    totalPoints: 350,
  },
  stats: {
    following: 128,
    followers: 1024,
    likes: 3680,
  },
  coins: 520,
  coupons: 3,
  points: 1280,
  orders: {
    pending: 2,
    shipped: 1,
    received: 3,
    refund: 0,
  },
  continueLearning: {
    id: 1,
    title: '八字入门实战课',
    progress: 45,
    lastLesson: '第三章：天干地支详解',
  },
})

// ===== 问候语 =====
const greeting = ref('')

function getGreeting(): string {
  const hour = new Date().getHours()
  if (hour < 6) return '夜深了'
  if (hour < 12) return '早上好'
  if (hour < 14) return '中午好'
  if (hour < 18) return '下午好'
  return '晚上好'
}

// ===== 消息总数 =====
const totalMessages = computed(() => {
  const m = userData.value.messages
  return m.system + m.interaction + m.transaction
})

// ===== 角色配置 =====
const roleConfig: Record<UserRole, { label: string; icon: string; color: string; bgColor: string }> = {
  user: { label: '普通用户', icon: '', color: 'text-muted-foreground', bgColor: 'bg-[#999]/10' },
  circle_owner: { label: '圈主后台', icon: '👑', color: 'text-accent', bgColor: 'bg-accent/10' },
  teacher: { label: '讲师后台', icon: '🎓', color: 'text-[#4A90D9]', bgColor: 'bg-[#4A90D9]/10' },
  station_owner: { label: '站长后台', icon: '', color: 'text-success', bgColor: 'bg-success/10' },
  streamer: { label: '主播中心', icon: '📡', color: 'text-primary', bgColor: 'bg-primary/10' },
  creator: { label: '创作中心', icon: '', color: 'text-operator', bgColor: 'bg-operator/10' },
}

// ===== 订单状态配置 =====
interface OrderStatusItem {
  key: string
  label: string
  icon: string
  count: number
  href: string
}

const orderStatus = computed<OrderStatusItem[]>(() => [
  { key: 'pending', label: '待付款', icon: '', count: userData.value.orders.pending, href: '/pages/orders/index?status=pending' },
  { key: 'shipped', label: '待发货', icon: '📦', count: userData.value.orders.shipped, href: '/pages/orders/index?status=shipped' },
  { key: 'received', label: '待收货', icon: '🚚', count: userData.value.orders.received, href: '/pages/orders/index?status=received' },
  { key: 'refund', label: '售后', icon: '', count: userData.value.orders.refund, href: '/pages/orders/index?status=refund' },
])

// ===== 常用功能入口 =====
interface QuickFunction {
  icon: string
  label: string
  href: string
  color: string
}

const quickFunctions: QuickFunction[] = [
  { icon: '🧭', label: '排盘记录', href: '/pages/paipan/bazi/history/index', color: 'text-primary' },
  { icon: '', label: '我的课程', href: '/pages/learning/index', color: 'text-[#4A90D9]' },
  { icon: '', label: '我的圈子', href: '/pages/my-circles/index', color: 'text-operator' },
  { icon: '', label: '我的笔记', href: '/pages/classics/notes/index', color: 'text-accent' },
  { icon: '❤', label: '我的收藏', href: '/pages/favorites/index', color: 'text-primary' },
  { icon: '', label: '我的电子书', href: '/pages/ebook/index', color: 'text-success' },
  { icon: '🕐', label: '浏览历史', href: '/pages/history/index', color: 'text-[#64748B]' },
  { icon: '❓', label: '帮助中心', href: '/pages/help/index', color: 'text-muted-foreground' },
]

// ===== 猜你喜欢推荐 =====
interface Recommendation {
  id: number
  type: 'course' | 'product'
  title: string
  price: number
  originalPrice: number
  tag: string
}

const recommendations: Recommendation[] = [
  { id: 1, type: 'course', title: '紫微斗数入门精讲', price: 199, originalPrice: 399, tag: '热门' },
  { id: 2, type: 'product', title: '专业罗盘套装', price: 298, originalPrice: 598, tag: '特惠' },
  { id: 3, type: 'course', title: '六爻预测实战班', price: 299, originalPrice: 499, tag: '新课' },
  { id: 4, type: 'product', title: '渊海子平精装版', price: 68, originalPrice: 128, tag: '' },
]

// ===== 底部导航 =====
const bottomNavItems = [
  { key: 'home', label: '首页', icon: '🏠', href: '/pages/index/index' },
  { key: 'discover', label: '发现', icon: '', href: '/pages/discover/index' },
  { key: 'learning', label: '学习', icon: '', href: '/pages/learning/index' },
  { key: 'messages', label: '消息', icon: '', href: '/pages/messages/index' },
  { key: 'profile', label: '我的', icon: '', href: '/pages/profile/index' },
]

// ===== 导航函数 =====
function navigateTo(url: string) {
  uni.navigateTo({ url })
}

function navigateToRole(role: { type: UserRole; name: string; id: number }) {
  let href = ''
  switch (role.type) {
    case 'circle_owner':
      href = `/pages/circle/${role.id}/settings/index`
      break
    case 'teacher':
      href = '/pages/manage/my-courses/index'
      break
    case 'streamer':
      href = '/pages/creator/live/console/index'
      break
    case 'creator':
      href = '/pages/videos/creator/index'
      break
    default:
      href = '/pages/profile/index'
  }
  uni.navigateTo({ url: href })
}

function scanQR() {
  uni.scanCode({
    success: (res) => {
      uni.showToast({ title: '扫码结果: ' + res.result, icon: 'none' })
    },
  })
}

// ===== 生命周期 =====
onMounted(() => {
  greeting.value = getGreeting()
})
</script>
