// apps/mobile/src/pkg-im/im/add-friend/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="navbar">
      <view class="back-btn" @tap="goBack">
        <AppIcon name="arrow-left" :size="40" color="#2c2c2c" />
      </view>
      <text class="nav-title">添加好友</text>
    </view>

    <view class="content">
      <!-- 搜索栏 -->
      <view class="search-bar">
        <view class="search-input-wrap">
          <AppIcon name="search" :size="32" color="#999999" class="search-icon" />
          <input
            class="search-input"
            :value="query"
            placeholder="搜索手机号 / 智玄号 / 昵称"
            placeholder-class="search-ph"
            confirm-type="search"
            @input="onInput"
            @confirm="doSearch"
          />
        </view>
        <view class="search-btn" :class="{ 'btn-disabled': loading || !query.trim() }" @tap="doSearch">
          <view v-if="loading" class="spin">
            <AppIcon name="loader-2" :size="28" color="#ffffff" />
          </view>
          <text v-else class="search-btn-text">搜索</text>
        </view>
      </view>

      <!-- 其他方式 -->
      <view v-if="!searched">
        <text class="section-title">其他方式</text>
        <view class="method-list">
          <view v-for="tip in TIPS" :key="tip.label" class="method-item">
            <view class="method-icon">
              <AppIcon :name="tip.icon" :size="40" color="#c41e3a" />
            </view>
            <view class="method-body">
              <text class="method-label">{{ tip.label }}</text>
              <text class="method-desc">{{ tip.desc }}</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 搜索结果 -->
      <view v-if="searched">
        <text class="section-title">搜索结果</text>
        <view v-if="results.length === 0" class="empty">
          <text class="empty-text">未找到该用户</text>
        </view>
        <view v-else class="result-list">
          <view v-for="user in results" :key="user.id" class="result-item">
            <image class="result-avatar" :src="user.avatar" mode="aspectFill" />
            <view class="result-body">
              <text class="result-name">{{ user.name }}</text>
              <text class="result-bio">{{ user.bio }}</text>
              <text class="result-mutual">{{ user.mutual }} 个共同好友</text>
            </view>
            <view
              class="add-btn"
              :class="user.added ? 'add-btn-done' : 'add-btn-default'"
              @tap="!user.added && addFriend(user.id)"
            >
              <view v-if="sending[user.id]" class="spin">
                <AppIcon name="loader-2" :size="28" color="#c41e3a" />
              </view>
              <template v-else-if="user.added">
                <AppIcon name="check" :size="28" color="#2c2c2c" />
                <text class="add-btn-text-done">已添加</text>
              </template>
              <template v-else>
                <AppIcon name="user-plus" :size="28" color="#ffffff" />
                <text class="add-btn-text">添加</text>
              </template>
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'

interface SearchUser {
  id: string
  name: string
  avatar: string
  bio: string
  mutual: number
  added: boolean
}

const TIPS = [
  { icon: 'qr-code', label: '扫一扫', desc: '扫描好友二维码' },
  { icon: 'phone', label: '手机联系人', desc: '从通讯录添加好友' },
  { icon: 'at-sign', label: '智玄号', desc: '通过智玄号搜索' },
]

const query = ref('')
const searched = ref(false)
const loading = ref(false)
const results = ref<SearchUser[]>([])
const sending = ref<Record<string, boolean>>({})

function onInput(e: any) {
  query.value = e.detail.value
}

// @data-needs: 搜索用户, 参数 {keyword}, 返回 SearchUser[]
async function doSearch() {
  if (!query.value.trim() || loading.value) return
  loading.value = true
  await new Promise((r) => setTimeout(r, 800))
  results.value = [
    { id: '1', name: '周易大师', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80', bio: '八字命理研究者，从业二十年', mutual: 12, added: false },
    { id: '2', name: '张玄风', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80', bio: '紫微斗数专家 · 台湾传承', mutual: 5, added: false },
  ]
  searched.value = true
  loading.value = false
}

// @data-needs: 发送好友申请, 参数 {userId}, 返回 {code}
async function addFriend(id: string) {
  sending.value = { ...sending.value, [id]: true }
  await new Promise((r) => setTimeout(r, 800))
  const u = results.value.find((x) => x.id === id)
  if (u) u.added = true
  sending.value = { ...sending.value, [id]: false }
}
</script>

<style scoped>
.page {
  min-height: 100vh;
  background: #faf8f5;
}

/* 导航栏 */
.navbar {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  gap: 24rpx;
  height: 96rpx;
  padding: 0 32rpx;
  background: #faf8f5;
  border-bottom: 2rpx solid #e8e0d5;
}
.back-btn {
  width: 40rpx;
  height: 40rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}
.nav-title {
  font-size: 32rpx;
  font-weight: 600;
  color: #2c2c2c;
}

/* 内容 */
.content {
  padding: 32rpx 32rpx 160rpx;
}

/* 搜索栏 */
.search-bar {
  display: flex;
  gap: 16rpx;
  margin-bottom: 48rpx;
}
.search-input-wrap {
  flex: 1;
  position: relative;
  display: flex;
  align-items: center;
  height: 72rpx;
  border: 2rpx solid #e8e0d5;
  border-radius: 12rpx;
  background: #ffffff;
}
.search-icon {
  position: absolute;
  left: 24rpx;
}
.search-input {
  flex: 1;
  height: 72rpx;
  padding-left: 72rpx;
  padding-right: 24rpx;
  font-size: 32rpx;
  color: #2c2c2c;
  background: transparent;
}
.search-ph {
  color: #999999;
}
.search-btn {
  flex-shrink: 0;
  height: 72rpx;
  padding: 0 32rpx;
  border-radius: 12rpx;
  background: #c41e3a;
  display: flex;
  align-items: center;
  justify-content: center;
}
.btn-disabled {
  opacity: 0.5;
}
.search-btn-text {
  font-size: 28rpx;
  font-weight: 500;
  color: #ffffff;
}

/* 区块标题 */
.section-title {
  display: block;
  font-size: 28rpx;
  font-weight: 600;
  color: #2c2c2c;
  margin-bottom: 24rpx;
}

/* 其他方式 */
.method-list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}
.method-item {
  display: flex;
  align-items: center;
  gap: 24rpx;
  padding: 32rpx;
  background: #ffffff;
  border: 2rpx solid #e8e0d5;
  border-radius: 24rpx;
}
.method-icon {
  width: 80rpx;
  height: 80rpx;
  border-radius: 24rpx;
  background: rgba(196, 30, 58, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.method-body {
  display: flex;
  flex-direction: column;
}
.method-label {
  font-size: 28rpx;
  font-weight: 500;
  color: #2c2c2c;
}
.method-desc {
  font-size: 24rpx;
  color: #999999;
}

/* 空态 */
.empty {
  padding: 96rpx 0;
  text-align: center;
}
.empty-text {
  font-size: 28rpx;
  color: #999999;
}

/* 搜索结果 */
.result-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.result-item {
  display: flex;
  align-items: center;
  gap: 24rpx;
  padding: 32rpx;
  background: #ffffff;
  border: 2rpx solid #e8e0d5;
  border-radius: 24rpx;
}
.result-avatar {
  width: 96rpx;
  height: 96rpx;
  border-radius: 50%;
  background: #f0ebe5;
  flex-shrink: 0;
}
.result-body {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
}
.result-name {
  font-size: 28rpx;
  font-weight: 500;
  color: #2c2c2c;
}
.result-bio {
  font-size: 24rpx;
  color: #999999;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.result-mutual {
  font-size: 24rpx;
  color: #999999;
}
.add-btn {
  flex-shrink: 0;
  height: 64rpx;
  padding: 0 24rpx;
  border-radius: 12rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8rpx;
}
.add-btn-default {
  background: #c41e3a;
}
.add-btn-done {
  background: transparent;
  border: 2rpx solid #e8e0d5;
}
.add-btn-text {
  font-size: 26rpx;
  font-weight: 500;
  color: #ffffff;
}
.add-btn-text-done {
  font-size: 26rpx;
  font-weight: 500;
  color: #2c2c2c;
}

/* loading 旋转 */
.spin {
  display: flex;
  align-items: center;
  justify-content: center;
  animation: spin 0.8s linear infinite;
}
@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
</style>

// proto-ref-app/im/add-friend/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Search, UserPlus, QrCode, Phone, AtSign, Check, Loader2 } from 'lucide-react'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface SearchUser {
  id: string
  name: string
  avatar: string
  bio: string
  mutual: number
  added: boolean
}

const TIPS = [
  { icon: <QrCode className="w-5 h-5" />, label: '扫一扫', desc: '扫描好友二维码' },
  { icon: <Phone className="w-5 h-5" />, label: '手机联系人', desc: '从通讯录添加好友' },
  { icon: <AtSign className="w-5 h-5" />, label: '智玄号', desc: '通过智玄号搜索' },
]

export default function AddFriendPage() {
  const router = useRouter()
  const [query, setQuery] = useState('')
  const [searched, setSearched] = useState(false)
  const [loading, setLoading] = useState(false)
  const [results, setResults] = useState<SearchUser[]>([])
  const [sending, setSending] = useState<Record<string, boolean>>({})

  const doSearch = async () => {
    if (!query.trim()) return
    setLoading(true)
    await new Promise(r => setTimeout(r, 800))
    setResults([
      { id: '1', name: '周易大师', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80', bio: '八字命理研究者，从业二十年', mutual: 12, added: false },
      { id: '2', name: '张玄风', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80', bio: '紫微斗数专家 · 台湾传承', mutual: 5, added: false },
    ])
    setSearched(true)
    setLoading(false)
  }

  const addFriend = async (id: string) => {
    setSending(prev => ({ ...prev, [id]: true }))
    await new Promise(r => setTimeout(r, 800))
    setResults(prev => prev.map(u => u.id === id ? { ...u, added: true } : u))
    setSending(prev => ({ ...prev, [id]: false }))
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 bg-background border-b border-border flex items-center px-4 h-12 gap-3">
        <button onClick={() => router.back()}><ArrowLeft className="w-5 h-5 text-foreground" /></button>
        <h1 className="text-base font-semibold text-foreground">添加好友</h1>
      </header>

      <div className="px-4 pt-4 pb-20">
        {/* Search bar */}
        <div className="flex gap-2 mb-6">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input placeholder="搜索手机号 / 智玄号 / 昵称" value={query} onChange={e => setQuery(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && doSearch()} className="pl-9" />
          </div>
          <Button onClick={doSearch} disabled={loading || !query.trim()} className="bg-primary hover:bg-primary/90">
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : '搜索'}
          </Button>
        </div>

        {/* Methods */}
        {!searched && (
          <div>
            <h2 className="text-sm font-semibold text-foreground mb-3">其他方式</h2>
            <div className="space-y-2">
              {TIPS.map(tip => (
                <button key={tip.label} className="w-full flex items-center gap-3 p-4 bg-card border border-border rounded-xl text-left hover:bg-muted/20 transition-colors">
                  <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary flex-shrink-0">
                    {tip.icon}
                  </div>
                  <div>
                    <p className="text-sm font-medium text-foreground">{tip.label}</p>
                    <p className="text-xs text-muted-foreground">{tip.desc}</p>
                  </div>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Results */}
        {searched && (
          <div>
            <h2 className="text-sm font-semibold text-foreground mb-3">搜索结果</h2>
            {results.length === 0 ? (
              <p className="text-center py-12 text-sm text-muted-foreground">未找到该用户</p>
            ) : (
              <div className="space-y-3">
                {results.map(user => (
                  <div key={user.id} className="flex items-center gap-3 p-4 bg-card border border-border rounded-xl">
                    <Avatar className="w-12 h-12 flex-shrink-0">
                      <AvatarImage src={user.avatar} />
                      <AvatarFallback>{user.name[0]}</AvatarFallback>
                    </Avatar>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground">{user.name}</p>
                      <p className="text-xs text-muted-foreground truncate">{user.bio}</p>
                      <p className="text-xs text-muted-foreground">{user.mutual} 个共同好友</p>
                    </div>
                    <Button size="sm" variant={user.added ? 'outline' : 'default'} disabled={user.added || sending[user.id]}
                      onClick={() => !user.added && addFriend(user.id)}
                      className={cn(!user.added && 'bg-primary hover:bg-primary/90')}>
                      {sending[user.id] ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                        : user.added ? <><Check className="w-3.5 h-3.5 mr-1" />已添加</>
                        : <><UserPlus className="w-3.5 h-3.5 mr-1" />添加</>}
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
