// v0-reference/app/vip/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { Crown, Check, Star, BookOpen, Bot, Radio, ShoppingBag, Gift, Zap, Shield, TrendingUp } from 'lucide-react'
import { BackButton } from '@/components/common/back-button'
import { MembershipComparison } from '@/components/membership/membership-comparison'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Switch } from '@/components/ui/switch'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Label } from '@/components/ui/label'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import { toast } from 'sonner'
import { DataState, SkeletonCard, SkeletonLine } from '@/components/data-state'
import { getVipCenterData, purchaseVip, toggleAutoRenew } from '@/lib/api/vip'
import type { VipCenterData, VipPlan, VipLevel } from '@/lib/types/vip'
import { usePaymentBindings } from '@/hooks/use-payment-bindings'
import { BindPaymentDialog } from '@/components/wallet/bind-payment-dialog'

// 权益图标映射
const benefitIcons: Record<string, React.ComponentType<{ className?: string }>> = {
  'crown': Crown,
  'video': Bot,
  'download': BookOpen,
  'gift': Gift,
  'book': BookOpen,
  'calculator': Zap,
  'customer-service': Shield,
  'discount': ShoppingBag,
}

// 等级颜色
const levelColors: Record<VipLevel, string> = {
  'none': 'bg-muted',
  'basic': 'bg-amber-500',
  'pro': 'bg-purple-500',
  'premium': 'bg-gradient-to-r from-amber-400 to-orange-500',
}

export default function VIPPage() {
  const [data, setData] = useState<VipCenterData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  const [selectedLevel, setSelectedLevel] = useState<VipLevel>('pro')
  const [selectedPlan, setSelectedPlan] = useState<VipPlan | null>(null)
  const [showPaySheet, setShowPaySheet] = useState(false)
  const [paymentMethod, setPaymentMethod] = useState<'wechat' | 'alipay' | 'unionpay' | 'huifu'>('wechat')
  const { isBound } = usePaymentBindings()
  const [showBindDialog, setShowBindDialog] = useState(false)
  const [purchasing, setPurchasing] = useState(false)
  const [autoRenewLoading, setAutoRenewLoading] = useState(false)

  useEffect(() => {
    loadData()
  }, [])

  const loadData = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await getVipCenterData()
      if (res.code === 200) {
        setData(res.data)
        // 默认选中当前等级或专业会员
        const defaultLevel = res.data.status.level !== 'none' ? res.data.status.level : 'pro'
        setSelectedLevel(defaultLevel)
        // 默认选中推荐套餐
        const currentGroup = res.data.planGroups.find(g => g.level === defaultLevel)
        const popularPlan = currentGroup?.plans.find(p => p.popular)
        setSelectedPlan(popularPlan || currentGroup?.plans[0] || null)
      } else {
        setError(res.message)
      }
    } catch {
      setError('加载失败')
    } finally {
      setLoading(false)
    }
  }

  const handleSelectLevel = (level: VipLevel) => {
    setSelectedLevel(level)
    const group = data?.planGroups.find(g => g.level === level)
    const popularPlan = group?.plans.find(p => p.popular)
    setSelectedPlan(popularPlan || group?.plans[0] || null)
  }

  const handleSelectPlan = (plan: VipPlan) => {
    setSelectedPlan(plan)
  }

  const handlePurchase = async () => {
    if (!selectedPlan) return

    // 所选第三方支付渠道未绑定时，引导用户先绑定
    if (!isBound(paymentMethod)) {
      setShowPaySheet(false)
      setShowBindDialog(true)
      return
    }

    setPurchasing(true)
    try {
      const res = await purchaseVip({ planId: selectedPlan.id, paymentMethod })
      if (res.code === 200) {
        toast.success('购买成功', { description: `会员有效期至 ${res.data.expireAt}` })
        setShowPaySheet(false)
        loadData()
      } else {
        toast.error(res.message)
      }
    } catch {
      toast.error('购买失败')
    } finally {
      setPurchasing(false)
    }
  }

  const handleToggleAutoRenew = async (enabled: boolean) => {
    setAutoRenewLoading(true)
    try {
      const res = await toggleAutoRenew(enabled)
      if (res.code === 200) {
        toast.success(res.message)
        if (data) {
          setData({ ...data, status: { ...data.status, autoRenew: enabled } })
        }
      } else {
        toast.error(res.message)
      }
    } catch {
      toast.error('操作失败')
    } finally {
      setAutoRenewLoading(false)
    }
  }

  // 骨架屏
  const renderSkeleton = () => (
    <div className="min-h-screen bg-background pb-24">
      <div className="absolute top-0 left-0 right-0 h-80 bg-gradient-to-b from-accent/20 via-accent/10 to-transparent pointer-events-none" />
      <header className="sticky top-0 z-40 bg-transparent safe-area-pt">
        <div className="flex items-center justify-between px-4 h-14">
          <div className="w-10" />
          <SkeletonLine className="w-24 h-5" />
          <div className="w-10" />
        </div>
      </header>
      <div className="relative z-10 px-4 space-y-6">
        <SkeletonCard className="h-44" />
        <div>
          <SkeletonLine className="w-20 h-5 mb-3" />
          <div className="grid grid-cols-2 gap-3">
            {[1, 2, 3, 4].map(i => <SkeletonCard key={i} className="h-32" />)}
          </div>
        </div>
        <div>
          <SkeletonLine className="w-24 h-5 mb-3" />
          <div className="grid grid-cols-2 gap-3">
            {[1, 2, 3, 4].map(i => <SkeletonCard key={i} className="h-20" />)}
          </div>
        </div>
      </div>
    </div>
  )

  // 获取当前选中的套餐组
  const currentPlanGroup = data?.planGroups.find(g => g.level === selectedLevel)

  return (
    <div className="min-h-screen bg-background pb-24">
      {/* 顶部金色渐变背景 */}
      <div className="absolute top-0 left-0 right-0 h-80 bg-gradient-to-b from-accent/20 via-accent/10 to-transparent pointer-events-none" />
      
      {/* 顶部导航 */}
      <header className="sticky top-0 z-40 bg-transparent safe-area-pt">
        <div className="flex items-center justify-between px-4 h-14">
          <BackButton fallbackPath="/profile" />
          <h1 className="font-semibold text-lg text-foreground">会员中心</h1>
          <Link href="/vip/records" className="text-sm text-primary">
            购买记录
          </Link>
        </div>
      </header>

      <DataState
        loading={loading}
        error={error}
        empty={!data}
        skeleton={renderSkeleton()}
        onRetry={loadData}
      >
        {data && (
          <div className="relative z-10 px-4 space-y-6">
            {/* 会员卡片 */}
            <Card className="p-6 bg-gradient-to-br from-accent via-accent/90 to-primary/80 border-0 shadow-xl shadow-accent/20 overflow-hidden relative">
              {/* 装饰图案 */}
              <div className="absolute -right-10 -top-10 w-40 h-40 opacity-10">
                <svg viewBox="0 0 100 100" className="w-full h-full fill-current text-white">
                  <circle cx="50" cy="50" r="48" fill="none" stroke="currentColor" strokeWidth="2"/>
                  <path d="M50 2 A48 48 0 0 1 50 98 A24 24 0 0 1 50 50 A24 24 0 0 0 50 2" />
                </svg>
              </div>
              
              <div className="relative">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-14 h-14 rounded-full bg-white/20 flex items-center justify-center">
                    <Crown className="w-8 h-8 text-white" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <h2 className="text-xl font-bold text-white">
                        {data.status.level !== 'none' ? data.status.levelName : '热卜国学VIP'}
                      </h2>
                      {data.status.level !== 'none' && (
                        <Badge className="bg-white/20 text-white border-0">
                          {data.status.level.toUpperCase()}
                        </Badge>
                      )}
                    </div>
                    <p className="text-sm text-white/70">
                      {data.status.level !== 'none' 
                        ? (data.status.isExpired 
                            ? '会员已过期' 
                            : `有效期至 ${data.status.expireAt}，还剩 ${data.status.daysLeft} 天`)
                        : '解锁全部特权，畅享国学智慧'}
                    </p>
                  </div>
                </div>
                
                {/* 核心数据 */}
                <div className="grid grid-cols-3 gap-4 pt-4 border-t border-white/20">
                  <div className="text-center">
                    <p className="text-2xl font-bold text-white">500+</p>
                    <p className="text-xs text-white/70">免费课程</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-white">无限</p>
                    <p className="text-xs text-white/70">AI对话</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-white">{data.status.points}</p>
                    <p className="text-xs text-white/70">会员积分</p>
                  </div>
                </div>

                {/* 自动续费 */}
                {data.status.level !== 'none' && (
                  <div className="flex items-center justify-between mt-4 pt-4 border-t border-white/20">
                    <span className="text-sm text-white/80">自动续费</span>
                    <Switch
                      checked={data.status.autoRenew}
                      onCheckedChange={handleToggleAutoRenew}
                      disabled={autoRenewLoading}
                      className="data-[state=checked]:bg-white/30"
                    />
                  </div>
                )}
              </div>
            </Card>

            {/* 等级选择 */}
            <div>
              <h3 className="font-semibold text-base text-foreground mb-3">选择等级</h3>
              <div className="flex gap-2 overflow-x-auto pb-2">
                {data.planGroups.map(group => (
                  <Button
                    key={group.level}
                    variant={selectedLevel === group.level ? 'default' : 'outline'}
                    className={cn(
                      'flex-shrink-0',
                      selectedLevel === group.level && levelColors[group.level]
                    )}
                    onClick={() => handleSelectLevel(group.level)}
                  >
                    {group.levelName}
                  </Button>
                ))}
              </div>
              {currentPlanGroup && (
                <p className="text-sm text-muted-foreground mt-2">{currentPlanGroup.description}</p>
              )}
            </div>

            {/* 套餐选择 */}
            <div>
              <h3 className="font-semibold text-base text-foreground mb-3">选择套餐</h3>
              <div className="grid grid-cols-3 gap-3">
                {currentPlanGroup?.plans.map(plan => (
                  <Card
                    key={plan.id}
                    onClick={() => handleSelectPlan(plan)}
                    className={cn(
                      'p-3 cursor-pointer transition-all relative overflow-hidden',
                      selectedPlan?.id === plan.id
                        ? 'border-2 border-accent bg-accent/5'
                        : 'border-border hover:border-accent/50'
                    )}
                  >
                    {/* 标签 */}
                    {plan.popular && (
                      <div className="absolute top-0 right-0 px-2 py-0.5 text-[10px] font-medium rounded-bl-lg bg-accent text-accent-foreground">
                        推荐
                      </div>
                    )}
                    {plan.discount && !plan.popular && (
                      <div className="absolute top-0 right-0 px-2 py-0.5 text-[10px] font-medium rounded-bl-lg bg-destructive text-destructive-foreground">
                        {plan.discount}
                      </div>
                    )}
                    
                    <p className="font-medium text-sm text-foreground text-center">{plan.durationName}</p>
                    <div className="flex items-baseline justify-center gap-0.5 mt-2">
                      <span className="text-xs text-muted-foreground">¥</span>
                      <span className="text-2xl font-bold text-primary">{plan.price}</span>
                    </div>
                    {plan.originalPrice > plan.price && (
                      <p className="text-xs text-muted-foreground line-through text-center mt-1">
                        ¥{plan.originalPrice}
                      </p>
                    )}
                    <p className="text-xs text-accent text-center mt-1">
                      ¥{plan.dailyPrice}/天
                    </p>
                    
                    {/* 选中指示 */}
                    {selectedPlan?.id === plan.id && (
                      <div className="absolute top-2 left-2 w-5 h-5 rounded-full bg-accent flex items-center justify-center">
                        <Check className="w-3 h-3 text-accent-foreground" />
                      </div>
                    )}
                  </Card>
                ))}
              </div>
            </div>

            {/* 会员权益 */}
            <div>
              <h3 className="font-semibold text-base text-foreground mb-3">会员专属权益</h3>
              <div className="grid grid-cols-2 gap-3">
                {data.benefits.map((benefit) => {
                  const Icon = benefitIcons[benefit.icon] || Gift
                  const available = benefit.levels.includes(selectedLevel)
                  return (
                    <Card
                      key={benefit.id}
                      className={cn(
                        'p-3',
                        available ? 'bg-accent/5 border-accent/30' : 'opacity-50'
                      )}
                    >
                      <div className="flex items-start gap-3">
                        <div className={cn(
                          'w-10 h-10 rounded-lg flex items-center justify-center shrink-0',
                          available ? 'bg-accent/20' : 'bg-secondary'
                        )}>
                          <Icon className={cn(
                            'w-5 h-5',
                            available ? 'text-accent' : 'text-muted-foreground'
                          )} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-sm text-foreground">{benefit.title}</p>
                          <p className="text-xs text-muted-foreground mt-0.5 line-clamp-2">
                            {benefit.description}
                          </p>
                        </div>
                      </div>
                    </Card>
                  )
                })}
              </div>
            </div>

            {/* 权益对比 */}
            <div>
              <h3 className="font-semibold text-base text-foreground mb-3 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-green-500" />
                权益对比
              </h3>
              <MembershipComparison onSelectVIP={() => setShowPaySheet(true)} />
            </div>

            {/* 用户评价 */}
            <div>
              <h3 className="font-semibold text-base text-foreground mb-3">会员评价</h3>
              <div className="space-y-3">
                {[
                  { name: '易*明', avatar: '易', content: '开通年度会员后，学习效率提升很多，课程质量很高！', days: 128 },
                  { name: '张*华', avatar: '张', content: 'AI智能体太好用了，排盘解读很专业，物超所值。', days: 56 },
                ].map((review, index) => (
                  <Card key={index} className="p-3">
                    <div className="flex items-start gap-3">
                      <div className="w-10 h-10 rounded-full bg-accent/20 flex items-center justify-center">
                        <span className="text-sm font-medium text-accent">{review.avatar}</span>
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center justify-between">
                          <span className="font-medium text-sm text-foreground">{review.name}</span>
                          <div className="flex items-center gap-0.5">
                            {[1,2,3,4,5].map(i => (
                              <Star key={i} className="w-3 h-3 fill-accent text-accent" />
                            ))}
                          </div>
                        </div>
                        <p className="text-xs text-muted-foreground mt-1">{review.content}</p>
                        <p className="text-xs text-muted-foreground mt-2">已开通{review.days}天</p>
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
            </div>

            {/* 常见问题 */}
            <div>
              <h3 className="font-semibold text-base text-foreground mb-3">常见问题</h3>
              <Card className="divide-y divide-border">
                {[
                  { q: '开通后可以退款吗？', a: '会员服务一经开通，暂不支持退款，请确认后购买。' },
                  { q: '会员可以多设备登录吗？', a: '同一账号最多支持3台设备同时登录。' },
                  { q: '会员到期后权益还在吗？', a: '到期后会员权益将失效，但已下载的内容可继续保留。' },
                ].map((faq, index) => (
                  <div key={index} className="p-3">
                    <p className="font-medium text-sm text-foreground">{faq.q}</p>
                    <p className="text-xs text-muted-foreground mt-1">{faq.a}</p>
                  </div>
                ))}
              </Card>
            </div>
          </div>
        )}
      </DataState>

      {/* 底部购买栏 */}
      {data && selectedPlan && (
        <div className="fixed bottom-0 left-0 right-0 bg-background/95 backdrop-blur-lg border-t border-border safe-area-pb z-50">
          <div className="flex items-center justify-between px-4 py-3 max-w-lg mx-auto">
            <div>
              <div className="flex items-baseline gap-1">
                <span className="text-sm text-muted-foreground">¥</span>
                <span className="text-3xl font-bold text-primary">{selectedPlan.price}</span>
                <span className="text-sm text-muted-foreground">/{selectedPlan.durationName}</span>
              </div>
              <p className="text-xs text-muted-foreground line-through">
                原价 ¥{selectedPlan.originalPrice}
              </p>
            </div>
            <Button
              onClick={() => setShowPaySheet(true)}
              className="px-8 h-12 rounded-full bg-gradient-to-r from-accent to-primary text-white font-medium shadow-lg shadow-accent/30"
            >
              {data.status.level === selectedLevel && !data.status.isExpired ? '续费' : '立即开通'}
            </Button>
          </div>
        </div>
      )}

      {/* 支付方式选择 */}
      <Sheet open={showPaySheet} onOpenChange={setShowPaySheet}>
        <SheetContent side="bottom" className="rounded-t-2xl">
          <SheetHeader>
            <SheetTitle>选择支付方式</SheetTitle>
          </SheetHeader>
          <div className="py-4">
            {selectedPlan && (
              <div className="text-center mb-4 pb-4 border-b">
                <p className="text-sm text-muted-foreground">{selectedPlan.levelName} · {selectedPlan.durationName}</p>
                <p className="text-3xl font-bold text-primary mt-1">
                  <span className="text-lg">¥</span>{selectedPlan.price}
                </p>
              </div>
            )}
            
            <RadioGroup value={paymentMethod} onValueChange={(v) => setPaymentMethod(v as typeof paymentMethod)}>
              <div className="space-y-3">
                <Label className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-muted/50">
                  <RadioGroupItem value="wechat" />
                  <div className="w-8 h-8 rounded bg-green-500 flex items-center justify-center text-white text-xs font-bold">微</div>
                  <span>微信支付</span>
                </Label>
                <Label className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-muted/50">
                  <RadioGroupItem value="alipay" />
                  <div className="w-8 h-8 rounded bg-blue-500 flex items-center justify-center text-white text-xs font-bold">支</div>
                  <span>支付宝</span>
                </Label>
                <Label className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-muted/50">
                  <RadioGroupItem value="unionpay" />
                  <div className="w-8 h-8 rounded bg-red-500 flex items-center justify-center text-white text-xs font-bold">云</div>
                  <span>云闪付</span>
                </Label>
                <Label className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-muted/50">
                  <RadioGroupItem value="huifu" />
                  <div className="w-8 h-8 rounded bg-orange-500 flex items-center justify-center text-white text-xs font-bold">汇</div>
                  <span>汇付天下</span>
                </Label>
              </div>
            </RadioGroup>

            <Button 
              className="w-full mt-6" 
              size="lg"
              onClick={handlePurchase}
              disabled={purchasing}
            >
              {purchasing ? '处理中...' : '确认支付'}
            </Button>
          </div>
        </SheetContent>
      </Sheet>

      <BindPaymentDialog
        open={showBindDialog}
        onClose={() => setShowBindDialog(false)}
        channel={paymentMethod}
      />
    </div>
  )
}

// apps/mobile/.backup_vue3_converted/pages/vip/index.vue
<template>
  <view class="min-h-screen" style="background:#FAF8F5;padding-bottom:96px">
    <!-- 顶部金色渐变背景 -->
    <view style="position:absolute;top:0;left:0;right:0;height:320px;background:linear-gradient(180deg,rgba(201,169,110,0.2) 0%,rgba(201,169,110,0.1) 50%,transparent 100%);pointer-events:none" />

    <!-- 顶部导航 -->
    <view style="position:sticky;top:0;z-index:40;padding-top:env(safe-area-inset-top)">
      <view style="display:flex;align-items:center;justify-content:space-between;padding:0 16px;height:56px">
        <view style="width:40px;display:flex;align-items:center;justify-content:center" @click="goBack">
          <text style="font-size:20px;color:#2C2C2C">←</text>
        </view>
        <text style="font-size:18px;font-weight:600;color:#2C2C2C">会员中心</text>
        <view @click="goRecords" style="padding:8px 0">
          <text style="font-size:14px;color:#C41E3A">购买记录</text>
        </view>
      </view>
    </view>

    <!-- ====== 骨架屏 ====== -->
    <block v-if="loading && !data">
      <view style="padding:0 16px;display:flex;flex-direction:column;gap:24px">
        <!-- 骨架 header -->
        <view style="display:flex;justify-content:center">
          <view class="skeleton-pulse" style="width:96px;height:20px;border-radius:4px"></view>
        </view>
        <!-- 骨架 card -->
        <view class="skeleton-pulse" style="background:#fff;border-radius:12px;height:176px"></view>
        <!-- 骨架 grid 1 -->
        <view>
          <view class="skeleton-pulse" style="width:80px;height:20px;border-radius:4px;margin-bottom:12px"></view>
          <view style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
            <view v-for="i in 4" :key="i" class="skeleton-pulse" style="background:#fff;border-radius:12px;height:128px"></view>
          </view>
        </view>
        <!-- 骨架 grid 2 -->
        <view>
          <view class="skeleton-pulse" style="width:96px;height:20px;border-radius:4px;margin-bottom:12px"></view>
          <view style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
            <view v-for="i in 4" :key="'s2-'+i" class="skeleton-pulse" style="background:#fff;border-radius:12px;height:80px"></view>
          </view>
        </view>
      </view>
    </block>

    <!-- ====== 错误状态 ====== -->
    <block v-else-if="error">
      <view style="display:flex;flex-direction:column;align-items:center;justify-content:center;padding:80px 16px">
        <text style="font-size:40px;margin-bottom:16px"></text>
        <text style="font-size:14px;color:#999;margin-bottom:16px">{{ error }}</text>
        <view style="padding:10px 24px;background:#C41E3A;border-radius:999px" @click="loadData">
          <text style="color:#fff;font-size:14px">重新加载</text>
        </view>
      </view>
    </block>

    <!-- ====== 主内容 ====== -->
    <block v-if="data">
      <view style="position:relative;z-index:10;padding:0 16px;display:flex;flex-direction:column;gap:24px">

        <!-- ====== 会员卡片 ====== -->
        <view style="padding:24px;border-radius:12px;overflow:hidden;position:relative;background:linear-gradient(135deg,#C9A96E,rgba(201,169,110,0.9),rgba(196,30,58,0.8));box-shadow:0 20px 25px -5px rgba(201,169,110,0.2),0 10px 10px -5px rgba(201,169,110,0.04)">
          <!-- 装饰 SVG 图案 -->
          <view style="position:absolute;right:-40px;top:-40px;width:160px;height:160px;opacity:0.1">
            <svg viewBox="0 0 100 100" style="width:100%;height:100%;fill:currentColor;color:#fff">
              <circle cx="50" cy="50" r="48" fill="none" stroke="currentColor" stroke-width="2" />
              <path d="M50 2 A48 48 0 0 1 50 98 A24 24 0 0 1 50 50 A24 24 0 0 0 50 2" />
            </svg>
          </view>

          <view style="position:relative">
            <!-- 用户信息 -->
            <view style="display:flex;align-items:center;gap:12px;margin-bottom:16px">
              <view style="width:56px;height:56px;border-radius:50%;background:rgba(255,255,255,0.2);display:flex;align-items:center;justify-content:center">
                <text style="font-size:32px">👑</text>
              </view>
              <view style="flex:1">
                <view style="display:flex;align-items:center;gap:8px">
                  <text style="font-size:20px;font-weight:700;color:#fff">{{ data.status.level !== 'none' ? data.status.levelName : '热卜国学VIP' }}</text>
                  <text v-if="data.status.level !== 'none'" style="padding:2px 8px;border-radius:4px;font-size:10px;font-weight:500;background:rgba(255,255,255,0.2);color:#fff">{{ data.status.level.toUpperCase() }}</text>
                </view>
                <text style="font-size:14px;color:rgba(255,255,255,0.7);display:block">
                  {{ data.status.level !== 'none'
                    ? (data.status.isExpired ? '会员已过期' : '有效期至 ' + data.status.expireAt + '，还剩 ' + data.status.daysLeft + ' 天')
                    : '解锁全部特权，畅享国学智慧' }}
                </text>
              </view>
            </view>

            <!-- 核心数据 -->
            <view style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;padding-top:16px;border-top:1px solid rgba(255,255,255,0.2)">
              <view style="text-align:center">
                <text style="font-size:24px;font-weight:700;color:#fff;display:block">500+</text>
                <text style="font-size:12px;color:rgba(255,255,255,0.7)">免费课程</text>
              </view>
              <view style="text-align:center">
                <text style="font-size:24px;font-weight:700;color:#fff;display:block">无限</text>
                <text style="font-size:12px;color:rgba(255,255,255,0.7)">AI对话</text>
              </view>
              <view style="text-align:center">
                <text style="font-size:24px;font-weight:700;color:#fff;display:block">{{ data.status.points }}</text>
                <text style="font-size:12px;color:rgba(255,255,255,0.7)">会员积分</text>
              </view>
            </view>

            <!-- 自动续费 -->
            <view v-if="data.status.level !== 'none'" style="display:flex;align-items:center;justify-content:space-between;margin-top:16px;padding-top:16px;border-top:1px solid rgba(255,255,255,0.2)">
              <text style="font-size:14px;color:rgba(255,255,255,0.8)">自动续费</text>
              <view
                :style="{ width:'44px', height:'24px', borderRadius:'12px', padding:'2px', position:'relative', cursor:'pointer', background: data.status.autoRenew ? 'rgba(255,255,255,0.3)' : 'rgba(255,255,255,0.1)', opacity: autoRenewLoading ? 0.5 : 1 }"
                @click="!autoRenewLoading && handleToggleAutoRenew()"
              >
                <view :style="{ width:'20px', height:'20px', borderRadius:'10px', background:'#fff', transition:'all 0.2s', transform: data.status.autoRenew ? 'translateX(20px)' : 'translateX(0)' }" />
              </view>
            </view>
          </view>
        </view>

        <!-- ====== 等级选择 ====== -->
        <view>
          <text style="font-size:16px;font-weight:600;color:#2C2C2C;display:block;margin-bottom:12px">选择等级</text>
          <scroll-view scroll-x style="overflow-x:auto;padding-bottom:8px;white-space:nowrap">
            <view style="display:flex;gap:8px">
              <view
                v-for="group in data.planGroups" :key="group.level"
                :style="{
                  display:'inline-flex', padding:'6px 16px', borderRadius:'999px', fontSize:'14px', fontWeight:500,
                  whiteSpace:'nowrap', cursor:'pointer', transition:'all 0.2s',
                  background: selectedLevel === group.level ? levelColors[group.level].bg : '#fff',
                  color: selectedLevel === group.level ? '#fff' : '#2C2C2C',
                  border: selectedLevel === group.level ? 'none' : '1px solid #E8E0D5'
                }"
                @click="handleSelectLevel(group.level)"
              >
                <text>{{ group.levelName }}</text>
              </view>
            </view>
          </scroll-view>
          <text v-if="currentPlanGroup" style="font-size:14px;color:#999;display:block;margin-top:8px">{{ currentPlanGroup.description }}</text>
        </view>

        <!-- ====== 套餐选择 ====== -->
        <view>
          <text style="font-size:16px;font-weight:600;color:#2C2C2C;display:block;margin-bottom:12px">选择套餐</text>
          <view style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px">
            <view
              v-for="plan in currentPlanGroup?.plans" :key="plan.id"
              :style="{
                padding:'12px', borderRadius:'12px', cursor:'pointer', transition:'all 0.2s', position:'relative', overflow:'hidden',
                border: selectedPlan?.id === plan.id ? '2px solid #C9A96E' : '1px solid #E8E0D5',
                background: selectedPlan?.id === plan.id ? 'rgba(201,169,110,0.05)' : '#fff'
              }"
              @click="handleSelectPlan(plan)"
            >
              <!-- 标签 -->
              <view v-if="plan.popular" style="position:absolute;top:0;right:0;padding:2px 8px;font-size:10px;font-weight:500;border-radius:0 0 0 8px;background:#C9A96E;color:#fff">
                <text>推荐</text>
              </view>
              <view v-else-if="plan.discount" style="position:absolute;top:0;right:0;padding:2px 8px;font-size:10px;font-weight:500;border-radius:0 0 0 8px;background:#FF4D4F;color:#fff">
                <text>{{ plan.discount }}</text>
              </view>

              <text style="font-size:14px;font-weight:500;color:#2C2C2C;display:block;text-align:center">{{ plan.durationName }}</text>
              <view style="display:flex;align-items:baseline;justify-content:center;gap:2px;margin-top:8px">
                <text style="font-size:12px;color:#999">¥</text>
                <text style="font-size:24px;font-weight:700;color:#C41E3A">{{ plan.price }}</text>
              </view>
              <text v-if="plan.originalPrice > plan.price" style="font-size:12px;color:#999;text-decoration:line-through;display:block;text-align:center;margin-top:4px">¥{{ plan.originalPrice }}</text>
              <text style="font-size:12px;color:#C9A96E;display:block;text-align:center;margin-top:4px">¥{{ plan.dailyPrice }}/天</text>

              <!-- 选中指示 -->
              <view v-if="selectedPlan?.id === plan.id" style="position:absolute;top:8px;left:8px;width:20px;height:20px;border-radius:50%;background:#C9A96E;display:flex;align-items:center;justify-content:center">
                <text style="color:#fff;font-size:12px;font-weight:700">✓</text>
              </view>
            </view>
          </view>
        </view>

        <!-- ====== 会员权益 ====== -->
        <view>
          <text style="font-size:16px;font-weight:600;color:#2C2C2C;display:block;margin-bottom:12px">会员专属权益</text>
          <view style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
            <view
              v-for="benefit in data.benefits" :key="benefit.id"
              :style="{
                padding:'12px', borderRadius:'12px',
                background: benefit.levels.includes(selectedLevel) ? 'rgba(201,169,110,0.05)' : '#fff',
                border: benefit.levels.includes(selectedLevel) ? '1px solid rgba(201,169,110,0.3)' : '1px solid #E8E0D5',
                opacity: benefit.levels.includes(selectedLevel) ? 1 : 0.5
              }"
            >
              <view style="display:flex;align-items:flex-start;gap:12px">
                <view :style="{
                  width:'40px', height:'40px', borderRadius:'8px', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0,
                  background: benefit.levels.includes(selectedLevel) ? 'rgba(201,169,110,0.2)' : '#F5F1EB'
                }">
                  <text :style="{ fontSize:'20px', opacity: benefit.levels.includes(selectedLevel) ? 1 : 0.5 }">{{ benefitIconMap[benefit.icon] || '🎁' }}</text>
                </view>
                <view style="flex:1;min-width:0">
                  <text style="font-size:14px;font-weight:500;color:#2C2C2C;display:block">{{ benefit.title }}</text>
                  <text style="font-size:12px;color:#999;display:block;margin-top:2px;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical">{{ benefit.description }}</text>
                </view>
              </view>
            </view>
          </view>
        </view>

        <!-- ====== 权益对比 ====== -->
        <view>
          <text style="font-size:16px;font-weight:600;color:#2C2C2C;display:flex;align-items:center;gap:8px;margin-bottom:12px">
            <text style="font-size:16px">📈</text>
            权益对比
          </text>
          <view style="background:#fff;border-radius:12px;overflow:hidden;border:1px solid #E8E0D5">
            <!-- 表头 -->
            <view style="display:flex;border-bottom:1px solid #E8E0D5">
              <view style="flex:1;padding:12px"><text style="font-size:12px;color:#999">权益项</text></view>
              <view v-for="lvl in ['basic','pro','premium']" :key="lvl" style="flex:1;padding:12px;text-align:center">
                <text :style="{ fontSize:'12px', fontWeight:500, color: selectedLevel === lvl ? '#C41E3A' : '#2C2C2C' }">{{ levelNames[lvl] }}</text>
              </view>
            </view>
            <!-- 数据行 -->
            <view v-for="(feature, idx) in comparisonFeatures" :key="idx" :style="{ display:'flex', borderBottom: idx < comparisonFeatures.length - 1 ? '1px solid #E8E0D5' : 'none' }">
              <view style="flex:1;padding:12px"><text style="font-size:12px;color:#2C2C2C">{{ feature.name }}</text></view>
              <view v-for="lvl in ['basic','pro','premium']" :key="lvl" style="flex:1;padding:12px;text-align:center">
                <text v-if="feature[lvl] === true" style="font-size:14px;color:#22c55e">✓</text>
                <text v-else-if="feature[lvl]" style="font-size:12px;color:#C9A96E">{{ feature[lvl] }}</text>
                <text v-else style="font-size:14px;color:#D9D9D9">✗</text>
              </view>
            </view>
            <!-- CTA 行 -->
            <view style="padding:12px;text-align:center;background:rgba(201,169,110,0.05)" @click="showPaySheet = true">
              <text style="font-size:14px;font-weight:500;color:#C41E3A">立即开通会员 →</text>
            </view>
          </view>
        </view>

        <!-- ====== 用户评价 ====== -->
        <view>
          <text style="font-size:16px;font-weight:600;color:#2C2C2C;display:block;margin-bottom:12px">会员评价</text>
          <view style="display:flex;flex-direction:column;gap:12px">
            <view v-for="(review, idx) in reviews" :key="idx" style="background:#fff;border-radius:12px;padding:12px">
              <view style="display:flex;align-items:flex-start;gap:12px">
                <view style="width:40px;height:40px;border-radius:50%;background:rgba(201,169,110,0.2);display:flex;align-items:center;justify-content:center;flex-shrink:0">
                  <text style="font-size:14px;font-weight:500;color:#C9A96E">{{ review.avatar }}</text>
                </view>
                <view style="flex:1">
                  <view style="display:flex;align-items:center;justify-content:space-between">
                    <text style="font-size:14px;font-weight:500;color:#2C2C2C">{{ review.name }}</text>
                    <view style="display:flex;align-items:center;gap:2px">
                      <text v-for="i in 5" :key="i" style="font-size:12px;color:#C9A96E"></text>
                    </view>
                  </view>
                  <text style="font-size:12px;color:#999;display:block;margin-top:4px">{{ review.content }}</text>
                  <text style="font-size:12px;color:#999;display:block;margin-top:8px">已开通{{ review.days }}天</text>
                </view>
              </view>
            </view>
          </view>
        </view>

        <!-- ====== 常见问题 ====== -->
        <view>
          <text style="font-size:16px;font-weight:600;color:#2C2C2C;display:block;margin-bottom:12px">常见问题</text>
          <view style="background:#fff;border-radius:12px;overflow:hidden">
            <view v-for="(faq, idx) in faqs" :key="idx" :style="{ padding:'12px', borderTop: idx > 0 ? '1px solid #E8E0D5' : 'none' }">
              <text style="font-size:14px;font-weight:500;color:#2C2C2C;display:block">{{ faq.q }}</text>
              <text style="font-size:12px;color:#999;display:block;margin-top:4px">{{ faq.a }}</text>
            </view>
          </view>
        </view>
      </view>
    </block>

    <!-- ====== 底部购买栏 ====== -->
    <view v-if="data && selectedPlan" style="position:fixed;bottom:0;left:0;right:0;background:rgba(250,248,245,0.95);backdrop-filter:blur(12px);border-top:1px solid #E8E0D5;z-index:50;padding-bottom:env(safe-area-inset-bottom)">
      <view style="display:flex;align-items:center;justify-content:space-between;padding:12px 16px;max-width:600px;margin:0 auto">
        <view>
          <view style="display:flex;align-items:baseline;gap:4px">
            <text style="font-size:14px;color:#999">¥</text>
            <text style="font-size:30px;font-weight:700;color:#C41E3A">{{ selectedPlan.price }}</text>
            <text style="font-size:14px;color:#999">/{{ selectedPlan.durationName }}</text>
          </view>
          <text style="font-size:12px;color:#999;text-decoration:line-through;display:block">原价 ¥{{ selectedPlan.originalPrice }}</text>
        </view>
        <view
          style="padding:0 32px;height:48px;border-radius:999px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:14px;font-weight:500;background:linear-gradient(90deg,#C9A96E,#C41E3A);box-shadow:0 4px 20px rgba(201,169,110,0.3);cursor:pointer"
          @click="showPaySheet = true"
        >
          <text>{{ data.status.level === selectedLevel && !data.status.isExpired ? '续费' : '立即开通' }}</text>
        </view>
      </view>
    </view>

    <!-- ====== 支付方式选择弹窗 ====== -->
    <view v-if="showPaySheet" style="position:fixed;inset:0;z-index:1000">
      <!-- 蒙层 -->
      <view style="position:absolute;inset:0;background:rgba(0,0,0,0.5)" @click="showPaySheet = false" />
      <!-- 面板 -->
      <view style="position:absolute;bottom:0;left:0;right:0;background:#fff;border-radius:16px 16px 0 0;animation:slideUp 0.3s ease-out">
        <view style="display:flex;align-items:center;justify-content:space-between;padding:16px;border-bottom:1px solid #E8E0D5">
          <text style="font-size:16px;font-weight:600;color:#2C2C2C">选择支付方式</text>
          <text style="font-size:20px;color:#999;cursor:pointer" @click="showPaySheet = false">✕</text>
        </view>
        <view style="padding:16px;padding-bottom:calc(16px + env(safe-area-inset-bottom))">
          <!-- 订单摘要 -->
          <view v-if="selectedPlan" style="text-align:center;margin-bottom:16px;padding-bottom:16px;border-bottom:1px solid #E8E0D5">
            <text style="font-size:14px;color:#999;display:block">{{ selectedPlan.levelName }} · {{ selectedPlan.durationName }}</text>
            <text style="font-size:30px;font-weight:700;color:#C41E3A;display:block;margin-top:4px">
              <text style="font-size:18px">¥</text>{{ selectedPlan.price }}
            </text>
          </view>

          <!-- 支付方式 -->
          <view style="display:flex;flex-direction:column;gap:12px">
            <view
              v-for="method in paymentMethods" :key="method.value"
              :style="{
                display:'flex', alignItems:'center', gap:'12px', padding:'12px', borderRadius:'12px', cursor:'pointer',
                border: paymentMethod === method.value ? '1px solid #C41E3A' : '1px solid #E8E0D5',
                background: paymentMethod === method.value ? 'rgba(196,30,58,0.05)' : '#fff'
              }"
              @click="paymentMethod = method.value"
            >
              <!-- 单选圆点 -->
              <view :style="{
                width:'20px', height:'20px', borderRadius:'50%', border:'2px solid',
                display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0,
                borderColor: paymentMethod === method.value ? '#C41E3A' : '#999'
              }">
                <view v-if="paymentMethod === method.value" style="width:12px;height:12px;border-radius:50%;background:#C41E3A" />
              </view>
              <!-- 图标 --><view :style="{ width:'32px', height:'32px', borderRadius:'8px', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0, background: method.bg }"><text style="color:#fff;font-size:12px;font-weight:700">{{ method.label[0] }}</text></view>
              <text style="font-size:14px;color:#2C2C2C">{{ method.label }}</text>
            </view>
          </view>

          <!-- 确认按钮 -->
          <view
            :style="{
              width:'100%', marginTop:'24px', height:'48px', borderRadius:'12px',
              display:'flex', alignItems:'center', justifyContent:'center',
              background: purchasing ? '#ccc' : '#C41E3A',
              color:'#fff', fontSize:'14px', fontWeight:500, cursor:'pointer'
            }"
            @click="handlePurchase"
          >
            <text>{{ purchasing ? '处理中...' : '确认支付' }}</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

/* ---- 类型定义 ---- */
type VipLevel = 'none' | 'basic' | 'pro' | 'premium'

interface VipPlan {
  id: string
  levelName: string
  durationName: string
  price: number
  originalPrice: number
  dailyPrice: number
  popular: boolean
  discount: string
}

interface VipPlanGroup {
  level: VipLevel
  levelName: string
  description: string
  plans: VipPlan[]
}

interface VipStatus {
  level: VipLevel
  levelName: string
  isExpired: boolean
  expireAt: string
  daysLeft: number
  points: number
  autoRenew: boolean
}

interface VipBenefit {
  id: string
  icon: string
  title: string
  description: string
  levels: VipLevel[]
}

interface VipCenterData {
  status: VipStatus
  planGroups: VipPlanGroup[]
  benefits: VipBenefit[]
}

/* ---- 状态 ---- */
const data = ref<VipCenterData | null>(null)
const loading = ref(true)
const error = ref<string | null>(null)
const selectedLevel = ref<VipLevel>('pro')
const selectedPlan = ref<VipPlan | null>(null)
const showPaySheet = ref(false)
const paymentMethod = ref<'wechat' | 'alipay' | 'balance'>('wechat')
const purchasing = ref(false)
const autoRenewLoading = ref(false)

/* ---- 常量 ---- */
const levelColors: Record<string, { bg: string }> = {
  none:  { bg: '#D9D9D9' },
  basic: { bg: '#C9A96E' },
  pro:   { bg: '#8B5CF6' },
  premium: { bg: 'linear-gradient(90deg,#C9A96E,#F97316)' },
}

const levelNames: Record<string, string> = {
  basic: '基础', pro: '专业', premium: '至尊',
}

const benefitIconMap: Record<string, string> = {
  crown: '👑',
  video: '',
  download: '',
  gift: '🎁',
  book: '',
  calculator: '⚡',
  'customer-service': '🛡️',
  discount: '️',
}

const paymentMethods = [
  { value: 'wechat' as const, label: '微信支付', bg: '#22c55e' },
  { value: 'alipay' as const, label: '支付宝', bg: '#3b82f6' },
  { value: 'balance' as const, label: '余额支付', bg: '#f59e0b' },
]

const reviews = [
  { name: '易*明', avatar: '易', content: '开通年度会员后，学习效率提升很多，课程质量很高！', days: 128 },
  { name: '张*华', avatar: '张', content: 'AI智能体太好用了，排盘解读很专业，物超所值。', days: 56 },
]

const faqs = [
  { q: '开通后可以退款吗？', a: '会员服务一经开通，暂不支持退款，请确认后购买。' },
  { q: '会员可以多设备登录吗？', a: '同一账号最多支持3台设备同时登录。' },
  { q: '会员到期后权益还在吗？', a: '到期后会员权益将失效，但已下载的内容可继续保留。' },
]

const comparisonFeatures = [
  { name: '精品课程', basic: true, pro: true, premium: true },
  { name: '离线下载', basic: true, pro: true, premium: true },
  { name: 'AI智能体', basic: false, pro: true, premium: true },
  { name: '专业排盘', basic: false, pro: true, premium: true },
  { name: '古籍文库', basic: false, pro: true, premium: true },
  { name: '专属福利', basic: false, pro: false, premium: true },
  { name: '课程折扣', basic: '9折', pro: '8折', premium: '7折' },
]

/* ---- 计算属性 ---- */
const currentPlanGroup = computed(() => data.value?.planGroups.find(g => g.level === selectedLevel.value))

/* ---- Mock 数据 ---- */
const mockVipCenterData = (): VipCenterData => ({
  status: {
    level: 'none',
    levelName: '热卜国学VIP',
    isExpired: false,
    expireAt: '2027-06-10',
    daysLeft: 365,
    points: 1280,
    autoRenew: false,
  },
  planGroups: [
    {
      level: 'basic',
      levelName: '基础会员',
      description: '适合入门学习，享受基础权益',
      plans: [
        { id: 'b1', levelName: '基础会员', durationName: '月卡', price: 28, originalPrice: 48, dailyPrice: 0.93, popular: false, discount: '省20' },
        { id: 'b2', levelName: '基础会员', durationName: '季卡', price: 68, originalPrice: 128, dailyPrice: 0.76, popular: false, discount: '省60' },
        { id: 'b3', levelName: '基础会员', durationName: '年卡', price: 198, originalPrice: 398, dailyPrice: 0.54, popular: true, discount: '' },
      ],
    },
    {
      level: 'pro',
      levelName: '专业会员',
      description: '适合进阶学习，享受全部专业权益',
      plans: [
        { id: 'p1', levelName: '专业会员', durationName: '月卡', price: 68, originalPrice: 128, dailyPrice: 2.27, popular: false, discount: '省60' },
        { id: 'p2', levelName: '专业会员', durationName: '季卡', price: 168, originalPrice: 328, dailyPrice: 1.87, popular: false, discount: '省160' },
        { id: 'p3', levelName: '专业会员', durationName: '年卡', price: 398, originalPrice: 798, dailyPrice: 1.09, popular: true, discount: '' },
      ],
    },
    {
      level: 'premium',
      levelName: '至尊会员',
      description: '顶级会员，尊享全部特权',
      plans: [
        { id: 'pm1', levelName: '至尊会员', durationName: '月卡', price: 128, originalPrice: 258, dailyPrice: 4.27, popular: false, discount: '省130' },
        { id: 'pm2', levelName: '至尊会员', durationName: '季卡', price: 328, originalPrice: 658, dailyPrice: 3.64, popular: false, discount: '省330' },
        { id: 'pm3', levelName: '至尊会员', durationName: '年卡', price: 998, originalPrice: 1998, dailyPrice: 2.73, popular: true, discount: '' },
      ],
    },
  ],
  benefits: [
    { id: 'b1', icon: 'book', title: '海量课程', description: '500+精品国学课程免费学习', levels: ['basic', 'pro', 'premium'] },
    { id: 'b2', icon: 'video', title: 'AI智能体', description: '智能排盘解读，专业问答', levels: ['pro', 'premium'] },
    { id: 'b3', icon: 'download', title: '离线下载', description: '课程离线缓存，随时随地学习', levels: ['basic', 'pro', 'premium'] },
    { id: 'b4', icon: 'gift', title: '专属福利', description: '会员日专属折扣，积分翻倍', levels: ['premium'] },
    { id: 'b5', icon: 'calculator', title: '高级工具', description: '专业排盘工具，多种流派算法', levels: ['pro', 'premium'] },
    { id: 'b6', icon: 'customer-service', title: '优先客服', description: '7x24小时专属客服优先响应', levels: ['premium'] },
    { id: 'b7', icon: 'discount', title: '课程优惠', description: '购买付费课程享受会员专属折扣', levels: ['basic', 'pro', 'premium'] },
    { id: 'b8', icon: 'book', title: '古籍文库', description: '数千部古籍全文检索阅读', levels: ['pro', 'premium'] },
  ],
})

/* ---- 业务逻辑 ---- */
async function loadData() {
  loading.value = true
  error.value = null
  try {
    // 模拟 API 请求
    await new Promise(resolve => setTimeout(resolve, 600))
    const res = { code: 200, message: 'ok', data: mockVipCenterData() }
    if (res.code === 200) {
      data.value = res.data
      const defaultLevel = res.data.status.level !== 'none' ? res.data.status.level : 'pro'
      selectedLevel.value = defaultLevel
      const currentGroup = res.data.planGroups.find(g => g.level === defaultLevel)
      const popularPlan = currentGroup?.plans.find(p => p.popular)
      selectedPlan.value = popularPlan || currentGroup?.plans[0] || null
    } else {
      error.value = res.message
    }
  } catch {
    error.value = '加载失败，请稍后重试'
  } finally {
    loading.value = false
  }
}

onMounted(loadData)

function handleSelectLevel(level: VipLevel) {
  selectedLevel.value = level
  const group = data.value?.planGroups.find(g => g.level === level)
  const popularPlan = group?.plans.find(p => p.popular)
  selectedPlan.value = popularPlan || group?.plans[0] || null
}

function handleSelectPlan(plan: VipPlan) {
  selectedPlan.value = plan
}

async function handlePurchase() {
  if (!selectedPlan.value) return
  purchasing.value = true
  try {
    await new Promise(resolve => setTimeout(resolve, 1500))
    uni.showToast({ title: '购买成功', icon: 'success' })
    showPaySheet.value = false
    loadData()
  } catch {
    uni.showToast({ title: '购买失败', icon: 'error' })
  } finally {
    purchasing.value = false
  }
}

async function handleToggleAutoRenew() {
  if (autoRenewLoading.value || !data.value) return
  autoRenewLoading.value = true
  try {
    await new Promise(resolve => setTimeout(resolve, 500))
    const newVal = !data.value.status.autoRenew
    data.value = { ...data.value, status: { ...data.value.status, autoRenew: newVal } }
    uni.showToast({ title: newVal ? '已开启自动续费' : '已关闭自动续费', icon: 'success' })
  } catch {
    uni.showToast({ title: '操作失败', icon: 'error' })
  } finally {
    autoRenewLoading.value = false
  }
}

function goBack() {
  uni.navigateBack()
}

function goRecords() {
  uni.navigateTo({ url: '/pages/vip/records/index' })
}
</script>

<style scoped>
/* 样式由 Tailwind 处理 */
@keyframes slideUp {
  from { transform: translateY(100%); }
  to   { transform: translateY(0); }
}
</style>

<style>
/* 骨架屏脉冲动画 */
.skeleton-pulse {
  background: linear-gradient(90deg, #F0EBE5 25%, #E8E0D5 50%, #F0EBE5 75%);
  background-size: 200% 100%;
  animation: skeleton-shimmer 1.5s ease-in-out infinite;
}

@keyframes skeleton-shimmer {
  0%   { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
</style>
