// apps/mobile/src/pkg-merchant/content-stats/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="navbar" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="navbar-inner">
        <view class="nav-back" @tap="goBack">
          <AppIcon name="arrow-left" :size="24" color="#1f1f1f" />
        </view>
        <text class="nav-title">内容统计</text>
        <view class="nav-placeholder" />
      </view>
    </view>

    <scroll-view scroll-y class="scroll" :style="{ top: navH + 'px' }">
      <view v-if="loading" class="loading-state"><text>加载中...</text></view>
      <view v-if="error" class="error-state">
        <text>加载失败</text>
        <view @tap="retry"><text>重试</text></view>
      </view>
      <view v-if="!loading && !error">
      <!-- 数据概览 -->
      <view class="grid2">
        <view class="ov-card">
          <text class="ov-label">发布商品</text>
          <text class="ov-num">{{ stats.publishedProducts }}</text>
          <text class="ov-sub">/ {{ stats.totalProducts }}</text>
        </view>
        <view class="ov-card">
          <text class="ov-label">已发布文章</text>
          <text class="ov-num">{{ stats.publishedArticles }}</text>
        </view>
        <view class="ov-card">
          <text class="ov-label">总浏览数</text>
          <text class="ov-num">{{ formatNum(stats.totalViews) }}</text>
        </view>
        <view class="ov-card">
          <text class="ov-label">总点赞数</text>
          <text class="ov-num">{{ formatNum(stats.totalLikes) }}</text>
        </view>
      </view>

      <!-- 内容详情卡片 -->
      <view class="detail-wrap">
        <view class="card">
          <view class="card-head">
            <view class="card-head-left">
              <AppIcon name="file-text" :size="20" color="#c41e3a" />
              <text class="card-title">商品</text>
            </view>
            <text class="card-count">{{ stats.totalProducts }} 件</text>
          </view>
          <view class="grid2 inner-grid">
            <view class="inner-box">
              <text class="inner-label">已发布</text>
              <text class="inner-num">{{ stats.publishedProducts }}</text>
            </view>
            <view class="inner-box">
              <text class="inner-label">草稿</text>
              <text class="inner-num">{{ stats.draftProducts }}</text>
            </view>
          </view>
        </view>

        <view class="card">
          <view class="card-head">
            <view class="card-head-left">
              <AppIcon name="file-text" :size="20" color="#c9a96e" />
              <text class="card-title">文章</text>
            </view>
            <text class="card-count">{{ stats.publishedArticles }} 篇</text>
          </view>
          <view class="row-line">
            <text class="row-label">总阅读</text>
            <text class="row-val">{{ formatNum(stats.totalViews) }}</text>
          </view>
          <view class="row-line">
            <text class="row-label">总点赞</text>
            <text class="row-val">{{ formatNum(stats.totalLikes) }}</text>
          </view>
        </view>
      </view>

      <!-- 内容列表 -->
      <view class="list-wrap">
        <text class="section-title">内容列表</text>
        <view class="tabs">
          <view
            v-for="t in tabs"
            :key="t.value"
            class="tab"
            :class="{ 'tab-active': activeType === t.value }"
            @tap="activeType = t.value"
          >
            <text class="tab-text" :class="{ 'tab-text-active': activeType === t.value }">{{ t.label }}</text>
          </view>
        </view>

        <view v-if="filteredList.length" class="content-list">
          <view v-for="item in filteredList" :key="item.id" class="content-card">
            <view class="content-top">
              <text class="content-title">{{ item.title }}</text>
              <view class="status-badge" :style="{ color: contentStatusBadge[item.status].color, background: contentStatusBadge[item.status].bg }">
                <text class="status-text" :style="{ color: contentStatusBadge[item.status].color }">{{ item.status }}</text>
              </view>
            </view>
            <text class="content-date">{{ item.createdAt }}</text>
            <view class="content-stats">
              <view class="stat-item">
                <AppIcon name="eye" :size="13" color="#9ca3af" />
                <text class="stat-text">{{ item.views }}</text>
              </view>
              <view class="stat-item">
                <AppIcon name="thumbs-up" :size="13" color="#9ca3af" />
                <text class="stat-text">{{ item.likes }}</text>
              </view>
              <view v-if="item.sales !== undefined" class="stat-item">
                <AppIcon name="shopping-bag" :size="13" color="#9ca3af" />
                <text class="stat-text">{{ item.sales }} 件</text>
              </view>
            </view>
          </view>
        </view>
        <view v-else class="empty">
          <text class="empty-text">暂无内容</text>
        </view>
      </view>
      <view style="height: 40px" />
      </view>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'
import { merchantAdminApi, contentStatusBadge } from '@/lib/merchant-data'

const statusBarHeight = ref(20)
const navH = ref(64)
const loading = ref(true)
const error = ref(false)
const stats = ref<any>({})
const contentList = ref<any[]>([])

uni.getSystemInfo({
  success: (r) => {
    statusBarHeight.value = r.statusBarHeight || 20
    navH.value = (r.statusBarHeight || 20) + 44
  },
})

onMounted(async () => {
  try {
    await merchantAdminApi.getDashboard()
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
})

function retry() {
  error.value = false
  loading.value = true
  onMounted()
}

const activeType = ref<'all' | '商品' | '文章'>('all')
const tabs = [
  { label: '全部', value: 'all' as const },
  { label: '商品', value: '商品' as const },
  { label: '文章', value: '文章' as const },
]

const filteredList = computed(() => {
  if (activeType.value === 'all') return contentList.value
  return contentList.value.filter((c: any) => c.type === activeType.value)
})

function formatNum(n: number) {
  return n.toLocaleString('en-US')
}
</script>

<style scoped>
.page { min-height: 100vh; background: #f5f5f5; }
.navbar { position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: #fff; border-bottom: 1px solid #ededed; }
.navbar-inner { height: 44px; display: flex; align-items: center; justify-content: space-between; padding: 0 12px; }
.nav-back { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; }
.nav-title { font-size: 17px; font-weight: 600; color: #1f1f1f; }
.nav-placeholder { width: 32px; }
.scroll { position: fixed; left: 0; right: 0; bottom: 0; }

.grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; padding: 16px 16px 0; }
.ov-card { background: #fff; border-radius: 12px; padding: 16px; display: flex; flex-direction: column; align-items: center; }
.ov-label { font-size: 12px; color: #9ca3af; margin-bottom: 4px; }
.ov-num { font-size: 24px; font-weight: 700; color: #1f1f1f; }
.ov-sub { font-size: 12px; color: #9ca3af; margin-top: 2px; }

.detail-wrap { padding: 24px 16px 0; display: flex; flex-direction: column; gap: 12px; }
.card { background: #fff; border-radius: 12px; padding: 16px; }
.card-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; }
.card-head-left { display: flex; align-items: center; gap: 8px; }
.card-title { font-size: 15px; font-weight: 600; color: #1f1f1f; }
.card-count { font-size: 13px; color: #9ca3af; }
.inner-grid { padding: 0; }
.inner-box { background: #f9fafb; border-radius: 8px; padding: 8px 12px; }
.inner-label { font-size: 12px; color: #9ca3af; display: block; margin-bottom: 4px; }
.inner-num { font-size: 18px; font-weight: 700; color: #1f1f1f; }
.row-line { display: flex; align-items: center; justify-content: space-between; padding: 6px 0; }
.row-label { font-size: 13px; color: #9ca3af; }
.row-val { font-size: 14px; font-weight: 600; color: #1f1f1f; }

.list-wrap { padding: 24px 16px 0; }
.section-title { font-size: 14px; font-weight: 600; color: #1f1f1f; display: block; margin-bottom: 12px; }
.tabs { display: flex; gap: 8px; margin-bottom: 12px; }
.tab { padding: 6px 14px; border-radius: 999px; background: #ededed; }
.tab-active { background: #c41e3a; }
.tab-text { font-size: 13px; color: #4b5563; }
.tab-text-active { color: #fff; }

.content-list { display: flex; flex-direction: column; gap: 8px; }
.content-card { background: #fff; border-radius: 10px; padding: 12px; }
.content-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; margin-bottom: 4px; }
.content-title { font-size: 14px; font-weight: 500; color: #1f1f1f; flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.status-badge { padding: 1px 8px; border-radius: 6px; flex-shrink: 0; }
.status-text { font-size: 11px; }
.content-date { font-size: 12px; color: #9ca3af; }
.content-stats { display: flex; align-items: center; gap: 12px; margin-top: 8px; }
.stat-item { display: flex; align-items: center; gap: 4px; }
.stat-text { font-size: 12px; color: #9ca3af; }

.empty { background: #fff; border-radius: 12px; padding: 32px; display: flex; justify-content: center; }
.empty-text { font-size: 14px; color: #9ca3af; }

.loading-state { padding: 60px 0; display: flex; align-items: center; justify-content: center; }
.loading-state text { font-size: 14px; color: #9ca3af; }
.error-state { padding: 60px 0; display: flex; flex-direction: column; align-items: center; gap: 12px; }
.error-state text { font-size: 14px; color: #ef4444; }
.error-state view { padding: 8px 20px; background: #c41e3a; border-radius: 8px; }
.error-state view text { font-size: 14px; color: #fff; }
</style>

// app/merchant/content-stats/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, FileText, Eye, ThumbsUp, ShoppingBag } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DataState } from '@/components/data-state'
import { getContentStats, getContentList } from '@/lib/api/merchant'
import type { ContentStats, ContentItem } from '@/lib/types/merchant'

export default function ContentStatsPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [stats, setStats] = useState<ContentStats | null>(null)
  const [contents, setContents] = useState<ContentItem[]>([])
  const [activeType, setActiveType] = useState<'商品' | '文章' | null>(null)

  useEffect(() => {
    loadData()
  }, [activeType])

  const loadData = async () => {
    setLoading(true)
    setError(null)
    try {
      const [statsRes, contentRes] = await Promise.all([
        getContentStats(),
        getContentList(activeType ? (activeType === '商品' ? '商品' : '文章') : undefined, 1, 20),
      ])

      if (statsRes.code === 200) {
        setStats(statsRes.data)
      } else {
        setError('加载内容统计失败')
      }

      if (contentRes.code === 200) {
        setContents(contentRes.data.list)
      }
    } catch {
      setError('加载失败，请重试')
    } finally {
      setLoading(false)
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case '已发布':
        return 'bg-green-100 text-green-800'
      case '草稿':
        return 'bg-gray-100 text-gray-800'
      case '下架':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <button onClick={() => router.back()} className="p-1">
            <ArrowLeft className="w-6 h-6 text-foreground" />
          </button>
          <h1 className="text-lg font-semibold text-foreground">内容统计</h1>
          <div className="w-8" />
        </div>
      </div>

      <DataState
        loading={loading}
        error={error}
        empty={!stats}
        onRetry={loadData}
        skeleton={
          <div className="p-4 space-y-4">
            <div className="grid grid-cols-2 gap-3">
              {[1, 2, 3, 4].map(i => (
                <div key={i} className="h-24 bg-gray-200 rounded-xl animate-pulse" />
              ))}
            </div>
          </div>
        }
      >
        {stats && (
          <div className="pb-20">
            {/* 数据概览 */}
            <div className="mx-4 mt-4 grid grid-cols-2 gap-3">
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">发布商品</div>
                <div className="text-2xl font-bold text-foreground">{stats.publishedProducts}</div>
                <div className="text-xs text-muted-foreground mt-1">/ {stats.totalProducts}</div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">已发布文章</div>
                <div className="text-2xl font-bold text-foreground">{stats.publishedArticles}</div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">总浏览数</div>
                <div className="text-2xl font-bold text-foreground">{stats.totalViews.toLocaleString()}</div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">总点赞数</div>
                <div className="text-2xl font-bold text-foreground">{stats.totalLikes.toLocaleString()}</div>
              </Card>
            </div>

            {/* 内容详情卡片 */}
            <div className="mx-4 mt-6 grid grid-cols-1 gap-3">
              <Card className="p-4">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-primary" />
                    <span className="font-semibold text-foreground">商品</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{stats.totalProducts} 件</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="p-2 bg-muted/50 rounded-lg">
                    <div className="text-xs text-muted-foreground mb-1">已发布</div>
                    <div className="text-lg font-bold text-foreground">{stats.publishedProducts}</div>
                  </div>
                  <div className="p-2 bg-muted/50 rounded-lg">
                    <div className="text-xs text-muted-foreground mb-1">草稿</div>
                    <div className="text-lg font-bold text-foreground">{stats.draftProducts}</div>
                  </div>
                </div>
              </Card>

              <Card className="p-4">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-gold" />
                    <span className="font-semibold text-foreground">文章</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{stats.publishedArticles} 篇</span>
                </div>
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">总阅读</span>
                    <span className="font-semibold text-foreground">{stats.totalViews.toLocaleString()}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">总点赞</span>
                    <span className="font-semibold text-foreground">{stats.totalLikes.toLocaleString()}</span>
                  </div>
                </div>
              </Card>
            </div>

            {/* 内容列表 */}
            <div className="mx-4 mt-6">
              <h3 className="text-sm font-semibold text-foreground mb-3">内容列表</h3>
              <div className="flex gap-2 mb-3 pb-2 overflow-x-auto">
                <button
                  onClick={() => setActiveType(null)}
                  className={`px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors ${
                    activeType === null
                      ? 'bg-primary text-white'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  全部
                </button>
                <button
                  onClick={() => setActiveType('商品')}
                  className={`px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors ${
                    activeType === '商品'
                      ? 'bg-primary text-white'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  商品
                </button>
                <button
                  onClick={() => setActiveType('文章')}
                  className={`px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors ${
                    activeType === '文章'
                      ? 'bg-primary text-white'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  文章
                </button>
              </div>

              {contents.length > 0 ? (
                <div className="space-y-2">
                  {contents.map(item => (
                    <Card key={item.id} className="p-3">
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="text-sm font-medium text-foreground line-clamp-1">
                              {item.title}
                            </span>
                            <Badge variant="secondary" className={`text-xs ${getStatusColor(item.status)}`}>
                              {item.status}
                            </Badge>
                          </div>
                          <div className="text-xs text-muted-foreground">{item.createdAt}</div>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 text-xs">
                        <span className="flex items-center gap-1 text-muted-foreground">
                          <Eye className="w-3 h-3" /> {item.views}
                        </span>
                        <span className="flex items-center gap-1 text-muted-foreground">
                          <ThumbsUp className="w-3 h-3" /> {item.likes}
                        </span>
                        {item.sales !== undefined && (
                          <span className="flex items-center gap-1 text-muted-foreground">
                            <ShoppingBag className="w-3 h-3" /> {item.sales} 件
                          </span>
                        )}
                      </div>
                    </Card>
                  ))}
                </div>
              ) : (
                <Card className="p-8 text-center">
                  <div className="text-muted-foreground">暂无内容</div>
                </Card>
              )}
            </div>
          </div>
        )}
      </DataState>
    </div>
  )
}
