// apps/mobile/.backup_vue3_converted/pages/merchant/content-stats/index.vue
<template>
  <view class="min-h-screen bg-background">
    <!-- 顶部导航 -->
    <view class="sticky top-0 z-10 bg-white border-b border-border">
      <view class="flex items-center justify-between px-4 py-3">
        <view @click="goBack" class="p-1">
          <text class="text-2xl text-foreground">←</text>
        </view>
        <text class="text-lg font-semibold text-foreground">内容统计</text>
        <view class="w-8" />
      </view>
    </view>

    <!-- 加载骨架 -->
    <view v-if="loading" class="p-4 space-y-4">
      <view class="grid grid-cols-2 gap-3">
        <view v-for="i in 4" :key="i" class="h-24 bg-gray-200 rounded-xl animate-pulse" />
      </view>
    </view>

    <!-- 错误状态 -->
    <view v-else-if="error" class="p-4">
      <view class="bg-white rounded-2xl p-8 text-center">
        <text class="text-4xl block mb-3">😵</text>
        <text class="text-muted-foreground block mb-4">{{ error }}</text>
        <view @click="loadData" class="inline-block px-6 py-2.5 bg-primary text-white rounded-xl text-sm font-medium">重新加载</view>
      </view>
    </view>

    <scroll-view v-else scroll-y class="flex-1 pb-20">
      <!-- 数据概览 -->
      <view class="mx-4 mt-4 grid grid-cols-2 gap-3">
        <view class="bg-white rounded-xl p-4 text-center shadow-sm">
          <text class="text-xs text-muted-foreground mb-1 block">发布商品</text>
          <text class="text-2xl font-bold text-foreground block">{{ stats.publishedProducts }}</text>
          <text class="text-xs text-muted-foreground mt-1 block">/ {{ stats.totalProducts }}</text>
        </view>
        <view class="bg-white rounded-xl p-4 text-center shadow-sm">
          <text class="text-xs text-muted-foreground mb-1 block">已发布文章</text>
          <text class="text-2xl font-bold text-foreground block">{{ stats.publishedArticles }}</text>
        </view>
        <view class="bg-white rounded-xl p-4 text-center shadow-sm">
          <text class="text-xs text-muted-foreground mb-1 block">总浏览数</text>
          <text class="text-2xl font-bold text-foreground block">{{ stats.totalViews.toLocaleString() }}</text>
        </view>
        <view class="bg-white rounded-xl p-4 text-center shadow-sm">
          <text class="text-xs text-muted-foreground mb-1 block">总点赞数</text>
          <text class="text-2xl font-bold text-foreground block">{{ stats.totalLikes.toLocaleString() }}</text>
        </view>
      </view>

      <!-- 内容详情 -->
      <view class="mx-4 mt-6 space-y-3">
        <view class="bg-white rounded-xl p-4 shadow-sm">
          <view class="flex items-center justify-between mb-4">
            <view class="flex items-center gap-2">
              <text class="text-lg text-primary"></text>
              <text class="font-semibold">商品</text>
            </view>
            <text class="text-sm text-muted-foreground">{{ stats.totalProducts }} 件</text>
          </view>
          <view class="grid grid-cols-2 gap-2">
            <view class="p-2 bg-background rounded-lg">
              <text class="text-xs text-muted-foreground mb-1 block">已发布</text>
              <text class="text-lg font-bold text-foreground block">{{ stats.publishedProducts }}</text>
            </view>
            <view class="p-2 bg-background rounded-lg">
              <text class="text-xs text-muted-foreground mb-1 block">草稿</text>
              <text class="text-lg font-bold text-foreground block">{{ stats.draftProducts }}</text>
            </view>
          </view>
        </view>

        <view class="bg-white rounded-xl p-4 shadow-sm">
          <view class="flex items-center justify-between mb-4">
            <view class="flex items-center gap-2">
              <text class="text-lg text-accent"></text>
              <text class="font-semibold">文章</text>
            </view>
            <text class="text-sm text-muted-foreground">{{ stats.publishedArticles }} 篇</text>
          </view>
          <view class="space-y-2">
            <view class="flex items-center justify-between">
              <text class="text-sm text-muted-foreground">总阅读</text>
              <text class="font-semibold">{{ stats.totalViews.toLocaleString() }}</text>
            </view>
            <view class="flex items-center justify-between">
              <text class="text-sm text-muted-foreground">总点赞</text>
              <text class="font-semibold">{{ stats.totalLikes.toLocaleString() }}</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 内容列表 -->
      <view class="mx-4 mt-6">
        <text class="text-sm font-semibold text-foreground mb-3 block">内容列表</text>
        <view class="flex gap-2 mb-3 overflow-x-auto">
          <view v-for="t in typeFilters" :key="String(t.key)" @click="activeType = t.key" :class="['px-3 py-1.5 rounded-full text-sm whitespace-nowrap', activeType === t.key ? 'bg-primary text-white' : 'bg-background text-ink-soft']">
            <text>{{ t.label }}</text>
          </view>
        </view>

        <view v-if="contents.length > 0" class="space-y-2">
          <view v-for="item in contents" :key="item.id" class="bg-white rounded-xl p-3 shadow-sm">
            <view class="flex items-start justify-between mb-2">
              <view class="flex-1">
                <view class="flex items-center gap-2 mb-1">
                  <text class="text-sm font-medium text-foreground line-clamp-1">{{ item.title }}</text>
                  <text :class="['px-1.5 py-0.5 rounded text-xs', getStatusColor(item.status)]">{{ item.status }}</text>
                </view>
                <text class="text-xs text-muted-foreground">{{ item.createdAt }}</text>
              </view>
            </view>
            <view class="flex items-center gap-3 text-xs text-muted-foreground">
              <text> {{ item.views }}</text>
              <text> {{ item.likes }}</text>
              <text v-if="item.sales !== undefined"> {{ item.sales }} 件</text>
            </view>
          </view>
        </view>
        <view v-else class="bg-white rounded-2xl p-8 text-center">
          <text class="text-muted-foreground">暂无内容</text>
        </view>
      </view>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'

const typeFilters = [
  { key: null as null | string, label: '全部' },
  { key: '商品' as null | string, label: '商品' },
  { key: '文章' as null | string, label: '文章' },
]

const loading = ref(true)
const error = ref<string | null>(null)
const activeType = ref<null | string>(null)

const stats = ref({
  publishedProducts: 0,
  totalProducts: 0,
  publishedArticles: 0,
  draftProducts: 0,
  totalViews: 0,
  totalLikes: 0,
})

const contents = ref<{ id: string; title: string; status: string; views: number; likes: number; sales?: number; createdAt: string }[]>([])

function getStatusColor(status: string) {
  switch (status) {
    case '已发布': return 'bg-green-100 text-green-800'
    case '草稿': return 'bg-gray-100 text-gray-800'
    case '下架': return 'bg-red-100 text-red-800'
    default: return 'bg-gray-100 text-gray-800'
  }
}

async function loadData() {
  loading.value = true
  error.value = null
  try {
    // 模拟 API 请求
    await new Promise(resolve => setTimeout(resolve, 600))
    const filterType = activeType.value
    // 模拟根据筛选返回不同数据
    let filteredContents = [
      { id: '1', title: '《渊海子平》命理经典解读', status: '已发布', views: 2340, likes: 156, sales: 45, createdAt: '2024-01-15' },
      { id: '2', title: '紫微斗数入门指南', status: '草稿', views: 0, likes: 0, createdAt: '2024-01-14' },
      { id: '3', title: '八字合婚详解服务介绍', status: '已发布', views: 1890, likes: 98, sales: 12, createdAt: '2024-01-12' },
    ]
    if (filterType === '商品') {
      filteredContents = filteredContents.filter(item => item.sales !== undefined)
    } else if (filterType === '文章') {
      filteredContents = filteredContents.filter(item => item.sales === undefined)
    }
    stats.value = {
      publishedProducts: 128,
      totalProducts: 156,
      publishedArticles: 45,
      draftProducts: 28,
      totalViews: 12560,
      totalLikes: 890,
    }
    contents.value = filteredContents
  } catch {
    error.value = '加载失败，请重试'
  } finally {
    loading.value = false
  }
}

watch(activeType, () => { loadData() })

onMounted(() => { loadData() })

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
/* 样式由 Tailwind 处理 */
</style>

// app/merchant/content-stats/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, FileText, Eye, ThumbsUp, ShoppingBag } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DataState } from '@/components/data-state'
import { getContentStats, getContentList } from '@/lib/api/merchant'
import type { ContentStats, ContentItem } from '@/lib/types/merchant'

export default function ContentStatsPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [stats, setStats] = useState<ContentStats | null>(null)
  const [contents, setContents] = useState<ContentItem[]>([])
  const [activeType, setActiveType] = useState<'商品' | '文章' | null>(null)

  useEffect(() => {
    loadData()
  }, [activeType])

  const loadData = async () => {
    setLoading(true)
    setError(null)
    try {
      const [statsRes, contentRes] = await Promise.all([
        getContentStats(),
        getContentList(activeType ? (activeType === '商品' ? '商品' : '文章') : undefined, 1, 20),
      ])

      if (statsRes.code === 200) {
        setStats(statsRes.data)
      } else {
        setError('加载内容统计失败')
      }

      if (contentRes.code === 200) {
        setContents(contentRes.data.list)
      }
    } catch {
      setError('加载失败，请重试')
    } finally {
      setLoading(false)
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case '已发布':
        return 'bg-green-100 text-green-800'
      case '草稿':
        return 'bg-gray-100 text-gray-800'
      case '下架':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-10 bg-background border-b border-border">
        <div className="flex items-center justify-between px-4 py-3">
          <button onClick={() => router.back()} className="p-1">
            <ArrowLeft className="w-6 h-6 text-foreground" />
          </button>
          <h1 className="text-lg font-semibold text-foreground">内容统计</h1>
          <div className="w-8" />
        </div>
      </div>

      <DataState
        loading={loading}
        error={error}
        empty={!stats}
        onRetry={loadData}
        skeleton={
          <div className="p-4 space-y-4">
            <div className="grid grid-cols-2 gap-3">
              {[1, 2, 3, 4].map(i => (
                <div key={i} className="h-24 bg-gray-200 rounded-xl animate-pulse" />
              ))}
            </div>
          </div>
        }
      >
        {stats && (
          <div className="pb-20">
            {/* 数据概览 */}
            <div className="mx-4 mt-4 grid grid-cols-2 gap-3">
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">发布商品</div>
                <div className="text-2xl font-bold text-foreground">{stats.publishedProducts}</div>
                <div className="text-xs text-muted-foreground mt-1">/ {stats.totalProducts}</div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">已发布文章</div>
                <div className="text-2xl font-bold text-foreground">{stats.publishedArticles}</div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">总浏览数</div>
                <div className="text-2xl font-bold text-foreground">{stats.totalViews.toLocaleString()}</div>
              </Card>
              <Card className="p-4 text-center">
                <div className="text-xs text-muted-foreground mb-1">总点赞数</div>
                <div className="text-2xl font-bold text-foreground">{stats.totalLikes.toLocaleString()}</div>
              </Card>
            </div>

            {/* 内容详情卡片 */}
            <div className="mx-4 mt-6 grid grid-cols-1 gap-3">
              <Card className="p-4">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-primary" />
                    <span className="font-semibold text-foreground">商品</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{stats.totalProducts} 件</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="p-2 bg-muted/50 rounded-lg">
                    <div className="text-xs text-muted-foreground mb-1">已发布</div>
                    <div className="text-lg font-bold text-foreground">{stats.publishedProducts}</div>
                  </div>
                  <div className="p-2 bg-muted/50 rounded-lg">
                    <div className="text-xs text-muted-foreground mb-1">草稿</div>
                    <div className="text-lg font-bold text-foreground">{stats.draftProducts}</div>
                  </div>
                </div>
              </Card>

              <Card className="p-4">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-gold" />
                    <span className="font-semibold text-foreground">文章</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{stats.publishedArticles} 篇</span>
                </div>
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">总阅读</span>
                    <span className="font-semibold text-foreground">{stats.totalViews.toLocaleString()}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">总点赞</span>
                    <span className="font-semibold text-foreground">{stats.totalLikes.toLocaleString()}</span>
                  </div>
                </div>
              </Card>
            </div>

            {/* 内容列表 */}
            <div className="mx-4 mt-6">
              <h3 className="text-sm font-semibold text-foreground mb-3">内容列表</h3>
              <div className="flex gap-2 mb-3 pb-2 overflow-x-auto">
                <button
                  onClick={() => setActiveType(null)}
                  className={`px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors ${
                    activeType === null
                      ? 'bg-primary text-white'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  全部
                </button>
                <button
                  onClick={() => setActiveType('商品')}
                  className={`px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors ${
                    activeType === '商品'
                      ? 'bg-primary text-white'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  商品
                </button>
                <button
                  onClick={() => setActiveType('文章')}
                  className={`px-3 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors ${
                    activeType === '文章'
                      ? 'bg-primary text-white'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  文章
                </button>
              </div>

              {contents.length > 0 ? (
                <div className="space-y-2">
                  {contents.map(item => (
                    <Card key={item.id} className="p-3">
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="text-sm font-medium text-foreground line-clamp-1">
                              {item.title}
                            </span>
                            <Badge variant="secondary" className={`text-xs ${getStatusColor(item.status)}`}>
                              {item.status}
                            </Badge>
                          </div>
                          <div className="text-xs text-muted-foreground">{item.createdAt}</div>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 text-xs">
                        <span className="flex items-center gap-1 text-muted-foreground">
                          <Eye className="w-3 h-3" /> {item.views}
                        </span>
                        <span className="flex items-center gap-1 text-muted-foreground">
                          <ThumbsUp className="w-3 h-3" /> {item.likes}
                        </span>
                        {item.sales !== undefined && (
                          <span className="flex items-center gap-1 text-muted-foreground">
                            <ShoppingBag className="w-3 h-3" /> {item.sales} 件
                          </span>
                        )}
                      </div>
                    </Card>
                  ))}
                </div>
              ) : (
                <Card className="p-8 text-center">
                  <div className="text-muted-foreground">暂无内容</div>
                </Card>
              )}
            </div>
          </div>
        )}
      </DataState>
    </div>
  )
}
