// app/circles/[id]/invite-codes/page.tsx
"use client"

import { useState, useEffect } from "react"
import { useParams, useRouter } from "next/navigation"
import { ArrowLeft, Plus, Copy, Share2, MoreHorizontal, Ban, Trash2, Check, Users, Gift, Clock, X } from "lucide-react"
import { cn } from "@/lib/utils"

// Mock数据
const mockStats = {
  totalInvited: 156,
  usedCodes: 12,
  pendingCodes: 5,
  thisWeek: 23,
}

const mockInviteCodes = [
  {
    id: "1",
    code: "GUOXUE2024A",
    maxUses: 10,
    usedCount: 8,
    status: "active" as const,
    createdAt: "2024-01-15T10:00:00Z",
    usedBy: [
      { id: "1", name: "张三", avatar: "/placeholder.svg?height=32&width=32", usedAt: "2024-01-16" },
      { id: "2", name: "李四", avatar: "/placeholder.svg?height=32&width=32", usedAt: "2024-01-17" },
    ],
  },
  {
    id: "2",
    code: "GUOXUE2024B",
    maxUses: 5,
    usedCount: 5,
    status: "expired" as const,
    createdAt: "2024-01-10T10:00:00Z",
    expiresAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "3",
    code: "VIP888",
    maxUses: 100,
    usedCount: 45,
    status: "active" as const,
    createdAt: "2024-01-01T10:00:00Z",
  },
  {
    id: "4",
    code: "TEST123",
    maxUses: 3,
    usedCount: 1,
    status: "disabled" as const,
    createdAt: "2024-01-05T10:00:00Z",
  },
]

interface InviteCode {
  id: string
  code: string
  maxUses: number
  usedCount: number
  status: "active" | "disabled" | "expired"
  createdAt: string
  expiresAt?: string
  usedBy?: { id: string; name: string; avatar: string; usedAt: string }[]
}

// 骨架屏
function Skeleton() {
  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      <div className="h-14 bg-white" />
      <div className="p-4 space-y-4">
        <div className="grid grid-cols-2 gap-3">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-20 bg-white rounded-xl animate-pulse" />
          ))}
        </div>
        <div className="space-y-3">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-32 bg-white rounded-xl animate-pulse" />
          ))}
        </div>
      </div>
    </div>
  )
}

export default function InviteCodesPage() {
  const params = useParams()
  const router = useRouter()
  const circleId = params.id as string

  const [isLoading, setIsLoading] = useState(true)
  const [stats, setStats] = useState(mockStats)
  const [inviteCodes, setInviteCodes] = useState<InviteCode[]>([])
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [newCodeMaxUses, setNewCodeMaxUses] = useState(10)
  const [creating, setCreating] = useState(false)
  const [expandedCode, setExpandedCode] = useState<string | null>(null)
  const [activeMenu, setActiveMenu] = useState<string | null>(null)
  const [copiedCode, setCopiedCode] = useState<string | null>(null)

  useEffect(() => {
    const timer = setTimeout(() => {
      setInviteCodes(mockInviteCodes)
      setIsLoading(false)
    }, 800)
    return () => clearTimeout(timer)
  }, [])

  const handleCreateCode = async () => {
    setCreating(true)
    // 模拟API调用
    await new Promise(resolve => setTimeout(resolve, 1000))
    const newCode: InviteCode = {
      id: Date.now().toString(),
      code: `NEW${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
      maxUses: newCodeMaxUses,
      usedCount: 0,
      status: "active",
      createdAt: new Date().toISOString(),
    }
    setInviteCodes([newCode, ...inviteCodes])
    setStats({ ...stats, pendingCodes: stats.pendingCodes + 1 })
    setShowCreateModal(false)
    setCreating(false)
  }

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code)
    setCopiedCode(code)
    setTimeout(() => setCopiedCode(null), 2000)
  }

  const handleShareCode = (code: string) => {
    const shareUrl = `${window.location.origin}/circles/${circleId}/join?code=${code}`
    if (navigator.share) {
      navigator.share({ title: "加入圈子", text: `使用邀请码 ${code} 加入圈子`, url: shareUrl })
    } else {
      navigator.clipboard.writeText(shareUrl)
      setCopiedCode(code)
      setTimeout(() => setCopiedCode(null), 2000)
    }
  }

  const handleDisableCode = (codeId: string) => {
    setInviteCodes(inviteCodes.map(c => 
      c.id === codeId ? { ...c, status: "disabled" as const } : c
    ))
    setActiveMenu(null)
  }

  const handleDeleteCode = (codeId: string) => {
    setInviteCodes(inviteCodes.filter(c => c.id !== codeId))
    setActiveMenu(null)
  }

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr)
    return `${date.getMonth() + 1}/${date.getDate()}`
  }

  if (isLoading) return <Skeleton />

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-24">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-20 bg-white border-b border-[#E8E3DB]">
        <div className="flex items-center justify-between h-14 px-4">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ArrowLeft className="w-5 h-5 text-[#2C2C2C]" />
          </button>
          <h1 className="font-semibold text-[#2C2C2C]">邀请码管理</h1>
          <button
            onClick={() => setShowCreateModal(true)}
            className="p-2 -mr-2 text-[#C41E3A]"
          >
            <Plus className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* 统计卡片 */}
      <div className="p-4">
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-gradient-to-br from-[#C41E3A] to-[#A01830] rounded-xl p-4 text-white">
            <div className="flex items-center gap-2 mb-2">
              <Users className="w-4 h-4 opacity-80" />
              <span className="text-sm opacity-80">总邀请人数</span>
            </div>
            <div className="text-2xl font-bold">{stats.totalInvited}</div>
          </div>
          <div className="bg-white rounded-xl p-4 shadow-sm">
            <div className="flex items-center gap-2 mb-2">
              <Gift className="w-4 h-4 text-[#C9A96E]" />
              <span className="text-sm text-[#666666]">本周新增</span>
            </div>
            <div className="text-2xl font-bold text-[#2C2C2C]">{stats.thisWeek}</div>
          </div>
          <div className="bg-white rounded-xl p-4 shadow-sm">
            <div className="flex items-center gap-2 mb-2">
              <Check className="w-4 h-4 text-green-500" />
              <span className="text-sm text-[#666666]">已使用码</span>
            </div>
            <div className="text-2xl font-bold text-[#2C2C2C]">{stats.usedCodes}</div>
          </div>
          <div className="bg-white rounded-xl p-4 shadow-sm">
            <div className="flex items-center gap-2 mb-2">
              <Clock className="w-4 h-4 text-[#C41E3A]" />
              <span className="text-sm text-[#666666]">待使用码</span>
            </div>
            <div className="text-2xl font-bold text-[#2C2C2C]">{stats.pendingCodes}</div>
          </div>
        </div>
      </div>

      {/* 邀请码列表 */}
      <div className="px-4 space-y-3">
        <h2 className="text-sm font-medium text-[#666666]">邀请码列表</h2>
        
        {inviteCodes.length === 0 ? (
          <div className="bg-white rounded-xl p-8 text-center">
            <div className="w-16 h-16 rounded-full bg-[#F5F0E8] flex items-center justify-center mx-auto mb-4">
              <Gift className="w-8 h-8 text-[#999999]" />
            </div>
            <p className="text-[#666666] mb-4">还没有创建邀请码</p>
            <button
              onClick={() => setShowCreateModal(true)}
              className="px-6 py-2 bg-[#C41E3A] text-white rounded-full text-sm"
            >
              创建邀请码
            </button>
          </div>
        ) : (
          inviteCodes.map(code => (
            <div
              key={code.id}
              className={cn(
                "bg-white rounded-xl overflow-hidden shadow-sm",
                code.status === "disabled" && "opacity-60"
              )}
            >
              {/* 邀请码头部 */}
              <div className="p-4">
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-lg text-[#2C2C2C]">{code.code}</span>
                      <span className={cn(
                        "px-2 py-0.5 rounded text-xs",
                        code.status === "active" && "bg-green-100 text-green-600",
                        code.status === "disabled" && "bg-gray-100 text-gray-500",
                        code.status === "expired" && "bg-orange-100 text-orange-600"
                      )}>
                        {code.status === "active" ? "有效" : code.status === "disabled" ? "已禁用" : "已过期"}
                      </span>
                    </div>
                    <p className="text-sm text-[#999999] mt-1">
                      创建于 {formatDate(code.createdAt)}
                      {code.expiresAt && ` · 过期于 ${formatDate(code.expiresAt)}`}
                    </p>
                  </div>
                  
                  <div className="relative">
                    <button
                      onClick={() => setActiveMenu(activeMenu === code.id ? null : code.id)}
                      className="p-2 hover:bg-[#F5F0E8] rounded-lg"
                    >
                      <MoreHorizontal className="w-5 h-5 text-[#666666]" />
                    </button>
                    
                    {activeMenu === code.id && (
                      <div className="absolute right-0 top-full mt-1 bg-white rounded-lg shadow-xl border border-[#E8E3DB] py-1 z-10 min-w-32">
                        {code.status === "active" && (
                          <button
                            onClick={() => handleDisableCode(code.id)}
                            className="w-full px-4 py-2 text-left text-sm text-[#666666] hover:bg-[#F5F0E8] flex items-center gap-2"
                          >
                            <Ban className="w-4 h-4" />
                            禁用
                          </button>
                        )}
                        <button
                          onClick={() => handleDeleteCode(code.id)}
                          className="w-full px-4 py-2 text-left text-sm text-[#C41E3A] hover:bg-red-50 flex items-center gap-2"
                        >
                          <Trash2 className="w-4 h-4" />
                          删除
                        </button>
                      </div>
                    )}
                  </div>
                </div>

                {/* 使用进度 */}
                <div className="mt-3">
                  <div className="flex items-center justify-between text-sm mb-1">
                    <span className="text-[#666666]">使用进度</span>
                    <span className="text-[#2C2C2C] font-medium">{code.usedCount}/{code.maxUses}</span>
                  </div>
                  <div className="h-2 bg-[#F2EFEA] rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-[#C41E3A] to-[#E85A5A] rounded-full transition-all"
                      style={{ width: `${(code.usedCount / code.maxUses) * 100}%` }}
                    />
                  </div>
                </div>

                {/* 操作按钮 */}
                <div className="flex gap-2 mt-4">
                  <button
                    onClick={() => handleCopyCode(code.code)}
                    className={cn(
                      "flex-1 py-2 rounded-lg text-sm flex items-center justify-center gap-1.5 transition-all",
                      copiedCode === code.code
                        ? "bg-green-100 text-green-600"
                        : "bg-[#F5F0E8] text-[#666666]"
                    )}
                  >
                    {copiedCode === code.code ? (
                      <>
                        <Check className="w-4 h-4" />
                        已复制
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        复制
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => handleShareCode(code.code)}
                    className="flex-1 py-2 rounded-lg text-sm bg-[#C41E3A] text-white flex items-center justify-center gap-1.5"
                  >
                    <Share2 className="w-4 h-4" />
                    分享
                  </button>
                </div>
              </div>

              {/* 使用记录 */}
              {code.usedBy && code.usedBy.length > 0 && (
                <div className="border-t border-[#E8E3DB]">
                  <button
                    onClick={() => setExpandedCode(expandedCode === code.id ? null : code.id)}
                    className="w-full px-4 py-3 flex items-center justify-between text-sm text-[#666666]"
                  >
                    <span>查看使用记录 ({code.usedBy.length})</span>
                    <svg
                      className={cn("w-4 h-4 transition-transform", expandedCode === code.id && "rotate-180")}
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </button>
                  
                  {expandedCode === code.id && (
                    <div className="px-4 pb-4 space-y-2">
                      {code.usedBy.map(user => (
                        <div key={user.id} className="flex items-center gap-3 bg-[#F5F0E8] rounded-lg p-2">
                          <img
                            src={user.avatar}
                            alt={user.name}
                            className="w-8 h-8 rounded-full"
                          />
                          <div className="flex-1">
                            <p className="text-sm font-medium text-[#2C2C2C]">{user.name}</p>
                            <p className="text-xs text-[#999999]">{user.usedAt}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {/* 创建邀请码弹窗 */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50" onClick={() => setShowCreateModal(false)}>
          <div
            className="w-full max-w-lg bg-white rounded-t-2xl animate-in slide-in-from-bottom duration-300"
            onClick={e => e.stopPropagation()}
          >
            <div className="flex items-center justify-between p-4 border-b border-[#E8E3DB]">
              <h3 className="font-semibold text-[#2C2C2C]">生成新邀请码</h3>
              <button onClick={() => setShowCreateModal(false)} className="p-1">
                <X className="w-5 h-5 text-[#666666]" />
              </button>
            </div>
            
            <div className="p-4 space-y-4">
              <div>
                <label className="block text-sm font-medium text-[#2C2C2C] mb-2">最大使用次数</label>
                <div className="flex gap-2">
                  {[5, 10, 20, 50, 100].map(num => (
                    <button
                      key={num}
                      onClick={() => setNewCodeMaxUses(num)}
                      className={cn(
                        "flex-1 py-2 rounded-lg text-sm transition-all",
                        newCodeMaxUses === num
                          ? "bg-[#C41E3A] text-white"
                          : "bg-[#F5F0E8] text-[#666666]"
                      )}
                    >
                      {num}次
                    </button>
                  ))}
                </div>
              </div>
              
              <div className="bg-[#FFF8E6] rounded-lg p-3 text-sm text-[#8B6914]">
                邀请码生成后，被邀请人可通过邀请码直接加入圈子，无需审批
              </div>
            </div>
            
            <div className="p-4 border-t border-[#E8E3DB]">
              <button
                onClick={handleCreateCode}
                disabled={creating}
                className="w-full py-3 bg-gradient-to-r from-[#C41E3A] to-[#E85A5A] text-white rounded-xl font-medium disabled:opacity-50"
              >
                {creating ? "生成中..." : "生成邀请码"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// apps/mobile/src/pages/circles/invite-codes.vue
<script setup lang="ts">
/**
 * 邀请码管理页（从原型 app/circles/[id]/invite-codes/page.tsx 438行高保真迁移）
 * 4统计卡 + 邀请码列表(状态徽章/操作菜单禁用·删除/使用进度条/复制·分享/使用记录展开) + 创建底部弹窗 + 骨架屏
 * 复制/分享改用 uni.setClipboardData 跨端
 */
import { ref, onMounted } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import ErrorState from '@/components/common/error-state.vue'
import { goBack } from '@/utils/router'

interface UsedUser { id: string; name: string; avatar: string; usedAt: string }
interface InviteCode {
  id: string
  code: string
  maxUses: number
  usedCount: number
  status: 'active' | 'disabled' | 'expired'
  createdAt: string
  expiresAt?: string
  usedBy?: UsedUser[]
}

const mockStats = { totalInvited: 156, usedCodes: 12, pendingCodes: 5, thisWeek: 23 }
const mockInviteCodes: InviteCode[] = [
  { id: '1', code: 'GUOXUE2024A', maxUses: 10, usedCount: 8, status: 'active', createdAt: '2024-01-15T10:00:00Z', usedBy: [
    { id: '1', name: '张三', avatar: '/static/avatars/u1.png', usedAt: '2024-01-16' },
    { id: '2', name: '李四', avatar: '/static/avatars/u2.png', usedAt: '2024-01-17' },
  ] },
  { id: '2', code: 'GUOXUE2024B', maxUses: 5, usedCount: 5, status: 'expired', createdAt: '2024-01-10T10:00:00Z', expiresAt: '2024-01-20T10:00:00Z' },
  { id: '3', code: 'VIP888', maxUses: 100, usedCount: 45, status: 'active', createdAt: '2024-01-01T10:00:00Z' },
  { id: '4', code: 'TEST123', maxUses: 3, usedCount: 1, status: 'disabled', createdAt: '2024-01-05T10:00:00Z' },
]

const isLoading = ref(true)
const error = ref('')
const stats = ref({ ...mockStats })
const inviteCodes = ref<InviteCode[]>([])
const showCreateModal = ref(false)
const newCodeMaxUses = ref(10)
const creating = ref(false)
const expandedCode = ref<string | null>(null)
const activeMenu = ref<string | null>(null)
const copiedCode = ref<string | null>(null)

onMounted(() => { loadData() })

async function loadData() {
  isLoading.value = true
  error.value = ''
  try {
    await new Promise(r => setTimeout(r, 800))
    inviteCodes.value = mockInviteCodes
  } catch (e: any) {
    error.value = e?.message || '加载失败'
  } finally {
    isLoading.value = false
  }
}

function statusLabel(s: string) { return s === 'active' ? '有效' : s === 'disabled' ? '已禁用' : '已过期' }
function statusCls(s: string) { return s === 'active' ? 'ic-st-active' : s === 'disabled' ? 'ic-st-disabled' : 'ic-st-expired' }
function formatDate(s: string) { const d = new Date(s); return `${d.getMonth() + 1}/${d.getDate()}` }

async function createCode() {
  creating.value = true
  await new Promise((r) => setTimeout(r, 1000))
  const newCode: InviteCode = {
    id: Date.now().toString(),
    code: `NEW${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
    maxUses: newCodeMaxUses.value,
    usedCount: 0,
    status: 'active',
    createdAt: new Date().toISOString(),
  }
  inviteCodes.value = [newCode, ...inviteCodes.value]
  stats.value.pendingCodes += 1
  showCreateModal.value = false
  creating.value = false
}

function copyCode(code: string) {
  uni.setClipboardData({ data: code, success: () => { copiedCode.value = code; setTimeout(() => (copiedCode.value = null), 2000) } })
}
function shareCode(code: string) {
  // #ifdef MP-WEIXIN
  uni.showToast({ title: '请点击右上角分享', icon: 'none' })
  // #endif
  // #ifndef MP-WEIXIN
  const url = `https://rebugx.com/circles/join?code=${code}`
  uni.setClipboardData({ data: url, success: () => { copiedCode.value = code; setTimeout(() => (copiedCode.value = null), 2000); uni.showToast({ title: '邀请链接已复制', icon: 'none' }) } })
  // #endif
}
function disableCode(id: string) {
  inviteCodes.value = inviteCodes.value.map((c) => (c.id === id ? { ...c, status: 'disabled' as const } : c))
  activeMenu.value = null
}
function deleteCode(id: string) {
  inviteCodes.value = inviteCodes.value.filter((c) => c.id !== id)
  activeMenu.value = null
}
</script>

<template>
  <view class="ic">
    <!-- 顶部导航 -->
    <view class="ic-nav">
      <view class="ic-back" @tap="goBack"><app-icon name="arrow-left" :size="40" color="#2C2C2C" /></view>
      <text class="ic-title">邀请码管理</text>
      <view class="ic-add" @tap="showCreateModal = true"><app-icon name="plus" :size="40" color="#C41E3A" /></view>
    </view>

    <!-- 骨架屏 -->
    <view v-if="isLoading" class="ic-body">
      <view class="ic-stats">
        <view v-for="i in 4" :key="i" class="ic-skel-stat" />
      </view>
      <view class="ic-skel-list">
        <view v-for="i in 3" :key="i" class="ic-skel-card" />
      </view>
    </view>

    <error-state v-else-if="error" :message="error" @retry="loadData" />

    <template v-else>
      <!-- 统计卡片 -->
      <view class="ic-body">
        <view class="ic-stats">
          <view class="ic-stat ic-stat-primary">
            <view class="ic-stat-head"><app-icon name="users" :size="26" color="#ffffff" /><text class="ic-stat-label ic-light">总邀请人数</text></view>
            <text class="ic-stat-num ic-light">{{ stats.totalInvited }}</text>
          </view>
          <view class="ic-stat">
            <view class="ic-stat-head"><app-icon name="gift" :size="26" color="#C9A96E" /><text class="ic-stat-label">本周新增</text></view>
            <text class="ic-stat-num">{{ stats.thisWeek }}</text>
          </view>
          <view class="ic-stat">
            <view class="ic-stat-head"><app-icon name="check" :size="26" color="#22C55E" /><text class="ic-stat-label">已使用码</text></view>
            <text class="ic-stat-num">{{ stats.usedCodes }}</text>
          </view>
          <view class="ic-stat">
            <view class="ic-stat-head"><app-icon name="clock" :size="26" color="#C41E3A" /><text class="ic-stat-label">待使用码</text></view>
            <text class="ic-stat-num">{{ stats.pendingCodes }}</text>
          </view>
        </view>
      </view>

      <!-- 列表 -->
      <view class="ic-list">
        <text class="ic-list-title">邀请码列表</text>

        <view v-if="inviteCodes.length === 0" class="ic-empty">
          <view class="ic-empty-icon"><app-icon name="gift" :size="56" color="#999999" /></view>
          <text class="ic-empty-text">还没有创建邀请码</text>
          <view class="ic-empty-btn" @tap="showCreateModal = true">创建邀请码</view>
        </view>

        <view v-for="code in inviteCodes" :key="code.id" class="ic-card" :class="{ 'ic-card-disabled': code.status === 'disabled' }">
          <view class="ic-card-body">
            <view class="ic-card-head">
              <view class="ic-code-info">
                <view class="ic-code-row">
                  <text class="ic-code">{{ code.code }}</text>
                  <text class="ic-badge" :class="statusCls(code.status)">{{ statusLabel(code.status) }}</text>
                </view>
                <text class="ic-code-date">创建于 {{ formatDate(code.createdAt) }}<text v-if="code.expiresAt"> · 过期于 {{ formatDate(code.expiresAt) }}</text></text>
              </view>
              <view class="ic-menu-wrap">
                <view class="ic-menu-btn" @tap="activeMenu = activeMenu === code.id ? null : code.id"><app-icon name="more-horizontal" :size="36" color="#666666" /></view>
                <view v-if="activeMenu === code.id" class="ic-menu">
                  <view v-if="code.status === 'active'" class="ic-menu-item" @tap="disableCode(code.id)"><app-icon name="ban" :size="26" color="#666666" /><text>禁用</text></view>
                  <view class="ic-menu-item ic-menu-del" @tap="deleteCode(code.id)"><app-icon name="trash-2" :size="26" color="#C41E3A" /><text>删除</text></view>
                </view>
              </view>
            </view>

            <!-- 使用进度 -->
            <view class="ic-progress">
              <view class="ic-progress-row">
                <text class="ic-progress-label">使用进度</text>
                <text class="ic-progress-val">{{ code.usedCount }}/{{ code.maxUses }}</text>
              </view>
              <view class="ic-progress-track"><view class="ic-progress-bar" :style="{ width: (code.usedCount / code.maxUses) * 100 + '%' }" /></view>
            </view>

            <!-- 操作按钮 -->
            <view class="ic-actions">
              <view class="ic-act ic-act-copy" :class="{ 'ic-act-copied': copiedCode === code.code }" @tap="copyCode(code.code)">
                <app-icon :name="copiedCode === code.code ? 'check' : 'copy'" :size="28" :color="copiedCode === code.code ? '#16A34A' : '#666666'" />
                <text>{{ copiedCode === code.code ? '已复制' : '复制' }}</text>
              </view>
              <view class="ic-act ic-act-share" @tap="shareCode(code.code)"><app-icon name="share-2" :size="28" color="#ffffff" /><text>分享</text></view>
            </view>
          </view>

          <!-- 使用记录 -->
          <view v-if="code.usedBy && code.usedBy.length > 0" class="ic-records">
            <view class="ic-records-toggle" @tap="expandedCode = expandedCode === code.id ? null : code.id">
              <text>查看使用记录 ({{ code.usedBy.length }})</text>
              <app-icon :name="expandedCode === code.id ? 'chevron-up' : 'chevron-down'" :size="28" color="#666666" />
            </view>
            <view v-if="expandedCode === code.id" class="ic-records-list">
              <view v-for="u in code.usedBy" :key="u.id" class="ic-record">
                <image class="ic-record-avatar" :src="u.avatar" mode="aspectFill" />
                <view class="ic-record-info"><text class="ic-record-name">{{ u.name }}</text><text class="ic-record-time">{{ u.usedAt }}</text></view>
              </view>
            </view>
          </view>
        </view>
      </view>
    </template>

    <!-- 创建邀请码底部弹窗 -->
    <view v-if="showCreateModal" class="ic-modal-mask" @tap="showCreateModal = false">
      <view class="ic-sheet" @tap.stop>
        <view class="ic-sheet-head">
          <text class="ic-sheet-title">生成新邀请码</text>
          <view @tap="showCreateModal = false"><app-icon name="x" :size="36" color="#666666" /></view>
        </view>
        <view class="ic-sheet-body">
          <text class="ic-field-label">最大使用次数</text>
          <view class="ic-uses">
            <view v-for="n in [5, 10, 20, 50, 100]" :key="n" class="ic-use" :class="{ 'ic-use-on': newCodeMaxUses === n }" @tap="newCodeMaxUses = n">{{ n }}次</view>
          </view>
          <view class="ic-tip">邀请码生成后，被邀请人可通过邀请码直接加入圈子，无需审批</view>
        </view>
        <view class="ic-sheet-foot">
          <view class="ic-create-btn" :class="{ 'ic-create-disabled': creating }" @tap="!creating && createCode()">{{ creating ? '生成中...' : '生成邀请码' }}</view>
        </view>
      </view>
    </view>
  </view>
</template>

<style lang="scss" scoped>
.ic { min-height: 100vh; background: #FAF8F5; padding-bottom: 96rpx; }
.ic-nav { position: sticky; top: 0; z-index: 20; background: #fff; border-bottom: 1rpx solid #E8E3DB; height: 96rpx; display: flex; align-items: center; justify-content: space-between; padding: 0 24rpx; }
.ic-back, .ic-add { padding: 8rpx; }
.ic-title { font-size: 32rpx; font-weight: 600; color: #2C2C2C; }
.ic-body { padding: 24rpx; }
.ic-stats { display: grid; grid-template-columns: 1fr 1fr; gap: 18rpx; }
.ic-stat { background: #fff; border-radius: 20rpx; padding: 24rpx; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.ic-stat-primary { background: linear-gradient(135deg, #C41E3A, #A01830); }
.ic-stat-head { display: flex; align-items: center; gap: 10rpx; margin-bottom: 14rpx; }
.ic-stat-label { font-size: 26rpx; color: #666666; }
.ic-light { color: rgba(255,255,255,0.85); }
.ic-stat-num { font-size: 44rpx; font-weight: 700; color: #2C2C2C; }
.ic-stat-primary .ic-stat-num { color: #fff; }
.ic-list { padding: 0 24rpx; display: flex; flex-direction: column; gap: 18rpx; }
.ic-list-title { font-size: 26rpx; font-weight: 500; color: #666666; }
.ic-empty { background: #fff; border-radius: 20rpx; padding: 56rpx 24rpx; text-align: center; display: flex; flex-direction: column; align-items: center; }
.ic-empty-icon { width: 120rpx; height: 120rpx; border-radius: 999rpx; background: #F5F0E8; display: flex; align-items: center; justify-content: center; margin-bottom: 24rpx; }
.ic-empty-text { font-size: 28rpx; color: #666666; margin-bottom: 24rpx; }
.ic-empty-btn { padding: 14rpx 48rpx; background: #C41E3A; color: #fff; border-radius: 999rpx; font-size: 26rpx; }
.ic-card { background: #fff; border-radius: 20rpx; overflow: hidden; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.ic-card-disabled { opacity: 0.6; }
.ic-card-body { padding: 24rpx; }
.ic-card-head { display: flex; align-items: flex-start; justify-content: space-between; }
.ic-code-row { display: flex; align-items: center; gap: 12rpx; }
.ic-code { font-family: monospace; font-weight: 700; font-size: 36rpx; color: #2C2C2C; }
.ic-badge { padding: 2rpx 12rpx; border-radius: 6rpx; font-size: 20rpx; }
.ic-st-active { background: #DCFCE7; color: #16A34A; }
.ic-st-disabled { background: #F3F4F6; color: #6B7280; }
.ic-st-expired { background: #FFEDD5; color: #EA580C; }
.ic-code-date { display: block; font-size: 24rpx; color: #999999; margin-top: 6rpx; }
.ic-menu-wrap { position: relative; }
.ic-menu-btn { padding: 8rpx; }
.ic-menu { position: absolute; right: 0; top: 100%; margin-top: 4rpx; background: #fff; border-radius: 14rpx; box-shadow: 0 8rpx 24rpx rgba(0,0,0,0.15); border: 1rpx solid #E8E3DB; padding: 8rpx 0; z-index: 10; min-width: 180rpx; }
.ic-menu-item { display: flex; align-items: center; gap: 12rpx; padding: 16rpx 24rpx; font-size: 26rpx; color: #666666; }
.ic-menu-del { color: #C41E3A; }
.ic-progress { margin-top: 18rpx; }
.ic-progress-row { display: flex; align-items: center; justify-content: space-between; font-size: 26rpx; margin-bottom: 8rpx; }
.ic-progress-label { color: #666666; }
.ic-progress-val { color: #2C2C2C; font-weight: 500; }
.ic-progress-track { height: 12rpx; background: #F2EFEA; border-radius: 999rpx; overflow: hidden; }
.ic-progress-bar { height: 100%; background: linear-gradient(to right, #C41E3A, #E85A5A); border-radius: 999rpx; }
.ic-actions { display: flex; gap: 14rpx; margin-top: 24rpx; }
.ic-act { flex: 1; padding: 16rpx 0; border-radius: 14rpx; font-size: 26rpx; display: flex; align-items: center; justify-content: center; gap: 10rpx; }
.ic-act-copy { background: #F5F0E8; color: #666666; }
.ic-act-copied { background: #DCFCE7; color: #16A34A; }
.ic-act-share { background: #C41E3A; color: #fff; }
.ic-records { border-top: 1rpx solid #E8E3DB; }
.ic-records-toggle { display: flex; align-items: center; justify-content: space-between; padding: 22rpx 24rpx; font-size: 26rpx; color: #666666; }
.ic-records-list { padding: 0 24rpx 24rpx; display: flex; flex-direction: column; gap: 14rpx; }
.ic-record { display: flex; align-items: center; gap: 18rpx; background: #F5F0E8; border-radius: 14rpx; padding: 14rpx; }
.ic-record-avatar { width: 56rpx; height: 56rpx; border-radius: 999rpx; background: #E8E3DB; }
.ic-record-info { flex: 1; }
.ic-record-name { display: block; font-size: 26rpx; font-weight: 500; color: #2C2C2C; }
.ic-record-time { display: block; font-size: 22rpx; color: #999999; }
.ic-skel-stat { height: 140rpx; background: #fff; border-radius: 20rpx; }
.ic-stats .ic-skel-stat:nth-child(odd), .ic-stats .ic-skel-stat:nth-child(even) { animation: ic-pulse 1.4s ease-in-out infinite; }
.ic-skel-list { display: flex; flex-direction: column; gap: 18rpx; margin-top: 18rpx; }
.ic-skel-card { height: 260rpx; background: #fff; border-radius: 20rpx; animation: ic-pulse 1.4s ease-in-out infinite; }
@keyframes ic-pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.5; } }
.ic-modal-mask { position: fixed; inset: 0; z-index: 50; background: rgba(0,0,0,0.5); display: flex; align-items: flex-end; }
.ic-sheet { width: 100%; background: #fff; border-radius: 28rpx 28rpx 0 0; }
.ic-sheet-head { display: flex; align-items: center; justify-content: space-between; padding: 28rpx 24rpx; border-bottom: 1rpx solid #E8E3DB; }
.ic-sheet-title { font-size: 30rpx; font-weight: 600; color: #2C2C2C; }
.ic-sheet-body { padding: 28rpx 24rpx; }
.ic-field-label { display: block; font-size: 28rpx; font-weight: 500; color: #2C2C2C; margin-bottom: 18rpx; }
.ic-uses { display: flex; gap: 14rpx; }
.ic-use { flex: 1; padding: 16rpx 0; text-align: center; border-radius: 14rpx; font-size: 26rpx; background: #F5F0E8; color: #666666; }
.ic-use-on { background: #C41E3A; color: #fff; }
.ic-tip { margin-top: 24rpx; background: #FFF8E6; border-radius: 14rpx; padding: 18rpx; font-size: 26rpx; color: #8B6914; line-height: 1.6; }
.ic-sheet-foot { padding: 24rpx; border-top: 1rpx solid #E8E3DB; }
.ic-create-btn { padding: 24rpx 0; text-align: center; background: linear-gradient(to right, #C41E3A, #E85A5A); color: #fff; border-radius: 18rpx; font-size: 30rpx; font-weight: 500; }
.ic-create-disabled { opacity: 0.5; }
</style>
