// v0-reference/proto-ref-app/welcome/page.tsx
"use client"

/**
 * 注册成功 · 欢迎仪式（峰值时刻 1.1）
 *
 * 宣纸色背景 + 中心热卜 LOGO + 渐入「欢迎来到国学世界」+ Slogan，
 * 底部「开始探索」按钮，3 秒自动进入下一步（兴趣选择/首页），可主动点击加速。
 */

import { useEffect, useState, useCallback } from "react"
import { useRouter } from "next/navigation"
import { authApi } from "@/lib/api"
import Image from "next/image"
import { BRAND } from "@/lib/brand"
import { ArrowRight } from "lucide-react"

export default function WelcomePage() {
  const router = useRouter()
  const [countdown, setCountdown] = useState(3)
  const [showTitle, setShowTitle] = useState(false)
  const [showSlogan, setShowSlogan] = useState(false)
  const [showButton, setShowButton] = useState(false)
  const [hasInterests, setHasInterests] = useState<boolean | null>(null)
  const [userName, setUserName] = useState("")

  useEffect(() => {
    const checkUserProfile = async () => {
      try {
        const profile = await authApi.getProfile()
        setUserName(profile?.nickname || profile?.username || "")
        setHasInterests(Boolean(profile?.interests && profile.interests.length > 0))
      } catch {
        setHasInterests(false)
      }
    }
    checkUserProfile()
  }, [])

  const handleNavigate = useCallback(() => {
    if (hasInterests === null) return
    router.replace(hasInterests ? "/" : "/interests-guide")
  }, [router, hasInterests])

  // 渐入动画序列
  useEffect(() => {
    const timers: ReturnType<typeof setTimeout>[] = []
    timers.push(setTimeout(() => setShowTitle(true), 1000))
    timers.push(setTimeout(() => setShowSlogan(true), 1500))
    timers.push(setTimeout(() => setShowButton(true), 2000))
    return () => timers.forEach(clearTimeout)
  }, [])

  // 倒计时自动进入
  useEffect(() => {
    if (countdown <= 0) {
      handleNavigate()
      return
    }
    const timer = setTimeout(() => setCountdown((p) => p - 1), 1000)
    return () => clearTimeout(timer)
  }, [countdown, handleNavigate])

  return (
    <div className="fixed inset-0 overflow-hidden" style={{ background: "linear-gradient(180deg,#f7f0e3 0%,#efe4cf 100%)" }}>
      {/* 柔和光晕 */}
      <div className="absolute left-1/2 top-1/3 h-[360px] w-[360px] -translate-x-1/2 rounded-full blur-[100px]" style={{ background: "rgba(201,169,110,0.18)" }} />

      <div className="relative z-10 flex min-h-screen flex-col items-center justify-center px-8">
        {/* 热卜 LOGO */}
        <div className="mb-10 animate-in fade-in zoom-in-90 duration-1000">
          <div className="overflow-hidden rounded-3xl shadow-xl ring-1 ring-[#c9a96e]/30">
            <Image
              src="/brand/rebu-logo.jpg"
              alt="热卜国学"
              width={104}
              height={104}
              priority
              className="h-[104px] w-[104px] object-cover"
            />
          </div>
        </div>

        {/* 欢迎标题 */}
        <div className={`text-center transition-all duration-1000 ease-out ${showTitle ? "translate-y-0 opacity-100" : "translate-y-3 opacity-0"}`}>
          <h1 className="font-serif text-[26px] font-bold" style={{ color: "#3a3226" }}>
            {userName ? `${userName}，` : ""}欢迎来到国学世界
          </h1>
        </div>

        {/* Slogan */}
        <p className={`mt-4 font-serif text-[16px] transition-all duration-1000 ease-out ${showSlogan ? "translate-y-0 opacity-100" : "translate-y-3 opacity-0"}`} style={{ color: "#7a6f60" }}>
          {BRAND.slogan}
        </p>

        {/* 开始探索按钮 */}
        <button
          onClick={handleNavigate}
          disabled={hasInterests === null}
          className={`mt-14 flex items-center gap-2 rounded-3xl px-10 py-3.5 text-[15px] font-medium text-white shadow-lg transition-all duration-700 active:scale-95 disabled:opacity-50 ${showButton ? "translate-y-0 opacity-100" : "translate-y-3 opacity-0"}`}
          style={{ background: "#c41e3a" }}
        >
          {hasInterests === null ? "加载中…" : (
            <>
              开始探索
              <ArrowRight className="h-4 w-4" />
              <span className="text-white/70">({countdown}s)</span>
            </>
          )}
        </button>

        {/* 装饰分隔线 */}
        <div className={`mt-16 flex items-center gap-4 transition-opacity duration-700 ${showButton ? "opacity-100" : "opacity-0"}`}>
          <div className="h-px w-12" style={{ background: "linear-gradient(to right,transparent,rgba(201,169,110,0.6))" }} />
          <div className="h-1.5 w-1.5 rounded-full" style={{ background: "rgba(201,169,110,0.6)" }} />
          <div className="h-px w-12" style={{ background: "linear-gradient(to left,transparent,rgba(201,169,110,0.6))" }} />
        </div>
      </div>

      {/* 底部品牌落款 */}
      <div className="absolute bottom-8 left-0 right-0 text-center">
        <p className="text-[11px]" style={{ color: "rgba(122,111,96,0.6)" }}>
          {BRAND.name} · {BRAND.tagline}
        </p>
      </div>
    </div>
  )
}

// apps/mobile/src/pages/welcome/index.vue
<template>
  <view class="page">
    <view class="v0-header">
      <text class="v0-title">欢迎页</text>
      <text class="v0-route">V0: welcome</text>
    </view>
    ) => timers.forEach(clearTimeout)
      }, [])
    
      // 倒计时
      useEffect(() => {{ if (countdown <= 0) {
          handleNavigate()
          return }}
        
        const timer = setTimeout(() => {
          setCountdown(prev => prev - 1)
        }, 1000)
        
        return () => clearTimeout(timer)
      }, [countdown, handleNavigate])
    
      return (
        <view class="fixed inset-0 bg-gradient-to-b from-[#1a1a2e] via-[#16213e] to-[#0f0f23] overflow-hidden">
          <!--   -->
          <view class="absolute inset-0">
            <!--   -->
            {[...Array(30)].map((_, i) => (
              <view
                key={i}
                class="absolute w-1 h-1 bg-white rounded-full animate-pulse"
                :style="
                  left: `${{ Math.random() * 100 }}%`,
                  top: `${{ Math.random() * 100 }}%`,
                  animationDelay: `${{ Math.random() * 2 }}s`,
                  opacity: Math.random() * 0.5 + 0.3,
                }}
              />
            ))}
            
            <!--   -->
            <view class="absolute top-1/4 left-1/2 -translate-x-1/2 w-[400px] h-[400px] bg-[#C9A96E]/10 rounded-full blur-[100px]" />
            <view class="absolute bottom-1/4 left-1/2 -translate-x-1/2 w-[300px] h-[300px] bg-[#C41E3A]/10 rounded-full blur-[80px]" />
          </view>
    
          <!--   -->
          <view class="relative z-10 flex flex-col items-center justify-center min-h-screen px-8">
            <!--   -->
            <view 
              class={`mb-8 transition-all duration-700 ease-out ${
                showContent ? "opacity-100 scale-100" : "opacity-0 scale-90"
              }`}
            >
              <view class="w-20 h-20 rounded-full bg-gradient-to-br from-[#C9A96E] to-[#A67C52] flex items-center justify-center shadow-[0_0_40px_rgba(201,169,110,0.4)]">
                <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={{ 1.5 }} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                </svg>
              </view>
            </view>
    
            <!--   -->
            <view 
              class={`text-center transition-all duration-700 ease-out delay-100 ${
                showContent ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              }`}
            >
              <text class="text-2xl font-serif font-bold text-white mb-2">
                {userName ? `${userName}，` : ""}欢迎来到
              </text>
              <text class="text-3xl font-serif font-bold bg-gradient-to-r from-[#C9A96E] to-[#E8D5B0] bg-clip-text text-transparent">
                热卜国学
              </text>
            </view>
    
            <!--   -->
            <text 
              class={`mt-6 text-[15px] text-white/70 text-center leading-relaxed transition-all duration-700 ease-out ${
                showSlogan ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              }`}
            >
              探寻东方智慧，传承千年文化
              <text>
    </text> />
              <text class="text-[13px] text-white/50">开启你的国学之旅</text>
            </text>
    
            <!--   -->
            <view class="v0-btn"
              @click={{ handleNavigate }}
              :disabled={{ hasInterests === null }}
              class={`mt-12 px-10 py-3 rounded-full bg-gradient-to-r from-[#C41E3A] to-[#9B1B30] text-white font-medium text-[15px] shadow-[0_4px_20px_rgba(196,30,58,0.4)] active:scale-95 transition-all duration-300 ${
                showButton ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              } disabled:opacity-50`}
            >
              {hasInterests === null ? "加载中..." : (
                
                  进入平台
                  <text class="ml-2 text-white/70">({{ countdown }}s)</text>
                
              )}
            </view>
    
            <!--   -->
            <view 
              class={`mt-16 flex items-center gap-4 transition-all duration-700 delay-500 ${
                showButton ? "opacity-100" : "opacity-0"
              }`}
            >
              <view class="w-12 h-px bg-gradient-to-r from-transparent to-[#C9A96E]/50" />
              <view class="w-1.5 h-1.5 rounded-full bg-[#C9A96E]/50" />
              <view class="w-12 h-px bg-gradient-to-l from-transparent to-[#C9A96E]/50" />
            </view>
    
            <!--   -->
            <text 
              class={`mt-6 text-[12px] text-white/40 transition-all duration-700 delay-700 ${
                showButton ? "opacity-100" : "opacity-0"
              }`}
            >
              {hasInterests ? "即将进入首页" : "即将进入兴趣选择"}
            </text>
          </view>
    
          <!--   -->
          <view class="absolute bottom-8 left-0 right-0 text-center">
            <text class="text-[11px] text-white/30">
              热卜国学 - 传承东方智慧
            </text>
          </view>
    
          <!--   -->
          <style jsx>{`
            @keyframes pulse {
              0%, 100% { opacity: 0.3; }
              50% { opacity: 0.8; }
            }
          `}</style>
        </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { onPullDownRefresh } from '@dcloudio/uni-app'

const loading = ref(true)
const error = ref<string | null>(null)

// V0 原始数据
    const timers: NodeJS.Timeout[] = []

async function fetchData() {
  loading.value = true
  try { loading.value = false } catch (e: any) { error.value = e.message }
}

onMounted(() => fetchData())
onPullDownRefresh(() => fetchData().finally(() => uni.stopPullDownRefresh()))
</script>

<style scoped>
.page {
  background: #FAF8F5;
  min-height: 100vh;
}
.v0-header {
  padding: 24rpx 32rpx;
  background: linear-gradient(135deg, #C41E3A, #8B0000);
  margin-bottom: 24rpx;
}
.v0-title {
  font-size: 36rpx;
  font-weight: 700;
  color: #FFFFFF;
  display: block;
}
.v0-route {
  font-size: 20rpx;
  color: rgba(255,255,255,0.6);
  margin-top: 4rpx;
  display: block;
}
.v0-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 16rpx 32rpx;
  border-radius: 12rpx;
  background: #C41E3A;
  color: #FFFFFF;
  font-size: 28rpx;
}
.v0-hr {
  height: 1px;
  background: #E8E0D5;
  margin: 24rpx 0;
}
</style>
