// apps/mobile/src/pkg-ebook/notes/index.vue
<template>
  <view class="page">
    <!-- Header -->
    <view class="hd">
      <view class="hd-bar">
        <view class="icon-btn" @tap="goBack"><AppIcon name="arrow-left" :size="40" :color="C.text" /></view>
        <text class="hd-title">笔记 & 划线</text>
        <view class="icon-btn"><AppIcon name="download" :size="40" :color="C.primary" /></view>
      </view>

      <!-- 统计 -->
      <view class="summary">
        <view class="summary-item">
          <AppIcon name="pen-line" :size="32" :color="C.primary" />
          <text class="summary-tx">{{ totalNotes }} 条笔记</text>
        </view>
        <view class="summary-item">
          <AppIcon name="highlighter" :size="32" :color="C.amber" />
          <text class="summary-tx">{{ totalHighlights }} 处划线</text>
        </view>
      </view>

      <!-- 搜索 -->
      <view class="hd-search">
        <view class="search-box">
          <AppIcon name="search" :size="32" :color="C.slate400" class="search-icon" />
          <input v-model="search" class="search-input" placeholder="搜索笔记内容..." placeholder-class="ph" />
        </view>
      </view>

      <!-- 筛选 -->
      <view class="filters">
        <view
          v-for="f in filterTabs"
          :key="f.id"
          class="filter-chip"
          :class="{ active: filter === f.id }"
          @tap="filter = f.id"
        >
          <text class="filter-tx" :class="{ 'active-tx': filter === f.id }">{{ f.label }}</text>
        </view>
      </view>
    </view>

    <scroll-view scroll-y class="body">
      <!-- 空状态 -->
      <view v-if="groupedKeys.length === 0" class="empty">
        <AppIcon name="message-square" :size="96" :color="C.slate200" />
        <text class="empty-title">暂无笔记</text>
        <text class="empty-sub">在阅读时选中文字，可以划线或添加笔记</text>
        <view class="empty-btn" @tap="goShelf"><text class="empty-btn-tx">去阅读</text></view>
      </view>

      <!-- 按书分组 -->
      <view v-for="g in grouped" :key="g.bookId" class="group">
        <view class="book-hd">
          <view class="book-cover" :style="{ background: g.book.bookCoverColor }">
            <view class="cover-spine" />
          </view>
          <view class="book-meta">
            <text class="book-title">{{ g.book.bookTitle }}</text>
            <text class="book-sub">{{ g.list.length }} 条记录</text>
          </view>
          <view class="continue" @tap="goReader(g.bookId)">
            <text class="continue-tx">继续读</text>
            <AppIcon name="chevron-right" :size="28" :color="C.primary" />
          </view>
        </view>

        <view class="card">
          <view v-for="(note, idx) in g.list" :key="note.id" class="note-item" :class="{ 'no-border': idx === 0 }">
            <view class="note-top">
              <view class="note-type">
                <AppIcon :name="note.type === 'highlight' ? 'highlighter' : 'pen-line'" :size="28" :color="note.type === 'highlight' ? C.amber : C.primary" />
                <text class="note-chapter">{{ note.chapterTitle }}</text>
              </view>
              <view class="note-actions">
                <view class="act-btn"><AppIcon name="share-2" :size="24" :color="C.slate400" /></view>
                <view class="act-btn" @tap="del(note.id)"><AppIcon name="trash-2" :size="24" :color="C.red400" /></view>
              </view>
            </view>

            <!-- 选中文字（带划线色） -->
            <view
              class="sel-text"
              :style="{
                background: note.highlightColor ? note.highlightColor + '40' : '#eff6ff',
                borderLeftColor: note.highlightColor || C.primary,
              }"
            >
              <text class="sel-tx">{{ note.selectedText }}</text>
            </view>

            <!-- 笔记内容 -->
            <view v-if="note.noteContent" class="note-content">
              <view class="note-content-label">
                <AppIcon name="pen-line" :size="24" :color="C.textSoft" />
                <text class="note-content-label-tx">笔记</text>
              </view>
              <text class="note-content-tx">{{ note.noteContent }}</text>
            </view>

            <text class="note-time">{{ note.createdAt }}</text>
          </view>
        </view>
      </view>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { ebookNotes, type EbookNote, type EbookNoteType } from '@/lib/ebook-data'

const C = {
  text: '#1e293b', textSoft: '#64748b', primary: '#2563eb', amber: '#f59e0b',
  slate400: '#94a3b8', slate200: '#e2e8f0', red400: '#f87171',
}

type FilterType = 'all' | 'note' | 'highlight'
const filterTabs: { id: FilterType; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: 'note', label: '笔记' },
  { id: 'highlight', label: '划线' },
]

const search = ref('')
const filter = ref<FilterType>('all')
const items = ref<EbookNote[]>([...ebookNotes])

const filtered = computed(() =>
  items.value.filter((n) => {
    const matchSearch = !search.value || n.selectedText.includes(search.value) || (n.noteContent || '').includes(search.value)
    const matchFilter = filter.value === 'all' || (n.type as EbookNoteType) === filter.value
    return matchSearch && matchFilter
  }),
)
const grouped = computed(() => {
  const map: Record<string, EbookNote[]> = {}
  filtered.value.forEach((n) => {
    if (!map[n.bookId]) map[n.bookId] = []
    map[n.bookId].push(n)
  })
  return Object.keys(map).map((bookId) => ({ bookId, book: map[bookId][0], list: map[bookId] }))
})
const groupedKeys = computed(() => grouped.value.map((g) => g.bookId))
const totalNotes = computed(() => items.value.filter((n) => n.type === 'note').length)
const totalHighlights = computed(() => items.value.filter((n) => n.type === 'highlight').length)

function del(id: string) {
  items.value = items.value.filter((n) => n.id !== id)
}
function goBack() {
  uni.navigateBack()
}
function goShelf() {
  uni.navigateTo({ url: '/pkg-ebook/bookshelf/index' })
}
function goReader(bookId: string) {
  uni.navigateTo({ url: `/pkg-ebook/reader/index?id=${bookId}` })
}
</script>

<style scoped lang="scss">
.page {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: var(--ebook-bg);
}
.hd {
  position: sticky;
  top: 0;
  z-index: 50;
  background: rgba(255, 255, 255, 0.95);
  border-bottom: 2rpx solid var(--ebook-border);
}
.hd-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 32rpx;
  height: 112rpx;
}
.icon-btn {
  padding: 12rpx;
  border-radius: 16rpx;
}
.hd-title {
  font-size: 32rpx;
  font-weight: 600;
  color: var(--ebook-text);
}
.summary {
  display: flex;
  align-items: center;
  gap: 32rpx;
  padding: 0 32rpx 24rpx;
}
.summary-item {
  display: flex;
  align-items: center;
  gap: 12rpx;
}
.summary-tx {
  font-size: 28rpx;
  color: var(--ebook-text-soft);
}
.hd-search {
  padding: 0 32rpx 24rpx;
}
.search-box {
  position: relative;
  display: flex;
  align-items: center;
}
.search-icon {
  position: absolute;
  left: 24rpx;
  z-index: 1;
}
.search-input {
  width: 100%;
  height: 72rpx;
  padding: 0 32rpx 0 72rpx;
  background: #f1f5f9;
  border-radius: 999rpx;
  font-size: 28rpx;
  color: var(--ebook-text);
  box-sizing: border-box;
}
.ph {
  color: #94a3b8;
}
.filters {
  display: flex;
  gap: 16rpx;
  padding: 0 32rpx 24rpx;
}
.filter-chip {
  padding: 12rpx 28rpx;
  border-radius: 999rpx;
  background: #fff;
  border: 2rpx solid var(--ebook-border);
}
.filter-chip.active {
  background: var(--ebook-primary);
  border-color: var(--ebook-primary);
}
.filter-tx {
  font-size: 24rpx;
  font-weight: 500;
  color: var(--ebook-text-soft);
}
.filter-tx.active-tx {
  color: #fff;
}
.body {
  flex: 1;
  padding: 24rpx 32rpx 64rpx;
  box-sizing: border-box;
}
.empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 128rpx 0;
}
.empty-title {
  font-size: 28rpx;
  font-weight: 500;
  color: var(--ebook-text-soft);
  margin: 24rpx 0 8rpx;
}
.empty-sub {
  font-size: 26rpx;
  color: #94a3b8;
  margin-bottom: 32rpx;
}
.empty-btn {
  padding: 18rpx 48rpx;
  background: var(--ebook-primary);
  border-radius: 16rpx;
}
.empty-btn-tx {
  color: #fff;
  font-size: 28rpx;
  font-weight: 500;
}
.group {
  margin-bottom: 40rpx;
}
.book-hd {
  display: flex;
  align-items: center;
  gap: 20rpx;
  margin-bottom: 16rpx;
}
.book-cover {
  width: 64rpx;
  height: 92rpx;
  border-radius: 8rpx;
  box-shadow: 0 2rpx 6rpx rgba(0, 0, 0, 0.1);
  flex-shrink: 0;
  position: relative;
  overflow: hidden;
}
.cover-spine {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 4rpx;
  background: rgba(255, 255, 255, 0.2);
}
.book-meta {
  flex: 1;
  min-width: 0;
}
.book-title {
  display: block;
  font-size: 28rpx;
  font-weight: 600;
  color: var(--ebook-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.book-sub {
  font-size: 24rpx;
  color: var(--ebook-text-soft);
}
.continue {
  display: flex;
  align-items: center;
  gap: 2rpx;
}
.continue-tx {
  font-size: 24rpx;
  color: var(--ebook-primary);
}
.card {
  background: #fff;
  border-radius: 24rpx;
  border: 2rpx solid var(--ebook-border);
  overflow: hidden;
}
.note-item {
  padding: 32rpx;
  border-top: 2rpx solid var(--ebook-border);
}
.note-item.no-border {
  border-top: none;
}
.note-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16rpx;
  margin-bottom: 16rpx;
}
.note-type {
  display: flex;
  align-items: center;
  gap: 12rpx;
}
.note-chapter {
  font-size: 24rpx;
  color: var(--ebook-text-soft);
}
.note-actions {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.act-btn {
  padding: 8rpx;
  border-radius: 8rpx;
}
.sel-text {
  padding: 16rpx 24rpx;
  border-radius: 12rpx;
  margin-bottom: 16rpx;
  border-left: 8rpx solid;
}
.sel-tx {
  font-size: 28rpx;
  color: var(--ebook-text);
  line-height: 1.6;
}
.note-content {
  background: #f8fafc;
  border-radius: 12rpx;
  padding: 20rpx 24rpx;
}
.note-content-label {
  display: flex;
  align-items: center;
  gap: 8rpx;
  margin-bottom: 8rpx;
}
.note-content-label-tx {
  font-size: 24rpx;
  color: var(--ebook-text-soft);
}
.note-content-tx {
  font-size: 28rpx;
  color: var(--ebook-text);
  line-height: 1.6;
}
.note-time {
  display: block;
  font-size: 20rpx;
  color: #94a3b8;
  margin-top: 16rpx;
}
</style>

// app/ebook/notes/page.tsx
"use client"

import { useState } from "react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  ArrowLeft,
  MessageSquare,
  ChevronRight,
  Search,
  Trash2,
  Share2,
  Download,
  Highlighter,
  PenLine,
} from "lucide-react"
import Link from "next/link"

type NoteType = "highlight" | "note"

interface NoteItem {
  id: string
  type: NoteType
  bookId: string
  bookTitle: string
  bookCoverColor: string
  chapterId: string
  chapterTitle: string
  selectedText: string
  noteContent?: string
  highlightColor?: string
  createdAt: string
}

const notesData: NoteItem[] = [
  {
    id: "n1",
    type: "note",
    bookId: "1",
    bookTitle: "八字命理精解",
    bookCoverColor: "#1e3a5f",
    chapterId: "2",
    chapterTitle: "第二章 天干地支详解",
    selectedText: "天干共有十个，分别是：甲、乙、丙、丁、戊、己、庚、辛、壬、癸。",
    noteContent: "这十个天干需要熟记，并对应五行属性：甲乙木、丙丁火、戊己土、庚辛金、壬癸水",
    createdAt: "今天 14:32",
  },
  {
    id: "n2",
    type: "highlight",
    bookId: "1",
    bookTitle: "八字命理精解",
    bookCoverColor: "#1e3a5f",
    chapterId: "3",
    chapterTitle: "第三章 五行生克制化",
    selectedText: "五行之间存在着相生相克的关系：相生：木生火，火生土，土生金，金生水，水生木",
    highlightColor: "#fef08a",
    createdAt: "昨天 09:15",
  },
  {
    id: "n3",
    type: "highlight",
    bookId: "1",
    bookTitle: "八字命理精解",
    bookCoverColor: "#1e3a5f",
    chapterId: "3",
    chapterTitle: "第三章 五行生克制化",
    selectedText: "相克：木克土，土克水，水克火，火克金，金克木",
    highlightColor: "#bbf7d0",
    createdAt: "昨天 09:18",
  },
  {
    id: "n4",
    type: "note",
    bookId: "3",
    bookTitle: "风水学基础教程",
    bookCoverColor: "#4a1942",
    chapterId: "1",
    chapterTitle: "第一章 风水学概论",
    selectedText: "风水学是中国传统文化中的重要组成部分，讲究天地人三才合一。",
    noteContent: "风水的核心思想：「气」的流动与聚散决定了居住环境的吉凶",
    createdAt: "3天前",
  },
]

function groupByBook(items: NoteItem[]) {
  return items.reduce<Record<string, NoteItem[]>>((acc, item) => {
    if (!acc[item.bookId]) acc[item.bookId] = []
    acc[item.bookId].push(item)
    return acc
  }, {})
}

type FilterType = "all" | "note" | "highlight"

export default function EbookNotesPage() {
  const [search, setSearch] = useState("")
  const [filter, setFilter] = useState<FilterType>("all")
  const [items, setItems] = useState(notesData)

  const filtered = items.filter((n) => {
    const matchSearch = !search || n.selectedText.includes(search) || (n.noteContent || "").includes(search)
    const matchFilter =
      filter === "all" || (filter === "note" && n.type === "note") || (filter === "highlight" && n.type === "highlight")
    return matchSearch && matchFilter
  })

  const grouped = groupByBook(filtered)

  const deleteNote = (id: string) => {
    setItems((prev) => prev.filter((n) => n.id !== id))
  }

  const totalNotes = items.filter((n) => n.type === "note").length
  const totalHighlights = items.filter((n) => n.type === "highlight").length

  return (
    <div className="min-h-screen bg-[var(--ebook-bg)]">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-sm border-b border-[var(--ebook-border)]">
        <div className="flex items-center justify-between px-4 h-14">
          <Link href="/ebook/bookshelf" className="p-1.5 -ml-1.5 rounded-lg hover:bg-slate-100 active:scale-95 transition-all">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="font-semibold text-base text-[var(--ebook-text)]">笔记 & 划线</h1>
          <button className="p-1.5 rounded-lg hover:bg-slate-100 transition-all">
            <Download className="w-5 h-5 text-[var(--ebook-primary)]" />
          </button>
        </div>

        {/* Summary */}
        <div className="flex items-center gap-4 px-4 pb-3">
          <div className="flex items-center gap-1.5 text-sm text-[var(--ebook-text-soft)]">
            <PenLine className="w-4 h-4 text-[var(--ebook-primary)]" />
            <span>{totalNotes} 条笔记</span>
          </div>
          <div className="flex items-center gap-1.5 text-sm text-[var(--ebook-text-soft)]">
            <Highlighter className="w-4 h-4 text-amber-500" />
            <span>{totalHighlights} 处划线</span>
          </div>
        </div>

        {/* Search */}
        <div className="px-4 pb-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="搜索笔记内容..."
              className="w-full h-9 pl-9 pr-4 bg-slate-100 rounded-full text-sm border-0 focus:outline-none focus:ring-2 focus:ring-[var(--ebook-primary)]"
            />
          </div>
        </div>

        {/* Filter */}
        <div className="flex gap-2 px-4 pb-3">
          {[
            { id: "all" as FilterType, label: "全部" },
            { id: "note" as FilterType, label: "笔记" },
            { id: "highlight" as FilterType, label: "划线" },
          ].map((f) => (
            <button
              key={f.id}
              onClick={() => setFilter(f.id)}
              className={cn(
                "px-3.5 py-1.5 rounded-full text-xs font-medium transition-all",
                filter === f.id
                  ? "bg-[var(--ebook-primary)] text-white"
                  : "bg-white border border-[var(--ebook-border)] text-[var(--ebook-text-soft)]"
              )}
            >
              {f.label}
            </button>
          ))}
        </div>
      </header>

      <main className="px-4 py-3 pb-8 space-y-5">
        {Object.keys(grouped).length === 0 ? (
          <div className="text-center py-16">
            <MessageSquare className="w-12 h-12 mx-auto mb-3 text-slate-200" />
            <p className="text-[var(--ebook-text-soft)] font-medium mb-1">暂无笔记</p>
            <p className="text-sm text-slate-400 mb-4">在阅读时选中文字，可以划线或添加笔记</p>
            <Button className="bg-[var(--ebook-primary)]" asChild>
              <Link href="/ebook/bookshelf">去阅读</Link>
            </Button>
          </div>
        ) : (
          Object.entries(grouped).map(([bookId, notes]) => {
            const book = notes[0]
            return (
              <div key={bookId}>
                {/* Book header */}
                <div className="flex items-center gap-2.5 mb-2">
                  <div
                    className="w-8 h-[46px] rounded shadow-sm flex-shrink-0 relative overflow-hidden"
                    style={{ background: book.bookCoverColor }}
                  >
                    <div className="absolute left-0 top-0 bottom-0 w-0.5 bg-white/20" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-sm text-[var(--ebook-text)] line-clamp-1">{book.bookTitle}</h3>
                    <p className="text-xs text-[var(--ebook-text-soft)]">{notes.length} 条记录</p>
                  </div>
                  <Link
                    href={`/ebook/reader/${bookId}`}
                    className="text-xs text-[var(--ebook-primary)] flex items-center gap-0.5"
                  >
                    继续读<ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </div>

                <div className="bg-white rounded-xl border border-[var(--ebook-border)] overflow-hidden divide-y divide-[var(--ebook-border)]">
                  {notes.map((note) => (
                    <div key={note.id} className="px-4 py-4 group">
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <div className="flex items-center gap-1.5">
                          {note.type === "highlight" ? (
                            <Highlighter className="w-3.5 h-3.5 text-amber-500" />
                          ) : (
                            <PenLine className="w-3.5 h-3.5 text-[var(--ebook-primary)]" />
                          )}
                          <span className="text-xs text-[var(--ebook-text-soft)]">{note.chapterTitle}</span>
                        </div>
                        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                          <button className="p-1 rounded hover:bg-slate-100">
                            <Share2 className="w-3 h-3 text-slate-400" />
                          </button>
                          <button onClick={() => deleteNote(note.id)} className="p-1 rounded hover:bg-red-50">
                            <Trash2 className="w-3 h-3 text-red-400" />
                          </button>
                        </div>
                      </div>

                      {/* Selected text with highlight */}
                      <div
                        className="text-sm text-[var(--ebook-text)] leading-relaxed px-3 py-2 rounded-lg mb-2 border-l-4"
                        style={{
                          background: note.highlightColor ? note.highlightColor + "40" : "#eff6ff",
                          borderLeftColor: note.highlightColor || "var(--ebook-primary)",
                        }}
                      >
                        {note.selectedText}
                      </div>

                      {/* Note content */}
                      {note.noteContent && (
                        <div className="bg-slate-50 rounded-lg px-3 py-2.5">
                          <p className="text-xs text-[var(--ebook-text-soft)] mb-1 flex items-center gap-1">
                            <PenLine className="w-3 h-3" />笔记
                          </p>
                          <p className="text-sm text-[var(--ebook-text)] leading-relaxed">{note.noteContent}</p>
                        </div>
                      )}

                      <p className="text-[10px] text-slate-400 mt-2">{note.createdAt}</p>
                    </div>
                  ))}
                </div>
              </div>
            )
          })
        )}
      </main>
    </div>
  )
}
