// apps/mobile/src/pkg-merchant/violations/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="navbar" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="navbar-inner">
        <view class="nav-back" @tap="goBack">
          <AppIcon name="arrow-left" :size="20" color="#1f1f1f" />
        </view>
        <text class="nav-title">违规管理</text>
        <view class="nav-placeholder" />
      </view>
    </view>

    <scroll-view scroll-y class="scroll" :style="{ top: navH + 'px' }">
      <view v-if="loading" class="state-loading"><text class="state-loading-text">加载中...</text></view>
      <view v-if="error" class="state-error"><text class="state-error-text">加载失败</text><view class="state-retry" @tap="retry"><text class="state-retry-text">重试</text></view></view>
      <template v-if="!loading && !error">
      <!-- 违规概览 -->
      <view class="overview-wrap">
        <view class="card">
          <view class="ov-head">
            <view>
              <text class="ov-label">店铺扣分</text>
              <view class="ov-score-row">
                <text class="ov-score">{{ stats.score }}</text>
                <text class="ov-max">/ {{ stats.maxScore }}分</text>
              </view>
            </view>
            <view class="ov-circle" :style="{ background: levelBg }">
              <text class="ov-circle-text" :style="{ color: levelColor }">{{ levelLabel }}</text>
            </view>
          </view>
          <!-- 进度条 -->
          <view class="progress-track">
            <view class="progress-fill" :style="{ width: scorePercent + '%', background: levelColor }" />
          </view>
          <view class="ov-foot">
            <view class="ov-foot-item">
              <text class="ov-foot-label">违规次数</text>
              <text class="ov-foot-val">{{ stats.total }}</text>
            </view>
            <view class="ov-foot-item">
              <text class="ov-foot-label">待处理</text>
              <text class="ov-foot-val ov-foot-danger">{{ stats.pending }}</text>
            </view>
          </view>
        </view>

        <!-- 扣分说明 -->
        <view class="info-card">
          <AppIcon name="info" :size="16" color="#d97706" />
          <view class="info-text-wrap">
            <text class="info-text">扣分满48分将被暂停营业资格，每季度初清零一次。</text>
            <text class="info-text info-text-2">如有异议可在收到通知后3天内提交申诉。</text>
          </view>
        </view>
      </view>

      <!-- 违规记录 -->
      <view class="record-wrap">
        <text class="section-title">违规记录</text>
        <view class="record-list">
          <view v-for="v in violations" :key="v.id" class="record-card">
            <view class="record-row">
              <view class="record-icon" :style="{ background: typeConfig[v.type].bg }">
                <AppIcon :name="typeConfig[v.type].icon" :size="20" :color="typeConfig[v.type].color" />
              </view>
              <view class="record-body">
                <view class="record-title-row">
                  <text class="record-title">{{ v.title }}</text>
                  <view class="record-status" :style="{ background: statusConfig[v.status].bg }">
                    <text class="record-status-text" :style="{ color: statusConfig[v.status].color }">{{ statusConfig[v.status].label }}</text>
                  </view>
                </view>
                <text class="record-desc">{{ v.description }}</text>
                <view class="record-meta">
                  <text v-if="v.productTitle" class="record-meta-text">商品: {{ v.productTitle }}</text>
                  <text v-if="v.orderNo" class="record-meta-text">订单: {{ v.orderNo }}</text>
                </view>
                <view class="record-penalty">
                  <text class="record-penalty-text">处罚: {{ v.penalty }}</text>
                </view>
                <view class="record-foot">
                  <text class="record-time">{{ v.createdAt }}</text>
                  <view v-if="v.status === 'pending'" class="record-actions">
                    <view class="rbtn rbtn-outline" @tap="onAppeal">
                      <text class="rbtn-outline-text">申诉</text>
                    </view>
                    <view class="rbtn rbtn-primary" @tap="onHandle">
                      <text class="rbtn-primary-text">去处理</text>
                    </view>
                  </view>
                  <text v-else class="record-processed">处理时间: {{ v.processedAt }}</text>
                </view>
              </view>
            </view>
          </view>
        </view>

        <view v-if="violations.length === 0" class="empty">
          <view class="empty-icon">
            <AppIcon name="shield-alert" :size="32" color="#16a34a" />
          </view>
          <text class="empty-text">暂无违规记录，继续保持！</text>
        </view>
      </view>
      <view style="height: 40px" />
      </template>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'
import {
  merchantAdminApi,
  violationTypeConfig,
  violationStatusConfig,
} from '@/lib/merchant-data'

const statusBarHeight = ref(20)
const navH = ref(64)
uni.getSystemInfo({
  success: (r) => {
    statusBarHeight.value = r.statusBarHeight || 20
    navH.value = (r.statusBarHeight || 20) + 44
  },
})

const stats = ref<any>({})
const violations = ref<any[]>([])
const loading = ref(true)
const error = ref(false)
const typeConfig = violationTypeConfig
const statusConfig = violationStatusConfig

const scorePercent = computed(() => (stats.value.score / stats.value.maxScore) * 100)
const levelLabel = computed(() => (scorePercent.value > 50 ? '警告' : scorePercent.value > 25 ? '注意' : '良好'))
const levelColor = computed(() => (scorePercent.value > 50 ? '#dc2626' : scorePercent.value > 25 ? '#d97706' : '#16a34a'))
const levelBg = computed(() => (scorePercent.value > 50 ? '#fee2e2' : scorePercent.value > 25 ? '#fef3c7' : '#dcfce7'))

function onAppeal() {
  uni.showToast({ title: '申诉功能开发中', icon: 'none' })
}
function onHandle() {
  uni.showToast({ title: '处理功能开发中', icon: 'none' })
}

onMounted(async () => {
  try {
    const res = await merchantAdminApi.getViolations()
    stats.value = res.stats || {}
    violations.value = res.items || []
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
})

async function retry() {
  error.value = false
  loading.value = true
  try {
    const res = await merchantAdminApi.getViolations()
    stats.value = res.stats || {}
    violations.value = res.items || []
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.page { min-height: 100vh; background: #f5f5f5; }
.navbar { position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: #fff; border-bottom: 1px solid #ededed; }
.navbar-inner { height: 44px; display: flex; align-items: center; padding: 0 12px; }
.nav-back { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; }
.nav-title { font-size: 17px; font-weight: 600; color: #1f1f1f; margin-left: 4px; }
.nav-placeholder { width: 32px; }
.scroll { position: fixed; left: 0; right: 0; bottom: 0; }

.overview-wrap { padding: 16px; }
.card { background: #fff; border-radius: 12px; padding: 16px; }
.ov-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; }
.ov-label { font-size: 13px; color: #9ca3af; }
.ov-score-row { display: flex; align-items: baseline; gap: 4px; margin-top: 4px; }
.ov-score { font-size: 30px; font-weight: 700; color: #1f1f1f; }
.ov-max { font-size: 13px; color: #9ca3af; }
.ov-circle { width: 64px; height: 64px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }
.ov-circle-text { font-size: 17px; font-weight: 700; }
.progress-track { width: 100%; height: 8px; background: #f3f4f6; border-radius: 999px; overflow: hidden; }
.progress-fill { height: 100%; border-radius: 999px; }
.ov-foot { display: flex; align-items: center; gap: 16px; margin-top: 16px; }
.ov-foot-item { display: flex; align-items: center; gap: 4px; }
.ov-foot-label { font-size: 13px; color: #9ca3af; }
.ov-foot-val { font-size: 13px; font-weight: 500; color: #1f1f1f; }
.ov-foot-danger { color: #dc2626; }

.info-card { display: flex; align-items: flex-start; gap: 8px; margin-top: 12px; padding: 12px; background: #fffbeb; border: 1px solid rgba(217, 119, 6, 0.2); border-radius: 12px; }
.info-text-wrap { flex: 1; }
.info-text { font-size: 12px; color: #6b7280; line-height: 1.5; display: block; }
.info-text-2 { margin-top: 4px; }

.record-wrap { padding: 0 16px; }
.section-title { font-size: 15px; font-weight: 500; color: #1f1f1f; display: block; margin-bottom: 12px; }
.record-list { display: flex; flex-direction: column; gap: 12px; }
.record-card { background: #fff; border-radius: 12px; padding: 16px; }
.record-row { display: flex; align-items: flex-start; gap: 12px; }
.record-icon { width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.record-body { flex: 1; min-width: 0; }
.record-title-row { display: flex; align-items: center; justify-content: space-between; }
.record-title { font-size: 15px; font-weight: 500; color: #1f1f1f; }
.record-status { padding: 2px 8px; border-radius: 6px; }
.record-status-text { font-size: 10px; }
.record-desc { font-size: 13px; color: #6b7280; margin-top: 4px; display: block; }
.record-meta { margin-top: 8px; }
.record-meta-text { font-size: 12px; color: #9ca3af; display: block; }
.record-penalty { margin-top: 8px; padding: 8px; background: #fef2f2; border-radius: 6px; }
.record-penalty-text { font-size: 12px; color: #dc2626; }
.record-foot { display: flex; align-items: center; justify-content: space-between; margin-top: 12px; padding-top: 12px; border-top: 1px solid #ededed; }
.record-time { font-size: 12px; color: #9ca3af; }
.record-actions { display: flex; gap: 8px; }
.rbtn { height: 30px; padding: 0 14px; border-radius: 6px; display: flex; align-items: center; justify-content: center; }
.rbtn-outline { border: 1px solid #d1d5db; }
.rbtn-outline-text { font-size: 13px; color: #4b5563; }
.rbtn-primary { background: #c41e3a; }
.rbtn-primary-text { font-size: 13px; color: #fff; }
.record-processed { font-size: 12px; color: #9ca3af; }

.empty { padding: 80px 0; display: flex; flex-direction: column; align-items: center; }
.empty-icon { width: 64px; height: 64px; border-radius: 50%; background: #dcfce7; display: flex; align-items: center; justify-content: center; margin-bottom: 16px; }
.empty-text { font-size: 14px; color: #9ca3af; }
/* 三态 */
.state-loading { padding: 80px 0; text-align: center; }
.state-loading-text { font-size: 14px; color: #9ca3af; }
.state-error { padding: 80px 0; text-align: center; }
.state-error-text { font-size: 14px; color: #ef4444; display: block; margin-bottom: 12px; }
.state-retry { display: inline-block; padding: 8px 20px; background: #c41e3a; border-radius: 8px; }
.state-retry-text { font-size: 14px; color: #fff; }
</style>

// app/merchant/violations/page.tsx
"use client"

import Link from "next/link"
import { ArrowLeft, AlertTriangle, FileWarning, ShieldAlert, ChevronRight, Info } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { cn } from "@/lib/utils"

const violationStats = {
  total: 3,
  pending: 1,
  score: 12,
  maxScore: 48,
}

const violations = [
  {
    id: "1",
    type: "product",
    title: "商品信息违规",
    description: "商品标题包含夸大宣传用语",
    productTitle: "最强命理秘籍",
    penalty: "商品下架，扣2分",
    score: 2,
    status: "pending",
    createdAt: "2024-01-15 10:00",
    deadline: "2024-01-18 10:00",
  },
  {
    id: "2",
    type: "service",
    title: "服务态度违规",
    description: "与买家沟通时使用不文明用语",
    orderNo: "202401100001",
    penalty: "警告，扣5分",
    score: 5,
    status: "processed",
    createdAt: "2024-01-10 15:00",
    processedAt: "2024-01-11 09:00",
  },
  {
    id: "3",
    type: "delay",
    title: "延迟发货",
    description: "超过承诺时间48小时未发货",
    orderNo: "202401050001",
    penalty: "扣5分，赔付买家5元",
    score: 5,
    status: "processed",
    createdAt: "2024-01-05 00:00",
    processedAt: "2024-01-05 12:00",
  },
]

const typeConfig = {
  product: { icon: FileWarning, color: "text-orange-600 bg-orange-50" },
  service: { icon: ShieldAlert, color: "text-red-600 bg-red-50" },
  delay: { icon: AlertTriangle, color: "text-amber-600 bg-amber-50" },
}

const statusConfig = {
  pending: { label: "待处理", color: "bg-red-100 text-red-700" },
  appealing: { label: "申诉中", color: "bg-blue-100 text-blue-700" },
  processed: { label: "已处理", color: "bg-gray-100 text-gray-700" },
}

export default function ViolationsPage() {
  const scorePercent = (violationStats.score / violationStats.maxScore) * 100

  return (
    <div className="min-h-screen bg-muted/30 pb-20">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background border-b border-border">
        <div className="flex items-center h-14 px-4">
          <Link href="/merchant/dashboard" className="mr-3">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-lg font-semibold">违规管理</h1>
        </div>
      </header>
      
      {/* 违规概览 */}
      <div className="p-4">
        <Card className="p-4">
          <div className="flex items-center justify-between mb-4">
            <div>
              <p className="text-sm text-muted-foreground">店铺扣分</p>
              <div className="flex items-baseline gap-1 mt-1">
                <span className="text-3xl font-bold text-foreground">{violationStats.score}</span>
                <span className="text-sm text-muted-foreground">/ {violationStats.maxScore}分</span>
              </div>
            </div>
            <div className={cn(
              "w-16 h-16 rounded-full flex items-center justify-center",
              scorePercent > 50 ? "bg-red-100" : scorePercent > 25 ? "bg-amber-100" : "bg-green-100"
            )}>
              <span className={cn(
                "text-lg font-bold",
                scorePercent > 50 ? "text-red-600" : scorePercent > 25 ? "text-amber-600" : "text-green-600"
              )}>
                {scorePercent > 50 ? "警告" : scorePercent > 25 ? "注意" : "良好"}
              </span>
            </div>
          </div>
          
          {/* 进度条 */}
          <div className="w-full h-2 bg-muted rounded-full overflow-hidden">
            <div 
              className={cn(
                "h-full rounded-full transition-all",
                scorePercent > 50 ? "bg-red-500" : scorePercent > 25 ? "bg-amber-500" : "bg-green-500"
              )}
              style={{ width: `${scorePercent}%` }}
            />
          </div>
          
          <div className="flex items-center gap-4 mt-4 text-sm">
            <div className="flex items-center gap-1">
              <span className="text-muted-foreground">违规次数</span>
              <span className="font-medium">{violationStats.total}</span>
            </div>
            <div className="flex items-center gap-1">
              <span className="text-muted-foreground">待处理</span>
              <span className="font-medium text-red-600">{violationStats.pending}</span>
            </div>
          </div>
        </Card>
        
        {/* 扣分说明 */}
        <Card className="mt-3 p-3 bg-amber-50 dark:bg-amber-950/30 border-amber-200/50">
          <div className="flex items-start gap-2">
            <Info className="w-4 h-4 text-amber-600 mt-0.5" />
            <div className="text-xs text-muted-foreground">
              <p>扣分满48分将被暂停营业资格，每季度初清零一次。</p>
              <p className="mt-1">如有异议可在收到通知后3天内提交申诉。</p>
            </div>
          </div>
        </Card>
      </div>
      
      {/* 违规记录 */}
      <div className="px-4">
        <h2 className="font-medium mb-3">违规记录</h2>
        
        <div className="space-y-3">
          {violations.map(violation => {
            const config = typeConfig[violation.type as keyof typeof typeConfig]
            const status = statusConfig[violation.status as keyof typeof statusConfig]
            const Icon = config.icon
            
            return (
              <Card key={violation.id} className="p-4">
                <div className="flex items-start gap-3">
                  <div className={cn("w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0", config.color)}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between">
                      <h3 className="font-medium text-foreground">{violation.title}</h3>
                      <Badge className={cn("text-[10px]", status.color)}>{status.label}</Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">{violation.description}</p>
                    
                    <div className="mt-2 text-xs text-muted-foreground">
                      {violation.productTitle && <p>商品: {violation.productTitle}</p>}
                      {violation.orderNo && <p>订单: {violation.orderNo}</p>}
                    </div>
                    
                    <div className="mt-2 p-2 bg-red-50 dark:bg-red-950/30 rounded text-xs">
                      <span className="text-red-600">处罚: {violation.penalty}</span>
                    </div>
                    
                    <div className="flex items-center justify-between mt-3 pt-3 border-t border-border">
                      <span className="text-xs text-muted-foreground">{violation.createdAt}</span>
                      {violation.status === "pending" && (
                        <div className="flex gap-2">
                          <Button variant="outline" size="sm">申诉</Button>
                          <Button size="sm">去处理</Button>
                        </div>
                      )}
                      {violation.status === "processed" && (
                        <span className="text-xs text-muted-foreground">
                          处理时间: {violation.processedAt}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              </Card>
            )
          })}
        </div>
        
        {violations.length === 0 && (
          <div className="py-20 text-center">
            <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-4">
              <ShieldAlert className="w-8 h-8 text-green-600" />
            </div>
            <p className="text-muted-foreground">暂无违规记录，继续保持！</p>
          </div>
        )}
      </div>
    </div>
  )
}
