// apps/mobile/src/pages_backup_20260609/ai/cover-generate/index.vue
<template>
  <view class="cg-page">
    <view class="header-sticky">
      <view class="header-row">
        <text class="header-back" @click="uni.navigateBack()">‹</text>
        <text class="header-title">AI 封面生成</text>
        <text class="header-history" @click="showHistory = true; loadHistory()">📋</text>
      </view>
    </view>

    <view class="cg-body">
      <view class="field">
        <text class="field-label">内容标题</text>
        <input v-model="title" class="field-input" placeholder="输入文章/帖子标题" />
      </view>

      <view class="field">
        <view class="field-label-row">
          <text class="field-label">生成描述 (Prompt)</text>
          <text class="field-smart" :class="{ disabled: !title }" @click="handleSmartPrompt">✨ 智能生成</text>
        </view>
        <textarea v-model="prompt" class="field-textarea" placeholder="描述你想要的封面风格、元素、色调等（可选）" />
      </view>

      <view class="field">
        <text class="field-label">封面风格</text>
        <view class="style-grid">
          <view v-for="s in styles" :key="s.value" class="style-card" :class="{ active: selectedStyle === s.value }" @click="selectedStyle = s.value">
            <view class="style-thumb">🖼️</view>
            <text class="style-name">{{ s.label }}</text>
            <view v-if="selectedStyle === s.value" class="style-check">✓</view>
          </view>
        </view>
      </view>

      <view class="field">
        <text class="field-label">封面尺寸</text>
        <view class="size-row">
          <view v-for="s in sizeOptions" :key="s.value" class="size-card" :class="{ active: selectedSize === s.value }" @click="selectedSize = s.value">
            <text class="size-label">{{ s.label }}</text>
            <text class="size-ratio">{{ s.ratio }}</text>
          </view>
        </view>
      </view>

      <view class="field">
        <text class="field-label">生成数量</text>
        <view class="count-row">
          <view v-for="c in [2, 4, 6]" :key="c" class="count-card" :class="{ active: generateCount === c }" @click="generateCount = c">
            <text>{{ c }} 张</text>
          </view>
        </view>
      </view>

      <view class="gen-btn" :class="{ disabled: !title || generating }" @click="handleGenerate">
        <text v-if="generating">⏳ AI 生成中...</text>
        <text v-else>✨ 生成封面</text>
      </view>

      <view v-if="results.length > 0" class="results-section">
        <view class="results-head">
          <text class="results-title">生成结果</text>
          <text class="results-retry" @click="handleGenerate">🔄 重新生成</text>
        </view>
        <view class="results-grid">
          <view v-for="r in results" :key="r.id" class="result-card" :class="{ selected: selectedResultId === r.id }" @click="selectedResultId = r.id">
            <view class="result-img-wrap">
              <image v-if="r.url" :src="r.url" class="result-img" mode="aspectFill" />
              <text v-else class="result-placeholder">🖼️</text>
            </view>
            <view v-if="selectedResultId === r.id" class="result-check">✓</view>
          </view>
        </view>

        <view v-if="selectedResult" class="preview-card">
          <view class="preview-img">
            <image v-if="selectedResult.url" :src="selectedResult.url" class="preview-img-inner" mode="aspectFill" />
            <text v-else class="preview-placeholder">🖼️</text>
          </view>
          <view class="preview-meta">
            <text class="preview-tag">{{ styleLabel(selectedResult.style) }}</text>
            <text class="preview-tag">{{ selectedResult.size }}</text>
          </view>
          <view class="preview-actions">
            <view class="preview-btn outline" @click="handleSave"><text>💾 保存</text></view>
            <view class="preview-btn outline" @click="handleDownload"><text>📥 下载</text></view>
          </view>
          <view v-if="contentId" class="preview-btn primary" @click="handleApply"><text>应用为封面</text></view>
        </view>
      </view>
    </view>

    <view v-if="showHistory" class="sheet-mask" @click="showHistory = false">
      <view class="sheet-panel" @click.stop>
        <view class="sheet-handle" />
        <text class="sheet-title">生成历史</text>
        <scroll-view scroll-y class="sheet-body">
          <view v-if="historyLoading" class="history-loading">
            <view v-for="i in 3" :key="i" class="skeleton-card" />
          </view>
          <view v-else-if="history.length === 0" class="history-empty"><text>暂无生成历史</text></view>
          <view v-for="item in history" :key="item.id" class="history-item">
            <view class="hi-header">
              <text class="hi-title">{{ item.title }}</text>
              <text class="hi-time">{{ item.createdAt }}</text>
            </view>
            <view class="hi-thumbs">
              <view v-for="r in item.results" :key="r.id" class="hi-thumb" :class="{ active: r.id === item.selectedId }">
                <image v-if="r.url" :src="r.url" class="hi-thumb-img" mode="aspectFill" />
                <text v-else class="hi-thumb-empty">🖼️</text>
              </view>
            </view>
            <text class="hi-detail">查看详情 ›</text>
          </view>
        </scroll-view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onLoad } from 'vue'

const title = ref('')
const prompt = ref('')
const selectedStyle = ref('traditional')
const selectedSize = ref('16:9')
const generateCount = ref(4)
const generating = ref(false)
const results = ref<{ id: string; url: string; style: string; size: string; prompt: string }[]>([])
const selectedResultId = ref<string | null>(null)
const saving = ref(false)
const showHistory = ref(false)
const historyLoading = ref(false)
const history = ref<{ id: string; title: string; createdAt: string; selectedId: string; results: { id: string; url: string }[] }[]>([])
const contentId = ref('')
const contentSummary = ref('')

const styles = [
  { value: 'traditional', label: '传统中国风' },
  { value: 'minimal', label: '极简风格' },
  { value: 'ink', label: '水墨风格' },
  { value: 'modern', label: '现代设计' },
  { value: 'calligraphy', label: '书法风格' },
  { value: 'nature', label: '自然风景' },
]

const sizeOptions = [
  { value: '16:9', label: '横版', ratio: '16:9' },
  { value: '4:3', label: '标准', ratio: '4:3' },
  { value: '1:1', label: '方形', ratio: '1:1' },
  { value: '3:4', label: '竖版', ratio: '3:4' },
]

const selectedResult = computed(() => results.value.find(r => r.id === selectedResultId.value))

function styleLabel(v: string) { return styles.find(s => s.value === v)?.label || v }

function handleSmartPrompt() {
  if (!title.value) return
  prompt.value = `为"${title.value}"设计一个${styleLabel(selectedStyle.value)}风格的封面，要求画面精美、构图合理、色彩协调`
}

function handleGenerate() {
  if (!title.value.trim() || generating.value) return
  generating.value = true
  results.value = []
  selectedResultId.value = null
  setTimeout(() => {
    results.value = Array.from({ length: generateCount.value }, (_, i) => ({
      id: `r${Date.now()}_${i}`,
      url: '',
      style: selectedStyle.value,
      size: selectedSize.value,
      prompt: prompt.value || `为"${title.value}"生成的封面方案${i + 1}`,
    }))
    if (results.value.length > 0) selectedResultId.value = results.value[0].id
    generating.value = false
  }, 1500)
}

function handleSave() {
  if (saving.value) return
  saving.value = true
  setTimeout(() => { uni.showToast({ title: '已保存到素材库', icon: 'success' }); saving.value = false }, 500)
}

function handleDownload() { uni.showToast({ title: '下载中...', icon: 'loading' }) }

function handleApply() { uni.navigateBack() }

function loadHistory() {
  historyLoading.value = true
  setTimeout(() => { historyLoading.value = false }, 500)
}
</script>

<style scoped>
.cg-page { min-height: 100vh; background: #FAF8F5; padding-bottom: 40rpx; }
.header-sticky { position: sticky; top: 0; z-index: 30; background: linear-gradient(90deg, #C41E3A, #9a1830); }
.header-row { display: flex; align-items: center; justify-content: space-between; padding: 10rpx 24rpx; height: 80rpx; }
.header-back { font-size: 48rpx; color: #fff; width: 56rpx; }
.header-title { font-size: 30rpx; font-weight: 600; color: #fff; }
.header-history { font-size: 32rpx; width: 56rpx; text-align: right; }

.cg-body { padding: 24rpx; }
.field { margin-bottom: 24rpx; }
.field-label { font-size: 26rpx; font-weight: 500; color: #333; display: block; margin-bottom: 10rpx; }
.field-label-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10rpx; }
.field-smart { font-size: 22rpx; color: #C41E3A; }
.field-smart.disabled { opacity: 0.5; }
.field-input { background: #fff; border-radius: 14rpx; padding: 16rpx 18rpx; font-size: 26rpx; color: #333; }
.field-textarea { background: #fff; border-radius: 14rpx; padding: 16rpx 18rpx; font-size: 26rpx; color: #333; width: 100%; box-sizing: border-box; height: 160rpx; }

.style-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12rpx; }
.style-card { background: #fff; border-radius: 14rpx; padding: 20rpx 0 14rpx; text-align: center; border: 2px solid transparent; position: relative; }
.style-card.active { border-color: #C41E3A; background: #FFF5F5; }
.style-thumb { font-size: 36rpx; margin-bottom: 8rpx; }
.style-name { font-size: 22rpx; color: #666; }
.style-card.active .style-name { color: #C41E3A; }
.style-check { position: absolute; top: -6rpx; right: -6rpx; width: 36rpx; height: 36rpx; border-radius: 50%; background: #C41E3A; color: #fff; font-size: 20rpx; display: flex; align-items: center; justify-content: center; }

.size-row, .count-row { display: flex; gap: 12rpx; }
.size-card, .count-card { flex: 1; background: #fff; border-radius: 14rpx; padding: 16rpx 0; text-align: center; border: 2px solid transparent; }
.size-card.active, .count-card.active { border-color: #C41E3A; background: #FFF5F5; }
.size-label { font-size: 26rpx; font-weight: 500; color: #333; display: block; }
.size-card.active .size-label, .count-card.active text { color: #C41E3A; }
.size-ratio { font-size: 20rpx; color: #999; display: block; margin-top: 4rpx; }
.count-card text { font-size: 26rpx; color: #333; }

.gen-btn { background: linear-gradient(90deg, #C41E3A, #9a1830); border-radius: 16rpx; padding: 24rpx; text-align: center; margin-bottom: 32rpx; }
.gen-btn.disabled { opacity: 0.6; }
.gen-btn text { font-size: 30rpx; font-weight: 600; color: #fff; }

.results-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16rpx; }
.results-title { font-size: 28rpx; font-weight: 600; color: #333; }
.results-retry { font-size: 22rpx; color: #C41E3A; }
.results-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12rpx; margin-bottom: 20rpx; }
.result-card { border-radius: 14rpx; overflow: hidden; border: 2px solid transparent; position: relative; }
.result-card.selected { border-color: #C41E3A; }
.result-img-wrap { aspect-ratio: 16/9; background: #f0f0f0; }
.result-img { width: 100%; height: 100%; }
.result-placeholder { display: flex; align-items: center; justify-content: center; height: 100%; font-size: 48rpx; }
.result-check { position: absolute; top: 8rpx; right: 8rpx; width: 36rpx; height: 36rpx; border-radius: 50%; background: #C41E3A; color: #fff; font-size: 20rpx; display: flex; align-items: center; justify-content: center; }

.preview-card { background: #fff; border-radius: 16rpx; padding: 20rpx; }
.preview-img { border-radius: 12rpx; overflow: hidden; aspect-ratio: 16/9; background: #f0f0f0; margin-bottom: 14rpx; }
.preview-img-inner { width: 100%; height: 100%; }
.preview-placeholder { display: flex; align-items: center; justify-content: center; height: 100%; font-size: 56rpx; }
.preview-meta { display: flex; gap: 8rpx; margin-bottom: 16rpx; }
.preview-tag { font-size: 20rpx; color: #999; background: #F5F1EB; padding: 4rpx 12rpx; border-radius: 8rpx; }
.preview-actions { display: flex; gap: 12rpx; margin-bottom: 16rpx; }
.preview-btn { flex: 1; padding: 18rpx; border-radius: 14rpx; text-align: center; }
.preview-btn.outline { border: 1px solid #E8E0D5; }
.preview-btn.outline text { font-size: 24rpx; color: #666; }
.preview-btn.primary { background: #C41E3A; }
.preview-btn.primary text { font-size: 24rpx; color: #fff; }

.sheet-mask { position: fixed; inset: 0; z-index: 100; background: rgba(0,0,0,0.4); display: flex; align-items: flex-end; }
.sheet-panel { background: #fff; border-radius: 24rpx 24rpx 0 0; height: 70vh; width: 100%; display: flex; flex-direction: column; }
.sheet-handle { width: 60rpx; height: 6rpx; background: #E8E0D5; border-radius: 3rpx; margin: 16rpx auto; }
.sheet-title { font-size: 30rpx; font-weight: 600; color: #333; text-align: center; margin-bottom: 16rpx; }
.sheet-body { flex: 1; padding: 0 24rpx; }

.history-loading { display: flex; flex-direction: column; gap: 16rpx; }
.skeleton-card { height: 120rpx; background: #f0f0f0; border-radius: 14rpx; }
.history-empty { text-align: center; padding: 80rpx 0; color: #999; font-size: 26rpx; }
.history-item { background: #FAF8F5; border-radius: 14rpx; padding: 16rpx; margin-bottom: 16rpx; }
.hi-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10rpx; }
.hi-title { font-size: 26rpx; font-weight: 500; color: #333; max-width: 70%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.hi-time { font-size: 20rpx; color: #999; }
.hi-thumbs { display: flex; gap: 8rpx; overflow-x: auto; margin-bottom: 10rpx; }
.hi-thumb { width: 120rpx; height: 72rpx; border-radius: 8rpx; overflow: hidden; border: 2px solid transparent; flex-shrink: 0; background: #f0f0f0; }
.hi-thumb.active { border-color: #C41E3A; }
.hi-thumb-img { width: 100%; height: 100%; }
.hi-thumb-empty { display: flex; align-items: center; justify-content: center; font-size: 28rpx; height: 100%; }
.hi-detail { font-size: 22rpx; color: #C41E3A; }
</style>

// app/ai/cover-generate/page.tsx
'use client'

import { useState, useEffect, Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { ArrowLeft, Sparkles, Download, Check, RefreshCw, Save, History, ChevronRight, Wand2, Image as ImageIcon } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { DataState, LoadingSkeleton } from '@/components/data-state'
import { 
  getCoverStyles, 
  generateSmartPrompt, 
  generateCover, 
  saveCoverToLibrary, 
  downloadCover,
  getCoverHistory,
  getStyleName
} from '@/lib/api/ai-cover'
import type { CoverStyle, CoverSize, CoverGenerateResult, CoverStyleOption, CoverHistoryItem } from '@/lib/types/ai-cover'

export default function CoverGeneratePage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><LoadingSkeleton /></div>}>
      <CoverGenerateContent />
    </Suspense>
  )
}

function CoverGenerateContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  
  // 从 URL 获取内容信息
  const contentTitle = searchParams.get('title') || ''
  const contentSummary = searchParams.get('summary') || ''
  const contentId = searchParams.get('contentId') || ''
  const contentType = searchParams.get('contentType') || 'article'
  
  // 状态
  const [title, setTitle] = useState(contentTitle)
  const [prompt, setPrompt] = useState('')
  const [selectedStyle, setSelectedStyle] = useState<CoverStyle>('traditional')
  const [selectedSize, setSelectedSize] = useState<CoverSize>('16:9')
  const [generateCount, setGenerateCount] = useState(4)
  
  const [styles, setStyles] = useState<CoverStyleOption[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [results, setResults] = useState<CoverGenerateResult[]>([])
  const [selectedResultId, setSelectedResultId] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  
  const [showHistory, setShowHistory] = useState(false)
  const [history, setHistory] = useState<CoverHistoryItem[]>([])
  const [historyLoading, setHistoryLoading] = useState(false)

  // 尺寸选项
  const sizeOptions: { value: CoverSize; label: string; ratio: string }[] = [
    { value: '16:9', label: '横版', ratio: '16:9' },
    { value: '4:3', label: '标准', ratio: '4:3' },
    { value: '1:1', label: '方形', ratio: '1:1' },
    { value: '3:4', label: '竖版', ratio: '3:4' },
  ]

  // 加载风格选项
  useEffect(() => {
    const loadStyles = async () => {
      const res = await getCoverStyles()
      if (res.code === 200) {
        setStyles(res.data)
      }
      setLoading(false)
    }
    loadStyles()
  }, [])

  // 智能生成 Prompt
  const handleSmartPrompt = async () => {
    if (!title.trim()) return
    const res = await generateSmartPrompt(title, contentSummary, selectedStyle)
    if (res.code === 200) {
      setPrompt(res.data.prompt)
    }
  }

  // 生成封面
  const handleGenerate = async () => {
    if (!title.trim()) return
    
    setGenerating(true)
    setResults([])
    setSelectedResultId(null)
    
    try {
      const res = await generateCover({
        title,
        summary: contentSummary,
        prompt: prompt || undefined,
        style: selectedStyle,
        size: selectedSize,
        count: generateCount,
      })
      
      if (res.code === 200 && res.data.status === 'completed') {
        setResults(res.data.results)
        if (res.data.results.length > 0) {
          setSelectedResultId(res.data.results[0].id)
        }
      }
    } finally {
      setGenerating(false)
    }
  }

  // 保存到素材库
  const handleSave = async () => {
    if (!selectedResultId) return
    setSaving(true)
    try {
      const res = await saveCoverToLibrary(selectedResultId)
      if (res.code === 200) {
        alert('已保存到素材库')
      }
    } finally {
      setSaving(false)
    }
  }

  // 下载封面
  const handleDownload = async () => {
    if (!selectedResultId) return
    const res = await downloadCover(selectedResultId)
    if (res.code === 200) {
      // 触发下载
      const link = document.createElement('a')
      link.href = res.data.downloadUrl
      link.download = `cover_${selectedResultId}.png`
      link.click()
    }
  }

  // 应用封面（返回上一页并传递选中的封面）
  const handleApply = () => {
    const selected = results.find(r => r.id === selectedResultId)
    if (selected && contentId) {
      // 实际应用中这里会调用API更新内容封面
      router.back()
    }
  }

  // 加载历史记录
  const loadHistory = async () => {
    setHistoryLoading(true)
    const res = await getCoverHistory()
    if (res.code === 200) {
      setHistory(res.data)
    }
    setHistoryLoading(false)
  }

  const selectedResult = results.find(r => r.id === selectedResultId)

  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-10 bg-gradient-to-r from-[#C41E3A] to-[#9a1830] text-white">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <button onClick={() => router.back()} className="p-1">
              <ArrowLeft className="h-5 w-5" />
            </button>
            <h1 className="text-lg font-semibold">AI 封面生成</h1>
          </div>
          <button 
            onClick={() => { setShowHistory(true); loadHistory() }}
            className="p-2"
          >
            <History className="h-5 w-5" />
          </button>
        </div>
      </header>

      <DataState loading={loading}>
        <div className="p-4 space-y-6">
          {/* 内容标题 */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-700">内容标题</label>
            <Input
              value={title}
              onChange={e => setTitle(e.target.value)}
              placeholder="输入文章/帖子标题"
              className="bg-white"
            />
          </div>

          {/* Prompt 输入 */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-gray-700">生成描述 (Prompt)</label>
              <button 
                onClick={handleSmartPrompt}
                disabled={!title.trim()}
                className="flex items-center gap-1 text-xs text-[#C41E3A] disabled:opacity-50"
              >
                <Wand2 className="h-3 w-3" />
                智能生成
              </button>
            </div>
            <Textarea
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
              placeholder="描述你想要的封面风格、元素、色调等（可选，AI会根据标题自动生成）"
              rows={3}
              className="bg-white resize-none"
            />
          </div>

          {/* 风格选择 */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-gray-700">封面风格</label>
            <div className="grid grid-cols-3 gap-2">
              {styles.map(style => (
                <button
                  key={style.value}
                  onClick={() => setSelectedStyle(style.value)}
                  className={`relative p-3 rounded-lg border-2 transition-all ${
                    selectedStyle === style.value
                      ? 'border-[#C41E3A] bg-red-50'
                      : 'border-gray-200 bg-white'
                  }`}
                >
                  <div className="text-center">
                    <div className="w-full h-12 rounded bg-gray-100 mb-2 flex items-center justify-center">
                      <ImageIcon className="h-6 w-6 text-gray-400" />
                    </div>
                    <span className={`text-xs font-medium ${
                      selectedStyle === style.value ? 'text-[#C41E3A]' : 'text-gray-700'
                    }`}>
                      {style.label}
                    </span>
                  </div>
                  {selectedStyle === style.value && (
                    <div className="absolute -top-1 -right-1 w-5 h-5 bg-[#C41E3A] rounded-full flex items-center justify-center">
                      <Check className="h-3 w-3 text-white" />
                    </div>
                  )}
                </button>
              ))}
            </div>
          </div>

          {/* 尺寸选择 */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-gray-700">封面尺寸</label>
            <div className="flex gap-2">
              {sizeOptions.map(size => (
                <button
                  key={size.value}
                  onClick={() => setSelectedSize(size.value)}
                  className={`flex-1 py-2 px-3 rounded-lg border-2 text-center transition-all ${
                    selectedSize === size.value
                      ? 'border-[#C41E3A] bg-red-50 text-[#C41E3A]'
                      : 'border-gray-200 bg-white text-gray-700'
                  }`}
                >
                  <div className="text-sm font-medium">{size.label}</div>
                  <div className="text-xs text-gray-500">{size.ratio}</div>
                </button>
              ))}
            </div>
          </div>

          {/* 生成数量 */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-gray-700">生成数量</label>
            <div className="flex gap-2">
              {[2, 4, 6].map(count => (
                <button
                  key={count}
                  onClick={() => setGenerateCount(count)}
                  className={`flex-1 py-2 rounded-lg border-2 text-sm font-medium transition-all ${
                    generateCount === count
                      ? 'border-[#C41E3A] bg-red-50 text-[#C41E3A]'
                      : 'border-gray-200 bg-white text-gray-700'
                  }`}
                >
                  {count} 张
                </button>
              ))}
            </div>
          </div>

          {/* 生成按钮 */}
          <Button
            onClick={handleGenerate}
            disabled={!title.trim() || generating}
            className="w-full h-12 bg-gradient-to-r from-[#C41E3A] to-[#9a1830] hover:from-[#a31830] hover:to-[#7a1428] text-white font-semibold"
          >
            {generating ? (
              <div className="flex items-center gap-2">
                <RefreshCw className="h-5 w-5 animate-spin" />
                AI 生成中...
              </div>
            ) : (
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                生成封面
              </div>
            )}
          </Button>

          {/* 生成结果 */}
          {results.length > 0 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold text-gray-800">生成结果</h3>
                <button
                  onClick={handleGenerate}
                  disabled={generating}
                  className="flex items-center gap-1 text-sm text-[#C41E3A]"
                >
                  <RefreshCw className="h-4 w-4" />
                  重新生成
                </button>
              </div>

              {/* 结果网格 */}
              <div className="grid grid-cols-2 gap-3">
                {results.map(result => (
                  <button
                    key={result.id}
                    onClick={() => setSelectedResultId(result.id)}
                    className={`relative rounded-lg overflow-hidden border-2 transition-all ${
                      selectedResultId === result.id
                        ? 'border-[#C41E3A] ring-2 ring-[#C41E3A]/30'
                        : 'border-gray-200'
                    }`}
                  >
                    <div className="aspect-video bg-gray-100">
                      <img
                        src={result.url}
                        alt="生成的封面"
                        className="w-full h-full object-cover"
                      />
                    </div>
                    {selectedResultId === result.id && (
                      <div className="absolute top-2 right-2 w-6 h-6 bg-[#C41E3A] rounded-full flex items-center justify-center">
                        <Check className="h-4 w-4 text-white" />
                      </div>
                    )}
                  </button>
                ))}
              </div>

              {/* 选中的封面预览 */}
              {selectedResult && (
                <div className="bg-white rounded-xl p-4 space-y-4">
                  <div className="aspect-video rounded-lg overflow-hidden bg-gray-100">
                    <img
                      src={selectedResult.url}
                      alt="选中的封面"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <span className="px-2 py-0.5 bg-gray-100 rounded">
                        {getStyleName(selectedResult.style)}
                      </span>
                      <span className="px-2 py-0.5 bg-gray-100 rounded">
                        {selectedResult.size}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 line-clamp-2">
                      {selectedResult.prompt}
                    </p>
                  </div>

                  {/* 操作按钮 */}
                  <div className="flex gap-3">
                    <Button
                      variant="outline"
                      onClick={handleSave}
                      disabled={saving}
                      className="flex-1 border-gray-300"
                    >
                      <Save className="h-4 w-4 mr-2" />
                      保存
                    </Button>
                    <Button
                      variant="outline"
                      onClick={handleDownload}
                      className="flex-1 border-gray-300"
                    >
                      <Download className="h-4 w-4 mr-2" />
                      下载
                    </Button>
                  </div>

                  {contentId && (
                    <Button
                      onClick={handleApply}
                      className="w-full bg-[#C41E3A] hover:bg-[#a31830] text-white"
                    >
                      应用为封面
                    </Button>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </DataState>

      {/* 历史记录弹层 */}
      <Sheet open={showHistory} onOpenChange={setShowHistory}>
        <SheetContent side="bottom" className="h-[70vh] rounded-t-2xl">
          <SheetHeader>
            <SheetTitle>生成历史</SheetTitle>
          </SheetHeader>
          
          <div className="mt-4 space-y-4 overflow-y-auto max-h-[calc(70vh-80px)]">
            {historyLoading ? (
              <div className="space-y-4">
                {[1, 2, 3].map(i => (
                  <div key={i} className="animate-pulse">
                    <div className="h-24 bg-gray-200 rounded-lg" />
                  </div>
                ))}
              </div>
            ) : history.length === 0 ? (
              <div className="text-center py-12 text-gray-500">
                暂无生成历史
              </div>
            ) : (
              history.map(item => (
                <div
                  key={item.id}
                  className="bg-gray-50 rounded-lg p-3 space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <h4 className="font-medium text-gray-800 line-clamp-1">
                      {item.title}
                    </h4>
                    <span className="text-xs text-gray-500">
                      {item.createdAt}
                    </span>
                  </div>
                  <div className="flex gap-2 overflow-x-auto">
                    {item.results.map(result => (
                      <div
                        key={result.id}
                        className={`flex-shrink-0 w-20 h-12 rounded overflow-hidden border-2 ${
                          result.id === item.selectedId
                            ? 'border-[#C41E3A]'
                            : 'border-transparent'
                        }`}
                      >
                        <img
                          src={result.url}
                          alt=""
                          className="w-full h-full object-cover"
                        />
                      </div>
                    ))}
                  </div>
                  <button className="flex items-center gap-1 text-xs text-[#C41E3A]">
                    查看详情 <ChevronRight className="h-3 w-3" />
                  </button>
                </div>
              ))
            )}
          </div>
        </SheetContent>
      </Sheet>
    </div>
  )
}
