// app/live/end/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import Image from "next/image"
import { ChevronLeft, Play, Eye, Users, Heart, Gift, UserPlus, Check, ChevronRight, Radio } from "lucide-react"
import { liveApi, type LiveRoom } from "@/lib/api"

// Mock数据
const mockRoom: LiveRoom & { 
  stats: { totalViewers: number; peakViewers: number; totalLikes: number; totalGifts: number; duration: number }
  hasReplay: boolean
  replayUrl?: string
} = {
  id: "1",
  title: "《周易》六十四卦精讲：乾卦的智慧",
  cover: "/placeholder.svg",
  status: "replay",
  host: {
    id: "h1",
    name: "易经大师·张道长",
    avatar: "/placeholder.svg",
    followers: 12580,
  },
  viewers: 0,
  likes: 8532,
  startTime: "2024-01-15T14:00:00",
  endTime: "2024-01-15T16:30:00",
  category: "易经",
  tags: ["周易", "六十四卦", "国学"],
  stats: {
    totalViewers: 15680,
    peakViewers: 3256,
    totalLikes: 8532,
    totalGifts: 1256,
    duration: 9000,
  },
  hasReplay: true,
  replayUrl: "/live/1?replay=true",
}

const mockRecommendLives: LiveRoom[] = [
  { id: "2", title: "紫微斗数入门：认识你的命盘", cover: "/placeholder.svg", status: "preview", host: { id: "h1", name: "易经大师·张道长", avatar: "/placeholder.svg", followers: 12580 }, viewers: 0, likes: 0, startTime: "2024-01-20T14:00:00", category: "紫微斗数", isBooked: false, bookedCount: 856 },
  { id: "3", title: "风水布局与家居吉凶", cover: "/placeholder.svg", status: "live", host: { id: "h2", name: "风水师·李明", avatar: "/placeholder.svg", followers: 8960 }, viewers: 1256, likes: 3200, category: "风水", tags: ["风水"] },
]

const mockRecommendCourses = [
  { id: "c1", title: "周易六十四卦系统课", cover: "/placeholder.svg", price: 299, lessons: 64 },
  { id: "c2", title: "紫微斗数精讲班", cover: "/placeholder.svg", price: 399, lessons: 48 },
]

function LiveEndContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const roomId = searchParams.get('id')
  
  const [room, setRoom] = useState(mockRoom)
  const [isFollowing, setIsFollowing] = useState(false)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 500)
    return () => clearTimeout(timer)
  }, [])

  const formatDuration = (seconds: number) => {
    const hours = Math.floor(seconds / 3600)
    const mins = Math.floor((seconds % 3600) / 60)
    if (hours > 0) return `${hours}小时${mins}分钟`
    return `${mins}分钟`
  }

  const formatNumber = (num: number) => {
    if (num >= 10000) return (num / 10000).toFixed(1) + '万'
    return num.toString()
  }

  const handleFollow = () => {
    setIsFollowing(!isFollowing)
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-[#FAF8F5]">
        <div className="h-64 bg-gray-200 animate-pulse" />
        <div className="p-4 space-y-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="bg-white rounded-2xl h-32 animate-pulse" />
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-24">
      {/* 封面区域 */}
      <div className="relative h-64">
        <Image
          src={room.cover}
          alt={room.title}
          fill
          className="object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-black/50 via-transparent to-black/70" />
        
        {/* 顶部导航 */}
        <div className="absolute top-0 left-0 right-0 p-4 flex items-center justify-between">
          <button
            onClick={() => router.back()}
            className="w-8 h-8 bg-black/30 backdrop-blur-sm rounded-full flex items-center justify-center"
          >
            <ChevronLeft className="w-5 h-5 text-white" />
          </button>
        </div>

        {/* 直播已结束标识 */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
          <div className="bg-black/60 backdrop-blur-sm rounded-2xl px-6 py-4 text-center">
            <div className="w-12 h-12 mx-auto mb-2 rounded-full bg-white/20 flex items-center justify-center">
              <Radio className="w-6 h-6 text-white" />
            </div>
            <div className="text-white font-medium">直播已结束</div>
            <div className="text-white/70 text-sm mt-1">
              时长 {formatDuration(room.stats.duration)}
            </div>
          </div>
        </div>

        {/* 底部信息 */}
        <div className="absolute bottom-0 left-0 right-0 p-4">
          <h1 className="text-white font-bold text-lg line-clamp-2">{room.title}</h1>
          <div className="flex items-center gap-2 mt-2">
            {room.tags?.map(tag => (
              <span key={tag} className="px-2 py-0.5 bg-white/20 text-white text-xs rounded-full">
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* 主播信息 */}
      <div className="mx-4 -mt-6 relative z-10 bg-white rounded-2xl p-4 shadow-sm">
        <div className="flex items-center justify-between">
          <div
            className="flex items-center gap-3 flex-1 cursor-pointer"
            onClick={() => router.push(`/user/${room.host.id}`)}
          >
            <div className="relative w-12 h-12">
              <Image
                src={room.host.avatar}
                alt={room.host.name}
                fill
                className="rounded-full object-cover"
              />
            </div>
            <div>
              <div className="font-medium text-[#2C2C2C]">{room.host.name}</div>
              <div className="text-sm text-[#999999]">{formatNumber(room.host.followers)} 粉丝</div>
            </div>
          </div>
          <button
            onClick={handleFollow}
            className={`flex items-center gap-1 px-4 py-2 rounded-full text-sm font-medium transition-all ${
              isFollowing
                ? "bg-[#FAF8F5] text-[#999999]"
                : "bg-[#C41E3A] text-white"
            }`}
          >
            {isFollowing ? (
              <>
                <Check className="w-4 h-4" />
                已关注
              </>
            ) : (
              <>
                <UserPlus className="w-4 h-4" />
                关注
              </>
            )}
          </button>
        </div>
      </div>

      {/* 直播数据统计 */}
      <div className="mx-4 mt-4 bg-white rounded-2xl p-4 shadow-sm">
        <h2 className="font-medium text-[#2C2C2C] mb-4">直播数据</h2>
        <div className="grid grid-cols-4 gap-2">
          <div className="text-center p-3 bg-[#FAF8F5] rounded-xl">
            <Eye className="w-5 h-5 text-[#C41E3A] mx-auto mb-1" />
            <div className="text-lg font-bold text-[#2C2C2C]">{formatNumber(room.stats.totalViewers)}</div>
            <div className="text-xs text-[#999999]">总观看</div>
          </div>
          <div className="text-center p-3 bg-[#FAF8F5] rounded-xl">
            <Users className="w-5 h-5 text-[#C9A96E] mx-auto mb-1" />
            <div className="text-lg font-bold text-[#2C2C2C]">{formatNumber(room.stats.peakViewers)}</div>
            <div className="text-xs text-[#999999]">峰值在线</div>
          </div>
          <div className="text-center p-3 bg-[#FAF8F5] rounded-xl">
            <Heart className="w-5 h-5 text-pink-500 mx-auto mb-1" />
            <div className="text-lg font-bold text-[#2C2C2C]">{formatNumber(room.stats.totalLikes)}</div>
            <div className="text-xs text-[#999999]">总点赞</div>
          </div>
          <div className="text-center p-3 bg-[#FAF8F5] rounded-xl">
            <Gift className="w-5 h-5 text-orange-500 mx-auto mb-1" />
            <div className="text-lg font-bold text-[#2C2C2C]">{formatNumber(room.stats.totalGifts)}</div>
            <div className="text-xs text-[#999999]">礼物收入</div>
          </div>
        </div>
      </div>

      {/* 讲师其他直播 */}
      <div className="mx-4 mt-4 bg-white rounded-2xl p-4 shadow-sm">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-medium text-[#2C2C2C]">讲师其他直播</h2>
          <button
            onClick={() => router.push(`/user/${room.host.id}?tab=lives`)}
            className="flex items-center text-sm text-[#999999]"
          >
            查看全部
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
        <div className="space-y-3">
          {mockRecommendLives.map(live => (
            <div
              key={live.id}
              onClick={() => {
                if (live.status === "live") {
                  router.push(`/live/${live.id}`)
                } else if (live.status === "preview") {
                  router.push(`/live/preview?id=${live.id}`)
                }
              }}
              className="flex gap-3 cursor-pointer"
            >
              <div className="relative w-24 h-16 flex-shrink-0">
                <Image
                  src={live.cover}
                  alt={live.title}
                  fill
                  className="rounded-lg object-cover"
                />
                {live.status === "live" && (
                  <div className="absolute top-1 left-1 flex items-center gap-1 px-1.5 py-0.5 bg-[#C41E3A] text-white text-xs rounded">
                    <span className="w-1.5 h-1.5 bg-white rounded-full animate-pulse" />
                    直播中
                  </div>
                )}
                {live.status === "preview" && (
                  <div className="absolute top-1 left-1 px-1.5 py-0.5 bg-[#C9A96E] text-white text-xs rounded">
                    预告
                  </div>
                )}
              </div>
              <div className="flex-1 min-w-0">
                <div className="font-medium text-[#2C2C2C] text-sm line-clamp-2">{live.title}</div>
                <div className="flex items-center gap-2 mt-1 text-xs text-[#999999]">
                  {live.status === "live" ? (
                    <span>{formatNumber(live.viewers)} 观看</span>
                  ) : (
                    <span>{live.bookedCount} 人预约</span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 相关课程推荐 */}
      <div className="mx-4 mt-4 bg-white rounded-2xl p-4 shadow-sm">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-medium text-[#2C2C2C]">相关课程推荐</h2>
          <button
            onClick={() => router.push('/courses')}
            className="flex items-center text-sm text-[#999999]"
          >
            查看更多
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
        <div className="grid grid-cols-2 gap-3">
          {mockRecommendCourses.map(course => (
            <div
              key={course.id}
              onClick={() => router.push(`/courses/${course.id}`)}
              className="bg-[#FAF8F5] rounded-xl overflow-hidden cursor-pointer"
            >
              <div className="relative aspect-video">
                <Image
                  src={course.cover}
                  alt={course.title}
                  fill
                  className="object-cover"
                />
              </div>
              <div className="p-3">
                <div className="font-medium text-[#2C2C2C] text-sm line-clamp-1">{course.title}</div>
                <div className="flex items-center justify-between mt-2">
                  <span className="text-[#C41E3A] font-bold">¥{course.price}</span>
                  <span className="text-xs text-[#999999]">{course.lessons}课时</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 底部固定按钮 */}
      <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-[#E8E3DB] p-4 safe-area-inset-bottom">
        <div className="flex gap-3">
          <button
            onClick={() => router.push(`/community/circles?hostId=${room.host.id}`)}
            className="flex-1 py-3 border border-[#E8E3DB] rounded-xl text-[#2C2C2C] font-medium"
          >
            进入讲师圈子
          </button>
          {room.hasReplay && (
            <button
              onClick={() => router.push(room.replayUrl || `/live/${room.id}?replay=true`)}
              className="flex-1 py-3 bg-[#C41E3A] text-white rounded-xl font-medium flex items-center justify-center gap-2"
            >
              <Play className="w-4 h-4" />
              查看回放
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

function LoadingFallback() {
  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      <div className="h-64 bg-gray-200 animate-pulse" />
      <div className="p-4 space-y-4">
        {[1, 2, 3].map(i => (
          <div key={i} className="bg-white rounded-2xl h-32 animate-pulse" />
        ))}
      </div>
    </div>
  )
}

export default function LiveEndPage() {
  return (
    <Suspense fallback={<LoadingFallback />}>
      <LiveEndContent />
    </Suspense>
  )
}

// apps/mobile/src/pkg-live/end/index.vue
<template>
  <view class="page">
    <!-- 封面区域 -->
    <view class="cover">
      <image
        class="cover-img"
        :src="room.cover"
        mode="aspectFill"
      />
      <view class="cover-mask" />

      <!-- 顶部导航 -->
      <view
        class="cover-nav"
        :style="{ paddingTop: statusBarHeight + 'px' }"
      >
        <view
          class="nav-back"
          @tap="goBack"
        >
          <AppIcon
            name="chevron-left"
            :size="40"
            color="#fff"
          />
        </view>
      </view>

      <!-- 直播已结束标识 -->
      <view class="end-badge">
        <view class="end-badge-inner">
          <view class="end-icon">
            <AppIcon
              name="radio"
              :size="48"
              color="#fff"
            />
          </view>
          <text class="end-title">
            直播已结束
          </text>
          <text class="end-duration">
            时长 {{ formatDuration(room.stats.duration) }}
          </text>
        </view>
      </view>

      <!-- 底部信息 -->
      <view class="cover-info">
        <text class="cover-title">
          {{ room.title }}
        </text>
        <view class="cover-tags">
          <text
            v-for="tag in room.tags"
            :key="tag"
            class="cover-tag"
          >
            {{ tag }}
          </text>
        </view>
      </view>
    </view>

    <!-- 主播信息 -->
    <view class="host-card">
      <view class="host-left">
        <image
          class="host-avatar"
          :src="room.hostAvatar"
          mode="aspectFill"
        />
        <view class="host-meta">
          <text class="host-name">
            {{ room.hostName }}
          </text>
          <text class="host-fans">
            {{ formatNumber(room.hostFollowers) }} 粉丝
          </text>
        </view>
      </view>
      <view
        class="follow-btn"
        :class="{ followed: isFollowing }"
        @tap="isFollowing = !isFollowing"
      >
        <AppIcon
          :name="isFollowing ? 'check' : 'user-plus'"
          :size="32"
          :color="isFollowing ? '#999999' : '#fff'"
        />
        <text class="follow-txt">
          {{ isFollowing ? '已关注' : '关注' }}
        </text>
      </view>
    </view>

    <!-- 直播数据统计 -->
    <view class="card">
      <text class="card-title">
        直播数据
      </text>
      <view class="stats-grid">
        <view class="stat-item">
          <AppIcon
            name="eye"
            :size="40"
            color="#C41E3A"
          />
          <text class="stat-num">
            {{ formatNumber(room.stats.totalViewers) }}
          </text>
          <text class="stat-label">
            总观看
          </text>
        </view>
        <view class="stat-item">
          <AppIcon
            name="users"
            :size="40"
            color="#C9A96E"
          />
          <text class="stat-num">
            {{ formatNumber(room.stats.peakViewers) }}
          </text>
          <text class="stat-label">
            峰值在线
          </text>
        </view>
        <view class="stat-item">
          <AppIcon
            name="heart"
            :size="40"
            color="#ec4899"
          />
          <text class="stat-num">
            {{ formatNumber(room.stats.totalLikes) }}
          </text>
          <text class="stat-label">
            总点赞
          </text>
        </view>
        <view class="stat-item">
          <AppIcon
            name="gift"
            :size="40"
            color="#f97316"
          />
          <text class="stat-num">
            {{ formatNumber(room.stats.totalGifts) }}
          </text>
          <text class="stat-label">
            礼物收入
          </text>
        </view>
      </view>
    </view>

    <!-- 讲师其他直播 -->
    <view class="card">
      <view class="card-head">
        <text class="card-title">
          讲师其他直播
        </text>
        <view class="card-more">
          <text class="more-txt">
            查看全部
          </text>
          <AppIcon
            name="chevron-right"
            :size="32"
            color="#999999"
          />
        </view>
      </view>
      <view class="live-list">
        <view
          v-for="live in recommendLives"
          :key="live.id"
          class="live-item"
        >
          <view class="live-cover">
            <image
              class="live-cover-img"
              :src="live.cover"
              mode="aspectFill"
            />
            <view
              v-if="live.status === 'live'"
              class="live-tag live-tag-live"
            >
              <view class="live-dot" />
              <text class="live-tag-txt">
                直播中
              </text>
            </view>
            <view
              v-else
              class="live-tag live-tag-preview"
            >
              <text class="live-tag-txt">
                预告
              </text>
            </view>
          </view>
          <view class="live-meta">
            <text class="live-title">
              {{ live.title }}
            </text>
            <text class="live-stat">
              {{ live.status === 'live' ? formatNumber(live.viewers) + ' 观看' : live.bookedCount + ' 人预约' }}
            </text>
          </view>
        </view>
      </view>
    </view>

    <!-- 相关课程推荐 -->
    <view class="card">
      <view class="card-head">
        <text class="card-title">
          相关课程推荐
        </text>
        <view class="card-more">
          <text class="more-txt">
            查看更多
          </text>
          <AppIcon
            name="chevron-right"
            :size="32"
            color="#999999"
          />
        </view>
      </view>
      <view class="course-grid">
        <view
          v-for="course in recommendCourses"
          :key="course.id"
          class="course-item"
        >
          <image
            class="course-cover"
            :src="course.cover"
            mode="aspectFill"
          />
          <view class="course-meta">
            <text class="course-title">
              {{ course.title }}
            </text>
            <view class="course-foot">
              <text class="course-price">
                ¥{{ course.price }}
              </text>
              <text class="course-lessons">
                {{ course.lessons }}课时
              </text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 底部固定按钮 -->
    <view
      class="bottom-bar"
      :style="{ paddingBottom: 'calc(env(safe-area-inset-bottom) + 16rpx)' }"
    >
      <view class="bottom-btn bottom-btn-outline">
        <text class="bottom-btn-txt-outline">
          进入讲师圈子
        </text>
      </view>
      <view
        v-if="room.hasReplay"
        class="bottom-btn bottom-btn-primary"
      >
        <AppIcon
          name="play"
          :size="32"
          color="#fff"
        />
        <text class="bottom-btn-txt-primary">
          查看回放
        </text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'
import { liveEndRoom, liveEndRecommendLives, liveEndRecommendCourses } from '@/lib/live-data'

const statusBarHeight = ref(0)

// UI 临时状态
const room = ref(liveEndRoom)
const recommendLives = ref(liveEndRecommendLives)
const recommendCourses = ref(liveEndRecommendCourses)
const isFollowing = ref(false)

function formatDuration(seconds: number): string {
  const hours = Math.floor(seconds / 3600)
  const mins = Math.floor((seconds % 3600) / 60)
  if (hours > 0) return `${hours}小时${mins}分钟`
  return `${mins}分钟`
}
function formatNumber(num: number): string {
  if (num >= 10000) return (num / 10000).toFixed(1) + '万'
  return String(num)
}
</script>

<style scoped>
.page {
  min-height: 100vh;
  background: #FAF8F5;
  padding-bottom: 192rpx;
}

/* 封面区域 */
.cover {
  position: relative;
  height: 512rpx;
}
.cover-img {
  width: 100%;
  height: 100%;
}
.cover-mask {
  position: absolute;
  inset: 0;
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0.5), transparent, rgba(0, 0, 0, 0.7));
}
.cover-nav {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  padding: 32rpx;
}
.nav-back {
  width: 64rpx;
  height: 64rpx;
  background: rgba(0, 0, 0, 0.3);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.end-badge {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.end-badge-inner {
  background: rgba(0, 0, 0, 0.6);
  border-radius: 32rpx;
  padding: 32rpx 48rpx;
  display: flex;
  flex-direction: column;
  align-items: center;
}
.end-icon {
  width: 96rpx;
  height: 96rpx;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 16rpx;
}
.end-title {
  font-size: 30rpx;
  font-weight: 500;
  color: #fff;
}
.end-duration {
  font-size: 26rpx;
  color: rgba(255, 255, 255, 0.7);
  margin-top: 8rpx;
}
.cover-info {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 32rpx;
}
.cover-title {
  font-size: 36rpx;
  font-weight: 700;
  color: #fff;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.cover-tags {
  display: flex;
  gap: 16rpx;
  margin-top: 16rpx;
}
.cover-tag {
  padding: 4rpx 16rpx;
  background: rgba(255, 255, 255, 0.2);
  color: #fff;
  font-size: 22rpx;
  border-radius: 999rpx;
}

/* 主播信息 */
.host-card {
  margin: -48rpx 32rpx 0;
  position: relative;
  z-index: 10;
  background: #fff;
  border-radius: 32rpx;
  padding: 32rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.host-left {
  display: flex;
  align-items: center;
  gap: 24rpx;
  flex: 1;
}
.host-avatar {
  width: 96rpx;
  height: 96rpx;
  border-radius: 50%;
  background: #eee;
  flex-shrink: 0;
}
.host-meta {
  display: flex;
  flex-direction: column;
}
.host-name {
  font-size: 30rpx;
  font-weight: 500;
  color: #2C2C2C;
}
.host-fans {
  font-size: 26rpx;
  color: #999999;
  margin-top: 4rpx;
}
.follow-btn {
  display: flex;
  align-items: center;
  gap: 8rpx;
  padding: 16rpx 32rpx;
  background: #C41E3A;
  border-radius: 999rpx;
  flex-shrink: 0;
}
.follow-btn.followed {
  background: #FAF8F5;
}
.follow-txt {
  font-size: 26rpx;
  font-weight: 500;
  color: #fff;
}
.follow-btn.followed .follow-txt {
  color: #999999;
}

/* 卡片通用 */
.card {
  margin: 32rpx 32rpx 0;
  background: #fff;
  border-radius: 32rpx;
  padding: 32rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
}
.card-title {
  font-size: 30rpx;
  font-weight: 500;
  color: #2C2C2C;
}
.card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 32rpx;
}
.card-more {
  display: flex;
  align-items: center;
}
.more-txt {
  font-size: 26rpx;
  color: #999999;
}

/* 统计 */
.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16rpx;
  margin-top: 32rpx;
}
.stat-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 24rpx 8rpx;
  background: #FAF8F5;
  border-radius: 24rpx;
}
.stat-num {
  font-size: 34rpx;
  font-weight: 700;
  color: #2C2C2C;
  margin-top: 8rpx;
}
.stat-label {
  font-size: 22rpx;
  color: #999999;
  margin-top: 4rpx;
}

/* 讲师其他直播 */
.live-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.live-item {
  display: flex;
  gap: 24rpx;
}
.live-cover {
  position: relative;
  width: 192rpx;
  height: 128rpx;
  flex-shrink: 0;
}
.live-cover-img {
  width: 100%;
  height: 100%;
  border-radius: 16rpx;
  background: #eee;
}
.live-tag {
  position: absolute;
  top: 8rpx;
  left: 8rpx;
  display: flex;
  align-items: center;
  gap: 6rpx;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
}
.live-tag-live {
  background: #C41E3A;
}
.live-tag-preview {
  background: #C9A96E;
}
.live-dot {
  width: 12rpx;
  height: 12rpx;
  background: #fff;
  border-radius: 50%;
}
.live-tag-txt {
  font-size: 20rpx;
  color: #fff;
}
.live-meta {
  flex: 1;
  min-width: 0;
}
.live-title {
  font-size: 26rpx;
  font-weight: 500;
  color: #2C2C2C;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.live-stat {
  font-size: 22rpx;
  color: #999999;
  margin-top: 8rpx;
}

/* 课程推荐 */
.course-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 24rpx;
}
.course-item {
  background: #FAF8F5;
  border-radius: 24rpx;
  overflow: hidden;
}
.course-cover {
  width: 100%;
  height: 180rpx;
  background: #eee;
}
.course-meta {
  padding: 24rpx;
}
.course-title {
  font-size: 26rpx;
  font-weight: 500;
  color: #2C2C2C;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
.course-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 16rpx;
}
.course-price {
  font-size: 28rpx;
  font-weight: 700;
  color: #C41E3A;
}
.course-lessons {
  font-size: 22rpx;
  color: #999999;
}

/* 底部固定按钮 */
.bottom-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #fff;
  border-top: 1rpx solid #E8E3DB;
  padding: 16rpx 32rpx;
  display: flex;
  gap: 24rpx;
}
.bottom-btn {
  flex: 1;
  height: 88rpx;
  border-radius: 24rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8rpx;
}
.bottom-btn-outline {
  border: 1rpx solid #E8E3DB;
}
.bottom-btn-txt-outline {
  font-size: 28rpx;
  font-weight: 500;
  color: #2C2C2C;
}
.bottom-btn-primary {
  background: #C41E3A;
}
.bottom-btn-txt-primary {
  font-size: 28rpx;
  font-weight: 500;
  color: #fff;
}
</style>
