// apps/mobile/.backup_vue3_converted/pages/mine/role-panels/admin-panel/index.vue
<template>
  <view class="min-h-screen" style="background-color: #FAF8F5; padding-bottom: 80px;">
    <!-- Header -->
    <view class="sticky top-0 z-50" style="background: linear-gradient(to right, #C41E3A, #A01830); color: #FFFFFF;">
      <view class="flex items-center justify-between px-4 py-3">
        <view class="flex items-center gap-3">
          <view @click="goBack" class="p-1" style="cursor: pointer;">
            <text style="color: #FFFFFF; font-size: 22px; line-height: 1;">❮</text>
          </view>
          <text class="font-semibold" style="font-size: 18px;">管理中心</text>
        </view>
        <view class="relative p-2" style="cursor: pointer;">
          <text style="color: #FFFFFF; font-size: 18px;"></text>
          <view v-if="totalPending > 0" class="absolute top-1 right-1 w-2 h-2 rounded-full" style="background-color: #facc15;" />
        </view>
      </view>

      <!-- 管理员信息 -->
      <view class="px-4 pb-4">
        <view class="flex items-center gap-3">
          <view class="w-12 h-12 rounded-full flex items-center justify-center" style="background-color: rgba(255,255,255,0.2);">
            <text style="color: #FFFFFF; font-size: 20px;"></text>
          </view>
          <view>
            <text class="font-medium block" style="color: #FFFFFF;">{{ adminInfo.name }}</text>
            <text class="text-sm block" style="color: rgba(255,255,255,0.8);">{{ adminInfo.roleName }}</text>
          </view>
        </view>
      </view>
    </view>

    <!-- Loading State -->
    <view v-if="loading" class="space-y-6 p-4">
      <!-- 管理员信息骨架 -->
      <view class="flex items-center gap-3">
        <view class="w-12 h-12 rounded-full skeleton-pulse" style="background-color: #F0EBE5;" />
        <view class="space-y-2">
          <view class="h-5 w-24 rounded skeleton-pulse" style="background-color: #F0EBE5;" />
          <view class="h-4 w-32 rounded skeleton-pulse" style="background-color: #F0EBE5;" />
        </view>
      </view>

      <!-- 数据概览骨架 -->
      <view class="grid grid-cols-2 gap-3">
        <view v-for="i in 4" :key="i" class="h-24 rounded-xl skeleton-pulse" style="background-color: #F0EBE5;" />
      </view>

      <!-- 快捷功能骨架 -->
      <view class="grid grid-cols-4 gap-3">
        <view v-for="i in 8" :key="'action-' + i" class="h-20 rounded-xl skeleton-pulse" style="background-color: #F0EBE5;" />
      </view>

      <!-- 待处理事项骨架 -->
      <view class="space-y-3">
        <view v-for="i in 3" :key="'pending-' + i" class="h-20 rounded-xl skeleton-pulse" style="background-color: #F0EBE5;" />
      </view>
    </view>

    <!-- Error State -->
    <view v-else-if="error" class="flex flex-col items-center justify-center py-20 px-4">
      <text style="font-size: 48px; margin-bottom: 12px;"></text>
      <text class="text-base mb-2" style="color: #2C2C2C;">加载失败</text>
      <text class="text-sm mb-4" style="color: #999;">{{ error }}</text>
      <view
        @click="loadData"
        class="px-6 py-2 rounded-lg text-sm"
        style="background-color: #C41E3A; color: #FFFFFF; cursor: pointer;"
      >
        重新加载
      </view>
    </view>

    <!-- Content -->
    <view v-else class="p-4 space-y-5">
      <!-- 数据概览 -->
      <section>
        <text class="text-sm font-medium block mb-3" style="color: #999;">数据概览</text>
        <view class="grid grid-cols-2 gap-3">
          <view
            v-for="item in overviewItems"
            :key="item.key"
            class="p-3 rounded-xl"
            style="background-color: #FFFFFF;"
          >
            <view class="flex items-start justify-between">
              <view class="flex-1">
                <text class="text-xs block mb-1" style="color: #999;">{{ item.label }}</text>
                <text class="text-xl font-bold block" style="color: #1a1a1a;">
                  {{ item.value.toLocaleString() }}
                  <text v-if="item.unit" class="text-sm font-normal ml-1" style="color: #999;">{{ item.unit }}</text>
                </text>
                <view v-if="item.trend && item.trend.type !== 'flat'" class="flex items-center gap-1 mt-1">
                  <text v-if="item.trend.type === 'up'" style="color: #22c55e; font-size: 12px;">▲</text>
                  <text v-else style="color: #ef4444; font-size: 12px;">▼</text>
                  <text :style="{ fontSize: '12px', color: item.trend.type === 'up' ? '#22c55e' : '#ef4444' }">
                    {{ item.trend.value }}%
                  </text>
                  <text style="font-size: 12px; color: #999;">{{ item.trend.label }}</text>
                </view>
              </view>
              <view class="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0" style="background-color: #FFF8F0;">
                <text style="color: #C9A96E; font-size: 18px;">{{ getOverviewIcon(item.key) }}</text>
              </view>
            </view>
          </view>
        </view>
      </section>

      <!-- 快捷功能 -->
      <section>
        <text class="text-sm font-medium block mb-3" style="color: #999;">快捷功能</text>
        <view class="grid grid-cols-4 gap-3">
          <view
            v-for="action in quickActions"
            :key="action.id"
            @click="goToAction(action)"
            class="flex flex-col items-center gap-1.5 p-3 rounded-xl relative"
            hover-class="action-hover"
            style="background-color: #FFFFFF; cursor: pointer;"
          >
            <view
              class="w-10 h-10 rounded-full flex items-center justify-center"
              :style="{ backgroundColor: action.color + '20' }"
            >
              <text :style="{ color: action.color, fontSize: '18px' }">{{ getActionIcon(action.icon) }}</text>
            </view>
            <text class="text-xs" style="color: #4a4a4a;">{{ action.label }}</text>
            <view
              v-if="action.badge && action.badge > 0"
              class="absolute -top-1 -right-1 px-1.5 text-xs text-white rounded-full flex items-center justify-center"
              style="background-color: #C41E3A; min-width: 20px; height: 20px; border: none;"
            >
              <text style="font-size: 11px;">{{ action.badge > 99 ? '99+' : action.badge }}</text>
            </view>
          </view>
        </view>
      </section>

      <!-- 待处理事项 -->
      <section>
        <view class="flex items-center justify-between mb-3">
          <text class="text-sm font-medium" style="color: #999;">
            待处理事项
            <text v-if="totalPending > 0" class="ml-2 px-2 py-0.5 text-xs text-white rounded-full" style="background-color: #C41E3A;">{{ totalPending }}</text>
          </text>
          <view
            @click="goToPendingAll"
            class="flex items-center text-xs"
            style="color: #C9A96E; cursor: pointer;"
          >
            <text>查看全部</text>
            <text style="font-size: 14px; margin-left: 4px;">❯</text>
          </view>
        </view>

        <view v-if="pendingItems.length > 0" class="space-y-3">
          <view
            v-for="item in pendingItems.slice(0, 5)"
            :key="item.id"
            @click="goToPendingDetail(item)"
            class="p-3 rounded-xl"
            hover-class="pending-hover"
            style="background-color: #FFFFFF; cursor: pointer;"
          >
            <view class="flex items-start gap-3">
              <!-- Priority indicator -->
              <view
                class="w-1 rounded-full flex-shrink-0"
                :style="{
                  height: '48px',
                  backgroundColor: item.priority === 'high' ? '#C41E3A' : item.priority === 'medium' ? '#C9A96E' : '#d1d5db'
                }"
              />
              <view class="flex-1 min-w-0">
                <view class="flex items-center gap-2 mb-1">
                  <text class="font-medium text-sm" style="color: #1a1a1a;">{{ item.title }}</text>
                  <view
                    class="px-1.5 py-0.5 rounded text-xs"
                    :style="{
                      backgroundColor: item.priority === 'high' ? '#fee2e2' : item.priority === 'medium' ? '#fef3c7' : '#f3f4f6',
                      color: item.priority === 'high' ? '#dc2626' : item.priority === 'medium' ? '#d97706' : '#4b5563'
                    }"
                  >
                    <text>{{ item.priority === 'high' ? '紧急' : item.priority === 'medium' ? '一般' : '普通' }}</text>
                  </view>
                </view>
                <text class="text-xs truncate block" style="color: #999;">{{ item.description }}</text>
                <view class="flex items-center gap-1 mt-1.5">
                  <text style="font-size: 10px; color: #999;">⏱️</text>
                  <text class="text-xs" style="color: #999;">{{ item.createdAt }}</text>
                  <text class="text-xs mx-1" style="color: #ccc;">|</text>
                  <text class="text-xs" style="color: #C9A96E;">{{ item.type }}</text>
                </view>
              </view>
              <text style="font-size: 16px; color: #ccc; flex-shrink: 0;">❯</text>
            </view>
          </view>
        </view>

        <!-- Empty pending state -->
        <view v-else class="p-8 rounded-xl text-center" style="background-color: #FFFFFF;">
          <view class="text-center" style="color: #999;">
            <text style="font-size: 40px; display: block; margin-bottom: 8px; opacity: 0.5;">📊</text>
            <text class="text-sm" style="color: #999;">暂无待处理事项</text>
          </view>
        </view>
      </section>

      <!-- 分类统计 -->
      <section>
        <text class="text-sm font-medium block mb-3" style="color: #999;">分类统计</text>
        <view class="p-4 rounded-xl" style="background-color: #FFFFFF;">
          <view class="grid grid-cols-3 gap-4">
            <view v-for="(stat, key) in categoryStats" :key="key" class="text-center">
              <text class="text-xl font-bold block" :style="{ color: stat.color }">{{ stat.count }}</text>
              <text class="text-xs block mt-1" style="color: #999;">{{ stat.label }}</text>
            </view>
          </view>
        </view>
      </section>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { onLoad } from '@dcloudio/uni-app'

// --- Types ---
interface AdminInfo {
  name: string
  roleName: string
}

interface TrendData {
  type: 'up' | 'down' | 'flat'
  value: number
  label: string
}

interface OverviewItem {
  key: string
  label: string
  value: number
  unit?: string
  trend?: TrendData
}

interface QuickAction {
  id: string
  icon: string
  label: string
  color: string
  badge: number
}

interface PendingItem {
  id: string
  title: string
  description: string
  priority: 'high' | 'medium' | 'low'
  createdAt: string
  type: string
}

interface CategoryStat {
  label: string
  count: number
  color: string
}

// --- State ---
const loading = ref(true)
const error = ref<string | null>(null)

const adminInfo = ref<AdminInfo>({
  name: '管理员',
  roleName: '平台管理员',
})

const overviewItems = ref<OverviewItem[]>([])
const quickActions = ref<QuickAction[]>([])
const pendingItems = ref<PendingItem[]>([])
const categoryStats = ref<Record<string, CategoryStat>>({})

const totalPending = computed(() =>
  Object.values(categoryStats.value).reduce((a, b) => a + b.count, 0)
)

// --- Lifecycle ---
onLoad(() => {
  loadData()
})

// --- Data Loading ---
function loadData() {
  loading.value = true
  error.value = null

  // 模拟 API 请求（对应 V0 的 Promise.all 模式）
  setTimeout(() => {
    try {
      // 管理员信息
      adminInfo.value = {
        name: '管理员',
        roleName: '平台管理员',
      }

      // 数据概览
      overviewItems.value = [
        { key: 'users', label: '总用户数', value: 12860, unit: '人', trend: { type: 'up', value: 12, label: '较上月' } },
        { key: 'orders', label: '今日订单', value: 328, unit: '单', trend: { type: 'up', value: 5, label: '较昨日' } },
        { key: 'revenue', label: '本月收入', value: 186000, unit: '元', trend: { type: 'up', value: 8, label: '较上月' } },
        { key: 'reports', label: '待处理举报', value: 12, unit: '条', trend: { type: 'down', value: 3, label: '较昨日' } },
      ]

      // 快捷功能
      quickActions.value = [
        { id: '1', icon: 'users', label: '用户管理', color: '#C41E3A', badge: 12 },
        { id: '2', icon: 'content', label: '内容审核', color: '#C9A96E', badge: 15 },
        { id: '3', icon: 'order', label: '订单管理', color: '#4A6FA5', badge: 0 },
        { id: '4', icon: 'finance', label: '财务管理', color: '#2E7D32', badge: 0 },
        { id: '5', icon: 'report', label: '举报处理', color: '#E65100', badge: 8 },
        { id: '6', icon: 'cert', label: '认证审核', color: '#6A1B9A', badge: 7 },
        { id: '7', icon: 'withdraw', label: '提现管理', color: '#00695C', badge: 5 },
        { id: '8', icon: 'settings', label: '系统设置', color: '#546E7A', badge: 0 },
      ]

      // 待处理事项
      pendingItems.value = [
        { id: '1', title: '用户举报违规内容', description: '用户举报某课程涉嫌虚假宣传', priority: 'high', createdAt: '10分钟前', type: '内容审核' },
        { id: '2', title: '退款申请待处理', description: '用户申请课程退款', priority: 'medium', createdAt: '30分钟前', type: '退款申请' },
        { id: '3', title: '新讲师认证申请', description: '新讲师提交资质认证', priority: 'medium', createdAt: '1小时前', type: '认证审核' },
      ]

      // 分类统计
      categoryStats.value = {
        contentReview: { label: '内容审核', count: 15, color: '#C41E3A' },
        userReport: { label: '用户举报', count: 8, color: '#DC143C' },
        orderRefund: { label: '退款申请', count: 3, color: '#C9A96E' },
        withdraw: { label: '提现审核', count: 5, color: '#8B4513' },
        certification: { label: '认证审核', count: 7, color: '#9370DB' },
        feedback: { label: '用户反馈', count: 12, color: '#708090' },
      }

      loading.value = false
    } catch (err) {
      error.value = '网络错误，请重试'
      loading.value = false
    }
  }, 800)
}

// --- Icon Mappings ---
const overviewIconMap: Record<string, string> = {
  users: '',
  orders: '',
  revenue: '',
  reports: '',
}

const actionIconMap: Record<string, string> = {
  users: '',
  content: '',
  order: '️',
  finance: '',
  report: '',
  cert: '🪪',
  withdraw: '',
  settings: '⚙️',
}

function getOverviewIcon(key: string): string {
  return overviewIconMap[key] || '📊'
}

function getActionIcon(icon: string): string {
  return actionIconMap[icon] || '📌'
}

// --- Navigation ---
function goToAction(action: QuickAction) {
  uni.navigateTo({ url: '/admin/' + action.id + '/index' })
}

function goToPendingAll() {
  uni.navigateTo({ url: '/admin/pending/index' })
}

function goToPendingDetail(item: PendingItem) {
  uni.navigateTo({ url: '/admin/detail/index?id=' + item.id })
}

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
@keyframes skeletonPulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}
.skeleton-pulse {
  animation: skeletonPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}
.action-hover {
  background-color: rgba(249, 250, 251, 1);
}
.pending-hover {
  background-color: rgba(249, 250, 251, 1);
}
</style>

// proto-ref-app/mine/role-panels/admin-panel/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { 
  ChevronLeft, 
  Users, 
  ShoppingBag, 
  DollarSign, 
  Activity,
  FileCheck,
  BarChart2,
  Award,
  AlertTriangle,
  Settings,
  TrendingUp,
  TrendingDown,
  Minus,
  ChevronRight,
  Clock,
  Bell
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { DataState } from '@/components/data-state'
import { 
  getAdminPanelData, 
  getAdminInfo,
  getPendingTypeName, 
  getPriorityStyle 
} from '@/lib/api/admin'
import type { AdminPanelData, AdminInfo, AdminOverviewItem, AdminQuickAction, AdminPendingItem } from '@/lib/types/admin'

// 图标映射
const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  'users': Users,
  'shopping-bag': ShoppingBag,
  'dollar-sign': DollarSign,
  'activity': Activity,
  'file-check': FileCheck,
  'bar-chart-2': BarChart2,
  'award': Award,
  'alert-triangle': AlertTriangle,
  'settings': Settings
}

// 骨架屏组件
function AdminPanelSkeleton() {
  return (
    <div className="space-y-6 p-4">
      {/* 管理员信息骨架 */}
      <div className="flex items-center gap-3">
        <Skeleton className="h-12 w-12 rounded-full" />
        <div className="space-y-2">
          <Skeleton className="h-5 w-24" />
          <Skeleton className="h-4 w-32" />
        </div>
      </div>
      
      {/* 数据概览骨架 */}
      <div className="grid grid-cols-2 gap-3">
        {[1, 2, 3, 4].map(i => (
          <Skeleton key={i} className="h-24 rounded-xl" />
        ))}
      </div>
      
      {/* 快捷功能骨架 */}
      <div className="grid grid-cols-4 gap-3">
        {[1, 2, 3, 4, 5, 6, 7, 8].map(i => (
          <Skeleton key={i} className="h-20 rounded-xl" />
        ))}
      </div>
      
      {/* 待处理事项骨架 */}
      <div className="space-y-3">
        {[1, 2, 3].map(i => (
          <Skeleton key={i} className="h-20 rounded-xl" />
        ))}
      </div>
    </div>
  )
}

// 数据概览卡片
function OverviewCard({ item }: { item: AdminOverviewItem }) {
  const Icon = iconMap[item.icon] || Activity
  
  return (
    <Card className="p-3 bg-white border-none shadow-sm">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <p className="text-xs text-gray-500 mb-1">{item.label}</p>
          <p className="text-xl font-bold text-gray-900">
            {item.value.toLocaleString()}
            {item.unit && <span className="text-sm font-normal text-gray-500 ml-1">{item.unit}</span>}
          </p>
          {item.trend && item.trend.type !== 'flat' && (
            <div className="flex items-center gap-1 mt-1">
              {item.trend.type === 'up' ? (
                <TrendingUp className="h-3 w-3 text-green-500" />
              ) : (
                <TrendingDown className="h-3 w-3 text-red-500" />
              )}
              <span className={`text-xs ${item.trend.type === 'up' ? 'text-green-500' : 'text-red-500'}`}>
                {item.trend.value}%
              </span>
              <span className="text-xs text-gray-400">{item.trend.label}</span>
            </div>
          )}
        </div>
        <div className="w-10 h-10 rounded-full bg-[#FFF8F0] flex items-center justify-center">
          <Icon className="h-5 w-5 text-[#C9A96E]" />
        </div>
      </div>
    </Card>
  )
}

// 快捷功能按钮
function QuickActionButton({ action }: { action: AdminQuickAction }) {
  const router = useRouter()
  const Icon = iconMap[action.icon] || Activity
  
  return (
    <button
      onClick={() => router.push(action.href)}
      className="flex flex-col items-center gap-1.5 p-3 rounded-xl bg-white hover:bg-gray-50 active:scale-95 transition-all relative"
    >
      <div 
        className="w-10 h-10 rounded-full flex items-center justify-center"
        style={{ backgroundColor: `${action.color}15` }}
      >
        <Icon className="h-5 w-5" style={{ color: action.color }} />
      </div>
      <span className="text-xs text-gray-700">{action.label}</span>
      {action.badge && action.badge > 0 && (
        <Badge 
          className="absolute -top-1 -right-1 h-5 min-w-5 px-1.5 text-xs bg-[#C41E3A] text-white border-none"
        >
          {action.badge > 99 ? '99+' : action.badge}
        </Badge>
      )}
    </button>
  )
}

// 待处理事项项
function PendingItemCard({ item }: { item: AdminPendingItem }) {
  const router = useRouter()
  const priorityStyle = getPriorityStyle(item.priority)
  
  return (
    <Card 
      className="p-3 bg-white border-none shadow-sm cursor-pointer hover:bg-gray-50 active:bg-gray-100 transition-colors"
      onClick={() => router.push(item.href)}
    >
      <div className="flex items-start gap-3">
        <div className={`w-1 h-full min-h-[48px] rounded-full ${
          item.priority === 'high' ? 'bg-[#C41E3A]' : 
          item.priority === 'medium' ? 'bg-[#C9A96E]' : 'bg-gray-300'
        }`} />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="font-medium text-gray-900 text-sm">{item.title}</span>
            <Badge className={`${priorityStyle.bg} ${priorityStyle.text} text-xs px-1.5 py-0 h-5`}>
              {priorityStyle.label}
            </Badge>
          </div>
          <p className="text-xs text-gray-500 truncate">{item.description}</p>
          <div className="flex items-center gap-1 mt-1.5">
            <Clock className="h-3 w-3 text-gray-400" />
            <span className="text-xs text-gray-400">{item.createdAt}</span>
            <span className="text-xs text-gray-300 mx-1">|</span>
            <span className="text-xs text-[#C9A96E]">{getPendingTypeName(item.type)}</span>
          </div>
        </div>
        <ChevronRight className="h-5 w-5 text-gray-300 flex-shrink-0" />
      </div>
    </Card>
  )
}

export default function AdminPanelPage() {
  const router = useRouter()
  const [adminInfo, setAdminInfo] = useState<AdminInfo | null>(null)
  const [panelData, setPanelData] = useState<AdminPanelData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    loadData()
  }, [])

  const loadData = async () => {
    try {
      setLoading(true)
      setError(null)
      
      const [infoRes, panelRes] = await Promise.all([
        getAdminInfo(),
        getAdminPanelData()
      ])
      
      if (infoRes.code === 200 && infoRes.data) {
        setAdminInfo(infoRes.data)
      }
      
      if (panelRes.code === 200 && panelRes.data) {
        setPanelData(panelRes.data)
      } else {
        setError(panelRes.message || '加载失败')
      }
    } catch (err) {
      setError('网络错误，请重试')
    } finally {
      setLoading(false)
    }
  }

  // 计算总待处理数
  const totalPending = panelData ? Object.values(panelData.pendingCounts).reduce((a, b) => a + b, 0) : 0

  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-gradient-to-r from-[#C41E3A] to-[#A01830] text-white">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <button onClick={() => router.back()} className="p-1">
              <ChevronLeft className="h-6 w-6" />
            </button>
            <h1 className="text-lg font-semibold">管理中心</h1>
          </div>
          <button className="relative p-2">
            <Bell className="h-5 w-5" />
            {totalPending > 0 && (
              <span className="absolute top-1 right-1 w-2 h-2 bg-yellow-400 rounded-full" />
            )}
          </button>
        </div>
        
        {/* 管理员信息 */}
        {adminInfo && (
          <div className="px-4 pb-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center">
                <Users className="h-6 w-6 text-white" />
              </div>
              <div>
                <p className="font-medium">{adminInfo.name}</p>
                <p className="text-sm text-white/80">{adminInfo.roleName}</p>
              </div>
            </div>
          </div>
        )}
      </header>

      <DataState
        loading={loading}
        error={error}
        empty={!panelData}
        loadingComponent={<AdminPanelSkeleton />}
        emptyTitle="暂无数据"
        emptyDescription="无法加载管理面板数据"
        onRetry={loadData}
      >
        {panelData && (
          <div className="p-4 space-y-5 pb-20">
            {/* 数据概览 */}
            <section>
              <h2 className="text-sm font-medium text-gray-500 mb-3">数据概览</h2>
              <div className="grid grid-cols-2 gap-3">
                {panelData.overview.map(item => (
                  <OverviewCard key={item.key} item={item} />
                ))}
              </div>
            </section>

            {/* 快捷功能 */}
            <section>
              <h2 className="text-sm font-medium text-gray-500 mb-3">快捷功能</h2>
              <div className="grid grid-cols-4 gap-3">
                {panelData.quickActions.map(action => (
                  <QuickActionButton key={action.id} action={action} />
                ))}
              </div>
            </section>

            {/* 待处理事项 */}
            <section>
              <div className="flex items-center justify-between mb-3">
                <h2 className="text-sm font-medium text-gray-500">
                  待处理事项
                  {totalPending > 0 && (
                    <Badge className="ml-2 bg-[#C41E3A] text-white text-xs">
                      {totalPending}
                    </Badge>
                  )}
                </h2>
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="text-[#C9A96E] text-xs h-7 px-2"
                  onClick={() => router.push('/admin/user-audit')}
                >
                  查看全部
                  <ChevronRight className="h-4 w-4 ml-1" />
                </Button>
              </div>
              
              {panelData.pendingItems.length > 0 ? (
                <div className="space-y-3">
                  {panelData.pendingItems.slice(0, 5).map(item => (
                    <PendingItemCard key={item.id} item={item} />
                  ))}
                </div>
              ) : (
                <Card className="p-8 bg-white border-none shadow-sm">
                  <div className="text-center text-gray-400">
                    <Activity className="h-10 w-10 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">暂无待处理事项</p>
                  </div>
                </Card>
              )}
            </section>

            {/* 待处理分类统计 */}
            <section>
              <h2 className="text-sm font-medium text-gray-500 mb-3">分类统计</h2>
              <Card className="p-4 bg-white border-none shadow-sm">
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center">
                    <p className="text-xl font-bold text-[#C41E3A]">{panelData.pendingCounts.contentReview}</p>
                    <p className="text-xs text-gray-500 mt-1">内容审核</p>
                  </div>
                  <div className="text-center">
                    <p className="text-xl font-bold text-[#DC143C]">{panelData.pendingCounts.userReport}</p>
                    <p className="text-xs text-gray-500 mt-1">用户举报</p>
                  </div>
                  <div className="text-center">
                    <p className="text-xl font-bold text-[#C9A96E]">{panelData.pendingCounts.orderRefund}</p>
                    <p className="text-xs text-gray-500 mt-1">退款申请</p>
                  </div>
                  <div className="text-center">
                    <p className="text-xl font-bold text-[#8B4513]">{panelData.pendingCounts.withdraw}</p>
                    <p className="text-xs text-gray-500 mt-1">提现审核</p>
                  </div>
                  <div className="text-center">
                    <p className="text-xl font-bold text-[#9370DB]">{panelData.pendingCounts.certification}</p>
                    <p className="text-xs text-gray-500 mt-1">认证审核</p>
                  </div>
                  <div className="text-center">
                    <p className="text-xl font-bold text-[#708090]">{panelData.pendingCounts.feedback}</p>
                    <p className="text-xs text-gray-500 mt-1">用户反馈</p>
                  </div>
                </div>
              </Card>
            </section>
          </div>
        )}
      </DataState>
    </div>
  )
}
