// proto-ref-app/live/stream-config/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { ChevronLeft, Copy, Check, Eye, EyeOff, RefreshCw, Circle, ExternalLink, Monitor, Settings, Wifi, WifiOff } from "lucide-react"
import { liveApi, type StreamConfig, type StreamStatus } from "@/lib/api"

// Mock数据
const mockConfig: StreamConfig = {
  roomId: "room1",
  roomTitle: "周易六十四卦深度解读",
  streamUrl: "rtmp://live.rebu.com/live",
  streamKey: "stream_key_abc123xyz789",
  playUrl: "https://live.rebu.com/play/room1.flv",
  recommendedSettings: {
    resolution: "1920x1080",
    bitrate: "4000-6000 Kbps",
    fps: "30",
    encoder: "x264 / NVENC"
  }
}

const obsSteps = [
  {
    title: "打开OBS Studio",
    description: "下载并安装最新版OBS Studio，打开软件",
    image: "/placeholder.svg"
  },
  {
    title: "进入推流设置",
    description: "点击「设置」→「推流」，服务选择「自定义」",
    image: "/placeholder.svg"
  },
  {
    title: "填写推流信息",
    description: "将下方的「推流地址」填入服务器，「推流密钥」填入串流密钥",
    image: "/placeholder.svg"
  },
  {
    title: "配置视频参数",
    description: "点击「输出」→「流」，设置编码器和比特率；点击「视频」设置分辨率",
    image: "/placeholder.svg"
  },
  {
    title: "开始推流",
    description: "点击主界面的「开始推流」按钮，等待连接成功后即可开播",
    image: "/placeholder.svg"
  }
]

function StreamConfigContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const roomId = searchParams.get('roomId') || 'room1'
  
  const [loading, setLoading] = useState(true)
  const [config, setConfig] = useState<StreamConfig | null>(null)
  const [status, setStatus] = useState<StreamStatus | null>(null)
  const [showKey, setShowKey] = useState(false)
  const [copiedUrl, setCopiedUrl] = useState(false)
  const [copiedKey, setCopiedKey] = useState(false)
  const [checkingStatus, setCheckingStatus] = useState(false)
  const [currentStep, setCurrentStep] = useState(0)

  useEffect(() => {
    const loadData = async () => {
      try {
        // const [configRes, statusRes] = await Promise.all([
        //   liveApi.getStreamConfig(roomId),
        //   liveApi.checkStreamStatus(roomId)
        // ])
        // setConfig(configRes)
        // setStatus(statusRes)
        setConfig(mockConfig)
        setStatus({ roomId, isStreaming: false })
      } catch (error) {
        console.error('Failed to load stream config:', error)
      } finally {
        setLoading(false)
      }
    }
    loadData()
  }, [roomId])

  const copyToClipboard = async (text: string, type: 'url' | 'key') => {
    try {
      await navigator.clipboard.writeText(text)
      if (type === 'url') {
        setCopiedUrl(true)
        setTimeout(() => setCopiedUrl(false), 2000)
      } else {
        setCopiedKey(true)
        setTimeout(() => setCopiedKey(false), 2000)
      }
    } catch (error) {
      console.error('Failed to copy:', error)
    }
  }

  const checkStatus = async () => {
    setCheckingStatus(true)
    try {
      // const statusRes = await liveApi.checkStreamStatus(roomId)
      // setStatus(statusRes)
      // 模拟状态检测
      await new Promise(resolve => setTimeout(resolve, 1500))
      setStatus(prev => prev ? { ...prev, isStreaming: Math.random() > 0.5 } : null)
    } catch (error) {
      console.error('Failed to check status:', error)
    } finally {
      setCheckingStatus(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-[#FAF8F5]">
        <div className="sticky top-0 z-10 bg-white border-b border-[#E8E3DB] px-4 py-3 h-14" />
        <div className="p-4 space-y-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="bg-white rounded-2xl h-32 animate-pulse" />
          ))}
        </div>
      </div>
    )
  }

  if (!config) {
    return (
      <div className="min-h-screen bg-[#FAF8F5] flex items-center justify-center">
        <div className="text-center">
          <p className="text-[#999999]">加载失败</p>
          <button onClick={() => router.back()} className="mt-4 text-[#C41E3A]">返回</button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-6">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-10 bg-white border-b border-[#E8E3DB]">
        <div className="flex items-center justify-between px-4 py-3">
          <button onClick={() => router.back()} className="p-1 -ml-1">
            <ChevronLeft className="w-6 h-6 text-[#2C2C2C]" />
          </button>
          <h1 className="text-lg font-semibold text-[#2C2C2C]">推流配置</h1>
          <div className="w-6" />
        </div>
      </div>

      <div className="p-4 space-y-4">
        {/* 直播间信息 */}
        <div className="bg-white rounded-2xl p-4 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-br from-[#C41E3A] to-[#E8546D] rounded-xl flex items-center justify-center">
              <Monitor className="w-6 h-6 text-white" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-semibold text-[#2C2C2C] truncate">{config.roomTitle}</h2>
              <p className="text-sm text-[#999999]">直播间ID: {config.roomId}</p>
            </div>
          </div>
        </div>

        {/* 推流状态 */}
        <div className="bg-white rounded-2xl p-4 shadow-sm">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              {status?.isStreaming ? (
                <>
                  <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                    <Wifi className="w-5 h-5 text-green-600" />
                  </div>
                  <div>
                    <p className="font-medium text-green-600">推流中</p>
                    <p className="text-sm text-[#999999]">
                      {status.viewers || 0}人观看 · {status.bitrate || 0} Kbps
                    </p>
                  </div>
                </>
              ) : (
                <>
                  <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center">
                    <WifiOff className="w-5 h-5 text-[#999999]" />
                  </div>
                  <div>
                    <p className="font-medium text-[#666666]">未推流</p>
                    <p className="text-sm text-[#999999]">等待OBS连接</p>
                  </div>
                </>
              )}
            </div>
            <button
              onClick={checkStatus}
              disabled={checkingStatus}
              className="flex items-center gap-1 px-3 py-1.5 text-sm text-[#C41E3A] border border-[#C41E3A] rounded-full disabled:opacity-50"
            >
              <RefreshCw className={`w-4 h-4 ${checkingStatus ? 'animate-spin' : ''}`} />
              刷新
            </button>
          </div>

          {status?.isStreaming && (
            <div className="mt-4 pt-4 border-t border-[#E8E3DB]">
              <div className="aspect-video bg-black rounded-xl overflow-hidden relative">
                <div className="absolute inset-0 flex items-center justify-center text-white/50">
                  直播预览
                </div>
                <div className="absolute top-2 left-2 flex items-center gap-1 bg-red-500 text-white text-xs px-2 py-0.5 rounded">
                  <Circle className="w-2 h-2 fill-current animate-pulse" />
                  LIVE
                </div>
              </div>
            </div>
          )}
        </div>

        {/* 推流地址和密钥 */}
        <div className="bg-white rounded-2xl p-4 shadow-sm space-y-4">
          <h3 className="font-semibold text-[#2C2C2C] flex items-center gap-2">
            <Settings className="w-5 h-5 text-[#C41E3A]" />
            推流信息
          </h3>

          {/* 推流地址 */}
          <div>
            <label className="text-sm text-[#666666] mb-1.5 block">推流地址（服务器）</label>
            <div className="flex items-center gap-2">
              <div className="flex-1 bg-[#FAF8F5] rounded-lg px-3 py-2.5 font-mono text-sm text-[#2C2C2C] break-all">
                {config.streamUrl}
              </div>
              <button
                onClick={() => copyToClipboard(config.streamUrl, 'url')}
                className={`shrink-0 w-10 h-10 rounded-lg flex items-center justify-center transition-colors ${
                  copiedUrl ? 'bg-green-100 text-green-600' : 'bg-[#FAF8F5] text-[#666666] hover:bg-[#E8E3DB]'
                }`}
              >
                {copiedUrl ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
              </button>
            </div>
          </div>

          {/* 推流密钥 */}
          <div>
            <label className="text-sm text-[#666666] mb-1.5 block">推流密钥（串流密钥）</label>
            <div className="flex items-center gap-2">
              <div className="flex-1 bg-[#FAF8F5] rounded-lg px-3 py-2.5 font-mono text-sm text-[#2C2C2C] break-all">
                {showKey ? config.streamKey : '••••••••••••••••••••••'}
              </div>
              <button
                onClick={() => setShowKey(!showKey)}
                className="shrink-0 w-10 h-10 bg-[#FAF8F5] rounded-lg flex items-center justify-center text-[#666666] hover:bg-[#E8E3DB]"
              >
                {showKey ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
              </button>
              <button
                onClick={() => copyToClipboard(config.streamKey, 'key')}
                className={`shrink-0 w-10 h-10 rounded-lg flex items-center justify-center transition-colors ${
                  copiedKey ? 'bg-green-100 text-green-600' : 'bg-[#FAF8F5] text-[#666666] hover:bg-[#E8E3DB]'
                }`}
              >
                {copiedKey ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
              </button>
            </div>
            <p className="text-xs text-orange-500 mt-1.5">请勿泄露推流密钥，否则他人可能冒用您的直播间</p>
          </div>
        </div>

        {/* 推荐参数 */}
        <div className="bg-white rounded-2xl p-4 shadow-sm">
          <h3 className="font-semibold text-[#2C2C2C] mb-3">推荐参数设置</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="text-xs text-[#999999]">分辨率</p>
              <p className="font-medium text-[#2C2C2C]">{config.recommendedSettings.resolution}</p>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="text-xs text-[#999999]">比特率</p>
              <p className="font-medium text-[#2C2C2C]">{config.recommendedSettings.bitrate}</p>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="text-xs text-[#999999]">帧率</p>
              <p className="font-medium text-[#2C2C2C]">{config.recommendedSettings.fps} fps</p>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="text-xs text-[#999999]">编码器</p>
              <p className="font-medium text-[#2C2C2C]">{config.recommendedSettings.encoder}</p>
            </div>
          </div>
        </div>

        {/* OBS配置步骤 */}
        <div className="bg-white rounded-2xl p-4 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-[#2C2C2C]">OBS配置教程</h3>
            <a
              href="https://obsproject.com/download"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-[#C41E3A] flex items-center gap-1"
            >
              下载OBS
              <ExternalLink className="w-4 h-4" />
            </a>
          </div>

          {/* 步骤指示器 */}
          <div className="flex items-center gap-1 mb-4 overflow-x-auto pb-2">
            {obsSteps.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentStep(index)}
                className={`shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors ${
                  index === currentStep
                    ? 'bg-[#C41E3A] text-white'
                    : index < currentStep
                    ? 'bg-green-100 text-green-600'
                    : 'bg-[#FAF8F5] text-[#999999]'
                }`}
              >
                {index < currentStep ? <Check className="w-4 h-4" /> : index + 1}
              </button>
            ))}
          </div>

          {/* 当前步骤内容 */}
          <div className="bg-[#FAF8F5] rounded-xl p-4">
            <div className="aspect-video bg-[#E8E3DB] rounded-lg mb-3 flex items-center justify-center text-[#999999]">
              步骤 {currentStep + 1} 示意图
            </div>
            <h4 className="font-medium text-[#2C2C2C] mb-1">
              步骤 {currentStep + 1}: {obsSteps[currentStep].title}
            </h4>
            <p className="text-sm text-[#666666]">{obsSteps[currentStep].description}</p>
          </div>

          {/* 步骤导航 */}
          <div className="flex items-center justify-between mt-4">
            <button
              onClick={() => setCurrentStep(prev => Math.max(0, prev - 1))}
              disabled={currentStep === 0}
              className="px-4 py-2 text-sm text-[#666666] disabled:opacity-50"
            >
              上一步
            </button>
            <button
              onClick={() => setCurrentStep(prev => Math.min(obsSteps.length - 1, prev + 1))}
              disabled={currentStep === obsSteps.length - 1}
              className="px-4 py-2 text-sm text-[#C41E3A] font-medium disabled:opacity-50"
            >
              下一步
            </button>
          </div>
        </div>

        {/* 常见问题 */}
        <div className="bg-white rounded-2xl p-4 shadow-sm">
          <h3 className="font-semibold text-[#2C2C2C] mb-3">常见问题</h3>
          <div className="space-y-3">
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="font-medium text-[#2C2C2C] text-sm mb-1">推流失败怎么办？</p>
              <p className="text-xs text-[#666666]">请检查网络连接、推流地址和密钥是否正确，确保防火墙未阻止OBS</p>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="font-medium text-[#2C2C2C] text-sm mb-1">画面卡顿怎么办？</p>
              <p className="text-xs text-[#666666]">尝试降低比特率或分辨率，检查上行带宽是否足够</p>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3">
              <p className="font-medium text-[#2C2C2C] text-sm mb-1">可以使用其他推流软件吗？</p>
              <p className="text-xs text-[#666666]">支持任何RTMP推流软件，如Streamlabs、XSplit等</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function LoadingFallback() {
  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      <div className="sticky top-0 z-10 bg-white border-b border-[#E8E3DB] px-4 py-3 h-14" />
      <div className="p-4 space-y-4">
        {[1, 2, 3].map(i => (
          <div key={i} className="bg-white rounded-2xl h-32 animate-pulse" />
        ))}
      </div>
    </div>
  )
}

export default function StreamConfigPage() {
  return (
    <Suspense fallback={<LoadingFallback />}>
      <StreamConfigContent />
    </Suspense>
  )
}

// apps/mobile/src/pkg-live/stream-config/index.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view
      class="nav"
      :style="{ paddingTop: statusBarHeight + 'px' }"
    >
      <view class="nav-bar">
        <view
          class="nav-btn"
          @tap="goBack"
        >
          <AppIcon
            name="chevron-left"
            :size="48"
            color="#2C2C2C"
          />
        </view>
        <text class="nav-title">
          推流配置
        </text>
        <view class="nav-spacer" />
      </view>
    </view>

    <view class="body">
      <!-- 直播间信息 -->
      <view class="card">
        <view class="room-row">
          <view class="room-icon">
            <AppIcon
              name="monitor"
              :size="48"
              color="#fff"
            />
          </view>
          <view class="room-info">
            <text class="room-title">
              {{ config.roomTitle }}
            </text>
            <text class="room-id">
              直播间ID: {{ config.roomId }}
            </text>
          </view>
        </view>
      </view>

      <!-- 推流状态(默认未推流) -->
      <view class="card">
        <view class="status-row">
          <view class="status-left">
            <view class="status-icon off">
              <AppIcon
                name="wifi-off"
                :size="40"
                color="#999"
              />
            </view>
            <view class="status-text">
              <text class="status-title off">
                未推流
              </text>
              <text class="status-note">
                等待OBS连接
              </text>
            </view>
          </view>
          <view
            class="refresh-btn"
            @tap="handleRefresh"
          >
            <AppIcon
              name="refresh-cw"
              :size="32"
              color="#C41E3A"
              :class="{ spin: checking }"
            />
            <text class="refresh-txt">
              刷新
            </text>
          </view>
        </view>
      </view>

      <!-- 推流地址和密钥 -->
      <view class="card">
        <view class="info-head">
          <AppIcon
            name="settings"
            :size="40"
            color="#C41E3A"
          />
          <text class="info-head-txt">
            推流信息
          </text>
        </view>

        <view class="field">
          <text class="field-label">
            推流地址（服务器）
          </text>
          <view class="field-row">
            <view class="field-value">
              {{ config.streamUrl }}
            </view>
            <view
              class="field-btn"
              :class="{ copied: copiedUrl }"
              @tap="copyUrl"
            >
              <AppIcon
                :name="copiedUrl ? 'check' : 'copy'"
                :size="40"
                :color="copiedUrl ? '#16a34a' : '#666'"
              />
            </view>
          </view>
        </view>

        <view class="field">
          <text class="field-label">
            推流密钥（串流密钥）
          </text>
          <view class="field-row">
            <view class="field-value">
              {{ showKey ? config.streamKey : '••••••••••••••••••••••' }}
            </view>
            <view
              class="field-btn"
              @tap="showKey = !showKey"
            >
              <AppIcon
                :name="showKey ? 'eye-off' : 'eye'"
                :size="40"
                color="#666"
              />
            </view>
            <view
              class="field-btn"
              :class="{ copied: copiedKey }"
              @tap="copyKey"
            >
              <AppIcon
                :name="copiedKey ? 'check' : 'copy'"
                :size="40"
                :color="copiedKey ? '#16a34a' : '#666'"
              />
            </view>
          </view>
          <text class="field-warn">
            请勿泄露推流密钥，否则他人可能冒用您的直播间
          </text>
        </view>
      </view>

      <!-- 推荐参数 -->
      <view class="card">
        <text class="card-title">
          推荐参数设置
        </text>
        <view class="param-grid">
          <view class="param-item">
            <text class="param-label">
              分辨率
            </text>
            <text class="param-value">
              {{ config.recommendedSettings.resolution }}
            </text>
          </view>
          <view class="param-item">
            <text class="param-label">
              比特率
            </text>
            <text class="param-value">
              {{ config.recommendedSettings.bitrate }}
            </text>
          </view>
          <view class="param-item">
            <text class="param-label">
              帧率
            </text>
            <text class="param-value">
              {{ config.recommendedSettings.fps }} fps
            </text>
          </view>
          <view class="param-item">
            <text class="param-label">
              编码器
            </text>
            <text class="param-value">
              {{ config.recommendedSettings.encoder }}
            </text>
          </view>
        </view>
      </view>

      <!-- OBS配置步骤 -->
      <view class="card">
        <view class="obs-head">
          <text class="card-title nomb">
            OBS配置教程
          </text>
          <view class="obs-download">
            <text class="obs-download-txt">
              下载OBS
            </text>
            <AppIcon
              name="external-link"
              :size="32"
              color="#C41E3A"
            />
          </view>
        </view>

        <!-- 步骤指示器 -->
        <scroll-view
          scroll-x
          class="step-indicator"
        >
          <view
            v-for="(_, idx) in obsSteps"
            :key="idx"
            class="step-dot"
            :class="idx === currentStep ? 'active' : idx < currentStep ? 'done' : ''"
            @tap="currentStep = idx"
          >
            <AppIcon
              v-if="idx < currentStep"
              name="check"
              :size="32"
              color="#16a34a"
            />
            <text v-else>
              {{ idx + 1 }}
            </text>
          </view>
        </scroll-view>

        <!-- 当前步骤内容 -->
        <view class="step-box">
          <view class="step-img">
            步骤 {{ currentStep + 1 }} 示意图
          </view>
          <text class="step-box-title">
            步骤 {{ currentStep + 1 }}: {{ obsSteps[currentStep].title }}
          </text>
          <text class="step-box-desc">
            {{ obsSteps[currentStep].description }}
          </text>
        </view>

        <!-- 步骤导航 -->
        <view class="step-nav">
          <text
            class="step-nav-btn prev"
            :class="{ disabled: currentStep === 0 }"
            @tap="prevStep"
          >
            上一步
          </text>
          <text
            class="step-nav-btn next"
            :class="{ disabled: currentStep === obsSteps.length - 1 }"
            @tap="nextStep"
          >
            下一步
          </text>
        </view>
      </view>

      <!-- 常见问题 -->
      <view class="card">
        <text class="card-title">
          常见问题
        </text>
        <view class="faq-list">
          <view
            v-for="f in faq"
            :key="f.q"
            class="faq-item"
          >
            <text class="faq-q">
              {{ f.q }}
            </text>
            <text class="faq-a">
              {{ f.a }}
            </text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack } from '@/utils/router'
const streamConfig = { roomId: 'room1', roomTitle: '周易六十四卦深度解读', streamUrl: 'rtmp://live.rebu.com/live', streamKey: 'stream_key_abc123', playUrl: 'https://live.rebu.com/play/room1.flv', recommendedSettings: { resolution: '1920x1080', bitrate: '4000-6000 Kbps', fps: '30', encoder: 'x264 / NVENC' } }
const obsConfigSteps = [
  { title: '打开OBS Studio', description: '下载并安装最新版OBS Studio，打开软件' },
  { title: '进入推流设置', description: '点击「设置」→「推流」，服务选择「自定义」' },
  { title: '填写推流信息', description: '将下方的「推流地址」填入服务器，「推流密钥」填入串流密钥' },
  { title: '配置视频参数', description: '设置编码器和比特率、分辨率' },
  { title: '开始推流', description: '点击主界面的「开始推流」按钮' },
]
const streamConfigFaq = [
  { q: '推流失败怎么办？', a: '请检查网络连接、推流地址和密钥是否正确，确保防火墙未阻止OBS' },
  { q: '画面卡顿怎么办？', a: '尝试降低比特率或分辨率，检查上行带宽是否足够' },
  { q: '可以使用其他推流软件吗？', a: '支持任何RTMP推流软件，如Streamlabs、XSplit等' },
]

const statusBarHeight = ref(0)
const config = ref(streamConfig)
const obsSteps = ref(obsConfigSteps)
const faq = ref(streamConfigFaq)

// UI 临时状态
const showKey = ref(false)
const copiedUrl = ref(false)
const copiedKey = ref(false)
const checking = ref(false)
const currentStep = ref(0)

function copyUrl() {
  copiedUrl.value = true
  setTimeout(() => (copiedUrl.value = false), 2000)
}
function copyKey() {
  copiedKey.value = true
  setTimeout(() => (copiedKey.value = false), 2000)
}
function handleRefresh() {}
function prevStep() {
  if (currentStep.value > 0) currentStep.value--
}
function nextStep() {
  if (currentStep.value < obsSteps.value.length - 1) currentStep.value++
}
</script>

<style scoped>
.page {
  min-height: 100vh;
  background: #FAF8F5;
  padding-bottom: 48rpx;
}
.nav {
  position: sticky;
  top: 0;
  z-index: 10;
  background: #fff;
  border-bottom: 1rpx solid #E8E3DB;
}
.nav-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 24rpx 32rpx;
}
.nav-btn {
  display: flex;
  align-items: center;
  justify-content: center;
}
.nav-title {
  font-size: 36rpx;
  font-weight: 600;
  color: #2C2C2C;
}
.nav-spacer {
  width: 48rpx;
}
.body {
  padding: 32rpx;
  display: flex;
  flex-direction: column;
  gap: 32rpx;
}

/* Card */
.card {
  background: #fff;
  border-radius: 32rpx;
  padding: 32rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
}
.card-title {
  display: block;
  font-size: 30rpx;
  font-weight: 600;
  color: #2C2C2C;
  margin-bottom: 24rpx;
}
.card-title.nomb {
  margin-bottom: 0;
}

/* 直播间信息 */
.room-row {
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.room-icon {
  width: 96rpx;
  height: 96rpx;
  border-radius: 24rpx;
  background: linear-gradient(135deg, #C41E3A, #E8546D);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.room-info {
  flex: 1;
  min-width: 0;
}
.room-title {
  display: block;
  font-size: 30rpx;
  font-weight: 600;
  color: #2C2C2C;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.room-id {
  font-size: 28rpx;
  color: #999;
}

/* 推流状态 */
.status-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.status-left {
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.status-icon {
  width: 80rpx;
  height: 80rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.status-icon.off {
  background: #f3f4f6;
}
.status-text {
  display: flex;
  flex-direction: column;
}
.status-title {
  font-size: 28rpx;
  font-weight: 500;
}
.status-title.off {
  color: #666;
}
.status-note {
  font-size: 28rpx;
  color: #999;
}
.refresh-btn {
  display: flex;
  align-items: center;
  gap: 8rpx;
  padding: 12rpx 24rpx;
  border: 1rpx solid #C41E3A;
  border-radius: 999rpx;
}
.refresh-txt {
  font-size: 28rpx;
  color: #C41E3A;
}
.spin {
  animation: spin 1s linear infinite;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

/* 推流信息 */
.info-head {
  display: flex;
  align-items: center;
  gap: 16rpx;
  margin-bottom: 32rpx;
}
.info-head-txt {
  font-size: 30rpx;
  font-weight: 600;
  color: #2C2C2C;
}
.field {
  margin-bottom: 32rpx;
}
.field:last-child {
  margin-bottom: 0;
}
.field-label {
  display: block;
  font-size: 28rpx;
  color: #666;
  margin-bottom: 12rpx;
}
.field-row {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.field-value {
  flex: 1;
  background: #FAF8F5;
  border-radius: 16rpx;
  padding: 20rpx 24rpx;
  font-family: monospace;
  font-size: 28rpx;
  color: #2C2C2C;
  word-break: break-all;
}
.field-btn {
  flex-shrink: 0;
  width: 80rpx;
  height: 80rpx;
  border-radius: 16rpx;
  background: #FAF8F5;
  display: flex;
  align-items: center;
  justify-content: center;
}
.field-btn.copied {
  background: #dcfce7;
}
.field-warn {
  display: block;
  font-size: 24rpx;
  color: #f97316;
  margin-top: 12rpx;
}

/* 推荐参数 */
.param-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24rpx;
}
.param-item {
  background: #FAF8F5;
  border-radius: 24rpx;
  padding: 24rpx;
}
.param-label {
  display: block;
  font-size: 24rpx;
  color: #999;
}
.param-value {
  font-size: 28rpx;
  font-weight: 500;
  color: #2C2C2C;
}

/* OBS步骤 */
.obs-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 32rpx;
}
.obs-download {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.obs-download-txt {
  font-size: 28rpx;
  color: #C41E3A;
}
.step-indicator {
  white-space: nowrap;
  margin-bottom: 32rpx;
}
.step-dot {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 64rpx;
  height: 64rpx;
  border-radius: 50%;
  background: #FAF8F5;
  color: #999;
  font-size: 28rpx;
  font-weight: 500;
  margin-right: 8rpx;
  flex-shrink: 0;
}
.step-dot.active {
  background: #C41E3A;
  color: #fff;
}
.step-dot.done {
  background: #dcfce7;
  color: #16a34a;
}
.step-box {
  background: #FAF8F5;
  border-radius: 24rpx;
  padding: 32rpx;
}
.step-img {
  aspect-ratio: 16 / 9;
  background: #E8E3DB;
  border-radius: 16rpx;
  margin-bottom: 24rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28rpx;
  color: #999;
}
.step-box-title {
  display: block;
  font-size: 28rpx;
  font-weight: 500;
  color: #2C2C2C;
  margin-bottom: 8rpx;
}
.step-box-desc {
  font-size: 28rpx;
  color: #666;
}
.step-nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 32rpx;
}
.step-nav-btn {
  padding: 16rpx 32rpx;
  font-size: 28rpx;
}
.step-nav-btn.prev {
  color: #666;
}
.step-nav-btn.next {
  color: #C41E3A;
  font-weight: 500;
}
.step-nav-btn.disabled {
  opacity: 0.5;
}

/* FAQ */
.faq-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.faq-item {
  background: #FAF8F5;
  border-radius: 24rpx;
  padding: 24rpx;
}
.faq-q {
  display: block;
  font-size: 28rpx;
  font-weight: 500;
  color: #2C2C2C;
  margin-bottom: 8rpx;
}
.faq-a {
  font-size: 24rpx;
  color: #666;
}
</style>
