// components/live/live-card.tsx
"use client"

import { useState } from "react"
import { Eye, Clock, Bell, Users } from "lucide-react"
import { Card } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { cn } from "@/lib/utils"
import Link from "next/link"

interface LiveCardProps {
  id: string
  title: string
  cover: string
  hostName: string
  hostAvatar: string
  viewerCount: number
  type: "knowledge" | "commerce"
  status: "live" | "upcoming" | "replay"
  scheduledTime?: string
  duration?: string // 回放时长
  orientation?: "vertical" | "horizontal" // 竖屏(手机直播)或横屏(OBS直播)
  priceType?: "free" | "paid" // 收费类型（与可见范围独立）
  price?: number // 付费价格
  circleFree?: boolean // 圈内成员免费（全平台可见的付费直播）
  productCount?: number // 电商带货商品数
  className?: string
}

export function LiveCard({
  id,
  title,
  cover,
  hostName,
  hostAvatar,
  viewerCount,
  type,
  status,
  scheduledTime,
  duration,
  orientation = "vertical",
  priceType = "free",
  price,
  circleFree = false,
  productCount,
  className
}: LiveCardProps) {
  const [isBooked, setIsBooked] = useState(false)

  const handleBook = (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsBooked(!isBooked)
  }

  const typeLabel = type === "knowledge" ? "知识授课" : "电商带货"
  const typeColor = type === "knowledge" ? "bg-[#4A90D9]" : "bg-[#C9A96E]"

  // 根据方向决定封面比例
  // 横屏OBS直播: 16:9
  // 竖屏手机直播: 3:4
  const aspectClass = orientation === "horizontal" ? "aspect-video" : "aspect-[3/4]"

  return (
    <Link href={`/live/${id}`} className={className}>
      <Card className="overflow-hidden border-0 rounded-[10px] shadow-[0_2px_12px_rgba(0,0,0,0.08)] hover:shadow-[0_4px_20px_rgba(0,0,0,0.12)] transition-all duration-300 active:scale-[0.98] bg-white">
        {/* 封面图 */}
        <div className={cn("relative bg-[#F2EFEA] overflow-hidden", aspectClass)}>
          <img
            src={cover}
            alt={title}
            className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
          />
          
          {/* 渐变遮罩 */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
          
          {/* 类型标签 - 左上角 */}
          <Badge className={cn("absolute top-2 left-2 text-[10px] text-white border-0 font-medium", typeColor)}>
            {typeLabel}
          </Badge>
          
          {/* 状态标签 - 右上角 */}
          {status === "live" ? (
            // 直播中 - 红色呼吸灯
            <div className="absolute top-2 right-2 flex items-center gap-1 px-2 py-1 bg-[#C41E3A] rounded live-indicator">
              <span className="w-1.5 h-1.5 bg-white rounded-full" />
              <span className="text-[10px] font-medium text-white">直播中</span>
            </div>
          ) : status === "upcoming" ? (
            // 预约中 - 蓝色标签+时间
            <div className="absolute top-2 right-2 flex items-center gap-1 px-2 py-1 bg-[#4A90D9] rounded">
              <Clock className="w-3 h-3 text-white" />
              <span className="text-[10px] font-medium text-white">{scheduledTime}</span>
            </div>
          ) : (
            // 回放 - 灰色标签+时长
            <div className="absolute top-2 right-2 flex items-center gap-1 px-2 py-1 bg-black/60 rounded">
              <span className="text-[10px] text-white">{duration || "回放"}</span>
            </div>
          )}
          
          {/* 观看人数/预约人数 - 左下角 */}
          <div className="absolute bottom-2 left-2 flex items-center gap-1 px-2 py-1 bg-black/50 backdrop-blur-sm rounded">
            {status === "live" ? (
              <>
                <Eye className="w-3 h-3 text-white/80" />
                <span className="text-[10px] text-white">
                  {viewerCount >= 10000 ? `${(viewerCount / 10000).toFixed(1)}万` : viewerCount}
                </span>
              </>
            ) : status === "upcoming" ? (
              <>
                <Users className="w-3 h-3 text-white/80" />
                <span className="text-[10px] text-white">{viewerCount}人预约</span>
              </>
            ) : (
              <>
                <Eye className="w-3 h-3 text-white/80" />
                <span className="text-[10px] text-white">{viewerCount}次观看</span>
              </>
            )}
          </div>
          
          {/* 预约按钮 - 右下角（仅预约中显示） */}
          {status === "upcoming" && (
            <button
              onClick={handleBook}
              className={cn(
                "absolute bottom-2 right-2 flex items-center gap-1 px-3 py-1 rounded text-[10px] font-medium transition-all",
                isBooked
                  ? "bg-white/20 text-white border border-white/30"
                  : "bg-[#4A90D9] text-white"
              )}
            >
              <Bell className="w-3 h-3" />
              {isBooked ? "已预约" : "预约"}
            </button>
          )}
        </div>
        
        {/* 主播信息 - 统一首页卡片样式 */}
        <div className="p-2.5">
          <h3 className="text-[15px] font-medium text-[#2C2C2C] line-clamp-2 leading-snug mb-2">
            {title}
          </h3>
          <div className="flex items-center gap-1.5">
            <Avatar className="w-5 h-5">
              <AvatarImage src={hostAvatar} alt={hostName} />
              <AvatarFallback className="text-[9px] bg-[#F5F1EB] text-[#666666]">{hostName[0]}</AvatarFallback>
            </Avatar>
            <span className="text-[11px] text-[#666666] truncate flex-1">{hostName}</span>
            {/* 收费标签 - 与可见范围独立 */}
            {priceType === "paid" ? (
              <span className="flex-shrink-0 text-danger text-[12px] font-bold leading-none">¥{price}</span>
            ) : (
              <span className="flex-shrink-0 text-success text-[10px] font-medium leading-none px-1.5 py-0.5 rounded bg-success/10">免费</span>
            )}
          </div>
          {/* 圈内免费 / 带货商品数 - 次级信息 */}
          {(circleFree || (type === "commerce" && productCount)) && (
            <div className="flex items-center gap-2 mt-1.5">
              {circleFree && (
                <span className="text-[10px] text-gold leading-none px-1.5 py-0.5 rounded bg-gold/10">圈内免费</span>
              )}
              {type === "commerce" && productCount ? (
                <span className="text-[10px] text-[#999999] leading-none">{productCount}件好物</span>
              ) : null}
            </div>
          )}
        </div>
      </Card>
    </Link>
  )
}

// apps/mobile/src/components/live/live-card.vue
<script setup lang="ts">
/** 直播广场卡片 - 从原型 components/live/live-card.tsx 迁移（与首页 feed 的 cards/live-card 不同） */
import { ref, computed } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { navigateTo } from '@/utils/router'
import type { LiveItem } from '@/lib/live-data'

const props = defineProps<{ data: LiveItem }>()
const booked = ref(false)

const typeLabel = computed(() => (props.data.type === 'knowledge' ? '知识授课' : '电商带货'))
const viewerText = computed(() => {
  const v = props.data.viewerCount
  return v >= 10000 ? `${(v / 10000).toFixed(1)}万` : String(v)
})
const showSecondRow = computed(
  () => props.data.circleFree || (props.data.type === 'commerce' && !!props.data.productCount),
)

function open() {
  navigateTo(`/live/${props.data.id}`)
}
function toggleBook() {
  booked.value = !booked.value
}
</script>

<template>
  <view class="lc" hover-class="lc-press" @tap="open">
    <!-- 封面 -->
    <view class="cover" :class="data.orientation === 'horizontal' ? 'r-169' : 'r-34'">
      <image v-if="data.cover" class="cover-img" :src="data.cover" mode="aspectFill" />
      <view class="grad" />
      <!-- 类型标签 左上 -->
      <text class="type-badge" :class="data.type === 'knowledge' ? 'tb-know' : 'tb-comm'">{{ typeLabel }}</text>
      <!-- 状态标签 右上 -->
      <view v-if="data.status === 'live'" class="st-badge st-live">
        <view class="live-dot" /><text class="st-txt">直播中</text>
      </view>
      <view v-else-if="data.status === 'upcoming'" class="st-badge st-up">
        <AppIcon name="clock" :size="20" color="#ffffff" /><text class="st-txt">{{ data.scheduledTime }}</text>
      </view>
      <view v-else class="st-badge st-replay">
        <text class="st-txt">{{ data.duration || '回放' }}</text>
      </view>
      <!-- 人数 左下 -->
      <view class="viewers">
        <AppIcon :name="data.status === 'upcoming' ? 'users' : 'eye'" :size="20" color="rgba(255,255,255,0.8)" />
        <text class="viewers-txt">
          {{ data.status === 'live' ? viewerText : data.status === 'upcoming' ? data.viewerCount + '人预约' : data.viewerCount + '次观看' }}
        </text>
      </view>
      <!-- 预约按钮 右下 -->
      <view
        v-if="data.status === 'upcoming'"
        class="book-btn"
        :class="booked ? 'book-on' : 'book-off'"
        @tap.stop="toggleBook"
      >
        <AppIcon name="bell" :size="20" color="#ffffff" /><text class="book-txt">{{ booked ? '已预约' : '预约' }}</text>
      </view>
    </view>
    <!-- 信息区 -->
    <view class="body">
      <text class="title">{{ data.title }}</text>
      <view class="host">
        <view class="avatar">
          <image v-if="data.hostAvatar" class="avatar-img" :src="data.hostAvatar" mode="aspectFill" />
          <text v-else class="avatar-ph">{{ data.hostName.charAt(0) }}</text>
        </view>
        <text class="host-name">{{ data.hostName }}</text>
        <text v-if="data.priceType === 'paid'" class="price">¥{{ data.price }}</text>
        <text v-else class="free">免费</text>
      </view>
      <view v-if="showSecondRow" class="sub-row">
        <text v-if="data.circleFree" class="circle-free">圈内免费</text>
        <text v-if="data.type === 'commerce' && data.productCount" class="goods">{{ data.productCount }}件好物</text>
      </view>
    </view>
</template>

<style scoped lang="scss">
.lc { overflow: hidden; border-radius: 20rpx; background: #ffffff; box-shadow: 0 4rpx 24rpx rgba(0, 0, 0, 0.08); }
.lc-press { transform: scale(0.98); }
.cover { position: relative; width: 100%; background: var(--surface-sunken); overflow: hidden; }
.r-169 { padding-bottom: 56.25%; }
.r-34 { padding-bottom: 133.33%; }
.cover-img { position: absolute; inset: 0; width: 100%; height: 100%; }
.grad { position: absolute; inset: 0; background: linear-gradient(to top, rgba(0, 0, 0, 0.6), transparent 50%); }
.type-badge { position: absolute; top: 16rpx; left: 16rpx; z-index: 10; font-size: 20rpx; line-height: 1; padding: 6rpx 12rpx; border-radius: 8rpx; color: #ffffff; font-weight: 500; white-space: nowrap; }
.tb-know { background: #4a90d9; }
.tb-comm { background: #c9a96e; }
.st-badge { position: absolute; top: 16rpx; right: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 6rpx 12rpx; border-radius: 8rpx; }
.st-live { background: var(--brand); }
.st-up { background: #4a90d9; }
.st-replay { background: rgba(0, 0, 0, 0.6); }
.live-dot { width: 12rpx; height: 12rpx; background: #ffffff; border-radius: 999rpx; }
.st-txt { font-size: 20rpx; line-height: 1; color: #ffffff; font-weight: 500; white-space: nowrap; }
.viewers { position: absolute; left: 16rpx; bottom: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 6rpx 12rpx; border-radius: 8rpx; background: rgba(0, 0, 0, 0.5); }
.viewers-txt { font-size: 20rpx; line-height: 1; color: #ffffff; white-space: nowrap; }
.book-btn { position: absolute; right: 16rpx; bottom: 16rpx; z-index: 10; display: flex; align-items: center; gap: 6rpx; padding: 8rpx 18rpx; border-radius: 8rpx; }
.book-off { background: #4a90d9; }
.book-on { background: rgba(255, 255, 255, 0.2); border: 2rpx solid rgba(255, 255, 255, 0.3); }
.book-txt { font-size: 20rpx; line-height: 1; color: #ffffff; font-weight: 500; white-space: nowrap; }
.body { padding: 20rpx; }
.title { display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; overflow: hidden; font-size: 30rpx; font-weight: 500; color: #2c2c2c; line-height: 1.375; margin-bottom: 16rpx; }
.host { display: flex; align-items: center; gap: 12rpx; }
.avatar { width: 40rpx; height: 40rpx; border-radius: 999rpx; overflow: hidden; background: var(--surface-sunken); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.avatar-img { width: 100%; height: 100%; }
.avatar-ph { font-size: 18rpx; color: #666666; }
.host-name { flex: 1; font-size: 22rpx; color: #666666; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; }
.price { flex-shrink: 0; font-size: 24rpx; font-weight: 700; line-height: 1; color: var(--danger); }
.free { flex-shrink: 0; font-size: 20rpx; font-weight: 500; line-height: 1; color: var(--success); padding: 4rpx 10rpx; border-radius: 8rpx; background: rgba(82, 196, 26, 0.1); }
.sub-row { display: flex; align-items: center; gap: 16rpx; margin-top: 12rpx; }
.circle-free { font-size: 20rpx; line-height: 1; color: var(--gold); padding: 4rpx 10rpx; border-radius: 8rpx; background: rgba(201, 169, 110, 0.1); white-space: nowrap; }
.goods { font-size: 20rpx; line-height: 1; color: #999999; white-space: nowrap; }
</style>
