// apps/mobile/.backup_vue3_converted/pages/circles/id-detail/join-requests/index.vue
<template>
  <view class="min-h-screen" style="background-color: #FAF8F5;">
    <!-- 顶部导航 -->
    <view class="sticky top-0 z-40" style="background-color: #FFFFFF; border-bottom: 2rpx solid #F2EFEA;">
      <view class="flex items-center justify-between" style="padding: 0 32rpx; height: 112rpx;">
        <view @click="goBack" style="padding: 8rpx;">
          <text style="font-size: 36rpx; color: #2C2C2C;">←</text>
        </view>
        <text style="font-size: 30rpx; font-weight: 600; color: #2C2C2C;">入圈申请</text>
        <view style="width: 64rpx;" />
      </view>

      <!-- 统计信息 -->
      <view class="flex items-center" style="gap: 32rpx; padding: 24rpx 32rpx; background: linear-gradient(to right, rgba(196,30,58,0.05), transparent);">
        <view class="flex items-center" style="gap: 16rpx;">
          <view style="width: 64rpx; height: 64rpx; border-radius: 50%; background-color: rgba(196,30,58,0.1); display: flex; align-items: center; justify-content: center;">
            <text style="font-size: 28rpx; color: #C41E3A;"></text>
          </view>
          <view>
            <text style="font-size: 36rpx; font-weight: 700; color: #C41E3A; display: block;">{{ pendingRequests.length }}</text>
            <text style="font-size: 22rpx; color: #999999;">待审批</text>
          </view>
        </view>
        <view style="width: 2rpx; height: 64rpx; background-color: #E8E0D5;" />
        <view>
          <text style="font-size: 36rpx; font-weight: 700; color: #2C2C2C; display: block;">{{ processedRequests.length }}</text>
          <text style="font-size: 22rpx; color: #999999;">已处理</text>
        </view>
      </view>

      <!-- 筛选Tab -->
      <view class="flex" style="border-bottom: 2rpx solid #F2EFEA;">
        <view v-for="tab in filterTabs" :key="tab.key"
          @click="filter = tab.key; selectedIds = new Set(); isBatchMode = false"
          :style="{
            flex: 1,
            padding: '24rpx 0',
            fontSize: '24rpx',
            fontWeight: 500,
            position: 'relative',
            textAlign: 'center',
            color: filter === tab.key ? '#C41E3A' : '#999999'
          }">
          <text>{{ tab.label }}</text>
          <view v-if="filter === tab.key"
            style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); width: 64rpx; height: 4rpx; background-color: #C41E3A; border-radius: 999rpx;" />
        </view>
      </view>
    </view>

    <!-- 批量操作栏 -->
    <view v-if="filter === 'pending' && pendingRequests.length > 0"
      class="flex items-center justify-between"
      style="position: sticky; top: 292rpx; z-index: 30; background-color: #FAF8F5; padding: 16rpx 32rpx;">
      <view @click="handleSelectAll" class="flex items-center" style="gap: 16rpx; font-size: 24rpx; color: #666666;">
        <view :style="{
          width: '32rpx',
          height: '32rpx',
          borderRadius: '8rpx',
          border: '4rpx solid',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          borderColor: selectedIds.size === pendingRequests.length && pendingRequests.length > 0 ? '#C41E3A' : '#D9D9D9',
          backgroundColor: selectedIds.size === pendingRequests.length && pendingRequests.length > 0 ? '#C41E3A' : 'transparent'
        }">
          <text v-if="selectedIds.size === pendingRequests.length && pendingRequests.length > 0" style="font-size: 20rpx; color: #FFFFFF;">✓</text>
        </view>
        <text>全选</text>
      </view>
      <view v-if="selectedIds.size > 0" @click="handleBatchApprove"
        style="padding: 12rpx 32rpx; background-color: #C41E3A; color: #FFFFFF; font-size: 24rpx; border-radius: 999rpx;">
        <text>批量通过 ({{ selectedIds.size }})</text>
      </view>
    </view>

    <!-- 申请列表 -->
    <view v-if="isLoading" style="padding: 32rpx; display: flex; flex-direction: column; gap: 24rpx;">
      <view v-for="i in 3" :key="i" style="background-color: #FFFFFF; border-radius: 16rpx; padding: 32rpx;">
        <view class="flex" style="gap: 24rpx;">
          <view style="width: 96rpx; height: 96rpx; background-color: #F2EFEA; border-radius: 50%;" />
          <view style="flex: 1; display: flex; flex-direction: column; gap: 16rpx;">
            <view style="height: 32rpx; background-color: #F2EFEA; border-radius: 8rpx; width: 192rpx;" />
            <view style="height: 24rpx; background-color: #F2EFEA; border-radius: 8rpx; width: 256rpx;" />
          </view>
        </view>
        <view style="margin-top: 24rpx; height: 32rpx; background-color: #F2EFEA; border-radius: 8rpx; width: 100%;" />
        <view style="margin-top: 16rpx; height: 32rpx; background-color: #F2EFEA; border-radius: 8rpx; width: 66%;" />
      </view>
    </view>

    <view v-else-if="displayRequests.length === 0" class="flex flex-col items-center justify-center" style="padding: 160rpx 0;">
      <view style="width: 128rpx; height: 128rpx; border-radius: 50%; background-color: #F2EFEA; display: flex; align-items: center; justify-content: center; margin-bottom: 32rpx;">
        <text style="font-size: 48rpx; color: #CCCCCC;"></text>
      </view>
      <text style="font-size: 24rpx; color: #999999;">{{ filter === 'pending' ? '暂无待审批申请' : '暂无已处理申请' }}</text>
    </view>

    <view v-else style="padding: 32rpx; display: flex; flex-direction: column; gap: 24rpx;">
      <view v-for="request in displayRequests" :key="request.id"
        :style="{
          backgroundColor: '#FFFFFF',
          borderRadius: '16rpx',
          overflow: 'hidden',
          boxShadow: request.status === 'pending' ? '0 4rpx 24rpx rgba(0,0,0,0.06)' : 'none',
          opacity: request.status === 'pending' ? 1 : 0.7,
          border: selectedIds.has(request.id) ? '4rpx solid #C41E3A' : 'none'
        }">

        <view style="padding: 32rpx;">
          <view class="flex items-start" style="gap: 24rpx;">
            <!-- 选择框 -->
            <view v-if="request.status === 'pending'" @click="handleSelect(request.id)"
              :style="{
                width: '40rpx',
                height: '40rpx',
                borderRadius: '8rpx',
                border: '4rpx solid',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
                marginTop: '4rpx',
                borderColor: selectedIds.has(request.id) ? '#C41E3A' : '#D9D9D9',
                backgroundColor: selectedIds.has(request.id) ? '#C41E3A' : 'transparent'
              }">
              <text v-if="selectedIds.has(request.id)" style="font-size: 20rpx; color: #FFFFFF;">✓</text>
            </view>

            <!-- 用户信息 -->
            <image :src="request.user.avatar" mode="aspectFill"
              style="width: 96rpx; height: 96rpx; border-radius: 50%; background-color: #F2EFEA; flex-shrink: 0;" />
            <view style="flex: 1; min-width: 0;">
              <view class="flex items-center" style="gap: 16rpx;">
                <text style="font-size: 26rpx; font-weight: 500; color: #2C2C2C;">{{ request.user.name }}</text>
                <text v-if="request.status !== 'pending'"
                  :style="{
                    fontSize: '20rpx',
                    padding: '4rpx 16rpx',
                    borderRadius: '999rpx',
                    backgroundColor: request.status === 'approved' ? 'rgba(22,163,74,0.1)' : 'rgba(220,38,38,0.1)',
                    color: request.status === 'approved' ? '#16A34A' : '#DC2626'
                  }">
                  {{ request.status === 'approved' ? '已通过' : '已拒绝' }}
                </text>
              </view>
              <text v-if="request.user.bio" style="font-size: 22rpx; color: #999999; margin-top: 4rpx; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ request.user.bio }}</text>
              <view class="flex items-center" style="gap: 8rpx; margin-top: 8rpx; font-size: 22rpx; color: #999999;">
                <text style="font-size: 24rpx;">🕐</text>
                <text>{{ formatTime(request.createdAt) }}</text>
              </view>
            </view>

            <!-- 展开按钮 -->
            <view @click="expandedId = expandedId === request.id ? null : request.id" style="padding: 8rpx;">
              <text style="font-size: 32rpx; color: #999999;">{{ expandedId === request.id ? '▲' : '▼' }}</text>
            </view>
          </view>

          <!-- 申请理由 -->
          <view style="margin-top: 24rpx; padding-left: 64rpx;">
            <text style="font-size: 24rpx; color: #666666;">
              <text style="color: #999999;">申请理由：</text>
              {{ request.reason }}
            </text>
          </view>

          <!-- 展开详情 -->
          <view v-if="expandedId === request.id" style="margin-top: 24rpx; padding-top: 24rpx; border-top: 2rpx solid #F2EFEA; padding-left: 64rpx; display: flex; flex-direction: column; gap: 16rpx;">
            <text style="font-size: 22rpx; color: #999999; display: block;">申请时间：{{ new Date(request.createdAt).toLocaleString('zh-CN') }}</text>
            <text v-if="request.processedAt" style="font-size: 22rpx; color: #999999; display: block;">处理时间：{{ new Date(request.processedAt).toLocaleString('zh-CN') }}</text>
            <text v-if="request.rejectReason" style="font-size: 22rpx; color: #DC2626; display: block;">拒绝原因：{{ request.rejectReason }}</text>
          </view>
        </view>

        <!-- 操作按钮 -->
        <view v-if="request.status === 'pending'" class="flex" style="border-top: 2rpx solid #F2EFEA;">
          <view @click="setRejectingId(request.id)" hover-class="action-hover"
            class="flex items-center justify-center" style="flex: 1; gap: 8rpx; padding: 24rpx 0; font-size: 24rpx; color: #666666;">
            <text style="font-size: 28rpx;">✖</text>
            <text>拒绝</text>
          </view>
          <view style="width: 2rpx; background-color: #F2EFEA;" />
          <view @click="handleApprove(request.id)" hover-class="action-hover-approve"
            class="flex items-center justify-center" style="flex: 1; gap: 8rpx; padding: 24rpx 0; font-size: 24rpx; color: #C41E3A; font-weight: 500;">
            <text style="font-size: 28rpx;">✔</text>
            <text>通过</text>
          </view>
        </view>
      </view>
    </view>

    <!-- 拒绝原因弹窗 -->
    <view v-if="rejectingId" class="flex items-center justify-center" style="position: fixed; inset: 0; z-index: 999;">
      <view style="position: absolute; inset: 0; background-color: rgba(0,0,0,0.5);" @click="setRejectingId(null)" />
      <view style="position: relative; background-color: #FFFFFF; border-radius: 24rpx; padding: 40rpx; width: 85%; max-width: 600rpx;">
        <text style="font-size: 30rpx; font-weight: 600; color: #2C2C2C; margin-bottom: 32rpx; display: block;">拒绝申请</text>
        <textarea v-model="rejectReason" placeholder="请输入拒绝原因（选填）"
          style="width: 100%; min-height: 192rpx; padding: 24rpx; border: 2rpx solid #E8E0D5; border-radius: 12rpx; font-size: 24rpx; box-sizing: border-box;"
          placeholder-style="color: #999999;" />
        <view class="flex" style="gap: 24rpx; margin-top: 32rpx;">
          <view @click="setRejectingId(null)"
            style="flex: 1; padding: 20rpx 0; border-radius: 12rpx; border: 2rpx solid #E8E0D5; text-align: center; font-size: 24rpx; color: #666666;">
            <text>取消</text>
          </view>
          <view @click="handleRejectConfirm"
            style="flex: 1; padding: 20rpx 0; border-radius: 12rpx; background-color: #C41E3A; text-align: center; font-size: 24rpx; color: #FFFFFF;">
            <text>确认拒绝</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

interface User {
  id: string
  name: string
  avatar: string
  bio?: string
}

interface JoinRequest {
  id: string
  user: User
  reason: string
  status: 'pending' | 'approved' | 'rejected'
  createdAt: string
  processedAt?: string
  rejectReason?: string
}

const mockRequests: JoinRequest[] = [
  { id: '1', user: { id: 'u1', name: '张三', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&q=80', bio: '命理爱好者，学习八字3年' }, reason: '对八字命理非常感兴趣，希望能加入圈子与各位老师交流学习，提升自己的命理水平。', status: 'pending', createdAt: '2024-01-15T10:30:00Z' },
  { id: '2', user: { id: 'u2', name: '李四', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&q=80', bio: '风水师，从业5年' }, reason: '想与圈内同好交流风水心得，分享实战经验。', status: 'pending', createdAt: '2024-01-15T09:20:00Z' },
  { id: '3', user: { id: 'u3', name: '王五', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=96&q=80' }, reason: '朋友推荐的圈子，想来学习。', status: 'pending', createdAt: '2024-01-14T18:45:00Z' },
  { id: '4', user: { id: 'u4', name: '赵六', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&q=80', bio: '国学爱好者' }, reason: '希望学习传统文化知识', status: 'approved', createdAt: '2024-01-13T14:00:00Z', processedAt: '2024-01-13T16:30:00Z' },
  { id: '5', user: { id: 'u5', name: '钱七', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&q=80' }, reason: '...', status: 'rejected', createdAt: '2024-01-12T11:00:00Z', processedAt: '2024-01-12T15:00:00Z', rejectReason: '申请理由过于简单' },
]

const isLoading = ref(true)
const requests = ref<JoinRequest[]>([])
const filter = ref<'pending' | 'processed'>('pending')
const selectedIds = ref<Set<string>>(new Set())
const expandedId = ref<string | null>(null)
const rejectingId = ref<string | null>(null)
const rejectReason = ref('')
const isBatchMode = ref(false)

const filterTabs = [
  { key: 'pending' as const, label: '待审批' },
  { key: 'processed' as const, label: '已处理' },
]

const pendingRequests = computed(() => requests.value.filter(r => r.status === 'pending'))
const processedRequests = computed(() => requests.value.filter(r => r.status !== 'pending'))
const displayRequests = computed(() => filter.value === 'pending' ? pendingRequests.value : processedRequests.value)

onMounted(() => {
  setTimeout(() => {
    requests.value = mockRequests
    isLoading.value = false
  }, 800)
})

function handleSelect(id: string) {
  const next = new Set(selectedIds.value)
  next.has(id) ? next.delete(id) : next.add(id)
  selectedIds.value = next
}

function handleSelectAll() {
  if (selectedIds.value.size === pendingRequests.value.length) {
    selectedIds.value = new Set()
  } else {
    selectedIds.value = new Set(pendingRequests.value.map(r => r.id))
  }
}

function handleApprove(id: string) {
  requests.value = requests.value.map(r =>
    r.id === id ? { ...r, status: 'approved' as const, processedAt: new Date().toISOString() } : r
  )
  const next = new Set(selectedIds.value)
  next.delete(id)
  selectedIds.value = next
}

function handleRejectConfirm() {
  if (!rejectingId.value) return
  requests.value = requests.value.map(r =>
    r.id === rejectingId.value ? { ...r, status: 'rejected' as const, processedAt: new Date().toISOString(), rejectReason: rejectReason.value || undefined } : r
  )
  const next = new Set(selectedIds.value)
  next.delete(rejectingId.value)
  selectedIds.value = next
  rejectingId.value = null
  rejectReason.value = ''
}

function handleBatchApprove() {
  const ids = Array.from(selectedIds.value)
  requests.value = requests.value.map(r =>
    ids.includes(r.id) ? { ...r, status: 'approved' as const, processedAt: new Date().toISOString() } : r
  )
  selectedIds.value = new Set()
  isBatchMode.value = false
}

function formatTime(dateStr: string) {
  const date = new Date(dateStr)
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const hours = Math.floor(diff / (1000 * 60 * 60))
  if (hours < 1) return '刚刚'
  if (hours < 24) return `${hours}小时前`
  const days = Math.floor(hours / 24)
  if (days < 7) return `${days}天前`
  return `${date.getMonth() + 1}/${date.getDate()}`
}

function goBack() {
  uni.navigateBack()
}
</script>

<style scoped>
.flex { display: flex; }
.items-center { align-items: center; }
.justify-between { justify-content: space-between; }
.items-start { align-items: flex-start; }
.flex-col { flex-direction: column; }
.justify-center { justify-content: center; }
.action-hover {
  background-color: rgba(245,240,232,0.5);
}
.action-hover-approve {
  background-color: rgba(196,30,58,0.05);
}
</style>

// app/circles/[id]/join-requests/page.tsx
"use client"

import { useState, useEffect } from "react"
import { useParams, useRouter } from "next/navigation"
import { ChevronLeft, Check, X, Users, Clock, CheckCircle, XCircle, ChevronDown, ChevronUp } from "lucide-react"
import { cn } from "@/lib/utils"

// Types
interface JoinRequest {
  id: string
  user: {
    id: string
    name: string
    avatar: string
    bio?: string
  }
  reason: string
  status: 'pending' | 'approved' | 'rejected'
  createdAt: string
  processedAt?: string
  rejectReason?: string
}

// Mock data
const mockRequests: JoinRequest[] = [
  {
    id: "1",
    user: { id: "u1", name: "张三", avatar: "/placeholder.svg?height=48&width=48", bio: "命理爱好者，学习八字3年" },
    reason: "对八字命理非常感兴趣，希望能加入圈子与各位老师交流学习，提升自己的命理水平。",
    status: "pending",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    user: { id: "u2", name: "李四", avatar: "/placeholder.svg?height=48&width=48", bio: "风水师，从业5年" },
    reason: "想与圈内同好交流风水心得，分享实战经验。",
    status: "pending",
    createdAt: "2024-01-15T09:20:00Z",
  },
  {
    id: "3",
    user: { id: "u3", name: "王五", avatar: "/placeholder.svg?height=48&width=48" },
    reason: "朋友推荐的圈子，想来学习。",
    status: "pending",
    createdAt: "2024-01-14T18:45:00Z",
  },
  {
    id: "4",
    user: { id: "u4", name: "赵六", avatar: "/placeholder.svg?height=48&width=48", bio: "国学爱好者" },
    reason: "希望学习传统文化知识",
    status: "approved",
    createdAt: "2024-01-13T14:00:00Z",
    processedAt: "2024-01-13T16:30:00Z",
  },
  {
    id: "5",
    user: { id: "u5", name: "钱七", avatar: "/placeholder.svg?height=48&width=48" },
    reason: "...",
    status: "rejected",
    createdAt: "2024-01-12T11:00:00Z",
    processedAt: "2024-01-12T15:00:00Z",
    rejectReason: "申请理由过于简单",
  },
]

// 骨架屏
function RequestSkeleton() {
  return (
    <div className="space-y-3 p-4">
      {[1, 2, 3].map(i => (
        <div key={i} className="bg-white rounded-xl p-4 animate-pulse">
          <div className="flex gap-3">
            <div className="w-12 h-12 bg-[#F2EFEA] rounded-full" />
            <div className="flex-1 space-y-2">
              <div className="h-4 bg-[#F2EFEA] rounded w-24" />
              <div className="h-3 bg-[#F2EFEA] rounded w-32" />
            </div>
          </div>
          <div className="mt-3 h-4 bg-[#F2EFEA] rounded w-full" />
          <div className="mt-2 h-4 bg-[#F2EFEA] rounded w-2/3" />
        </div>
      ))}
    </div>
  )
}

// 申请卡片
function RequestCard({ 
  request, 
  isSelected,
  onSelect,
  onApprove,
  onReject,
  expanded,
  onToggleExpand,
}: { 
  request: JoinRequest
  isSelected: boolean
  onSelect: () => void
  onApprove: () => void
  onReject: () => void
  expanded: boolean
  onToggleExpand: () => void
}) {
  const isPending = request.status === 'pending'
  const isApproved = request.status === 'approved'
  const isRejected = request.status === 'rejected'
  
  const formatTime = (dateStr: string) => {
    const date = new Date(dateStr)
    const now = new Date()
    const diff = now.getTime() - date.getTime()
    const hours = Math.floor(diff / (1000 * 60 * 60))
    if (hours < 1) return '刚刚'
    if (hours < 24) return `${hours}小时前`
    const days = Math.floor(hours / 24)
    if (days < 7) return `${days}天前`
    return date.toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' })
  }
  
  return (
    <div className={cn(
      "bg-white rounded-xl overflow-hidden transition-all",
      isPending ? "shadow-[0_2px_12px_rgba(0,0,0,0.06)]" : "opacity-70",
      isSelected && "ring-2 ring-[#C41E3A]"
    )}>
      {/* 头部 */}
      <div className="p-4">
        <div className="flex items-start gap-3">
          {/* 选择框（仅待审批显示） */}
          {isPending && (
            <button
              onClick={onSelect}
              className={cn(
                "w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 mt-1 transition-colors",
                isSelected 
                  ? "bg-[#C41E3A] border-[#C41E3A]" 
                  : "border-[#D9D9D9] hover:border-[#C41E3A]"
              )}
            >
              {isSelected && <Check className="w-3 h-3 text-white" />}
            </button>
          )}
          
          {/* 用户信息 */}
          <img
            src={request.user.avatar}
            alt={request.user.name}
            className="w-12 h-12 rounded-full object-cover"
          />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <span className="font-medium text-[#2C2C2C]">{request.user.name}</span>
              {!isPending && (
                <span className={cn(
                  "text-xs px-2 py-0.5 rounded-full",
                  isApproved ? "bg-green-50 text-green-600" : "bg-red-50 text-red-600"
                )}>
                  {isApproved ? "已通过" : "已拒绝"}
                </span>
              )}
            </div>
            {request.user.bio && (
              <p className="text-xs text-[#999999] mt-0.5 truncate">{request.user.bio}</p>
            )}
            <div className="flex items-center gap-1 mt-1 text-xs text-[#999999]">
              <Clock className="w-3 h-3" />
              <span>{formatTime(request.createdAt)}</span>
            </div>
          </div>
          
          {/* 展开按钮 */}
          <button 
            onClick={onToggleExpand}
            className="p-1 text-[#999999] hover:text-[#666666]"
          >
            {expanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
          </button>
        </div>
        
        {/* 申请理由 */}
        <div className="mt-3 pl-8">
          <p className="text-sm text-[#666666]">
            <span className="text-[#999999]">申请理由：</span>
            {request.reason}
          </p>
        </div>
        
        {/* 展开详情 */}
        {expanded && (
          <div className="mt-3 pl-8 pt-3 border-t border-[#F2EFEA] space-y-2">
            <div className="text-xs text-[#999999]">
              申请时间：{new Date(request.createdAt).toLocaleString('zh-CN')}
            </div>
            {request.processedAt && (
              <div className="text-xs text-[#999999]">
                处理时间：{new Date(request.processedAt).toLocaleString('zh-CN')}
              </div>
            )}
            {request.rejectReason && (
              <div className="text-xs text-red-500">
                拒绝原因：{request.rejectReason}
              </div>
            )}
          </div>
        )}
      </div>
      
      {/* 操作按钮（仅待审批显示） */}
      {isPending && (
        <div className="flex border-t border-[#F2EFEA]">
          <button
            onClick={onReject}
            className="flex-1 py-3 text-sm text-[#666666] hover:bg-[#F5F0E8] transition-colors flex items-center justify-center gap-1"
          >
            <XCircle className="w-4 h-4" />
            拒绝
          </button>
          <div className="w-px bg-[#F2EFEA]" />
          <button
            onClick={onApprove}
            className="flex-1 py-3 text-sm text-[#C41E3A] hover:bg-red-50 transition-colors flex items-center justify-center gap-1 font-medium"
          >
            <CheckCircle className="w-4 h-4" />
            通过
          </button>
        </div>
      )}
    </div>
  )
}

// 拒绝原因弹窗
function RejectModal({ 
  isOpen, 
  onClose, 
  onConfirm 
}: { 
  isOpen: boolean
  onClose: () => void
  onConfirm: (reason: string) => void
}) {
  const [reason, setReason] = useState("")
  
  if (!isOpen) return null
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <div className="relative bg-white rounded-2xl w-[85%] max-w-sm p-5">
        <h3 className="text-lg font-semibold text-[#2C2C2C] mb-4">拒绝申请</h3>
        <textarea
          value={reason}
          onChange={(e) => setReason(e.target.value)}
          placeholder="请输入拒绝原因（选填）"
          className="w-full h-24 p-3 border border-[#E8E3DB] rounded-lg text-sm resize-none focus:outline-none focus:border-[#C41E3A]"
        />
        <div className="flex gap-3 mt-4">
          <button
            onClick={onClose}
            className="flex-1 py-2.5 rounded-lg border border-[#E8E3DB] text-[#666666] text-sm"
          >
            取消
          </button>
          <button
            onClick={() => {
              onConfirm(reason)
              setReason("")
            }}
            className="flex-1 py-2.5 rounded-lg bg-[#C41E3A] text-white text-sm"
          >
            确认拒绝
          </button>
        </div>
      </div>
    </div>
  )
}

export default function JoinRequestsPage() {
  const params = useParams()
  const router = useRouter()
  const circleId = params.id as string
  
  const [isLoading, setIsLoading] = useState(true)
  const [requests, setRequests] = useState<JoinRequest[]>([])
  const [filter, setFilter] = useState<'pending' | 'processed'>('pending')
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [rejectingId, setRejectingId] = useState<string | null>(null)
  const [isBatchMode, setIsBatchMode] = useState(false)
  
  useEffect(() => {
    // TODO: 调用 circleApi.listJoinRequests
    setTimeout(() => {
      setRequests(mockRequests)
      setIsLoading(false)
    }, 800)
  }, [circleId])
  
  const pendingRequests = requests.filter(r => r.status === 'pending')
  const processedRequests = requests.filter(r => r.status !== 'pending')
  const displayRequests = filter === 'pending' ? pendingRequests : processedRequests
  
  const handleSelect = (id: string) => {
    setSelectedIds(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }
  
  const handleSelectAll = () => {
    if (selectedIds.size === pendingRequests.length) {
      setSelectedIds(new Set())
    } else {
      setSelectedIds(new Set(pendingRequests.map(r => r.id)))
    }
  }
  
  const handleApprove = async (id: string) => {
    // TODO: 调用 circleApi.approveJoinRequest
    setRequests(prev => prev.map(r => 
      r.id === id ? { ...r, status: 'approved' as const, processedAt: new Date().toISOString() } : r
    ))
    setSelectedIds(prev => {
      const next = new Set(prev)
      next.delete(id)
      return next
    })
  }
  
  const handleReject = async (id: string, reason: string) => {
    // TODO: 调用 circleApi.rejectJoinRequest
    setRequests(prev => prev.map(r => 
      r.id === id ? { ...r, status: 'rejected' as const, processedAt: new Date().toISOString(), rejectReason: reason || undefined } : r
    ))
    setSelectedIds(prev => {
      const next = new Set(prev)
      next.delete(id)
      return next
    })
    setRejectingId(null)
  }
  
  const handleBatchApprove = async () => {
    // TODO: 调用 circleApi.batchApproveRequests
    const ids = Array.from(selectedIds)
    setRequests(prev => prev.map(r => 
      ids.includes(r.id) ? { ...r, status: 'approved' as const, processedAt: new Date().toISOString() } : r
    ))
    setSelectedIds(new Set())
    setIsBatchMode(false)
  }
  
  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      {/* 顶部导航 */}
      <div className="sticky top-0 z-40 bg-white border-b border-[#F2EFEA]">
        <div className="flex items-center justify-between px-4 h-14">
          <button onClick={() => router.back()} className="p-1 -ml-1">
            <ChevronLeft className="w-6 h-6 text-[#2C2C2C]" />
          </button>
          <h1 className="text-lg font-semibold text-[#2C2C2C]">入圈申请</h1>
          <div className="w-8" />
        </div>
        
        {/* 统计信息 */}
        <div className="flex items-center gap-4 px-4 py-3 bg-gradient-to-r from-[#C41E3A]/5 to-transparent">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-[#C41E3A]/10 flex items-center justify-center">
              <Users className="w-4 h-4 text-[#C41E3A]" />
            </div>
            <div>
              <div className="text-lg font-bold text-[#C41E3A]">{pendingRequests.length}</div>
              <div className="text-xs text-[#999999]">待审批</div>
            </div>
          </div>
          <div className="w-px h-8 bg-[#E8E3DB]" />
          <div>
            <div className="text-lg font-bold text-[#2C2C2C]">{processedRequests.length}</div>
            <div className="text-xs text-[#999999]">已处理</div>
          </div>
        </div>
        
        {/* 筛选Tab */}
        <div className="flex border-b border-[#F2EFEA]">
          {[
            { key: 'pending', label: '待审批' },
            { key: 'processed', label: '已处理' },
          ].map(tab => (
            <button
              key={tab.key}
              onClick={() => {
                setFilter(tab.key as typeof filter)
                setSelectedIds(new Set())
                setIsBatchMode(false)
              }}
              className={cn(
                "flex-1 py-3 text-sm font-medium relative transition-colors",
                filter === tab.key ? "text-[#C41E3A]" : "text-[#999999]"
              )}
            >
              {tab.label}
              {filter === tab.key && (
                <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-8 h-0.5 bg-[#C41E3A] rounded-full" />
              )}
            </button>
          ))}
        </div>
      </div>
      
      {/* 批量操作栏 */}
      {filter === 'pending' && pendingRequests.length > 0 && (
        <div className="sticky top-[142px] z-30 bg-[#FAF8F5] px-4 py-2 flex items-center justify-between">
          <button
            onClick={handleSelectAll}
            className="flex items-center gap-2 text-sm text-[#666666]"
          >
            <div className={cn(
              "w-4 h-4 rounded border-2 flex items-center justify-center transition-colors",
              selectedIds.size === pendingRequests.length && pendingRequests.length > 0
                ? "bg-[#C41E3A] border-[#C41E3A]" 
                : "border-[#D9D9D9]"
            )}>
              {selectedIds.size === pendingRequests.length && pendingRequests.length > 0 && (
                <Check className="w-2.5 h-2.5 text-white" />
              )}
            </div>
            全选
          </button>
          
          {selectedIds.size > 0 && (
            <button
              onClick={handleBatchApprove}
              className="px-4 py-1.5 bg-[#C41E3A] text-white text-sm rounded-full"
            >
              批量通过 ({selectedIds.size})
            </button>
          )}
        </div>
      )}
      
      {/* 申请列表 */}
      {isLoading ? (
        <RequestSkeleton />
      ) : displayRequests.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20">
          <div className="w-16 h-16 rounded-full bg-[#F2EFEA] flex items-center justify-center mb-4">
            <Users className="w-8 h-8 text-[#CCCCCC]" />
          </div>
          <p className="text-[#999999]">
            {filter === 'pending' ? "暂无待审批申请" : "暂无已处理申请"}
          </p>
        </div>
      ) : (
        <div className="p-4 space-y-3">
          {displayRequests.map(request => (
            <RequestCard
              key={request.id}
              request={request}
              isSelected={selectedIds.has(request.id)}
              onSelect={() => handleSelect(request.id)}
              onApprove={() => handleApprove(request.id)}
              onReject={() => setRejectingId(request.id)}
              expanded={expandedId === request.id}
              onToggleExpand={() => setExpandedId(expandedId === request.id ? null : request.id)}
            />
          ))}
        </div>
      )}
      
      {/* 拒绝原因弹窗 */}
      <RejectModal
        isOpen={!!rejectingId}
        onClose={() => setRejectingId(null)}
        onConfirm={(reason) => rejectingId && handleReject(rejectingId, reason)}
      />
    </div>
  )
}
