// proto-ref-app/ebook/bookmarks/page.tsx
"use client"

import { useState } from "react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  ArrowLeft,
  Bookmark,
  BookOpen,
  Trash2,
  ChevronRight,
  Search,
} from "lucide-react"
import Link from "next/link"

interface BookmarkItem {
  id: string
  bookId: string
  bookTitle: string
  bookCoverColor: string
  chapterId: string
  chapterTitle: string
  text: string      // first line of context
  pageNum: number
  createdAt: string
}

const bookmarks: BookmarkItem[] = [
  {
    id: "bm1",
    bookId: "1",
    bookTitle: "八字命理精解",
    bookCoverColor: "#1e3a5f",
    chapterId: "2",
    chapterTitle: "第二章 天干地支详解",
    text: "天干共有十个，分别是：甲、乙、丙、丁、戊、己、庚、辛、壬、癸。",
    pageNum: 45,
    createdAt: "今天 14:32",
  },
  {
    id: "bm2",
    bookId: "1",
    bookTitle: "八字命理精解",
    bookCoverColor: "#1e3a5f",
    chapterId: "3",
    chapterTitle: "第三章 五行生克制化",
    text: "五行之间存在着相生相克的关系，理解这一原理是学习八字命理的第一步。",
    pageNum: 78,
    createdAt: "昨天 09:15",
  },
  {
    id: "bm3",
    bookId: "3",
    bookTitle: "风水学基础教程",
    bookCoverColor: "#4a1942",
    chapterId: "1",
    chapterTitle: "第一章 风水学概论",
    text: "风水学是中国传统文化中的重要组成部分，讲究天地人三才合一。",
    pageNum: 12,
    createdAt: "3天前",
  },
  {
    id: "bm4",
    bookId: "5",
    bookTitle: "紫微斗数全书",
    bookCoverColor: "#1e3a5f",
    chapterId: "2",
    chapterTitle: "第二章 十四主星详解",
    text: "紫微星是斗数之首，入命宫主贵气，其人多有才华，气宇不凡。",
    pageNum: 56,
    createdAt: "1周前",
  },
]

// Group by book
function groupByBook(items: BookmarkItem[]) {
  return items.reduce<Record<string, BookmarkItem[]>>((acc, item) => {
    if (!acc[item.bookId]) acc[item.bookId] = []
    acc[item.bookId].push(item)
    return acc
  }, {})
}

export default function EbookBookmarksPage() {
  const [search, setSearch] = useState("")
  const [items, setItems] = useState(bookmarks)

  const filtered = items.filter(
    (b) =>
      !search ||
      b.bookTitle.includes(search) ||
      b.text.includes(search) ||
      b.chapterTitle.includes(search)
  )

  const grouped = groupByBook(filtered)

  const deleteBookmark = (id: string) => {
    setItems((prev) => prev.filter((b) => b.id !== id))
  }

  return (
    <div className="min-h-screen bg-[var(--ebook-bg)]">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-sm border-b border-[var(--ebook-border)]">
        <div className="flex items-center justify-between px-4 h-14">
          <Link href="/ebook/bookshelf" className="p-1.5 -ml-1.5 rounded-lg hover:bg-slate-100 active:scale-95 transition-all">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="font-semibold text-base text-[var(--ebook-text)]">书签管理</h1>
          <span className="text-xs text-[var(--ebook-text-soft)]">{items.length} 个</span>
        </div>

        {/* Search */}
        <div className="px-4 pb-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="搜索书签..."
              className="w-full h-9 pl-9 pr-4 bg-slate-100 rounded-full text-sm border-0 focus:outline-none focus:ring-2 focus:ring-[var(--ebook-primary)]"
            />
          </div>
        </div>
      </header>

      <main className="px-4 py-3 pb-8 space-y-5">
        {Object.keys(grouped).length === 0 ? (
          <div className="text-center py-16">
            <Bookmark className="w-12 h-12 mx-auto mb-3 text-slate-200" />
            <p className="text-[var(--ebook-text-soft)] font-medium mb-1">暂无书签</p>
            <p className="text-sm text-slate-400 mb-4">在阅读时点击书签按钮保存位置</p>
            <Button className="bg-[var(--ebook-primary)]" asChild>
              <Link href="/ebook/bookshelf">去阅读</Link>
            </Button>
          </div>
        ) : (
          Object.entries(grouped).map(([bookId, bms]) => {
            const book = bms[0]
            return (
              <div key={bookId}>
                {/* Book header */}
                <div className="flex items-center gap-2.5 mb-2">
                  <div
                    className="w-8 h-[46px] rounded shadow-sm flex-shrink-0 relative overflow-hidden"
                    style={{ background: book.bookCoverColor }}
                  >
                    <div className="absolute left-0 top-0 bottom-0 w-0.5 bg-white/20" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-sm text-[var(--ebook-text)] line-clamp-1">{book.bookTitle}</h3>
                    <p className="text-xs text-[var(--ebook-text-soft)]">{bms.length} 个书签</p>
                  </div>
                  <Link
                    href={`/ebook/reader/${bookId}`}
                    className="text-xs text-[var(--ebook-primary)] flex items-center gap-0.5"
                  >
                    继续读<ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </div>

                {/* Bookmarks list */}
                <div className="bg-white rounded-xl border border-[var(--ebook-border)] overflow-hidden divide-y divide-[var(--ebook-border)]">
                  {bms.map((bm) => (
                    <Link
                      key={bm.id}
                      href={`/ebook/reader/${bm.bookId}?chapter=${bm.chapterId}`}
                      className="flex items-start gap-3 px-4 py-3.5 hover:bg-slate-50 transition-all group"
                    >
                      <Bookmark className="w-4 h-4 text-[var(--ebook-primary)] flex-shrink-0 mt-0.5" />
                      <div className="flex-1 min-w-0">
                        <p className="text-xs text-[var(--ebook-text-soft)] mb-1">{bm.chapterTitle} · 第{bm.pageNum}页</p>
                        <p className="text-sm text-[var(--ebook-text)] line-clamp-2 leading-relaxed">{bm.text}</p>
                        <p className="text-[10px] text-slate-400 mt-1">{bm.createdAt}</p>
                      </div>
                      <button
                        onClick={(e) => { e.preventDefault(); deleteBookmark(bm.id); }}
                        className="opacity-0 group-hover:opacity-100 p-1 rounded-lg hover:bg-red-50 transition-all text-slate-400 hover:text-red-500"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </Link>
                  ))}
                </div>
              </div>
            )
          })
        )}
      </main>
    </div>
  )
}

// apps/mobile/src/pkg-ebook/bookmarks/index.vue
<template>
  <view class="page">
    <!-- Header -->
    <view class="hd">
      <view class="hd-bar">
        <view
          class="icon-btn"
          @tap="goBack"
        >
          <AppIcon
            name="arrow-left"
            :size="40"
            :color="C.text"
          />
        </view>
        <text class="hd-title">
          书签管理
        </text>
        <text class="hd-count">
          {{ items.length }} 个
        </text>
      </view>
      <view class="hd-search">
        <view class="search-box">
          <AppIcon
            name="search"
            :size="32"
            :color="C.slate400"
            class="search-icon"
          />
          <input
            v-model="search"
            class="search-input"
            placeholder="搜索书签..."
            placeholder-class="ph"
          >
        </view>
      </view>
    </view>

    <scroll-view
      scroll-y
      class="body"
    >
      <!-- 空状态 -->
      <view
        v-if="groupedKeys.length === 0"
        class="empty"
      >
        <AppIcon
          name="bookmark"
          :size="96"
          :color="C.slate200"
        />
        <text class="empty-title">
          暂无书签
        </text>
        <text class="empty-sub">
          在阅读时点击书签按钮保存位置
        </text>
        <view
          class="empty-btn"
          @tap="goShelf"
        >
          <text class="empty-btn-tx">
            去阅读
          </text>
        </view>
      </view>

      <!-- 按书分组 -->
      <view
        v-for="g in grouped"
        :key="g.bookId"
        class="group"
      >
        <view class="book-hd">
          <view
            class="book-cover"
            :style="{ background: g.book.bookCoverColor }"
          >
            <view class="cover-spine" />
          </view>
          <view class="book-meta">
            <text class="book-title">
              {{ g.book.bookTitle }}
            </text>
            <text class="book-sub">
              {{ g.list.length }} 个书签
            </text>
          </view>
          <view
            class="continue"
            @tap="goReader(g.bookId)"
          >
            <text class="continue-tx">
              继续读
            </text>
            <AppIcon
              name="chevron-right"
              :size="28"
              :color="C.primary"
            />
          </view>
        </view>

        <view class="card">
          <view
            v-for="(bm, idx) in g.list"
            :key="bm.id"
            class="bm-item"
            :class="{ 'no-border': idx === 0 }"
            @tap="goReaderChapter(bm)"
          >
            <AppIcon
              name="bookmark"
              :size="32"
              :color="C.primary"
              class="bm-icon"
            />
            <view class="bm-body">
              <text class="bm-chapter">
                {{ bm.chapterTitle }} · 第{{ bm.pageNum }}页
              </text>
              <text class="bm-text">
                {{ bm.text }}
              </text>
              <text class="bm-time">
                {{ bm.createdAt }}
              </text>
            </view>
            <view
              class="del-btn"
              @tap.stop="del(bm.id)"
            >
              <AppIcon
                name="trash-2"
                :size="28"
                :color="C.slate400"
              />
            </view>
          </view>
        </view>
      </view>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import AppIcon from '@/components/common/app-icon.vue'
import { ebookApi, type EbookBookmark } from '@/lib/ebook-data'

const C = {
  text: '#1e293b', primary: '#2563eb', slate400: '#94a3b8', slate200: '#e2e8f0',
}

const search = ref('')
const items = ref<EbookBookmark[]>([])

onMounted(async () => {
  const res = await ebookApi.bookmarks()
  items.value = res.items
})

const filtered = computed(() =>
  items.value.filter(
    (b) => !search.value || b.bookTitle.includes(search.value) || b.text.includes(search.value) || b.chapterTitle.includes(search.value),
  ),
)
const grouped = computed(() => {
  const map: Record<string, EbookBookmark[]> = {}
  filtered.value.forEach((b) => {
    if (!map[b.bookId]) map[b.bookId] = []
    map[b.bookId].push(b)
  })
  return Object.keys(map).map((bookId) => ({ bookId, book: map[bookId][0], list: map[bookId] }))
})
const groupedKeys = computed(() => grouped.value.map((g) => g.bookId))

function del(id: string) {
  items.value = items.value.filter((b) => b.id !== id)
}
function goBack() {
  uni.navigateBack()
}
function goShelf() {
  uni.navigateTo({ url: '/pkg-ebook/bookshelf/index' })
}
function goReader(bookId: string) {
  uni.navigateTo({ url: `/pkg-ebook/reader/index?id=${bookId}` })
}
function goReaderChapter(bm: EbookBookmark) {
  uni.navigateTo({ url: `/pkg-ebook/reader/index?id=${bm.bookId}&chapter=${bm.chapterId}` })
}
</script>

<style scoped lang="scss">
.page {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: var(--ebook-bg);
}
.hd {
  position: sticky;
  top: 0;
  z-index: 50;
  background: rgba(255, 255, 255, 0.95);
  border-bottom: 2rpx solid var(--ebook-border);
}
.hd-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 32rpx;
  height: 112rpx;
}
.icon-btn {
  padding: 12rpx;
  margin-left: -12rpx;
  border-radius: 16rpx;
}
.hd-title {
  font-size: 32rpx;
  font-weight: 600;
  color: var(--ebook-text);
}
.hd-count {
  font-size: 24rpx;
  color: var(--ebook-text-soft);
}
.hd-search {
  padding: 0 32rpx 24rpx;
}
.search-box {
  position: relative;
  display: flex;
  align-items: center;
}
.search-icon {
  position: absolute;
  left: 24rpx;
  z-index: 1;
}
.search-input {
  width: 100%;
  height: 72rpx;
  padding: 0 32rpx 0 72rpx;
  background: #f1f5f9;
  border-radius: 999rpx;
  font-size: 28rpx;
  color: var(--ebook-text);
  box-sizing: border-box;
}
.ph {
  color: #94a3b8;
}
.body {
  flex: 1;
  padding: 24rpx 32rpx 64rpx;
  box-sizing: border-box;
}
.empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 128rpx 0;
}
.empty-title {
  font-size: 28rpx;
  font-weight: 500;
  color: var(--ebook-text-soft);
  margin: 24rpx 0 8rpx;
}
.empty-sub {
  font-size: 26rpx;
  color: #94a3b8;
  margin-bottom: 32rpx;
}
.empty-btn {
  padding: 18rpx 48rpx;
  background: var(--ebook-primary);
  border-radius: 16rpx;
}
.empty-btn-tx {
  color: #fff;
  font-size: 28rpx;
  font-weight: 500;
}
.group {
  margin-bottom: 40rpx;
}
.book-hd {
  display: flex;
  align-items: center;
  gap: 20rpx;
  margin-bottom: 16rpx;
}
.book-cover {
  width: 64rpx;
  height: 92rpx;
  border-radius: 8rpx;
  box-shadow: 0 2rpx 6rpx rgba(0, 0, 0, 0.1);
  flex-shrink: 0;
  position: relative;
  overflow: hidden;
}
.cover-spine {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 4rpx;
  background: rgba(255, 255, 255, 0.2);
}
.book-meta {
  flex: 1;
  min-width: 0;
}
.book-title {
  display: block;
  font-size: 28rpx;
  font-weight: 600;
  color: var(--ebook-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.book-sub {
  font-size: 24rpx;
  color: var(--ebook-text-soft);
}
.continue {
  display: flex;
  align-items: center;
  gap: 2rpx;
}
.continue-tx {
  font-size: 24rpx;
  color: var(--ebook-primary);
}
.card {
  background: #fff;
  border-radius: 24rpx;
  border: 2rpx solid var(--ebook-border);
  overflow: hidden;
}
.bm-item {
  display: flex;
  align-items: flex-start;
  gap: 24rpx;
  padding: 28rpx 32rpx;
  border-top: 2rpx solid var(--ebook-border);
}
.bm-item.no-border {
  border-top: none;
}
.bm-icon {
  flex-shrink: 0;
  margin-top: 4rpx;
}
.bm-body {
  flex: 1;
  min-width: 0;
}
.bm-chapter {
  display: block;
  font-size: 24rpx;
  color: var(--ebook-text-soft);
  margin-bottom: 8rpx;
}
.bm-text {
  display: block;
  font-size: 28rpx;
  color: var(--ebook-text);
  line-height: 1.6;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.bm-time {
  display: block;
  font-size: 20rpx;
  color: #94a3b8;
  margin-top: 8rpx;
}
.del-btn {
  padding: 8rpx;
  flex-shrink: 0;
}
</style>
