// components/common/discussion-sheet.tsx
"use client"

/**
 * 讨论抽屉包装组件
 *
 * 把讨论母版 DiscussionPanel 包成底部弹层，用于详情/阅读页的「查看全部讨论」。
 * 统一替换原型中分散的 CommentSheet，复用于古籍/电子书/诗词/文章等场景。
 */

import { useEffect } from "react"
import { X } from "lucide-react"
import { DiscussionPanel } from "@/components/common/discussion-panel"
import type { DiscussionConfig, DiscussionItem } from "@/lib/types/discussion"

interface DiscussionSheetProps {
  open: boolean
  onClose: () => void
  config: DiscussionConfig
  items: DiscussionItem[]
  /** 启用 AI 辅助输入 */
  enableAIAssist?: boolean
}

export function DiscussionSheet({ open, onClose, config, items, enableAIAssist }: DiscussionSheetProps) {
  // 打开时锁定背景滚动
  useEffect(() => {
    if (open) {
      document.body.style.overflow = "hidden"
      return () => {
        document.body.style.overflow = ""
      }
    }
  }, [open])

  return (
    <>
      {/* 遮罩 */}
      <div
        className={`fixed inset-0 z-50 bg-black/40 transition-opacity duration-300 ${
          open ? "opacity-100" : "pointer-events-none opacity-0"
        }`}
        onClick={onClose}
        aria-hidden
      />
      {/* 抽屉 */}
      <div
        className={`fixed inset-x-0 bottom-0 z-50 flex h-[80vh] flex-col overflow-hidden rounded-t-2xl bg-card shadow-2xl transition-transform duration-300 ${
          open ? "translate-y-0" : "translate-y-full"
        }`}
        role="dialog"
        aria-modal="true"
        aria-label={config.title}
      >
        {/* 顶部拖拽条与关闭 */}
        <div className="relative flex-shrink-0 pt-2.5">
          <div className="mx-auto h-1 w-10 rounded-full bg-border" aria-hidden />
          <button
            onClick={onClose}
            className="absolute right-3 top-2 flex h-8 w-8 items-center justify-center rounded-full text-muted-foreground active:bg-muted"
            aria-label="关闭"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
        {/* 母版面板 */}
        <DiscussionPanel
          config={config}
          items={items}
          enableAIAssist={enableAIAssist}
          className="min-h-0 flex-1"
        />
      </div>
    </>
  )
}

// apps/mobile/src/components/common/discussion-sheet.vue
<template>
  <view>
    <!-- 遮罩 -->
    <view class="ds-mask" :class="{ 'ds-mask-on': open }" @tap="emit('close')" />
    <!-- 弹层主体 -->
    <view class="ds-sheet" :class="{ 'ds-sheet-on': open }">
      <view class="ds-grab-wrap">
        <view class="ds-grab" />
        <view class="ds-close" @tap="emit('close')">
          <app-icon name="x" :size="40" color="#999999" />
        </view>
      </view>
      <discussion-panel
        :config="config"
        :items="items"
        :inline="true"
        :enable-a-i-assist="enableAIAssist"
        class="ds-panel"
      />
    </view>
</template>

<script setup lang="ts">
import DiscussionPanel from '@/components/common/discussion-panel.vue'
import type { DiscussionConfig, DiscussionItem } from '@/lib/discussion-types'

defineProps<{
  open: boolean
  config: DiscussionConfig
  items: DiscussionItem[]
  enableAIAssist?: boolean
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()
</script>

<style scoped>
.ds-mask {
  position: fixed;
  inset: 0;
  z-index: 50;
  background: rgba(0, 0, 0, 0.4);
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.3s;
}
.ds-mask-on {
  opacity: 1;
  pointer-events: auto;
}
.ds-sheet {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 50;
  display: flex;
  flex-direction: column;
  height: 80vh;
  border-radius: 32rpx 32rpx 0 0;
  background: var(--card);
  transform: translateY(100%);
  transition: transform 0.3s;
}
.ds-sheet-on {
  transform: translateY(0);
}
.ds-grab-wrap {
  position: relative;
  flex-shrink: 0;
  padding: 16rpx 32rpx 0;
}
.ds-grab {
  width: 80rpx;
  height: 8rpx;
  border-radius: 999rpx;
  background: rgba(150, 150, 150, 0.3);
  margin: 0 auto;
}
.ds-close {
  position: absolute;
  right: 32rpx;
  top: 12rpx;
}
.ds-panel {
  min-height: 0;
  flex: 1;
}
</style>
