// app/shop/page.tsx
"use client"

import { useState, useEffect, useCallback } from "react"
import { useRouter } from "next/navigation"
import { Search, ChevronRight, Clock, Users, Flame, Star, Zap, Gift, Ticket, TrendingUp, ShoppingBag, Bell } from "lucide-react"

// 快捷活动入口
const quickActions = [
  { id: "flash", name: "限时秒杀", icon: Zap, color: "from-red-500 to-orange-500", link: "/shop/flash-sale" },
  { id: "group", name: "拼团特惠", icon: Users, color: "from-orange-500 to-amber-500", link: "/shop/group-buy" },
  { id: "coupon", name: "领券中心", icon: Ticket, color: "from-pink-500 to-rose-500", link: "/shop/coupons" },
  { id: "points", name: "积分兑换", icon: Gift, color: "from-purple-500 to-indigo-500", link: "/shop/exchange" },
]

// Mock数据
const mockBanners = [
  { id: "1", image: "/placeholder.svg?height=200&width=400", title: "国学典籍大促", link: "/shop/activity/1", linkType: "activity" as const },
  { id: "2", image: "/placeholder.svg?height=200&width=400", title: "新品上市", link: "/shop/products?tag=new", linkType: "url" as const },
  { id: "3", image: "/placeholder.svg?height=200&width=400", title: "会员专享", link: "/shop/vip", linkType: "url" as const },
]

const mockCategories = [
  { id: "1", name: "古籍善本", icon: "📚" },
  { id: "2", name: "文房四宝", icon: "🖌️" },
  { id: "3", name: "香道用品", icon: "🪷" },
  { id: "4", name: "茶道器具", icon: "🍵" },
  { id: "5", name: "命理工具", icon: "🧭" },
  { id: "6", name: "风水摆件", icon: "🏺" },
  { id: "7", name: "养生食品", icon: "🌿" },
  { id: "8", name: "更多分类", icon: "📋" },
]

const mockFlashSale = {
  id: "1",
  title: "限时秒杀",
  startTime: new Date().toISOString(),
  endTime: new Date(Date.now() + 3600000 * 2).toISOString(),
  status: "ongoing" as const,
  products: [
    { id: "1", name: "渊海子平精装版", cover: "/placeholder.svg?height=100&width=100", price: 68, originalPrice: 128, stock: 50, sold: 42 },
    { id: "2", name: "罗盘专业款", cover: "/placeholder.svg?height=100&width=100", price: 199, originalPrice: 399, stock: 30, sold: 18 },
    { id: "3", name: "紫檀木签筒", cover: "/placeholder.svg?height=100&width=100", price: 88, originalPrice: 168, stock: 100, sold: 67 },
  ],
}

const mockGroupBuy = {
  id: "1",
  title: "3人成团",
  cover: "/placeholder.svg?height=120&width=120",
  price: 299,
  originalPrice: 599,
  minMembers: 3,
  currentMembers: 2,
  endTime: new Date(Date.now() + 86400000).toISOString(),
  status: "ongoing" as const,
  productName: "周易全集精装套装",
}

const mockProducts = [
  { id: "1", name: "渊海子平（精装典藏版）", cover: "/placeholder.svg?height=200&width=200", price: 128, originalPrice: 168, sales: 2860, rating: 4.9, category: "古籍", isHot: true },
  { id: "2", name: "专业风水罗盘", cover: "/placeholder.svg?height=200&width=200", price: 399, originalPrice: 599, sales: 1250, rating: 4.8, category: "工具", isNew: true },
  { id: "3", name: "紫檀木文房套装", cover: "/placeholder.svg?height=200&width=200", price: 688, originalPrice: 888, sales: 560, rating: 4.9, category: "文房" },
  { id: "4", name: "沉香线香礼盒", cover: "/placeholder.svg?height=200&width=200", price: 168, originalPrice: 238, sales: 3200, rating: 4.7, category: "香道", isHot: true },
  { id: "5", name: "紫砂茶具套装", cover: "/placeholder.svg?height=200&width=200", price: 458, originalPrice: 658, sales: 890, rating: 4.8, category: "茶道" },
  { id: "6", name: "黄铜貔貅摆件", cover: "/placeholder.svg?height=200&width=200", price: 299, originalPrice: 399, sales: 1560, rating: 4.6, category: "摆件", isNew: true },
]

// 骨架屏
function ShopSkeleton() {
  return (
    <div className="min-h-screen bg-[#FAF8F5] animate-pulse">
      <div className="h-12 bg-white" />
      <div className="mx-4 mt-4 h-36 rounded-xl bg-gray-200" />
      <div className="mx-4 mt-4 grid grid-cols-4 gap-3">
        {[...Array(8)].map((_, i) => (
          <div key={i} className="flex flex-col items-center gap-2">
            <div className="w-12 h-12 rounded-full bg-gray-200" />
            <div className="w-10 h-3 rounded bg-gray-200" />
          </div>
        ))}
      </div>
      <div className="mx-4 mt-6 h-32 rounded-xl bg-gray-200" />
      <div className="mx-4 mt-6 grid grid-cols-2 gap-3">
        {[...Array(4)].map((_, i) => (
          <div key={i} className="h-64 rounded-xl bg-gray-200" />
        ))}
      </div>
    </div>
  )
}

export default function ShopPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [banners] = useState(mockBanners)
  const [categories] = useState(mockCategories)
  const [flashSale] = useState(mockFlashSale)
  const [groupBuy] = useState(mockGroupBuy)
  const [products] = useState(mockProducts)
  const [currentBanner, setCurrentBanner] = useState(0)
  const [countdown, setCountdown] = useState({ hours: 0, minutes: 0, seconds: 0 })

  // 轮播自动切换
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentBanner(prev => (prev + 1) % banners.length)
    }, 4000)
    return () => clearInterval(timer)
  }, [banners.length])

  // 秒杀倒计时
  useEffect(() => {
    const updateCountdown = () => {
      const end = new Date(flashSale.endTime).getTime()
      const now = Date.now()
      const diff = Math.max(0, end - now)
      setCountdown({
        hours: Math.floor(diff / 3600000),
        minutes: Math.floor((diff % 3600000) / 60000),
        seconds: Math.floor((diff % 60000) / 1000),
      })
    }
    updateCountdown()
    const timer = setInterval(updateCountdown, 1000)
    return () => clearInterval(timer)
  }, [flashSale.endTime])

  // 模拟加载
  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 800)
    return () => clearTimeout(timer)
  }, [])

  const handleBannerClick = useCallback((banner: typeof mockBanners[0]) => {
    router.push(banner.link)
  }, [router])

  if (loading) return <ShopSkeleton />

  return (
    <div className="min-h-screen bg-[#FAF8F5] pb-20">
      {/* 顶部搜索栏 - 优化版 */}
      <div className="sticky top-0 z-20 bg-white px-4 py-3 shadow-sm">
        <div className="flex items-center gap-3">
          <div 
            className="flex-1 flex items-center gap-2 px-4 py-2 bg-[#FAF8F5] rounded-full cursor-pointer"
            onClick={() => router.push("/search?from=shop")}
          >
            <Search className="w-4 h-4 text-[#999999]" />
            <span className="text-sm text-[#999999]">搜索商品</span>
          </div>
          <button 
            onClick={() => router.push("/shop/cart")}
            className="relative p-2"
          >
            <ShoppingBag className="w-5 h-5 text-[#666666]" />
            <span className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-[#C41E3A] text-white text-[10px] rounded-full flex items-center justify-center">3</span>
          </button>
          <button className="relative p-2">
            <Bell className="w-5 h-5 text-[#666666]" />
            <span className="absolute top-1 right-1 w-2 h-2 bg-[#C41E3A] rounded-full" />
          </button>
        </div>
      </div>

      {/* Banner轮播 - 缩小高度 */}
      <div className="relative mx-4 mt-4 h-28 sm:h-36 rounded-xl overflow-hidden">
        <div 
          className="flex transition-transform duration-500 h-full"
          style={{ transform: `translateX(-${currentBanner * 100}%)` }}
        >
          {banners.map((banner) => (
            <div
              key={banner.id}
              className="w-full h-full flex-shrink-0 cursor-pointer"
              onClick={() => handleBannerClick(banner)}
            >
              <div 
                className="w-full h-full bg-gradient-to-r from-[#C41E3A] to-[#E85A70] flex items-center justify-center"
              >
                <span className="text-white text-xl font-bold">{banner.title}</span>
              </div>
            </div>
          ))}
        </div>
        {/* 指示器 */}
        <div className="absolute bottom-2 left-1/2 -translate-x-1/2 flex gap-1.5">
          {banners.map((_, idx) => (
            <div
              key={idx}
              className={`w-1.5 h-1.5 rounded-full transition-all ${
                idx === currentBanner ? "w-4 bg-white" : "bg-white/50"
              }`}
            />
          ))}
        </div>
      </div>

      {/* 快捷活动入口 */}
      <div className="mx-4 mt-4 grid grid-cols-4 gap-2">
        {quickActions.map(action => (
          <button
            key={action.id}
            onClick={() => router.push(action.link)}
            className={`p-3 rounded-xl bg-gradient-to-br ${action.color} text-white flex flex-col items-center gap-1.5 shadow-sm active:scale-95 transition-transform`}
          >
            <action.icon className="w-5 h-5" />
            <span className="text-xs font-medium">{action.name}</span>
          </button>
        ))}
      </div>

      {/* 分类图标网格 */}
      <div className="mx-4 mt-5 grid grid-cols-4 gap-3">
        {categories.map((cat) => (
          <div
            key={cat.id}
            className="flex flex-col items-center gap-1.5 cursor-pointer"
            onClick={() => router.push(`/shop/category/${cat.id}`)}
          >
            <div className="w-12 h-12 rounded-full bg-white shadow-sm flex items-center justify-center text-2xl">
              {cat.icon}
            </div>
            <span className="text-xs text-[#2C2C2C]">{cat.name}</span>
          </div>
        ))}
      </div>

      {/* 秒杀专区 */}
      <div className="mx-4 mt-6">
        <div 
          className="bg-gradient-to-r from-[#C41E3A] to-[#E85A70] rounded-xl p-4 cursor-pointer"
          onClick={() => router.push(`/shop/flash-sale/${flashSale.id}`)}
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Flame className="w-5 h-5 text-[#FFD700]" />
              <span className="text-white font-bold">{flashSale.title}</span>
            </div>
            <div className="flex items-center gap-1 text-white text-sm">
              <Clock className="w-4 h-4" />
              <span className="bg-white/20 px-1.5 py-0.5 rounded text-xs font-mono">
                {String(countdown.hours).padStart(2, "0")}
              </span>
              <span>:</span>
              <span className="bg-white/20 px-1.5 py-0.5 rounded text-xs font-mono">
                {String(countdown.minutes).padStart(2, "0")}
              </span>
              <span>:</span>
              <span className="bg-white/20 px-1.5 py-0.5 rounded text-xs font-mono">
                {String(countdown.seconds).padStart(2, "0")}
              </span>
            </div>
          </div>
          <div className="flex gap-3 overflow-x-auto pb-1 scrollbar-hide">
            {flashSale.products.map((product) => (
              <div
                key={product.id}
                className="flex-shrink-0 w-20 bg-white rounded-lg p-2"
                onClick={(e) => {
                  e.stopPropagation()
                  router.push(`/shop/product/${product.id}`)
                }}
              >
                <div className="w-16 h-16 mx-auto bg-[#FAF8F5] rounded-lg mb-1.5" />
                <div className="text-[#C41E3A] font-bold text-sm text-center">
                  ¥{product.price}
                </div>
                <div className="text-[#999999] text-xs line-through text-center">
                  ¥{product.originalPrice}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 拼团专区 */}
      <div className="mx-4 mt-4">
        <div 
          className="bg-white rounded-xl p-4 shadow-sm cursor-pointer"
          onClick={() => router.push(`/shop/group-buy/${groupBuy.id}`)}
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Users className="w-5 h-5 text-[#C41E3A]" />
              <span className="font-bold text-[#2C2C2C]">拼团特惠</span>
              <span className="text-xs text-white bg-[#C41E3A] px-2 py-0.5 rounded-full">
                {groupBuy.title}
              </span>
            </div>
            <ChevronRight className="w-4 h-4 text-[#999999]" />
          </div>
          <div className="flex gap-4">
            <div className="w-20 h-20 bg-[#FAF8F5] rounded-lg flex-shrink-0" />
            <div className="flex-1 min-w-0">
              <h4 className="text-sm font-medium text-[#2C2C2C] truncate">
                {groupBuy.productName}
              </h4>
              <div className="flex items-baseline gap-2 mt-1">
                <span className="text-[#C41E3A] font-bold text-lg">¥{groupBuy.price}</span>
                <span className="text-[#999999] text-xs line-through">¥{groupBuy.originalPrice}</span>
              </div>
              <div className="flex items-center gap-2 mt-2">
                <div className="flex-1 h-1.5 bg-[#FAF8F5] rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-gradient-to-r from-[#C41E3A] to-[#E85A70] rounded-full"
                    style={{ width: `${(groupBuy.currentMembers / groupBuy.minMembers) * 100}%` }}
                  />
                </div>
                <span className="text-xs text-[#C41E3A]">
                  还差{groupBuy.minMembers - groupBuy.currentMembers}人
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 商品推荐 */}
      <div className="mx-4 mt-6">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-bold text-[#2C2C2C]">为你推荐</h3>
          <span 
            className="text-xs text-[#999999] flex items-center gap-1 cursor-pointer"
            onClick={() => router.push("/shop/products")}
          >
            更多 <ChevronRight className="w-3 h-3" />
          </span>
        </div>
        <div className="grid grid-cols-2 gap-3">
          {products.map((product) => (
            <div
              key={product.id}
              className="bg-white rounded-xl overflow-hidden shadow-sm cursor-pointer"
              onClick={() => router.push(`/shop/product/${product.id}`)}
            >
              <div className="relative aspect-square bg-[#FAF8F5]">
                {product.isNew && (
                  <span className="absolute top-2 left-2 text-xs text-white bg-[#1890FF] px-2 py-0.5 rounded">
                    新品
                  </span>
                )}
                {product.isHot && (
                  <span className="absolute top-2 left-2 text-xs text-white bg-[#C41E3A] px-2 py-0.5 rounded">
                    热销
                  </span>
                )}
              </div>
              <div className="p-3">
                <h4 className="text-sm text-[#2C2C2C] line-clamp-2 min-h-[40px]">
                  {product.name}
                </h4>
                <div className="flex items-center gap-1 mt-1">
                  <Star className="w-3 h-3 text-[#C9A96E] fill-[#C9A96E]" />
                  <span className="text-xs text-[#C9A96E]">{product.rating}</span>
                  <span className="text-xs text-[#999999] ml-1">{product.sales}人付款</span>
                </div>
                <div className="flex items-baseline gap-2 mt-2">
                  <span className="text-[#C41E3A] font-bold">¥{product.price}</span>
                  <span className="text-xs text-[#999999] line-through">¥{product.originalPrice}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 底部安全距离 */}
      <div className="h-4" />
    </div>
  )
}

// apps/mobile/src/pages_backup_20260609/shop/index.vue
<template>
  <view class="shop-page">
    <!-- 骨架屏 -->
    <view v-if="loading" class="skeleton-wrap">
      <view class="sk-bar" />
      <view class="sk-banner" />
      <view class="sk-grid4">
        <view v-for="i in 8" :key="i" class="sk-grid-item">
          <view class="sk-circle" />
          <view class="sk-line w-30" />
        </view>
      </view>
      <view class="sk-banner" />
      <view class="sk-grid2">
        <view v-for="i in 4" :key="i" class="sk-card">
          <view class="sk-img" />
          <view class="sk-line w-80" />
          <view class="sk-line w-40" />
        </view>
      </view>
    </view>

    <view v-else class="shop-content">
      <!-- 顶部搜索栏 -->
      <view class="header-sticky">
        <view class="header-row">
          <view class="search-box" @click="goPage('/pages/search/index?from=shop')">
            <text class="search-icon">🔍</text>
            <text class="search-placeholder">搜索商品</text>
          </view>
          <view class="header-icon" @click="goPage('/pages/shop/cart/index')">
            <text class="hi-icon">🛒</text>
            <text class="hi-badge">3</text>
          </view>
          <view class="header-icon">
            <text class="hi-icon">🔔</text>
            <view class="hi-dot" />
          </view>
        </view>
      </view>

      <!-- Banner轮播 -->
      <view class="banner-wrap">
        <swiper :current="currentBanner" @change="onBannerChange" :interval="4000" circular class="banner-swiper">
          <swiper-item v-for="b in banners" :key="b.id" @click="goPage(b.link)">
            <view class="banner-slide">
              <text class="banner-title">{{ b.title }}</text>
            </view>
          </swiper-item>
        </swiper>
        <view class="banner-indicators">
          <view v-for="(b, idx) in banners" :key="idx" class="bi-dot" :class="{ active: idx === currentBanner }" />
        </view>
      </view>

      <!-- 快捷活动入口 -->
      <view class="quick-actions">
        <view v-for="a in quickActions" :key="a.id" class="qa-item" :class="a.color" @click="goPage(a.link)">
          <text class="qa-icon">{{ a.icon }}</text>
          <text class="qa-name">{{ a.name }}</text>
        </view>
      </view>

      <!-- 分类图标网格 -->
      <view class="cat-grid">
        <view v-for="c in categories" :key="c.id" class="cat-item" @click="goPage('/pages/shop/category/index?id=' + c.id)">
          <view class="cat-icon-wrap">
            <text class="cat-icon">{{ c.icon }}</text>
          </view>
          <text class="cat-name">{{ c.name }}</text>
        </view>
      </view>

      <!-- 秒杀专区 -->
      <view class="flash-section" @click="goPage('/pages/shop/flash-sale/index?id=' + flashSale.id)">
        <view class="flash-header">
          <view class="flash-title-row">
            <text class="flash-fire">🔥</text>
            <text class="flash-title">{{ flashSale.title }}</text>
          </view>
          <view class="flash-countdown">
            <text class="fc-num">{{ pad(countdown.hours) }}</text>
            <text>:</text>
            <text class="fc-num">{{ pad(countdown.minutes) }}</text>
            <text>:</text>
            <text class="fc-num">{{ pad(countdown.seconds) }}</text>
          </view>
        </view>
        <scroll-view scroll-x class="flash-products">
          <view v-for="p in flashSale.products" :key="p.id" class="fp-item" @click.stop="goPage('/pages/shop/product/index?id=' + p.id)">
            <view class="fp-img" />
            <text class="fp-price">¥{{ p.price }}</text>
            <text class="fp-original">¥{{ p.originalPrice }}</text>
          </view>
        </scroll-view>
      </view>

      <!-- 拼团专区 -->
      <view class="group-section" @click="goPage('/pages/shop/group-buy/index?id=' + groupBuy.id)">
        <view class="gs-header">
          <view class="gs-title-row">
            <text class="gs-icon">👥</text>
            <text class="gs-title">拼团特惠</text>
            <text class="gs-badge">{{ groupBuy.title }}</text>
          </view>
          <text class="gs-arrow">›</text>
        </view>
        <view class="gs-body">
          <view class="gs-cover" />
          <view class="gs-info">
            <text class="gs-name">{{ groupBuy.productName }}</text>
            <view class="gs-price-row">
              <text class="gs-price">¥{{ groupBuy.price }}</text>
              <text class="gs-original">¥{{ groupBuy.originalPrice }}</text>
            </view>
            <view class="gs-progress">
              <view class="gsp-bar">
                <view class="gsp-fill" :style="{ width: (groupBuy.currentMembers / groupBuy.minMembers * 100) + '%' }" />
              </view>
              <text class="gsp-text">还差{{ groupBuy.minMembers - groupBuy.currentMembers }}人</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 商品推荐 -->
      <view class="recommend-section">
        <view class="rs-header">
          <text class="rs-title">为你推荐</text>
          <text class="rs-more" @click="goPage('/pages/shop/products/index')">更多 ›</text>
        </view>
        <view class="product-grid">
          <view v-for="p in products" :key="p.id" class="product-card" @click="goPage('/pages/shop/product/index?id=' + p.id)">
            <view class="pc-img">
              <text v-if="p.isNew" class="pc-badge new">新品</text>
              <text v-if="p.isHot" class="pc-badge hot">热销</text>
            </view>
            <view class="pc-info">
              <text class="pc-name">{{ p.name }}</text>
              <view class="pc-stats">
                <text class="pc-rating">⭐ {{ p.rating }}</text>
                <text class="pc-sales">{{ p.sales }}人付款</text>
              </view>
              <view class="pc-price-row">
                <text class="pc-price">¥{{ p.price }}</text>
                <text class="pc-original">¥{{ p.originalPrice }}</text>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const loading = ref(true)
const currentBanner = ref(0)
const countdown = ref({ hours: 2, minutes: 0, seconds: 0 })

const banners = [
  { id: '1', title: '国学典籍大促', link: '/pages/shop/activity/index?id=1' },
  { id: '2', title: '新品上市', link: '/pages/shop/products/index?tag=new' },
  { id: '3', title: '会员专享', link: '/pages/shop/vip/index' },
]

const quickActions = [
  { id: 'flash', name: '限时秒杀', icon: '⚡', color: 'qa-red', link: '/pages/shop/flash-sale/index' },
  { id: 'group', name: '拼团特惠', icon: '👥', color: 'qa-orange', link: '/pages/shop/group-buy/index' },
  { id: 'coupon', name: '领券中心', icon: '🎫', color: 'qa-pink', link: '/pages/shop/coupons/index' },
  { id: 'points', name: '积分兑换', icon: '🎁', color: 'qa-purple', link: '/pages/shop/exchange/index' },
]

const categories = [
  { id: '1', name: '古籍善本', icon: '📚' },
  { id: '2', name: '文房四宝', icon: '🖌️' },
  { id: '3', name: '香道用品', icon: '🪷' },
  { id: '4', name: '茶道器具', icon: '🍵' },
  { id: '5', name: '命理工具', icon: '🧭' },
  { id: '6', name: '风水摆件', icon: '🏺' },
  { id: '7', name: '养生食品', icon: '🌿' },
  { id: '8', name: '更多分类', icon: '📋' },
]

const flashSale = {
  id: '1',
  title: '限时秒杀',
  products: [
    { id: '1', name: '渊海子平精装版', price: 68, originalPrice: 128 },
    { id: '2', name: '罗盘专业款', price: 199, originalPrice: 399 },
    { id: '3', name: '紫檀木签筒', price: 88, originalPrice: 168 },
  ],
}

const groupBuy = {
  id: '1',
  title: '3人成团',
  productName: '周易全集精装套装',
  price: 299,
  originalPrice: 599,
  minMembers: 3,
  currentMembers: 2,
}

const products = [
  { id: '1', name: '渊海子平（精装典藏版）', price: 128, originalPrice: 168, sales: 2860, rating: 4.9, isHot: true, isNew: false },
  { id: '2', name: '专业风水罗盘', price: 399, originalPrice: 599, sales: 1250, rating: 4.8, isHot: false, isNew: true },
  { id: '3', name: '紫檀木文房套装', price: 688, originalPrice: 888, sales: 560, rating: 4.9, isHot: false, isNew: false },
  { id: '4', name: '沉香线香礼盒', price: 168, originalPrice: 238, sales: 3200, rating: 4.7, isHot: true, isNew: false },
  { id: '5', name: '紫砂茶具套装', price: 458, originalPrice: 658, sales: 890, rating: 4.8, isHot: false, isNew: false },
  { id: '6', name: '黄铜貔貅摆件', price: 299, originalPrice: 399, sales: 1560, rating: 4.6, isHot: false, isNew: true },
]

let countdownTimer: ReturnType<typeof setInterval> | null = null

function pad(n: number) { return String(n).padStart(2, '0') }

function onBannerChange(e: any) { currentBanner.value = e.detail.current }

function goPage(url: string) { uni.navigateTo({ url }) }

onMounted(() => {
  setTimeout(() => { loading.value = false }, 600)

  const endTime = Date.now() + 2 * 3600000
  countdownTimer = setInterval(() => {
    const diff = Math.max(0, endTime - Date.now())
    countdown.value = {
      hours: Math.floor(diff / 3600000),
      minutes: Math.floor((diff % 3600000) / 60000),
      seconds: Math.floor((diff % 60000) / 1000),
    }
  }, 1000)
})

onUnmounted(() => {
  if (countdownTimer) clearInterval(countdownTimer)
})
</script>

<style scoped>
.shop-page { min-height: 100vh; background: #FAF8F5; padding-bottom: 40rpx; }

.skeleton-wrap { padding: 0 24rpx; }
.sk-bar { height: 72rpx; background: #fff; border-radius: 36rpx; margin: 14rpx 0; }
.sk-banner { height: 240rpx; border-radius: 20rpx; background: #F0EDE5; margin: 14rpx 0; animation: pulse 1.5s infinite; }
.sk-grid4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16rpx; margin: 16rpx 0; }
.sk-grid-item { display: flex; flex-direction: column; align-items: center; gap: 8rpx; }
.sk-circle { width: 96rpx; height: 96rpx; border-radius: 50%; background: #F0EDE5; }
.sk-line { height: 20rpx; background: #F0EDE5; border-radius: 4rpx; }
.w-30 { width: 60rpx; }
.w-40 { width: 120rpx; }
.w-80 { width: 200rpx; }
.sk-grid2 { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16rpx; margin: 16rpx 0; }
.sk-card { background: #fff; border-radius: 16rpx; padding: 16rpx; }
.sk-img { height: 280rpx; background: #F0EDE5; border-radius: 12rpx; margin-bottom: 12rpx; }
@keyframes pulse { 0%, 100% { opacity: 0.6; } 50% { opacity: 1; } }

.header-sticky { position: sticky; top: 0; z-index: 30; background: #fff; padding: 14rpx 24rpx; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.header-row { display: flex; align-items: center; gap: 16rpx; }
.search-box { flex: 1; display: flex; align-items: center; height: 64rpx; background: #FAF8F5; border-radius: 32rpx; padding: 0 18rpx; }
.search-icon { font-size: 24rpx; margin-right: 6rpx; }
.search-placeholder { font-size: 24rpx; color: #999; }
.header-icon { position: relative; padding: 8rpx; }
.hi-icon { font-size: 36rpx; }
.hi-badge { position: absolute; top: -2rpx; right: -4rpx; min-width: 28rpx; height: 28rpx; background: #C41E3A; color: #fff; font-size: 18rpx; border-radius: 14rpx; display: flex; align-items: center; justify-content: center; }
.hi-dot { position: absolute; top: 2rpx; right: 2rpx; width: 14rpx; height: 14rpx; background: #C41E3A; border-radius: 50%; }

.banner-wrap { margin: 16rpx 24rpx; position: relative; }
.banner-swiper { height: 240rpx; border-radius: 20rpx; overflow: hidden; }
.banner-slide { height: 100%; background: linear-gradient(135deg, #C41E3A, #E85A70); display: flex; align-items: center; justify-content: center; }
.banner-title { font-size: 36rpx; font-weight: 700; color: #fff; }
.banner-indicators { position: absolute; bottom: 16rpx; left: 50%; transform: translateX(-50%); display: flex; gap: 10rpx; }
.bi-dot { width: 10rpx; height: 10rpx; border-radius: 50%; background: rgba(255,255,255,0.5); transition: all 0.3s; }
.bi-dot.active { width: 28rpx; background: #fff; border-radius: 10rpx; }

.quick-actions { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12rpx; padding: 0 24rpx; margin-bottom: 16rpx; }
.qa-item { padding: 18rpx 0; border-radius: 16rpx; display: flex; flex-direction: column; align-items: center; gap: 8rpx; }
.qa-red { background: linear-gradient(135deg, #C41E3A, #F5222D); }
.qa-orange { background: linear-gradient(135deg, #FA8C16, #FFA940); }
.qa-pink { background: linear-gradient(135deg, #EB2F96, #FF85C0); }
.qa-purple { background: linear-gradient(135deg, #722ED1, #B37FEB); }
.qa-icon { font-size: 36rpx; }
.qa-name { font-size: 20rpx; color: #fff; }

.cat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20rpx; padding: 0 24rpx; margin-bottom: 20rpx; }
.cat-item { display: flex; flex-direction: column; align-items: center; gap: 8rpx; }
.cat-icon-wrap { width: 96rpx; height: 96rpx; border-radius: 50%; background: #fff; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); display: flex; align-items: center; justify-content: center; }
.cat-icon { font-size: 40rpx; }
.cat-name { font-size: 20rpx; color: #2C2C2C; }

.flash-section { margin: 0 24rpx 14rpx; background: linear-gradient(135deg, #C41E3A, #E85A70); border-radius: 20rpx; padding: 20rpx; }
.flash-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16rpx; }
.flash-title-row { display: flex; align-items: center; gap: 8rpx; }
.flash-fire { font-size: 28rpx; }
.flash-title { font-size: 28rpx; font-weight: 700; color: #fff; }
.flash-countdown { display: flex; align-items: center; gap: 4rpx; font-size: 22rpx; color: #fff; }
.fc-num { background: rgba(255,255,255,0.2); padding: 2rpx 8rpx; border-radius: 6rpx; font-size: 22rpx; }

.flash-products { display: flex; gap: 12rpx; white-space: nowrap; }
.fp-item { flex-shrink: 0; width: 160rpx; background: #fff; border-radius: 14rpx; padding: 14rpx; text-align: center; }
.fp-img { width: 128rpx; height: 128rpx; background: #FAF8F5; border-radius: 12rpx; margin: 0 auto 8rpx; }
.fp-price { font-size: 24rpx; font-weight: 700; color: #C41E3A; display: block; }
.fp-original { font-size: 18rpx; color: #999; text-decoration: line-through; }

.group-section { margin: 0 24rpx 14rpx; background: #fff; border-radius: 20rpx; padding: 20rpx; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.gs-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16rpx; }
.gs-title-row { display: flex; align-items: center; gap: 8rpx; }
.gs-icon { font-size: 28rpx; color: #C41E3A; }
.gs-title { font-size: 26rpx; font-weight: 700; color: #2C2C2C; }
.gs-badge { font-size: 18rpx; color: #fff; background: #C41E3A; padding: 2rpx 12rpx; border-radius: 20rpx; }
.gs-arrow { font-size: 32rpx; color: #999; }
.gs-body { display: flex; gap: 16rpx; }
.gs-cover { width: 160rpx; height: 160rpx; background: #FAF8F5; border-radius: 14rpx; flex-shrink: 0; }
.gs-info { flex: 1; min-width: 0; }
.gs-name { font-size: 24rpx; font-weight: 500; color: #2C2C2C; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gs-price-row { display: flex; align-items: baseline; gap: 12rpx; margin: 8rpx 0; }
.gs-price { font-size: 36rpx; font-weight: 700; color: #C41E3A; }
.gs-original { font-size: 20rpx; color: #999; text-decoration: line-through; }
.gs-progress { display: flex; align-items: center; gap: 12rpx; }
.gsp-bar { flex: 1; height: 10rpx; background: #FAF8F5; border-radius: 10rpx; overflow: hidden; }
.gsp-fill { height: 100%; background: linear-gradient(90deg, #C41E3A, #E85A70); border-radius: 10rpx; }
.gsp-text { font-size: 20rpx; color: #C41E3A; flex-shrink: 0; }

.recommend-section { padding: 0 24rpx; }
.rs-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14rpx; }
.rs-title { font-size: 30rpx; font-weight: 700; color: #2C2C2C; }
.rs-more { font-size: 22rpx; color: #999; }

.product-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 14rpx; }
.product-card { background: #fff; border-radius: 16rpx; overflow: hidden; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04); }
.pc-img { aspect-ratio: 1; background: #FAF8F5; position: relative; }
.pc-badge { position: absolute; top: 12rpx; left: 12rpx; font-size: 18rpx; color: #fff; padding: 2rpx 12rpx; border-radius: 4rpx; }
.pc-badge.new { background: #1890FF; }
.pc-badge.hot { background: #C41E3A; }
.pc-info { padding: 16rpx; }
.pc-name { font-size: 24rpx; color: #2C2C2C; display: block; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; min-height: 64rpx; }
.pc-stats { display: flex; align-items: center; gap: 8rpx; margin: 8rpx 0; }
.pc-rating { font-size: 20rpx; color: #C9A96E; }
.pc-sales { font-size: 20rpx; color: #999; }
.pc-price-row { display: flex; align-items: baseline; gap: 8rpx; }
.pc-price { font-size: 28rpx; font-weight: 700; color: #C41E3A; }
.pc-original { font-size: 20rpx; color: #999; text-decoration: line-through; }
</style>
