// app/classics/audiobooks/page.tsx
"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Play, Heart, Headphones, Clock } from "lucide-react"
import { cn } from "@/lib/utils"
import { ClassicsHeader, FlatCover, coverColorForBook, type CoverColor } from "@/components/classics"

interface AudioBook {
  id: string
  title: string
  shortTitle: string
  author: string
  duration: string
  narrator: string
  plays: number
  likes: number
  quality: string
  size: string
  desc: string
  color: CoverColor
}

const mockAudioBooks: AudioBook[] = [
  { id: "1", title: "《道德经》完整版朗读", shortTitle: "道德经", author: "王教授", duration: "4小时32分", narrator: "张三", plays: 12850, likes: 1250, quality: "高保真", size: "450MB", desc: "五千言道尽天地至理，名家逐句精讲。", color: "brown" },
  { id: "2", title: "《易经》上下经讲解", shortTitle: "易经", author: "李明星", duration: "6小时15分", narrator: "李四", plays: 9850, likes: 850, quality: "高保真", size: "520MB", desc: "六十四卦层层拆解，听懂群经之首。", color: "cream" },
  { id: "3", title: "《四书五经》核心讲座", shortTitle: "四书五经", author: "孔子研究院", duration: "8小时20分", narrator: "王五", plays: 7420, likes: 620, quality: "高保真", size: "650MB", desc: "儒学经典系统串讲，通识入门首选。", color: "red" },
  { id: "4", title: "《黄帝内经》全文诵读", shortTitle: "黄帝内经", author: "中医学院", duration: "5小时45分", narrator: "赵六", plays: 5840, likes: 480, quality: "标清", size: "380MB", desc: "中医奠基之作，养生智慧娓娓道来。", color: "green" },
]

function fmtPlays(n: number) {
  return n >= 10000 ? `${(n / 10000).toFixed(1)}万` : `${n}`
}

export default function ClassicsAudiobooksPage() {
  const router = useRouter()
  const [favorites, setFavorites] = useState<string[]>([])

  const toggleFavorite = (id: string) =>
    setFavorites((prev) => (prev.includes(id) ? prev.filter((f) => f !== id) : [...prev, id]))

  const [feature, ...rest] = mockAudioBooks

  return (
    <div className="min-h-screen bg-[#f4f2ee] dark:bg-background pb-20 sm:pb-10">
      <ClassicsHeader title="听书" />

      <main className="max-w-screen-xl mx-auto">
        {/* Hero */}
        <section className="px-5 sm:px-6 pt-2 pb-4">
          <p className="text-[13px] font-semibold tracking-wide text-[#c41e3a] dark:text-amber-400 mb-1.5">名家播讲</p>
          <h2 className="text-[34px] leading-[1.1] font-bold tracking-tight text-foreground">轻松听典籍</h2>
        </section>

        {/* 今日主打 - 大卡 */}
        <section className="px-5 sm:px-6 pb-5">
          <button
            onClick={() => router.push(`/classics/audiobooks/${feature.id}`)}
            className="block w-full text-left group"
          >
            <div
              className="relative rounded-[28px] overflow-hidden p-6 shadow-lg ring-1 ring-black/5 active:scale-[0.99] transition-transform"
              style={{ background: "linear-gradient(150deg, #a06a38, #5f3a1a)" }}
            >
              <p className="text-[12px] font-semibold tracking-[0.2em] text-white/70 uppercase">编辑主打</p>
              <div className="mt-4 flex items-center gap-4">
                <FlatCover title={feature.shortTitle} coverColor={coverColorForBook(feature.shortTitle)} className="w-[92px] flex-shrink-0 shadow-xl" titleClassName="text-lg" />
                <div className="flex-1 min-w-0">
                  <p className="text-white font-bold text-xl">{feature.title}</p>
                  <p className="text-white/70 text-[13px] mt-1 line-clamp-2">{feature.desc}</p>
                  <div className="mt-2 flex items-center gap-3 text-white/70 text-[12px]">
                    <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" />{feature.duration}</span>
                    <span className="flex items-center gap-1"><Headphones className="w-3.5 h-3.5" />{fmtPlays(feature.plays)}</span>
                  </div>
                  <span className="mt-3 inline-flex items-center gap-1.5 h-9 px-5 rounded-full bg-white text-[#6f4521] text-[14px] font-semibold shadow-sm">
                    <Play className="w-4 h-4 fill-current" />立即收听
                  </span>
                </div>
              </div>
            </div>
          </button>
        </section>

        {/* 全部有声书 */}
        <section className="px-5 sm:px-6">
          <h3 className="text-[22px] font-bold tracking-tight text-foreground mb-3.5">全部有声书</h3>
          <div className="space-y-3">
            {rest.map((book) => (
              <div key={book.id} className="flex items-center gap-4 p-4 bg-card rounded-2xl shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5">
                <button onClick={() => router.push(`/classics/audiobooks/${book.id}`)} className="flex items-center gap-4 flex-1 min-w-0 text-left active:scale-[0.99] transition-transform">
                  <FlatCover title={book.shortTitle} coverColor={coverColorForBook(book.shortTitle)} className="w-16 flex-shrink-0" titleClassName="text-xs" />
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-[15px] text-foreground line-clamp-1">{book.title}</h3>
                    <p className="text-[12px] text-muted-foreground mt-1 line-clamp-1">{book.desc}</p>
                    <div className="mt-1.5 flex items-center gap-2.5 text-[11px] text-muted-foreground/70">
                      <span className="px-1.5 py-0.5 rounded-md bg-muted">{book.quality}</span>
                      <span className="flex items-center gap-0.5"><Clock className="w-3 h-3" />{book.duration}</span>
                      <span className="flex items-center gap-0.5"><Headphones className="w-3 h-3" />{fmtPlays(book.plays)}</span>
                    </div>
                  </div>
                </button>
                <div className="flex flex-col items-center gap-3 flex-shrink-0">
                  <button onClick={() => toggleFavorite(book.id)} aria-label="收藏" className="active:scale-90 transition-transform">
                    <Heart className={cn("w-5 h-5", favorites.includes(book.id) ? "fill-[#c41e3a] text-[#c41e3a]" : "text-muted-foreground/50")} />
                  </button>
                  <button
                    onClick={() => router.push(`/classics/audiobooks/${book.id}`)}
                    className="w-9 h-9 rounded-full bg-[#c41e3a] dark:bg-amber-500 flex items-center justify-center shadow-sm active:scale-90 transition-transform"
                    aria-label="播放"
                  >
                    <Play className="w-4 h-4 text-white ml-0.5" fill="white" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}

// apps/mobile-backup-20260621_1544/src/pkg-classics/audiobooks/index.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import ClassicsHeader from '@/components/classics/classics-header.vue'
import FlatCover from '@/components/classics/flat-cover.vue'
import { coverColorForBook } from '@/lib/classics-cover'
import { classicsApi, fmtPlays, type AudioBookFull } from '@/lib/classics-data'

const items = ref<AudioBookFull[]>([])
const favorites = ref<string[]>([])

const feature = computed(() => items.value[0])
const rest = computed(() => items.value.slice(1))

onMounted(async () => {
  const res = await classicsApi.audiobooks()
  items.value = res.items
})

function toggleFavorite(id: string) {
  favorites.value = favorites.value.includes(id)
    ? favorites.value.filter((f) => f !== id)
    : [...favorites.value, id]
}

function goPlayer(id: string) {
  uni.navigateTo({ url: `/pkg-classics/audiobooks/player?id=${id}` })
}
</script>

<template>
  <view class="ab-page">
    <classics-header title="听书" />

    <view class="ab-main">
      <!-- Hero -->
      <view class="ab-hero">
        <text class="ab-hero-kicker">
          名家播讲
        </text>
        <text class="ab-hero-title">
          轻松听典籍
        </text>
      </view>

      <!-- 今日主打 - 大卡 -->
      <view class="ab-feature-sec">
        <view
          class="ab-feature"
          @tap="goPlayer(feature.id)"
        >
          <text class="ab-feature-tag">
            编辑主打
          </text>
          <view class="ab-feature-body">
            <FlatCover
              :title="feature.shortTitle"
              :cover-color="coverColorForBook(feature.shortTitle)"
              title-size="36rpx"
              class="ab-feature-cover"
            />
            <view class="ab-feature-info">
              <text class="ab-feature-name">
                {{ feature.title }}
              </text>
              <text class="ab-feature-desc">
                {{ feature.desc }}
              </text>
              <view class="ab-feature-meta">
                <view class="ab-meta-item">
                  <app-icon
                    name="clock"
                    :size="28"
                    color="rgba(255,255,255,0.7)"
                  />
                  <text>{{ feature.duration }}</text>
                </view>
                <view class="ab-meta-item">
                  <app-icon
                    name="headphones"
                    :size="28"
                    color="rgba(255,255,255,0.7)"
                  />
                  <text>{{ fmtPlays(feature.plays) }}</text>
                </view>
              </view>
              <view class="ab-feature-btn">
                <app-icon
                  name="play"
                  :size="32"
                  color="#6f4521"
                  :fill="true"
                />
                <text class="ab-feature-btn-txt">
                  立即收听
                </text>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 全部有声书 -->
      <view class="ab-list-sec">
        <text class="ab-list-title">
          全部有声书
        </text>
        <view class="ab-list">
          <view
            v-for="book in rest"
            :key="book.id"
            class="ab-row"
          >
            <view
              class="ab-row-main"
              @tap="goPlayer(book.id)"
            >
              <FlatCover
                :title="book.shortTitle"
                :cover-color="coverColorForBook(book.shortTitle)"
                title-size="24rpx"
                class="ab-row-cover"
              />
              <view class="ab-row-info">
                <text class="ab-row-title">
                  {{ book.title }}
                </text>
                <text class="ab-row-desc">
                  {{ book.desc }}
                </text>
                <view class="ab-row-meta">
                  <text class="ab-row-quality">
                    {{ book.quality }}
                  </text>
                  <view class="ab-meta-item">
                    <app-icon
                      name="clock"
                      :size="24"
                      color="#999999"
                    />
                    <text>{{ book.duration }}</text>
                  </view>
                  <view class="ab-meta-item">
                    <app-icon
                      name="headphones"
                      :size="24"
                      color="#999999"
                    />
                    <text>{{ fmtPlays(book.plays) }}</text>
                  </view>
                </view>
              </view>
            </view>
            <view class="ab-row-actions">
              <view
                class="ab-fav-btn"
                @tap="toggleFavorite(book.id)"
              >
                <app-icon
                  name="heart"
                  :size="40"
                  :color="favorites.includes(book.id) ? '#c41e3a' : '#cccccc'"
                  :fill="favorites.includes(book.id)"
                />
              </view>
              <view
                class="ab-play-btn"
                @tap="goPlayer(book.id)"
              >
                <app-icon
                  name="play"
                  :size="32"
                  color="#ffffff"
                  :fill="true"
                />
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<style scoped lang="scss">
.ab-page {
  min-height: 100vh;
  background: var(--classics-bg);
  padding-bottom: 160rpx;
}
.ab-main {
  max-width: 100%;
}

/* Hero */
.ab-hero {
  padding: 16rpx 40rpx 32rpx;
}
.ab-hero-kicker {
  display: block;
  font-size: 26rpx;
  font-weight: 600;
  letter-spacing: 1rpx;
  color: #c41e3a;
  margin-bottom: 12rpx;
}
.ab-hero-title {
  display: block;
  font-size: 68rpx;
  line-height: 1.1;
  font-weight: 700;
  letter-spacing: -1rpx;
  color: var(--foreground);
}

/* 今日主打 大卡 */
.ab-feature-sec {
  padding: 0 40rpx 40rpx;
}
.ab-feature {
  position: relative;
  border-radius: 56rpx;
  overflow: hidden;
  padding: 48rpx;
  background: linear-gradient(150deg, #a06a38, #5f3a1a);
  box-shadow: 0 8rpx 24rpx rgba(0, 0, 0, 0.15);
  &:active { transform: scale(0.99); }
}
.ab-feature-tag {
  display: block;
  font-size: 24rpx;
  font-weight: 600;
  letter-spacing: 0.2em;
  color: rgba(255, 255, 255, 0.7);
  text-transform: uppercase;
}
.ab-feature-body {
  margin-top: 32rpx;
  display: flex;
  align-items: center;
  gap: 32rpx;
}
.ab-feature-cover {
  width: 184rpx;
  flex-shrink: 0;
  box-shadow: 0 12rpx 32rpx rgba(0, 0, 0, 0.25);
}
.ab-feature-info {
  flex: 1;
  min-width: 0;
}
.ab-feature-name {
  display: block;
  color: #fff;
  font-weight: 700;
  font-size: 40rpx;
}
.ab-feature-desc {
  display: block;
  color: rgba(255, 255, 255, 0.7);
  font-size: 26rpx;
  margin-top: 8rpx;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.ab-feature-meta {
  margin-top: 16rpx;
  display: flex;
  align-items: center;
  gap: 24rpx;
  font-size: 24rpx;
  color: rgba(255, 255, 255, 0.7);
}
.ab-meta-item {
  display: flex;
  align-items: center;
  gap: 8rpx;
  flex-shrink: 0;
  white-space: nowrap;
}
.ab-feature-btn {
  margin-top: 24rpx;
  display: inline-flex;
  align-items: center;
  gap: 12rpx;
  height: 72rpx;
  padding: 0 40rpx;
  border-radius: 999rpx;
  background: #fff;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.08);
}
.ab-feature-btn-txt {
  color: #6f4521;
  font-size: 28rpx;
  font-weight: 600;
}

/* 全部有声书 */
.ab-list-sec {
  padding: 0 40rpx;
}
.ab-list-title {
  display: block;
  font-size: 44rpx;
  font-weight: 700;
  letter-spacing: -0.5rpx;
  color: var(--foreground);
  margin-bottom: 28rpx;
}
.ab-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.ab-row {
  display: flex;
  align-items: center;
  gap: 32rpx;
  padding: 32rpx;
  background: var(--card);
  border-radius: 32rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
}
.ab-row-main {
  display: flex;
  align-items: center;
  gap: 32rpx;
  flex: 1;
  min-width: 0;
  &:active { transform: scale(0.99); }
}
.ab-row-cover {
  width: 128rpx;
  flex-shrink: 0;
}
.ab-row-info {
  flex: 1;
  min-width: 0;
}
.ab-row-title {
  display: block;
  font-weight: 600;
  font-size: 30rpx;
  color: var(--foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ab-row-desc {
  display: block;
  font-size: 24rpx;
  color: var(--muted-foreground);
  margin-top: 8rpx;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ab-row-meta {
  margin-top: 12rpx;
  display: flex;
  align-items: center;
  flex-wrap: nowrap;
  gap: 20rpx;
  font-size: 22rpx;
  color: var(--muted-foreground);
}
.ab-row-quality {
  flex-shrink: 0;
  white-space: nowrap;
  padding: 4rpx 12rpx;
  border-radius: 12rpx;
  background: var(--muted);
}
.ab-row-actions {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24rpx;
  flex-shrink: 0;
}
.ab-fav-btn {
  &:active { transform: scale(0.9); }
}
.ab-play-btn {
  width: 72rpx;
  height: 72rpx;
  border-radius: 50%;
  background: #c41e3a;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.08);
  &:active { transform: scale(0.9); }
}
</style>
