// apps/mobile/src/pages/activity/landing.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="top-bar">
      <view class="top-bar-inner">
        <text class="back-btn" @click="goBack">‹</text>
        <text class="top-title">{{ activity?.title || '活动详情' }}</text>
        <text class="share-btn" @click="handleShare">📤</text>
      </view>
    </view>

    <!-- Banner -->
    <view class="banner-wrap" v-if="activity?.bannerUrl">
      <image :src="activity.bannerUrl" mode="aspectFill" class="banner-img" />
      <view class="banner-overlay" />
      <view class="banner-text">
        <text class="banner-title">{{ activity.title }}</text>
        <text v-if="activity.subtitle" class="banner-sub">{{ activity.subtitle }}</text>
      </view>
    </view>

    <!-- 倒计时 -->
    <view class="countdown-bar" v-if="countdown">
      <view class="cd-left">
        <text class="cd-icon">🕐</text>
        <text class="cd-label">{{ activity?.status === 'upcoming' ? '距开始' : '距结束' }}</text>
      </view>
      <view class="cd-right" v-if="!countdown.isEnded">
        <text class="cd-box">{{ countdown.hours }}</text>
        <text class="cd-colon">:</text>
        <text class="cd-box">{{ countdown.minutes }}</text>
        <text class="cd-colon">:</text>
        <text class="cd-box">{{ countdown.seconds }}</text>
      </view>
      <text v-else class="cd-ended">{{ activity?.status === 'upcoming' ? '即将开始' : '已结束' }}</text>
    </view>

    <!-- 活动商品 -->
    <view class="section" v-if="activity">
      <view v-if="activity.type === 'flash_sale'" class="section-header">
        <text class="section-icon">⚡</text>
        <text class="section-title">限时秒杀</text>
      </view>
      <view v-else-if="activity.type === 'group_buy'" class="section-header">
        <text class="section-icon">👥</text>
        <text class="section-title">拼团购</text>
      </view>
      <view v-else-if="activity.type === 'promotion'" class="section-header">
        <text class="section-icon">🎁</text>
        <text class="section-title">促销商品</text>
      </view>

      <!-- Flash Sale Items -->
      <view v-if="activity.type === 'flash_sale' && activity.items" class="item-list">
        <view v-for="item in activity.items" :key="item.id" class="item-card">
          <view class="item-row">
            <image :src="item.cover" mode="aspectFill" class="item-cover" />
            <view class="item-info">
              <text class="item-title">{{ item.title }}</text>
              <view class="price-row">
                <text class="sale-price">¥{{ item.salePrice }}</text>
                <text class="orig-price">¥{{ item.originalPrice }}</text>
              </view>
              <view class="progress-row">
                <text class="progress-text">已抢 {{ calcProgress(item) }}%</text>
                <text class="limit-text">限购 {{ item.limitPerUser }} 件</text>
              </view>
              <view class="progress-bar">
                <view class="progress-fill" :style="{ width: calcProgress(item) + '%' }" />
              </view>
            </view>
          </view>
          <view class="item-action">
            <view class="buy-btn" :class="{ disabled: item.status !== 'ongoing' }" @click="buyFlash(item)">
              <text>{{ buyingId === item.id ? '抢购中...' : item.status === 'sold_out' ? '已抢光' : '立即抢购' }}</text>
            </view>
          </view>
        </view>
      </view>

      <!-- Group Buy Items -->
      <view v-if="activity.type === 'group_buy' && activity.items" class="item-list">
        <view v-for="item in activity.items" :key="item.id" class="item-card">
          <view class="item-row">
            <image :src="item.cover" mode="aspectFill" class="item-cover" />
            <view class="item-info">
              <text class="item-title">{{ item.title }}</text>
              <view class="price-row">
                <text class="sale-price">¥{{ item.groupPrice }}</text>
                <text class="orig-price">¥{{ item.originalPrice }}</text>
              </view>
              <text class="group-meta">{{ item.groupSize }}人团 · 已拼{{ item.completedGroups }}件</text>
            </view>
          </view>
          <view v-if="item.ongoingGroups?.length" class="ongoing-groups">
            <text class="og-title">正在拼团：</text>
            <view v-for="g in item.ongoingGroups.slice(0, 2)" :key="g.id" class="og-item">
              <image :src="g.leaderAvatar" mode="aspectFill" class="og-avatar" />
              <text class="og-name">{{ g.leaderName }}</text>
              <text class="og-remain">还差{{ item.groupSize - g.currentSize }}人</text>
              <text class="og-join" @click="joinGroupBuy(g.id)">去拼团</text>
            </view>
          </view>
          <view class="item-action">
            <view class="buy-btn primary" @click="createGroupBuy(item.id)">
              <text>{{ buyingId === item.id ? '开团中...' : '我要开团' }}</text>
            </view>
          </view>
        </view>
      </view>

      <!-- Promotion Items -->
      <view v-if="activity.type === 'promotion' && activity.items" class="promo-grid">
        <view v-for="item in activity.items" :key="item.id" class="promo-card" @click="goProduct(item)">
          <image :src="item.cover" mode="aspectFill" class="promo-cover" />
          <view class="promo-badge">{{ item.discountLabel }}</view>
          <view class="promo-info">
            <text class="promo-title">{{ item.title }}</text>
            <view class="promo-price-row">
              <text class="promo-price">¥{{ item.promotionPrice }}</text>
              <text class="promo-orig">¥{{ item.originalPrice }}</text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 活动规则 -->
    <view class="rules-section" v-if="activity?.rules?.length">
      <view class="rules-header" @click="showRules = !showRules">
        <text class="rules-title">活动规则</text>
        <text class="rules-arrow">{{ showRules ? '▲' : '▼' }}</text>
      </view>
      <view v-if="showRules" class="rules-body">
        <text v-for="(r, i) in activity.rules" :key="i" class="rule-item">{{ i + 1 }}. {{ r }}</text>
      </view>
    </view>

    <!-- Loading -->
    <view v-if="loading" class="loading-wrap">
      <text class="loading-text">加载中...</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { marketingApi, shopApi } from '../../api'

interface ActivityItem {
  id: number
  title: string
  cover: string
  salePrice?: number
  originalPrice?: number
  groupPrice?: number
  limitPerUser?: number
  status?: string
  soldCount?: number
  totalStock?: number
  completedGroups?: number
  groupSize?: number
  ongoingGroups?: Array<{ id: number; leaderName: string; leaderAvatar: string; currentSize: number }>
  promotionPrice?: number
  discountLabel?: string
  productId?: number
  tags?: string[]
}

interface ActivityDetail {
  title: string
  subtitle?: string
  bannerUrl?: string
  type: string
  status: string
  startTime: string
  endTime: string
  items?: ActivityItem[]
  rules?: string[]
  shareTitle?: string
}

const loading = ref(true)
const activity = ref<ActivityDetail | null>(null)
const buyingId = ref<number | null>(null)
const showRules = ref(false)
const countdown = ref<{ hours: string; minutes: string; seconds: string; isEnded: boolean } | null>(null)
let countdownTimer: number | null = null

onMounted(() => {
  loadActivity()
})

onUnmounted(() => {
  if (countdownTimer) clearInterval(countdownTimer)
})

async function loadActivity() {
  loading.value = true
  try {
    const pages = getCurrentPages()
    const page = pages[pages.length - 1] as any
    const route = page?.$page?.options?.route || page?.options?.route || 'flash-sale'
    const res = await marketingApi.pageByRoute(route)
    if (res) {
      activity.value = res as any || res.data
      startCountdown()
    }
  } catch { /* ignore */ }
  loading.value = false
}

function startCountdown() {
  if (!activity.value) return
  const target = activity.value.status === 'upcoming' ? activity.value.startTime : activity.value.endTime
  if (!target) return
  const update = () => {
    const diff = new Date(target).getTime() - Date.now()
    if (diff <= 0) {
      countdown.value = { hours: '00', minutes: '00', seconds: '00', isEnded: true }
      if (countdownTimer) clearInterval(countdownTimer)
      return
    }
    const h = Math.floor(diff / 3600000)
    const m = Math.floor((diff % 3600000) / 60000)
    const s = Math.floor((diff % 60000) / 1000)
    countdown.value = {
      hours: String(h).padStart(2, '0'),
      minutes: String(m).padStart(2, '0'),
      seconds: String(s).padStart(2, '0'),
      isEnded: false,
    }
  }
  update()
  countdownTimer = setInterval(update, 1000) as any
}

function calcProgress(item: any): number {
  if (!item.totalStock) return 0
  return Math.round((item.soldCount / item.totalStock) * 100)
}

async function buyFlash(item: ActivityItem) {
  if (item.status !== 'ongoing') return
  buyingId.value = item.id
  try {
    const res = await marketingApi.flashSaleDetail(String(item.id))
    if (res) {
      uni.showToast({ title: '抢购成功' })
    }
  } catch { uni.showToast({ title: '抢购失败', icon: 'none' }) }
  buyingId.value = null
}

async function createGroupBuy(itemId: number) {
  buyingId.value = itemId
  try {
    const res = await marketingApi.createGroupBuy ? await marketingApi.createGroupBuy(itemId) : null
    if (res) {
      uni.showToast({ title: '开团成功' })
    }
  } catch { uni.showToast({ title: '开团失败', icon: 'none' }) }
  buyingId.value = null
}

async function joinGroupBuy(groupId: number) {
  buyingId.value = groupId
  try {
    const res = await marketingApi.joinGroupBuy ? await marketingApi.joinGroupBuy(groupId) : null
    if (res) {
      uni.showToast({ title: '参团成功' })
    }
  } catch { uni.showToast({ title: '参团失败', icon: 'none' }) }
  buyingId.value = null
}

function goProduct(item: ActivityItem) {
  uni.navigateTo({ url: `/pages/shop/product-detail?id=${item.productId || item.id}` })
}

function handleShare() {
  uni.showShareMenu({ withShareTicket: true })
}

function goBack() { uni.navigateBack() }
</script>

<style scoped>
.page { background: #F5F0E8; min-height: 100vh; padding-bottom: 40rpx; }
.top-bar { position: sticky; top: 0; z-index: 50; background: rgba(245, 240, 232, 0.95); backdrop-filter: blur(10px); border-bottom: 1rpx solid #E5E1DB; }
.top-bar-inner { display: flex; align-items: center; justify-content: space-between; padding: 20rpx 24rpx; }
.back-btn { font-size: 40rpx; color: #2C2C2C; font-weight: bold; width: 60rpx; }
.top-title { font-size: 30rpx; font-weight: 500; color: #2C2C2C; }
.share-btn { font-size: 36rpx; width: 60rpx; text-align: right; }

.banner-wrap { position: relative; width: 100%; height: 360rpx; overflow: hidden; }
.banner-img { width: 100%; height: 100%; }
.banner-overlay { position: absolute; inset: 0; background: linear-gradient(0deg, rgba(0,0,0,0.6), transparent); }
.banner-text { position: absolute; bottom: 24rpx; left: 24rpx; right: 24rpx; }
.banner-title { font-size: 36rpx; font-weight: bold; color: #fff; display: block; }
.banner-sub { font-size: 24rpx; color: rgba(255,255,255,0.8); margin-top: 8rpx; display: block; }

.countdown-bar { display: flex; align-items: center; justify-content: space-between; padding: 16rpx 24rpx; background: #fef0f0; }
.cd-left { display: flex; align-items: center; gap: 8rpx; }
.cd-icon { font-size: 28rpx; }
.cd-label { font-size: 24rpx; color: #666; }
.cd-right { display: flex; align-items: center; gap: 6rpx; }
.cd-box { background: #C41E3A; color: #fff; font-size: 28rpx; font-weight: bold; padding: 4rpx 12rpx; border-radius: 6rpx; min-width: 48rpx; text-align: center; }
.cd-colon { font-size: 24rpx; color: #C41E3A; font-weight: bold; }
.cd-ended { font-size: 24rpx; color: #999; }

.section { margin: 16rpx 24rpx; background: #fff; border-radius: 16rpx; padding: 24rpx; }
.section-header { display: flex; align-items: center; gap: 8rpx; margin-bottom: 20rpx; }
.section-icon { font-size: 32rpx; }
.section-title { font-size: 28rpx; font-weight: 600; color: #2C2C2C; }

.item-list { display: flex; flex-direction: column; gap: 16rpx; }
.item-card { border: 1rpx solid #E5E1DB; border-radius: 12rpx; padding: 16rpx; }
.item-row { display: flex; gap: 16rpx; }
.item-cover { width: 160rpx; height: 160rpx; border-radius: 12rpx; flex-shrink: 0; }
.item-info { flex: 1; min-width: 0; }
.item-title { font-size: 26rpx; font-weight: 500; color: #2C2C2C; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.price-row { display: flex; align-items: baseline; gap: 12rpx; margin-top: 8rpx; }
.sale-price { font-size: 32rpx; font-weight: bold; color: #C41E3A; }
.orig-price { font-size: 22rpx; color: #999; text-decoration: line-through; }
.progress-row { display: flex; justify-content: space-between; margin-top: 10rpx; }
.progress-text, .limit-text { font-size: 20rpx; color: #999; }
.progress-bar { height: 12rpx; background: #f0f0f0; border-radius: 6rpx; margin-top: 6rpx; overflow: hidden; }
.progress-fill { height: 100%; background: linear-gradient(90deg, #C41E3A, #e8505a); border-radius: 6rpx; }
.group-meta { font-size: 22rpx; color: #999; margin-top: 6rpx; display: block; }
.item-action { margin-top: 12rpx; display: flex; justify-content: flex-end; }
.buy-btn { background: #C41E3A; color: #fff; padding: 10rpx 36rpx; border-radius: 28rpx; font-size: 24rpx; }
.buy-btn.disabled { background: #ccc; }
.buy-btn.primary { width: 100%; text-align: center; }

.ongoing-groups { border-top: 1rpx solid #E5E1DB; padding-top: 12rpx; margin-top: 12rpx; }
.og-title { font-size: 22rpx; color: #999; display: block; margin-bottom: 8rpx; }
.og-item { display: flex; align-items: center; gap: 8rpx; margin-bottom: 8rpx; }
.og-avatar { width: 40rpx; height: 40rpx; border-radius: 50%; }
.og-name { font-size: 24rpx; color: #2C2C2C; flex: 1; }
.og-remain { font-size: 22rpx; color: #999; }
.og-join { font-size: 22rpx; color: #C41E3A; padding: 4rpx 16rpx; border: 1rpx solid #C41E3A; border-radius: 20rpx; }

.promo-grid { display: flex; flex-wrap: wrap; gap: 16rpx; }
.promo-card { width: calc(50% - 8rpx); border: 1rpx solid #E5E1DB; border-radius: 12rpx; overflow: hidden; }
.promo-cover { width: 100%; height: 240rpx; }
.promo-badge { position: absolute; top: 8rpx; left: 8rpx; background: #C41E3A; color: #fff; font-size: 20rpx; padding: 2rpx 12rpx; border-radius: 16rpx; }
.promo-info { padding: 12rpx; }
.promo-title { font-size: 24rpx; color: #2C2C2C; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block; }
.promo-price-row { display: flex; align-items: baseline; gap: 8rpx; margin-top: 4rpx; }
.promo-price { font-size: 28rpx; font-weight: bold; color: #C41E3A; }
.promo-orig { font-size: 20rpx; color: #999; text-decoration: line-through; }

.rules-section { margin: 0 24rpx; background: #fff; border-radius: 16rpx; overflow: hidden; }
.rules-header { display: flex; align-items: center; justify-content: space-between; padding: 20rpx 24rpx; background: #fafafa; }
.rules-title { font-size: 26rpx; font-weight: 500; color: #2C2C2C; }
.rules-arrow { font-size: 24rpx; color: #999; }
.rules-body { padding: 16rpx 24rpx; }
.rule-item { display: block; font-size: 24rpx; color: #666; line-height: 1.8; }

.loading-wrap { display: flex; align-items: center; justify-content: center; padding: 100rpx 0; }
.loading-text { font-size: 28rpx; color: #999; }
</style>

// v0-reference/proto-ref-app/activity/landing/page.tsx
'use client'

import { useState, useEffect, useCallback, Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Share2, Clock, ChevronDown, ChevronUp, Users, Zap, Tag, Gift } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import { DataState, LoadingSkeleton } from '@/components/data-state'
import { 
  getActivityByRoute, 
  calculateCountdown, 
  getActivityStatusText,
  calculateSaleProgress,
  flashSaleBuy,
  createGroupBuy,
  joinGroupBuy
} from '@/lib/api/marketing'
import type { 
  ActivityDetail, 
  FlashSaleActivity, 
  GroupBuyActivity, 
  PromotionActivity,
  Countdown 
} from '@/lib/types/marketing'

export default function ActivityLandingPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><LoadingSkeleton /></div>}>
      <ActivityLandingContent />
    </Suspense>
  )
}

function ActivityLandingContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const route = searchParams.get('route') || 'flash-sale'

  const [activity, setActivity] = useState<ActivityDetail | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [countdown, setCountdown] = useState<Countdown | null>(null)
  const [showRules, setShowRules] = useState(false)
  const [buyingId, setBuyingId] = useState<number | null>(null)

  // 获取活动数据
  useEffect(() => {
    async function fetchActivity() {
      setLoading(true)
      setError(null)
      try {
        const response = await getActivityByRoute(route)
        if (response.code === 200 && response.data) {
          setActivity(response.data)
        } else {
          setError(response.message || '获取活动失败')
        }
      } catch {
        setError('网络错误，请重试')
      } finally {
        setLoading(false)
      }
    }
    fetchActivity()
  }, [route])

  // 倒计时
  useEffect(() => {
    if (!activity) return

    const targetTime = activity.status === 'upcoming' ? activity.startTime : activity.endTime

    const updateCountdown = () => {
      setCountdown(calculateCountdown(targetTime))
    }

    updateCountdown()
    const timer = setInterval(updateCountdown, 1000)

    return () => clearInterval(timer)
  }, [activity])

  // 倒计时归零刷新
  useEffect(() => {
    if (countdown?.isEnded && activity) {
      // 刷新活动状态
      setTimeout(() => {
        window.location.reload()
      }, 1000)
    }
  }, [countdown?.isEnded, activity])

  // 秒杀抢购
  const handleFlashSaleBuy = useCallback(async (itemId: number) => {
    setBuyingId(itemId)
    try {
      const response = await flashSaleBuy(itemId)
      if (response.code === 200) {
        toast.success('抢购成功！')
        router.push(`/orders/${response.data.orderId}`)
      } else {
        toast.error(response.message || '抢购失败')
      }
    } catch {
      toast.error('网络错误，请重试')
    } finally {
      setBuyingId(null)
    }
  }, [router])

  // 发起拼团
  const handleCreateGroup = useCallback(async (itemId: number) => {
    setBuyingId(itemId)
    try {
      const response = await createGroupBuy(itemId)
      if (response.code === 200) {
        toast.success('开团成功！')
        router.push(`/orders/${response.data.orderId}`)
      } else {
        toast.error(response.message || '开团失败')
      }
    } catch {
      toast.error('网络错误，请重试')
    } finally {
      setBuyingId(null)
    }
  }, [router])

  // 参与拼团
  const handleJoinGroup = useCallback(async (groupId: number) => {
    setBuyingId(groupId)
    try {
      const response = await joinGroupBuy(groupId)
      if (response.code === 200) {
        toast.success('参团成功！')
        router.push(`/orders/${response.data.orderId}`)
      } else {
        toast.error(response.message || '参团失败')
      }
    } catch {
      toast.error('网络错误，请重试')
    } finally {
      setBuyingId(null)
    }
  }, [router])

  // 分享
  const handleShare = () => {
    if (navigator.share && activity) {
      navigator.share({
        title: activity.shareTitle || activity.title,
        url: window.location.href,
      })
    } else {
      navigator.clipboard.writeText(window.location.href)
      toast.success('链接已复制')
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur border-b border-border">
        <div className="flex items-center justify-between px-4 h-14">
          <Button variant="ghost" size="icon" onClick={() => router.back()}>
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <h1 className="font-medium">活动详情</h1>
          <Button variant="ghost" size="icon" onClick={handleShare}>
            <Share2 className="w-5 h-5" />
          </Button>
        </div>
      </header>

      <DataState
        isLoading={loading}
        error={error}
        isEmpty={!activity}
        emptyMessage="活动不存在"
        onRetry={() => window.location.reload()}
      >
        {activity && (
          <main className="pb-20">
            {/* Banner */}
            <div className="relative aspect-[2/1] bg-secondary">
              <img
                src={activity.bannerUrl}
                alt={activity.title}
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
              <div className="absolute bottom-4 left-4 right-4 text-white">
                <h2 className="text-xl font-bold">{activity.title}</h2>
                {activity.subtitle && (
                  <p className="text-sm opacity-90 mt-1">{activity.subtitle}</p>
                )}
              </div>
            </div>

            {/* 倒计时模块 */}
            {countdown && (
              <div className="bg-primary/10 px-4 py-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4 text-primary" />
                    <span className="text-sm text-muted-foreground">
                      {activity.status === 'upcoming' ? '距开始' : '距结束'}
                    </span>
                  </div>
                  {countdown.isEnded ? (
                    <Badge variant="secondary">活动{activity.status === 'upcoming' ? '即将开始' : '已结束'}</Badge>
                  ) : (
                    <div className="flex items-center gap-1">
                      {countdown.days > 0 && (
                        <>
                          <CountdownBox value={countdown.days} />
                          <span className="text-xs text-muted-foreground">天</span>
                        </>
                      )}
                      <CountdownBox value={countdown.hours} />
                      <span className="text-muted-foreground">:</span>
                      <CountdownBox value={countdown.minutes} />
                      <span className="text-muted-foreground">:</span>
                      <CountdownBox value={countdown.seconds} />
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* 活动商品区 */}
            <div className="p-4 space-y-4">
              {activity.type === 'flash_sale' && (
                <FlashSaleSection 
                  activity={activity as FlashSaleActivity} 
                  onBuy={handleFlashSaleBuy}
                  buyingId={buyingId}
                />
              )}
              {activity.type === 'group_buy' && (
                <GroupBuySection 
                  activity={activity as GroupBuyActivity} 
                  onCreate={handleCreateGroup}
                  onJoin={handleJoinGroup}
                  buyingId={buyingId}
                />
              )}
              {activity.type === 'promotion' && (
                <PromotionSection activity={activity as PromotionActivity} />
              )}
            </div>

            {/* 活动规则 */}
            <div className="mx-4 border border-border rounded-lg overflow-hidden">
              <button
                onClick={() => setShowRules(!showRules)}
                className="w-full flex items-center justify-between p-4 bg-secondary/30"
              >
                <span className="font-medium">活动规则</span>
                {showRules ? (
                  <ChevronUp className="w-4 h-4 text-muted-foreground" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-muted-foreground" />
                )}
              </button>
              {showRules && (
                <div className="p-4 space-y-2">
                  {activity.rules.map((rule, index) => (
                    <p key={index} className="text-sm text-muted-foreground flex gap-2">
                      <span className="text-primary">{index + 1}.</span>
                      <span>{rule}</span>
                    </p>
                  ))}
                </div>
              )}
            </div>
          </main>
        )}
      </DataState>
    </div>
  )
}

// 倒计时数字框
function CountdownBox({ value }: { value: number }) {
  return (
    <span className="bg-primary text-primary-foreground text-sm font-mono font-bold px-2 py-1 rounded min-w-[32px] text-center">
      {String(value).padStart(2, '0')}
    </span>
  )
}

// 秒杀商品区
function FlashSaleSection({ 
  activity, 
  onBuy, 
  buyingId 
}: { 
  activity: FlashSaleActivity
  onBuy: (itemId: number) => void
  buyingId: number | null
}) {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Zap className="w-5 h-5 text-primary" />
        <span className="font-medium">限时秒杀</span>
      </div>
      {activity.items.map(item => {
        const progress = calculateSaleProgress(item.soldCount, item.totalStock)
        const isSoldOut = item.status === 'sold_out'
        const isEnded = item.status === 'ended'
        const canBuy = item.status === 'ongoing'

        return (
          <Link
            key={item.id}
            href={`/courses/${item.productId}`}
            className="block bg-card border border-border rounded-lg p-3"
          >
            <div className="flex gap-3">
              <img
                src={item.cover}
                alt={item.title}
                className="w-20 h-20 rounded-lg object-cover shrink-0"
              />
              <div className="flex-1 min-w-0">
                <h3 className="font-medium line-clamp-2">{item.title}</h3>
                <div className="flex items-baseline gap-2 mt-2">
                  <span className="text-lg font-bold text-primary">
                    ¥{item.salePrice}
                  </span>
                  <span className="text-sm text-muted-foreground line-through">
                    ¥{item.originalPrice}
                  </span>
                </div>
                <div className="mt-2">
                  <div className="flex items-center justify-between text-xs text-muted-foreground mb-1">
                    <span>已抢 {progress}%</span>
                    <span>限购 {item.limitPerUser} 件</span>
                  </div>
                  <Progress value={progress} className="h-2" />
                </div>
              </div>
            </div>
            <div className="mt-3 flex justify-end">
              <Button
                size="sm"
                disabled={!canBuy || buyingId === item.id}
                onClick={(e) => {
                  e.preventDefault()
                  if (canBuy) onBuy(item.id)
                }}
                className={cn(
                  isSoldOut && 'bg-muted text-muted-foreground',
                  isEnded && 'bg-muted text-muted-foreground'
                )}
              >
                {buyingId === item.id ? '抢购中...' :
                  isSoldOut ? '已抢光' :
                  isEnded ? '已结束' : '立即抢购'}
              </Button>
            </div>
          </Link>
        )
      })}
    </div>
  )
}

// 拼团商品区
function GroupBuySection({ 
  activity, 
  onCreate,
  onJoin,
  buyingId 
}: { 
  activity: GroupBuyActivity
  onCreate: (itemId: number) => void
  onJoin: (groupId: number) => void
  buyingId: number | null
}) {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Users className="w-5 h-5 text-primary" />
        <span className="font-medium">拼团购</span>
      </div>
      {activity.items.map(item => (
        <div key={item.id} className="bg-card border border-border rounded-lg p-3 space-y-3">
          <Link href={`/courses/${item.productId}`} className="flex gap-3">
            <img
              src={item.cover}
              alt={item.title}
              className="w-20 h-20 rounded-lg object-cover shrink-0"
            />
            <div className="flex-1 min-w-0">
              <h3 className="font-medium line-clamp-2">{item.title}</h3>
              <div className="flex items-baseline gap-2 mt-2">
                <span className="text-lg font-bold text-primary">
                  ¥{item.groupPrice}
                </span>
                <span className="text-sm text-muted-foreground line-through">
                  ¥{item.originalPrice}
                </span>
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                {item.groupSize}人团 · 已拼{item.completedGroups}件
              </p>
            </div>
          </Link>

          {/* 正在拼团 */}
          {item.ongoingGroups.length > 0 && (
            <div className="border-t border-border pt-3 space-y-2">
              <p className="text-xs text-muted-foreground">正在拼团：</p>
              {item.ongoingGroups.slice(0, 2).map(group => (
                <div key={group.id} className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      src={group.leaderAvatar}
                      alt={group.leaderName}
                      className="w-6 h-6 rounded-full"
                    />
                    <span className="text-sm">{group.leaderName}</span>
                    <span className="text-xs text-muted-foreground">
                      还差{item.groupSize - group.currentSize}人
                    </span>
                  </div>
                  <Button
                    size="sm"
                    variant="outline"
                    disabled={buyingId === group.id}
                    onClick={() => onJoin(group.id)}
                  >
                    {buyingId === group.id ? '参团中...' : '去拼团'}
                  </Button>
                </div>
              ))}
            </div>
          )}

          <Button
            className="w-full"
            disabled={buyingId === item.id}
            onClick={() => onCreate(item.id)}
          >
            {buyingId === item.id ? '开团中...' : '我要开团'}
          </Button>
        </div>
      ))}
    </div>
  )
}

// 促销商品区
function PromotionSection({ activity }: { activity: PromotionActivity }) {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Gift className="w-5 h-5 text-primary" />
        <span className="font-medium">促销商品</span>
      </div>
      <div className="grid grid-cols-2 gap-3">
        {activity.items.map(item => (
          <Link
            key={item.id}
            href={`/courses/${item.productId}`}
            className="bg-card border border-border rounded-lg overflow-hidden"
          >
            <div className="relative aspect-square">
              <img
                src={item.cover}
                alt={item.title}
                className="w-full h-full object-cover"
              />
              <Badge className="absolute top-2 left-2 bg-primary">
                {item.discountLabel}
              </Badge>
            </div>
            <div className="p-3">
              <h3 className="text-sm font-medium line-clamp-2">{item.title}</h3>
              <div className="flex items-baseline gap-2 mt-2">
                <span className="text-primary font-bold">
                  ¥{item.promotionPrice}
                </span>
                <span className="text-xs text-muted-foreground line-through">
                  ¥{item.originalPrice}
                </span>
              </div>
              {item.tags && item.tags.length > 0 && (
                <div className="flex gap-1 mt-2">
                  {item.tags.map(tag => (
                    <Badge key={tag} variant="secondary" className="text-xs">
                      {tag}
                    </Badge>
                  ))}
                </div>
              )}
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}
