// proto-ref-app/im/invite/page.tsx
'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { 
  ArrowLeft, 
  Copy, 
  Check, 
  Download, 
  Share2, 
  QrCode, 
  Link2, 
  Image as ImageIcon,
  Loader2,
  ChevronRight,
  Gift
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { toast } from 'sonner'
import { DataState } from '@/components/data-state'
import { 
  getInviteLinkInfo, 
  getInvitePosterConfig, 
  recordShare 
} from '@/lib/api/invite'
import type { InviteLinkInfo, InvitePosterConfig, ShareChannel } from '@/lib/types/invite'

type TabType = 'link' | 'qrcode' | 'poster'

export default function InvitePage() {
  const router = useRouter()
  const canvasRef = useRef<HTMLCanvasElement>(null)
  
  const [activeTab, setActiveTab] = useState<TabType>('link')
  const [linkInfo, setLinkInfo] = useState<InviteLinkInfo | null>(null)
  const [posterConfig, setPosterConfig] = useState<InvitePosterConfig | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [selectedBg, setSelectedBg] = useState(0)
  const [posterGenerated, setPosterGenerated] = useState(false)
  const [generatingPoster, setGeneratingPoster] = useState(false)

  // 加载数据
  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true)
        const [linkRes, posterRes] = await Promise.all([
          getInviteLinkInfo(),
          getInvitePosterConfig(),
        ])
        if (linkRes.code === 200) {
          setLinkInfo(linkRes.data)
        }
        if (posterRes.code === 200) {
          setPosterConfig(posterRes.data)
        }
      } catch (err) {
        setError('加载失败')
      } finally {
        setLoading(false)
      }
    }
    loadData()
  }, [])

  // 复制链接
  const handleCopyLink = useCallback(async () => {
    if (!linkInfo) return
    try {
      await navigator.clipboard.writeText(linkInfo.inviteLink)
      setCopied(true)
      toast.success('链接已复制')
      recordShare('copy', 'invite')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast.error('复制失败')
    }
  }, [linkInfo])

  // 复制邀请码
  const handleCopyCode = useCallback(async () => {
    if (!linkInfo) return
    try {
      await navigator.clipboard.writeText(linkInfo.inviteCode)
      toast.success('邀请码已复制')
    } catch {
      toast.error('复制失败')
    }
  }, [linkInfo])

  // 生成海报
  const generatePoster = useCallback(async () => {
    if (!canvasRef.current || !posterConfig) return
    
    setGeneratingPoster(true)
    const canvas = canvasRef.current
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    // Canvas尺寸
    canvas.width = 400
    canvas.height = 600

    try {
      // 绘制背景
      const bgImg = new Image()
      bgImg.crossOrigin = 'anonymous'
      bgImg.src = posterConfig.backgroundImages[selectedBg]
      
      await new Promise((resolve, reject) => {
        bgImg.onload = resolve
        bgImg.onerror = reject
      })
      
      ctx.drawImage(bgImg, 0, 0, 400, 600)

      // 绘制半透明遮罩
      ctx.fillStyle = 'rgba(0, 0, 0, 0.3)'
      ctx.fillRect(0, 0, 400, 600)

      // 绘制用户头像（圆形）
      const avatarImg = new Image()
      avatarImg.crossOrigin = 'anonymous'
      avatarImg.src = posterConfig.userAvatar
      
      await new Promise((resolve, reject) => {
        avatarImg.onload = resolve
        avatarImg.onerror = reject
      })

      ctx.save()
      ctx.beginPath()
      ctx.arc(200, 100, 40, 0, Math.PI * 2)
      ctx.closePath()
      ctx.clip()
      ctx.drawImage(avatarImg, 160, 60, 80, 80)
      ctx.restore()

      // 绘制用户名
      ctx.fillStyle = '#FFFFFF'
      ctx.font = 'bold 18px sans-serif'
      ctx.textAlign = 'center'
      ctx.fillText(posterConfig.userName, 200, 170)

      // 绘制标题
      ctx.font = 'bold 24px sans-serif'
      ctx.fillText(posterConfig.title, 200, 220)

      // 绘制副标题
      ctx.font = '14px sans-serif'
      ctx.fillStyle = 'rgba(255, 255, 255, 0.8)'
      ctx.fillText(posterConfig.subtitle, 200, 250)

      // 绘制权益列表
      ctx.textAlign = 'left'
      ctx.font = '14px sans-serif'
      posterConfig.benefits.forEach((benefit, index) => {
        ctx.fillText(`• ${benefit}`, 60, 300 + index * 28)
      })

      // 绘制二维码区域背景
      ctx.fillStyle = '#FFFFFF'
      roundRect(ctx, 130, 420, 140, 160, 8)
      ctx.fill()

      // 绘制二维码
      const qrImg = new Image()
      qrImg.crossOrigin = 'anonymous'
      qrImg.src = posterConfig.qrCodeUrl
      
      await new Promise((resolve, reject) => {
        qrImg.onload = resolve
        qrImg.onerror = reject
      })
      
      ctx.drawImage(qrImg, 140, 430, 120, 120)

      // 绘制扫码提示
      ctx.fillStyle = '#666666'
      ctx.font = '12px sans-serif'
      ctx.textAlign = 'center'
      ctx.fillText('扫码加入', 200, 565)

      // 绘制邀请码
      ctx.fillStyle = '#C41E3A'
      ctx.font = 'bold 12px sans-serif'
      ctx.fillText(`邀请码: ${posterConfig.inviteCode}`, 200, 580)

      setPosterGenerated(true)
    } catch (err) {
      toast.error('海报生成失败')
    } finally {
      setGeneratingPoster(false)
    }
  }, [posterConfig, selectedBg])

  // 绘制圆角矩形
  function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
    ctx.beginPath()
    ctx.moveTo(x + r, y)
    ctx.arcTo(x + w, y, x + w, y + h, r)
    ctx.arcTo(x + w, y + h, x, y + h, r)
    ctx.arcTo(x, y + h, x, y, r)
    ctx.arcTo(x, y, x + w, y, r)
    ctx.closePath()
  }

  // 保存海报
  const handleSavePoster = useCallback(() => {
    if (!canvasRef.current) return
    
    const link = document.createElement('a')
    link.download = `invite_poster_${Date.now()}.png`
    link.href = canvasRef.current.toDataURL('image/png')
    link.click()
    
    toast.success('海报已保存')
    recordShare('save', 'poster')
  }, [])

  // 分享到渠道
  const handleShare = useCallback((channel: ShareChannel) => {
    recordShare(channel, 'invite')
    
    const messages: Record<ShareChannel, string> = {
      wechat: '请在微信中打开分享',
      moments: '请在微信朋友圈中打开分享',
      qq: '请在QQ中打开分享',
      weibo: '请在微博中打开分享',
      copy: '链接已复制',
    }
    
    if (channel === 'copy') {
      handleCopyLink()
    } else {
      toast.info(messages[channel])
    }
  }, [handleCopyLink])

  // 当切换到海报Tab时自动生成
  useEffect(() => {
    if (activeTab === 'poster' && posterConfig && !posterGenerated) {
      generatePoster()
    }
  }, [activeTab, posterConfig, posterGenerated, generatePoster])

  // 当切换背景时重新生成
  useEffect(() => {
    if (activeTab === 'poster' && posterConfig && posterGenerated) {
      generatePoster()
    }
  }, [selectedBg])

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-10 bg-gradient-to-r from-primary to-primary/80 text-primary-foreground">
        <div className="flex items-center justify-between px-4 h-14">
          <Button 
            variant="ghost" 
            size="icon" 
            onClick={() => router.back()}
            className="text-primary-foreground hover:bg-primary-foreground/10"
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <h1 className="text-lg font-semibold">邀请好友</h1>
          <div className="w-10" />
        </div>
      </header>

      <DataState
        loading={loading}
        error={error}
        empty={!linkInfo}
        emptyMessage="暂无邀请信息"
        onRetry={() => window.location.reload()}
      >
        <div className="p-4 space-y-4">
          {/* 邀请奖励说明 */}
          <div className="bg-gradient-to-r from-amber-50 to-orange-50 dark:from-amber-950/30 dark:to-orange-950/30 rounded-xl p-4 border border-amber-200/50 dark:border-amber-800/50">
            <div className="flex items-center gap-2 mb-2">
              <Gift className="w-5 h-5 text-amber-600" />
              <span className="font-semibold text-amber-800 dark:text-amber-200">邀请奖励</span>
            </div>
            <ul className="text-sm text-amber-700 dark:text-amber-300 space-y-1">
              <li>• 好友注册即得 <span className="font-semibold">10积分</span></li>
              <li>• 好友首次付费返佣 <span className="font-semibold">10%</span></li>
              <li>• 好友开通会员再得 <span className="font-semibold">20元</span></li>
            </ul>
          </div>

          {/* Tab切换 */}
          <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as TabType)}>
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="link" className="gap-1.5">
                <Link2 className="w-4 h-4" />
                推荐链接
              </TabsTrigger>
              <TabsTrigger value="qrcode" className="gap-1.5">
                <QrCode className="w-4 h-4" />
                二维码
              </TabsTrigger>
              <TabsTrigger value="poster" className="gap-1.5">
                <ImageIcon className="w-4 h-4" />
                分享海报
              </TabsTrigger>
            </TabsList>

            {/* 推荐链接 */}
            <TabsContent value="link" className="mt-4 space-y-4">
              <div className="bg-card rounded-xl p-4 border">
                <div className="text-sm text-muted-foreground mb-2">我的邀请码</div>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold text-primary tracking-widest">
                    {linkInfo?.inviteCode}
                  </span>
                  <Button variant="outline" size="sm" onClick={handleCopyCode}>
                    <Copy className="w-4 h-4 mr-1" />
                    复制
                  </Button>
                </div>
              </div>

              <div className="bg-card rounded-xl p-4 border">
                <div className="text-sm text-muted-foreground mb-2">邀请链接</div>
                <div className="bg-muted/50 rounded-lg p-3 text-sm break-all text-foreground/80">
                  {linkInfo?.inviteLink}
                </div>
                <Button 
                  className="w-full mt-3" 
                  onClick={handleCopyLink}
                  disabled={copied}
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4 mr-2" />
                      已复制
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 mr-2" />
                      复制链接
                    </>
                  )}
                </Button>
              </div>
            </TabsContent>

            {/* 二维码 */}
            <TabsContent value="qrcode" className="mt-4">
              <div className="bg-card rounded-xl p-6 border text-center">
                <div className="inline-block p-4 bg-white rounded-xl shadow-sm">
                  <img 
                    src={linkInfo?.qrCodeUrl || '/placeholder.svg'} 
                    alt="邀请二维码"
                    className="w-48 h-48"
                  />
                </div>
                <p className="mt-4 text-sm text-muted-foreground">
                  长按或扫描二维码加入
                </p>
                <p className="mt-1 text-primary font-semibold">
                  邀请码: {linkInfo?.inviteCode}
                </p>
                
                <div className="mt-4 flex gap-3">
                  <Button 
                    variant="outline" 
                    className="flex-1"
                    onClick={() => {
                      if (linkInfo?.qrCodeUrl) {
                        const link = document.createElement('a')
                        link.download = `qrcode_${linkInfo.inviteCode}.png`
                        link.href = linkInfo.qrCodeUrl
                        link.click()
                        toast.success('二维码已保存')
                      }
                    }}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    保存二维码
                  </Button>
                  <Button className="flex-1" onClick={handleCopyLink}>
                    <Copy className="w-4 h-4 mr-2" />
                    复制链接
                  </Button>
                </div>
              </div>
            </TabsContent>

            {/* 分享海报 */}
            <TabsContent value="poster" className="mt-4">
              <div className="bg-card rounded-xl p-4 border">
                {/* 背景选择 */}
                <div className="mb-4">
                  <div className="text-sm text-muted-foreground mb-2">选择背景</div>
                  <div className="flex gap-2">
                    {posterConfig?.backgroundImages.map((bg, index) => (
                      <button
                        key={index}
                        onClick={() => setSelectedBg(index)}
                        className={`w-16 h-24 rounded-lg overflow-hidden border-2 transition-all ${
                          selectedBg === index 
                            ? 'border-primary ring-2 ring-primary/20' 
                            : 'border-transparent hover:border-muted-foreground/30'
                        }`}
                      >
                        <img 
                          src={bg} 
                          alt={`背景${index + 1}`}
                          className="w-full h-full object-cover"
                        />
                      </button>
                    ))}
                  </div>
                </div>

                {/* Canvas海报预览 */}
                <div className="relative flex justify-center bg-muted/30 rounded-lg p-4">
                  {generatingPoster && (
                    <div className="absolute inset-0 flex items-center justify-center bg-background/50 rounded-lg z-10">
                      <Loader2 className="w-8 h-8 animate-spin text-primary" />
                    </div>
                  )}
                  <canvas 
                    ref={canvasRef}
                    className="max-w-full h-auto rounded-lg shadow-lg"
                    style={{ maxHeight: '400px' }}
                  />
                </div>

                {/* 操作按钮 */}
                <div className="mt-4 flex gap-3">
                  <Button 
                    variant="outline" 
                    className="flex-1"
                    onClick={generatePoster}
                    disabled={generatingPoster}
                  >
                    {generatingPoster ? (
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    ) : (
                      <ImageIcon className="w-4 h-4 mr-2" />
                    )}
                    重新生成
                  </Button>
                  <Button 
                    className="flex-1"
                    onClick={handleSavePoster}
                    disabled={!posterGenerated}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    保存海报
                  </Button>
                </div>
              </div>
            </TabsContent>
          </Tabs>

          {/* 分享渠道 */}
          <div className="bg-card rounded-xl p-4 border">
            <div className="text-sm text-muted-foreground mb-3">分享到</div>
            <div className="grid grid-cols-4 gap-4">
              <button 
                onClick={() => handleShare('wechat')}
                className="flex flex-col items-center gap-1.5"
              >
                <div className="w-12 h-12 rounded-full bg-green-500 flex items-center justify-center">
                  <svg className="w-6 h-6 text-white" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M8.691 2.188C3.891 2.188 0 5.476 0 9.53c0 2.212 1.17 4.203 3.002 5.55a.59.59 0 0 1 .213.665l-.39 1.48c-.019.07-.048.141-.048.213 0 .163.13.295.29.295a.326.326 0 0 0 .167-.054l1.903-1.114a.864.864 0 0 1 .717-.098 10.16 10.16 0 0 0 2.837.403c.276 0 .543-.027.811-.05-.857-2.578.157-4.972 1.932-6.446 1.703-1.415 3.882-1.98 5.853-1.838-.576-3.583-4.196-6.348-8.596-6.348zM5.785 5.991c.642 0 1.162.529 1.162 1.18a1.17 1.17 0 0 1-1.162 1.178A1.17 1.17 0 0 1 4.623 7.17c0-.651.52-1.18 1.162-1.18zm5.813 0c.642 0 1.162.529 1.162 1.18a1.17 1.17 0 0 1-1.162 1.178 1.17 1.17 0 0 1-1.162-1.178c0-.651.52-1.18 1.162-1.18zm5.34 2.867c-1.797-.052-3.746.512-5.28 1.786-1.72 1.428-2.687 3.72-1.78 6.22.942 2.453 3.666 4.229 6.884 4.229.826 0 1.622-.12 2.361-.336a.722.722 0 0 1 .598.082l1.584.926a.272.272 0 0 0 .14.047c.134 0 .24-.111.24-.247 0-.06-.023-.12-.038-.177l-.327-1.233a.582.582 0 0 1-.023-.156.49.49 0 0 1 .201-.398C23.024 18.48 24 16.82 24 14.98c0-3.21-2.931-5.837-6.656-6.088V8.89l-.006-.033zm-2.722 2.394c.535 0 .969.44.969.982a.976.976 0 0 1-.969.983.976.976 0 0 1-.969-.983c0-.542.434-.982.97-.982zm4.844 0c.535 0 .969.44.969.982a.976.976 0 0 1-.969.983.976.976 0 0 1-.969-.983c0-.542.434-.982.969-.982z"/>
                  </svg>
                </div>
                <span className="text-xs text-muted-foreground">微信</span>
              </button>
              
              <button 
                onClick={() => handleShare('moments')}
                className="flex flex-col items-center gap-1.5"
              >
                <div className="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center">
                  <svg className="w-6 h-6 text-white" viewBox="0 0 24 24" fill="currentColor">
                    <circle cx="12" cy="12" r="10" />
                    <circle cx="12" cy="12" r="4" fill="white" />
                  </svg>
                </div>
                <span className="text-xs text-muted-foreground">朋友圈</span>
              </button>
              
              <button 
                onClick={() => handleShare('qq')}
                className="flex flex-col items-center gap-1.5"
              >
                <div className="w-12 h-12 rounded-full bg-blue-500 flex items-center justify-center">
                  <svg className="w-6 h-6 text-white" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12.003 2c-2.265 0-6.29 1.364-6.29 7.325v1.195S3.55 14.96 3.55 17.474c0 .665.17 1.025.281 1.025.114 0 .902-.484 1.748-2.072 0 0-.18 2.197 1.904 3.967 0 0-1.77.495-1.77 1.182 0 .686 4.078.43 6.29.43 2.212 0 6.29.256 6.29-.43 0-.687-1.77-1.182-1.77-1.182 2.084-1.77 1.904-3.967 1.904-3.967.846 1.588 1.634 2.072 1.748 2.072.11 0 .281-.36.281-1.025 0-2.514-2.163-6.954-2.163-6.954V9.325C18.293 3.364 14.268 2 12.003 2z"/>
                  </svg>
                </div>
                <span className="text-xs text-muted-foreground">QQ</span>
              </button>
              
              <button 
                onClick={() => handleShare('copy')}
                className="flex flex-col items-center gap-1.5"
              >
                <div className="w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                  <Copy className="w-6 h-6 text-muted-foreground" />
                </div>
                <span className="text-xs text-muted-foreground">复制链接</span>
              </button>
            </div>
          </div>

          {/* 查看邀请记录 */}
          <Button 
            variant="outline" 
            className="w-full justify-between"
            onClick={() => router.push('/mine/invite-records')}
          >
            <span>查看邀请记录</span>
            <ChevronRight className="w-4 h-4" />
          </Button>
        </div>
      </DataState>
    </div>
  )
}

// apps/mobile/src/pages/im/invite.vue
<template>
  <view class="page">
    <!-- 顶部导航 -->
    <view class="nav">
      <text
        class="nav-back"
        @click="goBack"
      >
        ←
      </text>
      <text class="nav-title">
        邀请好友
      </text>
      <view class="nav-placeholder" />
    </view>

    <DataState
      :is-loading="loading"
      :error="loadError"
      :is-empty="!linkInfo"
      empty-icon="🎁"
      empty-title="暂无邀请信息"
      skeleton-type="card"
      @retry="loadFullData"
    >
      <view class="content">
        <!-- 邀请奖励说明 -->
        <view class="reward-card">
          <view class="reward-header">
            <text class="reward-icon">
              🎁
            </text>
            <text class="reward-title">
              邀请奖励
            </text>
          </view>
          <view class="reward-list">
            <text class="reward-item">
              • 好友注册即得 <text class="reward-highlight">
                10积分
              </text>
            </text>
            <text class="reward-item">
              • 好友首次付费返佣 <text class="reward-highlight">
                10%
              </text>
            </text>
            <text class="reward-item">
              • 好友开通会员再得 <text class="reward-highlight">
                20元
              </text>
            </text>
          </view>
        </view>

        <!-- Tab切换 -->
        <view class="tabs">
          <text
            class="tab"
            :class="{ active: activeTab === 'link' }"
            @click="activeTab = 'link'"
          >
            🔗 推荐链接
          </text>
          <text
            class="tab"
            :class="{ active: activeTab === 'qrcode' }"
            @click="activeTab = 'qrcode'"
          >
            📱 二维码
          </text>
          <text
            class="tab"
            :class="{ active: activeTab === 'poster' }"
            @click="activeTab = 'poster'"
          >
            🖼 分享海报
          </text>
        </view>

        <!-- 推荐链接 -->
        <view
          v-if="activeTab === 'link'"
          class="tab-content"
        >
          <view class="info-card">
            <text class="info-label">
              我的邀请码
            </text>
            <view class="info-code-row">
              <text class="info-code">
                {{ linkInfo?.inviteCode || '------' }}
              </text>
              <text
                class="info-copy"
                @click="copyCode"
              >
                📋 复制
              </text>
            </view>
          </view>
          <view class="info-card">
            <text class="info-label">
              邀请链接
            </text>
            <view class="info-link-box">
              <text class="info-link-text">
                {{ linkInfo?.inviteLink || 'https://...' }}
              </text>
            </view>
            <text
              class="info-copy-link"
              @click="copyLink"
            >
              {{ copied ? '✅ 已复制' : '📋 复制链接' }}
            </text>
          </view>
        </view>

        <!-- 二维码 -->
        <view
          v-if="activeTab === 'qrcode'"
          class="tab-content"
        >
          <view class="qrcode-card">
            <view class="qrcode-img-wrap">
              <view class="qrcode-img-placeholder">
                📱 扫码加入
              </view>
            </view>
            <text class="qrcode-hint">
              长按或扫描二维码加入
            </text>
            <text class="qrcode-code">
              邀请码: {{ linkInfo?.inviteCode || '------' }}
            </text>
            <view class="qrcode-actions">
              <text
                class="qrcode-btn qrcode-btn-outline"
                @click="saveQr"
              >
                ⬇ 保存二维码
              </text>
              <text
                class="qrcode-btn qrcode-btn-primary"
                @click="copyLink"
              >
                📋 复制链接
              </text>
            </view>
          </view>
        </view>

        <!-- 分享海报 -->
        <view
          v-if="activeTab === 'poster'"
          class="tab-content"
        >
          <view class="poster-card">
            <!-- 背景选择 -->
            <view class="poster-bg-section">
              <text class="poster-label">
                选择背景
              </text>
              <scroll-view
                scroll-x
                class="poster-bg-scroll"
                show-scrollbar="false"
              >
                <view class="poster-bg-row">
                  <view
                    v-for="(bg, idx) in posterBgList"
                    :key="idx"
                    class="poster-bg-thumb"
                    :class="{ selected: selectedBg === idx }"
                    @click="selectedBg = idx"
                  >
                    <view class="poster-bg-placeholder">
                      🎨
                    </view>
                  </view>
                </view>
              </scroll-view>
            </view>

            <!-- 海报预览 -->
            <view class="poster-preview">
              <view class="poster-placeholder">
                <text class="poster-placeholder-title">
                  邀请海报
                </text>
                <text class="poster-placeholder-name">
                  {{ posterConfig?.userName || '用户' }}
                </text>
                <text class="poster-placeholder-sub">
                  邀请您加入国学平台
                </text>
                <view class="poster-placeholder-qr">
                  <text class="poster-placeholder-code">
                    邀请码: {{ posterConfig?.inviteCode || linkInfo?.inviteCode || '------' }}
                  </text>
                </view>
              </view>
            </view>

            <!-- 操作按钮 -->
            <view class="poster-actions">
              <text
                class="poster-btn poster-btn-outline"
                @click="regeneratePoster"
              >
                🔄 重新生成
              </text>
              <text
                class="poster-btn poster-btn-primary"
                @click="savePoster"
              >
                ⬇ 保存海报
              </text>
            </view>
          </view>
        </view>

        <!-- 分享渠道 -->
        <view class="share-section">
          <text class="share-title">
            分享到
          </text>
          <view class="share-grid">
            <view
              class="share-item"
              @click="shareTo('wechat')"
            >
              <view class="share-icon wechat">
                <text>💬</text>
              </view>
              <text class="share-name">
                微信
              </text>
            </view>
            <view
              class="share-item"
              @click="shareTo('moments')"
            >
              <view class="share-icon moments">
                <text>🔄</text>
              </view>
              <text class="share-name">
                朋友圈
              </text>
            </view>
            <view
              class="share-item"
              @click="shareTo('qq')"
            >
              <view class="share-icon qq">
                <text>🐧</text>
              </view>
              <text class="share-name">
                QQ
              </text>
            </view>
            <view
              class="share-item"
              @click="copyLink"
            >
              <view class="share-icon copy">
                <text>📋</text>
              </view>
              <text class="share-name">
                复制链接
              </text>
            </view>
          </view>
        </view>

        <!-- 查看邀请记录 -->
        <view
          class="records-link"
          @click="goRecords"
        >
          <text>查看邀请记录</text>
          <text>›</text>
        </view>
      </view>
    </DataState>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import DataState from '../../components/DataState.vue'
import { api, commissionApi } from '../../api'

interface InviteLinkInfo {
  inviteCode: string
  inviteLink: string
  qrCodeUrl?: string
}

interface PosterConfig {
  userName: string
  title: string
  subtitle: string
  benefits: string[]
  qrCodeUrl: string
  inviteCode: string
  backgroundImages: string[]
  userAvatar?: string
}

const loading = ref(true)
const loadError = ref<string | null>(null)
const activeTab = ref<'link' | 'qrcode' | 'poster'>('link')
const linkInfo = ref<InviteLinkInfo | null>(null)
const posterConfig = ref<PosterConfig | null>(null)
const copied = ref(false)
const selectedBg = ref(0)
const posterBgList = ref([1, 2, 3]) // 占位背景列表

function goBack() { uni.navigateBack() }

function goRecords() {
  uni.navigateTo({ url: '/pages/mine/invite-records' })
}

async function loadFullData() {
  loading.value = true
  loadError.value = null
  try {
    // 优先从 commissionApi 获取推荐链接信息
    let inviteCode = 'GUOXUE888'
    let inviteLink = 'https://api.rebugx.cn/invite?code=GUOXUE888'
    try {
      const linksRes = await commissionApi.referralLinks() as any
      const links = Array.isArray(linksRes?.data ?? linksRes) ? (linksRes?.data ?? linksRes) : []
      if (links.length > 0) {
        const link = links[0]
        inviteCode = link.code || link.inviteCode || inviteCode
        inviteLink = link.url || link.link || inviteLink
      }
    } catch {
      // commissionApi 不可用时，尝试通过用户资料获取邀请码
      try {
        const profile = await api.get('/auth/me') as any
        const data = profile?.data ?? profile
        inviteCode = data.inviteCode || data.referralCode || inviteCode
        inviteLink = data.inviteLink || `https://api.rebugx.cn/invite?code=${inviteCode}`
      } catch {
        // 使用默认值
      }
    }

    linkInfo.value = {
      inviteCode,
      inviteLink,
      qrCodeUrl: '',
    }

    posterConfig.value = {
      userName: '',
      title: '邀请您加入国学平台',
      subtitle: '一起学习传统文化',
      benefits: ['专属国学课程', '名师在线答疑', '经典古籍库'],
      qrCodeUrl: '',
      inviteCode,
      backgroundImages: [],
    }
  } catch (e: any) {
    loadError.value = e?.errMsg || e?.message || '加载失败'
  } finally {
    loading.value = false
  }
}

onMounted(() => { loadFullData() })

async function copyLink() {
  if (!linkInfo.value) return
  try {
    await uni.setClipboardData({ data: linkInfo.value.inviteLink })
    copied.value = true
    uni.showToast({ title: '链接已复制', icon: 'none' })
    setTimeout(() => { copied.value = false }, 2000)
  } catch {
    uni.showToast({ title: '复制失败', icon: 'none' })
  }
}

async function copyCode() {
  if (!linkInfo.value) return
  try {
    await uni.setClipboardData({ data: linkInfo.value.inviteCode })
    uni.showToast({ title: '邀请码已复制', icon: 'none' })
  } catch {
    uni.showToast({ title: '复制失败', icon: 'none' })
  }
}

function saveQr() {
  uni.showToast({ title: '二维码已保存', icon: 'none' })
}

function regeneratePoster() {
  uni.showToast({ title: '海报重新生成中...', icon: 'none' })
}

function savePoster() {
  uni.showToast({ title: '海报已保存', icon: 'none' })
}

function shareTo(channel: string) {
  const messages: Record<string, string> = {
    wechat: '请在微信中打开分享',
    moments: '请在微信朋友圈中打开分享',
    qq: '请在QQ中打开分享',
    weibo: '请在微博中打开分享',
    copy: '链接已复制',
  }
  if (channel === 'copy') {
    copyLink()
  } else {
    uni.showToast({ title: messages[channel] || '分享功能开发中', icon: 'none' })
  }
}
</script>

<style scoped>
.page { background: #F5F0E8; min-height: 100vh; }

/* 导航 */
.nav { display: flex; align-items: center; justify-content: space-between; padding: 12px 16px; background: linear-gradient(135deg, #C41E3A, #B01A32); color: #fff; }
.nav-back { font-size: 22px; color: #fff; padding: 4px; }
.nav-title { font-size: 18px; font-weight: 600; color: #fff; }
.nav-placeholder { width: 30px; }

.content { padding: 16px; }

/* 奖励卡片 */
.reward-card { background: linear-gradient(135deg, #fef7e6, #fef0e0); border-radius: 12px; padding: 16px; margin-bottom: 16px; border: 1px solid rgba(201,169,110,0.3); }
.reward-header { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
.reward-icon { font-size: 20px; }
.reward-title { font-weight: 600; font-size: 15px; color: #8B6914; }
.reward-list { }
.reward-item { font-size: 13px; color: #8B6914; display: block; line-height: 1.8; }
.reward-highlight { font-weight: 600; color: #C41E3A; }

/* Tabs */
.tabs { display: flex; background: #fff; border-radius: 8px; overflow: hidden; margin-bottom: 16px; }
.tab { flex: 1; text-align: center; padding: 12px 8px; font-size: 13px; color: #666; border-bottom: 2px solid transparent; }
.tab.active { color: #C41E3A; border-bottom-color: #C41E3A; font-weight: 600; }

/* Tab内容 */
.tab-content { margin-bottom: 16px; }
.info-card { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.04); }
.info-label { font-size: 13px; color: #999; display: block; margin-bottom: 8px; }
.info-code-row { display: flex; align-items: center; justify-content: space-between; }
.info-code { font-size: 24px; font-weight: bold; color: #C41E3A; letter-spacing: 4px; }
.info-copy { font-size: 13px; color: #C41E3A; padding: 4px 12px; border: 1px solid #C41E3A; border-radius: 6px; }
.info-link-box { background: #F5F0E8; border-radius: 8px; padding: 10px 12px; }
.info-link-text { font-size: 13px; color: #666; word-break: break-all; }
.info-copy-link { display: block; text-align: center; margin-top: 12px; padding: 10px; background: #C41E3A; color: #fff; border-radius: 8px; font-size: 14px; font-weight: 500; }

/* 二维码 */
.qrcode-card { background: #fff; border-radius: 12px; padding: 24px; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.04); }
.qrcode-img-wrap { display: inline-block; padding: 12px; background: #fff; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }
.qrcode-img-placeholder { width: 160px; height: 160px; background: #F5F0E8; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 18px; color: #999; }
.qrcode-hint { font-size: 14px; color: #999; display: block; margin-top: 12px; }
.qrcode-code { font-size: 14px; color: #C41E3A; font-weight: 600; display: block; margin-top: 4px; }
.qrcode-actions { display: flex; gap: 12px; margin-top: 16px; }
.qrcode-btn { flex: 1; padding: 10px; border-radius: 8px; font-size: 13px; text-align: center; }
.qrcode-btn-outline { background: #F5F0E8; color: #666; }
.qrcode-btn-primary { background: #C41E3A; color: #fff; }

/* 海报 */
.poster-card { background: #fff; border-radius: 12px; padding: 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.04); }
.poster-bg-section { margin-bottom: 16px; }
.poster-label { font-size: 13px; color: #999; display: block; margin-bottom: 8px; }
.poster-bg-scroll { white-space: nowrap; }
.poster-bg-row { display: inline-flex; gap: 8px; }
.poster-bg-thumb { width: 60px; height: 80px; border-radius: 8px; overflow: hidden; display: inline-flex; align-items: center; justify-content: center; background: #F5F0E8; border: 2px solid transparent; }
.poster-bg-thumb.selected { border-color: #C41E3A; }
.poster-bg-placeholder { font-size: 24px; }

.poster-preview { background: #F5F0E8; border-radius: 8px; padding: 24px; margin-bottom: 12px; display: flex; justify-content: center; }
.poster-placeholder { width: 240px; text-align: center; }
.poster-placeholder-title { font-size: 20px; font-weight: bold; color: #C41E3A; display: block; margin-bottom: 12px; }
.poster-placeholder-name { font-size: 16px; color: #2C2C2C; display: block; font-weight: 500; }
.poster-placeholder-sub { font-size: 13px; color: #666; display: block; margin: 8px 0 16px; }
.poster-placeholder-qr { background: #fff; border-radius: 8px; padding: 12px; display: inline-block; }
.poster-placeholder-code { font-size: 12px; color: #C41E3A; }

.poster-actions { display: flex; gap: 12px; }
.poster-btn { flex: 1; padding: 10px; border-radius: 8px; font-size: 13px; text-align: center; }
.poster-btn-outline { background: #F5F0E8; color: #666; }
.poster-btn-primary { background: #C41E3A; color: #fff; }

/* 分享 */
.share-section { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.04); }
.share-title { font-size: 13px; color: #999; display: block; margin-bottom: 12px; }
.share-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.share-item { display: flex; flex-direction: column; align-items: center; gap: 6px; }
.share-icon { width: 48px; height: 48px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 22px; }
.share-icon.wechat { background: #07c160; }
.share-icon.moments { background: #06ad56; }
.share-icon.qq { background: #12b7f5; }
.share-icon.copy { background: #F5F0E8; }
.share-name { font-size: 11px; color: #666; }

/* 邀请记录 */
.records-link {
  display: flex; align-items: center; justify-content: space-between;
  background: #fff; border-radius: 12px; padding: 14px 16px;
  font-size: 14px; color: #2C2C2C; box-shadow: 0 2px 8px rgba(0,0,0,0.04);
}
.records-link:active { background: #FAF8F5; }
</style>
