// apps/mobile/src/pkg-classics/bookshelf/index.vue
<template>
  <view class="bs-page">
    <!-- 顶部导航 -->
    <view
      class="bs-header"
      :style="{ paddingTop: statusBarH + 'px' }"
    >
      <view class="bs-nav">
        <view class="bs-nav-left">
          <view
            class="bs-iconbtn"
            @tap="goBack"
          >
            <app-icon
              name="arrow-left"
              :size="40"
              color="#6b6b6b"
            />
          </view>
          <text class="bs-title">
            我的书房
          </text>
        </view>
        <view class="bs-nav-right">
          <template v-if="isSelectMode">
            <view
              class="bs-textbtn"
              @tap="exitSelect"
            >
              取消
            </view>
            <view
              class="bs-textbtn bs-textbtn-danger"
              :class="{ 'bs-textbtn-disabled': selectedIds.length === 0 }"
              @tap="batchRemove"
            >
              移除 ({{ selectedIds.length }})
            </view>
          </template>
          <template v-else>
            <view
              class="bs-iconbtn"
              @tap="goSearch"
            >
              <app-icon
                name="search"
                :size="34"
                color="#6b6b6b"
              />
            </view>
            <view
              class="bs-iconbtn"
              @tap="toggleMenu"
            >
              <app-icon
                name="more-vertical"
                :size="34"
                color="#6b6b6b"
              />
            </view>
          </template>
        </view>
      </view>

      <!-- 更多菜单 -->
      <view
        v-if="menuOpen"
        class="bs-menu-mask"
        @tap="menuOpen = false"
      >
        <view
          class="bs-menu"
          @tap.stop
        >
          <view
            class="bs-menu-item"
            @tap="enterSelect"
          >
            批量管理
          </view>
          <view
            class="bs-menu-item"
            @tap="onNewGroup"
          >
            <app-icon
              name="folder-plus"
              :size="32"
              color="#4a4a4a"
            />
            <text>新建分组</text>
          </view>
        </view>
      </view>
    </view>

    <!-- 标签页头 -->
    <view class="bs-tabs">
      <view class="bs-tablist">
        <view
          class="bs-tab"
          :class="{ 'bs-tab-active': activeTab === 'shelf' }"
          @tap="activeTab = 'shelf'"
        >
          书架
        </view>
        <view
          class="bs-tab"
          :class="{ 'bs-tab-active': activeTab === 'history' }"
          @tap="activeTab = 'history'"
        >
          浏览历史
        </view>
      </view>
    </view>

    <!-- 书架 Tab -->
    <view v-show="activeTab === 'shelf'">
      <!-- 分组筛选 -->
      <scroll-view
        scroll-x
        class="bs-groups"
        :show-scrollbar="false"
      >
        <view class="bs-groups-row">
          <view
            class="bs-group"
            :class="activeGroup === null ? 'bs-group-all-active' : 'bs-group-idle'"
            @tap="activeGroup = null"
          >
            全部
          </view>
          <view
            v-for="g in groups"
            :key="g.id"
            class="bs-group bs-group-flex"
            :class="activeGroup === g.id ? groupActiveClass(g.color) : 'bs-group-idle'"
            @tap="activeGroup = g.id"
          >
            <text>{{ g.name }}</text>
            <text class="bs-group-badge">
              {{ g.count }}
            </text>
          </view>
          <view
            class="bs-group-plus"
            @tap="onNewGroup"
          >
            <app-icon
              name="plus"
              :size="34"
              color="#6b6b6b"
            />
          </view>
        </view>
      </scroll-view>

      <!-- 视图切换 -->
      <view class="bs-viewbar">
        <text class="bs-count">
          共 <text class="bs-count-num">
            {{ filteredBooks.length }}
          </text> 本
        </text>
        <view class="bs-viewtoggle">
          <view
            class="bs-vt-btn"
            :class="{ 'bs-vt-active': viewMode === 'grid' }"
            @tap="viewMode = 'grid'"
          >
            <app-icon
              name="grid-3x3"
              :size="34"
              color="#4a4a4a"
            />
          </view>
          <view
            class="bs-vt-btn"
            :class="{ 'bs-vt-active': viewMode === 'list' }"
            @tap="viewMode = 'list'"
          >
            <app-icon
              name="list"
              :size="34"
              color="#4a4a4a"
            />
          </view>
        </view>
      </view>

      <!-- 书籍区 -->
      <view class="bs-body">
        <!-- 空态 -->
        <view
          v-if="filteredBooks.length === 0"
          class="bs-empty"
        >
          <view class="bs-empty-icon">
            <app-icon
              name="book-open"
              :size="64"
              color="#999999"
            />
          </view>
          <text class="bs-empty-title">
            书架是空的
          </text>
          <text class="bs-empty-desc">
            去古籍馆探索感兴趣的古籍吧
          </text>
          <view
            class="bs-empty-btn"
            @tap="goHome"
          >
            探索古籍
          </view>
        </view>

        <!-- 网格视图 -->
        <view
          v-else-if="viewMode === 'grid'"
          class="bs-grid"
        >
          <view
            v-for="book in filteredBooks"
            :key="book.id"
            class="bs-grid-item"
            :class="{ 'bs-grid-selected': isSelectMode && selectedIds.includes(book.id) }"
            @tap="onGridTap(book)"
          >
            <view class="bs-cover-wrap">
              <flat-cover
                :title="book.title"
                :label="book.dynasty"
                :cover-color="coverColorForBook(book.title)"
                title-size="32rpx"
                class="bs-cover"
              />
              <text
                v-if="book.hasAI"
                class="bs-tag-ai"
              >
                AI
              </text>
              <text
                v-if="book.progress >= 100"
                class="bs-tag-done"
              >
                已读完
              </text>
              <view
                v-if="isSelectMode && selectedIds.includes(book.id)"
                class="bs-check"
              >
                <app-icon
                  name="check"
                  :size="24"
                  color="#ffffff"
                />
              </view>
            </view>
            <text class="bs-book-title">
              {{ book.title }}
            </text>
            <!-- 已读完: 读后小结 -->
            <view
              v-if="book.progress >= 100"
              class="bs-summary-btn"
              @tap.stop="openSummary(book)"
            >
              <app-icon
                name="sparkles"
                :size="24"
                color="#8a6d2f"
              />
              <text>读后小结</text>
            </view>
            <!-- 进度条 -->
            <view
              v-else-if="book.progress > 0"
              class="bs-progress"
            >
              <view class="bs-progress-track">
                <view
                  class="bs-progress-fill"
                  :style="{ width: Math.min(book.progress, 100) + '%' }"
                />
              </view>
              <text class="bs-progress-num">
                {{ book.progress }}%
              </text>
            </view>
          </view>

          <!-- 添加更多 -->
          <view
            class="bs-add"
            @tap="goHome"
          >
            <app-icon
              name="plus"
              :size="48"
              color="#999999"
            />
            <text class="bs-add-text">
              添加
            </text>
          </view>
        </view>

        <!-- 列表视图 -->
        <view
          v-else
          class="bs-list"
        >
          <view
            v-for="book in filteredBooks"
            :key="book.id"
            class="bs-list-card"
            :class="{ 'bs-list-selected': isSelectMode && selectedIds.includes(book.id) }"
            @tap="onListTap(book)"
          >
            <view class="bs-spine">
              <view class="bs-spine-edge" />
              <text class="bs-spine-title">
                {{ book.title.slice(0, 3) }}
              </text>
            </view>
            <text class="bs-list-title">
              {{ book.title }}
            </text>
            <text class="bs-list-meta">
              [{{ book.dynasty }}] {{ book.author }}
            </text>
            <view class="bs-list-progress">
              <view class="bs-progress-track">
                <view
                  class="bs-progress-fill bs-progress-fill-soft"
                  :style="{ width: book.progress + '%' }"
                />
              </view>
              <text class="bs-progress-num">
                {{ book.progress }}%
              </text>
            </view>
            <view
              v-if="!isSelectMode"
              class="bs-row-menu"
              @tap.stop="openRowMenu(book)"
            >
              <app-icon
                name="more-vertical"
                :size="34"
                color="#6b6b6b"
              />
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 浏览历史 Tab -->
    <view
      v-show="activeTab === 'history'"
      class="bs-history"
    >
      <view
        v-for="item in readingHistory"
        :key="item.id"
        class="bs-history-card"
        @tap="goReader(item.id)"
      >
        <view class="bs-spine bs-spine-sm">
          <view class="bs-spine-edge" />
          <text class="bs-spine-title bs-spine-title-sm">
            {{ item.title.slice(0, 2) }}
          </text>
        </view>
        <view class="bs-hist-info">
          <text class="bs-hist-title">
            {{ item.title }}
          </text>
          <text class="bs-hist-chapter">
            {{ item.chapter }}
          </text>
        </view>
        <view class="bs-history-time">
          <app-icon
            name="clock"
            :size="24"
            color="#999999"
          />
          <text>{{ item.readAt }}</text>
        </view>
      </view>
      <view
        v-if="readingHistory.length > 0"
        class="bs-clear-history"
        @tap="onClearHistory"
      >
        清空历史记录
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import FlatCover from '@/components/classics/flat-cover.vue'
import { coverColorForBook } from '@/lib/classics-cover'

const statusBarH = ref(0)
try {
  const info = uni.getSystemInfoSync()
  statusBarH.value = info.statusBarHeight || 0
} catch (e) {}

interface ShelfBook {
  id: string
  title: string
  author: string
  dynasty: string
  progress: number
  hasAI: boolean
}

const books = ref<ShelfBook[]>([
  { id: '1', title: '周易', author: '伏羲', dynasty: '周', progress: 32, hasAI: true },
  { id: '2', title: '道德经', author: '老子', dynasty: '春秋', progress: 68, hasAI: true },
  { id: '3', title: '黄帝内经', author: '佚名', dynasty: '战国', progress: 15, hasAI: true },
  { id: '4', title: '论语', author: '孔子门人', dynasty: '春秋', progress: 45, hasAI: true },
  { id: '5', title: '滴天髓', author: '刘基', dynasty: '明', progress: 8, hasAI: true },
  { id: '6', title: '大学', author: '曾子', dynasty: '战国', progress: 100, hasAI: true },
])

const readingHistory = ref([
  { id: '1', title: '周易', author: '伏羲', dynasty: '周', chapter: '乾卦', readAt: '今天 14:30' },
  { id: '2', title: '道德经', author: '老子', dynasty: '春秋', chapter: '第四十二章', readAt: '昨天 20:15' },
  { id: '3', title: '论语', author: '孔子门人', dynasty: '春秋', chapter: '学而篇', readAt: '3天前' },
])

const groups = ref([
  { id: '1', name: '命理研究', count: 5, color: 'amber' },
  { id: '2', name: '道家经典', count: 3, color: 'emerald' },
  { id: '3', name: '养生必读', count: 4, color: 'blue' },
])

const activeTab = ref<'shelf' | 'history'>('shelf')
const viewMode = ref<'grid' | 'list'>('grid')
const activeGroup = ref<string | null>(null)
const isSelectMode = ref(false)
const selectedIds = ref<string[]>([])
const menuOpen = ref(false)
const searchValue = ref('')

const filteredBooks = computed(() =>
  books.value.filter(
    (b) => b.title.includes(searchValue.value) || b.author.includes(searchValue.value)
  )
)

function groupActiveClass(color: string): string {
  return `bs-group-${color}`
}

function goBack() {
  uni.navigateBack({ delta: 1, fail: () => uni.switchTab({ url: '/pages/index/index' }) })
}
function goSearch() {
  uni.navigateTo({ url: '/pkg-classics/search/index' })
}
function goHome() {
  uni.navigateTo({ url: '/pkg-classics/home/index' })
}
function goReader() {
  uni.showToast({ title: '阅读器即将上线', icon: 'none' })
}
function goDetail(id: string) {
  uni.navigateTo({ url: `/pkg-classics/detail/index?id=${id}` })
}

function toggleMenu() {
  menuOpen.value = !menuOpen.value
}
function enterSelect() {
  isSelectMode.value = true
  menuOpen.value = false
  selectedIds.value = []
}
function exitSelect() {
  isSelectMode.value = false
  selectedIds.value = []
}
function onNewGroup() {
  menuOpen.value = false
  uni.showToast({ title: '新建分组', icon: 'none' })
}
function toggleSelect(id: string) {
  const i = selectedIds.value.indexOf(id)
  if (i >= 0) selectedIds.value.splice(i, 1)
  else selectedIds.value.push(id)
}
function batchRemove() {
  if (selectedIds.value.length === 0) return
  books.value = books.value.filter((b) => !selectedIds.value.includes(b.id))
  selectedIds.value = []
  isSelectMode.value = false
}

function onGridTap(book: ShelfBook) {
  if (isSelectMode.value) toggleSelect(book.id)
  else goDetail(book.id)
}
function onListTap(book: ShelfBook) {
  if (isSelectMode.value) toggleSelect(book.id)
  else goDetail(book.id)
}
function openRowMenu(book: ShelfBook) {
  uni.showActionSheet({
    itemList: ['继续阅读', '移动分组', '移出书架'],
    success: (res) => {
      if (res.tapIndex === 2) {
        books.value = books.value.filter((b) => b.id !== book.id)
      } else if (res.tapIndex === 0) {
        goReader()
      } else {
        uni.showToast({ title: '移动分组', icon: 'none' })
      }
    },
  })
}

// 读后小结成就弹窗 —— 母版(canvas)后续单独迁移，此处占位
function openSummary(book: ShelfBook) {
  uni.showToast({ title: `《${book.title}》读后小结即将上线`, icon: 'none' })
}
function onClearHistory() {
  uni.showModal({
    title: '清空历史记录',
    content: '确定清空全部浏览历史吗？',
    success: (res) => {
      if (res.confirm) readingHistory.value = []
    },
  })
}
</script>

<style scoped>
.bs-page {
  min-height: 100vh;
  background: var(--card);
  padding-bottom: 48rpx;
}

/* 顶栏 */
.bs-header {
  position: sticky;
  top: 0;
  z-index: 50;
  background: var(--card);
  border-bottom: 1rpx solid var(--border);
}
.bs-nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 32rpx;
  height: 112rpx;
}
.bs-nav-left {
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.bs-iconbtn {
  width: 64rpx;
  height: 64rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.bs-title {
  font-size: 32rpx;
  font-weight: 500;
  color: var(--foreground);
}
.bs-nav-right {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.bs-textbtn {
  font-size: 28rpx;
  padding: 8rpx 20rpx;
  border-radius: 12rpx;
  color: var(--foreground);
}
.bs-textbtn-danger {
  background: #c41e3a;
  color: #fff;
}
.bs-textbtn-disabled {
  opacity: 0.5;
}

/* 更多菜单 */
.bs-menu-mask {
  position: fixed;
  inset: 0;
  z-index: 60;
}
.bs-menu {
  position: absolute;
  top: 100rpx;
  right: 32rpx;
  background: var(--card);
  border-radius: 16rpx;
  box-shadow: 0 8rpx 32rpx rgba(0, 0, 0, 0.12);
  border: 1rpx solid var(--border);
  padding: 8rpx;
  min-width: 240rpx;
}
.bs-menu-item {
  display: flex;
  align-items: center;
  gap: 16rpx;
  padding: 20rpx 24rpx;
  font-size: 28rpx;
  color: var(--foreground);
  border-radius: 12rpx;
}

/* Tabs */
.bs-tabs {
  padding: 24rpx 32rpx 16rpx;
  border-bottom: 1rpx solid var(--border);
}
.bs-tablist {
  display: flex;
  background: rgba(0, 0, 0, 0.04);
  border-radius: 16rpx;
  padding: 4rpx;
}
.bs-tab {
  flex: 1;
  height: 64rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24rpx;
  color: var(--muted-foreground);
  border-radius: 12rpx;
}
.bs-tab-active {
  background: var(--card);
  color: var(--foreground);
  font-weight: 500;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.06);
}

/* 分组筛选 */
.bs-groups {
  white-space: nowrap;
  padding: 24rpx 0;
}
.bs-groups-row {
  display: inline-flex;
  align-items: center;
  gap: 16rpx;
  padding: 0 32rpx;
}
.bs-group {
  padding: 12rpx 24rpx;
  border-radius: 999rpx;
  font-size: 24rpx;
  white-space: nowrap;
}
.bs-group-flex {
  display: flex;
  align-items: center;
  gap: 8rpx;
  white-space: nowrap;
}
.bs-group text {
  white-space: nowrap;
}
.bs-group-idle {
  background: rgba(0, 0, 0, 0.05);
  color: var(--muted-foreground);
}
.bs-group-all-active {
  background: #c41e3a;
  color: #fff;
}
.bs-group-amber {
  background: #fef3c7;
  color: #b45309;
}
.bs-group-emerald {
  background: #d1fae5;
  color: #047857;
}
.bs-group-blue {
  background: #dbeafe;
  color: #1d4ed8;
}
.bs-group-badge {
  font-size: 18rpx;
  padding: 0 8rpx;
  height: 28rpx;
  line-height: 28rpx;
  border-radius: 8rpx;
  background: rgba(0, 0, 0, 0.06);
}
.bs-group-plus {
  width: 56rpx;
  height: 56rpx;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.05);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

/* 视图栏 */
.bs-viewbar {
  padding: 0 32rpx 24rpx;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.bs-count {
  font-size: 24rpx;
  color: var(--muted-foreground);
}
.bs-count-num {
  color: var(--foreground);
  font-weight: 500;
}
.bs-viewtoggle {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.bs-vt-btn {
  padding: 12rpx;
  border-radius: 10rpx;
}
.bs-vt-active {
  background: rgba(0, 0, 0, 0.06);
}

/* 书籍区 */
.bs-body {
  padding: 0 32rpx;
}

/* 空态 */
.bs-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 128rpx 0;
  text-align: center;
}
.bs-empty-icon {
  width: 160rpx;
  height: 160rpx;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.05);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 32rpx;
}
.bs-empty-title {
  font-size: 30rpx;
  font-weight: 500;
  color: var(--foreground);
  margin-bottom: 8rpx;
}
.bs-empty-desc {
  font-size: 26rpx;
  color: var(--muted-foreground);
  margin-bottom: 32rpx;
}
.bs-empty-btn {
  padding: 18rpx 48rpx;
  border-radius: 999rpx;
  background: #c41e3a;
  color: #fff;
  font-size: 28rpx;
}

/* 网格 */
.bs-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24rpx;
}
.bs-grid-item {
  position: relative;
}
.bs-grid-selected {
  outline: 4rpx solid #c41e3a;
  border-radius: 16rpx;
}
.bs-cover-wrap {
  position: relative;
}
.bs-cover {
  width: 100%;
  box-shadow: 0 4rpx 12rpx rgba(0, 0, 0, 0.12);
}
.bs-tag-ai {
  position: absolute;
  top: 12rpx;
  left: 12rpx;
  font-size: 18rpx;
  font-weight: 500;
  padding: 2rpx 10rpx;
  border-radius: 8rpx;
  background: rgba(0, 0, 0, 0.3);
  color: #fff;
}
.bs-tag-done {
  position: absolute;
  top: 12rpx;
  right: 12rpx;
  font-size: 18rpx;
  font-weight: 500;
  padding: 2rpx 10rpx;
  border-radius: 8rpx;
  background: #c41e3a;
  color: #fff;
}
.bs-check {
  position: absolute;
  top: 12rpx;
  right: 12rpx;
  width: 40rpx;
  height: 40rpx;
  border-radius: 50%;
  background: #c41e3a;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.2);
}
.bs-book-title {
  display: block;
  margin-top: 12rpx;
  font-size: 26rpx;
  font-weight: 500;
  color: var(--foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.bs-summary-btn {
  margin-top: 8rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8rpx;
  padding: 8rpx 0;
  border-radius: 10rpx;
  font-size: 22rpx;
  font-weight: 500;
  background: rgba(201, 169, 110, 0.12);
  color: #8a6d2f;
}
.bs-progress {
  margin-top: 8rpx;
  display: flex;
  align-items: center;
  gap: 12rpx;
}
.bs-progress-track {
  flex: 1;
  height: 8rpx;
  border-radius: 999rpx;
  background: rgba(0, 0, 0, 0.08);
  overflow: hidden;
}
.bs-progress-fill {
  height: 100%;
  border-radius: 999rpx;
  background: #c41e3a;
}
.bs-progress-fill-soft {
  background: rgba(196, 30, 58, 0.7);
}
.bs-progress-num {
  font-size: 20rpx;
  color: var(--muted-foreground);
  font-variant-numeric: tabular-nums;
}
.bs-add {
  aspect-ratio: 3 / 4;
  border-radius: 24rpx;
  background: rgba(0, 0, 0, 0.04);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12rpx;
}
.bs-add-text {
  font-size: 24rpx;
  color: var(--muted-foreground);
}

/* 列表 */
.bs-list {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.bs-list-card {
  position: relative;
  background: var(--card);
  border: 1rpx solid var(--border);
  border-radius: 24rpx;
  padding: 32rpx 24rpx;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12rpx;
}
.bs-list-selected {
  outline: 4rpx solid #c41e3a;
}
.bs-row-menu {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 64rpx;
  height: 56rpx;
  margin-top: 4rpx;
}
.bs-spine {
  position: relative;
  width: 96rpx;
  height: 128rpx;
  border-radius: 6rpx;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f5f0e1;
  border: 1rpx solid rgba(201, 184, 150, 0.5);
  box-shadow: 0 2rpx 6rpx rgba(0, 0, 0, 0.08);
}
.bs-spine-sm {
  width: 80rpx;
  height: 112rpx;
}
.bs-spine-edge {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 12rpx;
  background: #d4c4a8;
  border-radius: 6rpx 0 0 6rpx;
}
.bs-spine-title {
  writing-mode: vertical-rl;
  font-size: 22rpx;
  font-weight: 700;
  color: #4a3f2f;
  font-family: 'Songti SC', 'STSong', serif;
}
.bs-spine-title-sm {
  font-size: 18rpx;
}
.bs-list-info {
  flex: 1;
  min-width: 0;
}
.bs-list-title {
  display: block;
  font-size: 28rpx;
  font-weight: 600;
  color: var(--foreground);
  text-align: center;
  margin-top: 8rpx;
}
.bs-list-meta {
  display: block;
  font-size: 22rpx;
  color: var(--muted-foreground);
  text-align: center;
}
.bs-list-progress {
  display: flex;
  align-items: center;
  gap: 16rpx;
  margin-top: 8rpx;
  width: 60%;
}

/* 浏览历史 */
.bs-history {
  padding: 32rpx;
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.bs-history-card {
  background: var(--card);
  border: 1rpx solid var(--border);
  border-radius: 24rpx;
  padding: 24rpx;
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.bs-hist-info {
  flex: 1;
  min-width: 0;
}
.bs-hist-title {
  display: block;
  font-size: 28rpx;
  font-weight: 500;
  color: var(--foreground);
}
.bs-hist-chapter {
  display: block;
  font-size: 22rpx;
  color: var(--muted-foreground);
  margin-top: 2rpx;
}
.bs-history-time {
  display: flex;
  align-items: center;
  gap: 8rpx;
  font-size: 22rpx;
  color: var(--muted-foreground);
  flex-shrink: 0;
}
.bs-clear-history {
  text-align: center;
  padding: 20rpx;
  font-size: 22rpx;
  color: var(--muted-foreground);
}
</style>

// v0-reference/proto-ref-app/classics/bookshelf/page.tsx
"use client"

import { useState, useCallback } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { cn } from "@/lib/utils"
import { 
  ArrowLeft, Search, Grid3X3, List, MoreVertical, Clock,
  BookOpen, Trash2, Plus, FolderPlus, ChevronRight, Edit3, Sparkles
} from "lucide-react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs"
import { FlatCover, coverColorForBook } from "@/components/classics"
import { AchievementMoment } from "@/components/common/achievement-moment"
import type { AchievementData } from "@/lib/types/achievement"

// 模拟数据 - 书架书籍
const bookshelfData = [
  { id: "1", title: "周易", author: "伏羲", dynasty: "周", progress: 32, hasAI: true, hasTranslation: true, lastReadAt: "2024-01-15", coverColor: "cream" as const },
  { id: "2", title: "道德经", author: "老子", dynasty: "春秋", progress: 68, hasAI: true, hasTranslation: true, lastReadAt: "2024-01-14", coverColor: "brown" as const },
  { id: "3", title: "黄帝内经", author: "佚名", dynasty: "战国", progress: 15, hasAI: true, hasTranslation: true, lastReadAt: "2024-01-13", coverColor: "blue" as const },
  { id: "4", title: "论语", author: "孔子门人", dynasty: "春秋", progress: 45, hasAI: true, hasTranslation: true, lastReadAt: "2024-01-12", coverColor: "green" as const },
  { id: "5", title: "滴天髓", author: "刘基", dynasty: "明", progress: 8, hasAI: true, hasTranslation: true, lastReadAt: "2024-01-10", coverColor: "gray" as const },
  { id: "6", title: "大学", author: "曾子", dynasty: "战国", progress: 100, hasAI: true, hasTranslation: true, lastReadAt: "2024-01-09", coverColor: "brown" as const },
]

// 读完古籍 → 读后小结成就数据
function buildSummaryData(book: { title: string; author: string; dynasty: string }): AchievementData {
  return {
    type: "summary",
    userName: "林清欢",
    subject: book.title,
    date: "2026-06-15",
    stats: [
      { label: "阅读时长", value: "9h" },
      { label: "阅读天数", value: "14天" },
      { label: "划线笔记", value: "32" },
    ],
    aiComment: `读完《${book.title}》，[${book.dynasty}] ${book.author}之作，受益匪浅，余味悠长。`,
  }
}

// 模拟数据 - 阅读历史
const readingHistoryData = [
  { id: "1", title: "周易", author: "伏羲", dynasty: "周", chapter: "乾卦", readAt: "今天 14:30", coverColor: "cream" as const },
  { id: "2", title: "道德经", author: "老子", dynasty: "春秋", chapter: "第四十二章", readAt: "昨天 20:15", coverColor: "brown" as const },
  { id: "3", title: "论语", author: "孔子门人", dynasty: "春秋", chapter: "学而篇", readAt: "3天前", coverColor: "green" as const },
]

// 模拟数据 - 分组
const groupsData = [
  { id: "1", name: "命理研究", count: 5, color: "amber" },
  { id: "2", name: "道家经典", count: 3, color: "emerald" },
  { id: "3", name: "养生必读", count: 4, color: "blue" },
]

// 书架平面书封 - 与古籍馆整体风格统一，含阅读进度
function BookshelfCover({ book, onSummary }: { book: { title: string; author: string; dynasty: string; progress: number; hasAI?: boolean }; onSummary?: () => void }) {
  const finished = book.progress >= 100
  return (
    <div>
      <div className="relative">
        <FlatCover
          title={book.title}
          label={book.dynasty}
          coverColor={coverColorForBook(book.title)}
          className="w-full shadow-md"
          titleClassName="text-base"
        />
        {book.hasAI && (
          <span className="absolute top-1.5 left-1.5 text-[9px] font-medium px-1.5 py-0.5 rounded-md bg-black/30 text-white backdrop-blur-sm">
            AI
          </span>
        )}
        {finished && (
          <span className="absolute top-1.5 right-1.5 text-[9px] font-medium px-1.5 py-0.5 rounded-md bg-[#c41e3a] text-white">
            已读完
          </span>
        )}
      </div>
      <p className="mt-1.5 text-[13px] font-medium text-foreground truncate">{book.title}</p>
      {finished ? (
        <button
          onClick={(e) => {
            e.preventDefault()
            e.stopPropagation()
            onSummary?.()
          }}
          className="mt-1 flex w-full items-center justify-center gap-1 rounded-md py-1 text-[11px] font-medium"
          style={{ background: "#c9a96e1f", color: "#8a6d2f" }}
        >
          <Sparkles className="w-3 h-3" />
          读后小结
        </button>
      ) : book.progress > 0 ? (
        <div className="mt-1 flex items-center gap-1.5">
          <div className="flex-1 h-1 rounded-full bg-muted overflow-hidden">
            <div className="h-full bg-[#c41e3a] dark:bg-amber-500 rounded-full" style={{ width: `${Math.min(book.progress, 100)}%` }} />
          </div>
          <span className="text-[10px] text-muted-foreground tabular-nums">{book.progress}%</span>
        </div>
      ) : null}
    </div>
  )
}

export default function BookshelfPage() {
  const router = useRouter()
  const [searchValue, setSearchValue] = useState("")
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid")
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [isSelectMode, setIsSelectMode] = useState(false)
  const [books, setBooks] = useState(bookshelfData)
  const [activeGroup, setActiveGroup] = useState<string | null>(null)
  const [summaryBook, setSummaryBook] = useState<AchievementData | null>(null)

  const filteredBooks = books.filter(book =>
    book.title.includes(searchValue) ||
    book.author.includes(searchValue)
  )

  const handleRemoveFromShelf = useCallback((id: string) => {
    setBooks(prev => prev.filter(book => book.id !== id))
  }, [])

  const handleBatchRemove = useCallback(() => {
    setBooks(prev => prev.filter(book => !selectedIds.has(book.id)))
    setSelectedIds(new Set())
    setIsSelectMode(false)
  }, [selectedIds])

  const handleToggleSelect = useCallback((id: string) => {
    setSelectedIds(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }, [])

  const colorClasses: Record<string, string> = {
    amber: "bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300",
    emerald: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300",
    blue: "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300",
  }

  return (
    <div className="min-h-screen bg-background pb-6">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background border-b border-border/60">
        <div className="flex items-center justify-between px-4 h-14">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => router.back()}
              className="w-8 h-8 rounded-full flex items-center justify-center text-muted-foreground hover:bg-secondary"
              aria-label="返回"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <h1 className="font-medium">我的书房</h1>
          </div>
          
          <div className="flex items-center gap-2">
            {isSelectMode ? (
              <>
                <Button 
                  variant="ghost" 
                  size="sm"
                  onClick={() => {
                    setIsSelectMode(false)
                    setSelectedIds(new Set())
                  }}
                >
                  取消
                </Button>
                <Button 
                  variant="destructive" 
                  size="sm"
                  onClick={handleBatchRemove}
                  disabled={selectedIds.size === 0}
                >
                  移除 ({selectedIds.size})
                </Button>
              </>
            ) : (
              <>
                <Link href="/classics/search">
                  <Button variant="ghost" size="icon" className="w-8 h-8">
                    <Search className="w-4 h-4" />
                  </Button>
                </Link>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon" className="w-8 h-8">
                      <MoreVertical className="w-4 h-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem onClick={() => setIsSelectMode(true)}>
                      批量管理
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <FolderPlus className="w-4 h-4 mr-2" />
                      新建分组
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </>
            )}
          </div>
        </div>
      </header>

      {/* 标签页 */}
      <Tabs defaultValue="shelf" className="w-full">
        <div className="px-4 pt-3 pb-2 border-b border-border/60">
          <TabsList className="w-full bg-secondary/50 p-0.5 h-9">
            <TabsTrigger value="shelf" className="flex-1 text-xs h-8">
              书架
            </TabsTrigger>
            <TabsTrigger value="history" className="flex-1 text-xs h-8">
              浏览历史
            </TabsTrigger>
          </TabsList>
        </div>

        {/* 书架 */}
        <TabsContent value="shelf" className="mt-0">
          {/* 分组筛选 */}
          <div className="px-4 py-3 flex items-center gap-2 overflow-x-auto scrollbar-hide">
            <button
              onClick={() => setActiveGroup(null)}
              className={cn(
                "px-3 py-1.5 rounded-full text-xs whitespace-nowrap transition-colors",
                activeGroup === null 
                  ? "bg-primary text-primary-foreground" 
                  : "bg-secondary text-muted-foreground"
              )}
            >
              全部
            </button>
            {groupsData.map(group => (
              <button
                key={group.id}
                onClick={() => setActiveGroup(group.id)}
                className={cn(
                  "px-3 py-1.5 rounded-full text-xs whitespace-nowrap transition-colors flex items-center gap-1",
                  activeGroup === group.id 
                    ? colorClasses[group.color]
                    : "bg-secondary text-muted-foreground"
                )}
              >
                {group.name}
                <Badge variant="secondary" className="text-[9px] px-1 py-0 h-4 ml-0.5">
                  {group.count}
                </Badge>
              </button>
            ))}
            <button className="p-1.5 rounded-full bg-secondary text-muted-foreground hover:bg-secondary/80 transition-colors">
              <Plus className="w-4 h-4" />
            </button>
          </div>

          {/* 视图切换 */}
          <div className="px-4 pb-3 flex items-center justify-between">
            <p className="text-xs text-muted-foreground">
              共 <span className="text-foreground font-medium">{filteredBooks.length}</span> 本
            </p>
            <div className="flex items-center gap-1">
              <button 
                onClick={() => setViewMode("grid")}
                className={cn("p-1.5 rounded", viewMode === "grid" ? "bg-secondary" : "")}
                aria-label="网格视图"
              >
                <Grid3X3 className="w-4 h-4" />
              </button>
              <button 
                onClick={() => setViewMode("list")}
                className={cn("p-1.5 rounded", viewMode === "list" ? "bg-secondary" : "")}
                aria-label="列表视图"
              >
                <List className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* 书籍列表 */}
          <div className="px-4">
            {filteredBooks.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <div className="w-20 h-20 rounded-full bg-secondary flex items-center justify-center mb-4">
                  <BookOpen className="w-8 h-8 text-muted-foreground" />
                </div>
                <h3 className="font-medium mb-1">书架是空的</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  去古籍馆探索感兴趣的古籍吧
                </p>
                <Link href="/classics/home">
                  <Button className="rounded-full">
                    探索古籍
                  </Button>
                </Link>
              </div>
            ) : viewMode === "grid" ? (
              <div className="grid grid-cols-3 gap-3">
                {filteredBooks.map((book) => (
                  <div 
                    key={book.id} 
                    className={cn(
                      "relative",
                      isSelectMode && "cursor-pointer",
                      selectedIds.has(book.id) && "ring-2 ring-primary rounded-lg"
                    )}
                    onClick={() => isSelectMode && handleToggleSelect(book.id)}
                  >
                    {isSelectMode ? (
                      <BookshelfCover book={book} />
                    ) : (
                      <Link href={`/classics/${book.id}`} className="block">
                        <BookshelfCover book={book} onSummary={() => setSummaryBook(buildSummaryData(book))} />
                      </Link>
                    )}
                    {isSelectMode && selectedIds.has(book.id) && (
                      <div className="absolute top-1.5 right-1.5 w-5 h-5 rounded-full bg-primary flex items-center justify-center shadow">
                        <span className="text-[10px] text-white">✓</span>
                      </div>
                    )}
                  </div>
                ))}
                {/* 添加更多 - 实心卡片 */}
                <Link href="/classics/home" className="block">
                  <div className="aspect-[3/4] rounded-2xl bg-muted/60 flex flex-col items-center justify-center gap-1.5 text-muted-foreground active:scale-[0.98] transition-transform">
                    <Plus className="w-6 h-6" />
                    <span className="text-xs">添加</span>
                  </div>
                </Link>
              </div>
            ) : (
              <div className="space-y-3">
                {filteredBooks.map((book) => (
                  <Card 
                    key={book.id}
                    className={cn(
                      "p-3 flex items-center gap-3 transition-all",
                      isSelectMode && "cursor-pointer",
                      selectedIds.has(book.id) && "ring-2 ring-primary"
                    )}
                    onClick={() => isSelectMode && handleToggleSelect(book.id)}
                  >
                    {/* 小封面 */}
                    <div className={cn(
                      "w-12 h-16 rounded-sm flex-shrink-0 flex items-center justify-center",
                      "bg-[#f5f0e1] border border-[#c9b896]/50 shadow-sm"
                    )}>
                      <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-[#d4c4a8] rounded-l-sm" />
                      <span className="writing-vertical-rl text-[9px] font-serif font-bold text-[#4a3f2f]">
                        {book.title.slice(0, 3)}
                      </span>
                    </div>
                    
                    {/* 信息 */}
                    <div className="flex-1 min-w-0">
                      <Link 
                        href={`/classics/${book.id}`}
                        className="font-medium text-sm hover:text-primary transition-colors"
                        onClick={e => isSelectMode && e.preventDefault()}
                      >
                        {book.title}
                      </Link>
                      <p className="text-xs text-muted-foreground">[{book.dynasty}] {book.author}</p>
                      <div className="flex items-center gap-2 mt-1">
                        <div className="flex-1 h-1 bg-secondary rounded-full overflow-hidden">
                          <div 
                            className="h-full bg-primary/70 rounded-full"
                            style={{ width: `${book.progress}%` }}
                          />
                        </div>
                        <span className="text-[10px] text-muted-foreground">{book.progress}%</span>
                      </div>
                    </div>
                    
                    {/* 操作 */}
                    {!isSelectMode && (
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="w-8 h-8 flex-shrink-0">
                            <MoreVertical className="w-4 h-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem>
                            <BookOpen className="w-4 h-4 mr-2" />
                            继续阅读
                          </DropdownMenuItem>
                          <DropdownMenuItem>
                            <Edit3 className="w-4 h-4 mr-2" />
                            移动分组
                          </DropdownMenuItem>
                          <DropdownMenuItem 
                            className="text-destructive"
                            onClick={() => handleRemoveFromShelf(book.id)}
                          >
                            <Trash2 className="w-4 h-4 mr-2" />
                            移出书架
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    )}
                  </Card>
                ))}
              </div>
            )}
          </div>
        </TabsContent>

        {/* 浏览历史 */}
        <TabsContent value="history" className="mt-0 p-4">
          <div className="space-y-3">
            {readingHistoryData.map((item) => (
              <Link key={item.id} href={`/reader/${item.id}`}>
                <Card className="p-3 flex items-center gap-3 hover:shadow-md transition-shadow">
                  {/* 小封面 */}
                  <div className={cn(
                    "w-10 h-14 rounded-sm flex-shrink-0 flex items-center justify-center relative",
                    "bg-[#f5f0e1] border border-[#c9b896]/50 shadow-sm"
                  )}>
                    <div className="absolute left-0 top-0 bottom-0 w-1 bg-[#d4c4a8] rounded-l-sm" />
                    <span className="writing-vertical-rl text-[8px] font-serif font-bold text-[#4a3f2f]">
                      {item.title.slice(0, 2)}
                    </span>
                  </div>
                  
                  {/* 信息 */}
                  <div className="flex-1 min-w-0">
                    <h3 className="font-medium text-sm">{item.title}</h3>
                    <p className="text-xs text-muted-foreground">{item.chapter}</p>
                  </div>
                  
                  {/* 时间 */}
                  <div className="flex items-center gap-1 text-xs text-muted-foreground flex-shrink-0">
                    <Clock className="w-3 h-3" />
                    {item.readAt}
                  </div>
                </Card>
              </Link>
            ))}
            
            {readingHistoryData.length > 0 && (
              <Button variant="ghost" className="w-full text-muted-foreground text-xs">
                清空历史记录
              </Button>
            )}
          </div>
        </TabsContent>
      </Tabs>

      <AchievementMoment
        open={summaryBook !== null}
        data={summaryBook || buildSummaryData({ title: "", author: "", dynasty: "" })}
        onClose={() => setSummaryBook(null)}
        continueLabel="继续探索古籍"
        editableComment
      />
    </div>
  )
}
