// app/classics/home/page.tsx
"use client"

import { useState, useCallback } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { cn } from "@/lib/utils"
import {
  ArrowLeft, Search, ChevronRight,
  Headphones, Play, ScrollText, BookOpen, Lightbulb, PenLine,
  Flame, Sparkles,
} from "lucide-react"
import { FlatCover, TypeFilter, coverColorForBook, type CoverColor } from "@/components/classics"

// 馆藏概览
const libraryStats = [
  { value: "12,860", label: "部典籍" },
  { value: "48", label: "门类" },
  { value: "1,200+", label: "白话译注" },
]

// 四库分类 - 苹果风彩色瓷砖
const categories = [
  { id: "jing", name: "经部", desc: "儒家经典", count: "3,210 部", icon: ScrollText, from: "#a06a38", to: "#7a4d22" },
  { id: "shi", name: "史部", desc: "历史典籍", count: "2,680 部", icon: BookOpen, from: "#3a6196", to: "#243f63" },
  { id: "zi", name: "子部", desc: "诸子百家", count: "4,150 部", icon: Lightbulb, from: "#3f8560", to: "#27543b" },
  { id: "ji", name: "集部", desc: "诗词文集", count: "2,820 部", icon: PenLine, from: "#9a4f6b", to: "#6e3147" },
]

// 今日导读 - App Store「今日」式大卡
const todayFeature = {
  id: "2",
  title: "道德经",
  author: "老子 · 春秋",
  coverColor: "brown" as CoverColor,
  tagline: "今日导读",
  quote: "道可道，非常道；名可名，非常名。",
  desc: "五千言道尽天地至理，读懂中国人的处世智慧。",
}

// 继续阅读
const lastReading = { id: "2", title: "道德经", author: "老子", progress: 68, coverColor: "brown" as CoverColor }
const weeklyMinutes = 127

// 专题书单
const bookLists = [
  { id: "1", title: "国学经典必读", desc: "入门必备，经典永流传", count: 12, color: "red" as CoverColor, books: [
    { title: "周易", color: "cream" as CoverColor }, { title: "论语", color: "brown" as CoverColor },
    { title: "道德经", color: "green" as CoverColor },
  ] },
  { id: "2", title: "命理入门书单", desc: "八字命理学习路径", count: 8, color: "blue" as CoverColor, books: [
    { title: "滴天髓", color: "gray" as CoverColor }, { title: "子平真诠", color: "blue" as CoverColor },
    { title: "穷通宝鉴", color: "brown" as CoverColor },
  ] },
  { id: "3", title: "道家养生典籍", desc: "修身养性，道法自然", count: 10, color: "green" as CoverColor, books: [
    { title: "道德经", color: "green" as CoverColor }, { title: "庄子", color: "cream" as CoverColor },
    { title: "抱朴子", color: "brown" as CoverColor },
  ] },
]

// 推荐榜
const rankingData = [
  { id: "1", title: "周易", author: "伏羲", dynasty: "周", desc: "群经之首，大道之源", reads: 128600, coverColor: "cream" as CoverColor },
  { id: "2", title: "道德经", author: "老子", dynasty: "春秋", desc: "道法自然，无为而治", reads: 145600, coverColor: "brown" as CoverColor },
  { id: "3", title: "黄帝内经", author: "佚名", dynasty: "战国", desc: "中医奠基，养生之本", reads: 98500, coverColor: "green" as CoverColor },
  { id: "4", title: "论语", author: "孔门", dynasty: "春秋", desc: "仁义礼智，修身齐家", reads: 156800, coverColor: "red" as CoverColor },
  { id: "5", title: "鬼谷子", author: "鬼谷子", dynasty: "战国", desc: "纵横捭阖，谋略奇书", reads: 76200, coverColor: "gray" as CoverColor },
]

// 听书
const audioBooks = [
  { id: "1", title: "金瓶梅", narrator: "专业主播", desc: "明代四大奇书之首", coverColor: "cream" as CoverColor },
  { id: "2", title: "山海经", narrator: "古籍朗读", desc: "上古奇书，神话之源", coverColor: "blue" as CoverColor },
  { id: "3", title: "聊斋志异", narrator: "学术讲解", desc: "鬼狐有性格，笑骂成文", coverColor: "brown" as CoverColor },
]

// 精选古籍
const featuredBooks = [
  { id: "1", title: "周易", author: "伏羲 · 周", desc: "群经之首，大道之源", isFree: true, coverColor: "cream" as CoverColor },
  { id: "5", title: "黄帝内经", author: "佚名 · 战国", desc: "中医学奠基之作", isFree: true, coverColor: "green" as CoverColor },
  { id: "3", title: "滴天髓", author: "刘基 · 明", desc: "八字命理经典", isFree: false, coverColor: "gray" as CoverColor },
  { id: "6", title: "论语", author: "孔门 · 春秋", desc: "儒家经典核心", isFree: true, coverColor: "red" as CoverColor },
]

function fmtReads(n: number) {
  return n >= 10000 ? `${(n / 10000).toFixed(1)}万` : `${n}`
}

function SectionHeader({ title, sub, href, linkText = "查看全部" }: { title: string; sub?: string; href: string; linkText?: string }) {
  return (
    <div className="flex items-end justify-between px-5 sm:px-6 mb-3.5">
      <div>
        <h2 className="text-[22px] sm:text-2xl font-bold tracking-tight text-foreground">{title}</h2>
        {sub ? <p className="text-[13px] text-muted-foreground mt-0.5">{sub}</p> : null}
      </div>
      <Link href={href} className="text-[13px] text-[#c41e3a] dark:text-amber-400 flex items-center font-medium flex-shrink-0">
        {linkText}<ChevronRight className="w-4 h-4" />
      </Link>
    </div>
  )
}

export default function ClassicsHomePage() {
  const router = useRouter()
  const [activeType, setActiveType] = useState("all")
  const handleRefreshRanking = useCallback(() => {}, [])

  return (
    <div className="min-h-screen bg-[#f4f2ee] dark:bg-background pb-20 sm:pb-10">
      {/* 顶部导航 - 苹果式半透明 */}
      <header className="sticky top-0 z-50 bg-[#f4f2ee]/80 dark:bg-background/80 backdrop-blur-xl">
        <div className="flex items-center justify-between px-3 sm:px-6 h-12 sm:h-14 max-w-screen-xl mx-auto">
          <button
            onClick={() => router.back()}
            className="w-9 h-9 rounded-full flex items-center justify-center active:scale-90 transition-transform"
            aria-label="返回"
          >
            <ArrowLeft className="w-[22px] h-[22px] text-foreground" />
          </button>
          <h1 className="text-[17px] font-semibold tracking-tight text-foreground">古籍馆</h1>
          <Link
            href="/classics/search"
            className="w-9 h-9 rounded-full flex items-center justify-center active:scale-90 transition-transform"
            aria-label="搜索"
          >
            <Search className="w-[22px] h-[22px] text-foreground" />
          </Link>
        </div>
      </header>

      <main className="max-w-screen-xl mx-auto">
        {/* ===== Hero 大标题 ===== */}
        <section className="px-5 sm:px-6 pt-3 pb-5">
          <p className="text-[13px] font-semibold tracking-wide text-[#c41e3a] dark:text-amber-400 mb-1.5">中华典籍 · 经史子集</p>
          <h2 className="text-[40px] leading-[1.05] sm:text-6xl font-bold tracking-tight text-foreground text-balance">
            千年典籍，<br />尽收一馆
          </h2>
          {/* 规模数据 - 小字一行 */}
          <div className="mt-4 flex items-center gap-4 text-[13px] text-muted-foreground">
            {libraryStats.map((s, i) => (
              <span key={s.label} className="flex items-center gap-1.5">
                {i > 0 && <span className="w-1 h-1 rounded-full bg-muted-foreground/40" />}
                <span className="font-semibold text-foreground tabular-nums">{s.value}</span>{s.label}
              </span>
            ))}
          </div>
        </section>

        {/* ===== 搜索栏 ===== */}
        <section className="px-5 sm:px-6 pb-4">
          <Link
            href="/classics/search"
            className="flex items-center gap-2.5 w-full h-11 px-4 rounded-2xl bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform"
          >
            <Search className="w-[18px] h-[18px] text-muted-foreground" />
            <span className="text-[15px] text-muted-foreground">搜书名、作者、朝代或门类</span>
          </Link>
        </section>

        {/* ===== 今日导读 - App Store「今日」式大卡 ===== */}
        <section className="px-5 sm:px-6 pb-5">
          <Link href={`/classics/${todayFeature.id}`} className="block group">
            <div className="relative rounded-[28px] overflow-hidden shadow-lg ring-1 ring-black/5 active:scale-[0.99] transition-transform">
              {/* 渐变背景 */}
              <div className="absolute inset-0" style={{ background: "linear-gradient(155deg, #a06a38, #5f3a1a)" }} />
              <div className="relative p-6 sm:p-8 flex flex-col gap-5">
                <div>
                  <p className="text-[12px] font-semibold tracking-[0.2em] text-white/70 uppercase">{todayFeature.tagline}</p>
                  <p className="mt-3 font-serif text-2xl sm:text-3xl font-bold text-white leading-snug text-balance">
                    {todayFeature.quote}
                  </p>
                  <p className="mt-3 text-[14px] text-white/75 leading-relaxed max-w-sm">{todayFeature.desc}</p>
                </div>
                <div className="flex items-center gap-4">
                  <FlatCover
                    title={todayFeature.title}
                    label={todayFeature.author.split(" · ")[1]}
                    footer={todayFeature.author.split(" · ")[0]}
                    coverColor={coverColorForBook(todayFeature.title)}
                    className="w-[96px] flex-shrink-0 shadow-xl"
                    titleClassName="text-lg"
                  />
                  <div className="flex-1">
                    <p className="text-white font-semibold text-lg">{todayFeature.title}</p>
                    <p className="text-white/70 text-[13px] mt-0.5">{todayFeature.author}</p>
                    <span className="mt-3 inline-flex items-center gap-1.5 h-9 px-5 rounded-full bg-white text-[#6f4521] text-[14px] font-semibold shadow-sm">
                      <BookOpen className="w-4 h-4" />立即阅读
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </Link>
        </section>

        {/* ===== 继续阅读 - 纤细一条 ===== */}
        <section className="px-5 sm:px-6 pb-5">
          <Link href={`/classics/${lastReading.id}`} className="flex items-center gap-3 p-2.5 rounded-2xl bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform">
            <FlatCover title={lastReading.title} coverColor={coverColorForBook(lastReading.title)} className="w-11 flex-shrink-0" titleClassName="text-[11px]" />
            <div className="min-w-0 flex-1">
              <p className="text-[11px] text-muted-foreground">继续阅读</p>
              <p className="text-[15px] font-semibold truncate text-foreground">{lastReading.title}</p>
              <div className="mt-1.5 flex items-center gap-2">
                <div className="flex-1 h-1 rounded-full bg-muted overflow-hidden max-w-[140px]">
                  <div className="h-full bg-[#c41e3a] dark:bg-amber-400 rounded-full" style={{ width: `${lastReading.progress}%` }} />
                </div>
                <span className="text-[11px] text-[#c41e3a] dark:text-amber-400 font-semibold tabular-nums">{lastReading.progress}%</span>
              </div>
            </div>
            <div className="flex items-center gap-1.5 pl-3 ml-1 border-l border-border flex-shrink-0">
              <Flame className="w-4 h-4 text-[#e0894a]" />
              <div className="text-right">
                <p className="text-[10px] text-muted-foreground leading-none">本周</p>
                <p className="text-[13px] font-bold text-foreground tabular-nums leading-tight">{weeklyMinutes}<span className="font-normal text-muted-foreground text-[10px]">分</span></p>
              </div>
            </div>
          </Link>
        </section>

        {/* ===== 四库分类 - 彩色瓷砖 ===== */}
        <section className="px-5 sm:px-6 pb-6">
          <div className="grid grid-cols-2 gap-3">
            {categories.map((cat) => {
              const Icon = cat.icon
              return (
                <button
                  key={cat.id}
                  onClick={() => router.push(`/classics/category/${cat.id}`)}
                  className="relative h-[88px] rounded-3xl overflow-hidden p-4 flex flex-col justify-between text-left active:scale-[0.97] transition-transform shadow-sm ring-1 ring-black/5"
                  style={{ background: `linear-gradient(150deg, ${cat.from}, ${cat.to})` }}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-white font-bold text-lg tracking-wide">{cat.name}</span>
                    <Icon className="w-5 h-5 text-white/80" />
                  </div>
                  <div>
                    <p className="text-white/90 text-[12px] font-medium">{cat.desc}</p>
                    <p className="text-white/60 text-[11px] tabular-nums">{cat.count}</p>
                  </div>
                </button>
              )
            })}
          </div>
        </section>

        {/* ===== 经典书单 ===== */}
        <section className="pb-6">
          <SectionHeader title="经典书单" sub="名家精选，循路而读" href="/classics/lists" linkText="全部书单" />
          <div className="flex gap-4 overflow-x-auto scrollbar-hide pb-2 px-5 sm:px-6">
            {bookLists.map((list) => (
              <Link key={list.id} href={`/classics/collection/${list.id}`} className="flex-shrink-0 w-[260px] group">
                <div className="rounded-3xl p-5 bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform h-full">
                  <h3 className="font-bold text-[17px] text-foreground">{list.title}</h3>
                  <p className="text-[12px] text-muted-foreground mt-0.5 mb-4">{list.desc} · {list.count} 本</p>
                  <div className="flex items-end gap-2.5">
                    {list.books.map((b, i) => (
                      <FlatCover
                        key={i}
                        title={b.title}
                        coverColor={coverColorForBook(b.title)}
                        className="flex-1 transition-transform group-hover:-translate-y-0.5"
                        titleClassName="text-sm"
                      />
                    ))}
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* ===== 推荐榜 - Apple Books 排行榜式清单 ===== */}
        <section className="pb-6">
          <SectionHeader title="推荐榜" sub="读者公认的传世经典" href="/classics/ranking" linkText="完整榜单" />
          <div className="px-5 sm:px-6 mb-3">
            <TypeFilter activeType={activeType} onTypeChange={setActiveType} />
          </div>
          <div className="px-5 sm:px-6">
            <div className="rounded-3xl bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 overflow-hidden">
              {rankingData.map((book, index) => (
                <Link
                  key={book.id}
                  href={`/classics/${book.id}`}
                  className={cn(
                    "flex items-center gap-3.5 p-3 active:bg-muted/50 transition-colors",
                    index > 0 && "border-t border-border/60",
                  )}
                >
                  <span className={cn(
                    "w-6 text-center font-bold text-lg tabular-nums flex-shrink-0",
                    index < 3 ? "text-[#c41e3a] dark:text-amber-400" : "text-muted-foreground",
                  )}>
                    {index + 1}
                  </span>
                  <FlatCover title={book.title} coverColor={coverColorForBook(book.title)} className="w-14 flex-shrink-0" titleClassName="text-xs" />
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-[15px] text-foreground truncate">{book.title}</p>
                    <p className="text-[12px] text-muted-foreground truncate mt-0.5">{book.desc}</p>
                    <p className="text-[11px] text-muted-foreground/70 mt-0.5">{book.author} · {book.dynasty} · {fmtReads(book.reads)}人读</p>
                  </div>
                  <ChevronRight className="w-5 h-5 text-muted-foreground/40 flex-shrink-0" />
                </Link>
              ))}
            </div>
            <button
              onClick={handleRefreshRanking}
              className="w-full mt-3 py-2.5 text-[14px] font-medium text-muted-foreground bg-card rounded-2xl shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform"
            >
              换一批
            </button>
          </div>
        </section>

        {/* ===== 听书 ===== */}
        <section className="pb-6">
          <SectionHeader title="听书" sub="轻松听，不啃厚书" href="/classics/audiobooks" linkText="更多" />
          <div className="flex gap-3 overflow-x-auto scrollbar-hide pb-2 px-5 sm:px-6">
            {audioBooks.map((book) => (
              <Link key={book.id} href={`/classics/audiobooks/${book.id}`} className="flex-shrink-0 w-[240px]">
                <div className="flex gap-3 p-3 bg-card rounded-2xl shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform">
                  <FlatCover title={book.title} coverColor={coverColorForBook(book.title)} className="w-14 flex-shrink-0" titleClassName="text-xs" />
                  <div className="flex-1 min-w-0 flex flex-col justify-between py-0.5">
                    <div>
                      <h3 className="font-semibold text-[15px] text-foreground truncate">{book.title}</h3>
                      <p className="text-[12px] text-muted-foreground line-clamp-2 mt-0.5 leading-relaxed">{book.desc}</p>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-[11px] text-muted-foreground">{book.narrator}</span>
                      <span className="w-8 h-8 rounded-full bg-[#c41e3a] dark:bg-amber-500 flex items-center justify-center shadow-sm">
                        <Play className="w-3.5 h-3.5 text-white ml-0.5" fill="white" />
                      </span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* ===== 精选古籍 ===== */}
        <section className="pb-6">
          <SectionHeader title="精选古籍" sub="编辑甄选，值得细读" href="/classics/lists" linkText="更多" />
          <div className="px-5 sm:px-6 grid grid-cols-1 sm:grid-cols-2 gap-3">
            {featuredBooks.map((book) => (
              <Link key={book.id} href={`/classics/${book.id}`} className="flex gap-4 p-4 bg-card rounded-2xl shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform">
                <FlatCover title={book.title} coverColor={coverColorForBook(book.title)} className="w-16 flex-shrink-0" titleClassName="text-sm" />
                <div className="flex-1 min-w-0 flex flex-col justify-between py-0.5">
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="font-semibold text-[16px] text-foreground">{book.title}</h3>
                      {book.isFree && (
                        <span className="text-[10px] font-medium px-1.5 py-0.5 rounded-md bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-400">免费</span>
                      )}
                    </div>
                    <p className="text-[12px] text-muted-foreground mt-1 line-clamp-2 leading-relaxed">{book.desc}</p>
                  </div>
                  <p className="text-[11px] text-muted-foreground/70">{book.author}</p>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* ===== 底部 AI 入口（仅引导，AI 辅助阅读在阅读器内） ===== */}
        <section className="px-5 sm:px-6 pb-4">
          <Link href="/classics/ai-assistant" className="flex items-center gap-3 p-4 rounded-2xl bg-card shadow-sm ring-1 ring-black/[0.04] dark:ring-white/5 active:scale-[0.99] transition-transform">
            <span className="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: "linear-gradient(150deg, #c8324c, #9e1b30)" }}>
              <Sparkles className="w-5 h-5 text-white" />
            </span>
            <div className="flex-1 min-w-0">
              <p className="font-semibold text-[15px] text-foreground">AI 国学助手</p>
              <p className="text-[12px] text-muted-foreground mt-0.5">不懂就问，白话解读古籍疑难</p>
            </div>
            <ChevronRight className="w-5 h-5 text-muted-foreground/40" />
          </Link>
        </section>
      </main>
    </div>
  )
}

// apps/mobile/src/pkg-classics/home/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import FlatCover from '@/components/classics/flat-cover.vue'
import { coverColorForBook } from '@/lib/classics-cover'
import {
  libraryStats, categories, todayFeature, lastReading, weeklyMinutes,
  bookLists, rankingData, audioBooks, featuredBooks, filterTypes, fmtReads,
} from '@/lib/classics-data'

const activeType = ref('all')

function goSearch() {
  uni.navigateTo({ url: '/pkg-classics/search/index' })
}
function goDetail(id: string) {
  uni.navigateTo({ url: `/pkg-classics/detail/index?id=${id}` })
}
function goCategory(cat: string) {
  uni.navigateTo({ url: `/pkg-classics/category/index?cat=${cat}` })
}
function goCollection(id: string) {
  uni.navigateTo({ url: `/pkg-classics/collection/index?id=${id}` })
}
function goAudioList() {
  uni.navigateTo({ url: '/pkg-classics/audiobooks/index' })
}
function goAudio(id: string) {
  uni.navigateTo({ url: `/pkg-classics/audiobooks/index?id=${id}` })
}
function goLists() {
  uni.navigateTo({ url: '/pkg-classics/lists/index' })
}
function goRanking() {
  uni.navigateTo({ url: '/pkg-classics/ranking/index' })
}
function goAI() {
  uni.navigateTo({ url: '/pkg-classics/ai-assistant/index' })
}
function goBack() {
  const pages = getCurrentPages()
  if (pages.length > 1) uni.navigateBack()
  else uni.switchTab?.({ url: '/pages/home/index' }).catch?.(() => {})
}
function onRefreshRanking() {}
</script>

<template>
  <view class="ch-page">
    <!-- 顶部导航 - 苹果式半透明 -->
    <view class="ch-topbar">
      <view class="ch-statusbar" />
      <view class="ch-topbar-inner">
        <view
          class="ch-circle-btn"
          @tap="goBack"
        >
          <app-icon
            name="arrow-left"
            :size="44"
            color="#2c2c2c"
          />
        </view>
        <text class="ch-topbar-title">
          古籍馆
        </text>
        <view
          class="ch-circle-btn"
          @tap="goSearch"
        >
          <app-icon
            name="search"
            :size="44"
            color="#2c2c2c"
          />
        </view>
      </view>
    </view>

    <view class="ch-main">
      <!-- Hero 大标题 -->
      <view class="ch-hero">
        <text class="ch-hero-kicker">
          中华典籍 · 经史子集
        </text>
        <text class="ch-hero-title">
          千年典籍，尽收一馆
        </text>
        <view class="ch-hero-stats">
          <view
            v-for="(s, i) in libraryStats"
            :key="s.label"
            class="ch-stat"
          >
            <view
              v-if="i > 0"
              class="ch-stat-dot"
            />
            <text class="ch-stat-val">
              {{ s.value }}
            </text>
            <text class="ch-stat-label">
              {{ s.label }}
            </text>
          </view>
        </view>
      </view>

      <!-- 搜索栏 -->
      <view class="ch-sec">
        <view
          class="ch-searchbar"
          @tap="goSearch"
        >
          <app-icon
            name="search"
            :size="36"
            color="#999999"
          />
          <text class="ch-search-ph">
            搜书名、作者、朝代或门类
          </text>
        </view>
      </view>

      <!-- 今日导读 -->
      <view class="ch-sec">
        <view
          class="ch-today"
          @tap="goDetail(todayFeature.id)"
        >
          <view class="ch-today-bg" />
          <view class="ch-today-inner">
            <view>
              <text class="ch-today-tag">
                {{ todayFeature.tagline }}
              </text>
              <text class="ch-today-quote">
                {{ todayFeature.quote }}
              </text>
              <text class="ch-today-desc">
                {{ todayFeature.desc }}
              </text>
            </view>
            <view class="ch-today-foot">
              <FlatCover
                :title="todayFeature.title"
                :label="todayFeature.author.split(' · ')[1]"
                :footer="todayFeature.author.split(' · ')[0]"
                :cover-color="coverColorForBook(todayFeature.title)"
                title-size="36rpx"
                class="ch-today-cover"
              />
              <view class="ch-today-meta">
                <text class="ch-today-name">
                  {{ todayFeature.title }}
                </text>
                <text class="ch-today-author">
                  {{ todayFeature.author }}
                </text>
                <view class="ch-today-btn">
                  <app-icon
                    name="book-open"
                    :size="32"
                    color="#6f4521"
                  />
                  <text class="ch-today-btn-txt">
                    立即阅读
                  </text>
                </view>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 继续阅读 -->
      <view class="ch-sec">
        <view
          class="ch-continue"
          @tap="goDetail(lastReading.id)"
        >
          <FlatCover
            :title="lastReading.title"
            :cover-color="coverColorForBook(lastReading.title)"
            title-size="22rpx"
            class="ch-continue-cover"
          />
          <view class="ch-continue-info">
            <text class="ch-continue-label">
              继续阅读
            </text>
            <text class="ch-continue-title">
              {{ lastReading.title }}
            </text>
            <view class="ch-continue-prog">
              <view class="ch-prog-track">
                <view
                  class="ch-prog-fill"
                  :style="{ width: lastReading.progress + '%' }"
                />
              </view>
              <text class="ch-prog-pct">
                {{ lastReading.progress }}%
              </text>
            </view>
          </view>
          <view class="ch-continue-week">
            <app-icon
              name="flame"
              :size="32"
              color="#e0894a"
            />
            <view class="ch-week-meta">
              <text class="ch-week-label">
                本周
              </text>
              <text class="ch-week-num">
                {{ weeklyMinutes }}<text class="ch-week-unit">
                  分
                </text>
              </text>
            </view>
          </view>
        </view>
      </view>

      <!-- 四库分类 - 彩色瓷砖 -->
      <view class="ch-sec">
        <view class="ch-cat-grid">
          <view
            v-for="cat in categories"
            :key="cat.id"
            class="ch-cat-tile"
            :style="{ background: `linear-gradient(150deg, ${cat.from}, ${cat.to})` }"
            @tap="goCategory(cat.id)"
          >
            <view class="ch-cat-top">
              <text class="ch-cat-name">
                {{ cat.name }}
              </text>
              <app-icon
                :name="cat.icon"
                :size="40"
                color="rgba(255,255,255,0.8)"
              />
            </view>
            <view>
              <text class="ch-cat-desc">
                {{ cat.desc }}
              </text>
              <text class="ch-cat-count">
                {{ cat.count }}
              </text>
            </view>
          </view>
        </view>
      </view>

      <!-- 经典书单 -->
      <view class="ch-block">
        <view class="ch-sec-head">
          <view>
            <text class="ch-sec-title">
              经典书单
            </text>
            <text class="ch-sec-sub">
              名家精选，循路而读
            </text>
          </view>
          <view
            class="ch-sec-link"
            @tap="goLists"
          >
            <text class="ch-sec-link-txt">
              全部书单
            </text>
            <app-icon
              name="chevron-right"
              :size="28"
              color="#c41e3a"
            />
          </view>
        </view>
        <scroll-view
          scroll-x
          class="ch-hscroll"
          :show-scrollbar="false"
        >
          <view class="ch-hscroll-row">
            <view
              v-for="list in bookLists"
              :key="list.id"
              class="ch-list-card"
              @tap="goCollection(list.id)"
            >
              <text class="ch-list-title">
                {{ list.title }}
              </text>
              <text class="ch-list-desc">
                {{ list.desc }} · {{ list.count }} 本
              </text>
              <view class="ch-list-covers">
                <FlatCover
                  v-for="(b, i) in list.books"
                  :key="i"
                  :title="b.title"
                  :cover-color="coverColorForBook(b.title)"
                  title-size="28rpx"
                  class="ch-list-cover"
                />
              </view>
            </view>
          </view>
        </scroll-view>
      </view>

      <!-- 推荐榜 -->
      <view class="ch-block">
        <view class="ch-sec-head">
          <view>
            <text class="ch-sec-title">
              推荐榜
            </text>
            <text class="ch-sec-sub">
              读者公认的传世经典
            </text>
          </view>
          <view
            class="ch-sec-link"
            @tap="goRanking"
          >
            <text class="ch-sec-link-txt">
              完整榜单
            </text>
            <app-icon
              name="chevron-right"
              :size="28"
              color="#c41e3a"
            />
          </view>
        </view>
        <scroll-view
          scroll-x
          class="ch-type-scroll"
          :show-scrollbar="false"
        >
          <view class="ch-type-row">
            <view
              v-for="t in filterTypes"
              :key="t.id"
              class="ch-type-chip"
              :class="{ 'ch-type-chip--on': activeType === t.id }"
              @tap="activeType = t.id"
            >
              {{ t.name }}
            </view>
          </view>
        </scroll-view>
        <view class="ch-sec-pad">
          <view class="ch-rank-card">
            <view
              v-for="(book, index) in rankingData"
              :key="book.id"
              class="ch-rank-row"
              :class="{ 'ch-rank-row--border': index > 0 }"
              @tap="goDetail(book.id)"
            >
              <text
                class="ch-rank-num"
                :class="{ 'ch-rank-num--top': index < 3 }"
              >
                {{ index + 1 }}
              </text>
              <FlatCover
                :title="book.title"
                :cover-color="coverColorForBook(book.title)"
                title-size="24rpx"
                class="ch-rank-cover"
              />
              <view class="ch-rank-info">
                <text class="ch-rank-title">
                  {{ book.title }}
                </text>
                <text class="ch-rank-desc">
                  {{ book.desc }}
                </text>
                <text class="ch-rank-meta">
                  {{ book.author }} · {{ book.dynasty }} · {{ fmtReads(book.reads) }}人读
                </text>
              </view>
              <app-icon
                name="chevron-right"
                :size="36"
                color="rgba(0,0,0,0.2)"
              />
            </view>
          </view>
          <view
            class="ch-refresh"
            @tap="onRefreshRanking"
          >
            换一批
          </view>
        </view>
      </view>

      <!-- 听书 -->
      <view class="ch-block">
        <view class="ch-sec-head">
          <view>
            <text class="ch-sec-title">
              听书
            </text>
            <text class="ch-sec-sub">
              轻松听，不啃厚书
            </text>
          </view>
          <view
            class="ch-sec-link"
            @tap="goAudioList"
          >
            <text class="ch-sec-link-txt">
              更多
            </text>
            <app-icon
              name="chevron-right"
              :size="28"
              color="#c41e3a"
            />
          </view>
        </view>
        <scroll-view
          scroll-x
          class="ch-hscroll"
          :show-scrollbar="false"
        >
          <view class="ch-hscroll-row">
            <view
              v-for="book in audioBooks"
              :key="book.id"
              class="ch-audio-card"
              @tap="goAudio(book.id)"
            >
              <FlatCover
                :title="book.title"
                :cover-color="coverColorForBook(book.title)"
                title-size="24rpx"
                class="ch-audio-cover"
              />
              <view class="ch-audio-info">
                <view>
                  <text class="ch-audio-title">
                    {{ book.title }}
                  </text>
                  <text class="ch-audio-desc">
                    {{ book.desc }}
                  </text>
                </view>
                <view class="ch-audio-foot">
                  <text class="ch-audio-narrator">
                    {{ book.narrator }}
                  </text>
                  <view class="ch-audio-play">
                    <app-icon
                      name="play"
                      :size="28"
                      color="#fff"
                      :fill="true"
                    />
                  </view>
                </view>
              </view>
            </view>
          </view>
        </scroll-view>
      </view>

      <!-- 精选古籍 -->
      <view class="ch-block">
        <view class="ch-sec-head">
          <view>
            <text class="ch-sec-title">
              精选古籍
            </text>
            <text class="ch-sec-sub">
              编辑甄选，值得细读
            </text>
          </view>
          <view
            class="ch-sec-link"
            @tap="goLists"
          >
            <text class="ch-sec-link-txt">
              更多
            </text>
            <app-icon
              name="chevron-right"
              :size="28"
              color="#c41e3a"
            />
          </view>
        </view>
        <view class="ch-sec-pad ch-featured-grid">
          <view
            v-for="book in featuredBooks"
            :key="book.id"
            class="ch-featured-card"
            @tap="goDetail(book.id)"
          >
            <FlatCover
              :title="book.title"
              :cover-color="coverColorForBook(book.title)"
              title-size="28rpx"
              class="ch-featured-cover"
            />
            <view class="ch-featured-info">
              <view>
                <view class="ch-featured-titlerow">
                  <text class="ch-featured-title">
                    {{ book.title }}
                  </text>
                  <text
                    v-if="book.isFree"
                    class="ch-badge-free"
                  >
                    免费
                  </text>
                </view>
                <text class="ch-featured-desc">
                  {{ book.desc }}
                </text>
              </view>
              <text class="ch-featured-author">
                {{ book.author }}
              </text>
            </view>
          </view>
        </view>
      </view>

      <!-- 底部 AI 入口 -->
      <view class="ch-sec ch-ai-sec">
        <view
          class="ch-ai-entry"
          @tap="goAI"
        >
          <view class="ch-ai-icon">
            <app-icon
              name="sparkles"
              :size="40"
              color="#fff"
            />
          </view>
          <view class="ch-ai-info">
            <text class="ch-ai-title">
              AI 国学助手
            </text>
            <text class="ch-ai-desc">
              不懂就问，白话解读古籍疑难
            </text>
          </view>
          <app-icon
            name="chevron-right"
            :size="36"
            color="rgba(0,0,0,0.2)"
          />
        </view>
      </view>
    </view>
  </view>
</template>

<style scoped lang="scss">
.ch-page {
  min-height: 100vh;
  background: var(--classics-bg);
  padding-bottom: 160rpx;
}

/* 顶栏 */
.ch-topbar {
  position: sticky;
  top: 0;
  z-index: 50;
  background: color-mix(in srgb, var(--classics-bg) 80%, transparent);
  backdrop-filter: blur(20rpx);
  -webkit-backdrop-filter: blur(20rpx);
}
.ch-statusbar {
  height: var(--status-bar-height, 0px);
}
.ch-topbar-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 12rpx;
  height: 96rpx;
}
.ch-circle-btn {
  width: 72rpx;
  height: 72rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  &:active { transform: scale(0.9); }
}
.ch-topbar-title {
  font-size: 34rpx;
  font-weight: 600;
  color: var(--foreground);
}

.ch-main {
  max-width: 100%;
}

/* Hero */
.ch-hero {
  padding: 24rpx 40rpx 40rpx;
}
.ch-hero-kicker {
  display: block;
  font-size: 26rpx;
  font-weight: 600;
  letter-spacing: 1rpx;
  color: var(--brand);
  margin-bottom: 12rpx;
}
.ch-hero-title {
  display: block;
  font-size: 80rpx;
  line-height: 1.05;
  font-weight: 700;
  letter-spacing: -1rpx;
  color: var(--foreground);
}
.ch-hero-stats {
  margin-top: 32rpx;
  display: flex;
  align-items: center;
  gap: 32rpx;
}
.ch-stat {
  display: flex;
  align-items: center;
  gap: 12rpx;
  font-size: 26rpx;
  color: var(--muted-foreground);
}
.ch-stat-dot {
  width: 8rpx;
  height: 8rpx;
  border-radius: 50%;
  background: rgba(153, 153, 153, 0.4);
}
.ch-stat-val {
  font-weight: 600;
  color: var(--foreground);
}

/* 通用 section */
.ch-sec {
  padding: 0 40rpx 32rpx;
}
.ch-block {
  padding-bottom: 48rpx;
}
.ch-sec-pad {
  padding: 0 40rpx;
}

/* 搜索栏 */
.ch-searchbar {
  display: flex;
  align-items: center;
  gap: 20rpx;
  width: 100%;
  height: 88rpx;
  padding: 0 32rpx;
  border-radius: 32rpx;
  background: var(--card);
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}
.ch-search-ph {
  font-size: 30rpx;
  color: var(--muted-foreground);
}

/* 今日导读 */
.ch-today {
  position: relative;
  border-radius: 56rpx;
  overflow: hidden;
  box-shadow: 0 8rpx 24rpx rgba(0, 0, 0, 0.15);
  &:active { transform: scale(0.99); }
}
.ch-today-bg {
  position: absolute;
  inset: 0;
  background: linear-gradient(155deg, #a06a38, #5f3a1a);
}
.ch-today-inner {
  position: relative;
  padding: 48rpx;
  display: flex;
  flex-direction: column;
  gap: 40rpx;
}
.ch-today-tag {
  display: block;
  font-size: 24rpx;
  font-weight: 600;
  letter-spacing: 4rpx;
  color: rgba(255, 255, 255, 0.7);
  text-transform: uppercase;
}
.ch-today-quote {
  display: block;
  margin-top: 24rpx;
  font-family: var(--font-serif);
  font-size: 48rpx;
  font-weight: 700;
  color: #fff;
  line-height: 1.4;
}
.ch-today-desc {
  display: block;
  margin-top: 24rpx;
  font-size: 28rpx;
  color: rgba(255, 255, 255, 0.75);
  line-height: 1.6;
}
.ch-today-foot {
  display: flex;
  align-items: center;
  gap: 32rpx;
}
.ch-today-cover {
  width: 192rpx;
  flex-shrink: 0;
  box-shadow: 0 12rpx 32rpx rgba(0, 0, 0, 0.3);
}
.ch-today-meta {
  flex: 1;
}
.ch-today-name {
  display: block;
  color: #fff;
  font-weight: 600;
  font-size: 36rpx;
}
.ch-today-author {
  display: block;
  color: rgba(255, 255, 255, 0.7);
  font-size: 26rpx;
  margin-top: 4rpx;
}
.ch-today-btn {
  margin-top: 24rpx;
  display: inline-flex;
  align-items: center;
  gap: 12rpx;
  height: 72rpx;
  padding: 0 40rpx;
  border-radius: 999rpx;
  background: #fff;
}
.ch-today-btn-txt {
  color: #6f4521;
  font-size: 28rpx;
  font-weight: 600;
}

/* 继续阅读 */
.ch-continue {
  display: flex;
  align-items: center;
  gap: 24rpx;
  padding: 20rpx;
  border-radius: 32rpx;
  background: var(--card);
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}
.ch-continue-cover {
  width: 88rpx;
  flex-shrink: 0;
}
.ch-continue-info {
  min-width: 0;
  flex: 1;
}
.ch-continue-label {
  display: block;
  font-size: 22rpx;
  color: var(--muted-foreground);
}
.ch-continue-title {
  display: block;
  font-size: 30rpx;
  font-weight: 600;
  color: var(--foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ch-continue-prog {
  margin-top: 12rpx;
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.ch-prog-track {
  flex: 1;
  height: 8rpx;
  border-radius: 999rpx;
  background: var(--muted);
  overflow: hidden;
  max-width: 280rpx;
}
.ch-prog-fill {
  height: 100%;
  background: var(--brand);
  border-radius: 999rpx;
}
.ch-prog-pct {
  font-size: 22rpx;
  color: var(--brand);
  font-weight: 600;
}
.ch-continue-week {
  display: flex;
  align-items: center;
  gap: 12rpx;
  padding-left: 24rpx;
  margin-left: 8rpx;
  border-left: 2rpx solid var(--border);
  flex-shrink: 0;
}
.ch-week-meta {
  text-align: right;
}
.ch-week-label {
  display: block;
  font-size: 20rpx;
  color: var(--muted-foreground);
  line-height: 1;
}
.ch-week-num {
  font-size: 26rpx;
  font-weight: 700;
  color: var(--foreground);
}
.ch-week-unit {
  font-weight: 400;
  color: var(--muted-foreground);
  font-size: 20rpx;
}

/* 四库分类 */
.ch-cat-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24rpx;
}
.ch-cat-tile {
  height: 176rpx;
  border-radius: 48rpx;
  padding: 32rpx;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.08);
  &:active { transform: scale(0.97); }
}
.ch-cat-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.ch-cat-name {
  color: #fff;
  font-weight: 700;
  font-size: 36rpx;
  letter-spacing: 2rpx;
}
.ch-cat-desc {
  display: block;
  color: rgba(255, 255, 255, 0.9);
  font-size: 24rpx;
  font-weight: 500;
}
.ch-cat-count {
  display: block;
  color: rgba(255, 255, 255, 0.6);
  font-size: 22rpx;
}

/* section header */
.ch-sec-head {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  padding: 0 40rpx;
  margin-bottom: 28rpx;
}
.ch-sec-title {
  font-size: 44rpx;
  font-weight: 700;
  letter-spacing: -0.5rpx;
  color: var(--foreground);
}
.ch-sec-sub {
  display: block;
  font-size: 26rpx;
  color: var(--muted-foreground);
  margin-top: 4rpx;
}
.ch-sec-link {
  display: flex;
  align-items: center;
  flex-shrink: 0;
}
.ch-sec-link-txt {
  font-size: 26rpx;
  color: var(--brand);
  font-weight: 500;
}

/* 横向滚动通用 */
.ch-hscroll {
  white-space: nowrap;
  width: 100%;
}
.ch-hscroll-row {
  display: inline-flex;
  gap: 32rpx;
  padding: 0 40rpx 16rpx;
}

/* 书单卡片 */
.ch-list-card {
  flex-shrink: 0;
  width: 520rpx;
  border-radius: 48rpx;
  padding: 40rpx;
  background: var(--card);
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}
.ch-list-title {
  font-weight: 700;
  font-size: 34rpx;
  color: var(--foreground);
}
.ch-list-desc {
  display: block;
  font-size: 24rpx;
  color: var(--muted-foreground);
  margin-top: 4rpx;
  margin-bottom: 32rpx;
}
.ch-list-covers {
  display: flex;
  align-items: flex-end;
  gap: 20rpx;
}
.ch-list-cover {
  flex: 1;
}

/* 类型筛选 */
.ch-type-scroll {
  white-space: nowrap;
  width: 100%;
  margin-bottom: 24rpx;
}
.ch-type-row {
  display: inline-flex;
  gap: 16rpx;
  padding: 0 40rpx;
}
.ch-type-chip {
  flex-shrink: 0;
  padding: 0 28rpx;
  height: 56rpx;
  line-height: 56rpx;
  border-radius: 999rpx;
  font-size: 26rpx;
  font-weight: 500;
  background: var(--secondary);
  color: var(--muted-foreground);
}
.ch-type-chip--on {
  background: var(--primary);
  color: var(--primary-foreground);
}

/* 推荐榜 */
.ch-rank-card {
  border-radius: 48rpx;
  background: var(--card);
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  overflow: hidden;
}
.ch-rank-row {
  display: flex;
  align-items: center;
  gap: 28rpx;
  padding: 24rpx;
  &:active { background: rgba(0, 0, 0, 0.03); }
}
.ch-rank-row--border {
  border-top: 2rpx solid rgba(232, 224, 213, 0.6);
}
.ch-rank-num {
  width: 48rpx;
  text-align: center;
  font-weight: 700;
  font-size: 36rpx;
  color: var(--muted-foreground);
  flex-shrink: 0;
}
.ch-rank-num--top {
  color: var(--brand);
}
.ch-rank-cover {
  width: 112rpx;
  flex-shrink: 0;
}
.ch-rank-info {
  flex: 1;
  min-width: 0;
}
.ch-rank-title {
  display: block;
  font-weight: 600;
  font-size: 30rpx;
  color: var(--foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ch-rank-desc {
  display: block;
  font-size: 24rpx;
  color: var(--muted-foreground);
  margin-top: 4rpx;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ch-rank-meta {
  display: block;
  font-size: 22rpx;
  color: rgba(153, 153, 153, 0.7);
  margin-top: 4rpx;
}
.ch-refresh {
  width: 100%;
  margin-top: 24rpx;
  padding: 20rpx 0;
  text-align: center;
  font-size: 28rpx;
  font-weight: 500;
  color: var(--muted-foreground);
  background: var(--card);
  border-radius: 32rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}

/* 听书 */
.ch-audio-card {
  flex-shrink: 0;
  width: 480rpx;
  display: flex;
  gap: 24rpx;
  padding: 24rpx;
  background: var(--card);
  border-radius: 32rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}
.ch-audio-cover {
  width: 112rpx;
  flex-shrink: 0;
}
.ch-audio-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  white-space: normal;
}
.ch-audio-title {
  display: block;
  font-weight: 600;
  font-size: 30rpx;
  color: var(--foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ch-audio-desc {
  display: block;
  font-size: 24rpx;
  color: var(--muted-foreground);
  margin-top: 4rpx;
  line-height: 1.5;
}
.ch-audio-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.ch-audio-narrator {
  font-size: 22rpx;
  color: var(--muted-foreground);
}
.ch-audio-play {
  width: 56rpx;
  height: 56rpx;
  border-radius: 50%;
  background: var(--brand);
  display: flex;
  align-items: center;
  justify-content: center;
}

/* 精选古籍 */
.ch-featured-grid {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.ch-featured-card {
  display: flex;
  gap: 32rpx;
  padding: 32rpx;
  background: var(--card);
  border-radius: 32rpx;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}
.ch-featured-cover {
  width: 128rpx;
  flex-shrink: 0;
}
.ch-featured-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
.ch-featured-titlerow {
  display: flex;
  align-items: center;
  gap: 16rpx;
}
.ch-featured-title {
  font-weight: 600;
  font-size: 32rpx;
  color: var(--foreground);
}
.ch-badge-free {
  font-size: 20rpx;
  font-weight: 500;
  padding: 2rpx 12rpx;
  border-radius: 8rpx;
  background: #d1fae5;
  color: #047857;
}
.ch-featured-desc {
  display: block;
  font-size: 24rpx;
  color: var(--muted-foreground);
  margin-top: 8rpx;
  line-height: 1.5;
}
.ch-featured-author {
  font-size: 22rpx;
  color: rgba(153, 153, 153, 0.7);
}

/* AI 入口 */
.ch-ai-sec {
  padding-top: 8rpx;
}
.ch-ai-entry {
  display: flex;
  align-items: center;
  gap: 24rpx;
  padding: 32rpx;
  border-radius: 32rpx;
  background: var(--card);
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  &:active { transform: scale(0.99); }
}
.ch-ai-icon {
  width: 80rpx;
  height: 80rpx;
  border-radius: 50%;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(150deg, #c8324c, #9e1b30);
}
.ch-ai-info {
  flex: 1;
  min-width: 0;
}
.ch-ai-title {
  display: block;
  font-weight: 600;
  font-size: 30rpx;
  color: var(--foreground);
}
.ch-ai-desc {
  display: block;
  font-size: 24rpx;
  color: var(--muted-foreground);
  margin-top: 4rpx;
}
</style>
