// apps/mobile/src/pkg-mine/wallet/withdraw.vue
<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import AppNavBar from '@/components/common/app-nav-bar.vue'
import AppIcon from '@/components/common/app-icon.vue'
import { goBack, navigateTo } from '@/utils/router'
import {
  mineApi,
  type WithdrawMethod,
  type WithdrawAccount,
  type WithdrawBalanceInfo,
} from '@/lib/mine-data'

const loading = ref(false)
const error = ref('')
const info = ref<WithdrawBalanceInfo>({
  availableBalance: 0, frozenBalance: 0, pendingBalance: 0,
  minWithdraw: 10, maxWithdraw: 50000, feeRate: 0.006, minFee: 1,
  savedAccounts: [],
})

const retry = () => { error.value = ''; loadData() }
async function loadData() {
  loading.value = true; error.value = ''
  try {
    info.value = await mineApi.getWithdrawInfo()
    // 预填已存账户
    const savedAlipay = info.value.savedAccounts.find((a) => a.method === 'alipay')
    if (savedAlipay) fillAccount(savedAlipay)
  } catch (e: any) { error.value = e?.message || '加载失败' }
  finally { loading.value = false }
}
onMounted(loadData)

// 表单状态
const amount = ref('')
const method = ref<WithdrawMethod>('alipay')
const form = reactive({
  alipayAccount: '',
  alipayName: '',
  bankName: '',
  bankAccount: '',
  bankHolder: '',
})

// 预填已存账户
function fillAccount(acc: WithdrawAccount) {
  if (acc.method === 'alipay') {
    form.alipayAccount = acc.alipayAccount || ''
    form.alipayName = acc.alipayName || ''
  } else {
    form.bankName = acc.bankName || ''
    form.bankAccount = acc.bankAccount || ''
    form.bankHolder = acc.bankHolder || ''
  }
}

function switchMethod(m: WithdrawMethod) {
  method.value = m
  const saved = info.value.savedAccounts.find((a: WithdrawAccount) => a.method === m)
  if (saved) {
    fillAccount(saved)
  } else if (m === 'alipay') {
    form.alipayAccount = ''
    form.alipayName = ''
  } else {
    form.bankName = ''
    form.bankAccount = ''
    form.bankHolder = ''
  }
}

const amountNum = computed(() => parseFloat(amount.value) || 0)
const fee = computed(() => Math.max(amountNum.value * info.value.feeRate, info.value.minFee))
const actualAmount = computed(() => Math.max(amountNum.value - fee.value, 0))

const isValidAmount = computed(
  () =>
    amountNum.value >= info.value.minWithdraw &&
    amountNum.value <= info.value.availableBalance &&
    amountNum.value <= info.value.maxWithdraw,
)
const isValidAccount = computed(() =>
  method.value === 'alipay'
    ? !!form.alipayAccount.trim() && !!form.alipayName.trim()
    : !!form.bankName.trim() && !!form.bankAccount.trim() && !!form.bankHolder.trim(),
)
const canSubmit = computed(() => isValidAmount.value && isValidAccount.value)

function withdrawAll() {
  amount.value = String(Math.min(info.value.availableBalance, info.value.maxWithdraw))
}

// 支付密码弹窗
const showPwd = ref(false)
const pwd = ref<string[]>(['', '', '', '', '', ''])
const verifying = ref(false)

function openPwd() {
  if (!canSubmit.value) return
  pwd.value = ['', '', '', '', '', '']
  showPwd.value = true
}
function onPwdInput(e: { detail: { value: string } }) {
  const v = e.detail.value.replace(/\D/g, '')
  const arr = ['', '', '', '', '', '']
  for (let i = 0; i < v.length && i < 6; i++) arr[i] = v[i]
  pwd.value = arr
  if (v.length === 6) verifyAndSubmit()
}

// 成功态
const success = ref(false)
const result = reactive({ amount: 0, fee: 0, actualAmount: 0, estimatedArrival: '' })

async function verifyAndSubmit() {
  verifying.value = true
  try {
    const account = method.value === 'alipay' ? form.alipayAccount : form.bankAccount
    const res = await mineApi.withdraw(amountNum.value, method.value, account)
    if (res.success) {
      showPwd.value = false
      result.amount = amountNum.value
      result.fee = fee.value
      result.actualAmount = actualAmount.value
      result.estimatedArrival =
        method.value === 'alipay' ? '预计2小时内到账' : '预计1-3个工作日到账'
      success.value = true
    } else {
      uni.showToast({ title: res.message, icon: 'none' })
    }
  } catch (e: any) {
    uni.showToast({ title: e?.message || '提现失败', icon: 'none' })
  } finally { verifying.value = false }
}

function backToWallet() {
  navigateTo('/mine/wallet')
}
function continueWithdraw() {
  success.value = false
  amount.value = ''
}
</script>

<template>
  <!-- 加载/错误态 -->
  <view v-if="loading" class="page">
    <app-nav-bar title="提现" back-icon="arrow-left" @back="goBack" />
    <view class="loading"><text>加载中...</text></view>
  </view>
  <view v-else-if="error" class="page">
    <app-nav-bar title="提现" back-icon="arrow-left" @back="goBack" />
    <view class="error-state"><text>{{ error }}</text><view class="retry-btn" @tap="retry">重试</view></view>
  </view>
  <!-- 成功态 -->
  <view v-else-if="success" class="page">
    <app-nav-bar title="提现结果" back-icon="arrow-left" @back="backToWallet" />
    <view class="success-wrap">
      <view class="success-icon">
        <app-icon name="check" :size="40" color="#16a34a" />
      </view>
      <text class="success-title">提现申请已提交</text>
      <text class="success-sub">{{ result.estimatedArrival }}</text>

      <view class="result-card">
        <view class="result-row">
          <text class="result-label">提现金额</text>
          <text class="result-val">¥{{ result.amount.toFixed(2) }}</text>
        </view>
        <view class="result-row">
          <text class="result-label">手续费</text>
          <text class="result-val">-¥{{ result.fee.toFixed(2) }}</text>
        </view>
        <view class="result-divider" />
        <view class="result-row">
          <text class="result-label">实际到账</text>
          <text class="result-amount">¥{{ result.actualAmount.toFixed(2) }}</text>
        </view>
      </view>

      <view class="success-btns">
        <view class="btn-outline" @tap="backToWallet">返回钱包</view>
        <view class="btn-primary" @tap="continueWithdraw">继续提现</view>
      </view>
    </view>
  </view>

  <!-- 表单态 -->
  <view v-else class="page">
    <app-nav-bar title="提现" back-icon="arrow-left" @back="goBack" />

    <view class="body">
      <!-- 可提现余额 -->
      <view class="balance-card">
        <view class="bal-head">
          <app-icon name="wallet" :size="36" color="rgba(255,255,255,0.8)" />
          <text class="bal-label">可提现余额</text>
        </view>
        <text class="bal-amount">¥{{ info.availableBalance.toFixed(2) }}</text>
        <view class="bal-extra">
          <text>冻结中: ¥{{ info.frozenBalance.toFixed(2) }}</text>
          <text>待结算: ¥{{ info.pendingBalance.toFixed(2) }}</text>
        </view>
      </view>

      <!-- 提现金额 -->
      <view class="card">
        <view class="card-head">
          <text class="card-label">提现金额</text>
          <text class="all-btn" @tap="withdrawAll">全部提现</text>
        </view>
        <view class="amount-input-wrap">
          <text class="amount-yen">¥</text>
          <input
            class="amount-input"
            type="digit"
            :value="amount"
            placeholder="0.00"
            placeholder-class="amount-ph"
            @input="(e: any) => (amount = e.detail.value)"
          />
        </view>
        <view class="amount-tip">
          <app-icon name="alert-circle" :size="26" color="rgba(92,64,51,0.6)" />
          <text>单笔最低{{ info.minWithdraw }}元，最高{{ info.maxWithdraw }}元</text>
        </view>
      </view>

      <!-- 收款方式 -->
      <view class="card">
        <text class="card-label block">收款方式</text>
        <view class="method-grid">
          <view
            class="method-btn"
            :class="{ active: method === 'alipay' }"
            @tap="switchMethod('alipay')"
          >
            <app-icon
              name="credit-card"
              :size="36"
              :color="method === 'alipay' ? '#c41e3a' : 'rgba(92,64,51,0.6)'"
            />
            <text :class="method === 'alipay' ? 'm-active' : 'm-normal'">支付宝</text>
          </view>
          <view
            class="method-btn"
            :class="{ active: method === 'bank' }"
            @tap="switchMethod('bank')"
          >
            <app-icon
              name="building-2"
              :size="36"
              :color="method === 'bank' ? '#c41e3a' : 'rgba(92,64,51,0.6)'"
            />
            <text :class="method === 'bank' ? 'm-active' : 'm-normal'">银行卡</text>
          </view>
        </view>

        <!-- 支付宝表单 -->
        <view v-if="method === 'alipay'" class="form-fields">
          <view class="field">
            <text class="field-label">支付宝账号</text>
            <input
              class="field-input"
              :value="form.alipayAccount"
              placeholder="请输入支付宝账号"
              placeholder-class="field-ph"
              @input="(e: any) => (form.alipayAccount = e.detail.value)"
            />
          </view>
          <view class="field">
            <text class="field-label">真实姓名</text>
            <input
              class="field-input"
              :value="form.alipayName"
              placeholder="请输入支付宝实名姓名"
              placeholder-class="field-ph"
              @input="(e: any) => (form.alipayName = e.detail.value)"
            />
          </view>
        </view>

        <!-- 银行卡表单 -->
        <view v-else class="form-fields">
          <view class="field">
            <text class="field-label">开户银行</text>
            <input
              class="field-input"
              :value="form.bankName"
              placeholder="请输入开户银行名称"
              placeholder-class="field-ph"
              @input="(e: any) => (form.bankName = e.detail.value)"
            />
          </view>
          <view class="field">
            <text class="field-label">银行卡号</text>
            <input
              class="field-input"
              type="number"
              :value="form.bankAccount"
              placeholder="请输入银行卡号"
              placeholder-class="field-ph"
              @input="(e: any) => (form.bankAccount = e.detail.value)"
            />
          </view>
          <view class="field">
            <text class="field-label">持卡人姓名</text>
            <input
              class="field-input"
              :value="form.bankHolder"
              placeholder="请输入持卡人姓名"
              placeholder-class="field-ph"
              @input="(e: any) => (form.bankHolder = e.detail.value)"
            />
          </view>
        </view>
      </view>

      <!-- 费用预览 -->
      <view v-if="amountNum > 0" class="card">
        <view class="fee-row">
          <text class="fee-label">提现金额</text>
          <text class="fee-val">¥{{ amountNum.toFixed(2) }}</text>
        </view>
        <view class="fee-row">
          <text class="fee-label"
            >手续费 ({{ (info.feeRate * 100).toFixed(1) }}%，最低{{ info.minFee }}元)</text
          >
          <text class="fee-val">-¥{{ fee.toFixed(2) }}</text>
        </view>
        <view class="result-divider" />
        <view class="fee-row">
          <text class="fee-label">预计到账</text>
          <text class="result-amount">¥{{ actualAmount.toFixed(2) }}</text>
        </view>
      </view>

      <!-- 提交 -->
      <view
        class="submit-btn"
        :class="{ disabled: !canSubmit }"
        @tap="openPwd"
        >确认提现</view
      >

      <view class="hints">
        <text>• 支付宝提现预计2小时内到账</text>
        <text>• 银行卡提现预计1-3个工作日到账</text>
        <text>• 请确保收款账户信息准确无误</text>
      </view>
    </view>

    <!-- 支付密码弹窗 -->
    <view v-if="showPwd" class="pwd-mask">
      <view class="pwd-sheet">
        <view class="pwd-head">
          <view class="pwd-spacer" />
          <text class="pwd-title">请输入支付密码</text>
          <view class="pwd-close" @tap="showPwd = false">
            <app-icon name="x" :size="36" color="rgba(92,64,51,0.6)" />
          </view>
        </view>
        <view class="pwd-boxes">
          <view v-for="(p, i) in pwd" :key="i" class="pwd-box">
            <view v-if="p" class="pwd-dot" />
          </view>
        </view>
        <input
          class="pwd-hidden-input"
          type="number"
          :maxlength="6"
          :value="pwd.join('')"
          :focus="showPwd"
          :disabled="verifying"
          @input="(e: any) => onPwdInput(e)"
        />
        <view v-if="verifying" class="pwd-verifying">
          <text>验证中...</text>
        </view>
        <text class="pwd-forget">忘记支付密码？</text>
      </view>
    </view>
  </view>

  </view>
  </view>
  </view>
  </view>
  </view>
</template>

<style scoped>
.page {
  min-height: 100vh;
  background: #faf8f5;
}
.body {
  padding: 32rpx;
  display: flex;
  flex-direction: column;
  gap: 32rpx;
}

/* 余额卡 */
.balance-card {
  background: linear-gradient(135deg, #c41e3a, #8b1528);
  border-radius: 24rpx;
  padding: 32rpx;
  color: #fff;
}
.bal-head {
  display: flex;
  align-items: center;
  gap: 16rpx;
  margin-bottom: 16rpx;
}
.bal-label {
  font-size: 28rpx;
  color: rgba(255, 255, 255, 0.8);
}
.bal-amount {
  display: block;
  font-size: 60rpx;
  font-weight: 700;
  margin-bottom: 24rpx;
}
.bal-extra {
  display: flex;
  gap: 32rpx;
  font-size: 22rpx;
  color: rgba(255, 255, 255, 0.7);
}

/* 通用卡片 */
.card {
  background: #fff;
  border-radius: 24rpx;
  padding: 32rpx;
}
.card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24rpx;
}
.card-label {
  font-size: 30rpx;
  font-weight: 500;
  color: #2f1810;
}
.card-label.block {
  display: block;
  margin-bottom: 24rpx;
}
.all-btn {
  font-size: 28rpx;
  color: #c41e3a;
}

/* 金额输入 */
.amount-input-wrap {
  position: relative;
  display: flex;
  align-items: center;
  height: 112rpx;
  border: 2rpx solid rgba(201, 169, 110, 0.3);
  border-radius: 16rpx;
  padding: 0 24rpx;
  gap: 16rpx;
}
.amount-yen {
  font-size: 48rpx;
  color: #2f1810;
}
.amount-input {
  flex: 1;
  font-size: 48rpx;
  font-weight: 600;
  color: #2f1810;
}
.amount-ph {
  color: #b8a99b;
  font-weight: 400;
}
.amount-tip {
  display: flex;
  align-items: center;
  gap: 8rpx;
  margin-top: 16rpx;
  font-size: 22rpx;
  color: rgba(92, 64, 51, 0.6);
}

/* 收款方式 */
.method-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 24rpx;
  margin-bottom: 32rpx;
}
.method-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 16rpx;
  height: 96rpx;
  border: 4rpx solid rgba(201, 169, 110, 0.3);
  border-radius: 16rpx;
}
.method-btn.active {
  border-color: #c41e3a;
  background: rgba(196, 30, 58, 0.05);
}
.m-active {
  color: #c41e3a;
  font-size: 30rpx;
}
.m-normal {
  color: #5c4033;
  font-size: 30rpx;
}

/* 表单 */
.form-fields {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.field-label {
  display: block;
  font-size: 26rpx;
  color: rgba(92, 64, 51, 0.7);
  margin-bottom: 12rpx;
}
.field-input {
  width: 100%;
  height: 80rpx;
  border: 2rpx solid rgba(201, 169, 110, 0.3);
  border-radius: 12rpx;
  padding: 0 24rpx;
  font-size: 28rpx;
  color: #2f1810;
  box-sizing: border-box;
}
.field-ph {
  color: #b8a99b;
}

/* 费用预览 */
.fee-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16rpx;
}
.fee-label {
  font-size: 28rpx;
  color: rgba(92, 64, 51, 0.7);
}
.fee-val {
  font-size: 28rpx;
  color: #2f1810;
}
.result-divider {
  height: 2rpx;
  background: rgba(201, 169, 110, 0.2);
  margin: 16rpx 0;
}
.result-amount {
  font-size: 36rpx;
  font-weight: 600;
  color: #c41e3a;
}

/* 提交 */
.submit-btn {
  height: 96rpx;
  border-radius: 16rpx;
  background: #c41e3a;
  color: #fff;
  font-size: 32rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}
.submit-btn.disabled {
  opacity: 0.5;
}
.hints {
  display: flex;
  flex-direction: column;
  gap: 8rpx;
  font-size: 22rpx;
  color: rgba(92, 64, 51, 0.6);
}

/* 成功态 */
.success-wrap {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 96rpx 32rpx 0;
}
.success-icon {
  width: 128rpx;
  height: 128rpx;
  border-radius: 50%;
  background: rgba(22, 163, 74, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 32rpx;
}
.success-title {
  font-size: 40rpx;
  font-weight: 600;
  color: #2f1810;
  margin-bottom: 16rpx;
}
.success-sub {
  font-size: 28rpx;
  color: rgba(92, 64, 51, 0.7);
  margin-bottom: 64rpx;
}
.result-card {
  width: 100%;
  background: #fff;
  border-radius: 24rpx;
  padding: 32rpx;
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}
.result-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.result-label {
  font-size: 28rpx;
  color: rgba(92, 64, 51, 0.7);
}
.result-val {
  font-size: 28rpx;
  color: #2f1810;
}
.success-btns {
  display: flex;
  gap: 24rpx;
  width: 100%;
  margin-top: 64rpx;
}
.btn-outline {
  flex: 1;
  height: 88rpx;
  border: 2rpx solid #c9a96e;
  border-radius: 16rpx;
  color: #c9a96e;
  font-size: 30rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}
.btn-primary {
  flex: 1;
  height: 88rpx;
  background: #c41e3a;
  border-radius: 16rpx;
  color: #fff;
  font-size: 30rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* 支付密码弹窗 */
.pwd-mask {
  position: fixed;
  inset: 0;
  z-index: 50;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: flex-end;
  justify-content: center;
}
.pwd-sheet {
  position: relative;
  width: 100%;
  background: #fff;
  border-radius: 32rpx 32rpx 0 0;
  padding: 32rpx 32rpx calc(48rpx + env(safe-area-inset-bottom));
}
.pwd-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 48rpx;
}
.pwd-spacer {
  width: 48rpx;
}
.pwd-title {
  font-size: 32rpx;
  font-weight: 500;
  color: #2f1810;
}
.pwd-close {
  width: 48rpx;
  display: flex;
  justify-content: flex-end;
}
.pwd-boxes {
  display: flex;
  justify-content: center;
  gap: 24rpx;
  margin-bottom: 48rpx;
}
.pwd-box {
  width: 80rpx;
  height: 96rpx;
  border: 4rpx solid rgba(201, 169, 110, 0.3);
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}
.pwd-dot {
  width: 24rpx;
  height: 24rpx;
  background: #2f1810;
  border-radius: 50%;
}
.pwd-hidden-input {
  position: absolute;
  opacity: 0;
  width: 1rpx;
  height: 1rpx;
}
.pwd-verifying {
  text-align: center;
  font-size: 28rpx;
  color: rgba(92, 64, 51, 0.7);
}
.pwd-forget {
  display: block;
  text-align: center;
  font-size: 28rpx;
  color: #c41e3a;
  margin-top: 32rpx;
}

.loading { flex: 1; display: flex; align-items: center; justify-content: center; font-size: 28rpx; color: rgba(92,64,51,0.6); }
.error-state { flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 24rpx; }
.error-state text { font-size: 28rpx; color: rgba(92,64,51,0.6); }
.retry-btn { padding: 16rpx 48rpx; background: #c41e3a; color: #fff; border-radius: 12rpx; font-size: 26rpx; }
</style>

// v0-reference/proto-ref-app/wallet/withdraw/page.tsx
"use client"

import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import { ArrowLeft, Wallet, CreditCard, Building2, AlertCircle, Check, ChevronRight, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { toast } from "sonner"
import { DataState } from "@/components/data-state"
import { getWithdrawBalance, applyWithdrawal, verifyPaymentPassword } from "@/lib/api/wallet"
import type { WithdrawBalanceInfo, WithdrawAccount, WithdrawMethod } from "@/lib/types/wallet"

export default function WithdrawPage() {
  const router = useRouter()
  const [balanceInfo, setBalanceInfo] = useState<WithdrawBalanceInfo | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  // 表单状态
  const [amount, setAmount] = useState("")
  const [method, setMethod] = useState<WithdrawMethod>("alipay")
  const [alipayAccount, setAlipayAccount] = useState("")
  const [alipayName, setAlipayName] = useState("")
  const [bankName, setBankName] = useState("")
  const [bankAccount, setBankAccount] = useState("")
  const [bankHolder, setBankHolder] = useState("")
  
  // 支付密码弹窗
  const [showPasswordModal, setShowPasswordModal] = useState(false)
  const [password, setPassword] = useState(["", "", "", "", "", ""])
  const [verifying, setVerifying] = useState(false)
  const passwordInputRefs = useRef<(HTMLInputElement | null)[]>([])
  
  // 成功态
  const [success, setSuccess] = useState(false)
  const [withdrawResult, setWithdrawResult] = useState<{
    amount: number
    fee: number
    actualAmount: number
    estimatedArrival: string
  } | null>(null)

  // 加载提现余额信息
  useEffect(() => {
    loadBalanceInfo()
  }, [])

  const loadBalanceInfo = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await getWithdrawBalance()
      if (res.code === 200 && res.data) {
        setBalanceInfo(res.data)
        // 如果有保存的账户，自动填充
        const savedAccount = res.data.savedAccounts.find(a => a.method === method)
        if (savedAccount) {
          fillAccountInfo(savedAccount)
        }
      } else {
        setError(res.message || "加载失败")
      }
    } catch {
      setError("网络错误，请重试")
    } finally {
      setLoading(false)
    }
  }

  const fillAccountInfo = (account: WithdrawAccount) => {
    if (account.method === "alipay") {
      setAlipayAccount(account.alipayAccount || "")
      setAlipayName(account.alipayName || "")
    } else {
      setBankName(account.bankName || "")
      setBankAccount(account.bankAccount || "")
      setBankHolder(account.bankHolder || "")
    }
  }

  // 切换提现方式
  const handleMethodChange = (newMethod: WithdrawMethod) => {
    setMethod(newMethod)
    // 查找是否有保存的账户
    const savedAccount = balanceInfo?.savedAccounts.find(a => a.method === newMethod)
    if (savedAccount) {
      fillAccountInfo(savedAccount)
    } else {
      // 清空表单
      if (newMethod === "alipay") {
        setAlipayAccount("")
        setAlipayName("")
      } else {
        setBankName("")
        setBankAccount("")
        setBankHolder("")
      }
    }
  }

  // 计算手续费和到账金额
  const amountNum = parseFloat(amount) || 0
  const fee = balanceInfo ? Math.max(amountNum * balanceInfo.feeRate, balanceInfo.minFee) : 0
  const actualAmount = Math.max(amountNum - fee, 0)

  // 表单验证
  const isValidAmount = balanceInfo && amountNum >= balanceInfo.minWithdraw && amountNum <= balanceInfo.availableBalance && amountNum <= balanceInfo.maxWithdraw
  const isValidAccount = method === "alipay" 
    ? alipayAccount.trim() && alipayName.trim()
    : bankName.trim() && bankAccount.trim() && bankHolder.trim()
  const canSubmit = isValidAmount && isValidAccount

  // 全部提现
  const handleWithdrawAll = () => {
    if (balanceInfo) {
      setAmount(Math.min(balanceInfo.availableBalance, balanceInfo.maxWithdraw).toString())
    }
  }

  // 提交提现申请
  const handleSubmit = () => {
    if (!canSubmit) return
    setShowPasswordModal(true)
    setPassword(["", "", "", "", "", ""])
    setTimeout(() => {
      passwordInputRefs.current[0]?.focus()
    }, 100)
  }

  // 密码输入处理
  const handlePasswordInput = (index: number, value: string) => {
    if (!/^\d*$/.test(value)) return
    
    const newPassword = [...password]
    newPassword[index] = value.slice(-1)
    setPassword(newPassword)

    if (value && index < 5) {
      passwordInputRefs.current[index + 1]?.focus()
    }

    // 输入完成自动验证
    if (newPassword.every(p => p) && newPassword.join("").length === 6) {
      verifyAndSubmit(newPassword.join(""))
    }
  }

  const handlePasswordKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === "Backspace" && !password[index] && index > 0) {
      passwordInputRefs.current[index - 1]?.focus()
    }
  }

  // 验证密码并提交
  const verifyAndSubmit = async (pwd: string) => {
    setVerifying(true)
    try {
      const verifyRes = await verifyPaymentPassword(pwd)
      if (verifyRes.code !== 200 || !verifyRes.data?.valid) {
        toast.error(verifyRes.message || "支付密码错误")
        setPassword(["", "", "", "", "", ""])
        passwordInputRefs.current[0]?.focus()
        setVerifying(false)
        return
      }

      // 构建提现请求
      const account: WithdrawAccount = method === "alipay"
        ? { method: "alipay", alipayAccount, alipayName }
        : { method: "bank", bankName, bankAccount, bankHolder }

      const res = await applyWithdrawal({
        amount: amountNum,
        account,
        paymentPassword: pwd,
      })

      if (res.code === 200 && res.data) {
        setWithdrawResult({
          amount: res.data.amount,
          fee: res.data.fee,
          actualAmount: res.data.actualAmount,
          estimatedArrival: res.data.estimatedArrival,
        })
        setSuccess(true)
        setShowPasswordModal(false)
      } else {
        toast.error(res.message || "提现申请失败")
      }
    } catch {
      toast.error("网络错误，请重试")
    } finally {
      setVerifying(false)
    }
  }

  // 成功页面
  if (success && withdrawResult) {
    return (
      <div className="min-h-screen bg-[#FAF8F5]">
        <header className="sticky top-0 z-10 bg-[#FAF8F5] border-b border-[#C9A96E]/20">
          <div className="flex items-center h-14 px-4">
            <button onClick={() => router.push("/wallet")} className="p-2 -ml-2">
              <ArrowLeft className="w-5 h-5 text-[#2F1810]" />
            </button>
            <h1 className="flex-1 text-center text-lg font-medium text-[#2F1810]">提现结果</h1>
            <div className="w-9" />
          </div>
        </header>

        <div className="flex flex-col items-center px-4 pt-12">
          <div className="w-16 h-16 rounded-full bg-green-500/10 flex items-center justify-center mb-4">
            <Check className="w-8 h-8 text-green-600" />
          </div>
          <h2 className="text-xl font-semibold text-[#2F1810] mb-2">提现申请已提交</h2>
          <p className="text-[#5C4033]/70 mb-8">{withdrawResult.estimatedArrival}</p>

          <div className="w-full bg-white rounded-xl p-4 space-y-3">
            <div className="flex justify-between">
              <span className="text-[#5C4033]/70">提现金额</span>
              <span className="text-[#2F1810]">¥{withdrawResult.amount.toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#5C4033]/70">手续费</span>
              <span className="text-[#2F1810]">-¥{withdrawResult.fee.toFixed(2)}</span>
            </div>
            <div className="h-px bg-[#C9A96E]/20" />
            <div className="flex justify-between">
              <span className="text-[#5C4033]/70">实际到账</span>
              <span className="text-lg font-semibold text-[#C41E3A]">¥{withdrawResult.actualAmount.toFixed(2)}</span>
            </div>
          </div>

          <div className="flex gap-3 w-full mt-8">
            <Button
              variant="outline"
              className="flex-1 border-[#C9A96E] text-[#C9A96E]"
              onClick={() => router.push("/wallet")}
            >
              返回钱包
            </Button>
            <Button
              className="flex-1 bg-[#C41E3A] hover:bg-[#A31830] text-white"
              onClick={() => {
                setSuccess(false)
                setWithdrawResult(null)
                setAmount("")
                loadBalanceInfo()
              }}
            >
              继续提现
            </Button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#FAF8F5]">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-[#FAF8F5] border-b border-[#C9A96E]/20">
        <div className="flex items-center h-14 px-4">
          <button onClick={() => router.back()} className="p-2 -ml-2">
            <ArrowLeft className="w-5 h-5 text-[#2F1810]" />
          </button>
          <h1 className="flex-1 text-center text-lg font-medium text-[#2F1810]">提现</h1>
          <div className="w-9" />
        </div>
      </header>

      <DataState
        loading={loading}
        error={error}
        data={balanceInfo}
        skeleton={
          <div className="p-4 space-y-4">
            <div className="bg-white rounded-xl p-4 space-y-3">
              <div className="h-4 w-24 bg-[#C9A96E]/10 rounded animate-pulse" />
              <div className="h-8 w-32 bg-[#C9A96E]/10 rounded animate-pulse" />
            </div>
            <div className="bg-white rounded-xl p-4 space-y-3">
              <div className="h-4 w-20 bg-[#C9A96E]/10 rounded animate-pulse" />
              <div className="h-12 bg-[#C9A96E]/10 rounded animate-pulse" />
            </div>
          </div>
        }
        onRetry={loadBalanceInfo}
      >
        {balanceInfo && (
          <div className="p-4 space-y-4">
            {/* 可提现余额 */}
            <div className="bg-gradient-to-br from-[#C41E3A] to-[#8B1528] rounded-xl p-4 text-white">
              <div className="flex items-center gap-2 mb-2">
                <Wallet className="w-5 h-5 opacity-80" />
                <span className="text-sm opacity-80">可提现余额</span>
              </div>
              <div className="text-3xl font-bold mb-3">¥{balanceInfo.availableBalance.toFixed(2)}</div>
              <div className="flex gap-4 text-xs opacity-70">
                <span>冻结中: ¥{balanceInfo.frozenBalance.toFixed(2)}</span>
                <span>待结算: ¥{balanceInfo.pendingBalance.toFixed(2)}</span>
              </div>
            </div>

            {/* 提现金额 */}
            <div className="bg-white rounded-xl p-4">
              <div className="flex items-center justify-between mb-3">
                <Label className="text-[#2F1810] font-medium">提现金额</Label>
                <button
                  onClick={handleWithdrawAll}
                  className="text-sm text-[#C41E3A]"
                >
                  全部提现
                </button>
              </div>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-2xl text-[#2F1810]">¥</span>
                <Input
                  type="number"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  placeholder="0.00"
                  className="pl-10 h-14 text-2xl font-semibold border-[#C9A96E]/30 focus:border-[#C41E3A] focus:ring-[#C41E3A]/20"
                />
              </div>
              <div className="flex items-center gap-1 mt-2 text-xs text-[#5C4033]/60">
                <AlertCircle className="w-3.5 h-3.5" />
                <span>单笔最低{balanceInfo.minWithdraw}元，最高{balanceInfo.maxWithdraw}元</span>
              </div>
            </div>

            {/* 收款方式 */}
            <div className="bg-white rounded-xl p-4">
              <Label className="text-[#2F1810] font-medium mb-3 block">收款方式</Label>
              <div className="grid grid-cols-2 gap-3 mb-4">
                <button
                  onClick={() => handleMethodChange("alipay")}
                  className={`flex items-center justify-center gap-2 p-3 rounded-lg border-2 transition-colors ${
                    method === "alipay"
                      ? "border-[#C41E3A] bg-[#C41E3A]/5"
                      : "border-[#C9A96E]/30"
                  }`}
                >
                  <CreditCard className={`w-5 h-5 ${method === "alipay" ? "text-[#C41E3A]" : "text-[#5C4033]/60"}`} />
                  <span className={method === "alipay" ? "text-[#C41E3A]" : "text-[#5C4033]"}>支付宝</span>
                </button>
                <button
                  onClick={() => handleMethodChange("bank")}
                  className={`flex items-center justify-center gap-2 p-3 rounded-lg border-2 transition-colors ${
                    method === "bank"
                      ? "border-[#C41E3A] bg-[#C41E3A]/5"
                      : "border-[#C9A96E]/30"
                  }`}
                >
                  <Building2 className={`w-5 h-5 ${method === "bank" ? "text-[#C41E3A]" : "text-[#5C4033]/60"}`} />
                  <span className={method === "bank" ? "text-[#C41E3A]" : "text-[#5C4033]"}>银行卡</span>
                </button>
              </div>

              {/* 支付宝表单 */}
              {method === "alipay" && (
                <div className="space-y-3">
                  <div>
                    <Label className="text-sm text-[#5C4033]/70 mb-1.5 block">支付宝账号</Label>
                    <Input
                      value={alipayAccount}
                      onChange={(e) => setAlipayAccount(e.target.value)}
                      placeholder="请输入支付宝账号"
                      className="border-[#C9A96E]/30"
                    />
                  </div>
                  <div>
                    <Label className="text-sm text-[#5C4033]/70 mb-1.5 block">真实姓名</Label>
                    <Input
                      value={alipayName}
                      onChange={(e) => setAlipayName(e.target.value)}
                      placeholder="请输入支付宝实名姓名"
                      className="border-[#C9A96E]/30"
                    />
                  </div>
                </div>
              )}

              {/* 银行卡表单 */}
              {method === "bank" && (
                <div className="space-y-3">
                  <div>
                    <Label className="text-sm text-[#5C4033]/70 mb-1.5 block">开户银行</Label>
                    <Input
                      value={bankName}
                      onChange={(e) => setBankName(e.target.value)}
                      placeholder="请输入开户银行名称"
                      className="border-[#C9A96E]/30"
                    />
                  </div>
                  <div>
                    <Label className="text-sm text-[#5C4033]/70 mb-1.5 block">银行卡号</Label>
                    <Input
                      value={bankAccount}
                      onChange={(e) => setBankAccount(e.target.value)}
                      placeholder="请输入银行卡号"
                      className="border-[#C9A96E]/30"
                    />
                  </div>
                  <div>
                    <Label className="text-sm text-[#5C4033]/70 mb-1.5 block">持卡人姓名</Label>
                    <Input
                      value={bankHolder}
                      onChange={(e) => setBankHolder(e.target.value)}
                      placeholder="请输入持卡人姓名"
                      className="border-[#C9A96E]/30"
                    />
                  </div>
                </div>
              )}
            </div>

            {/* 费用预览 */}
            {amountNum > 0 && (
              <div className="bg-white rounded-xl p-4">
                <div className="flex justify-between text-sm mb-2">
                  <span className="text-[#5C4033]/70">提现金额</span>
                  <span className="text-[#2F1810]">¥{amountNum.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm mb-2">
                  <span className="text-[#5C4033]/70">手续费 ({(balanceInfo.feeRate * 100).toFixed(1)}%，最低{balanceInfo.minFee}元)</span>
                  <span className="text-[#2F1810]">-¥{fee.toFixed(2)}</span>
                </div>
                <div className="h-px bg-[#C9A96E]/20 my-2" />
                <div className="flex justify-between">
                  <span className="text-[#5C4033]/70">预计到账</span>
                  <span className="text-lg font-semibold text-[#C41E3A]">¥{actualAmount.toFixed(2)}</span>
                </div>
              </div>
            )}

            {/* 提交按钮 */}
            <Button
              onClick={handleSubmit}
              disabled={!canSubmit}
              className="w-full h-12 bg-[#C41E3A] hover:bg-[#A31830] text-white disabled:opacity-50"
            >
              确认提现
            </Button>

            {/* 提示信息 */}
            <div className="text-xs text-[#5C4033]/60 space-y-1">
              <p>• 支付宝提现预计2小时内到账</p>
              <p>• 银行卡提现预计1-3个工作日到账</p>
              <p>• 请确保收款账户信息准确无误</p>
            </div>
          </div>
        )}
      </DataState>

      {/* 支付密码弹窗 */}
      {showPasswordModal && (
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50">
          <div className="w-full bg-white rounded-t-2xl p-4 animate-in slide-in-from-bottom">
            <div className="flex items-center justify-between mb-6">
              <div className="w-8" />
              <h3 className="text-lg font-medium text-[#2F1810]">请输入支付密码</h3>
              <button onClick={() => setShowPasswordModal(false)} className="p-1">
                <X className="w-5 h-5 text-[#5C4033]/60" />
              </button>
            </div>

            <div className="flex justify-center gap-3 mb-6">
              {password.map((p, i) => (
                <div key={i} className="relative">
                  <input
                    ref={(el) => { passwordInputRefs.current[i] = el }}
                    type="password"
                    inputMode="numeric"
                    maxLength={1}
                    value={p}
                    onChange={(e) => handlePasswordInput(i, e.target.value)}
                    onKeyDown={(e) => handlePasswordKeyDown(i, e)}
                    disabled={verifying}
                    className="w-12 h-14 text-center text-2xl font-bold border-2 border-[#C9A96E]/30 rounded-lg focus:border-[#C41E3A] focus:outline-none disabled:opacity-50"
                  />
                  {p && (
                    <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                      <div className="w-3 h-3 bg-[#2F1810] rounded-full" />
                    </div>
                  )}
                </div>
              ))}
            </div>

            {verifying && (
              <div className="flex items-center justify-center gap-2 text-[#5C4033]/70">
                <div className="w-4 h-4 border-2 border-[#C41E3A] border-t-transparent rounded-full animate-spin" />
                <span>验证中...</span>
              </div>
            )}

            <button className="w-full text-center text-sm text-[#C41E3A] mt-4 py-2">
              忘记支付密码？
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
