// v0-reference/proto-ref-app/merchant/product-edit/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import Link from "next/link"
import { useRouter, useSearchParams } from "next/navigation"
import { ArrowLeft, Camera, Plus, X, Save, Send, Loader2, Info } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { cn } from "@/lib/utils"

const categories = [
  { id: "guoxue", name: "国学课程", fee: "5%" },
  { id: "guji", name: "古籍图书", fee: "3%" },
  { id: "wenchuang", name: "文创用品", fee: "5%" },
  { id: "wenfang", name: "文房四宝", fee: "5%" },
  { id: "chadao", name: "茶道用品", fee: "5%" },
  { id: "mingli", name: "命理咨询", fee: "10%" },
  { id: "fengshui", name: "风水服务", fee: "10%" },
  { id: "shufa", name: "书法字画", fee: "8%" },
]

function ProductEditContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const productId = searchParams.get("id")
  const isEdit = !!productId
  
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [formData, setFormData] = useState({
    images: [] as string[],
    title: "",
    subtitle: "",
    description: "",
    price: "",
    originalPrice: "",
    stock: "",
    category: "",
    tags: [] as string[],
    isVirtual: false,
    allowRefund: true,
    limitPerPerson: "",
  })
  const [newTag, setNewTag] = useState("")
  
  useEffect(() => {
    if (isEdit) {
      setFormData({
        images: ["1", "2"],
        title: "滴天髓精解",
        subtitle: "命理学经典著作精装版",
        description: "详细描述内容...",
        price: "68",
        originalPrice: "98",
        stock: "156",
        category: "guji",
        tags: ["命理", "八字", "经典"],
        isVirtual: false,
        allowRefund: true,
        limitPerPerson: "",
      })
    }
  }, [isEdit])
  
  const addTag = () => {
    if (newTag && !formData.tags.includes(newTag) && formData.tags.length < 5) {
      setFormData(prev => ({ ...prev, tags: [...prev.tags, newTag] }))
      setNewTag("")
    }
  }
  
  const removeTag = (tag: string) => {
    setFormData(prev => ({ ...prev, tags: prev.tags.filter(t => t !== tag) }))
  }
  
  const handleSaveDraft = async () => {
    setIsSaving(true)
    await new Promise(resolve => setTimeout(resolve, 1000))
    setIsSaving(false)
  }
  
  const handlePublish = async () => {
    if (!formData.title || !formData.price || !formData.stock || !formData.category) {
      alert("请填写必填项")
      return
    }
    setIsSubmitting(true)
    await new Promise(resolve => setTimeout(resolve, 1500))
    setIsSubmitting(false)
    router.push("/merchant/products")
  }

  const selectedCategory = categories.find(c => c.id === formData.category)

  return (
    <div className="min-h-screen bg-background pb-32">
      <header className="sticky top-0 z-50 bg-background border-b border-border">
        <div className="flex items-center h-14 px-4">
          <Link href="/merchant/products" className="mr-3">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-lg font-semibold">{isEdit ? "编辑商品" : "发布商品"}</h1>
        </div>
      </header>
      
      <div className="p-4 space-y-4">
        {/* 商品图片 */}
        <Card className="p-4">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-medium">商品图片</h2>
            <span className="text-xs text-muted-foreground">最多9张，首图为封面</span>
          </div>
          <div className="grid grid-cols-3 gap-3">
            {formData.images.map((_, index) => (
              <div key={index} className="aspect-square rounded-lg bg-muted relative overflow-hidden border-2 border-dashed border-border">
                <div className="absolute inset-0 flex items-center justify-center">
                  <Camera className="w-8 h-8 text-muted-foreground" />
                </div>
                <button 
                  onClick={() => setFormData(prev => ({ ...prev, images: prev.images.filter((_, i) => i !== index) }))} 
                  className="absolute top-1 right-1 w-6 h-6 rounded-full bg-black/50 flex items-center justify-center"
                >
                  <X className="w-4 h-4 text-white" />
                </button>
                {index === 0 && (
                  <Badge className="absolute bottom-1 left-1 text-[10px]">封面</Badge>
                )}
              </div>
            ))}
            {formData.images.length < 9 && (
              <button 
                onClick={() => setFormData(prev => ({ ...prev, images: [...prev.images, String(prev.images.length + 1)] }))}
                className="aspect-square rounded-lg border-2 border-dashed border-border flex flex-col items-center justify-center hover:border-primary hover:bg-primary/5 transition-colors"
              >
                <Plus className="w-8 h-8 text-muted-foreground" />
                <span className="text-xs text-muted-foreground mt-1">添加图片</span>
              </button>
            )}
          </div>
        </Card>
        
        {/* 基本信息 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">基本信息</h2>
          
          <div className="space-y-2">
            <Label>商品名称 <span className="text-destructive">*</span></Label>
            <Input 
              placeholder="请输入商品名称（最多60字）" 
              value={formData.title} 
              onChange={e => setFormData(prev => ({ ...prev, title: e.target.value }))} 
              maxLength={60}
            />
            <p className="text-xs text-muted-foreground text-right">{formData.title.length}/60</p>
          </div>
          
          <div className="space-y-2">
            <Label>商品卖点</Label>
            <Input 
              placeholder="简要描述商品特点（最多30字）" 
              value={formData.subtitle} 
              onChange={e => setFormData(prev => ({ ...prev, subtitle: e.target.value }))} 
              maxLength={30}
            />
          </div>
          
          <div className="space-y-2">
            <Label>商品详情</Label>
            <Textarea 
              placeholder="详细描述商品信息、规格、使用方法等" 
              value={formData.description} 
              onChange={e => setFormData(prev => ({ ...prev, description: e.target.value }))} 
              rows={5}
            />
          </div>
        </Card>
        
        {/* 价格库存 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">价格库存</h2>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>售价 <span className="text-destructive">*</span></Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">¥</span>
                <Input 
                  type="number" 
                  placeholder="0.00" 
                  value={formData.price} 
                  onChange={e => setFormData(prev => ({ ...prev, price: e.target.value }))} 
                  className="pl-8"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label>原价（划线价）</Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">¥</span>
                <Input 
                  type="number" 
                  placeholder="0.00" 
                  value={formData.originalPrice} 
                  onChange={e => setFormData(prev => ({ ...prev, originalPrice: e.target.value }))} 
                  className="pl-8"
                />
              </div>
            </div>
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>库存 <span className="text-destructive">*</span></Label>
              <Input 
                type="number" 
                placeholder="请输入库存数量" 
                value={formData.stock} 
                onChange={e => setFormData(prev => ({ ...prev, stock: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <Label>限购数量</Label>
              <Input 
                type="number" 
                placeholder="不限制" 
                value={formData.limitPerPerson} 
                onChange={e => setFormData(prev => ({ ...prev, limitPerPerson: e.target.value }))}
              />
            </div>
          </div>
        </Card>
        
        {/* 分类与标签 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">分类与标签</h2>
          
          <div className="space-y-2">
            <Label>商品分类 <span className="text-destructive">*</span></Label>
            <Select value={formData.category} onValueChange={value => setFormData(prev => ({ ...prev, category: value }))}>
              <SelectTrigger>
                <SelectValue placeholder="请选择商品分类" />
              </SelectTrigger>
              <SelectContent>
                {categories.map(cat => (
                  <SelectItem key={cat.id} value={cat.id}>
                    <div className="flex items-center justify-between w-full">
                      <span>{cat.name}</span>
                      <span className="text-xs text-muted-foreground ml-2">佣金{cat.fee}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {selectedCategory && (
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <Info className="w-3 h-3" />
                该分类平台收取 {selectedCategory.fee} 技术服务费
              </p>
            )}
          </div>
          
          <div className="space-y-2">
            <Label>商品标签（最多5个）</Label>
            <div className="flex flex-wrap gap-2 mb-2">
              {formData.tags.map(tag => (
                <Badge key={tag} variant="secondary" className="gap-1">
                  {tag}
                  <button onClick={() => removeTag(tag)}>
                    <X className="w-3 h-3" />
                  </button>
                </Badge>
              ))}
            </div>
            <div className="flex gap-2">
              <Input 
                placeholder="输入标签后回车添加" 
                value={newTag} 
                onChange={e => setNewTag(e.target.value)} 
                onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addTag())} 
                className="flex-1"
              />
              <Button variant="outline" onClick={addTag} disabled={formData.tags.length >= 5}>
                <Plus className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </Card>
        
        {/* 其他设置 */}
        <Card className="p-4 space-y-4">
          <h2 className="font-medium">其他设置</h2>
          
          <div className="flex items-center justify-between">
            <div>
              <Label>虚拟商品</Label>
              <p className="text-xs text-muted-foreground mt-0.5">虚拟商品无需发货</p>
            </div>
            <Switch 
              checked={formData.isVirtual}
              onCheckedChange={checked => setFormData(prev => ({ ...prev, isVirtual: checked }))}
            />
          </div>
          
          <div className="flex items-center justify-between">
            <div>
              <Label>支持退款</Label>
              <p className="text-xs text-muted-foreground mt-0.5">买家可申请退款退货</p>
            </div>
            <Switch 
              checked={formData.allowRefund}
              onCheckedChange={checked => setFormData(prev => ({ ...prev, allowRefund: checked }))}
            />
          </div>
        </Card>
      </div>
      
      {/* 底部操作栏 */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t border-border safe-area-bottom">
        <div className="flex gap-3">
          <Button 
            variant="outline" 
            className="flex-1" 
            onClick={handleSaveDraft} 
            disabled={isSaving}
          >
            {isSaving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
            保存草稿
          </Button>
          <Button 
            className="flex-1" 
            onClick={handlePublish} 
            disabled={isSubmitting}
          >
            {isSubmitting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
            {isEdit ? "保存修改" : "立即发布"}
          </Button>
        </div>
      </div>
    </div>
  )
}

export default function ProductEditPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    }>
      <ProductEditContent />
    </Suspense>
  )
}

// apps/mobile/src/pkg-merchant/product-edit/index.vue
<template>
  <view class="pe-page">
    <!-- 顶部导航 -->
    <view class="pe-header" :style="{ paddingTop: statusBarHeight + 'px' }">
      <view class="pe-header-inner">
        <view class="pe-back" @tap="go('/merchant/products')">
          <AppIcon name="arrow-left" :size="20" color="#1a1a1a" />
        </view>
        <text class="pe-title">{{ isEdit ? '编辑商品' : '发布商品' }}</text>
      </view>
    </view>

    <scroll-view scroll-y class="pe-scroll" :style="{ paddingTop: statusBarHeight + 44 + 'px' }">
      <view class="pe-body">
        <!-- 商品图片 -->
        <view class="pe-card">
          <view class="pe-card-head">
            <text class="pe-card-title">商品图片</text>
            <text class="pe-card-sub">最多9张，首图为封面</text>
          </view>
          <view class="pe-img-grid">
            <view v-for="(img, i) in form.images" :key="i" class="pe-img">
              <AppIcon name="camera" :size="28" color="#9ca3af" />
              <view class="pe-img-del" @tap="removeImage(i)">
                <AppIcon name="x" :size="14" color="#fff" />
              </view>
              <text v-if="i === 0" class="pe-img-cover">封面</text>
            </view>
            <view v-if="form.images.length < 9" class="pe-img-add" @tap="addImage">
              <AppIcon name="plus" :size="28" color="#9ca3af" />
              <text class="pe-img-add-txt">添加图片</text>
            </view>
          </view>
        </view>

        <!-- 基本信息 -->
        <view class="pe-card">
          <text class="pe-card-title pe-mb">基本信息</text>
          <view class="pe-field">
            <text class="pe-label">商品名称 <text class="pe-req">*</text></text>
            <input class="pe-input" v-model="form.title" maxlength="60" placeholder="请输入商品名称（最多60字）" placeholder-class="pe-ph" />
            <text class="pe-count">{{ form.title.length }}/60</text>
          </view>
          <view class="pe-field">
            <text class="pe-label">商品卖点</text>
            <input class="pe-input" v-model="form.subtitle" maxlength="30" placeholder="简要描述商品特点（最多30字）" placeholder-class="pe-ph" />
          </view>
          <view class="pe-field">
            <text class="pe-label">商品详情</text>
            <textarea class="pe-textarea" v-model="form.description" placeholder="详细描述商品信息、规格、使用方法等" placeholder-class="pe-ph" />
          </view>
        </view>

        <!-- 价格库存 -->
        <view class="pe-card">
          <text class="pe-card-title pe-mb">价格库存</text>
          <view class="pe-grid2">
            <view class="pe-field">
              <text class="pe-label">售价 <text class="pe-req">*</text></text>
              <view class="pe-input-prefix">
                <text class="pe-prefix">¥</text>
                <input class="pe-input pe-input-pl" type="digit" v-model="form.price" placeholder="0.00" placeholder-class="pe-ph" />
              </view>
            </view>
            <view class="pe-field">
              <text class="pe-label">原价（划线价）</text>
              <view class="pe-input-prefix">
                <text class="pe-prefix">¥</text>
                <input class="pe-input pe-input-pl" type="digit" v-model="form.originalPrice" placeholder="0.00" placeholder-class="pe-ph" />
              </view>
            </view>
          </view>
          <view class="pe-grid2">
            <view class="pe-field">
              <text class="pe-label">库存 <text class="pe-req">*</text></text>
              <input class="pe-input" type="number" v-model="form.stock" placeholder="请输入库存数量" placeholder-class="pe-ph" />
            </view>
            <view class="pe-field">
              <text class="pe-label">限购数量</text>
              <input class="pe-input" type="number" v-model="form.limitPerPerson" placeholder="不限制" placeholder-class="pe-ph" />
            </view>
          </view>
        </view>

        <!-- 分类与标签 -->
        <view class="pe-card">
          <text class="pe-card-title pe-mb">分类与标签</text>
          <view class="pe-field">
            <text class="pe-label">商品分类 <text class="pe-req">*</text></text>
            <view class="pe-select" @tap="showCatPicker = true">
              <text :class="form.category ? 'pe-select-val' : 'pe-select-ph'">
                {{ selectedCategory ? selectedCategory.name : '请选择商品分类' }}
              </text>
              <AppIcon name="chevron-right" :size="16" color="#9ca3af" />
            </view>
            <view v-if="selectedCategory" class="pe-fee-tip">
              <AppIcon name="info" :size="12" color="#9ca3af" />
              <text>该分类平台收取 {{ selectedCategory.fee }} 技术服务费</text>
            </view>
          </view>
          <view class="pe-field">
            <text class="pe-label">商品标签（最多5个）</text>
            <view v-if="form.tags.length" class="pe-tags">
              <view v-for="tag in form.tags" :key="tag" class="pe-tag">
                <text>{{ tag }}</text>
                <view @tap="removeTag(tag)"><AppIcon name="x" :size="12" color="#6b7280" /></view>
              </view>
            </view>
            <view class="pe-tag-input-row">
              <input class="pe-input pe-tag-input" v-model="newTag" placeholder="输入标签后点击添加" placeholder-class="pe-ph" @confirm="addTag" />
              <view class="pe-tag-add" :class="{ disabled: form.tags.length >= 5 }" @tap="addTag">
                <AppIcon name="plus" :size="16" color="#1a1a1a" />
              </view>
            </view>
          </view>
        </view>

        <!-- 其他设置 -->
        <view class="pe-card">
          <text class="pe-card-title pe-mb">其他设置</text>
          <view class="pe-switch-row">
            <view>
              <text class="pe-switch-label">虚拟商品</text>
              <text class="pe-switch-desc">虚拟商品无需发货</text>
            </view>
            <view class="pe-switch" :class="{ on: form.isVirtual }" @tap="form.isVirtual = !form.isVirtual">
              <view class="pe-switch-knob" />
            </view>
          </view>
          <view class="pe-switch-row">
            <view>
              <text class="pe-switch-label">支持退款</text>
              <text class="pe-switch-desc">买家可申请退款退货</text>
            </view>
            <view class="pe-switch" :class="{ on: form.allowRefund }" @tap="form.allowRefund = !form.allowRefund">
              <view class="pe-switch-knob" />
            </view>
          </view>
        </view>
      </view>
      <view style="height: 90px" />
    </scroll-view>

    <!-- 底部操作栏 -->
    <view class="pe-footer">
      <view class="pe-foot-btn outline" @tap="saveDraft">
        <AppIcon name="save" :size="16" color="#1a1a1a" />
        <text>{{ isSaving ? '保存中...' : '保存草稿' }}</text>
      </view>
      <view class="pe-foot-btn primary" @tap="publish">
        <AppIcon name="send" :size="16" color="#fff" />
        <text>{{ isSubmitting ? '提交中...' : isEdit ? '保存修改' : '立即发布' }}</text>
      </view>
    </view>

    <!-- 分类选择浮层 -->
    <view v-if="showCatPicker" class="pe-mask" @tap="showCatPicker = false">
      <view class="pe-sheet" @tap.stop>
        <text class="pe-sheet-title">选择商品分类</text>
        <scroll-view scroll-y class="pe-sheet-list">
          <view
            v-for="cat in categories"
            :key="cat.id"
            class="pe-sheet-item"
            :class="{ active: form.category === cat.id }"
            @tap="pickCategory(cat.id)"
          >
            <text>{{ cat.name }}</text>
            <text class="pe-sheet-fee">佣金{{ cat.fee }}</text>
          </view>
        </scroll-view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import AppIcon from '@/components/common/app-icon.vue'
import { navigateTo } from '@/utils/router'
import { productCategories, productEditPreset } from '@/lib/merchant-data'

const statusBarHeight = ref(0)
uni.getSystemInfo({ success: (e) => { statusBarHeight.value = e.statusBarHeight || 0 } })

const categories = productCategories
const isEdit = ref(false)
const showCatPicker = ref(false)
const newTag = ref('')
const isSaving = ref(false)
const isSubmitting = ref(false)

const form = ref({
  images: [] as string[],
  title: '',
  subtitle: '',
  description: '',
  price: '',
  originalPrice: '',
  stock: '',
  category: '',
  tags: [] as string[],
  isVirtual: false,
  allowRefund: true,
  limitPerPerson: '',
})

onLoad((opts: any) => {
  if (opts?.id) {
    isEdit.value = true
    form.value = { ...productEditPreset, images: [...productEditPreset.images], tags: [...productEditPreset.tags] }
  }
})

const selectedCategory = computed(() => categories.find((c) => c.id === form.value.category))

function addImage() {
  uni.chooseImage({
    count: 1,
    success: () => {
      form.value.images.push(String(form.value.images.length + 1))
    },
  })
}
function removeImage(i: number) {
  form.value.images.splice(i, 1)
}
function pickCategory(id: string) {
  form.value.category = id
  showCatPicker.value = false
}
function addTag() {
  const t = newTag.value.trim()
  if (t && !form.value.tags.includes(t) && form.value.tags.length < 5) {
    form.value.tags.push(t)
    newTag.value = ''
  }
}
function removeTag(tag: string) {
  form.value.tags = form.value.tags.filter((t) => t !== tag)
}
function saveDraft() {
  isSaving.value = true
  setTimeout(() => {
    isSaving.value = false
    uni.showToast({ title: '已保存草稿', icon: 'success' })
  }, 1000)
}
function publish() {
  if (!form.value.title || !form.value.price || !form.value.stock || !form.value.category) {
    uni.showToast({ title: '请填写必填项', icon: 'none' })
    return
  }
  isSubmitting.value = true
  setTimeout(() => {
    isSubmitting.value = false
    navigateTo('/merchant/products')
  }, 1500)
}
function go(path: string) {
  navigateTo(path)
}
</script>

<style scoped>
.pe-page { min-height: 100vh; background: #f5f5f7; }
.pe-header { position: fixed; top: 0; left: 0; right: 0; z-index: 50; background: #fff; border-bottom: 1px solid #ededed; }
.pe-header-inner { height: 44px; display: flex; align-items: center; padding: 0 16px; }
.pe-back { width: 32px; display: flex; align-items: center; }
.pe-title { font-size: 18px; font-weight: 600; color: #1a1a1a; }
.pe-scroll { height: 100vh; box-sizing: border-box; }
.pe-body { padding: 16px; display: flex; flex-direction: column; gap: 16px; }
.pe-card { background: #fff; border-radius: 12px; padding: 16px; }
.pe-card-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }
.pe-card-title { font-size: 15px; font-weight: 500; color: #1a1a1a; }
.pe-mb { margin-bottom: 16px; display: block; }
.pe-card-sub { font-size: 12px; color: #9ca3af; }

.pe-img-grid { display: flex; flex-wrap: wrap; gap: 12px; }
.pe-img, .pe-img-add { width: calc((100% - 24px) / 3); aspect-ratio: 1; border-radius: 8px; position: relative; display: flex; flex-direction: column; align-items: center; justify-content: center; }
.pe-img { background: #f3f0ea; border: 2px dashed #e5e5e5; }
.pe-img-add { border: 2px dashed #e5e5e5; }
.pe-img-del { position: absolute; top: 4px; right: 4px; width: 22px; height: 22px; border-radius: 50%; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; }
.pe-img-cover { position: absolute; bottom: 4px; left: 4px; font-size: 10px; color: #fff; background: #c41e3a; padding: 1px 6px; border-radius: 4px; }
.pe-img-add-txt { font-size: 12px; color: #9ca3af; margin-top: 4px; }

.pe-field { margin-bottom: 16px; }
.pe-field:last-child { margin-bottom: 0; }
.pe-label { font-size: 14px; color: #1a1a1a; display: block; margin-bottom: 8px; }
.pe-req { color: #ef4444; }
.pe-input { width: 100%; box-sizing: border-box; height: 42px; border: 1px solid #e5e5e5; border-radius: 8px; padding: 0 12px; font-size: 14px; color: #1a1a1a; background: #fff; }
.pe-ph { color: #9ca3af; }
.pe-count { font-size: 12px; color: #9ca3af; text-align: right; display: block; margin-top: 4px; }
.pe-textarea { width: 100%; box-sizing: border-box; min-height: 100px; border: 1px solid #e5e5e5; border-radius: 8px; padding: 10px 12px; font-size: 14px; color: #1a1a1a; }
.pe-grid2 { display: flex; gap: 16px; }
.pe-grid2 .pe-field { flex: 1; }
.pe-input-prefix { position: relative; display: flex; align-items: center; }
.pe-prefix { position: absolute; left: 12px; font-size: 14px; color: #9ca3af; z-index: 1; }
.pe-input-pl { padding-left: 26px; }

.pe-select { height: 42px; border: 1px solid #e5e5e5; border-radius: 8px; padding: 0 12px; display: flex; align-items: center; justify-content: space-between; }
.pe-select-val { font-size: 14px; color: #1a1a1a; }
.pe-select-ph { font-size: 14px; color: #9ca3af; }
.pe-fee-tip { display: flex; align-items: center; gap: 4px; margin-top: 6px; font-size: 12px; color: #9ca3af; }
.pe-tags { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 8px; }
.pe-tag { display: flex; align-items: center; gap: 4px; background: #f3f4f6; padding: 4px 8px; border-radius: 6px; font-size: 12px; color: #1a1a1a; }
.pe-tag-input-row { display: flex; gap: 8px; }
.pe-tag-input { flex: 1; }
.pe-tag-add { width: 42px; height: 42px; border: 1px solid #e5e5e5; border-radius: 8px; display: flex; align-items: center; justify-content: center; }
.pe-tag-add.disabled { opacity: 0.4; }

.pe-switch-row { display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; }
.pe-switch-row:last-child { margin-bottom: 0; }
.pe-switch-label { font-size: 14px; color: #1a1a1a; display: block; }
.pe-switch-desc { font-size: 12px; color: #9ca3af; margin-top: 2px; display: block; }
.pe-switch { width: 44px; height: 24px; border-radius: 12px; background: #d1d5db; position: relative; transition: background 0.2s; }
.pe-switch.on { background: #c41e3a; }
.pe-switch-knob { position: absolute; top: 2px; left: 2px; width: 20px; height: 20px; border-radius: 50%; background: #fff; transition: transform 0.2s; }
.pe-switch.on .pe-switch-knob { transform: translateX(20px); }

.pe-footer { position: fixed; bottom: 0; left: 0; right: 0; background: #fff; border-top: 1px solid #ededed; padding: 12px 16px; padding-bottom: calc(12px + env(safe-area-inset-bottom)); display: flex; gap: 12px; z-index: 60; }
.pe-foot-btn { flex: 1; height: 44px; border-radius: 8px; display: flex; align-items: center; justify-content: center; gap: 6px; font-size: 15px; }
.pe-foot-btn.outline { border: 1px solid #d1d5db; color: #1a1a1a; }
.pe-foot-btn.primary { background: #c41e3a; color: #fff; }

.pe-mask { position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 100; display: flex; align-items: flex-end; }
.pe-sheet { width: 100%; background: #fff; border-radius: 16px 16px 0 0; padding: 16px; padding-bottom: calc(16px + env(safe-area-inset-bottom)); }
.pe-sheet-title { font-size: 16px; font-weight: 600; color: #1a1a1a; display: block; text-align: center; margin-bottom: 12px; }
.pe-sheet-list { max-height: 50vh; }
.pe-sheet-item { display: flex; align-items: center; justify-content: space-between; padding: 14px 4px; border-bottom: 1px solid #f3f4f6; font-size: 15px; color: #1a1a1a; }
.pe-sheet-item.active { color: #c41e3a; }
.pe-sheet-fee { font-size: 12px; color: #9ca3af; }
</style>
