// apps/mobile/src/pages/offline/stations/index.vue
<template>
  <view class="page">
    <view class="v0-header">
      <text class="v0-title">线下</text>
      <text class="v0-route">V0: offline/stations</text>
    </view>
        <view class="min-h-screen bg-background">
          <!--   -->
          <view class="sticky top-0 z-50 bg-background border-b">
            <view class="flex items-center justify-between px-4 h-14">
              <BackButton fallbackPath="/discover" />
              <text class="text-lg font-semibold">线下驿站</text>
              <view class="flex items-center gap-2">
                <view class="v0-btn"
                  @click={() => setViewMode(viewMode === 'list' ? 'map' : 'list')}
                  class="p-2 rounded-full hover:bg-muted"
                >
                  {viewMode === 'list' ? <MapIcon class="w-5 h-5" /> : <List class="w-5 h-5" />}
                </view>
              </view>
            </view>
    
            <!--   -->
            <view class="px-4 pb-3">
              <view class="relative">
                <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="搜索驿站名称或地址"
                  value={{ searchKeyword }}
                  @change={(e) => setSearchKeyword(e.target.value)}
                  class="w-full h-10 pl-10 pr-4 rounded-full bg-muted text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                />
              </view>
            </view>
    
            <!--   -->
            <view class="px-4 pb-3 flex gap-2 overflow-x-auto scrollbar-hide">
              
    <view v-for="(type, index) in stationTypes" :key="index"> (
                <view class="v0-btn"
                  key={{ type.value }}
                  @click={() => setSelectedType(type.value)}
                  class={cn(
                    "px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors",
                    selectedType === type.value
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground hover:bg-muted/80"
                  )}
                >
                  {{ type.label }}
                </view>
              ))}
            </view>
          </view>
    
          <!--   -->
          <view class="p-4 space-y-6">
            <!--   -->
            {nearbyStations.length > 0 && !searchKeyword && selectedType === 'all' && (
              <view>
                <view class="flex items-center justify-between mb-3">
                  <text class="font-semibold flex items-center gap-2">
                    <MapPin class="w-4 h-4 text-primary" />
                    附近驿站
                  </text>
                </view>
                <view class="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">
                  
    <view v-for="(station, index) in nearbyStations" :key="index"> (
                    <Link
                      key={station.id}
                      href={`/offline/stations/${station.id}`}
                      class="flex-shrink-0 w-64"
                    >
                      <Card class="overflow-hidden">
                        <view class="relative h-32">
                          <image
                            src={{ station.cover }}
                            alt={{ station.name }}
                            class="w-full h-full object-cover"
                          />
                          <Badge class="absolute top-2 left-2 bg-primary/90">
                            {{ formatDistance(station.distance) }}
                          </Badge>
                        </view>
                        <view class="p-3">
                          <text class="font-medium text-sm line-clamp-1">{{ station.name }}</text>
                          <text class="text-xs text-muted-foreground mt-1 line-clamp-1">
                            {{ station.address }}
                          </text>
                        </view>
                      </Card>
                    </Link>
                  ))}
                </view>
              </view>
            )}
    
            <!--   -->
            <view>
              <text class="font-semibold mb-3">
                {searchKeyword ? '搜索结果' : '全部驿站'}
                {!isLoading && <text class="text-muted-foreground font-normal text-sm ml-2">({{ stations.length }})</text>}
              </text>
    
              {isLoading ? (
                <view class="space-y-4">
                  {[1, 2, 3].map((i) => (
                    <Card key={i} class="p-4">
                      <view class="flex gap-4">
                        <Skeleton class="w-24 h-24 rounded-lg flex-shrink-0" />
                        <view class="flex-1 space-y-2">
                          <Skeleton class="h-5 w-3/4" />
                          <Skeleton class="h-4 w-full" />
                          <Skeleton class="h-4 w-1/2" />
                        </view>
                      </view>
                    </Card>
                  ))}
                </view>
              ) : stations.length === 0 ? (
                <view class="text-center py-12">
                  <MapPin class="w-12 h-12 mx-auto text-muted-foreground/50" />
                  <text class="mt-4 text-muted-foreground">暂无驿站</text>
                </view>
              ) : (
                <view class="space-y-4">
                  
    <view v-for="(station, index) in stations" :key="index"> (
                    <Link key={station.id} href={`/offline/stations/${station.id}`}>
                      <Card class="overflow-hidden hover:shadow-md transition-shadow">
                        <view class="flex">
                          <!--   -->
                          <view class="relative w-28 h-28 flex-shrink-0">
                            <image
                              src={{ station.cover }}
                              alt={{ station.name }}
                              class="w-full h-full object-cover"
                            />
                            {station.status !== 'open' && (
                              <view class="absolute inset-0 bg-black/50 flex items-center justify-center">
                                <text class="text-white text-xs">
                                  {station.status === 'closed' ? '暂停营业' : '装修中'}
                                </text>
                              </view>
                            )}
                          </view>
    
                          <!--   -->
                          <view class="flex-1 p-3 flex flex-col">
                            <view class="flex items-start justify-between gap-2">
                              <view class="flex-1 min-w-0">
                                <view class="flex items-center gap-2">
                                  <text class="font-medium text-sm line-clamp-1">{{ station.name }}</text>
                                  <Badge variant="outline" class="text-xs flex-shrink-0">
                                    {{ getStationTypeLabel(station.type) }}
                                  </Badge>
                                </view>
                                <view class="flex items-center gap-1 mt-1 text-xs text-amber-500">
                                  <Star class="w-3 h-3 fill-current" />
                                  <text>{{ station.rating }}</text>
                                  <text class="text-muted-foreground">({{ station.reviewCount }}评价)</text>
                                </view>
                              </view>
                              <view class="v0-btn"
                                @click={(e) => handleToggleFavorite(station.id, e)}
                                class="p-1"
                              >
                                <Heart
                                  class={cn(
                                    "w-5 h-5",
                                    station.isFavorited ? "fill-red-500 text-red-500" : "text-muted-foreground"
                                  )}
                                />
                              </view>
                            </view>
    
                            <text class="text-xs text-muted-foreground mt-1 line-clamp-1 flex items-center gap-1">
                              <MapPin class="w-3 h-3 flex-shrink-0" />
                              {{ station.address }}
                            </text>
    
                            <!--   -->
                            <view class="flex items-center gap-2 mt-2">
                              {station.facilities.slice(0, 4).map((f) => (
                                <text key={f} class="text-muted-foreground" title={{ f }}>
                                  {{ facilityIcons[f] }}
                                </text>
                              ))}
                              {station.facilities.length > 4 && (
                                <text class="text-xs text-muted-foreground">
                                  +{{ station.facilities.length - 4 }}
                                </text>
                              )}
                            </view>
    
                            <!--   -->
                            <view class="flex items-center justify-between mt-auto pt-2">
                              {station.distance && (
                                <text class="text-xs text-primary">
                                  {{ formatDistance(station.distance) }}
                                </text>
                              )}
                              <view class="v0-btn"
                                @click={(e) => handleNavigate(station, e)}
                                class="flex items-center gap-1 text-xs text-primary"
                              >
                                <Navigation class="w-3 h-3" />
                                导航
                              </view>
                            </view>
                          </view>
                        </view>
                      </Card>
                    </Link>
                  ))}
                </view>
              )}
            </view>
          </view>
        </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { onPullDownRefresh } from '@dcloudio/uni-app'

const loading = ref(true)
const error = ref<string | null>(null)

// V0 原始数据
const stationTypes: { value: StationType | 'all'; label: string }[] = [
const facilityIcons: Record<string, React.ReactNode> = {

async function fetchData() {
  loading.value = true
  try { loading.value = false } catch (e: any) { error.value = e.message }
}

onMounted(() => fetchData())
onPullDownRefresh(() => fetchData().finally(() => uni.stopPullDownRefresh()))
</script>

<style scoped>
.page {
  background: #FAF8F5;
  min-height: 100vh;
}
.v0-header {
  padding: 24rpx 32rpx;
  background: linear-gradient(135deg, #C41E3A, #8B0000);
  margin-bottom: 24rpx;
}
.v0-title {
  font-size: 36rpx;
  font-weight: 700;
  color: #FFFFFF;
  display: block;
}
.v0-route {
  font-size: 20rpx;
  color: rgba(255,255,255,0.6);
  margin-top: 4rpx;
  display: block;
}
.v0-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 16rpx 32rpx;
  border-radius: 12rpx;
  background: #C41E3A;
  color: #FFFFFF;
  font-size: 28rpx;
}
.v0-hr {
  height: 1px;
  background: #E8E0D5;
  margin: 24rpx 0;
}
</style>

// app/offline/stations/page.tsx
"use client"

import { useState, useEffect } from "react"
import { BackButton } from "@/components/common/back-button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"
import Link from "next/link"
import { 
  MapPin, 
  Phone, 
  Star, 
  Heart, 
  Navigation, 
  List, 
  Map as MapIcon,
  Search,
  Filter,
  Wifi,
  Car,
  Coffee,
  BookOpen,
  Users,
  MessageCircle,
  ChevronRight,
  Loader2
} from "lucide-react"
import { 
  getStationList, 
  getNearbyStations,
  getStationTypeLabel, 
  formatDistance,
  getNavigationUrl,
  toggleStationFavorite
} from "@/lib/api/offline"
import type { Station, StationType } from "@/lib/types/offline"
import { toast } from "sonner"

// 驿站类型筛选
const stationTypes: { value: StationType | 'all'; label: string }[] = [
  { value: 'all', label: '全部' },
  { value: 'center', label: '国学中心' },
  { value: 'academy', label: '书院' },
  { value: 'studio', label: '工作室' },
  { value: 'partner', label: '合作点' },
]

// 设施图标映射
const facilityIcons: Record<string, React.ReactNode> = {
  wifi: <Wifi className="w-4 h-4" />,
  parking: <Car className="w-4 h-4" />,
  tea: <Coffee className="w-4 h-4" />,
  library: <BookOpen className="w-4 h-4" />,
  classroom: <Users className="w-4 h-4" />,
  consultation: <MessageCircle className="w-4 h-4" />,
}

export default function StationsPage() {
  const [viewMode, setViewMode] = useState<'list' | 'map'>('list')
  const [selectedType, setSelectedType] = useState<StationType | 'all'>('all')
  const [searchKeyword, setSearchKeyword] = useState('')
  const [stations, setStations] = useState<Station[]>([])
  const [nearbyStations, setNearbyStations] = useState<Station[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [userLocation, setUserLocation] = useState<{ lat: number; lng: number } | null>(null)

  // 获取用户位置
  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setUserLocation({
            lat: position.coords.latitude,
            lng: position.coords.longitude,
          })
        },
        () => {
          // 定位失败，使用默认位置（北京）
          setUserLocation({ lat: 39.9042, lng: 116.4074 })
        }
      )
    } else {
      setUserLocation({ lat: 39.9042, lng: 116.4074 })
    }
  }, [])

  // 加载驿站列表
  useEffect(() => {
    loadStations()
  }, [selectedType, searchKeyword])

  // 加载附近驿站
  useEffect(() => {
    if (userLocation) {
      loadNearbyStations()
    }
  }, [userLocation])

  const loadStations = async () => {
    setIsLoading(true)
    try {
      const response = await getStationList({
        type: selectedType === 'all' ? undefined : selectedType,
        keyword: searchKeyword || undefined,
      })
      if (response.code === 200) {
        setStations(response.data.list)
      }
    } catch {
      toast.error('加载失败')
    } finally {
      setIsLoading(false)
    }
  }

  const loadNearbyStations = async () => {
    if (!userLocation) return
    try {
      const response = await getNearbyStations(userLocation.lat, userLocation.lng, 3)
      if (response.code === 200) {
        setNearbyStations(response.data)
      }
    } catch {
      // 忽略错误
    }
  }

  const handleToggleFavorite = async (id: number, e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    try {
      const response = await toggleStationFavorite(id)
      if (response.code === 200) {
        setStations(prev => prev.map(s => 
          s.id === id ? { ...s, isFavorited: response.data.isFavorited } : s
        ))
        toast.success(response.data.isFavorited ? '已收藏' : '已取消收藏')
      }
    } catch {
      toast.error('操作失败')
    }
  }

  const handleNavigate = (station: Station, e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    window.open(getNavigationUrl(station), '_blank')
  }

  return (
    <div className="min-h-screen bg-background">
      {/* 顶部导航 */}
      <header className="sticky top-0 z-50 bg-background border-b">
        <div className="flex items-center justify-between px-4 h-14">
          <BackButton fallbackPath="/discover" />
          <h1 className="text-lg font-semibold">线下驿站</h1>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setViewMode(viewMode === 'list' ? 'map' : 'list')}
              className="p-2 rounded-full hover:bg-muted"
            >
              {viewMode === 'list' ? <MapIcon className="w-5 h-5" /> : <List className="w-5 h-5" />}
            </button>
          </div>
        </div>

        {/* 搜索栏 */}
        <div className="px-4 pb-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="搜索驿站名称或地址"
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
              className="w-full h-10 pl-10 pr-4 rounded-full bg-muted text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
            />
          </div>
        </div>

        {/* 类型筛选 */}
        <div className="px-4 pb-3 flex gap-2 overflow-x-auto scrollbar-hide">
          {stationTypes.map((type) => (
            <button
              key={type.value}
              onClick={() => setSelectedType(type.value)}
              className={cn(
                "px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors",
                selectedType === type.value
                  ? "bg-primary text-primary-foreground"
                  : "bg-muted text-muted-foreground hover:bg-muted/80"
              )}
            >
              {type.label}
            </button>
          ))}
        </div>
      </header>

      {/* 内容区 */}
      <main className="p-4 space-y-6">
        {/* 附近推荐 */}
        {nearbyStations.length > 0 && !searchKeyword && selectedType === 'all' && (
          <section>
            <div className="flex items-center justify-between mb-3">
              <h2 className="font-semibold flex items-center gap-2">
                <MapPin className="w-4 h-4 text-primary" />
                附近驿站
              </h2>
            </div>
            <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">
              {nearbyStations.map((station) => (
                <Link
                  key={station.id}
                  href={`/offline/stations/${station.id}`}
                  className="flex-shrink-0 w-64"
                >
                  <Card className="overflow-hidden">
                    <div className="relative h-32">
                      <img
                        src={station.cover}
                        alt={station.name}
                        className="w-full h-full object-cover"
                      />
                      <Badge className="absolute top-2 left-2 bg-primary/90">
                        {formatDistance(station.distance)}
                      </Badge>
                    </div>
                    <div className="p-3">
                      <h3 className="font-medium text-sm line-clamp-1">{station.name}</h3>
                      <p className="text-xs text-muted-foreground mt-1 line-clamp-1">
                        {station.address}
                      </p>
                    </div>
                  </Card>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* 驿站列表 */}
        <section>
          <h2 className="font-semibold mb-3">
            {searchKeyword ? '搜索结果' : '全部驿站'}
            {!isLoading && <span className="text-muted-foreground font-normal text-sm ml-2">({stations.length})</span>}
          </h2>

          {isLoading ? (
            <div className="space-y-4">
              {[1, 2, 3].map((i) => (
                <Card key={i} className="p-4">
                  <div className="flex gap-4">
                    <Skeleton className="w-24 h-24 rounded-lg flex-shrink-0" />
                    <div className="flex-1 space-y-2">
                      <Skeleton className="h-5 w-3/4" />
                      <Skeleton className="h-4 w-full" />
                      <Skeleton className="h-4 w-1/2" />
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          ) : stations.length === 0 ? (
            <div className="text-center py-12">
              <MapPin className="w-12 h-12 mx-auto text-muted-foreground/50" />
              <p className="mt-4 text-muted-foreground">暂无驿站</p>
            </div>
          ) : (
            <div className="space-y-4">
              {stations.map((station) => (
                <Link key={station.id} href={`/offline/stations/${station.id}`}>
                  <Card className="overflow-hidden hover:shadow-md transition-shadow">
                    <div className="flex">
                      {/* 封面图 */}
                      <div className="relative w-28 h-28 flex-shrink-0">
                        <img
                          src={station.cover}
                          alt={station.name}
                          className="w-full h-full object-cover"
                        />
                        {station.status !== 'open' && (
                          <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                            <span className="text-white text-xs">
                              {station.status === 'closed' ? '暂停营业' : '装修中'}
                            </span>
                          </div>
                        )}
                      </div>

                      {/* 信息 */}
                      <div className="flex-1 p-3 flex flex-col">
                        <div className="flex items-start justify-between gap-2">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <h3 className="font-medium text-sm line-clamp-1">{station.name}</h3>
                              <Badge variant="outline" className="text-xs flex-shrink-0">
                                {getStationTypeLabel(station.type)}
                              </Badge>
                            </div>
                            <div className="flex items-center gap-1 mt-1 text-xs text-amber-500">
                              <Star className="w-3 h-3 fill-current" />
                              <span>{station.rating}</span>
                              <span className="text-muted-foreground">({station.reviewCount}评价)</span>
                            </div>
                          </div>
                          <button
                            onClick={(e) => handleToggleFavorite(station.id, e)}
                            className="p-1"
                          >
                            <Heart
                              className={cn(
                                "w-5 h-5",
                                station.isFavorited ? "fill-red-500 text-red-500" : "text-muted-foreground"
                              )}
                            />
                          </button>
                        </div>

                        <p className="text-xs text-muted-foreground mt-1 line-clamp-1 flex items-center gap-1">
                          <MapPin className="w-3 h-3 flex-shrink-0" />
                          {station.address}
                        </p>

                        {/* 设施标签 */}
                        <div className="flex items-center gap-2 mt-2">
                          {station.facilities.slice(0, 4).map((f) => (
                            <span key={f} className="text-muted-foreground" title={f}>
                              {facilityIcons[f]}
                            </span>
                          ))}
                          {station.facilities.length > 4 && (
                            <span className="text-xs text-muted-foreground">
                              +{station.facilities.length - 4}
                            </span>
                          )}
                        </div>

                        {/* 底部操作 */}
                        <div className="flex items-center justify-between mt-auto pt-2">
                          {station.distance && (
                            <span className="text-xs text-primary">
                              {formatDistance(station.distance)}
                            </span>
                          )}
                          <button
                            onClick={(e) => handleNavigate(station, e)}
                            className="flex items-center gap-1 text-xs text-primary"
                          >
                            <Navigation className="w-3 h-3" />
                            导航
                          </button>
                        </div>
                      </div>
                    </div>
                  </Card>
                </Link>
              ))}
            </div>
          )}
        </section>
      </main>
    </div>
  )
}
